### ISSUE TITLE
Like all posts liked by specific user

### ISSUE THREAD

**Issue by dieselp** [instabot-py/instabot.py#1000]
- [x] I have searched for other issues with the same problem.

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC

## Python Version?
2

## Description

Hi, Is it possible to configure bot to like all posts liked by specific user? If so, how to do that? ;)

Greets :)

**Comment by sionking** [comment]
It is not passavle to see this info onlt if you follow him I think

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
