### ISSUE TITLE
Dont skip it : "Trying to unfollow"

### ISSUE THREAD

**Issue by brunomosciatti** [instabot-py/instabot.py#1001]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Mac Os Sierra
## Python Version?
3

## Description
I've unfollowed by my own some users and now the instabot keep trying to unfollow and dont skip it:
28.02.2018_14:05 Trying to unfollow #1: 
28.02.2018_14:09 Trying to unfollow #1: 
28.02.2018_14:14 Trying to unfollow #1:

**Comment by brunomosciatti** [comment]
Wheres the support?

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
