### ISSUE TITLE
Bot run time issue?

### ISSUE THREAD

**Issue by MarrenDartin** [instabot-py/instabot.py#1002]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC v10.13.3

## Python Version?
2 /3

## Description

When I run the bot it only runs for a few seconds and then logs out without following/liking/commenting on anything and I get a traceback as seen below. Any help would be appreciated. Thanks.

```
01.03.2018_14:12 ======> Get media id by Tag <======
01.03.2018_14:12 Get media by user success!
01.03.2018_14:12 Current Index = 17 of 33 medias
Traceback (most recent call last):
  File "example.py", line 86, in <module>
    feed_scanner(bot)
  File "/home/marren1113/instabot.py/src/feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "/home/marren1113/instabot.py/src/likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "/home/marren1113/instabot.py/src/likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
01.03.2018_14:12 Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
01.03.2018_14:12 Bot work time: 0:00:11.402849
01.03.2018_14:12 Logout success!
```

**Comment by pggmrt** [comment]
Same here, I have been using it for some days and it worked flawlessly for 5 days straight. However, since yesterday after a couple hours working it logs out automatically in a similar fashion.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
