### ISSUE TITLE
tag_blacklist not working

### ISSUE THREAD

**Issue by animetrk** [instabot-py/instabot.py#1003]
- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 10

## Python Version?
3

## Description

Hi, thank you for your great work! I have an issue about the tag_blacklist, no matter how much I forbid hashtags with that list, bot doesn't mind it and likes all the pictures with or without blacklisted hashtags. It seems like tag_blacklist has no function. I am using the bot with the mode 0 and unfollow 0. I have no problems other than that. Thanks in advance!

**Comment by mactrash** [comment]
@animetrk yes it act same as my test.

**Comment by spud-dog** [comment]
Similar to the example above I'm finding the bot is ignoring the tag_blacklist in some instances, tried to find a common denominator between instances that this is happening, looking back through my liked media... but have not been able to so far

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
