### ISSUE TITLE
Stories at instagram

### ISSUE THREAD

**Issue by MatheusParanhos** [instabot-py/instabot.py#1004]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Python Version?
2 / 3

## Description

Type the description of your issue here.

Hi I would like to debate a bit on how we would add the functionality of looking at people's stories with a given hashtag. Is this doable? Because I can't seem to find hashtagging stories on the web. If it isn't,
is it possible by querying at their API? 
Is it possible by querying at their API at all? 

Thanks

```
Include the contents of the error.log here (if applicable).
```

**Comment by KalanaPerera** [comment]
good idea tho

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
