### ISSUE TITLE
sqlite3.OperationalError : database is locked

### ISSUE THREAD

**Issue by alex30020** [instabot-py/instabot.py#1006]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [X] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
Windows/Android

## Python Version?
 3

## Description

Type the description of your issue here.

I am getting this error after a while of running 2 or 3 accounts at the same time, sometimes also with just 1 account.
```
Include the contents of the error.log here (if applicable).
```
![error](https://user-images.githubusercontent.com/35959716/37052431-f2ff490a-2181-11e8-9dcc-b4e5254faf6c.jpg)

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
