### ISSUE TITLE
Removing already liked medias..

### ISSUE THREAD

**Issue by tadbeavers** [instabot-py/instabot.py#1008]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Windows

## Python Version?
2.7.6

## Description

Type the description of your issue here.
```
Tried using a customized version, tried a new VM instance, have tried reinstalling, have tried stock example.py. Whenever bot logs in, I get "Login error! Connection error! Removing already liked medias.."

Then, I just receive an endless stream of "Removing already likes medias..." with a "Trying to unfollow #1:"  "Looks like there is nobody to unfollow." thrown in every so often. 

What am I doing wrong? How can I fix this? Would prefer to stay on the cloud.  Log in information is all accurate and I'm logged out of my browser. 


Include the contents of the error.log here (if applicable).
```
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com

**Comment by kaburah10** [comment]
I had the same issue, but it turned out it was a typo in my pw. So make sure you have the correct login and pw.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
