### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jaybak** [instabot-py/instabot.py#1009]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Linux

## Python Version?
3

## Description

Type the description of your issue here.

I've installed the bot on both a ras pi and a linux laptop.  I get the same error on both when I run example.py

What am I missing?

Include the contents of the error.log here (if applicable).

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/home/jay/Documents/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/jay/Documents/instabot.py-master/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/home/jay/Documents/instabot.py-master/src/userinfo.py", line 5, in <module>
    import requests
ImportError: No module named requests

**Comment by saphuttu** [comment]
pip3 install requests

**Comment by benipla** [comment]
@jaybak 

sudo python -m pip install requests

**Comment by jcalvo-ixxus** [comment]
Same here, your solution doesn't seem to be working for me: @benipla @saphuttu
