### ISSUE TITLE
ImportError: No module named fake_useragent

### ISSUE THREAD

**Issue by Nikeless** [instabot-py/instabot.py#1010]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Linux

## Python Version?
2.7.6

## Description

Type the description of your issue here.

If I want to run the script on the Cloud9 Server I'm getting this kind of error.

Traceback (most recent call last):
  File "/home/ubuntu/workspace/example.py", line 6, in <module>
    from src import InstaBot
  File "/home/ubuntu/workspace/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/ubuntu/workspace/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ImportError: No module named fake_useragent

Process exited with code: 0

Include the contents of the error.log here (if applicable).
```

**Comment by saphuttu** [comment]
pip install fake_useragent

**Comment by Nikeless** [comment]
![screenshot_15](https://user-images.githubusercontent.com/26581443/37245383-92a5a43c-2497-11e8-9bb3-ebf9b4843299.png)

Getting this kind of error

**Comment by ri7nz** [comment]
@Nikeless  
```python
pip install fake_useragent --user
````

**Comment by Nikeless** [comment]
Thank you!

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
