### ISSUE TITLE
Run Bot 24/7

### ISSUE THREAD

**Issue by Botnewbie8754** [instabot-py/instabot.py#1012]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
 Windows 8.1

## Python Version?
 3

## Description

Type the description of your issue here.
Hallo,
I am trying to run the bot 24/7 but i get louged out after a few hours, i tried to read throw other Post but none of them helped me to solve the problem. I want to increase the number of peopley i follow/like per dayy so the bot runs 24/7. I will risk a ban. So can somewone please help me how to rewrite the eyample.py or how to solve this problem. I am really bad in informatics and cant understand everything so easy like most of the members here. So sry if i ask the wuestion again. But i read throw all other Post and none helped me or i couldnt understand how to do it :(.
Regard
```
Include the contents of the error.log here (if applicable).
```

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
