### ISSUE TITLE
Can's Login

### ISSUE THREAD

**Issue by EightShift** [instabot-py/instabot.py#1013]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [+] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [+] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Python Version?
3

## Description

About two weeks I can't login any account ...
About a minute there is a message about the logging, and then the window closes.

![cccc](https://user-images.githubusercontent.com/35277031/37194131-f74e7528-2396-11e8-8ca2-8fc06b5b7cc7.PNG)

**Comment by qnagr** [comment]
Maybe IG banned you?

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
