### ISSUE TITLE
Bot not liking or following anyone

### ISSUE THREAD

**Issue by qnagr** [instabot-py/instabot.py#1014]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Linux

## Python Version?
2

## Description
I put in my username and password in example.py and set a like and follow number but no unfollow number but it say Trying to like media: number and then Not liked: 400. It then gets stuck on Trying to follow. Thanks. Edit: Also, it gets stuck on following one person. Why is this? And now it's saying Already followed before [number] with the same number repeatedly.

```

```

**Comment by creeptosis** [comment]
normally when it says not liked, it could mean that instagram temporarily blocked you for liking too many photos in a short amount of time. Take a break for 1-2 days and gradually ramp up

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
