### ISSUE TITLE
INSTABOT - Looks like there is nobody to unfollow ISSUE

### ISSUE THREAD

**Issue by afesk87** [instabot-py/instabot.py#1015]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC

## Python Version?
2

## Description

Type the description of your issue here.
Hi, I'm having trouble with Instabot.
It always gives me the "Looks like there is nobody to unfollow" error and doesn't start following.
How can I fix it?

I already searched an answer, but no one of the solutions I read actually works.

Thanks
```
Include the contents of the error.log here (if applicable).
```

**Comment by afesk87** [comment]
It doesn't work with Python 3.6.4 too

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
