### ISSUE TITLE
Login error! [Solved]

### ISSUE THREAD

**Issue by regoautomatic** [instabot-py/instabot.py#1016]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Windows 10
## Python Version?
2 / 3
3.6.1

## Description
I have the following error when I try to log in.
![captura](https://user-images.githubusercontent.com/37348259/37365988-6b75b31a-26ff-11e8-8979-245120f45433.PNG)

**Comment by thenextleveluk** [comment]
Exactly the same here.

**Comment by regoautomatic** [comment]
Solved with #1017

**Comment by thenextleveluk** [comment]
Thank you
