### ISSUE TITLE
There is an issue on line 42 in userinfo.py. Key 'user' cannot be found.

### ISSUE THREAD

**Issue by petermirmo** [instabot-py/instabot.py#1017]
Instagram changed their api and 'user' is now in 'graphql' in all_data. So on line 42 in userinfo.py you got to change it to id_user = all_data['graphql']['user']['id'].

**Comment by sunny127** [comment]
Thank you so much!!!!!!! :) :) :) :) :) I would have never find it out by myself!! :) Thank you!!!!!!

**Comment by petermirmo** [comment]
No problem! :)

**Comment by renanlaudencia** [comment]
instabot.py-master\src\instabot.py", line 848, in auto_unfollow
    user_info = all_data['user']
KeyError: 'user'

Should i change it too?

**Comment by petermirmo** [comment]
Yes, just change it to 
user_info = all_data['graphql']['user']

**Comment by renanlaudencia** [comment]
And how about in this line?

instabot.py-master\src\instabot.py", line 853, in auto_unfollow
    follows = user_info['follows']['count']
KeyError: 'follows'

**Comment by petermirmo** [comment]
I haven't tested this one, but I would just try it! I bet it is the same problem!

**Comment by DubDubDan** [comment]
Works a charm, thank you 🙌🏼

**Comment by brodyxD** [comment]
this fixed my login problem but the unfollowing doesn't seem to work any more, I tried the above fixes but it just gets stuck at 

13.03.2018_19:19 Getting user info :

**Comment by petermirmo** [comment]
@brodyxD Do you see any errors? How long did you wait for?

**Comment by renanlaudencia** [comment]
@petermirmo I think we have the same problem. I got that problem at first then you told me to just do the same thing then another error raised, the line that I was asking for my last comment.

**Comment by Rafoo1381** [comment]
I'm experiencing the same thing. It looks like the structure of the data in the url used to pull user info changed. I tried to fix it on mine by putting the correct data, and it goes passed the first issue, but it does not go past follows = user_info['follows']['count']. I've tried to use follows = user_info['graphql']['user']['edge_follow']['count'] which corresponds to the structure in the url, but I still can't go past that. I think this is the right thing to test but can't figure my mistake.

**Comment by Rafoo1381** [comment]
Nevermind, I've fixed some of it. I'm stuck a little further though, working on it
Use the following
                    r = self.s.get(url_tag)
                    all_data = json.loads(r.text)
                    user_info = all_data['graphql']['user']
                    i = 0
                    log_string = "Checking user info.."
                    self.write_log(log_string)
                    follows = user_info['edge_follow']['count']
                    follower = user_info['edge_followed_by']['count']
                    media = user_info['edge_owner_to_timeline_media']['count']
                    follow_viewer = user_info['follows_viewer']
                    followed_by_viewer = user_info['followed_by_viewer']
                    requested_by_viewer = user_info['requested_by_viewer']
                    has_requested_viewer = user_info['has_requested_viewer']

**Comment by sunny127** [comment]
@petermirmo , you fix worked great for an hour, but now I get "Login error! Connection error!". Nothing works again :(

**Comment by KalanaPerera** [comment]
@petermirmo Thanks, bro.

**Comment by xthedevistatorx** [comment]
I am completely new to this, so hopefully someone is willing to explain a bit. I do not have the userinfo.py file in the Instabot folder. Where do I go to edit this correctly?

**Comment by jandeman120** [comment]
@sunny127  i have the same problem.

**Comment by jandeman120** [comment]
the bot is not unfollowing anymore... somebody now how to fix it?

**Comment by jandeman120** [comment]
The bot is not unfollowing anymore... it unfollows one person and then it unfollows nobody

r = self.s.get(url_tag)
                    all_data = json.loads(r.text)

                    user_info = all_data['graphql']['user']
                    i = 0
                    log_string = "Checking user info.."
                    self.write_log(log_string)

                    follows = user_info['edge_follow']['count']
                    follower = user_info['edge_followed_by']['count']
                    media = user_info['edge_owner_to_timeline_media']['count']
                    follow_viewer = user_info['follows_viewer']
                    followed_by_viewer = user_info[
                        'followed_by_viewer']
                    requested_by_viewer = user_info[
                        'requested_by_viewer']
                    has_requested_viewer = user_info[
                        'has_requested_viewer']

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
