### ISSUE TITLE
Issues with initial set-up (please see description)

### ISSUE THREAD

**Issue by flextmd** [instabot-py/instabot.py#1019]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [X] I have searched for other issues with the same problem.
- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 8.1

## Python Version?
3

## Description

I changed my username and password to add my account, as well as my tags, but when I go to run it I get an error (See attached). Thank you for your help in advanced :) Looking forward to contributing while I'm here - glad I found this place!
![instabot issue](https://user-images.githubusercontent.com/37355893/37380633-85ea58c4-2707-11e8-9c73-919a89cb9223.png)

```
Include the contents of the error.log here (if applicable).
```

**Comment by porsamini** [comment]
@flextmd This is currently known issue. See https://github.com/instabot-py/instabot.py/issues/1017

**Comment by flextmd** [comment]
Porsamini, 

Thank you so much! I guess I didn't know the specific problem to search. Fixed. You are the best! Thank you!

**Comment by qwertyuiuytrewq** [comment]
Thank you @porsamini

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
