### ISSUE TITLE
Issue with my Location

### ISSUE THREAD

**Issue by Nikeless** [instabot-py/instabot.py#1021]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Linux

## Python Version?
2.7

## Description

I'm running my python script on Cloud9 Webhosting. There Servers are anywhere in canada and I live in german. So if I'm trying to login with my bot I get a login error.
Is there a way to change my ip/proxy? Or any other solution for it?

```
Include the contents of the error.log here (if applicable).
```

**Comment by andrewsegas** [comment]
https://github.com/andrewsegas/instaboost

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
