### ISSUE TITLE
Bot not unfollowing

### ISSUE THREAD

**Issue by frextrem** [instabot-py/instabot.py#1025]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC 

## Python Version?
3

## Description

Yesterday I had the error "Key error: user". After I solved this, I got a new one. The bot doesn't unfollow anymore. 
Can anyone help me please?

```
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "/Users/alexwerner/Desktop/instabot.py-master/src/instabot.py", line 853, in auto_unfollow
    follows = user_info['follows']['count']
KeyError: 'follows'

```

**Comment by andrewsegas** [comment]
I have the same problem, return of request is always 400, i coudn't understand what instagran changed

**Comment by frextrem** [comment]
hello, @andrewsegas.  do you still have the same problem? or have you find a solution?

best regards

**Comment by andrewsegas** [comment]
@frextrem i found and fixed in my project https://github.com/andrewsegas/instaboost
this project has some changes, you can check

i tried to fix here but this prokect is off

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
