### ISSUE TITLE
Login error! Connection error! user info list is empty!

### ISSUE THREAD

**Issue by zhmrab** [instabot-py/instabot.py#1026]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Linux, Ubuntu 16.04
## Python Version?
2 / 3
2.7
## Description

Type the description of your issue here.
trying to log in and the bot goes `Login error! Connection error! user info list is empty!` also getting a warning on instagram,
```
14.03.2018_10:54 Login error! Connection error!
14.03.2018_10:54 Removing already liked medias..
xxxxxxx user info list is empty!!! xxxxxxxxx
```

**Comment by andrewsegas** [comment]
Instagran changed their JSON tags again, the instabot.py must be updated

**Comment by marcguilera** [comment]
I sent a PR for this 👍 

#1028

**Comment by zhmrab** [comment]
Fix isnt working for me, still getting 

```
14.03.2018_19:45 Login error! Connection error!
14.03.2018_19:45 Removing already liked medias..
xxxxxxx user info list is empty!!! xxxxxxxxx
^CTraceback (most recent call last):
  File "example.py", line 94, in <module>
    bot.new_auto_mod()
  File "/root/instabot.py/src/instabot.py", line 699, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "/root/instabot.py/src/instabot.py", line 764, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "/root/instabot.py/src/unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "/root/instabot.py/src/follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "/root/instabot.py/src/feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "/root/instabot.py/src/likers_graber_protocol.py", line 28, in likers_graber_protocol
    time.sleep(random.randint(13, 35))
```

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by UltraSon1c** [comment]
does not work for me neither
