### ISSUE TITLE
Instagram change API?

### ISSUE THREAD

**Issue by Koldrish** [instabot-py/instabot.py#1027]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows

## Python Version?
3

## Description
  File "C:\instabot.py\src\instabot.py", line 231, in __init__
    self.login()
  File "C:\instabot.py\src\instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\instabot.py\src\userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'

**Comment by andrewsegas** [comment]
to fix login you just need to change the file user_info.py for this
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import datetime
import json
import random
import time


def get_user_info(self, username):
    if self.login_status:
        now_time = datetime.datetime.now()
        log_string = "%s : Get user info \n%s" % (
            self.user_login, now_time.strftime("%d.%m.%Y %H:%M"))
        self.write_log(log_string)
        if self.login_status == 1:
            url = 'https://www.instagram.com/%s/?__a=1' % (username)
            try:
                r = self.s.get(url)

                user_info = json.loads(r.text)

                log_string = "Checking user info.."
                self.write_log(log_string)

                follows = user_info['graphql']['user']['edge_follow']['count']
                follower = user_info['graphql']['user']['edge_followed_by']['count']
                if self.is_self_checking is not False:
                    self.self_following = follows
                    self.self_follower = follower
                    self.is_self_checking = False
                    self.is_checked = True
                    return 0
                media = user_info['graphql']['user']['edge_owner_to_timeline_media']['count']
                follow_viewer = user_info['graphql']['user']['follows_viewer']
                followed_by_viewer = user_info['graphql']['user']['followed_by_viewer']
                requested_by_viewer = user_info['graphql']['user'][
                    'requested_by_viewer']
                has_requested_viewer = user_info['graphql']['user'][
                    'has_requested_viewer']
                log_string = "Follower : %i" % (follower)
                self.write_log(log_string)
                log_string = "Following : %s" % (follows)
                self.write_log(log_string)
                log_string = "Media : %i" % (media)
                self.write_log(log_string)

                if follows == 0 or follower / follows > 2:
                    self.is_selebgram = True
                    self.is_fake_account = False
                    print('   >>>This is probably Selebgram account')
                elif follower == 0 or follows / follower > 2:
                    self.is_fake_account = True
                    self.is_selebgram = False
                    print('   >>>This is probably Fake account')
                else:
                    self.is_selebgram = False
                    self.is_fake_account = False
                    print('   >>>This is a normal account')

                if media > 0 and follows / media < 10 and follower / media < 10:
                    self.is_active_user = True
                    print('   >>>This user is active')
                else:
                    self.is_active_user = False
                    print('   >>>This user is passive')

                if follow_viewer or has_requested_viewer:
                    self.is_follower = True
                    print("   >>>This account is following you")
                else:
                    self.is_follower = False
                    print('   >>>This account is NOT following you')

                if followed_by_viewer or requested_by_viewer:
                    self.is_following = True
                    print('   >>>You are following this account')
                else:
                    self.is_following = False
                    print('   >>>You are NOT following this account')
                    self.is_checked = True
            except:
                self.media_on_feed = []
                self.write_log("Except on get_info!")
                time.sleep(20)
                return 0
        else:
            return 0

**Comment by olivierognn** [comment]
andrewsegas  it seems doesn't work

**Comment by Koldrish** [comment]
> andrewsegas it seems doesn't work

**Comment by marcguilera** [comment]
You need to change user_info.py and userinfo.py

Check PR: #1029

**Comment by andrewsegas** [comment]
@marcguilera , did you get to solve the problem with follow and unfollow? I tried to understand what is going by inspector in my browser but I didn't get . Instagran is just returning status = 400 by bot

**Comment by Nikeless** [comment]
14.03.2018_13:26 Instabot v1.2.0 started at 14.03.2018 13:26:

14.03.2018_13:26 Trying to login as xxx...

14.03.2018_13:26 Login error! Connection error!
14.03.2018_13:26 Removing already liked medias..


Process exited with code: 1
14.03.2018_13:26 Removing already liked medias..


//Still getting this error

**Comment by joilson-cisne** [comment]
@Nikeless Did you try the PR: #1029?

**Comment by Nikeless** [comment]
@joilson-csine yeha I did

**Comment by sunny127** [comment]
@andrewsegas , I replaced the code in user_info.py with your code from this thread, and this didn't help.
I get "Login error! Connection error!".  :( And then when I get into Instagram web site, I get a warning "We detected a suspicious login attempt" :(

**Comment by marcguilera** [comment]
They also changed the schema in get_media looks like. Can anybody take a look?

**Comment by andrewsegas** [comment]
I didn't see any changes in get_media, I don't know wich module you're using @sunny127 .
I created one fork with User interface if you want it's in my git
https://github.com/andrewsegas/instaboost
just need double click in .exe and i also created one way to get media by location.

**Comment by marioaugustorama** [comment]
Not only this file, on instabot.py i get this traceback:

Traceback (most recent call last):
  File "/instabot/src/instabot.py", line 853, in auto_unfollow
    follows = user_info['follows']['count']

**Comment by williamwashere** [comment]
The fix is on #1030 - it's working now.

**Comment by ajose19** [comment]
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/eudym/Downloads/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/eudym/Downloads/instabot.py-master/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/Users/eudym/Downloads/instabot.py-master/src/userinfo.py", line 5, in <module>
    import requests
ImportError: No module named requests

**Comment by manguszta** [comment]
The bot doesn't do unfollows.
```
Trying to unfollow #1:
Except on get info of [user]
```

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
