### ISSUE TITLE
Help with systemctl (fake_useragent)

### ISSUE THREAD

**Issue by Obsessi0n** [instabot-py/instabot.py#1031]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Linux

## Python Version?
2.7

## Description

I would be thankful if someone could help me with this.
If I run the script like "sudo python example.py" it works fine but if i try to start it with systemctl it allways fails giving the error on the screenshot atached.
fake_useragent is installed.

```

```
![screenshot_14](https://user-images.githubusercontent.com/23345523/37425645-f9c0ba54-27bb-11e8-8a89-b184cdeea3ec.png)

**Comment by userevolution** [comment]
try: 
pip install --upgrade pip
pip install requests
pip install fake-useragent

**Comment by Obsessi0n** [comment]
I just reinstalled everything and now it works fine.
