### ISSUE TITLE
Bot fails to login and gives error about unfollow_whitelist

### ISSUE THREAD

**Issue by 1993henkpiet** [instabot-py/instabot.py#1032]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 7

## Python Version?
3

## Description

After running the bot, it tries to login for quite a few seconds and eventually gives me the following error message:

Traceback (most recent call last):
  File "C:\Users\Bart\Desktop\instabot.py-master\primeshock_bot.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\Bart\Desktop\instabot.py-master\src\instabot.py", line 231, in __init__
    self.login()
  File "C:\Users\Bart\Desktop\instabot.py-master\src\instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\Bart\Desktop\instabot.py-master\src\userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'
>>> 

Leaving the unfollow_whitelist blank or deleting the row entirely keeps giving similar errors. From what I've read in other topics, I think the original code needs to be updated to work again. I believe Instagram has changed things up on their end, which is why the bot doesn't work anymore.

Can somebody help me to get it to work again, please?

```
Include the contents of the error.log here (if applicable).
```

**Comment by stegzy176** [comment]
i have got this issue to on my rasberry pi

**Comment by mmming** [comment]
just got the same issue

**Comment by 1993henkpiet** [comment]
Awesome, that fix worked!

**Comment by stegzy176** [comment]
for some reason im having troubles changing those files is there somewhere i can download the updated files please?

**Comment by userevolution** [comment]
Awesome, it works 👍

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
