### ISSUE TITLE
KeyError: 'user' when trying to log in

### ISSUE THREAD

**Issue by mofukotan** [instabot-py/instabot.py#1034]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MacOS High sierra 10.13.3

## Python Version?
3

## Description

Type the description of your issue here.
I've already run it and it worked flawlessly but now I tried multiple time reinstalling the whole thing but I keep getting error messages, it's really weird since it worked before and it stopped all of a sudden.
```
Include the contents of the error.log here (if applicable).
```
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/oof/Desktop/instabot.py-master/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/oof/Desktop/instabot.py-master/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/oof/Desktop/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'

**Comment by MattPorto** [comment]
same problem here

**Comment by Glen-Cocoa** [comment]
here too

**Comment by canceroyer** [comment]
I have the same problem, have tried everything to solve it and not working also tried running it on  bluestacks on qpython it gives me the same error

**Comment by canceroyer** [comment]
I also had another account running on another computer logged out and now Im not able to log in, I think there must be an error related with the instabot and not with the computer

**Comment by enriqueg** [comment]
same here

**Comment by enriqueg** [comment]
line 42 in userinfo.py change to 

id_user = all_data['graphql'] ['user']['id']

**Comment by biggerry** [comment]
Good morning,
i change the line but always same error.

**Comment by enriqueg** [comment]
the complete fix here:

https://github.com/instabot-py/instabot.py/pull/1030/commits/38c46365407781e6be745dec83a4781ba0763cdb

**Comment by sunny127** [comment]
@enriqueg Thank you! It works! :) :)

**Comment by mofukotan** [comment]
It's nice but now I keep getting the same message over over and over 

15.03.2018_19:04 Instabot v1.2.0 started at 15.03.2018 19:04:

15.03.2018_19:04 Trying to login as account...

15.03.2018_19:05 account login success!
15.03.2018_19:05 Get media id by tag: furryoc
15.03.2018_19:05 Removing already liked medias..
15.03.2018_19:05 Trying to like media: 1735742151662617864
15.03.2018_19:05 Liked: 1735742151662617864. Like #1.
15.03.2018_19:05 Keep calm - It's your own profile ;)
15.03.2018_19:05 Trying to unfollow #1: 
15.03.2018_19:05 Getting user info : july97chan
15.03.2018_19:05 Keep calm - It's your own profile ;)
15.03.2018_19:05 Keep calm - It's your own profile ;)
15.03.2018_19:05 Keep calm - It's your own profile ;)
15.03.2018_19:05 Keep calm - It's your own profile ;)
15.03.2018_19:05 Keep calm - It's your own profile ;)
15.03.2018_19:05 Keep calm - It's your own profile ;)
15.03.2018_19:05 Keep calm - It's your own profile ;)

**Comment by tanmaybarave** [comment]
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/data/data/com.termux/files/home/instabot.py/src/instabot.py", line 231, in __init__
    self.login()
  File "/data/data/com.termux/files/home/instabot.py/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/data/data/com.termux/files/home/instabot.py/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'

**Comment by villefilho** [comment]
Hi everybody, I got this same error, fixed changing as follows:

open instabot.py/src/userinfo.py, on line 42:
change:
 id_user = all_data['user']['id']
to:
 id_user = all_data['graphql']['user']['id']

Instagram might have changed things a bit...

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
