### ISSUE TITLE
Unfollow not working. 

### ISSUE THREAD

**Issue by qwertyuiuytrewq** [instabot-py/instabot.py#1036]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Windows 10
## Python Version?
2 / 3
3
## Description

Type the description of your issue here.
Bot functioning nicely, but not unfollowing. Others have has this problem. Cannot find a solution.
```
Include the contents of the error.log here (if applicable).
```

14.03.2018_22:17 Liked: 1735258813595405534. Like #131.
14.03.2018_22:17 Trying to comment: 1735258664586092565
14.03.2018_22:17 Trying to unfollow #1:
14.03.2018_22:17 Getting user info : plutosrd
14.03.2018_22:17 Trying to like media: 1735258645286092565
14.03.2018_22:17 Liked: 1735258668245092565. Like #132.
14.03.2018_22:18 Trying to like media: 1735258604572519304
14.03.2018_22:18 Liked: 1735258604572519304. Like #133.
14.03.2018_22:18 Trying to unfollow #1:
14.03.2018_22:18 Getting user info : raising.son
14.03.2018_22:18 Trying to like media: 1735258543114571909
14.03.2018_22:18 Liked: 1735258543114571909. Like #134.
14.03.2018_22:18 Trying to unfollow #1:

**Comment by andrewsegas** [comment]
Here the bug is fixed
https://github.com/andrewsegas/instaboost

I'll fix this bug here in instabot-py too

**Comment by andrewsegas** [comment]
Here it is, this PR fix this bug https://github.com/instabot-py/instabot.py/pull/1038

**Comment by Christopharo** [comment]
@andrewsegas im using your instaboost and its unfollowing perfectly but its not commenting. Im running example.py in command prompt and i would like to continue using it this way and not the .exe.

**Comment by andrewsegas** [comment]
@Christopharo good, i understand, please don't mix the project, write about instaboost there.
if you run example.py comments is working

**Comment by josuegonzalezm** [comment]
i did what you said:
pip3 install pyqt5
pip install -r requirements.txt
python instaboost.py

but now  it does not want to let me connect, it says:
"login error, connection error"
but i have internet and its working, help me please

@andrewsegas

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
