### ISSUE TITLE
Understanding Follow/unfollow Algorithm 

### ISSUE THREAD

**Issue by jiweiyang93** [instabot-py/instabot.py#1037]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC 

## Python Version?
2 

## Description

Type the description of your issue here.
Can someone help me understand the Folllow_time and the Min/ max break? Sorry if this question seems simple, I am new to coding and python.  Is the follow time 5x60x60 as stated in the instabot.py or 1x60 in the example.py? 
What is the break, is there supposed to be a break between unfollows other than the follow time? 

I changed the parameters a little bit and was wondering if my change means there is going to be unfollowing every 3 minutes. 

I am using mode 0

Thanks for your help! 
```
Include the contents of the error.log here (if applicable).
```    
    follow_per_day=600,
    follow_time=3 * 60,
    unfollow_per_day=600,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,

**Comment by golddigger1080p** [comment]
check out the README file.

**Comment by andrewsegas** [comment]
@jiweiyang93 The number in instabot.py is default but if you fill the example.py this number will be the one.
if you need interface or like by location tags here it is
https://github.com/andrewsegas/instaboost

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
