### ISSUE TITLE
example.py quickly opens but window closes immediately

### ISSUE THREAD

**Issue by instabot-master** [instabot-py/instabot.py#1040]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
**- [ x] If so; have you tried running the code on your local machine?**

#### Select one:
**- [x ] Bug**
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / **Windows** / Linux / Android

## Python Version?
2 / **3**

## Description

Type the description of your issue here.

Since two days the example.py (when opening it) closes immediately. I would like to keep using this code of instabot.py and not like to switch to another provider as it worked fine before. All entered user data are correct and my insta account is also activated.
Do you know how to fix this issue? I am running on python 3.6.3

Thanks

**Comment by andrewsegas** [comment]
open in your prompt and send here the error

**Comment by instabot-master** [comment]
found fix here.
https://github.com/instabot-py/instabot.py/commit/38c46365407781e6be745dec83a4781ba0763cdb
