### ISSUE TITLE
Error after fixing [key] issue

### ISSUE THREAD

**Issue by Glen-Cocoa** [instabot-py/instabot.py#1041]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Ubuntu 16.something
## Python Version?
2 / 3
3
## Description

Type the description of your issue here.
after cloning commit 38c4636 i am receiving a new error
```
Include the contents of the error.log here (if applicable).
```
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/home/lnt/Desktop/updated/instabot.py/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/lnt/Desktop/updated/instabot.py/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'

**Comment by Glen-Cocoa** [comment]
I may have figured it out, installing pip to get the requirements now x)

**Comment by Glen-Cocoa** [comment]
nope still broken :(

**Comment by CazGirl** [comment]
Same issue :(

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
