### ISSUE TITLE
KeyError: 'user'

### ISSUE THREAD

**Issue by yourash** [instabot-py/instabot.py#1042]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
ubuntu-server 16.04
## Python Version?
2 / 3
python3
## Description

  File "naidoff.py", line 45, in <module>
    unfollow_whitelist=[])
  File "/root/instabot.py/src/instabot.py", line 231, in __init__
    self.login()
  File "/root/instabot.py/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/root/instabot.py/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'

Type the description of your issue here.

```
Include the contents of the error.log here (if applicable).
```

**Comment by andrewsegas** [comment]
Please, check previous issue before.
https://github.com/instabot-py/instabot.py/pull/1030

this project instabot must be updated
Here i have project updated and with user interface and tags by location
https://github.com/andrewsegas/instaboost

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
