### ISSUE TITLE
id_user = all_data['user']['id'] KeyError: 'user'

### ISSUE THREAD

**Issue by somoza** [instabot-py/instabot.py#1043]
Today the script stop working in the file src/userinfo.py line 42. Maybe IG make some changes?

**Comment by andrewsegas** [comment]
Please, check previous issue before.
#1030

this project instabot must be updated
Here i have project updated and with user interface and tags by location
https://github.com/andrewsegas/instaboost

**Comment by somoza** [comment]
Cool, I will check it.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
