### ISSUE TITLE
Login error! Check you login data!

### ISSUE THREAD

**Issue by ColeShelly** [instabot-py/instabot.py#1045]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Python Version?
2 / 3

## Description

Type the description of your issue here.

```
Include the contents of the error.log here (if applicable).
```

I've installed the requirements.txt and did nano example.py.. Help!

**Comment by andrewsegas** [comment]
Check previous issue, and make the merge. Or use this one that is already updated 
https://github.com/andrewsegas/instaboost

**Comment by ColeShelly** [comment]
Thank you!

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
