### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by WinkWink** [instabot-py/instabot.py#1046]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Python Version?
2 / 3

## Description

Type the description of your issue here.

```
Include the contents of the error.log here (if applicable).
```

Having issues, it came out of the blue 

My bot has been working fine up until now. 
![screen shot 2018-03-15 at 1 25 45 pm](https://user-images.githubusercontent.com/12740229/37480050-9b3ba068-2854-11e8-8a4f-3e64bcdad671.png)

**Comment by pedrozan** [comment]
The same thing is happening with me. I am using a Cloud9 instance with plain Ubuntu.

I tried with two accounts, one gives the exact same error you had and the other gives this message:

```
15.03.2018_20:02 Trying to login as posterando_decors...

Traceback (most recent call last):
  File "example.py", line 55, in <module>
    unfollow_whitelist=['example_user_2'])
  File "/home/ubuntu/workspace/instabot.py/src/instabot.py", line 231, in __init__
    self.login()
  File "/home/ubuntu/workspace/instabot.py/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/home/ubuntu/workspace/instabot.py/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user' 
```

**Comment by WinkWink** [comment]
Yea, originally I had the error that I posted, but now I am getting the same error that you posted. Let me know if you find a fix, I am going to keep looking into it.

**Comment by pedrozan** [comment]
This pull request has the fix https://github.com/instabot-py/instabot.py/pull/1030 I don't know why it is not merged yet

**Comment by andrewsegas** [comment]
@pedrozan i don't know why too, here is 2 months without update, I created my project with User Interface and tags by location if you want to check: https://github.com/andrewsegas/instaboost
all this bugs are already fixed

**Comment by limerick11** [comment]
@pedrozan suspect login attempt was my issue too. But I didn't manage to get it to work. It requests for a security code every time I try to log in via browser on the same IP as the bot. Is there a way for the bot to input the code?

**Comment by zhmrab** [comment]
Same problem here.. 

```
7.03.2018_02:43 Login error! Connection error!
17.03.2018_02:43 Removing already liked medias..
xxxxxxx user info list is empty!!! xxxxxxxxx


```

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
