### ISSUE TITLE
KeyError: 'user'

### ISSUE THREAD

**Issue by Azerafa** [instabot-py/instabot.py#1047]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
MacOS Sierra version 10.12.6
## Python Version?
2 / 3
2
## Description
Caveat I'm relatively new to python so this may be an easy fix. I got the bot running just fine on my local machine, but now the module is returning an error that reads; KeyError: 'user'

Above the keyerror the following code appears (I took my username out) 

afa'])
  File "/Users/username/Desktop/instabot.py-master/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/usrname/Desktop/instabot.py-master/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/username/Desktop/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']

I haven't made any significant changes to the source code so I'm not sure why this is happening... 

I've also gotten the below error a few times, not sure if its related to this issue 

ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /web/friendships/46904664/unfollow/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x102b623d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

```
Include the contents of the error.log here (if applicable).
```
KeyError: 'user'

and

ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /web/friendships/46904664/unfollow/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x102b623d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

**Comment by andrewsegas** [comment]
github.com/andrewsegas/instaboost

**Comment by Azerafa** [comment]
Whoops, someone answered this very recently and I missed it! https://github.com/instabot-py/instabot.py/issues/1017
