### ISSUE TITLE
Having trouble logging in recently? Quick Fix - Download and Replace these two source files

### ISSUE THREAD

**Issue by Follygon** [instabot-py/instabot.py#1048]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x ] I have searched for other issues with the same problem.

## Hosting
- [x ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Python Version?
2 / 3

## Description

The two files are attached. 
[srcfiles.zip](https://github.com/instabot-py/instabot.py/files/1817408/srcfiles.zip)

**Comment by alessandro893** [comment]
Thank you!

**Comment by rosie-dmt** [comment]
Thank you very much! :)

**Comment by uselessrob** [comment]
This is closer than other fixes I've tried, but I'm still getting an except on get_media with these changes. Any ideas?

**Comment by dimaregabriele** [comment]
I changed the two files but it does not work for me yet..

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by issamarmas** [comment]
great works
