### ISSUE TITLE
(**fix needed**) example.py fails to unfollow accounts

### ISSUE THREAD

**Issue by instabot-master** [instabot-py/instabot.py#1049]
- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / **Windows** / Linux / Android

## Python Version?
2 / **3**

## Description

Hi Team,
so I feel like for a longer time the instabot is not proberly unfollowing previously liked accounts. Since I fixed the bug with not being able to login (working now), the bot is not unfollowing at all anymore. Means I am following people but the unfollow misses. Please see the output below. Do you have any idea how to fix that? PS: I do not want to use a different bot. Thanks :)
```
**16.03.2018_10:06 Trying to unfollow #1:**
16.03.2018_10:06 Getting user info : xx
16.03.2018_10:07 Trying to follow: xx
16.03.2018_10:07 Followed: xx #645.
16.03.2018_10:07 Trying to like media: xx
16.03.2018_10:07 Liked: xx. Like #744.
**16.03.2018_10:08 Trying to unfollow #1:**
16.03.2018_10:08 Getting user info : xx
16.03.2018_10:09 Trying to follow: xx
16.03.2018_10:09 Followed: xx #646.
16.03.2018_10:09 Trying to like media: xx
16.03.2018_10:09 Liked: xx. Like #745.
**16.03.2018_10:10 Trying to unfollow #1:**
```

**Comment by suri4desplaines** [comment]
same bug !

**Comment by JordyVP** [comment]
Same here!

**Comment by instabot-master** [comment]
closed

**Comment by sjsh99** [comment]
Same problem here
