### ISSUE TITLE
error "list" object has no attributabe "items", after changing my userinfo files

### ISSUE THREAD

**Issue by JubJubWantRubRub1** [instabot-py/instabot.py#1050]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 10

## Python Version?
3

## Description

Programe keeps outputting this error after it logs in, when it's getting the tags. I've already updated my userinfo files like everyone is saying at the moment but my program has still stopped working

>>> 

```
  File "C:\Users\G0ji\Downloads\instabot.py-master\fanfanfan1997.py", line 60, in <module>
    bot.new_auto_mod()
  File "C:\Users\G0ji\Downloads\instabot.py-master\src\instabot.py", line 695, in new_auto_mod
    self.new_auto_mod_like()
  File "C:\Users\G0ji\Downloads\instabot.py-master\src\instabot.py", line 723, in new_auto_mod_like
    if self.like_all_exist_media(media_size=1, delay=False):
  File "C:\Users\G0ji\Downloads\instabot.py-master\src\instabot.py", line 458, in like_all_exist_media
    for blacklisted_user_name, blacklisted_user_id in self.user_blacklist.items(
AttributeError: 'list' object has no attribute 'items'
>>> 
```

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
