### ISSUE TITLE
KeyError: 'user'

### ISSUE THREAD

**Issue by adrianowatson** [instabot-py/instabot.py#1051]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
macOS Sierra version 10.12.6

## Python Version?
3

## Description

Type the description of your issue here.

Instabot stopped working

Include the contents of the error.log here (if applicable).
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/adrianwatson/Documents/instabot.py-master/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/adrianwatson/Documents/instabot.py-master/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/adrianwatson/Documents/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'

**Comment by rugge89lau** [comment]
I have the same problem!

**Comment by fedemengo** [comment]
In file `src/userinfo.py` you just need to replace `id_user = all_data['user']['id']` to `id_user = all_data['graphql']['user']['id']`

**Comment by SebastianInd** [comment]
See https://github.com/instabot-py/instabot.py/issues/1048

**Comment by paulcontboxx** [comment]
This works! Great. Thanks.

**Comment by Sanketdhanawade10** [comment]
what to enter instead of user and id?

**Comment by pocheche** [comment]
Now working all_data['graphql']['user']['id'] have to be replaced in instabot.py and userinfo.py. Thank you.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
