### ISSUE TITLE
User issue

### ISSUE THREAD

**Issue by jaybak** [instabot-py/instabot.py#1053]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Linux  on RaspPi3

## Python Version?
 3

## Description

Type the description of your issue here.

Ok.... Im having a bit of an issue.
I'm running raspPi3.
When I run the command:
_sudo python example.py_
I get the errors below.
What am I doing wrong?

Include the contents of the error.log here (if applicable).

_16.03.2018_17:07 Instabot v1.2.0 started at 16.03.2018 17:07:

16.03.2018_17:07 Trying to login as xxxxUSERNAMExxxx...

Traceback (most recent call last):
File "example.py", line 52, in <module>
unfollow_whitelist=[........all my white listed users.......])
File "/home/pi/USBDrive/instabot.py-master/src/instabot.py", line 231, in __init__
self.login()
File "/home/pi/USBDrive/instabot.py-master/src/instabot.py", line 300, in login
self.user_id = ui.get_user_id_by_login(self.user_login)
File "/home/pi/USBDrive/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
id_user = all_data['user']['id']
KeyError: 'user'

(user name and white list have been sanitized for this post)_

```

**Comment by SebastianInd** [comment]
Same here, running on ubuntu 14.04, python 2.7.6. Worked fine until a few days ago...probably something at Instagram has changed recently.

**Comment by SebastianInd** [comment]
See https://github.com/instabot-py/instabot.py/issues/1048

**Comment by jaybak** [comment]
That looks like it did the trick.  Thank you.
