### ISSUE TITLE
xxxxxxx user info list is empty!!! xxxxxxxxx

### ISSUE THREAD

**Issue by zhmrab** [instabot-py/instabot.py#1054]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Ubuntu VPS
## Python Version?
2 / 3
tried both
## Description

Type the description of your issue here.

Trying to login but getting this 

```
17.03.2018_02:43 Login error! Connection error!
17.03.2018_02:43 Removing already liked medias..
xxxxxxx user info list is empty!!! xxxxxxxxx
^CTraceback (most recent call last):
  File "example.py", line 94, in <module>
    bot.new_auto_mod()
  File "/home/bot/instabot.py/src/instabot.py", line 699, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "/home/bot/instabot.py/src/instabot.py", line 764, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "/home/bot/instabot.py/src/unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "/home/bot/instabot.py/src/follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "/home/bot/instabot.py/src/feed_scanner.py", line 68, in feed_scanner
    time.sleep(random.randint(15, 22))
KeyboardInterrupt
```

**Comment by digiteo** [comment]
+1, could someone help us please?

**Comment by Tidle999** [comment]
same problem for me on almost all modes except mode 0

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by victosuper** [comment]
This was still clearly a issue
