### ISSUE TITLE
Like recent media by user

### ISSUE THREAD

**Issue by Jame-Stitel** [instabot-py/instabot.py#1056]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Python Version?
2 / 3

## Description

Hey, 

I have a list of users. How can I like 2-4 most recent medias of those users?

Thanks!

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
