### ISSUE TITLE
The bot used to work for me, now I get an error

### ISSUE THREAD

**Issue by EliasElCampero** [instabot-py/instabot.py#1058]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Linux

## Python Version?
3.5

## Description

Type the description of your issue here.

```
17.03.2018_23:32 Instabot v1.2.0 started at 17.03.2018 23:32:

17.03.2018_23:32 Trying to login as animuotako...

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['YassuoMoe', 'EliasElCampero'])
  File "/home/pi/Desktop/bot/instabot.py/src/instabot.py", line 231, in __init__
    self.login()
  File "/home/pi/Desktop/bot/instabot.py/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/home/pi/Desktop/bot/instabot.py/src/userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'
```

**Comment by apdmatos** [comment]
A fix is already here: https://github.com/instabot-py/instabot.py/pull/1055

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
