### ISSUE TITLE
Is there any way to read direct messages from other users?

### ISSUE THREAD

**Issue by burakgulmez** [instabot-py/instabot.py#1062]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Linux, Ubuntu

## Python Version?
3

## Description

We can send direct messages to other users. Is there any way to read direct messages from other users?

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
