### ISSUE TITLE
not unfollowing and except in get_info! 

### ISSUE THREAD

**Issue by marcosenno88** [instabot-py/instabot.py#1067]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Python Version?
2 / 3

## Description

Type the description of your issue here.

```
Include the contents of the error.log here (if applicable).
```
Since i fixed User_info and userinfo the bot can't unfollow.
someone can fix this or have the same issue?

![cattura](https://user-images.githubusercontent.com/37532558/37590312-2ad3df86-2b68-11e8-83ba-790897ee61df.JPG)

**Comment by sunny127** [comment]
I have the same problem. It likes and follows OK , but can't unfollow...

**Comment by instabot-master** [comment]
yeah I have the same issue and opened an issue for that but no fix yet. please anyone help. thanks xx

**Comment by rinat-khantimirov** [comment]
change this in instabot.auto_unfollow() 
между 848 - 856 lines
```
user_info = all_data['graphql']['user']
i = 0
log_string = "Checking user info.."
self.write_log(log_string)

follows = user_info['edge_follow']['count']
follower = user_info['edge_followed_by']['count']
media = user_info['edge_owner_to_timeline_media']['count']
```

**Comment by instabot-master** [comment]
@rinat-khantimirov: chaning it in what file?

**Comment by rinat-khantimirov** [comment]
instabot.py

**Comment by instabot-master** [comment]
I only have these files in my instabot:
![image](https://user-images.githubusercontent.com/37404305/37603182-54b86f1c-2b8e-11e8-9b66-4ac466a23b5b.png)

**Comment by instabot-master** [comment]
@rinat-khantimirov which one do you mean of these?

**Comment by rinat-khantimirov** [comment]
You have this file in your list. 5 from top

**Comment by instabot-master** [comment]
@rinat-khantimirov: totally right ;) are there any other places where the ['graphql']['user'] is to be changed as ['user'] is used multiple times within that file?

**Comment by marcosenno88** [comment]
looks it works perfect ty so much!

**Comment by instabot-master** [comment]
@rinat-khantimirov: thank you. seems to work now. i am testing it currently.

**Comment by sunny127** [comment]
@rinat-khantimirov Thank you! Unfollow seems to work now! :)

**Comment by sunny127** [comment]
After about 8 hours testing it looks good, only one strange behavior:
I get sometimes:   
 >>>This account is NOT following you
 >>>You are NOT following this account

How can it be? If I don't follow him, and he doesn't follow me, how the heck the bot looks at it?
Here is an example:

`20.03.2018_00:06 Checking user info..
20.03.2018_00:06 Follower : 11
20.03.2018_00:06 Following : 19
20.03.2018_00:06 Media : 43
   >>>This is a normal account
   >>>This user is active
   >>>This account is NOT following you
   >>>You are NOT following this account
20.03.2018_00:06 <Account name>
20.03.2018_00:06 Unfollowed: <Account ID> #45.`

**Comment by Tidle999** [comment]
does not work for me. i changed the lines and also tried the commit with the already changed instabot.py (also edited the userinfo and user_info of clourse) but still no unfollowing and only mode 0 is working. any idea? when i am exiting by using ctrl+c unfollowing seems to work.
by using mode 3 for example i get these errors:
` python doit_leen2.py
10:36 Instabot v1.2.0 started at 20.03.2018 10:36:

10:36 Trying to login as test-account...

10:36 test-account login success!
10:36 test-account : Get media id on recent feed
 20.03.2018 10:36
10:36 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
10:37 test-account : Get media id on recent feed
 20.03.2018 10:37
10:37 Except on get media!!
10:37 ======> Get media id by Tag <======
10:37 Get media by user success!
10:37 Current Index = 3 of 40 medias
Traceback (most recent call last):
  File "doit_leen2.py", line 98, in <module>
    unfollow_protocol(bot)
  File "\src\unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File " \src\follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File " \src\feed_scanner.py", line 56, in feed_scanner
    likers_graber_protocol(self)
  File " \src\likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File " \src\likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'`

**Comment by clementinoux** [comment]
+1

**Comment by luciatseng** [comment]
Pull request for this fix: https://github.com/instabot-py/instabot.py/pull/1110

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by Thesmellofroses** [comment]
this fix did not help me.
