### ISSUE TITLE
ImportError After Correct Requirements Installation

### ISSUE THREAD

**Issue by mayvn10** [instabot-py/instabot.py#1068]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

Linux
Ubuntu 16.04.4 LTS

## Python Version?
2 / 3

Python 2.7.12

## Description

Type the description of your issue here.
Even after using `pip install fake_useragent --user` and confirming that the requirements have been installed using the `pip install -r requirements.txt`.. I am still getting an Import Error:

`ImportError: No module named 'fake_useragent'`

```
WARNING:fake_useragent:Error occurred during loading data. Trying to use cache server http://d2g6u4gh6d9rq0.cloudfront.net/browsers/fake_useragent_0.1.10.json
```

**Comment by Glen-Cocoa** [comment]
having the same problem!

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
