### ISSUE TITLE
Unfollow doesn't work

### ISSUE THREAD

**Issue by Metalskat** [instabot-py/instabot.py#1072]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Python Version?
2 / 3

## Description

20.03.2018_00:47 Trying to unfollow #1:
20.03.2018_00:47 Getting user info : xxxx
20.03.2018_00:47 Trying to like media: 1738789429289421610
20.03.2018_00:47 Liked: 1738789429289421610. Like #349.
20.03.2018_00:48 Trying to like media: 1738788913852951016
20.03.2018_00:48 Liked: 1738788913852951016. Like #350.
20.03.2018_00:49 Trying to like media: 1738788851725688386
20.03.2018_00:49 Liked: 1738788851725688386. Like #351.
20.03.2018_00:50 Trying to like media: 1738785400124000650
20.03.2018_00:50 Liked: 1738785400124000650. Like #352.
20.03.2018_00:51 Trying to like media: 1738785294158723903
20.03.2018_00:51 Liked: 1738785294158723903. Like #353.
20.03.2018_00:51 Get media id by tag: blackandwhite
20.03.2018_00:51 Removing already liked medias..
20.03.2018_00:51 Trying to unfollow #1:
20.03.2018_00:51 Getting user info : xxxxx

```
Include the contents of the error.log here (if applicable).
```

**Comment by Tidle999** [comment]
same for me. unfollowing not working although i changed instabot.py and userinfo/user_info.py.
only mode 0 is working (without unfollowing) which mode are u using?

**Comment by Metalskat** [comment]
auto mode!

**Comment by momentmaker** [comment]
Not working for me either.

**Comment by josuegonzalezm** [comment]
not working !!

**Comment by ocslegna** [comment]
**_auto_unfollow_** is not working after the modificactions with **['graphql']** in  **all_data** and **user_info**.
In any case, I 'm still getting _Key_ Error.
I think may be the problem is within the **usernames** table with the **get_username_random** function in **sql_updates.py**, don't know.
Perhaps for example  it is while trying to get the _url_tag_ in **auto_unfollow** in instabot.py

**Comment by luciatseng** [comment]
Pull request for this fix: https://github.com/instabot-py/instabot.py/pull/1110

**Comment by momentmaker** [comment]
Yep. I did all of that and it's still not working.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by luxmodz** [comment]
^^^ honestly f you chip you dont fix anything and you close unsolved issues you are a great help! NOT!!!!!!!!
