### ISSUE TITLE
getting several errors using stock script

### ISSUE THREAD

**Issue by Curtis777** [instabot-py/instabot.py#1077]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [] Bug
- [] Feature Request
- [x] Technical Help
- [] Other

### Operating System? (include version)
Windows 10

## Python Version?
2 / 3

## Description

Type the description of your issue here.

when i run on my windows 10 the example.py
i got several errors.
Include the contents of the error.log here (if applicable).

Traceback (most recent call last):
  File ".\example.original.py", line 52, in <module>
    unfollow_whitelist=['userxy', 'userzyx'])
  File "C:\instabot\src\instabot.py", line 231, in __init__
    self.login()
  File "C:\instabot\src\instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\instabot\src\userinfo.py", line 42, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'
```

**Comment by matt199x** [comment]
I have the same issue!

**Comment by dimosbc** [comment]
exactly the same problem for me on mac and linux

**Comment by focamonca** [comment]
the same here

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
