### ISSUE TITLE
Pause/Log Out Issue

### ISSUE THREAD

**Issue by Azerafa** [instabot-py/instabot.py#1079]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
MacOS Sierra 10.12.6

## Python Version?
2 / 3
2

## Description

Apologies for two issues so close together, but my bot has been logging itself off and I'm not sure why. I'm running it on my local machine and was having no issues at all last week, so I don't think it's a connectivity issue but I just don't know. 

NewConnectionError is what stands out to me in the log, but I included it all. 

```
Include the contents of the error.log here (if applicable).
```
Traceback (most recent call last):
  File "example.py", line 74, in <module>
    bot.new_auto_mod()
  File "/Users/xxxxxx/Desktop/instabot.py-master/src/instabot.py", line 701, in new_auto_mod
    self.new_auto_mod_comments()
  File "/Users/xxxxxx/Desktop/instabot.py-master/src/instabot.py", line 769, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['shortcode']) == False:
  File "/Users/xxxxxx/Desktop/instabot.py-master/src/instabot.py", line 792, in check_exisiting_comment
    check_comment = self.s.get(url_check)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /p/BgjpwkYHEa9/?__a=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10b3bed50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
20.03.2018_17:30 Trying to unfollow: 848960100
20.03.2018_17:30 Pausing for 454 seconds... 0 of 5
20.03.2018_17:38 Trying to unfollow: 3937834709
20.03.2018_17:38 Unfollow: 3937834709 #1 of 5.
20.03.2018_17:38 Pausing for 543 seconds... 1 of 5
20.03.2018_17:47 Trying to unfollow: 4143448491
20.03.2018_17:47 Unfollow: 4143448491 #2 of 5.
20.03.2018_17:47 Pausing for 303 seconds... 2 of 5
20.03.2018_17:52 Logout: likes - 22, follow - 5, unfollow - 2, comments - 2.
20.03.2018_17:52 Bot work time: 3:06:39.712696
20.03.2018_17:52 Logout success!

**Comment by OwenModamwen** [comment]
I'm getting the same issue

**Comment by Azerafa** [comment]
@OwenModamwen That worked, thanks! Just going to wait a day or so to see if the issue repeats itself.

**Comment by Matthew1337** [comment]
26.03.2018_19:28 Get media by user success!
26.03.2018_19:28 Current Index = 9 of 45 medias
Traceback (most recent call last):
  File "example.py", line 101, in <module>
    feed_scanner(bot)
  File "C:\Users\mattm\Desktop\insta\src\feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "C:\Users\mattm\Desktop\insta\src\likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "C:\Users\mattm\Desktop\insta\src\likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
26.03.2018_19:28 Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
26.03.2018_19:28 Bot work time: 0:00:28.995534
26.03.2018_19:28 Logout success!



Help pls?

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
