### ISSUE TITLE
Unfollow issue after fix

### ISSUE THREAD

**Issue by JordyVP** [instabot-py/instabot.py#1082]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Python Version?
2 / 3

## Description

Hi guys,

After applying this fix (see below) to the script, the unfollow seems to work.

change this in instabot.auto_unfollow()between 848 - 856 
linesuser_info = all_data['graphql']['user'] i = 0 log_string = "Checking user info.." self.write_log(log_string)  follows = user_info['edge_follow']['count'] follower = user_info['edge_followed_by']['count'] media = user_info['edge_owner_to_timeline_media']['count']
--
However, when I checked the logs this morning I found this. It unfollowed 25 people, but after that it stopped and it gave this log
![image](https://user-images.githubusercontent.com/37398701/37700153-acc03b9c-2cea-11e8-9f7d-6a1ca453074c.png)

Hope someone knows a fix for this!

Thanks in advance

**Comment by luciatseng** [comment]
I made the exact same fix as you and I'm able to get 500+ unfollows. Is your unfollow_per_day set to 25 by any chance?

**Comment by JordyVP** [comment]
Hm no my limit is set to 700, so that shouldn't be a problem! I use Grow automator for the unfollows now, it's a Google Chrome Extension, which works perfect but has to be paid for after 14 days..

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
