### ISSUE TITLE
Suspicious detection loop started again

### ISSUE THREAD

**Issue by may47** [instabot-py/instabot.py#1085]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

## Python Version?
3

## Description
Detection loop
Type the description of your issue here.
The suspicious detection loop started again
```
Include the contents of the error.log here (if applicable).
```

**Comment by may47** [comment]
Does anyone else face the same problem?

**Comment by dabsx** [comment]
I am facing this issue. Bot starts removing already liked medias :|

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
