### ISSUE TITLE
login error ?

### ISSUE THREAD

**Issue by s2339956** [instabot-py/instabot.py#1089]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Python Version?
3

## Description

Type the description of your issue here.
instabot V2
Include the contents of the error.log here (if applicable).
23.03.2018_14:59 Trying to login as s2339956...

Traceback (most recent call last):
  File "/Users/tinxie/Desktop/instabot.pyV2-masterv2/instabot.pyV2-masterv2/example.py", line 58, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/tinxie/Desktop/instabot.pyV2-masterv2/instabot.pyV2-masterv2/src/instabot.py", line 227, in __init__
    self.login()
  File "/Users/tinxie/Desktop/instabot.pyV2-masterv2/instabot.pyV2-masterv2/src/instabot.py", line 296, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/tinxie/Desktop/instabot.pyV2-masterv2/instabot.pyV2-masterv2/src/userinfo.py", line 45, in get_user_id_by_login
    id_user = all_data['user']['id']
KeyError: 'user'

**Comment by mathiasadam** [comment]
Same here

**Comment by fab976** [comment]
same here

**Comment by RCAHaertlein** [comment]
Yep exact same issue. The Login is dead

**Comment by MojtabaMoayedi** [comment]
hi friends.
I have the same issue too. can anybody help?

**Comment by tiaringhio** [comment]
Same here.

**Comment by s2339956** [comment]
FIXME: 
userinfo.py -> line 45 -> id_user = all_data['graphql']['user']['id']

**Comment by Abbas-Seyyedi** [comment]
s2339956 thaaaanks man

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
