### ISSUE TITLE
how to follow only private accounts? (that are not following you back)

### ISSUE THREAD

**Issue by fantomlord** [instabot-py/instabot.py#1090]
- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Microsoft Windows [Version 10.0.16299.309]
## Python Version?
2 / 3
3.6 64-bit
## Description

Type the description of your issue here.
Hi i am new to instabot and programming, i am trying to get followers for my page and as far as i understood the loyal followers are those who mostly have private account, what i request from you friends is if you can help me do the following:
- request to follow ONLY "private accounts" based on either they are active about an specific tag. ( i found the "is_private":true parameter on a private account but not in the code i don;t know where i can include such parameter in reading the user info)
- check if they are following you back and if so ignore rest of the process (because i usually unfollow people after they start following me) i have like 1K of followers on my page and about 15 following. 
```
Include the contents of the error.log here (if applicable).
```

**Comment by fantomlord** [comment]
push

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
