### ISSUE TITLE
Bot is only following but fails to like any media

### ISSUE THREAD

**Issue by zhmrab** [instabot-py/instabot.py#1094]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Ubuntu 16.04
## Python Version?
2 / 3
Both
## Description

Type the description of your issue here.

```
Bot is only following but fails to like any media, `not liked : 400`
```

**Comment by Bl4ckFr0st** [comment]
Having the same problem

**Comment by progl** [comment]
it's instagram error code 400 - blocks you as detection on spam! You can google it, maybe good mobile private proxy will help you

**Comment by zhmrab** [comment]
Thanks
