### ISSUE TITLE
i get Suspicious login detection on browser when i start the bot?

### ISSUE THREAD

**Issue by dipumahbub** [instabot-py/instabot.py#1095]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug

### Operating System? (include version)
MAC

## Python Version?
3

## Description

Login error! Connection error

24.03.2018_13:37 Login error! Connection error!
24.03.2018_13:37 Removing already liked medias..
24.03.2018_13:37 Trying to unfollow #1: 
24.03.2018_13:37 Removing already liked medias..
24.03.2018_13:37 Removing already liked medias..
 24.03.2018_13:37 Removing already liked medias..
^Z
[2]+  Stopped                 python example.py

**Comment by JongChing** [comment]
I got the same issue too! Help!

**Comment by facuardila** [comment]
same issue here

**Comment by mbe9477** [comment]
+1

**Comment by napster2091** [comment]
log from your webbrowser ans spoof cookies to reuse them for the next logins

**Comment by facuardila** [comment]
thanks @napster2091 that's worked for me.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
