### ISSUE TITLE
the unfollow isn't work 

### ISSUE THREAD

**Issue by josuegonzalezm** [instabot-py/instabot.py#1096]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System
MAC

## Python Version?
2.7.14

## Description

Type the description of your issue here.

24.03.2018_12:55 Trying to unfollow #1: 
24.03.2018_12:55 Getting user info : gnarley.charlie
24.03.2018_12:57 Trying to like media: 1742017239877594147
24.03.2018_12:57 Liked: 1742017239877594147. Like #1623.
24.03.2018_12:57#  Trying to unfollow #1: 
24.03.2018_12:57 Getting user info : travelandloveanimals
24.03.2018_12:58 Already followed before 255830400
24.03.2018_12:58 Trying to like media: 1741547489238105466
24.03.2018_12:58 Liked: 1741547489238105466. Like #1624.
24.03.2018_12:59 # Trying to unfollow #1: 
24.03.2018_12:59 Getting user info : pi_zdets
24.03.2018_12:59 Already followed before 255830400
24.03.2018_13:00 Trying to like media: 1740990132457986710
24.03.2018_13:00 Liked: 1740990132457986710. Like #1625.
24.03.2018_13:00 Get media id by tag: newyork
24.03.2018_13:00 Removing already liked medias..
24.03.2018_13:00 Trying to follow: 5966636376
24.03.2018_13:00 Followed: 5966636376 #977.
24.03.2018_13:00 # Trying to unfollow #1:

Include the contents of the error.log here (if applicable).
N/A

**Comment by napster2091** [comment]
your global user_id variable need to be updated everytime you try to followe someone new otherwise the compare function won't work well, you will stay comparing everytime the same user_id that you followed before so you will skip it because it has been already followed

**Comment by luciatseng** [comment]
Same issue

**Comment by robsouthgate4** [comment]
Any code examples to fix this please?

**Comment by napster2091** [comment]
Share here the code of the unfollow function...i'll try to help you

**Comment by luciatseng** [comment]
The following fix worked for me. Change lines 848 - 856 in instabot.py to the following: 

```
user_info = all_data['graphql']['user']
i = 0
log_string = "Checking user info.."
self.write_log(log_string)

follows = user_info['edge_follow']['count']
follower = user_info['edge_followed_by']['count']
media = user_info['edge_owner_to_timeline_media']['count']
follow_viewer = user_info['follows_viewer']
```

**Comment by josuegonzalezm** [comment]
@luciatseng  thanks !!!!! it's working with this code !!

**Comment by luciatseng** [comment]
Pull request for this fix: https://github.com/instabot-py/instabot.py/pull/1110

**Comment by inge453** [comment]
doesn't worked for me.. i "solved" (read as by-passed) issue by deleting from line 839 until 916.
