### ISSUE TITLE
Except on get media on recent feed

### ISSUE THREAD

**Issue by canceroyer** [instabot-py/instabot.py#1098]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ x] I have searched for other issues with the same problem.

## Hosting
- [no ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
windows 7 home premium

## Python Version?
3

## Description

Everything id working find unless it tries to get media on recent feed it always shows this:

![image](https://user-images.githubusercontent.com/37394638/37869014-280e643c-2f7e-11e8-9fbb-7fa30168d6a0.png)

**Comment by andrewsegas** [comment]
https://github.com/andrewsegas/instaboost

**Comment by marcosenno88** [comment]
i have the same problem...

**Comment by andrewsegas** [comment]
Guys, send more details, please, or can be log file

**Comment by marcosenno88** [comment]
@andrewsegas  i fixed Both, userinfo.py and user_info.py  (fixed by #1048)
then fixed "get_media" after the quick fix #1057
also fixed not unfollowing and except in get_info! #1067
but i still have this issue.


![cattura i](https://user-images.githubusercontent.com/37532558/37961236-096c1d08-31b8-11e8-8e74-523b67787839.JPG)

**Comment by andrewsegas** [comment]
It's not one error, i can't understand what is wrong with your log, i don't see anything wrong

**Comment by marcosenno88** [comment]
what doest it mean media in recent fees = 12?

**Comment by canceroyer** [comment]
ive tried all of these not working

**Comment by canceroyer** [comment]
does anyone have a instabot with geotag liking working fine that can send me the files?

**Comment by andrewsegas** [comment]
@canceroyer , here geotag is working and we have user interface as well
https://github.com/andrewsegas/instaboost/

**Comment by SeanFacer** [comment]
Getting the same

**Comment by frankpantone** [comment]
same issue. Any fix for this?

**Comment by andrewsegas** [comment]
Instagram changed their schema, here they doesn't accept PR
it's fixed here https://github.com/andrewsegas/instaboost

**Comment by angelorodem** [comment]
its not fixed in your fork @andrewsegas , i just tried it and got the same error

> 10:09 Except on get media!!
> ^CTraceback (most recent call last):
>   File "/home/ollegn/insta/instaboost/Instaboost/src/recent_feed.py", line 19, in get_media_id_recent_feed
>     self.media_on_feed = list(all_data['graphql']['user']['edge_web_feed_timeline']['edges'])
> TypeError: 'NoneType' object is not subscriptable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "teste.py", line 200, in <module>
>     comeca_bot(modo_)
>   File "teste.py", line 169, in comeca_bot
>     bot.new_auto_mod_unfollow()
>   File "/home/ollegn/insta/instaboost/Instaboost/src/instabot.py", line 872, in new_auto_mod_unfollow
>     unfollow_protocol(self)
>   File "/home/ollegn/insta/instaboost/Instaboost/src/unfollow_protocol.py", line 16, in unfollow_protocol
>     get_media_id_recent_feed(self)
>   File "/home/ollegn/insta/instaboost/Instaboost/src/recent_feed.py", line 26, in get_media_id_recent_feed
>     time.sleep(20)
> KeyboardInterrupt
> 10:10 Trying to Unfollow: 7596260343
> 10:10 Unfollow: 7596260343 #1 of 1.
> 10:10 Pausing for 18 seconds... 1 of 1
> ^CError in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "/home/ollegn/insta/instaboost/Instaboost/src/instabot.py", line 360, in cleanup
>     time.sleep(sleeptime)
> KeyboardInterrupt
>
