### ISSUE TITLE
Line 52 "key error"

### ISSUE THREAD

**Issue by nzt159** [instabot-py/instabot.py#1099]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Python Version?
2 / 3

## Description

Type the description of your issue here.

```
Include the contents of the error.log here (if applicable).
```
I've tried changing everything to graphql DOES NOT WORK

**Comment by andrewsegas** [comment]
https://github.com/andrewsegas/instaboost
here it is working

**Comment by nzt159** [comment]
How do you set it up? Sorry I am new to this

**Comment by andrewsegas** [comment]
@nzt159 just go to that link, download and run the project, you can just read the instructions.
any problem please open one issue in https://github.com/andrewsegas/instaboost

**Comment by nzt159** [comment]
Python cant open file "example"
[Errno 2] no such file or directory
