### ISSUE TITLE
Mode == 2

### ISSUE THREAD

**Issue by Koldrish** [instabot-py/instabot.py#1102]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [] Technical Help
- [ ] Other

### Operating System? (include version)
Windows

## Python Version?
3

## Description

Mode == 2 (original mode + unfollow who do not follow back) does not work, bot unfollow who follows me. How to fix?

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
