### ISSUE TITLE
Logout after get media

### ISSUE THREAD

**Issue by Matthew1337** [instabot-py/instabot.py#1103]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 

## Python Version?
3

## Description
logs out just after login with a couple of error codes. fixed the first error by replacing line 42 in userinfo.py but now after getting user media it logs itself out?

```
26.03.2018_19:28 Get media by user success!
26.03.2018_19:28 Current Index = 9 of 45 medias
Traceback (most recent call last):
  File "example.py", line 101, in <module>
    feed_scanner(bot)
  File "C:\Users\mattm\Desktop\insta\src\feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "C:\Users\mattm\Desktop\insta\src\likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "C:\Users\mattm\Desktop\insta\src\likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
26.03.2018_19:28 Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
26.03.2018_19:28 Bot work time: 0:00:28.995534
26.03.2018_19:28 Logout success!
```

**Comment by napster2091** [comment]
this is wrong ["likes"]["count"]

now the likes counter is under:
["graphql"]["shortcode_media"]["edge_media_preview_like"]["count"]

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
