### ISSUE TITLE
KeyError: 'user'

### ISSUE THREAD

**Issue by preps103** [instabot-py/instabot.py#1104]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Mac

## Python Version?
2 / 3
3

## Description

Type the description of your issue here.
<img width="715" alt="screen shot 2018-03-27 at 12 40 12 am" src="https://user-images.githubusercontent.com/35946160/37947247-050a1702-3158-11e8-899d-f474c2bf4230.png">

Include the contents of the error.log here (if applicable).
```

**Comment by Bersam** [comment]
https://github.com/instabot-py/instabot.py/issues/1086

**Comment by napster2091** [comment]
id_user = all_data ['user']['id'] is wrong, you need to use:

id_user = all_data["graphql"]["user"]["edge_followed_by"]["count"]

**Comment by LionelChow** [comment]
Met the same problem either. and the problem is solved after i modified the file as @napster2091 said. Thx man.

**Comment by eastcoastboys** [comment]
Thank you @napster2091 It worked perfect!!!!

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
