### ISSUE TITLE
import error: no module name instabot

### ISSUE THREAD

**Issue by archfch2** [instabot-py/instabot.py#1105]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
 Android 4.2

## Python Version?
2 

## Description
When try to run the script on my Android phone using Qpython I am getting the following error.
The same code and folder structure works fine when run on Windows.
in/qpython.sh && exit                    <
Python 2.7.12 (default, Nov 21 2017, 21:49:35)
[GCC 4.9.x 20150123 (prerelease)] on linux4Type "help", "copyright", "credits" or "license" for more information.
>>> exec(open("/sdcard/qpython/projects3/instabot-master/examples/multi_script_CLI.py" ).read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 10, in <module>
ImportError: No module named instabot
>>> exec(open("/sdcard/qpython/projects3/instabot-master/examples/multi_script_CLI.py" ).read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 10, in <module>
ImportError: No module named instabot
>>>

```
Include the contents of the error.log here (if applicable).
```

**Comment by napster2091** [comment]
you need to set the right path where the instabot module is located

try to use for example:

import sys, os
sys.path.append(os.path.join(sys.path[0],'here you need to write the path where there is the instabot module'))

**Comment by archfch2** [comment]
@napster2091  
tha path is there by default - 
```
sys.path.append(os.path.join(sys.path[0], '../'))
from instabot import Bot
```
which means go one level up and that is exactly where the instabot folder is.
What do I miss?

**Comment by napster2091** [comment]
i can't see any instabot folder here
/sdcard/qpython/projects3/instabot-master/examples/multi_script_CLI.py
maybe you need to go up 2 times because yourinstabot is inside instabo-master and not inside examples folder

**Comment by archfch2** [comment]
@napster2091  Yes, instabot is in instabot-master folder and current path points to examples folder.
So if i go one folder up I will land exactly in the insta-master folder.

**Comment by archfch2** [comment]
Ok. So I solved the issue by adding one line of code. (line 2)
```
1 sys.path.append(os.path.join(sys.path[0], '../'))
2 os.path.join(sys.path[0], '../')
3 from instabot import Bot
```

**Comment by napster2091** [comment]
../../ it is also allowed instead of writing line 2

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
