### ISSUE TITLE
KeyError: 'likes' / mode 3

### ISSUE THREAD

**Issue by mbe9477** [instabot-py/instabot.py#1108]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC

## Python Version?
2 / 3

## Description

Type the description of your issue here.

I've adjusted already the code in some *.py files listed here in other issues, but still I am not successful running mode #3. Can anyone please help me!? THANK YOU!
(******* = my IG accout & user name)

Include the contents of the error.log here (if applicable).
```
28.03.2018_19:22 Instabot v1.2.0 started at 28.03.2018 19:22:

28.03.2018_19:22 Trying to login as *******...

28.03.2018_19:22 ******* login success!
28.03.2018_19:22 ******* : Get media id on recent feed 
 28.03.2018 19:22
28.03.2018_19:22 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
28.03.2018_19:23 ******* : Get media id on recent feed 
 28.03.2018 19:23
28.03.2018_19:23 Except on get media!!
28.03.2018_19:23 ======> Get media id by Tag <======
28.03.2018_19:23 Get media by user success!
28.03.2018_19:23 Current Index = 51 of 56 medias
Traceback (most recent call last):
  File "example.py", line 93, in <module>
    unfollow_protocol(bot)
  File "/Users/*******/Desktop/instabot.py-master/src/unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "/Users/*******/Desktop/instabot.py-master/src/follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "/Users/*******/Desktop/instabot.py-master/src/feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "/Users/*******/Desktop/instabot.py-master/src/likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "/Users/*******/Desktop/instabot.py-master/src/likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
28.03.2018_19:23 Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
28.03.2018_19:23 Bot work time: 0:00:48.134652
28.03.2018_19:23 Logout success!

**Comment by yourash** [comment]
The same in mode 5

**Comment by Stepyon** [comment]
Mode 2 has the same issue

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by darynk** [comment]
Yes, this is still an issue

**Comment by ndlogog** [comment]
have u try change line '19' @ 'likers_protocol.py':
> if self.media_by_user[self.current_index]["likes"]["count"] >= 10 and self.media_by_user[self.current_index]["likes"]["count"] < 100:

change 

> if self.media_by_user[self.current_index]["node"]["edge_liked_by"]["count"] >= 10 and self.media_by_user[self.current_index]["node"]["edge_liked_by"]["count"] < 100:

**Comment by mbe9477** [comment]
I've changed as you suggest, but now I get this

SyntaxError: invalid syntax

**Comment by mistrbeard** [comment]
shit error fuck you

**Comment by Franz-Kafka** [comment]
I get the 

KeyError: 'code'

when I change these lines.

**Comment by steffo93** [comment]
BUMP! Still having this issue.

`line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'`

**Comment by dimisdas** [comment]
https://github.com/instabot-py/instabot.py/pull/1788 

Try this pull request. Make sure to use the new example.py. Let me know if it works with mode 3
