### ISSUE TITLE
How to add proxy with username and password?

### ISSUE THREAD

**Issue by stxrm** [instabot-py/instabot.py#1111]
- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [yes ] I have searched for other issues with the same problem.

## Hosting
- [no ] Are you hosting the bot on a VPS or other Cloud hosting?
- [no ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows
## Python Version?
3.6

## Description

Hey there, so I know nothing about python or github at all. I'm having issues with adding proxies to instabot.py because I don't have a clue how to add a proxy with a username and password.

```
Include the contents of the error.log here (if applicable).
```

**Comment by zhmrab** [comment]
+1

**Comment by progl** [comment]
People, are you reading source? Look there is a lot of interesting!
in init of ypur bot proxy as parameter is, proxy = 'user:password@host:port'

and then in code we see 
```
if proxy != "":
            proxies = {
                'http': 'http://' + proxy,
                'https': 'http://' + proxy,
            }
self.s.proxies.update(proxies)
```
any questions google python requests proxy

**Comment by stxrm** [comment]
Thank you, sir 👍

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by markeli1** [comment]
Thank you for your free instabot.py, it was really useful.
Can you please help me? I select proxy as it is required (for example proxy='12.12.12.12:2323'). Proxy do work, I have already checked. But bot still cannot see the proxy because instagram account sees my IP again.
Thank you in advance
