### ISSUE TITLE
Using randint module on variables

### ISSUE THREAD

**Issue by uhohbruno** [instabot-py/instabot.py#1112]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows8.1

## Python Version?
3.6

## Description

I'm trying to be as safe as possible to not banned or shadowbanned and keep my bot monotonous among other things using randomint for the variables so i.e likeperday= randomint(300,350) max_like_for_one_tag=randomint(35-50) follow_per_day=randomint(200, 300).

I'm guessing the changes would only take effect when I start up the example.py so for some of the variables it doesn't matter but for the unfollow_break_min I would like to change the int after every unfollow. I wouldn't want it to be so exact that eventually it would be detectable by instagram.

**Comment by andrewsegas** [comment]
Hi, You can add in everyevent one random sleep with some seconds,
https://github.com/andrewsegas/instaboost
Here I use many differents ways to avoid bann, and since i started it i've never been banned

**Comment by tonytiger2t** [comment]
Funny, @andrewsegas because your bot got me banned almost immediately. And it seems all you do is promote your bot instead of contributing.

**Comment by andrewsegas** [comment]
@tonytiger2t Hi are you the Tony Tiger that doesn't use Icebreaker to connect with people? Looking for girls in sex social network?
sorry but I tried to help this project many times. They are not updating this instabot or fixing bugs.
About your question... try to read the code, if you know how to do it))
Best regards with all my respect for this project
