### ISSUE TITLE
Error on auto unfollow

### ISSUE THREAD

**Issue by mkn03963** [instabot-py/instabot.py#1113]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [X] I have searched for other issues with the same problem.

## Hosting
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Linux version 4.9.0-5-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18) ) #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04)

## Python Version?
Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516] on linux2

## Description

The bot cant unfollow followed users. It just follows. I mean the bot is nice but this has to work too. :)

```
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "/home/bot/src/instabot.py", line 848, in auto_unfollow
    user_info = all_data['user']
KeyError: 'user'

```

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by evilism** [comment]
still a issue
