### ISSUE TITLE
Bot stops any activity without any exception

### ISSUE THREAD

**Issue by keshamin** [instabot-py/instabot.py#1114]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!*

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Ubuntu 17.10

## Python Version?
3

## Description
Bot is running with new_auto_mod() method as a systemd daemon. Bot works fine for a couple of days and then stops doing any activity without crashing the process and without any exceptions.
After restarting the daemon it works fine again until the same situation.

**Comment by omaconer** [comment]
got the same problem

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
