### ISSUE TITLE
No Module Named Request

### ISSUE THREAD

**Issue by 11Yellow11** [instabot-py/instabot.py#1115]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC 10.13.3
## Python Version?
2 / 3

## Description

Type the description of your issue here.

Can't make the bot start
Include the contents of the error.log here (if applicable).
When i try to run "python example.py" i get this error

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/julietbruno/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/julietbruno/Desktop/instabot.py-master/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/Users/julietbruno/Desktop/instabot.py-master/src/userinfo.py", line 5, in <module>
    import requests
ImportError: No module named requests

As other threads said, i tried to run "pip install request" but i get this

Collecting request
  Using cached request-0.0.26.tar.gz
Collecting get (from request)
  Using cached get-0.0.39.tar.gz
Collecting post (from request)
  Using cached post-0.0.26.tar.gz
Collecting query_string (from get->request)
  Using cached query_string-0.0.28.tar.gz
Collecting public (from query_string->get->request)
  Using cached public-0.0.65.tar.gz
matplotlib 1.3.1 requires nose, which is not installed.
matplotlib 1.3.1 requires tornado, which is not installed.
matplotlib 1.3.1 has requirement numpy>=1.5, but you'll have numpy 1.8.0rc1 which is incompatible.
Installing collected packages: public, query-string, get, post, request
  Running setup.py install for public ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/n_/mn_97dzj56b5hr3x9h79yb8r0000gn/T/pip-install-06FkHM/public/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/n_/mn_97dzj56b5hr3x9h79yb8r0000gn/T/pip-record-ECa_6M/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/public
    copying public/__init__.py -> build/lib/public
    running install_lib
    creating /Library/Python/2.7/site-packages/public
    error: could not create '/Library/Python/2.7/site-packages/public': Permission denied
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/n_/mn_97dzj56b5hr3x9h79yb8r0000gn/T/pip-install-06FkHM/public/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/n_/mn_97dzj56b5hr3x9h79yb8r0000gn/T/pip-record-ECa_6M/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/n_/mn_97dzj56b5hr3x9h79yb8r0000gn/T/pip-install-06FkHM/public/

Can someone please help me out?

**Comment by 11Yellow11** [comment]
I solved the problem, i installed python3, then i uninstalled using "pip uninstall request", then i wrote "pip3 install request", then "pip3 install -r requirements.txt", then "python3 example.py".
Hope it helps in the future.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
