### ISSUE TITLE
Trace/BPT trap: 5 error in mac os x

### ISSUE THREAD

**Issue by dvyama** [instabot-py/instabot.py#1118]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC 

## Python Version?
2 

## Description

Type the description of your issue here.

When installing the bot, after the command line "pip install -r requirements.txt" I get the following two lines:

Collecting requests (from -r requirements.txt (line 1))
Trace/BPT trap: 5

I have read that it's related to not being able to find a dynamic library, but I'm not sure which. Also, I was asked for my user password when installing pip.

**Comment by geersio** [comment]
try it with sudo:

sudo pip install -r requirements.txt

**Comment by dvyama** [comment]
Thanks! I tried the following command:

$ sudo -H pip install -r requirements.txt
Collecting requests (from -r requirements.txt (line 1))

So it seemed to work, however I got:

$ python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/alfg/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/alfg/Desktop/instabot.py-master/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/Users/alfg/Desktop/instabot.py-master/src/userinfo.py", line 5, in <module>
    import requests
ImportError: No module named requests

I then tried "sudo -H pip install requests" as well as putting the file "example.py" in the src folder, as some users suggested. The result is the same for me. What could go wrong?

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
