### ISSUE TITLE
Unable to start example.py

### ISSUE THREAD

**Issue by tone87** [instabot-py/instabot.py#1130]
- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Linux (CentOS 6.9)

## Python Version?
2.6

## Description
**unable to start example.py**

i have already executed "pip install -r requirements.txt"
i have already executed "pip install requests"
i have already executed "pip install --upgrade pip"
i have already edit username and password on example.py

but show me this error on terminal :

```
[root@localhost]# python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import instabot
  File "/var/instagram/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/var/instagram/src/instabot.py", line 484
    for tag in caption.split()
      ^
SyntaxError: invalid syntax
```

**Comment by Conorbro** [comment]
I suspect it's your Python version. Upgrade Python and try again.
