### ISSUE TITLE
Error running example.py

### ISSUE THREAD

**Issue by spodZ** [instabot-py/instabot.py#1133]
- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Linux(Deepin 15.5)

## Python Version?
*3*

## Description

Type the description of your issue here.
Please Don't Closed!!!!I tried adding ['graphql'] and still get `Traceback() error` and `fakeuserAgent` issue even ran the orginial version as a test same issue.
```
root@bae03-PC:/home/bae03/instabot.py-master# python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/home/bae03/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/bae03/instabot.py-master/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ImportError: No module named fake_useragent
```

**Comment by spodZ** [comment]
Jesus Christ Im going to kill myself...I found a fixed for it `pip install fake_useragent` totally forgot about this step feel like a real idiot

**Comment by ToryCasey** [comment]
I am having this problem too but when I type that in I get: Victorias-MBP:instabot.py-master victoriacasey$ pip3 install fake user agent
Collecting fake
  Downloading fake-0.8.tar.gz
Collecting user
  Could not find a version that satisfies the requirement user (from versions: )
No matching distribution found for user

**Comment by spodZ** [comment]
It should just be `pip install fake_useragent` for the command but make sure you're running python 3.6 and pip is fully installed onto your system

**Comment by ricocaine** [comment]
> It should just be `pip install fake_useragent` for the command but make sure you're running python 3.6 and pip is fully installed onto your system

Hey man, I did what you recommend and I obtained this: **fake_useragent in /Library/Python/2.7/site-packages (0.1.11)**

But when I rely to launch the file **example.py** I re-have the same:

  **File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/XXX/Documents/virtualenvs/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/XXX/Documents/virtualenvs/instabot.py-master/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragen**t'

Any ideas fro helping me ?
