### ISSUE TITLE
Instagram API Platform Changes, Are we Ready?

### ISSUE THREAD

**Issue by guatetrending** [instabot-py/instabot.py#1135]
To continuously improve Instagram users' privacy and security, we are accelerating the deprecation of Instagram API Platform, making the following changes effective immediately. We understand that this may affect your business or services, and we appreciate your support in keeping our platform secure. 

The following capabilities will be disabled immediately (previously set for July 31, 2018 or December 11, 2018 deprecation):

Follower List - to read the list of followers and followed-by users
Relationships - to follow and unfollow accounts on a user's behalf
Commenting on Public Content - to post and delete comments on a user's behalf on public media
Likes - to like and unlike media on a user's behalf
Subscriptions - to receive notifications when media is posted
Users Information - to search for and view users' public content
Some information on Public Content returned through hashtag and location search - Name, Bio, Comments, Commenters, Follower Count, Following Count, Post Count, and Profile Picture
 

The following will be deprecated according to the timeline we shared previously:

Public Content - all remaining capabilities to read public media on a user's behalf on December 11, 2018
Basic - to read a user's own profile info and media in early 2020

**Comment by Conorbro** [comment]
>we are accelerating the deprecation of Instagram API Platform

From the readme
> Toolkit for building automated Instagram bots **without direct access to the Instagram API** or passing through the review process.

Hard to know if instabot.py will be directly affected until it happens though.

**Comment by ChipWolf** [comment]
We don't use the API
