### ISSUE TITLE
Fake User Agent Error 

### ISSUE THREAD

**Issue by ToryCasey** [instabot-py/instabot.py#1137]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [ ] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC High Sierra 10.13.4

## Python Version?
 3

## Description

Type the description of your issue here.
I went through all the steps but this is what displays when I ran it. Also, I have installed the requirements but it looks like on the requirements there is some text about fake user agents? I am not really sure what any of that means, but I have attached the error issue text below. 
```
Include the contents of the error.log here (if applicable).
Last login: Fri Apr  6 08:10:01 on ttys000
Victorias-MBP:~ victoriacasey$ cd desktop
Victorias-MBP:desktop victoriacasey$ cd instabot.py
-bash: cd: instabot.py: No such file or directory
Victorias-MBP:desktop victoriacasey$ cd instabot.py-master
Victorias-MBP:instabot.py-master victoriacasey$ pip3 install fake_useragent
Requirement already satisfied: fake_useragent in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Victorias-MBP:instabot.py-master victoriacasey$ pip3 install -r

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

-r option requires 1 argument
Victorias-MBP:instabot.py-master victoriacasey$ python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/victoriacasey/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/victoriacasey/Desktop/instabot.py-master/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ImportError: No module named fake_useragent
Victorias-MBP:instabot.py-master victoriacasey$ 
```

**Comment by mistrp** [comment]
Also experiencing this exact problem

**Comment by spodZ** [comment]
Make Sure you have python 3.6 installed and pip fully installed 
Run `pip install fake-useragent`

**Comment by spodZ** [comment]
Look on how to install pip system wide and do `pip install fake_useragent`

**Comment by ToryCasey** [comment]
I verified that pip is installed. When I use pip instead of pip3 it opens the older version and gives me a long error message:
Victorias-MBP:instabot.py-master victoriacasey$ pip install fake_useragent
Collecting fake_useragent
Installing collected packages: fake-useragent
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/fake_useragent'

**Comment by ToryCasey** [comment]
Finally got it working! I had to use python3 example.py to get it to run. Thanks for your help!

**Comment by spodZ** [comment]
Welcome and NP
