### ISSUE TITLE
have some issue in example.py

### ISSUE THREAD

**Issue by piyushx12** [instabot-py/instabot.py#1146]
File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/piyushsmacbookair/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/piyushsmacbookair/Desktop/instabot.py-master/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/Users/piyushsmacbookair/Desktop/instabot.py-master/src/userinfo.py", line 5, in <module>
    import requests
ImportError: No module named requests

I have the latest version of python3 installed on my mac. I have tried every thing but nothing is working. Please help me out. 
Cheers

**Comment by leogregianin** [comment]
Hi,
First, do you need install some dependencies. Type `pip install -r requirements.txt`. And them, use `python example.py`.
Best regards.

**Comment by piyushx12** [comment]
Hey bro, 
Did installed the requirments.txt dependencies, every thing got installed but there was an error saying `matplotlib 1.3.1 has requirement numpy>=1.5, but you'll have numpy 1.8.0rc1 which is incompatible.`
Dont know why, I am running the latest version of python3.

**Comment by ChipWolf** [comment]
Python 3.6? and numpy 1.8.0rc1 matches numpy>=1.5 so that's strange.
Try `pip install numpy --upgrade`

**Comment by piyushx12** [comment]
Hey man, Getting this error 
`pip install numpy --upgrade
Collecting numpy
  Using cached numpy-1.14.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: numpy
  Found existing installation: numpy 1.8.0rc1
Cannot uninstall 'numpy'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

**Comment by ChipWolf** [comment]
funky... try `python3 -m pip install -r requirements.txt --upgrade`

**Comment by piyushx12** [comment]
Thank you very much ChipWolf. Its working now.
