### ISSUE TITLE
Option for idling

### ISSUE THREAD

**Issue by dgvicii** [instabot-py/instabot.py#1147]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows

## Python Version?
3

## Description

I was wondering if you could add a feature for an idle time period that way I can run the bot from say 6am to 10pm and then stops until 6am again. A thank you for following private message option would be nice also to automatically thank new followers

Thank you,
Derek

```
no errors
```

**Comment by ChipWolf** [comment]
You could easily achieve this with a script or cron job to launch and kill the bot as required.

**Comment by ChipWolf** [comment]
This can already be achieved with the parameters available in the config.

See the `README.md`

start_at_h | int | Start program at the hour | 0
start_at_m | int | Start program at the min | 0
end_at_h | int | End program at the hour | 23
end_at_m | int | End program at the min | 59

**Comment by dgvicii** [comment]
I missed that thank you!
