### ISSUE TITLE
Unfollow module does not work!

### ISSUE THREAD

**Issue by dajul123** [instabot-py/instabot.py#1148]
## Hosting
Local Machine

#### Select one:
- [X ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 10 Home

## Python Version?
3.6.4

## Description

The Like module works fine but the bot doen´t unfollow:
.........................
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "C:\Users\Acer\Desktop\instabot.py-master\src\instabot.py", line 848, in auto_unfollow
    user_info = all_data['user']
KeyError: 'user'

I already changed the instabot.py on line 848-856 to:

   user_info = all_data['graphql']['user']
                    i = 0
                    log_string = "Checking user info.."
                    self.write_log(log_string)

                    follows = user_info['edge_follow']['count']
                    follower = user_info['edge_followed_by']['count']
                    media = user_info['edge_owner_to_timeline_media']['count']
                    follow_viewer = user_info['follows_viewer']

**Comment by dajul123** [comment]
why is the Thread closed?

**Comment by ChipWolf** [comment]
The issue format wasn't followed @dajul123 
Also, duplicate, mode 0 is the only supported function.

**Comment by ChipWolf** [comment]
Are you using the latest version of the bot @Pantic14?
