### ISSUE TITLE
Script stops working after seconds: user info list is empty!!!

### ISSUE THREAD

**Issue by JoshAbramovitz** [instabot-py/instabot.py#1151]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC 10.12.6
MAC / Windows / Linux / Android

## Python Version?
2
2 / 3

## Description

After a few seconds and either no actions at all or just 1 like, 1 follow, it logs back out.

```
Include the contents of the error.log here (if applicable).

I get something like: Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
Get media id on recent feed
```

**Comment by JoshAbramovitz** [comment]
Turns out it's a bug when you put mode 2 in this current version! Put it back to mode = 0 and it's working great

**Comment by ChipWolf** [comment]
Python 3.6
