### ISSUE TITLE
Exception on Check Version

### ISSUE THREAD

**Issue by Bl4ckFr0st** [instabot-py/instabot.py#1154]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [x ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
 Windows 

## Python Version?
2 / 3

## Description

When i try to login i got a "Exception on Check Version" and i can't fix it :/

**Comment by ziliangpeng** [comment]
@Bl4ckFr0st  Could you paste a more detailed error message or stack trace?

**Comment by Bl4ckFr0st** [comment]
![can t login](https://user-images.githubusercontent.com/14877038/38667959-d1c56514-3e3a-11e8-8717-2eed2413a862.PNG)

**Comment by Bl4ckFr0st** [comment]
I am using a VPS, probably insta blocked my ip.. :(
On my computer i can run it

**Comment by Idrisskh** [comment]
I have also login problems since yesterday when I try to login using a VPS. This screenshot will show you the problem :

![capture](https://user-images.githubusercontent.com/30605776/38678091-5ce64a6c-3e60-11e8-80d8-a31d873a16db.PNG)

It is written that the account does not exist even if it is an existing account.

**Comment by Bl4ckFr0st** [comment]
I am hosting on Microsoft Azure

**Comment by Instaerror** [comment]
When it says the username does not belong to an account where there is an account, this is SENTRY block. So you need residential IP. Or at least a VPS instagram doesn't know about.
