### ISSUE TITLE
The username does not exist when I try to log on a VPS

### ISSUE THREAD

**Issue by Idrisskh** [instabot-py/instabot.py#1156]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Python Version?
2 / 3

## Description

Type the description of your issue here.

Since yesterday, when I try to log on a VPS, Instagram say that the username of the account does not exist. I can log on local without any problem. Has someone else got the same problem ?

```
Include the contents of the error.log here (if applicable).
```

**Comment by Idrisskh** [comment]
It is not related. Yestarday, there was no problem with the JSON file and it was not able to log on anyway. I have faced the same problem few weeks ago (it has started a saturday and it was fix by Instagram the next tuesday). I face this problem only when I try to log on using a VPS.

**Comment by ziliangpeng** [comment]
Instagram recognize IP location and refuse login if it determines abnormal, in which case you'll be asked to verify account by entering a auth code (sent to phone or email).

Every time you login you face the risk, especially if you use remote host (IP location different than you).


My workaround is to save the cookies somewhere and use read that back on bot startup, so no need to login.

**Comment by ChipWolf** [comment]
Yeah, you don't want to run the bot remotely, it tends to trip Instagram's 'suspicious activity detection'.

**Comment by Idrisskh** [comment]
I think it is a different problem that the one you are speaking about. If Instagram was detecting a suspicious activity, I should get a challenge. It seem that the log in is not working on a VPS whatever the account I want to log in. Last time, this problem appear during an Instagram update (the buy bottom).

**Comment by ChipWolf** [comment]
They tend to block IP ranges of those providers
