### ISSUE TITLE
Instagram API Changes Soon

### ISSUE THREAD

**Issue by chrisoname** [instabot-py/instabot.py#1166]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [x] Other

### Operating System? (include version)
MacOS Sierra 10.12.6 

## Python Version?
2 / 3

## Description

Type the description of your issue here.

How is the new changes to the Instagram API affecting Instabot?
https://www.agorapulse.com/blog/facebook-instagram-api-changes-2018

```
Include the contents of the error.log here (if applicable).
```

**Comment by ChipWolf** [comment]
We don't use the API.
