### ISSUE TITLE
Log In Error 

### ISSUE THREAD

**Issue by Therichiefleming** [instabot-py/instabot.py#1171]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MacOS High Sierra 10.13.3 2017 Macbook Pro 

## Python Version?
Anaconda so i'm assuming both? (New to this, sorry)

## Description

While running the example.py file, I get a log in error saying:

13.04.2018_11:19 Instabot v1.2.0 started at 13.04.2018 11:19:

13.04.2018_11:19 Trying to login as jdmbois...

13.04.2018_11:19 Login error! Connection error!
13.04.2018_11:19 Removing already liked medias..
xxxxxxx user info list is empty!!! xxxxxxxxx
==============================
Upss hajka is already in ex user list...
==============================
==============================
Upss hajka is already in ex user list...
==============================
==============================

I then went to check on my Instagram app and it says that a suspicious log in happened showing my location. I am running just the regular wifi I have always used both phone and laptop. I have multiple instagram accounts and it doesn't give me the option to verify a code or anything, it just makes me chose between "This was me" and "This wasn't me". Any ideas on whats going on here or how to get out of this loop? Thanks!

```
Include the contents of the error.log here (if applicable).
```

**Comment by Nuxwors** [comment]
I have the same problem but I don't get "This was me" and "This wasn't me" option and for you, you should press "This was me"

**Comment by Instaerror** [comment]
If sentry block then you wont get in and you wont get this was me. Occasionally when you get the this was me, even if you press this was me, it wont let you in for 24 hours.

**Comment by Nuxwors** [comment]
this is better : https://www.youtube.com/watch?v=6SFFvgf2SL0

**Comment by Therichiefleming** [comment]
Looks nice, but sadly Windows only :(

**Comment by Kadabrah** [comment]
API change from Instagram, hopefully an updated bot will be up soon. By changing its API, they are restricting access to Instagram for third party apps. This actually might be the end of bots since some fonctions wont be possible anymore.
