### ISSUE TITLE
Would like to Unfollow massively.

### ISSUE THREAD

**Issue by Kadabrah** [instabot-py/instabot.py#1178]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
 Windows

## Python Version?
2 / 3

## Description

Type the description of your issue here.
Hey guys, i would like to unfollow massively but the bot always tries to unfollow people it started to follow. Is there a way to change it so it picks randomly from the following pool ? Thank you for your hard work and time <3
```
Include the contents of the error.log here (if applicable).
```

**Comment by sjsh99** [comment]
Help for the same would be appreciated
Currently running on "Mode 0" and constantly getting a weird statement that "There is nobody to unfollow". Wanted to set up Mode 2 but didn't work initially
