### ISSUE TITLE
Logs out after 1 Like/Follow/Unfollow attempt

### ISSUE THREAD

**Issue by Swayzee808** [instabot-py/instabot.py#1179]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
 Windows

## Python Version?
3

## Description

have updated everything as of today, finally got mode 2 working however it logs me out immediately after attempting one of everything. on Mode 1 or 3 it keeps saying "Except on get media" or get user info "except on get_info". Completely new to this so just trying to understand.

``` 


```
13.04.2018_19:59 Trying to unfollow: 5354873018
13.04.2018_19:59 Unfollow: 5354873018 #1 of 0.
13.04.2018_19:59 Pausing for 16 seconds... 1 of 0
13.04.2018_20:00 Logout: likes - 1, follow - 0, unfollow - 1, comments - 0.
13.04.2018_20:00 Bot work time: 0:01:10.611360
13.04.2018_20:00 Logout success!

**Comment by Instaerror** [comment]
#1153 fixed

**Comment by ChipWolf** [comment]
Only mode 0 is supported
