### ISSUE TITLE
Instabot not working properly after last night

### ISSUE THREAD

**Issue by Blademontane** [instabot-py/instabot.py#1182]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ x] Technical Help
- [ ] Other

### Operating System? (include version)
 Windows 7
## Python Version?
3

## Description

Type the description of your issue here.

Yesterday, the instabot stopped working. I found the fix by looking on here https://github.com/instabot-py/instabot.py/issues/1153, and it ran, for about 5 minutes, then stopped working. I ran it directly from cmd, and it was running fine, but it was saying 'looks like there is nobody to unfollow', then after following someone, it unfollowed them directly afterwards. When I edit with Python, and run module from there, I get the error log below immediately, and does not even run the module fully.
Anyone know of this problem and how to fix it?
```
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\instabot.py-master\example.py", line 6, in <module>
    from src import InstaBot
  File "C:\Users\Admin\Downloads\instabot.py-master\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\Admin\Downloads\instabot.py-master\src\instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "C:\Users\Admin\Downloads\instabot.py-master\src\userinfo.py", line 5, in <module>
    import requests
ImportError: No module named requests
```

**Comment by Instaerror** [comment]
Login as administrator on command prompt, then type pip install requests

**Comment by Blademontane** [comment]
@Instaerror It says Requirement already satisfied
Comes up like this https://i.imgur.com/uPHYMDL.png

For the moment, I set following and unfollowing per day to 0, so it's only liking and commenting.

**Comment by ChipWolf** [comment]
python3 -m pip install -r requirements.txt --upgrade
python3 example.py

**Comment by Blademontane** [comment]
I don't understand what I should do with that advice

**Comment by Blademontane** [comment]
@ChipWolf It says requirement already up to date
