### ISSUE TITLE
Error in line 50, 231, 300, 41, 354, 339, and 357

### ISSUE THREAD

**Issue by jonathanfilbert** [instabot-py/instabot.py#1186]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Linux (Lubuntu)
## Python Version?
2 / 3
3
## Description

Type the description of your issue here.
It returns this:

Traceback (most recent call last):
  File "example.py", line 50, in <module>
    'follow', 'follower', 'gain', '.id', '_id', 'bags'
  File "/home/jonathanfilbert/Desktop/instabot.py/src/instabot.py", line 231, in __init__
    self.login()
  File "/home/jonathanfilbert/Desktop/instabot.py/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/home/jonathanfilbert/Desktop/instabot.py/src/userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Include the contents of the error.log here (if applicable).
*my errors.log seems empty, have tried gedit error.log, empty.*

**Comment by jonathanfilbert** [comment]
Nevermind, fixed.

**Comment by ProgrammingDude** [comment]
Hi, one question.

How did you fix it?

**Comment by yesdudeyes** [comment]
Hello there,

This is the exact problem i encountered.
How did you fix it?

Thanks.

**Comment by ChipWolf** [comment]
Duplicate of #1153
