### ISSUE TITLE
Like last media from a list of users

### ISSUE THREAD

**Issue by rorloj** [instabot-py/instabot.py#1194]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so; have you tried running the code on your local machine?
#### Select one:
- [ ] Bug
- [X] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Windows 10
## Python Version?
2 / 3
3.6
## Description

Type the description of your issue here.

Is it possible to like the last media of a list of users?? I found on issue #292 how to like 12 most recent but I'd like to just like the most recent.
Thanks
Include the contents of the error.log here (if applicable).
```

**Comment by virginsince1997** [comment]
Please send a screenshot

**Comment by rorloj** [comment]
![errorpy](https://user-images.githubusercontent.com/36339871/38780837-f201f6b8-40dc-11e8-9453-a259babebdad.JPG)

line 10 is when the for part starts "for username in users:"

![image](https://user-images.githubusercontent.com/36339871/38780865-489fabf0-40dd-11e8-8c9c-ecf5f972912e.png)

**Comment by virginsince1997** [comment]
Lol sorry my bad, this is for another project, delete the thread, and reopen

**Comment by rorloj** [comment]
LOL, thanks for your time anyways mate !

**Comment by Damny89** [comment]
How to add time between like?
