### ISSUE TITLE
Problem with pip "ModuleNotFoundError: No module named 'pip'"

### ISSUE THREAD

**Issue by nicolobi** [instabot-py/instabot.py#1199]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Windows

## Python Version?
2.7

## Description
Problem with pip ! 
Type the description of your issue here.
I have also add pip in path... I don't understand why i have this problem...
```
Include the contents of the error.log here (if applicable).
C:\Windows\system32>pip
Traceback (most recent call last):
  File "c:\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python27\Scripts\pip.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'pip'

**Comment by ugurozturk** [comment]
This issue is not related to this repo. Please use google for it
