### ISSUE TITLE
raise JSONDecodeError("Expecting value",s , err.value) from None

### ISSUE THREAD

**Issue by dgimenezrodriguez** [instabot-py/instabot.py#1203]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ x] Other

### Operating System? (include version)
Windows 7

## Python Version?
3

## Description

When I run Instabot from the terminal in Windows and Ubuntu I get the error: raise JSONDecodeError ("Expecting value", s, err.value) from None

```
Include the contents of the error.log here (if applicable).
```

**Comment by kawauti** [comment]
Same thing here. Im using Windows 8.

**Comment by striderwhite** [comment]
Same here.

**Comment by instabot-master** [comment]
hi. I have the same issue. the bot is not running. when starting, the bot window closes immediately. Error message:

 line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mekeloko** [comment]
Same here... The bot suddenly stopped working with the same message and didnt start again

**Comment by kawauti** [comment]
I used this tip and worked for me:

For those who are running in mode 0 can do a temporarly fix by replacing **line 300** from **instabot.py**

self.user_id = ui.get_user_id_by_login(self.user_login)
self.user_id = YOUR_USER_ID

if you dont know your user id you can get it from https://codeofaninja.com/tools/find-instagram-user-id

From user **Maty197**

**Comment by budstankz** [comment]
how to fix this?

**Comment by husligc** [comment]
Did this but it messed up the commenting function.  It puts all the comments on the same picture.  any idea on how to fix that?

**Comment by grishabh282** [comment]
> hi. I have the same issue. the bot is not running. when starting, the bot window closes immediately. Error message:
> 
> line 357, in raw_decode
> raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

can you tell me how you have debug it.
