### ISSUE TITLE
raspberry pi installation requirements?

### ISSUE THREAD

**Issue by canitb** [instabot-py/instabot.py#1205]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?
Yes.

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Raspberry PI 3

## Python Version?
2 / 3
Version 2.7.13

## Description

I have heard that the script was possible to use on a raspberry pi, and when I add the installation command: sudo pip install requirements.txt 

```
Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt
```

**Comment by Michael-Brooks** [comment]
You need to add `-r` for recursive installation. It should look like `sudo pip install -r requirements.txt`.

If the pip command doesn't work, then try using pip3 and python3 instead.
