### ISSUE TITLE
Suspicious Login Attempt/Connection Error

### ISSUE THREAD

**Issue by reega** [instabot-py/instabot.py#1206]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows

## Python Version?
3

## Description

Type the description of your issue here.
This issue seems to only have started in the last day or two, I get a "connection error" which is caused by Instagram thinking this is a suspicious login attempt, so i logon to the app or website and say this was me. Try the bot again and the same thing happens no matter how many times i say this was me
```
Include the contents of the error.log here (if applicable).
```

**Comment by striderwhite** [comment]
I get this as well. I opened the instagram app and it let me know it saw a suspicious login attempt, after I dismissed it the problem seems to have gone away.

**Comment by mattkoen** [comment]
Same thing is happening to me as **striderwhite** described but after I dismiss it on the Instagram website the problem repeats itself i.e. the suspicious login attempt warning message appears again on the website. I am using an AWS server for hosting...

**Comment by sethbarron25** [comment]
I have the same issue but on google cloud, here's the error I get. I've looked through as many previous cases as I can but can't seem to find anything to narrow down the problem. any help would be appreciated. thank you
 
17.04.2018_18:00 Login error! Check your login data!
17.04.2018_18:00 Removing already liked medias..
17.04.2018_18:00 Trying to unfollow #1: 
17.04.2018_18:00 Looks like there is nobody to unfollow.
17.04.2018_18:00 Removing already liked medias..
17.04.2018_18:01 Removing already liked medias..
17.04.2018_18:01 Removing already liked medias..
17.04.2018_18:01 Removing already liked medias..
^CTraceback (most recent call last):
  File "example.py", line 67, in <module>
    bot.new_auto_mod()
  File "/home/scenttechllc/instabot.py/src/instabot.py", line 703, in new_auto_mod
    time.sleep(3)
KeyboardInterrupt

**Comment by davidhearnsmith** [comment]
Use residential IP, as far as we can tell, all others have been blocked.
Unless anyone using one.

**Comment by reega** [comment]
My problem just went away, not sure what was causing it. Maybe leave it for a day or two then try again?
