### ISSUE TITLE
All Comments on The Same Photo

### ISSUE THREAD

**Issue by husligc** [instabot-py/instabot.py#1208]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / **Windows** / Linux / Android

## Python Version?
2 / **3**

## Description

I recently fixed the issue with the userID in the code around line 300 with my own user ID and now the bot comments only on one photo, for example 62 comments on 1 person's photo instead of dispersed.  any ideas?

```
Include the contents of the error.log here (if applicable).
```

**Comment by husligc** [comment]
Anybody else having this problem? still haven't solved it

**Comment by aldonbmorris** [comment]
I was having it comment on the same photo, back-to-back, the other day. However, I shut the program down until I get the time to look into a cause/fix.

**Comment by heldausberlin** [comment]
Same here.

**Comment by husligc** [comment]
Anybody making progress on this? Killing me

**Comment by maxxfly** [comment]
same here... and try to follow the same person

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
