### ISSUE TITLE
Question About accepting follow requests

### ISSUE THREAD

**Issue by HaydenSeward** [instabot-py/instabot.py#1209]
This there a way to use instabot to accept follower requests on insagram

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
