### ISSUE TITLE
Getting excepts on get media

### ISSUE THREAD

**Issue by aesptux** [instabot-py/instabot.py#121]
Hello, thank you for the bot.

I keep getting excepts while the bot is trying to get media. My bot code is the following:

```
from instabot import InstaBot
bot = InstaBot('myuser', 'mypass',
    like_per_day=500,
    media_max_like=200,
    follow_per_day=20,
    unfollow_per_day=0,
    comments_per_day=0,
    tag_list=['tags', 'and', 'more', 'tags'],
    log_mod=0
)
bot.auto_mod()
```

Example of the errors:

```
Trying to like media: 1282648422965216196
Liked: 1282648422965216196. Like #93.
Get media id by tag: success
Except on get_media!
Get media id by tag: lifestyle
Trying to like media: 1282656079516051656
Liked: 1282656079516051656. Like #94.
Trying to like media: 1282656075513976709
Except on like!
Get media id by tag: supercar
Trying to like media: 1282657485655882464
Liked: 1282657485655882464. Like #95.
```

Some fail, some don't

I'm using the latest version of instabot, I cloned it today.
My python version is 2.7

Thanks in advance.

P.S: why +18 tags like "boobs" are skipped? lol

**Comment by nickpettican** [comment]
Maybe it's because those tags do not have the "recently added" section (Instagram sometimes removes it temporarily when people report a lot of unappropriate content), which is where instabot takes its media from. Before adding the tags search for them and make sure this section is there :grin:

**Comment by nickpettican** [comment]
No problem :grin: ! 

It can't always be perfect, it may be because the user has a private account or something similar.

**Comment by LevPasha** [comment]
@aesptux first i don't test it on 2.7. Second - you can make some changes and get you exception.

**Comment by polaroi8d** [comment]
Hello @aesptux still have your problem? Can i closed this issue?

**Comment by heydenis** [comment]
Sorry to jump in on this. I have the same issue, except that I get except on get media on every hashtag.
I checked them manually on instagram, and they both have a "Most popular section" and a "Most recent section"

**Comment by Leastham2** [comment]
was reading this and im not sure if their is a fix for this guys exact problem but i did try to add in more hashtags to be searched. 

i get this as soon as i log in and start "Except on get_media!"

i found that adding hashtags with "#" trigger this "except on get_media!"
that the actual '#' is what my issue opened up notepad and removed all the "#" from my tag list and its back working :) 

sorry if this doesnt help you. but can helpful to know that the "#" will cause this(cant say this is the only thing causing this)

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
