### ISSUE TITLE
ModuleNotFoundError: No module named 'src' when starting to run the file

### ISSUE THREAD

**Issue by staiema** [instabot-py/instabot.py#1210]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
 Windows 

## Python Version?
 3

## Description

Type the description of your issue here.
So when I try to start the Bot, the Terminal says : 
"c:/Users/Myname/Desktop/Insta Bot.py", line 6, in <module>
    from src import InstaBot
ModuleNotFoundError: No module named 'src'
```
Include the contents of the error.log here (if applicable).
```E0401:Unable to import 'src'
E0401:Unable to import 'src.check_status'
E0401:Unable to import 'src.feed_scanner'
E0401:Unable to import 'src.follow_protocol'
E0401:Unable to import 'src.unfollow_protocol'

**Comment by husligc** [comment]
Would it by chance be the space you have Insta Bot.py in line 6?

**Comment by zhen737** [comment]
What is the path of your "src" file?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
