### ISSUE TITLE
Except on get info!

### ISSUE THREAD

**Issue by dgimenezrodriguez** [instabot-py/instabot.py#1212]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ x] Other

### Operating System? (include version)
 Windows 

## Python Version?
 3

## Description

Type the description of your issue here.
when I try to access mode 1 it gives me the following error: Except on get info!
```
Include the contents of the error.log here (if applicable).
```

**Comment by CupCakeArmy** [comment]
Same here, running locally or on a server in docker.

Stack Trace:
```
instabot    | 18.04.2018_12:49 Instabot v1.2.0 started at 18.04.2018 12:49:
instabot    |
instabot    | 18.04.2018_12:49 Trying to login as healthmachine...
instabot    |
instabot    | Traceback (most recent call last):
instabot    |   File "./app.py", line 8, in <module>
instabot    |     bot = InstaBot(**data)
instabot    |   File "/app/src/instabot.py", line 231, in __init__
instabot    |     self.login()
instabot    |   File "/app/src/instabot.py", line 300, in login
instabot    |     self.user_id = ui.get_user_id_by_login(self.user_login)
instabot    |   File "/app/src/userinfo.py", line 41, in get_user_id_by_login
instabot    |     all_data = json.loads(info.text)
instabot    |   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
instabot    |     return _default_decoder.decode(s)
instabot    |   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
instabot    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
instabot    |   File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
instabot    |     raise JSONDecodeError("Expecting value", s, err.value) from None
instabot    | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by CupCakeArmy** [comment]
Please see issue #1211

**Comment by andrewsegas** [comment]
Guys, here the get user info error is fixed
#1218

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
