### ISSUE TITLE
Bot Logs in, but can't execute follow unfollow protocols

### ISSUE THREAD

**Issue by theblanksign** [instabot-py/instabot.py#1213]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ x] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [] Technical Help
- [ ] Other

### Operating System? (include version)
MAC El Capitan 10.11.6
## Python Version?
3

## Description

Bot Logs in, but can't execute follow unfollow protocols
```
18.04.2018_18:09 xxxxxxxx login success!
18.04.2018_18:09 xxxxxx : Get media id on recent feed 
 18.04.2018 18:09
18.04.2018_18:09 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
18.04.2018_18:09 xxxxxxx : Get media id on recent feed 
 18.04.2018 18:09
18.04.2018_18:09 Except on get media!!
18.04.2018_18:09 ======> Get media id by Tag <======
18.04.2018_18:09 Get media by user success!
18.04.2018_18:09 Current Index = 34 of 46 medias
Traceback (most recent call last):
  File "example.py", line 82, in <module>
    unfollow_protocol(bot)
  File "/Users/xxxxx/Desktop/instabot.py-master/src/unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "/Users/xxxxxx/Desktop/instabot.py-master/src/follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "/Users/xxxxx/Desktop/instabot.py-master/src/feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "/Users/xxxxx/Desktop/instabot.py-master/src/likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "/Users/xxxxxx/Desktop/instabot.py-master/src/likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
18.04.2018_18:09 Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
18.04.2018_18:09 Bot work time: 0:00:47.359323
18.04.2018_18:09 Logout success!```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
