### ISSUE TITLE
Feature Request - Add ability to detect if commenting on video or photo, to adjust comment

### ISSUE THREAD

**Issue by ItsPaPPy** [instabot-py/instabot.py#1214]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [X] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows Server 2016

## Python Version?
3

## Description

I would like to see the ability to detect if the post is a video or a photo. And then adjust my comment accordingly. That way when I use comments I don’t say nice photo, when it’s a video.

**Comment by velivelo** [comment]
There is a key/sub-key named "is_video" in medias returned by get_medias_by_tag method.

**Comment by ItsPaPPy** [comment]
can you explain, @velivelo how to accomplish this?

**Comment by velivelo** [comment]
First you fill the media list :
`bot.get_media_id_by_tag(your_tag)`
Then you can iterate through the media list : 
`for media in bot.media_by_tag:
    print(media["is_video"])`
Or maybe `["is_video"]` is a sub-key of `["node"]` or I don't know.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
