### ISSUE TITLE
after fixing #1153 still not unfollow

### ISSUE THREAD

**Issue by marcosenno88** [instabot-py/instabot.py#1217]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 7

## Python Version?
 3

## Description

Type the description of your issue here.

```
trying to unfollow #1
```
Maby in the hundreds of comments i've lost some fix....
Someone can tell me why the bot doesn't unfollow anymore.
i'm running insabot v1.2.0

![oggi](https://user-images.githubusercontent.com/37532558/38981508-e11c796e-43bf-11e8-9bd1-170349ac9215.JPG)

**Comment by andrewsegas** [comment]
fix this one first
#1218

i already fixed unfollow but the merge with my project is too long

**Comment by marcosenno88** [comment]
@andrewsegas i fixed the #1218 but bhe situation is the same

**Comment by andrewsegas** [comment]
@marcosenno88 your problem is with unfollow because they use the same schema.
check here: https://github.com/andrewsegas/instaboost
the source instabot.py have been fixed you can copy, or run instaboost project

**Comment by marcosenno88** [comment]
@andrewsegas ty i start instaboost and seems the works but now the are a new issue
![cattura](https://user-images.githubusercontent.com/37532558/38996673-fd93010e-43eb-11e8-9f2f-2283d2e0c8c4.JPG)

**Comment by constantinosbou** [comment]
With instaboost i get ''Looks like there is nobody to unfollow.''

**Comment by SeanGallaghergit** [comment]
![screenshot_2](https://user-images.githubusercontent.com/29860195/39241166-dee2733e-487d-11e8-8179-d22783f6cf6d.png)

Exe is working fine except it only unfollows 1 user and then keeps saying "Looks like there is nobody to unfollow"

**Comment by andrewsegas** [comment]
Guys, @SeanGallaghergit @constantinosbou . Please, if you're talking about instaboost, open an issue there and i can check what is going on

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
