### ISSUE TITLE
Fixed JSON/UserID Bug.  Now all comments on 1 post!

### ISSUE THREAD

**Issue by husligc** [instabot-py/instabot.py#1219]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / **Windows** / Linux / Android
windows 10
## Python Version?
2 / **3**

## Description

Type the description of your issue here.
Fixed the JSON decoder error by replacing the userID line ~300 with my actual insta userid.  Now the bot will do all of my normal comments on just 1 person's post.  Obviously not ideal.  Please help
```
Include the contents of the error.log here (if applicable).
```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
