### ISSUE TITLE
"Removing already liked media"

### ISSUE THREAD

**Issue by marcelcaferati** [instabot-py/instabot.py#1223]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
windows server and  windows 10

## Python Version?
2.6 and 3

## Description

When running example.py out of the box, it logs in but prints an error to check the username and password, after that it keeps spaming "Removing already liked media",

If you have set to unfollow it will keep trying to unfollow a user with ID 1 and then back to "Removing already liked media"

**Comment by mwc320** [comment]
Ever figure this out?

**Comment by marcelcaferati** [comment]
yea, i took it out of my AWS server and started running locally, it was an
IP thing

Em dom, 10 de jun de 2018 às 00:01, mwc320 <notifications@github.com>
escreveu:

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
