### ISSUE TITLE
Bot logs out after a pause

### ISSUE THREAD

**Issue by staiema** [instabot-py/instabot.py#1226]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 

## Python Version?
 3

## Description

Type the description of your issue here.
hello there,
the bot logs out after 1 minute working. It likes 1 picture and unfollows one. then it logs out : 

22.04.2018_11:35 Trying to unfollow: 5652885946
22.04.2018_11:35 Unfollow: 5652885946 #1 of 0.
22.04.2018_11:35 Pausing for 20 seconds... 1 of 0
22.04.2018_11:36 Logout: likes - 1, follow - 0, unfollow - 1, comments - 0.
22.04.2018_11:36 Bot work time: 0:01:16.227567
22.04.2018_11:36 Logout success!

**Comment by emiccheese** [comment]
Same, there needs to be a way to automate the runs!

**Comment by emiccheese** [comment]
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot('Username', 'Password',
    like_per_day=800,
    comments_per_day=120,
    tag_list=['fitness', 'Herbalife'],
    max_like_for_one_tag=80,
    follow_per_day=300,
    follow_time=2 * 60
)

bot.auto_mod()
```
This works for me, replace your example.py file with this and include all other parameters you need! This one only likes 2 pictures a minute following the hashtags.
Enjoy!

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
