### ISSUE TITLE
Python Code Error - 22.04.2018.

### ISSUE THREAD

**Issue by blackracoorino** [instabot-py/instabot.py#1227]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine? I'm running code on my local machine

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Windows 10 Pro 64-bit

## Python Version?
2 / 3
Both

## Description

When I type 'python example.py' this text shows up. Good luck!

```
PS C:\Users\Aljosa Trninic\Desktop\instabot.py-master> python example.py
22.04.2018_11:41 Instabot v1.2.0 started at 22.04.2018 11:41:

22.04.2018_11:41 Trying to login as atrninicc...

Traceback (most recent call last):
  File "example.py", line 44, in <module>
    unfollow_whitelist=[])
  File "C:\Users\Aljosa Trninic\Desktop\instabot.py-master\src\instabot.py", line 231, in __init__
    self.login()
  File "C:\Users\Aljosa Trninic\Desktop\instabot.py-master\src\instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\Aljosa Trninic\Desktop\instabot.py-master\src\userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "C:\Users\Aljosa Trninic\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Aljosa Trninic\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Aljosa Trninic\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by srwiseman** [comment]
Everything is broken due to Instagram locking down the endpoint. You can add my fix #1225 to log in a get some functionality, but lots of things have to be completely rewritten fro full functionality.

**Comment by atrninicc** [comment]
Still doesn't work. Can you send me your 'src/userinfo.py' and 'src/instabot.py' files? Thanks!
![screenshot_1](https://user-images.githubusercontent.com/26109491/39098840-26b0f6ae-4671-11e8-9fe0-6839071a40ac.jpg)

**Comment by greenglass** [comment]
@atrninicc that is just simply a python formatting issue. Python is very specific on everything being space correctly. Make sure your code lines up, see how the red line has everything lined up in the same column...

![image](https://user-images.githubusercontent.com/10258394/39138494-e646319c-46d4-11e8-8833-025d93a93deb.png)

**Comment by atrninicc** [comment]
@instabot-master instabot.py-master/src/instabot.py

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
