### ISSUE TITLE
login OK and then nothing

### ISSUE THREAD

**Issue by FlavianoMucedda** [instabot-py/instabot.py#1228]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [x] Other

### Operating System? (include version)
MAC high sierra
## Python Version?
2.710

## Description

when i launch the bot it logs without any problem and then I have this running in a loop : 

22.04.2018 16:56 MY_LOGIN : Get user info
22.04.2018 16:56
22.04.2018_16:56 Except on get_info!

Someone can help me?

```
Include the contents of the error.log here (if applicable).
```

**Comment by stbernardy** [comment]
Why was this closed with no explanation? What was the solution?

**Comment by FlavianoMucedda** [comment]
i was tempban by instagram because i've manually liked a lot of pictures in the same time of the bot...

that's the solution :D
