### ISSUE TITLE
Login error! Check your login data!

### ISSUE THREAD

**Issue by ocit** [instabot-py/instabot.py#1233]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] I have searched for other issues with the same problem. (including #1153)
- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Ubuntu 16.04.4 x64 (digital ocean droplet)

## Python Version?
3

## Description
Getting this error when trying to launch example.py with my credentials from ssh terminal.
I am 100% sure that my username and password is correct. I run this script in digitalocean droplet via ssh mac terminal.

what i have done :
- make sure username and password are correct 
- use username instead of email to login
- click "it was me" when instagram ask "suspicious login"
- make sure 2FA is off

but the problem still the same. Here are the logs i got.

23.04.2018_08:02 Login error! Check your login data!
23.04.2018_08:02 Removing already liked medias..
23.04.2018_08:02 Trying to unfollow #1:
23.04.2018_08:02 Looks like there is nobody to unfollow.
23.04.2018_08:02 Removing already liked medias..
23.04.2018_08:02 Removing already liked medias..
23.04.2018_08:02 Removing already liked medias..
23.04.2018_08:02 Removing already liked medias..
23.04.2018_08:02 Removing already liked medias..
23.04.2018_08:02 Removing already liked medias..
23.04.2018_08:02 Removing already liked medias..
23.04.2018_08:02 Removing already liked medias..
23.04.2018_08:02 Removing already liked medias..
23.04.2018_08:02 Removing already liked medias..
23.04.2018_08:02 Removing already liked medias..
23.04.2018_08:02 Removing already liked medias..
23.04.2018_08:02 Removing already liked medias..
23.04.2018_08:02 Removing already liked medias..

**Comment by andrewsegas** [comment]
try to use proxy, the problem is that some VPS ip's are suspicious ip for instagram.

**Comment by marcelcaferati** [comment]
It started friday, apparently everyone has the same problem, I tried running localy, on my cloud pc and also tried changing the pc's IP address, it is a real issue

**Comment by greenglass** [comment]
I saw this happen on Friday also, but it is up and working today as of Monday 4/23/18, didn't change anything. Just gave it time.

**Comment by creeptosis** [comment]
waited 1-2 days tried again, still have the same problem

**Comment by emirbeytekin** [comment]
very bad news

**Comment by orkunasa** [comment]
I have also this issue on Digital Ocean servers

**Comment by VariyaKrupal** [comment]
Facing the same issue on google cloud compute engine vm

**Comment by sagepierce** [comment]
same issue with google cloud, when I run in terminal on mac everything works perfect however I hate leaving my mac on all the time in order for this to work. please fix this issue soon =)

**Comment by andrewsegas** [comment]
PEOPLE, it's NOT an issue for instabot, the problem is that ALL THESE IPS are suspicious ips for INSTAGRAM... then they (INSTAGRAM) will block your login.
YOU CAN use the proxy configuration inside INSTABOT to circumvent this IP and after that, log in with AMAZON, GOOGLE and other CLOUD computers that you want. AND BE HAPPY
i love you

**Comment by bkurnaz** [comment]
it doesn't work because your ip address got probably banned from instagram. Use a proxy and your issue should be solved

**Comment by ocit** [comment]
@andrewsegas @bkurnaz thank you for your comment. Yeah, perhaps if the code run in local, but doesn't work in cloud is because its IP is suspicious.

Anyone can help to give an example of proxy configuration? or recommendation article to set up proxy in cloud. Sorry I am a total newbie here. I already try some thread to set up proxy in ubuntu server but all of them always have problem in certain step.

**Comment by whmori17** [comment]
I tried to use a proxy and it works but not for entire. Now I get "Login error! Connection error!" because Instagram sends me a text with the security code. Where can I set that code within example.py? If I can't set it, I can't proceed.

**Comment by andrewsegas** [comment]
@whmori17 you can set it in your browser, instagram will just ask once as i know, and after try to log in again

**Comment by whmori17** [comment]
@andrewsegas I tried but it didn't work. I had to remove that kind of security. Now it's working but I have some proxy issues on AWS (proxy connection refused)) and I'm running example.py on my pc. I think it could depend on the proxy provider and the AWS instance...

**Comment by dexs99** [comment]
@whmori17 you use private proxy or free proxy?

**Comment by EntaThaVoid** [comment]
The bot was working perfectly for about 3 weeks. I decided to run another instance of it for another account and got a bunch of errors messages about trackbacks. Decided to go back to just one acct and now that instance of the bot is giving me the error described by the OP.

I've deleted the bot and redownloaded it, only changing my username and password. Still nothing. I purchased a proxy and get even weirder error messages that I can't post here cause the bot isn't recording anything in the error logs (another bug?).

Any advice? Has anyone fixed this "Login error! Check your login data!" issue?
![botfuckery](https://user-images.githubusercontent.com/42783318/44922056-47c66100-ad12-11e8-99c3-4f18ebc27ae6.png)

**Comment by alex-s435** [comment]
> The bot was working perfectly for about 3 weeks. I decided to run another instance of it for another account and got a bunch of errors messages about trackbacks. Decided to go back to just one acct and now that instance of the bot is giving me the error described by the OP.
> 
> I've deleted the bot and redownloaded it, only changing my username and password. Still nothing. I purchased a proxy and get even weirder error messages that I can't post here cause the bot isn't recording anything in the error logs (another bug?).
> 
> Any advice? Has anyone fixed this "Login error! Check your login data!" issue?
> ![botfuckery](https://user-images.githubusercontent.com/42783318/44922056-47c66100-ad12-11e8-99c3-4f18ebc27ae6.png)

I have the same!!!
Did you fix it????

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
