### ISSUE TITLE
Blacklisted tags are being ignored

### ISSUE THREAD

**Issue by CazGirl** [instabot-py/instabot.py#1234]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 10

## Python Version?
3

## Description

Type the description of your issue here.
tag_blacklist is ignoring blacklisted words.

tag_list=['gaming']
tag_blacklist=['pubg']

Bot will still like posts with both #gaming and #pubg 

```
Include the contents of the error.log here (if applicable).
```

**Comment by spud-dog** [comment]
Yes...! I'm having exactly the same issue as stated in #1142. Consistently seeing blacklisted tags appearing in posts the bot likes. Some of this is likely attributable to the comments being edited after the bot has liked the post... but certainly not at this frequency, where I've checked this most of the posts comments have not been edited.

**Comment by jaynemharper** [comment]
I am having the same issue. The instabot likes photos even with blacklisted tags.

What gives??

**Comment by olaims** [comment]
Same problem here.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
