### ISSUE TITLE
after fix the unfollow issue is still present

### ISSUE THREAD

**Issue by instabot-master** [instabot-py/instabot.py#1238]
## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / xWindows / Linux / Android

## Python Version?
2 / x3

## Description
Hi guys,
so for me after using the latest version of the bot, the issue with the not unfollowing is still existend.
Hence,
1) could some please post here how to resolve this as all the other issues did not provide sufficient answer
2) could someone please provide a fix for the mass-unfollow of mode 5? which is also not working currently.

Thanks ;)

**Comment by bodeezl** [comment]
mine doesnt even unfollow in the normal mode, just says unfollow #1 and never unfollows anyone, 
anyone else have this issue?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
