### ISSUE TITLE
Instabot Mode 5 Traceback error

### ISSUE THREAD

**Issue by jonathanfilbert** [instabot-py/instabot.py#1239]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Linux 4.13.0-37-generic #42-Ubuntu
## Python Version?
2 / 3
3
## Description

Type the description of your issue here.
Tried running a mode 5, recieved errors :
**
25.04.2018_00:19 jonathanfilbertt : Get media id on recent feed 
 25.04.2018 00:19
25.04.2018_00:19 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
25.04.2018_00:20 jonathanfilbertt : Get media id on recent feed 
 25.04.2018 00:20
25.04.2018_00:20 Except on get media!!
25.04.2018_00:20 ======> Get media id by Tag <======
25.04.2018_00:20 Get media by user success!
25.04.2018_00:20 Current Index = 27 of 66 medias
Traceback (most recent call last):
  File "example.py", line 99, in <module>
    unfollow_protocol(bot)
  File "/home/jonathanfilbert/Desktop/instabot.py/src/unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "/home/jonathanfilbert/Desktop/instabot.py/src/follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "/home/jonathanfilbert/Desktop/instabot.py/src/feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "/home/jonathanfilbert/Desktop/instabot.py/src/likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "/home/jonathanfilbert/Desktop/instabot.py/src/likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
25.04.2018_00:20 Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
25.04.2018_00:20 Bot work time: 0:00:50.036262
25.04.2018_00:20 Logout success!
**

Include the contents of the error.log here (if applicable).
**I have pasted the errors.log content into  [Pastebin](https://pastebin.com/wQEyBWrW)  since it's got more than 1k lines somehow :smiley: **

**Comment by ChipWolf** [comment]
We only support mode 0
