### ISSUE TITLE
Cannot find module in mac osx

### ISSUE THREAD

**Issue by dvyama** [instabot-py/instabot.py#1240]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC OS X El Captain

## Python Version?
2 

## Description

I managed to install the bot with the following command:

$ sudo -H pip install -r requirements.txt
Collecting requests (from -r requirements.txt (line 1))

which seemed to work, however when trying to run it I got:

$ python example.py
Traceback (most recent call last):
File "example.py", line 6, in 
from src import InstaBot
File "/Users/alfg/Desktop/instabot.py-master/src/init.py", line 1, in 
from .instabot import InstaBot
File "/Users/alfg/Desktop/instabot.py-master/src/instabot.py", line 6, in 
from .userinfo import UserInfo
File "/Users/alfg/Desktop/instabot.py-master/src/userinfo.py", line 5, in 
import requests
ImportError: No module named requests

I then tried "sudo -H pip install requests" as well as putting the file "example.py" in the src folder, as some users suggested. The result is the same for me. What could go wrong?

**Comment by ChipWolf** [comment]
```
sudo python3 -m pip install -r requirements.txt --upgrade
```

**Comment by dvyama** [comment]
My version is python, so I used python insteadof "python3", which however gave the same result.

**Comment by dvyama** [comment]
My version is python 2, so I used python instead of "python3", which however gave the same result.
