### ISSUE TITLE
Can save session to avoid login for each run??

### ISSUE THREAD

**Issue by sabloger** [instabot-py/instabot.py#1241]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Linux

## Python Version?
3

## Description

Hi there,
Is there any way to save login session to avoid login for each run?? This issue increases risk of get banned!

**Comment by velivelo** [comment]
Yes, you can save instabot.s with pickle.

**Comment by emiccheese** [comment]
Found a solution! Just add in the other parameters you need. This one is just for liking 2 pictures a minute.

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot('Username', 'Password',
    like_per_day=800,
    comments_per_day=120,
    tag_list=['fitness', 'Herbalife'],
    max_like_for_one_tag=80,
    follow_per_day=300,
    follow_time=2 * 60
)

bot.auto_mod()``
```

**Comment by velivelo** [comment]
@emiccheese your solution doesn't save the session...

**Comment by emiccheese** [comment]
I'm still learning, would you care to explain ? 
Thanks!
