### ISSUE TITLE
New Instagram Policym ???

### ISSUE THREAD

**Issue by rugge89lau** [instabot-py/instabot.py#1250]
Hi guys, how work with the new standard of instagram which allows instagram to perceive the touch and scroll and then understand if you are using a bot or not?

**Comment by luxmodz** [comment]
Possibly my freaking unfollow isnt working!

**Comment by nivong** [comment]
This is not an issue with the bot.

**Comment by rugge89lau** [comment]
I know, but i didn't know where I ask

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
