### ISSUE TITLE
follow_per_day is 0, but the instabot continue following

### ISSUE THREAD

**Issue by wladneto** [instabot-py/instabot.py#1252]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [ x] 3.x

## Description of your issue

```
QUESTION
In my config the parameter follow_per_day is 0, but the instabot continue following... 
what's is happening? :(

I want dont follow no one...

My Instabot is in v1.2.0 
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```
-----

**Comment by nivong** [comment]
Try and read your own stuff again. How do you think we can help if you do not fill in the original issue template?

**Comment by wladneto** [comment]
Hello! I tried to change password in my instagram and the bot Worked normally... :)

Thanks!
