### ISSUE TITLE
-bash: /usr/bin/env python: No such file or directory

### ISSUE THREAD

**Issue by giovannaparadiso80** [instabot-py/instabot.py#1253]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC High Sierra 10.13.3
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

When I launch the bot (that worked perfectly until yesterday) this appears to me : 

-bash: /usr/bin/env python: No such file or directory

please help me.

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by nivong** [comment]
Try and read your own stuff again. How do you think we can help if you do not fill in the original issue template?

**Comment by giovannaparadiso80** [comment]
@d1slact0r error log is too long!

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
