### ISSUE TITLE
except on get media

### ISSUE THREAD

**Issue by robsenn** [instabot-py/instabot.py#1257]
![untitled](https://user-images.githubusercontent.com/38855565/39424284-2e81d730-4c76-11e8-8859-6bb352735893.png)

please help, get this error in almost every mode except mode 0.
Thanks in advance and thank you for this awesome bot!

**Comment by Christopharo** [comment]
having same issue. bot works only on mode 0.

**Comment by aalshukri** [comment]
I am having the same issue. Only works on mode 0.

Stack trace of the error is below

```
01.05.2018_14:51 Except on get media!!
01.05.2018_14:51 ======> Get media id by Tag <======
01.05.2018_14:51 Get media by user success!
01.05.2018_14:51 Current Index = 1 of 37 medias
Traceback (most recent call last):
  File "example.py", line 105, in <module>
    bot.new_auto_mod()
  File "src/instabot.py", line 700, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "src/instabot.py", line 765, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "src/unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "src/follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "src/feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "src/likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "src/likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
01.05.2018_14:51 Logout: likes - 1, follow - 0, unfollow - 0, comments - 0.
01.05.2018_14:51 Bot work time: 0:00:51.844295
01.05.2018_14:51 Logout success!

```

**Comment by shagun2706** [comment]
i am also getting an error, except on get media.
Pls let me know how to resolve this.

**Comment by elias8808** [comment]
I'm also getting that error, someone already fix it? I want to use only mode 4, but it only lets me use mode 0

**Comment by leourl** [comment]
it only works on mode = 0 ... how can i fix it? i want to go on mode = 2

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
