### ISSUE TITLE
Unfollow 10 seconds after followe

### ISSUE THREAD

**Issue by Trazmor** [instabot-py/instabot.py#1259]
Hi.
My problem is that the bot is following someone and unfollowing a few seconds after.
I set :
`
follow_per_day = 3000,
unfollow_per_day = 3000,
follow_time= 1*60*60,
unfollow_break_min = 1*60*60,
unfollow_break_max = 5*60*60,
`

Where is the problem ?

**Comment by dexs99** [comment]
Hi,
you just have to use a little math
one day have 86400 sec...
you ask the bot to follow 3000 and unfollow 3000 for a total of 6000 interactions (are u serious?)
86400 / 6000 = 14.4 sec for each follow / unfollow
If you continue like this in a matter of hours, instagram will ban you.
read the [readme.md](https://github.com/instabot-py/instabot.py/blob/master/README.md) file and you will see an example of configuration of each value that you could use
have a nice day!

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
