### ISSUE TITLE
ImportError: No module named fake_useragent

### ISSUE THREAD

**Issue by dipumahbub** [instabot-py/instabot.py#1263]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Technical Help

### Operating System? (include version)
- [ ] MAC

## Python Version?
- [ ] 2.x
- [ ] 3.x

## Description of your issue

```


## Config

```
File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/dipu/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/dipu/Desktop/instabot.py-master/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ImportError: No module named fake_useragent
```
```

**Comment by dipumahbub** [comment]
**please guys help me, i'm not sure what's the problem** 

`instabot.py-master dipu$ pip install -r requirements.txt
Requirement already satisfied: requests in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1)) (2.18.4)
Collecting fake-useragent (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/19/78/942c4be64409dcb3ebdd5741e1b6cdc4d6153b16e9765bcecfb81547c7a1/fake-useragent-0.1.10.tar.gz
Requirement already satisfied: certifi>=2017.4.17 in /Library/Python/2.7/site-packages (from requests->-r requirements.txt (line 1)) (2018.4.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Python/2.7/site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /Library/Python/2.7/site-packages (from requests->-r requirements.txt (line 1)) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /Library/Python/2.7/site-packages (from requests->-r requirements.txt (line 1)) (1.22)
Installing collected packages: fake-useragent
  Running setup.py install for fake-useragent ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/pk/tnp9c0ps4mn5vyl6xct5pdrw0000gn/T/pip-install-YuksHk/fake-useragent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/pk/tnp9c0ps4mn5vyl6xct5pdrw0000gn/T/pip-record-T4bazd/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fake_useragent
    copying fake_useragent/__init__.py -> build/lib/fake_useragent
    copying fake_useragent/errors.py -> build/lib/fake_useragent
    copying fake_useragent/fake.py -> build/lib/fake_useragent
    copying fake_useragent/log.py -> build/lib/fake_useragent
    copying fake_useragent/settings.py -> build/lib/fake_useragent
    copying fake_useragent/utils.py -> build/lib/fake_useragent
    running egg_info
    writing fake_useragent.egg-info/PKG-INFO
    writing top-level names to fake_useragent.egg-info/top_level.txt
    writing dependency_links to fake_useragent.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'fake_useragent.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    writing manifest file 'fake_useragent.egg-info/SOURCES.txt'
    running install_lib
    creating /Library/Python/2.7/site-packages/fake_useragent
    error: could not create '/Library/Python/2.7/site-packages/fake_useragent': Permission denied
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/pk/tnp9c0ps4mn5vyl6xct5pdrw0000gn/T/pip-install-YuksHk/fake-useragent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/pk/tnp9c0ps4mn5vyl6xct5pdrw0000gn/T/pip-record-T4bazd/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/pk/tnp9c0ps4mn5vyl6xct5pdrw0000gn/T/pip-install-YuksHk/fake-useragent/
`

**Comment by rsummers23** [comment]
I am having this same issue but It seems like no one has an answer to fix the error.

**Comment by dexs99** [comment]
this is the problem --> "error: could not create '/Library/Python/2.7/site-packages/fake_useragent': Permission denied"
Try --> sudo pip install -r requirements.txt
maybe can solve your problem...

**Comment by d1slact0r** [comment]
Than close your issue please.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
