### ISSUE TITLE
Can add Follow&Like By Location PLEASE!!!

### ISSUE THREAD

**Issue by Gerper20** [instabot-py/instabot.py#1264]
I need follow and like people with x location please help!!

**Comment by Findiglay** [comment]
Would also love to be able to do this. Targeting by location is important for many online businesses.

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
