### ISSUE TITLE
Userinfo GetFollowers not working

### ISSUE THREAD

**Issue by griseraner** [instabot-py/instabot.py#1265]
## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so; have you tried running the code on your local machine?

#### Select one:
- [X] Bug

### Operating System? (include version)
Windows 10

## Python Version?
2.x

## Description of your issue
UserInfo.py : GetFollowers / GetFollowing functions aren't working.

followers = self.s.get(next_url)  
in GetFollowers, followers returns Reponse 404

![uten navn](https://user-images.githubusercontent.com/30091102/40335640-09e49ce6-5d65-11e8-8759-bfc40f4d711a.png)

I believe the links are outdated, can somebody help please?

**Comment by d1slact0r** [comment]
Redo your issue and use the templated provided or we can't help you.

**Comment by griseraner** [comment]
@d1slact0r Have updated the post with more information.

**Comment by MichelRibeiro1** [comment]
Same problem here

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
