### ISSUE TITLE
Only MODE 0 works

### ISSUE THREAD

**Issue by kintorres** [instabot-py/instabot.py#1267]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
I tried to run in other modes but still having problem. In mode 1 the program looks like entered in a loop (as following text shows) and 2,3,4,5 getting erros. Anyone have a solution for this?

MBP-de-Kin-5:instabot.py-master kintorres$ python3 example.py 
06.05.2018_17:57 Instabot v1.2.0 started at 06.05.2018 17:57:

06.05.2018_17:57 Trying to login as kintorres...

06.05.2018_17:57 kintorres login success!
06.05.2018_17:57 kintorres : Get user info 
06.05.2018 17:57
06.05.2018_17:57 Except on get_info!
06.05.2018_17:58 kintorres : Get user info 
06.05.2018 17:58
06.05.2018_17:58 Except on get_info!
06.05.2018_17:58 kintorres : Get user info 
06.05.2018 17:58
06.05.2018_17:58 Except on get_info!
06.05.2018_17:58 kintorres : Get user info 
06.05.2018 17:58
06.05.2018_17:58 Except on get_info!
06.05.2018_17:59 kintorres : Get user info 
06.05.2018 17:59
06.05.2018_17:59 Except on get_info!
06.05.2018_17:59 kintorres : Get user info 
06.05.2018 17:59
06.05.2018_17:59 Except on get_info!
06.05.2018_17:59 kintorres : Get user info 
06.05.2018 17:59
06.05.2018_17:59 Except on get_info!
06.05.2018_18:00 kintorres : Get user info 
06.05.2018 18:00
06.05.2018_18:00 Except on get_info!
06.05.2018_18:00 kintorres : Get user info 
06.05.2018 18:00
06.05.2018_18:00 Except on get_info!
06.05.2018_18:01 kintorres : Get user info 
06.05.2018 18:01
06.05.2018_18:01 Except on get_info!
06.05.2018_18:01 kintorres : Get user info 
06.05.2018 18:01
06.05.2018_18:01 Except on get_info!
06.05.2018_18:01 kintorres : Get user info 
06.05.2018 18:01
06.05.2018_18:01 Except on get_info!
06.05.2018_18:02 kintorres : Get user info 
06.05.2018 18:02
06.05.2018_18:02 Except on get_info!
06.05.2018_18:02 kintorres : Get user info 
06.05.2018 18:02
06.05.2018_18:02 Except on get_info!
06.05.2018_18:02 kintorres : Get user info 
06.05.2018 18:02


```

**Comment by leourl** [comment]
same here

**Comment by bodeezl** [comment]
I am having the same issue, also my bot doesn't unfollow anyone even on mode 0, just says unfollow #1 and continues

**Comment by Magisteri** [comment]
I am also having the same problem.

**Comment by noxx0r** [comment]
ive got the same message, only mode 0 works currently. all modes what im using are errors or endless loops

**Comment by dexs99** [comment]
@kintorres you can use the modified version of instabot, actually it works but always only in mode 0 (with unfollowing working too) it calls INSTABOOST, search for it on github.
good luck

**Comment by leourl** [comment]
@dexs99 that one doesnt work at all, i just tried it

**Comment by dexs99** [comment]
@leourl really? i use it now...
![prova](https://user-images.githubusercontent.com/38705585/39921664-1ad6cd36-551c-11e8-9808-a97670b9bf3a.png)

**Comment by dexs99** [comment]
@leourl maybe you're right, i forget that i made some changes on the code to make it work, just donwload the instabot repository from here -> [Instabot](https://github.com/dexs99/InstabotOK)
Only works mode 0

**Comment by leourl** [comment]
@dexs99 i tried to use this one... i'm getting this error:
![image](https://user-images.githubusercontent.com/22566254/39969034-98d58c22-56ac-11e8-8119-8f1faabae41d.png)

can you help me?

**Comment by dexs99** [comment]
@leourl yes. you need to put the line 308
            self.user_id = (self.user_login)
at the same level of the line 309
try it and let me know.

**Comment by leourl** [comment]
@dexs99 sorry, i think i dont undestand that

**Comment by leourl** [comment]
@dexs99 got it, thanks!
so... what is different about this one?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
