### ISSUE TITLE
error no 13 

### ISSUE THREAD

**Issue by mizrahidiamond** [instabot-py/instabot.py#1268]
fyi I'm a beginner.

Tried to install instabot on my Mac and keep getting this error message after typing **"pip install -r requirements.exe"** 

any idea how to fix this? am I missing anything? 

Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/certifi'
Consider using the `--user` option or check the permissions.

**Comment by bodeezl** [comment]
I believe it should be "sudo pip install -r requirements.txt"

**Comment by mizrahidiamond** [comment]
Issue Fixed installed an earlier version of Python

**Comment by d1slact0r** [comment]
Close the issue please...
