### ISSUE TITLE
sqlite3.OperationalError: database is locked   

### ISSUE THREAD

**Issue by bboy519** [instabot-py/instabot.py#1269]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue
It occurs on running the bot for some time (1d or so).

Traceback (most recent call last):
  File "./instabot/1.py", line 77, in <module>
    bot.new_auto_mod()
  File "/root/instabot/src/instabot.py", line 695, in new_auto_mod
    self.new_auto_mod_like()
  File "/root/instabot/src/instabot.py", line 723, in new_auto_mod_like                                                           if self.like_all_exist_media(media_size=1, delay=False):
  File "/root/instabot/src/instabot.py", line 524, in like_all_exist_media
    status="200")                                                File "/root/instabot/src/sql_updates.py", line 68, in insert_media                                                              media_id +"','"+ status +"','"+ str(now) +"')")
       sqlite3.OperationalError: database is locked            07.05.2018_09:34 Logout: likes - 1854, follow - 0, unfollow - 0, comments - 0.                                                07.05.2018_09:34 Bot work time: 1 day, 13:12:50.022098
07.05.2018_09:34 Logout success!
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by bboy519** [comment]
It occurs on running the bot one day

**Comment by LionelChow** [comment]
Same bug, most of the time, the bot will log out automatically.

**Comment by LionelChow** [comment]
@bboy519 I tried to add the "database_name" in a different name, now it's working perfect.

**Comment by onmyeoin** [comment]
Hi @LionelChow Im also having this issue. Can you please elaborate on your fix above? Would be much appreciated

**Comment by olaims** [comment]
> 
> 
> @bboy519 I tried to add the "database_name" in a different name, now it's working perfect.

how?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
