### ISSUE TITLE
Follow owner of photo

### ISSUE THREAD

**Issue by mateuszpokojowczyk** [instabot-py/instabot.py#1271]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

I use like_all_exist_media(num) function to like photos.
Is there any way to follow person whose photo I've just liked?

**Comment by d1slact0r** [comment]
As far as I know at this point. No.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
