### ISSUE TITLE
Mode 3 : User list empty 

### ISSUE THREAD

**Issue by noxx0r** [instabot-py/instabot.py#1273]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x  ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ x] Other

### Operating System? (include version)
- [ ] MAC
- [x ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [ x] 3.x

## Description of your issue
after starting the bot on mode 3 the error is always user list empty and the tab is closing
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

standard configuration

**Comment by d1slact0r** [comment]
If you read the commented stuff at the top it clearly states that you should not leave spaces around the x 
Witouth any error we can't help.
