### ISSUE TITLE
Login error! Check your login data!

### ISSUE THREAD

**Issue by williamwashere** [instabot-py/instabot.py#1274]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [N] Are you hosting the bot on a VPS or other Cloud hosting?
- [Y] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

The following problem is happening after executing the example.py script:

 10.05.2018_18:09 Instabot v1.2.0 started at 10.05.2018 18:09:

10.05.2018_18:09 Trying to login as blehtest...

10.05.2018_18:09 Login error! Check your login data!
10.05.2018_18:09 Removing already liked medias..
10.05.2018_18:09 Trying to unfollow #1: 
10.05.2018_18:09 Removing already liked medias..
10.05.2018_18:09 Removing already liked medias..
10.05.2018_18:09 Removing already liked medias..

It started now. No logs in error.log.

**Comment by d1slact0r** [comment]
Your login data is wrong.

**Comment by LopesX** [comment]
Same here! :(

12.05.2018_15:32 Instabot v1.2.0 started at 12.05.2018 15:32:

12.05.2018_15:32 Trying to login as XXXXXXXXX...

12.05.2018_15:32 Login error! Connection error!
12.05.2018_15:32 Removing already liked medias..
12.05.2018_15:32 Trying to unfollow #1:
12.05.2018_15:32 Removing already liked medias..

**Comment by dexs99** [comment]
as @d1slact0r says, your login data is wrong. control if your username and password are ok and then re-run

**Comment by LopesX** [comment]
I think was a error of instagram!
Its working again!

**Comment by Djuki** [comment]
Instagram is able to detect abuse. They check where login comes from and they block login.
Some ideas how to avoid this?

Maybe time to switch to some kind of frontend bots run in the browser?

**Comment by dexs99** [comment]
@Djuki if your account is up maybe they have ban your IP, just use proxy (better if it's a private one and is from the country that you usually use your account)

**Comment by pang007** [comment]
@dexs99 i have the same issue as @Djuki. Can you give some advice how to use the proxy to do some?

**Comment by dexs99** [comment]
@pang007 just take a look at the post #1256 , we talk about this in that topic. have a nice day

**Comment by napster2091** [comment]
I wrote the solution here:
https://github.com/instabot-py/instabot.py/issues/1287#issuecomment-391234255

**Comment by EntaThaVoid** [comment]
The bot was working perfectly for about 3 weeks. I decided to run another instance of it for another account and got a bunch of errors messages about trackbacks. Decided to go back to just one acct and now that instance of the bot is giving me the error described by the OP.

I've deleted the bot and redownloaded it, only changing my username and password. Still nothing. I purchased a proxy and get even weirder error messages that I can't post here cause the bot isn't recording anything in the error logs (another bug?).

Any advice? #1287 seems to deal with code that's not at all like what I see when I open the "example.py" file I downloaded only a month ago. Has anyone fixed this "Login error! Check your login data!"
![botfuckery](https://user-images.githubusercontent.com/42783318/44922307-113d1600-ad13-11e8-992a-83191afc290d.png)
 issue?

**Comment by cicciokof** [comment]
same here! tried many other topic's solution but nothing!!

**Comment by LopesX** [comment]
are all working fine... update your files

**Comment by Aleksim** [comment]
I have this problem as well
