### ISSUE TITLE
Install requirements.txt error

### ISSUE THREAD

**Issue by thiswayalice** [instabot-py/instabot.py#1275]
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
C:\Users\Alexandre\Desktop\instabot>pip install -r requirements.txt
Requirement already satisfied: requests in c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 1)) (2.12.4)
Requirement already satisfied: fake-useragent in c:\users\alexandre\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 2)) (0.1.10)
instagram-py 0.0.1 has requirement selenium==2.53.6, but you'll have selenium 3.5.0 which is incompatible.
clarifai 2.0.31 has requirement future==0.15.2, but you'll have future 0.16.0 which is incompatible.
clarifai 2.0.31 has requirement jsonschema==2.5.1, but you'll have jsonschema 2.6.0 which is incompatible.
clarifai 2.0.31 has requirement Pillow==2.9.0, but you'll have pillow 5.1.0 which is incompatible.
clarifai 2.0.31 has requirement requests==2.13.0, but you'll have requests 2.12.4 which is incompatible.
```

## Config

```
```

It seems it requires older versions of files I already have. How can I fix this ?

**Comment by atrninicc** [comment]
Use 'pip - i install -r requirements.txt' instead of 'pip install -r requirements.txt'

**Comment by waseem312** [comment]
Usage:
  pip <command> [options]

no such option: -i

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks

**Comment by lepri13** [comment]
Just did a brand new pull with the same issue, on Ubuntu 18.04, git clone  instapy-quickstart

**Comment by lepri13** [comment]
Ignore that I will need to raise another issues, my one is not 100% the same
