### ISSUE TITLE
Set time: sleep, wake up, lunch and dinner

### ISSUE THREAD

**Issue by danifki** [instabot-py/instabot.py#1276]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue
Is it possible to set a time for the bot to sleep (picking random time between 22:00 to 00:00), wake up (range 06:00 to 08:00), lunch (range 11:30 to 13:30) and dinner (range 19:00 to 20:30)? 
That could be perfect to look like human and not bot.
Btw, i tried changing the default (end 23:59 start 00:00) and i couldnt change it.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
