### ISSUE TITLE
How can i unfollow more users than follow ?

### ISSUE THREAD

**Issue by josuegonzalezm** [instabot-py/instabot.py#1278]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue
 
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
15.05.2018_15:31 Getting user info : dilara.demrc
15.05.2018_15:31 Checking user info..
15.05.2018_15:31 Follower : 122
15.05.2018_15:31 Following : 177
15.05.2018_15:31 Media : 10
   >>>This is a normal account
   >>>This user is active
   >>>This account is following you
   >>>You are following this account
15.05.2018_15:31 Trying to follow: 504459381
15.05.2018_15:31 Followed: 504459381 #2............................. <--
15.05.2018_15:32 Trying to like media: 1779999847703621970
15.05.2018_15:32 Liked: 1779999847703621970. Like #3.
15.05.2018_15:33 Trying to like media: 1779999818970743598
15.05.2018_15:33 Liked: 1779999818970743598. Like #4.
15.05.2018_15:33 Trying to unfollow #1: ................................... <--
15.05.2018_15:33 Getting user info : mario_genovesi
15.05.2018_15:33 Checking user info..
15.05.2018_15:33 Follower : 260
15.05.2018_15:33 Following : 937
15.05.2018_15:33 Media : 181
   >>>This is probably Fake account
   >>>This user is active
   >>>This account is NOT following you
   >>>You are following this account
15.05.2018_15:33 mario_genovesi
15.05.2018_15:33 Unfollowed: 5661302106 #1........................... <---
15.05.2018_15:34 Trying to follow: 2304056104
15.05.2018_15:34 Followed: 2304056104 #3.............................. <---

## Config
   like_per_day=1000,
    comments_per_day=0,
    tag_list=['nyc','photo','newyork','photos','picture','capture'],
    tag_blacklist=[],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=400,
    follow_time=1*60,
    unfollow_per_day=600,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by LopesX** [comment]
Set unfollow_per_day great than follow_per_day.

Example:
    follow_per_day=200,
    follow_time=1*60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,

Please Read https://github.com/instabot-py/instabot.py/blob/master/README.md for learn more to setting your config

**Comment by leourl** [comment]
@LopesX when i do that, i get "Looks like there is nobody to unfollow."
can you help us?

**Comment by Tycho-X** [comment]
Unfollow doesnt work any more since about 3-4 weeks.

**Comment by yamitha** [comment]
try putting it to mode 5 for an hour or so which will reduce the followings but dont use it much also there are  other 5 modes try reading the example.py script this part is what you ahev to change and what yu have to read;
unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

**Comment by marcos10soares** [comment]
The unfollow does not work because you get a 403 response (Forbidden) this is my solution:
https://github.com/marcos10soares/bluestacks-instagram-unfollow

it is rudimentary but it works...

**Comment by constantinosbou** [comment]
it's still not working?

**Comment by LopesX** [comment]
@josuegonzalezm It is a logic question... you understand now? the bot are working good ?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
