### ISSUE TITLE
Nothing happens when I run the code?

### ISSUE THREAD

**Issue by sxmuel** [instabot-py/instabot.py#1280]
When I run the code nothing happens, but I am not sure why. Can someone please help

Pictures
1 - My code (I entered my username and password correctly just switched it to show you guys)
2 - My code
3 - What happens when I run my code

![image](https://user-images.githubusercontent.com/30480650/40135378-2075f1ca-593d-11e8-9fff-c425e4a5f7eb.png)
![image](https://user-images.githubusercontent.com/30480650/40135389-249d8236-593d-11e8-867d-d9e7dac045a9.png)
![image](https://user-images.githubusercontent.com/30480650/40135413-340b6990-593d-11e8-8463-c4cb82a7acfc.png)

**Comment by d1slact0r** [comment]
please close your issue and read the template, it is not that we added that template for fun

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
