### ISSUE TITLE
What does removing already liked media mean?

### ISSUE THREAD

**Issue by ghost** [instabot-py/instabot.py#1282]
Check thi[x]r we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ x] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows 10
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

This may be a bit off topic, but I have seen nowhere else to put this. What does removing already liked media mean? The same sentence has been repeating for a few minutes now in my python prompt. For one thing, what does this mean. Second, is there a way to disable this?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks

**Comment by jackanory89** [comment]
@DarkSuniuM i'm really new to all of this and don't even know how to open a question in case it gets deleted for not being a relevant, but my instabot was running perfectly until a week ago. It still signs in and follows, unfollows, likes etc, but it will say:

26.02.2019_20:04 Get Media by tag: interiors
26.02.2019_20:04 Removing already liked medias

But it will still say:

26.02.2019_20:04 Trying to like media: 19880269728___________
                 https://www.instagram.com________________________
26.02.2019_20:04 Liked: 19880269728983_________ Like #13.(i omitted the post)

The instagram growth I was seeing has now slowed down and i'm wondering if it's linked to this?

Utterly clueless as to how I can fix this. Hope you can help!

Thanks
