### ISSUE TITLE
Follow_time is not changing 

### ISSUE THREAD

**Issue by MrFeltrim** [instabot-py/instabot.py#1285]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
Hi there,

The template says for follow_time = 1 * 60,
So that means it will follow for 1 minute and then unfollow. 

I want to change it to 24 hours. 
So math would be follow_time = 24 * 60 * 60,

I then save the file and then rerun it but it still only follows for a minute. 

I'm not sure if I need to change anything in the src files. 

Thanks for the help in advance. 
```

## Config

```
  follow_per_day= 1000,
    follow_time= 24 * 60 * 60,
    unfollow_per_day= 1000,
```

**Comment by joncodo** [comment]
Same

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
