### ISSUE TITLE
What does NOT LIKED: 403 means?

### ISSUE THREAD

**Issue by deyvid5** [instabot-py/instabot.py#1289]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [X] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X] 3.x

It keeps hitting this message:

 **NOT LIKED: 403** (it's not 400)

What does it mean?

**Comment by guido-n** [comment]
https://en.wikipedia.org/wiki/HTTP_403

Instagram wants to discourage bots :)

**Comment by amoroger** [comment]
Hey guys, i've been looking around for a while but did not found how to solve that, i got the same error than David5, someone got a solution ? (i'm quite a noob in code, sorry :/ )

**Comment by deyvid5** [comment]
Just wait for a while, or change IP. It helps.

**Comment by amoroger** [comment]
Hmmm ok i'll try, thanks ! 
For the moment changing IP does'nt work but i'll keep trying things :)

**Comment by mchiappinam** [comment]
For me the same problem and i already changed the IP but don't solved too :(

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
