### ISSUE TITLE
Issue running Instabot for the first time

### ISSUE THREAD

**Issue by AlexKLMan** [instabot-py/instabot.py#1290]
Hi there, this is my first time running it, I've edited the example file with my login info and change the values lower because I am testing on brand new accounts, but it gives me the following error:
23.05.2018_00:47 Instabot v1.2.0 started at 23.05.2018 00:47:

"23.05.2018_00:47 Trying to login as XXX...

Traceback (most recent call last):
  File "/home/pi/bot/instabot.py/followbot.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/home/pi/bot/instabot.py/src/instabot.py", line 232, in __init__
    self.login()
  File "/home/pi/bot/instabot.py/src/instabot.py", line 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None""

What are these errors and hwo do I fix it? Also how do I tell if the bot is running?
Thanks!

**Comment by napster2091** [comment]
I wrote the solution here
https://github.com/instabot-py/instabot.py/issues/1287#issuecomment-391234255

**Comment by almaromr** [comment]
I have the same problem, and I can not get it to work with the exposed solutions

**Comment by AlexKLMan** [comment]
I wrote this solution and it works for me:
response = self.s.get(https://www.instagram.com/)
if response.status_code == 404:
return
resp = response.text
if resp is not None and '_sharedData' in resp:
try:
shared_data = json.loads(resp.split("window._sharedData = ")[1].split(";</script>")[0])
except (TypeError, KeyError, IndexError):
pass
self.csrftoken = shared_data['config']['csrf_token']
Inside self.csrftoken you have the value you need to put in the header before doing the login POST request
self.s.headers.update({'X-CSRFToken': self.csrftoken})
login = self.s.post(self.url_login, data=self.login_post)

Where do I put this at the end of the example file? Thanks!

**Comment by almaromr** [comment]
solved, thank you very much for the help

**Comment by AlexKLMan** [comment]
@almaromr how did you fix this?

**Comment by SpaceSheepli** [comment]
@almaromr say us how did you fix this. Thanks!

**Comment by dimabondz** [comment]
HOW DID YOU SOLVE IT AND WHERE SHOULD I PUT THE FIX?!

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`

**Comment by lenger101** [comment]
@SpaceSheepli Hey any chance you could reupload the instabot.py file?
