### ISSUE TITLE
Error on script launch!!!

### ISSUE THREAD

**Issue by FilippoAggio** [instabot-py/instabot.py#1296]
## Hosting
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [X] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X] 3.x

## Description of your issue
This is the second time I launch the script on my profile. The first one everything went good, then I updated the server, run the "py example.py" but it gives me some lines of errors...

Command prmpt lines --->

**24.05.2018_08:39 Trying to login as a*********s...

Traceback (most recent call last):
  File "example.py", line 45, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\Administrator\Desktop\instabot.py-master\src\instabot.py", line
 232, in __init__
    self.login()
  File "C:\Users\Administrator\Desktop\instabot.py-master\src\instabot.py", line
 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\requests\cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\requests\cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

C:\Users\Administrator\Desktop\instabot.py-master>**

What do I have to do??

**Comment by foenzie** [comment]
Kind of having the same problem here =


24.05.2018_09:01 Trying to login as *****

Traceback (most recent call last):
  File "example.py", line 41, in <module>
    unfollow_whitelist=[])
  File "C:\Users\Jane\Downloads\instabot.py-master\src\instabot.py", line 232, i
n __init__
    self.login()
  File "C:\Users\Jane\Downloads\instabot.py-master\src\instabot.py", line 283, i
n login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\Jane\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\requests\cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\Jane\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\requests\cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by foenzie** [comment]
Script don't work on my raspberry and windows machine. Same errors.

**Comment by rugge89lau** [comment]
same here on my Mac Pro

**Comment by Robcis** [comment]
I get the same error.

**Comment by gbergna2009** [comment]
for me, work on windows. Not with MAC. https://github.com/instabot-py/instabot.py/issues/1287

**Comment by rocklyve** [comment]
Same problem here... Script doesn't work for my raspberry (raspbian) Got the same error message

**Comment by leeuwd** [comment]
Same here on macOS.

**Comment by Buck86** [comment]
Check out the fix here!
https://github.com/instabot-py/instabot.py/pull/1292/files

Remove the red line and replace with the green ones.

**Comment by gbergna2009** [comment]
thanks @Buck86 it work on Windows but doesn't work with MAC and that's very strange... anyone have a solution both for windows and MAC?

**Comment by Buck86** [comment]
Worked for me on Mac, but first I had to re-download because I had already modified my instabot.py 
 for some other start up error I can't remember exactly. Give it a try!

**Comment by Robcis** [comment]
I've got it working on Mac by merely updating Python from 2.7 to whatever is the latest version. After that, I installed all of the requirements (since the new version of Python is in a different directory), and that did the job. I didn't need to use the hack others post here.

**Comment by FilippoAggio** [comment]
Great @Buck86 !!
It works perfectly! Thanks :+1:

**Comment by Martypary** [comment]
now my bot does nothing.
