### ISSUE TITLE
KeyError in module threading

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [instabot-py/instabot.py#130]
When trying to run unfollowpub.py I get this error. Any idea ?

``` shell
Trying to login as xx...

xx login success!
('Number of unnecessary subscriptions:', 0, '\n')
All done.
Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
Bot work time: 0:00:04.015212
Logout success!
Exception KeyError: KeyError(140735321833984,) in <module 'threading' from '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'> ignored
```

**Comment by LevPasha** [comment]
Look like you use treads? I don't test it with treads.

**Comment by evavon** [comment]
I have the same issue even thought I import thread before importing other libraries.

**Comment by wootwoot1234** [comment]
@LevPasha How do you not use treads?  I'm new to python...

**Comment by ChipWolf** [comment]
Looks about right, lots of key issues. Instagram keep changing the layout of the things we parse.
There should be a 'smarter' way of parsing at some point to prevent updates breaking our stuff

**Comment by absint0o** [comment]
have the same error here

**Comment by re2005** [comment]
Same issue:

`Exception KeyError: KeyError(1995409600,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored`

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
