### ISSUE TITLE
Only set likes of recent pictures of people i follow

### ISSUE THREAD

**Issue by mahoch** [instabot-py/instabot.py#1300]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux (Raspbian)
- [ ] Android

## Python Version?
- [ ] 2.x
- [ ] 3.x

## Description of your issue

```
Hello, I tested instabot for a week now. and it works fine. 
Now i would love to change the code, that the bot only likes the recent instagram Images of people i follow. is it possible?
```

## Config

```

```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
