### ISSUE TITLE
Only mode 2 is "working" 

### ISSUE THREAD

**Issue by Lokinator178** [instabot-py/instabot.py#1303]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
Only mode 2 is "working" and it's stucked in an infinite loop, followin the same people and unfollowing them. I don't know what I did wrong.

This is with mode 4:
30.05.2018_09:12 username login success!
30.05.2018_09:12 username : Get media id on recent feed
 30.05.2018 09:12
30.05.2018_09:12 Except on get media!!
30.05.2018_09:12 ======> Get media id by Tag <======
30.05.2018_09:12 Get media by user success!
30.05.2018_09:12 Current Index = 12 of 64 medias
Traceback (most recent call last):
  File "example.py", line 101, in <module>
    feed_scanner(bot)
  File "C:\Users\loren\Downloads\instabot.py-master\src\feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "C:\Users\loren\Downloads\instabot.py-master\src\likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "C:\Users\loren\Downloads\instabot.py-master\src\likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
30.05.2018_09:12 Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
30.05.2018_09:12 Bot work time: 0:01:26.951607
30.05.2018_09:12 Logout success!

This is with mode 3 and 5:
30.05.2018_09:05 username login success!
30.05.2018_09:05 username: Get media id on recent feed
 30.05.2018 09:05
30.05.2018_09:05 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
30.05.2018_09:05 username : Get media id on recent feed
 30.05.2018 09:05
30.05.2018_09:05 Except on get media!!
30.05.2018_09:06 ======> Get media id by Tag <======
30.05.2018_09:06 Get media by user success!
30.05.2018_09:06 Current Index = 34 of 65 medias
Traceback (most recent call last):
  File "example.py", line 97, in <module>
    unfollow_protocol(bot)
  File "C:\Users\loren\Downloads\instabot.py-master\src\unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "C:\Users\loren\Downloads\instabot.py-master\src\follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "C:\Users\loren\Downloads\instabot.py-master\src\feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "C:\Users\loren\Downloads\instabot.py-master\src\likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "C:\Users\loren\Downloads\instabot.py-master\src\likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
30.05.2018_09:06 Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
30.05.2018_09:06 Bot work time: 0:01:55.786898
30.05.2018_09:06 Logout success!

This is with mode 2:
30.05.2018_08:41 Removing already liked medias..
30.05.2018_08:41 Trying to like media: 1790481034006287531
30.05.2018_08:41 Liked: 1790481034006287531. Like #1.
30.05.2018_08:41 Trying to follow: 6790992468
30.05.2018_08:41 Followed: 6790992468 #1.
30.05.2018_08:41 Trying to unfollow #1:
30.05.2018_08:41 Getting user info : kaspbraks.eggos
30.05.2018_08:41 Checking user info..
30.05.2018_08:41 Follower : 887
30.05.2018_08:41 Following : 1409
30.05.2018_08:41 Media : 108
   >>>This is a normal account
   >>>This user is active
   >>>This account is NOT following you
   >>>You are following this account
30.05.2018_08:41 kaspbraks.eggos
30.05.2018_08:41 Unfollowed: 6790992468 #1.
30.05.2018_08:46 Trying to unfollow #2:
30.05.2018_08:46 Looks like there is nobody to unfollow.
30.05.2018_08:46 Already followed before 6790992468
30.05.2018_08:48 Already followed before 6790992468
30.05.2018_08:50 Trying to unfollow #2:
30.05.2018_08:50 Looks like there is nobody to unfollow.
30.05.2018_08:51 Already followed before 6790992468
30.05.2018_08:53 Already followed before 6790992468

This is with mode 1:
30.05.2018_08:57 username login success!
30.05.2018_08:57 username: Get user info
30.05.2018 08:57
30.05.2018_08:57 Except on get_info!
30.05.2018_08:57 username: Get user info
30.05.2018 08:57
30.05.2018_08:57 Except on get_info!
30.05.2018_08:58 username : Get user info
30.05.2018 08:58
30.05.2018_08:58 Except on get_info!
30.05.2018_08:58 username: Get user info
30.05.2018 08:58
30.05.2018_08:58 Except on get_info!
30.05.2018_08:58 username : Get user info
30.05.2018 08:58
30.05.2018_08:58 Except on get_info!
30.05.2018_08:59 username : Get user info
30.05.2018 08:59
30.05.2018_08:59 Except on get_info!

With mode 0 after the login I get an infinite sequence of "Wrong mode!"
## Config

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="username",
    password="password",
    like_per_day=30,
    comments_per_day=0,
    tag_list=['follow4follow', 'f4f'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=2 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 2

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 2:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

```

**Comment by AizenSousuke** [comment]
doesn't work on mine... if node 1 or 3 it only run the cycle once

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
