### ISSUE TITLE
Syntax Error on Line 43

### ISSUE THREAD

**Issue by mmcsorley16** [instabot-py/instabot.py#1306]
<img width="1004" alt="screen shot 2018-05-30 at 8 00 55 pm" src="https://user-images.githubusercontent.com/39777809/40753977-b6219528-6444-11e8-8944-8898f5d6cda0.png">

Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Hi, I'm getting a syntax error on line 43. It was working 20 minutes ago, and I didn't make any changes.

```
Username's-MacBook-Pro:~ username$ /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Users/username/Desktop/instabot.py-master/example.py
  File "/Users/username/Desktop/instabot.py-master/example.py", line 43
    unwanted_username_list=[
                          ^
SyntaxError: invalid syntax

```

## Config

```

```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
