### ISSUE TITLE
Is there any way to target people that follow a given user?

### ISSUE THREAD

**Issue by Emahhh** [instabot-py/instabot.py#1311]
I mean: 
I’d like the bot to like and follow people from the followers list of a chosen user, that can be finded at:

`https://www.instagram.com/userthatichose/followers/`

How can I set this up?
I think that could be pretty useful, but I haven’t found anyone asking this question. 
Thanks in advance!

**Comment by oakleyblack** [comment]
would also love to see this feature. have been doing extensive googles, and can't seem to find anything on this. will be following.

**Comment by constantinosbou** [comment]
+1

**Comment by tuliosousa25** [comment]
+1

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
