### ISSUE TITLE
Documentation is needed

### ISSUE THREAD

**Issue by vandythong** [instabot-py/instabot.py#1314]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [x] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
This isn't an issue, but I would suggest proper documentations would be beneficial to the community. Thanks 
```

**Comment by twont** [comment]
What issue are you having? The ReadMe #1312 covers most of the basics

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
