### ISSUE TITLE
IndentationError: unexpected indent

### ISSUE THREAD

**Issue by christoskolovos** [instabot-py/instabot.py#1315]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
Traceback (most recent call last):
  File "/Users/Chris/Desktop/instabot.py-master /example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/Chris/Desktop/instabot.py-master /src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/Chris/Desktop/instabot.py-master /src/instabot.py", line 242
    subs1 = r.text[r.text.find("csrf_token")+13:]
    ^
IndentationError: unexpected indent

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by twont** [comment]
You either have 'spa ces' at the start of your lines that shouldn't be there, or the opposite.

The lines of the script should all be flush

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
