### ISSUE TITLE
How to Steal followers of other people?

### ISSUE THREAD

**Issue by manindertaggar** [instabot-py/instabot.py#1318]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
I want to follow people who follow a specific page or person. How to do it ?
```
I want to follow people who follow a specific page or person. How to do it ?
no issues. 
```

## Config

```
```

**Comment by twont** [comment]
#1281 - I think this is what you are looking for

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
