### ISSUE TITLE
Suspicious Login Attempt in endless loop

### ISSUE THREAD

**Issue by realoliverapps** [instabot-py/instabot.py#1320]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
When trying to login, bot prints out 'Login Error! Connection Error!'
When I open the IG app on my phone, I see a suspicious login attempt. After saying 'This Was Me' in the app, I try the bot again. The same behavior occurs. This is true for all accounts I have tried (6 accounts), and is true on my local machine as well as on a cloud-hosted VM (Windows and Linux, respectively). 

If I open a browser and login to IG, I get the same behavior. The loop breaks after a while (maybe 3 or 4 times hitting 'This Was Me' after trying to log in) and I am able to stay logged in.

**Comment by twont** [comment]
@realoliverapps - It is possible that the IPs used on the two machines are far apart, thus looking like you just moved country to country within seconds.

It shouldn't be an issue though. The best way to get around this is to log into IG using a browser on the device that will be running the script. This way, you shouldn't get the suspicious log in attempt.

It is also advisable not to log in using the app while the bot is running.

**Comment by Fuwordy** [comment]
Same problem

**Comment by kuzubov** [comment]
same problem. in login from phone through WiFi. and i'm login from PC... and all OK. but when i run bot in the same PC - i get an error and in my browser i see question about weird login... but all (pc, phone and bot) - works in my home and connect to one my wifi...

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
