### ISSUE TITLE
Too much issues on raspberry pi

### ISSUE THREAD

**Issue by Liturgikus** [instabot-py/instabot.py#1323]
## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
No
- [ ] If so; have you tried running the code on your local machine?
Yes, working on windows, not on my raspberry pi 3B+

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android
- [X] Raspbian

## Python Version?
- [X] 2.x
- [X] 3.x

## Description of your issue
Hey guys!
After spending literally hours in front of my screen trying to setup the bot on my raspberry pi, I think I'm now ready to open my own issue. I've already tried to follow step by step different tutorials, via Python 3, or 2. But I'm pretty sure I can't find any working tutorial...
I always face a new issue (the most preponderant is when I get this error while installing pip : You must give at least one requirement to install).
Is there a proper working tutorial?
I'm not running this headless, got a raspberry pi 3B+ on a new raspbian stretch

**Comment by rastarr** [comment]
did you watch the video tutorial listed at the bottom of the readme.md?

**Comment by Liturgikus** [comment]
@rastarr should I watch for the Mac/Linux tutorial?

**Comment by Liturgikus** [comment]
Further more, which version of python should I install? Only 3.5 available on raspberry

**Comment by rastarr** [comment]
well if you're running on a Pi then that runs linux
my instabot runs Python v3.6.5 under Terminal on my Mac. 3.5 should work equally as well

**Comment by twont** [comment]
@Liturgikus - Did you try running the script

pip install -r requirements.txt

**Comment by leourl** [comment]
@twont on my linux i had to get pip first... maybe he'll too
try this first https://pip.pypa.io/en/stable/installing/

i hope it helps

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
