### ISSUE TITLE
Instabot commenting on some posts but not commenting on others

### ISSUE THREAD

**Issue by jjfriend** [instabot-py/instabot.py#1324]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

First of all, I'd like to say thank you for this awesome bot... it has been working well for over a month. 
However today, or starting from before yesterday, i'm facing problems with commenting. The bot comments on some posts but for other posts it says "trying to comment" and then doesn't comment at all. Please check attached picture to further elaborate what I mean... 
![untitledpy](https://user-images.githubusercontent.com/40055417/41146490-98338464-6b14-11e8-9f5b-064e5e395324.png)

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by marfert** [comment]
I have the same or a similar issue. The bot is commenting the same media multiple times, in bad cases like 5 times or more and others get suspicious about this behavior.

Does anyone know a way to fix this?

**Comment by twont** [comment]
You could create a simple db table to save the media that has been commented on. 

Running a simple check before the next comment would at least prevent duplicates

**Comment by jjfriend** [comment]
hey @twont what do you mean

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
