### ISSUE TITLE
Geolocation on Instabot

### ISSUE THREAD

**Issue by mventer9** [instabot-py/instabot.py#1326]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

#### Select one:
- [x] Feature Request

### Operating System? (include version)
- [x] Windows 10

## Python Version?
- [x] 3.x

## Description of your issue
Is it possible to run geolocation via a specific command in the example.py?

## Config
Basic

**Comment by thibob38** [comment]
Did you solve your problem?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
