### ISSUE TITLE
TypeError unfollow_whitelist

### ISSUE THREAD

**Issue by valeirta** [instabot-py/instabot.py#1333]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ X] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [X ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X ] 3.x

## Description of your issue
I keep getting the following error:

File "example.py", line 45, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
TypeError: object() takes no parameters

Can anyone help pls?

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/issues/1437#issuecomment-407037536
