### ISSUE TITLE
A get a keyError

### ISSUE THREAD

**Issue by joost-heijden** [instabot-py/instabot.py#1334]
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/joost/Desktop/instabot.py-master/src/instabot.py", line 232, in __init__
    self.login()
  File "/Users/joost/Desktop/instabot.py-master/src/instabot.py", line 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by maxjbergmann** [comment]
same issue here

**Comment by joost-heijden** [comment]
@maxjbergmann i fixed it: [change the instabot.py file](https://github.com/instabot-py/instabot.py/commit/ba0fe9e5f37cddc3a42fed66994102e6dbc39643)

It works for me! Let me know if i can help ya.

**Comment by twont** [comment]
You may also need to include the 

Import re;

in your instabot.py header

**Comment by joost-heijden** [comment]
@twont i didn't, and it still works. Why do i need to do that?

**Comment by maxjbergmann** [comment]
@joost-heijden 
thanks a lot, it works for me

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
