### ISSUE TITLE
no module named fake_useragent

### ISSUE THREAD

**Issue by georgejr6** [instabot-py/instabot.py#1335]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [x ] 2.x
- [ ] 3.x

## Description of your issue
Been looking all over for a solution for running bot on the cloud server and nobody seems to have an answer that works. No fake_useragent fixes seem to be applicable. works fine on my computer, I am using python3 on my computer

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

Traceback (most recent call last):
  File "/home/novamaura/instabot.py/example.py", line 6, in <module>
    from src import InstaBot
  File "/home/novamaura/instabot.py/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/novamaura/instabot.py/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ImportError: No module named fake_useragent

## Config

```
Someone help, don't know how to answer this
```

**Comment by maxjbergmann** [comment]
You have to do this `sudo pip install fake-useragent`

**Comment by pd-escher** [comment]
still gives the same error

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
