### ISSUE TITLE
Working Instabot Version Here

### ISSUE THREAD

**Issue by reliefs** [instabot-py/instabot.py#1336]
I just forked and fixed the instabot. You can download a working version here
https://github.com/reliefs/instabot.py

**Comment by leourl** [comment]
tks, i'm gonna try it

**Comment by jjfriend** [comment]
reliefs what did you change

**Comment by Pleasehelpmee** [comment]
Thank you for the answer. I tried it but now I'm getting the following error:

ImportError: No module named requests
***-MacBook-Pro:instabot.py-master ***$ python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/***/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/***/Desktop/instabot.py-master/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/Users/***/Desktop/instabot.py-master/src/userinfo.py", line 5, in <module>
    import requests
ImportError: No module named requests
***-MacBook-Pro:instabot.py-master ***$

**Comment by dzsniper707** [comment]
Wow Thanks it worked perfectly, i just re-downloaded the bot and i installed it again 
I think you should download the bot again and install it so you wont get any issue 
thanks again, youre awesome ♥

**Comment by focamonca** [comment]
this is what I'm gettting: http://prntscr.com/juig28

**Comment by supermaku** [comment]
I downloaded this version and I seem to be getting this error:

`  File "C:\%FILEPATH%\src\instabot.py", line 283
    self.s.headers.update({'X-CSRFToken': csrf_token})
                                                     ^
TabError: inconsistent use of tabs and spaces in indentation`
I've checked, and the indentation looks fine in the file, not sure what the problem is.

**Comment by Paulactea** [comment]
It doesn't work for me at all. I just get:

Already followed before
Already followed before
etc..... it gets stuck there

**Comment by reliefs** [comment]
works fine tested 1 hour ago

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
