### ISSUE TITLE
Like most recent picture of username/username list?

### ISSUE THREAD

**Issue by teamscar** [instabot-py/instabot.py#1337]
This is a function that the community definitely needs for username drops and telegram likers. Can you consider this?

**Comment by lholdsworth** [comment]
Seconded

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
