### ISSUE TITLE
Follow(id)

### ISSUE THREAD

**Issue by charbeld** [instabot-py/instabot.py#1343]
[x] I have searched for other issues with the same problem.

## Hosting
- [No ] Are you hosting the bot on a VPS or other Cloud hosting?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

In the methods section, there's the follow(id) method how and where to use it? Where can I find it? I have a couple of ids that I want to follow.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
