### ISSUE TITLE
How to convert media ID into url?

### ISSUE THREAD

**Issue by marcopalla** [instabot-py/instabot.py#1344]
tryed every way but i miss something

I don't understand the 19 numbers media id
have a script tha t convert id into url but need a ID in a different format with an underscore in the middle

any suggestion?
thanx

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
