### ISSUE TITLE
Bot stuck on "Already followed before"

### ISSUE THREAD

**Issue by dennylel11** [instabot-py/instabot.py#1346]
Evertytime i log in the bot starts and after the first follow, this happens

14.06.2018_15:19 Trying to follow: 1516167654
14.06.2018_15:19 Followed: 1516167654 #1.
14.06.2018_15:19 Already followed before 1516167654
14.06.2018_15:20 Already followed before 1516167654
14.06.2018_15:20 Already followed before 1516167654
14.06.2018_15:21 Already followed before 1516167654
14.06.2018_15:21 Already followed before 1516167654

And it can last forever
How can I fix that?

**Comment by Paulactea** [comment]
It's broken for me too, same issue. How can we fix that?

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
