### ISSUE TITLE
Get followers for an account

### ISSUE THREAD

**Issue by gonzaphotography** [instabot-py/instabot.py#1347]
At first, sorry for my little english.

Im trying to customize the bot for my own case. I want to get the list o my followers and the list of the people i follow. 

im triying something like this:

            uh = urlopen("https://www.instagram.com/username/followers/?_a=1")
            data = uh.read()
            data2 = data.decode("utf-8")

but it come back a script, not a json.

Anybody kmows how i can do it? I know it must be without instagram API, but i dont know if it is possible.

Best regards

**Comment by dzsniper707** [comment]
i think you may use a chrome addon it helps..

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
