### ISSUE TITLE
"Trying to comment"

### ISSUE THREAD

**Issue by jjfriend** [instabot-py/instabot.py#1348]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your errors
The software keeps writing "trying to comment" but it doesn't comment at all. but for some posts it does... why is that? somebody please help

**Comment by anisghalmi** [comment]
I use Android and python3-x
