### ISSUE TITLE
How do I add the username when commenting. For example: Awesome @theusernameoftheaccount

### ISSUE THREAD

**Issue by jjfriend** [instabot-py/instabot.py#1349]
the title says all

**Comment by giulianoporro** [comment]
I follow this post :)

**Comment by danifki** [comment]
following

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
