### ISSUE TITLE
How to change the automatic generated comments into single comments?

### ISSUE THREAD

**Issue by Nicxpho** [instabot-py/instabot.py#1350]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
I want to use my own comments for the bot. But it doesnt work because the bot always wants to generate them. But I want to put in complete comments, that are not generated by the bot. I really hope you guys can understand my issue, because I am not a native speaker.

Thank you!
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by chopraaa** [comment]
Try this:

[/src/instabot.py:136](https://github.com/instabot-py/instabot.py/blob/765cc24b321572f5181f000d7d9d3d0a9f6146a7/src/instabot.py#L136)

```
comment_list=[["Sentence one.", "Sentence two.", "Sentence three."],[".", "..", "...", "!", "!!", "!!!"]],
```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
