### ISSUE TITLE
Account banned after enabling commenting, anyone else get this?

### ISSUE THREAD

**Issue by tonmanayo** [instabot-py/instabot.py#1353]
I enabled just 5 comments a day and after trying to post one comment the account was blocked for 5 min

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
