### ISSUE TITLE
unfollow_non_followers is unfollowing too much recent accounts

### ISSUE THREAD

**Issue by kintaro1981** [instabot-py/instabot.py#1356]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. (including 1153)

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [X] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [X] 2.x
- [ ] 3.x

## Description of your issue

```
unfollow_non_followers.py is unfollowing too much recent followed users, why is not unfollowing older first?
```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
