### ISSUE TITLE
like posts of people I follow

### ISSUE THREAD

**Issue by DasFussel** [instabot-py/instabot.py#1364]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

First of all: Thank you for this great bot!!
I use it to put likes for hashtags. Now I'm wondering if it would be possible to add a new feature that puts likes on people I follow.

For example:
like_followed_todayposts = 100,

- take all the people I follow
- sort them randomly (to avoid always liking the same people if there are too many)
- Check if they posted something today
- Check if I have already liked this post
- like it and decimate like_followed_todayposts until the limmit is reached

Unfortunately, my programming skills are not enough to integrate that. But I hope that this function would appeal to others and hope someone can manage to implement it. 

Have a nice day!

**Comment by Iiviin** [comment]
I would also like to see this, and the option to like photos from a list of accounts.

**Comment by alienhomie** [comment]
I would also like to see this

**Comment by DasFussel** [comment]
Had anyone else this claim and has found a solution?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
