### ISSUE TITLE
Follow/Unfollow. I am a novice at this guys. Is my bot working properly? 

### ISSUE THREAD

**Issue by JustBeGlad** [instabot-py/instabot.py#1367]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [ ] 3.x

## Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```
`
![untitled](https://user-images.githubusercontent.com/34154627/41935806-ec948f86-7982-11e8-899e-9a1486ef517c.png)

**Comment by JustBeGlad** [comment]
![untitled](https://user-images.githubusercontent.com/34154627/41935782-d53f0212-7982-11e8-93cd-e6a1b36058e1.png)

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
