### ISSUE TITLE
Targeting Users Based on tagged location or other methods

### ISSUE THREAD

**Issue by jfinly** [instabot-py/instabot.py#1368]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [X ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [X ] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X ] 3.x

## Description of your issue
The bot has been fantastic! Would love to see a method of targeting specific regions implemented. Perhaps by compiling popular locations based on city, state, country i.e. in Colorado: Rocky Mountain National Park, Denver, Boulder, Rocky Mountains, Vail, Aspen; would all be popular location tags for someone that wanted to target Colorado specific posts & users. 
```
. < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by thibob38** [comment]
did you solve the problem?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
