### ISSUE TITLE
Causes flask application to hang

### ISSUE THREAD

**Issue by Djsurry** [instabot-py/instabot.py#1371]
writing a quick flask app and trying to import a file where I have function that creates a bot object. When importing this, it causes my flask application to never launch

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
