### ISSUE TITLE
Cant log in

### ISSUE THREAD

**Issue by mighty2nyce** [instabot-py/instabot.py#1376]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ x] 2.x
- [ ] 3.x

## Description of your issue
Was working previously then stopped working. i downloaded another instabot and its not working for me nymore. tried to research but tried everything 
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/KoachMkNair/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/KoachMkNair/Desktop/instabot.py-master/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/Users/KoachMkNair/Desktop/instabot.py-master/src/userinfo.py", line 5, in <module>
    import requests
ImportError: No module named requests
Matthews-MacBook-Pro:instabot.py-master KoachMkNair$ 
## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by robery567** [comment]
Please run this command before running the script:
`pip install -r requirements.txt`

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
