### ISSUE TITLE
Help please 🤔

### ISSUE THREAD

**Issue by francescogosce** [instabot-py/instabot.py#1381]
Since today it does not work anymore...the problem is:

pi@raspberrypi:~/Projects/instabot.py $ python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/home/pi/Projects/instabot.py/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/pi/Projects/instabot.py/src/instabot.py", line 17, in <module>
    from unfollow_protocol import unfollow_protocol
ImportError: No module named 'unfollow_protocol'

What should I do?
Thanks

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
