### ISSUE TITLE
New error 02/07/2018

### ISSUE THREAD

**Issue by scotsfloki** [instabot-py/instabot.py#1383]
Does anyone get this error right after the bot tried to log into the account?
(I've been using the bot a lot of time and always managed to fix it but this is weird)

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\r
equests\packages\urllib3\connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\r
equests\packages\urllib3\util\connection.py", line 75, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\socket.py", lin
e 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\r
equests\packages\urllib3\connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\r
equests\packages\urllib3\connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\http\client.py"
, line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\http\client.py"
, line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\http\client.py"
, line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\http\client.py"
, line 1026, in _send_output
    self.send(msg)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\http\client.py"
, line 964, in send
    self.connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\r
equests\packages\urllib3\connection.py", line 163, in connect
    conn = self._new_conn()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\r
equests\packages\urllib3\connection.py", line 147, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urll
ib3.connection.HTTPConnection object at 0x000000669FC2DDD8>: Failed to establish
 a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\r
equests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\r
equests\packages\urllib3\connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\r
equests\packages\urllib3\util\retry.py", line 363, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='ink
361.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionErr
or('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000669FC
2DDD8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',
))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "a.py", line 47, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2']
  File "C:\Users\User\Documents\instabot.py-master\src\instabot.py", line 232, i
n __init__
    self.login()
  File "C:\Users\User\Documents\instabot.py-master\src\instabot.py", line 305, i
n login
    ui = UserInfo()
  File "C:\Users\User\Documents\instabot.py-master\src\userinfo.py", line 29, in
 __init__
    self.hello()
  File "C:\Users\User\Documents\instabot.py-master\src\userinfo.py", line 34, in
 hello
    main = self.s.get(self.url_list[self.i_a]["main"])
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\r
equests\sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\r
equests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\r
equests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\r
equests\adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ink361.com', port=
80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.p
ackages.urllib3.connection.HTTPConnection object at 0x000000669FC2DDD8>: Failed
to establish a new connection: [Errno 11001] getaddrinfo failed',))

**Comment by sissibianchi** [comment]
yes, me. it happened 2 hours ago. I can't find a way to fix this problem. I have different account some with my ip some with proxy but all of them have this problem

**Comment by danifki** [comment]
Got this error today, a few minutes ago. First time. I have no idea whats it about

**Comment by starib** [comment]
Apparently the domain ink361.com  is currently off line. Not sure why, but the domain is in the code.

**Comment by kairosooo** [comment]
ink361 is down, thts why the program is not working.

Is there any way to change the host to local or another site to run the program?

**Comment by hedi777** [comment]
Same here

**Comment by danifki** [comment]
Domain Name: INK361.COM
Registry Domain ID: 1688264378_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.rrpproxy.net
Registrar URL: http://www.key-systems.net
Updated Date: 2018-07-02T07:56:37Z
Creation Date: 2011-11-21T15:01:28Z
Registry Expiry Date: 2018-11-21T15:01:28Z
Registrar: Key-Systems GmbH
Registrar IANA ID: 269
Registrar Abuse Contact Email: abuse@key-systems.net
Registrar Abuse Contact Phone: +49.68949396850
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Name Server: NS0.TRANSIP.NET
Name Server: NS1.TRANSIP.NL
Name Server: NS2.TRANSIP.EU
DNSSEC: signedDelegation
DNSSEC DS Data: 9516 7 1 CACE8968D6AC4BBA16D7DA2E6F63CC9B5094D0E2
URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of whois database: 2018-07-02T13:40:35Z <<<

**Comment by vinaykarode** [comment]
for now I've managed to get around this issue by hard-coding my instagram user id into instabot.py

1. I went to this url and got my user id 

> https://www.instagram.com/{username}/?__a=1
found my user id under graphql -> user -> id

2.  In line 301 in instabot.py i replaced this line 
`self.user_id = ui.get_user_id_by_login(self.user_login)`
with my user id from above
`self.user_id = 'user id here'`

save and run bot

**Comment by Raeru** [comment]
@vinaykarode this solution did not work for me, can someone try and find a fix?

**Comment by vinaykarode** [comment]
@Raeru  oh forgot another piece of detail

comment line 29 in userinfo.py (or delete it)
`#self.hello()`

this should stop the function from calling ink361 api on initialisation

**Comment by mrtancau** [comment]
Thank you @vinaykarode it works for me!!

**Comment by sissibianchi** [comment]
hello @vinaykarode in my code the line 301 in instabot.py is 
self.s.cookies['ig_or'] = 'landscape-primary'
and this link https://www.instagram.com/{username}/?__a=1 is not working.
can you please help me? maybe I have to change the entire code in a new one updated? cause my bot was ok until this morning
thank you

**Comment by mrtancau** [comment]
Hello @sissibianchi you have to find  this line in your code :self.user_id = ui.get_user_id_by_login(self.user_login), comment it and replace with: self.user_id='yourUserId'

To find your userId you have to login to instagram and then go to https://www.instagram.com/{username}/?__a=1 using your username instead of {username}.

**Comment by hedi777** [comment]
@vinaykarode amazing you are a beast issue solved for now thank you ;)

**Comment by scotsfloki** [comment]
It worked perfectly! Thank you @vinaykarode !

**Comment by scotsfloki** [comment]
You can also get your instagram ID easily from this website https://codeofaninja.com/tools/find-instagram-user-id

**Comment by danifki** [comment]
Get your Instagram ID here: https://codeofaninja.com/tools/find-instagram-user-id

**Comment by starib** [comment]
I suppose that this solution doesn't allow you to run multiple instances with multiple accounts like before. Or am I missing something?

**Comment by vinaykarode** [comment]
changing the hello() in line 31 to 37 in userinfo.py from 

`    def hello(self):
        self.s = requests.Session()
        self.s.headers.update({'User-Agent': self.user_agent})
        main = self.s.get(self.url_list[self.i_a]["main"])
        if main.status_code == 200:
           return True
        return True`

to this should do the job

`    def hello(self):
        self.s = requests.Session()
        self.s.headers.update({'User-Agent': self.user_agent})
        # main = self.s.get(self.url_list[self.i_a]["main"])
        # if main.status_code == 200:
        #     return True
        return True`


no need to manually edit instabot.py

**Comment by vinaykarode** [comment]
changing hello() from line 31 to 37 in userinfo.py should allow multiple instances again

Change this function from
`    def hello(self):
        self.s = requests.Session()
        self.s.headers.update({'User-Agent': self.user_agent})
        main = self.s.get(self.url_list[self.i_a]["main"])
        if main.status_code == 200:
            return True
        return False`

to this

`    def hello(self):
         self.s = requests.Session()
         self.s.headers.update({'User-Agent': self.user_agent})
         # main = self.s.get(self.url_list[self.i_a]["main"])
         # if main.status_code == 200:
         #     return True
         return True`

**Comment by vinaykarode** [comment]
changing hello() from line 31 to 37 in userinfo.py should allow multiple instances again

Change this function from

>     def hello(self):
        self.s = requests.Session()
        self.s.headers.update({'User-Agent': self.user_agent})
        main = self.s.get(self.url_list[self.i_a]["main"])
        if main.status_code == 200:
            return True
        return False

to this

>     def hello(self):
         self.s = requests.Session()
         self.s.headers.update({'User-Agent': self.user_agent})
         # main = self.s.get(self.url_list[self.i_a]["main"])
         # if main.status_code == 200:
         #     return True
         return True

**Comment by vinaykarode** [comment]
changing the hello() in userinfo.py from line 31 to 37 should allow you to run multiple instance

comment out or delete few lines from the original function

>     def hello(self):
>         self.s = requests.Session()
>         self.s.headers.update({'User-Agent': self.user_agent})
>         main = self.s.get(self.url_list[self.i_a]["main"])
>         if main.status_code == 200:
>             return True
>         return False

to this

>     def hello(self):
>         self.s = requests.Session()
>         self.s.headers.update({'User-Agent': self.user_agent})
>         # main = self.s.get(self.url_list[self.i_a]["main"])
>         # if main.status_code == 200:
>         #     return True
>         return True

**Comment by starib** [comment]
thanks vinaykarode, this works for me. It fully restores previous functionality in one single move. 
As a tip for the others, I failed editing userinfo.py in notepad++ (indentation error). So I edited in IDLE to make it work.

**Comment by nufcsim** [comment]
Tried this fixes for to the files however I am still getting the following error:


Traceback (most recent call last):
  File "example.py", line 50, in <module>
    'follow', 'follower', 'gain', '.id', '_id', 'bags'])
  File "/Users/Sim/Desktop/instabot.py-master/src/instabot.py", line 232, in __init__
    self.login()
  File "/Users/Sim/Desktop/instabot.py-master/src/instabot.py", line 283, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

Anyone able to shed some light on a potential solution.  Had this working fine for ages and just started running into these errors this week.

**Comment by starib** [comment]
Nufcsim, did you reset any previous edit ?  
Start from scratch, restoring all files,  then try just vinaykarode's last post code only on userinfo.py. 
Hope that helps

**Comment by nufcsim** [comment]
Thanks @starib 

I found a solution on another thread that seems to have done the trick. 

Solution below if it helps anyone 

Replace line 283
self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})

with this:
csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0)
self.s.headers.update({'X-CSRFToken': csrf_token})

and use mode = 0

**Comment by starib** [comment]
@nufcsim I had already that lines modified indeed. I guess that was an earlier fix (from maybe 20 days ago?). I did not try mode other than 0. 
I'm glad that you solved it.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
