### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ink361.com', port=80): Max retries exceeded with url:

### ISSUE THREAD

**Issue by adhavalboy** [instabot-py/instabot.py#1384]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [ yes] Linux
- [ ] Android

## Python Version?
- [ 1.2] 2.x
- [ ] 3.x

## Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by vinaykarode** [comment]
I'm getting the same error

**Comment by uupascal** [comment]
Same here

**Comment by canpoyrazoglu** [comment]
This is due to ink361 going down. Just open `userinfo.py` file, find line 31 and change that function to return True:

    def hello(self):
        self.s = requests.Session()
        self.s.headers.update({'User-Agent': self.user_agent})
        return True

It's *NOT* a real solution, though a quick and dirty fix that might help some of you guys until the problem is fixed. It solved the problem for me.

Alternatively, you can just grab my fork (make sure you go back to the original when it's patched):
https://github.com/canpoyrazoglu/instabot.py

**Comment by hezrei** [comment]
works, thanks

**Comment by felixderlange** [comment]
yes, thanks mate

**Comment by lennlen** [comment]
worked for me too, thank you!

**Comment by dimrizo** [comment]
@canpoyrazoglu What does this change actually do?

**Comment by adhavalboy** [comment]
this issue solved so, i m closing it.

**Comment by AshuPari** [comment]
> def hello(self): self.s = requests.Session() self.s.headers.update({'User-Agent': self.user_agent}) return True

Hey thanks my issue solved
