### ISSUE TITLE
Problem logging in traceback please help

### ISSUE THREAD

**Issue by vincmusic95** [instabot-py/instabot.py#1386]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [
<img width="846" alt="schermafbeelding 2018-07-02 om 18 08 02" src="https://user-images.githubusercontent.com/40769385/42174530-f737fafa-7e22-11e8-8358-09be712b324c.png">
x] 3.x

## Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by vincmusic95** [comment]
I did everything like in the video from Conor on youtube and than this happened

**Comment by funnellco** [comment]
How'd you end up solving this?
