### ISSUE TITLE
Unlike all photos 

### ISSUE THREAD

**Issue by AlexandreTunnermann** [instabot-py/instabot.py#1392]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [X] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [X] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X] 3.x

## Description of your issue

Hi, I'm super new to all of this and I know next to zero coding. I need a mode that only unlikes the photos I have liked before. All of them.

I have granted access by mistake to a 3rd party app and it has like many photos, for months, on my behalf. So it is affecting what Instagram shows me and things like this.

It might be very easy for someone with the know how... but me... 👎 

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
