### ISSUE TITLE
400 Not Liked - proxy works fine on 1 other account, non-aggressive settings help

### ISSUE THREAD

**Issue by crazymisssarah** [instabot-py/instabot.py#1393]
I am getting this error on likes but follows are fine. 100 likes per day, 10 likes per tag, even took follows off. The proxy I'm using works fine on 1 other non-aggressive account, but not on this one. No other proxy (private) is working. Any ideas??

**Comment by headebeast** [comment]
same problem here

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
