### ISSUE TITLE
How set will not interact with my followers and followings and their media?

### ISSUE THREAD

**Issue by isayhow** [instabot-py/instabot.py#1397]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [O ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [O ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [O ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ O] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [ ] 3.6

## Description of your issue

How to set will not interact with my all followers and followings and their media?
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
