### ISSUE TITLE
Where do I add the names i want the bot to steal from?

### ISSUE THREAD

**Issue by freaky1** [instabot-py/instabot.py#1401]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [X] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X] 3.x

## Description of your issue
I don't know where I should leave the names on those accounts I want Instabot to follow its followers. I've tried but it doesn't say anything about it so i don't really know if it actually goes and steal the followers from the accounts I put in?
```
Instabot.py
 
user_agent = "" "name", "name", "name" ""
```

## Config

```
```

**Comment by freaky1** [comment]
where do you get help if no one is answering?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
