### ISSUE TITLE
How do I run the bot in the background of Google Cloud instance?

### ISSUE THREAD

**Issue by 4rt10m** [instabot-py/instabot.py#1404]
I’ve set the bot on google cloud platform and it works great as long as SSH terminal is opened. Cant get it to continue working when I close it, Tried using;

`nohup python exmaple.py &`
It returns;
`[1] 22499” “ignoring input and appending output to ‘nohup.out’`
when I hit enter it prints;
`[1]+  Exit 2    nohup python exmaple.py`

After that when I type `exit` it closes and stops working. Any advice? Or am I missing a step somewhere, got limited coding knowledge. 
Thanks!

**Comment by senatorlila** [comment]
If google cloud runs linux, take a look at tmux. Google is your friend ;-)

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
