### ISSUE TITLE
My System crashes when I put "#" in the comments area.

### ISSUE THREAD

**Issue by json144** [instabot-py/instabot.py#1405]
My system hangs every time that I enter "#" in the comment field. Am I unable to enter hashtags or emojis into the field?

Please assist.

Thank you!

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
