### ISSUE TITLE
user_blacklist not working

### ISSUE THREAD

**Issue by dreammusic2011** [instabot-py/instabot.py#1407]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
user_blacklist is not working. I've searched different articles and the solutions have not worked
I've tried "{'user1':'user2'},"
I've tried "{'hellokitty':'', 'hellokitty3':''},"
Neither solution worked
```
Include the contents of the error.log here (if applicable). <Traceback (most recent call last):
  File "example.py", line 136, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_'])
  File "/home/dreammusic2011/instabot-v2.py/src/instabot.py", line 233, in __init__
    self.populate_user_blacklist()
  File "/home/dreammusic2011/instabot-v2.py/src/instabot.py", line 243, in populate_user_blacklist
    from json import JSONDecodeError
ImportError: cannot import name JSONDecodeError
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by Th3BiSh0p** [comment]
make sure you use python3

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
