### ISSUE TITLE
Completely disable unfollow

### ISSUE THREAD

**Issue by obs0lete** [instabot-py/instabot.py#1409]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x ] Linux
- [ ] Android

## Python Version?
- [ x] 2.x
- [ ] 3.x

## Description of your issue

```
Hi, I have a hopefully simple issue. I just want to disable unfollowing completely, so the script will never unfollow anyone it has followed. How can I achieve this?
```

## Config

```
like_per_day=1000,
    comments_per_day=0,
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    #follow_time=1 * 60,
    #unfollow_per_day=300,
    follow_time=0,
    unfollow_per_day=0,
    unfollow_break_min=15,
    unfollow_break_max=30,
```

**Comment by ugurozturk** [comment]
unfollow_per_day=0, if doesn't work, then you can try unfollow_per_day=1

**Comment by obs0lete** [comment]
I already have set unfollow_per_day set to 0, however, when I try to quit the script (CTRL +C) it starts to unfollow.

**Comment by mbe9477** [comment]
Same here... I set as follows:
`   unfollow_per_day=1,
    unfollow_break_min=60,
    unfollow_break_max=600,`
in example.py

and

` unfollow_per_day=1,
`
in instabot.py
But it still unfollows 50 user / day... 
What have I done wrong?

**Comment by LopesX** [comment]
Please open new issue

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
