### ISSUE TITLE
instabot load image for like or comment and ...

### ISSUE THREAD

**Issue by imanbahmani** [instabot-py/instabot.py#1412]
InstaBot Robot has been using several Gigabytes of my internet volume over a single day!(about 5GB!!!)
Well, it's based on the HTTP Request and I think request library on python do not loading any images! and just work with text! 
Are there any settings for this issue?
My opinion is >>> I want to use the least amount of Internet traffic for running instaBot

Thanks

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
