### ISSUE TITLE
TypeError: write_log() takes 2 positional arguments but 3 were given 18.07.2018_00:21 Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.

### ISSUE THREAD

**Issue by astritshuli** [instabot-py/instabot.py#1416]
After i run python example.py it login successfuly and show me this !! 
Can Anyone help me with the issue.

TypeError: write_log() takes 2 positional arguments but 3 were given
18.07.2018_00:21 Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

Traceback (most recent call last):
  File "example.py", line 76, in <module>
    bot.new_auto_mod()
  File "C:\Users\GridComputers\desktop\instabot.py-master\src\instabot.py", line 712, in new_auto_mod
    self.get_media_id_by_tag(random.choice(self.tag_list))
  File "C:\Users\GridComputers\desktop\instabot.py-master\src\instabot.py", line 375, in get_media_id_by_tag
    self.write_log(log_string,True)
TypeError: write_log() takes 2 positional arguments but 3 were given
18.07.2018_00:21 Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
18.07.2018_00:21 Bot work time: 0:00:09.235461
18.07.2018_00:21 Logout success!

**Comment by ugurozturk** [comment]
fixed https://github.com/instabot-py/instabot.py/commit/8370b990d405547ae3858524c74805e79422c29b
