### ISSUE TITLE
how to put location tags?

### ISSUE THREAD

**Issue by 1yonatan** [instabot-py/instabot.py#1419]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x ] 3.x

## Description of your issue
need help and explanation about the new feature how to put location tag because i dont see it on the example.py .
```
Include the contents of the error.log here (if applicable)
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < 
```

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/README.md
