### ISSUE TITLE
Cant use mode 1/2/3/4/5

### ISSUE THREAD

**Issue by 1yonatan** [instabot-py/instabot.py#1420]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x ] 3.x

## Description of your issue
i can use only mode 0 
if i want to use any other mode i get an error saying "exept get on media"
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config
18.07.2018_12:07 Instabot v1.2.0 started at 18.07.2018 12:07:

18.07.2018_12:07 Trying to login as 1yonatann...

18.07.2018_12:08 1yonatann login success!
18.07.2018_12:08 1yonatann : Get media id on recent feed
 18.07.2018 12:08
18.07.2018_12:08 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
18.07.2018_12:08 1yonatann : Get media id on recent feed
 18.07.2018 12:08
18.07.2018_12:08 Except on get media!!

```

    login="username",
    password="password",
    like_per_day=2000,
    comments_per_day=0,
    tag_list=['kimkardashian', 'israel', 'london', 'shanedawson', 'rylandadams', 'kyliejenner', 'krisjenner', 'arianagrande'
![2018-07-18 12_03_29-](https://user-images.githubusercontent.com/41362015/42871917-29c64c16-8a84-11e8-812c-f1286dad3e1c.png)
![instabot error](https://user-images.githubusercontent.com/41362015/42872015-67b3ac1c-8a84-11e8-86d7-39f9dca828cc.png)

],
    user_blacklist={},
    max_like_for_one_tag=150,
    follow_per_day=300,
    follow_time=2 * 60,
    unfollow_per_day=250,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',

```

**Comment by tuliosousa25** [comment]
I can't use them too.....

**Comment by 1yonatan** [comment]
anything new?

**Comment by nazarus23** [comment]
Same here... Still looking for help!

**Comment by 1yonatan** [comment]
ANYTHING NEW?

**Comment by victosuper** [comment]
Nope still broke

**Comment by Mehranp** [comment]
same

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
