### ISSUE TITLE
How to add the feature to follow users from a specific user or to follow users that have liked a specific post ??

### ISSUE THREAD

**Issue by astritshuli** [instabot-py/instabot.py#1421]
How to add the feature to follow users from a specific user or to follow users that have liked a specific post ??

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
How to add the feature to follow users from a specific user or to follow users that have liked a specific post ??

**Comment by tuliosousa25** [comment]
I want to know that too

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
