### ISSUE TITLE
Guys a lil help :)

### ISSUE THREAD

**Issue by Jessnoia** [instabot-py/instabot.py#1425]
## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue

bot crushers at the login
```
error log INFO:urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
```

## Config

```
Include the contents of your config here

 unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/root/home/Bot/instabot.py-master/src/instabot.py", line 234, in __init__
    self.login()
  File "/root/home/Bot/instabot.py-master/src/instabot.py", line 293, in login
    if login.status_code == 200:


```

**Comment by brocool** [comment]
pip instal urllib3

**Comment by Jessnoia** [comment]
I do have it installed already, it has something to do with ssl since im tryin it on a VPS, okay the solution might be the ssl, then ill still end up with the user agent problem:

/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:369: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:160: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/root/home/instabot.py-master/src/instabot.py", line 234, in __init__
    self.login()
  File "/root/home/instabot.py-master/src/instabot.py", line 285, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/issues/1287
