### ISSUE TITLE
I FIGURED OUT THIS IS AWESOME WAY TO MAKE OUR ACCOUNTS NOT COMMENT ON THE SAME ACCOUNT, SINCE THESE DAYS THERE ARE MANY PEOPLE WHO POST A PICTURE EVERY MINUTE

### ISSUE THREAD

**Issue by brocool** [instabot-py/instabot.py#1426]
1.**Before that, why would we want this feature? That is to make the software not comment twice on the same account, since instagram has so many people who are spamming. These days people in instagram post an image every minute which is soo annoying.** 

2. So here's the idea. The bot would have a campaign, for instance, in the example.py, the code would be instabot.set.campaign="campaign one", and in campaign one it will comment and like accounts, and in the instabot-master folder, it will create a new a file that has the list of people liked, commented, and followed in "campaign one".

3. lets say after some time, we wan't to switch to make a new campaign, so we set code in example.py to
instabot.set.campaign="capaign two". This will start the whole process again.

4. However if we switch back to instabot.set.campaign="capaign one", it will like, follow, and comment on accounts but will ignore the ones liked, commented, and followed before only in "campaign one".
 
5. I hope you get my idea, it's already implemented in instapy but using instapy is tough. I prefer instabot.

6. Anyway, I hope somebody codes that, and as I would also love to contribute to it.

7. A small feature that i'd also request is to add a method to add the username of the account while commenting. for example: "this is awesome @username123." In instapy it's already implemented by adding @{} when typing so for instance if the account that your commenting on is called username123, and you add this to the session.comment in example.py, "awesome post @{}."-- which will be converted to "awesome post @username123." when commenting.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
