### ISSUE TITLE
Traceback / Syntax issue

### ISSUE THREAD

**Issue by iacomp123** [instabot-py/instabot.py#1427]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
Having a lot of issues trying get Instabot working. After several issues I've managed to get by, this is what I'm stuck on.

When I type "python example.py" into command prompt, I get the following message:

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "C:\Users\iacom\Desktop\New folder\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\iacom\Desktop\New folder\src\instabot.py", line 300
    <!--self.user_id = ui.get_user_id_by_login(self.user_login)-->
    ^
SyntaxError: invalid syntax

I've no idea about any of this or what it means so excuse my ignorance. Any help would be greatly appreciated.```

## Config

```
```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
