### ISSUE TITLE
User blacklist

### ISSUE THREAD

**Issue by mmaton** [instabot-py/instabot.py#143]
Please add the ability to blacklist liking certain users' posts (i.e our own posts when we're running the bot on tags we've posted under)

**Comment by polaroi8d** [comment]
Study python, write your code, share with us.

**Comment by shubs** [comment]
Love this answer.
I can try to help @mmaton ;)

**Comment by LevPasha** [comment]
@polaroi8d my guy! 
@mmaton Study python, write your code, share with us.
@shubs If you help to @mmaton then share with us.

**Comment by polaroi8d** [comment]
Hey @mmaton there is a good news, @nekfeu working on it in the #167 PR you can try. :)

**Comment by nekfeu** [comment]
Perfect I didn't see this post @polaroi8d, good for you, if I have one hour I will add the blacklist user array to finish the job completely

**Comment by polaroi8d** [comment]
Thanks for your work @nekfeu

**Comment by nekfeu** [comment]
Np, you made your work open source it's the minimum

**Comment by mmaton** [comment]
Thanks for the responses, sorry I must've sounded rude initially however that was not the intention. @polaroi8d I have implemented your fork and added a specific user blacklist, as well as tags blacklisting in a personal fork - I'll push when I get back from travels!

**Comment by mmaton** [comment]
Sorry, actually I'll leave this open until I've pushed my code :)

**Comment by mmaton** [comment]
@shubs / @polaroi8d please feel free to pick at my code :) #191

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
