### ISSUE TITLE
Can't connect.

### ISSUE THREAD

**Issue by williamwashere** [instabot-py/instabot.py#1432]
The following error is happening while trying to login:

  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ink361.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x75c3d7b0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

Indeed ink361.com is offline.

There's a way bypass it?

**Comment by LopesX** [comment]
same error

**Comment by adhavalboy** [comment]
follow fix #1435

**Comment by ugurozturk** [comment]
invalid issue template
