### ISSUE TITLE
Feature Request: Follow and Comment by Hashtag

### ISSUE THREAD

**Issue by TRys8** [instabot-py/instabot.py#1438]
I notice the 'tag_list' variable works well for likes.  I can set the likes to 600 per day and define a tag list, and then the bot will like posts in those hashtags.  However, the tags don't seem to apply for comments and follows.  I want the bot to follow only people who are either following a hashtag or liking/commenting posts with a certain hashtag.  The same goes for comments.  

These features are important because most users who are trying to expand their influence on Instagram are doing so in an effort to monetize their social medial presence.  This usually entails some type of personal brand that their trying to build, and so commenting and following random users will create a following and engagement that doesn't align with the desired brand of the user.

I notice there are scripts for these features in the examples folder of https://github.com/instagrambot/instabot.  For example: infinity_hashtag_follower follows users who post media with a certain hashtag.  Unfortunately, I've tried these scripts and they do not work for as long as their name implies.  Also in the instagrambot, there is a comment_medias_by_location, so I'd be looking for something like comment_medias_by_hashtag, which I don't believe exists.  

If anyone has suggestions to achieve this with instabot.py, I would much appreciate any help!  Or if this feature already exists and I'm missing something, also please let me know!  Thank you.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
