### ISSUE TITLE
ImportError: cannot import name JSONDecodeError

### ISSUE THREAD

**Issue by bmerrill35** [instabot-py/instabot.py#1441]
...coding novice here.. 

I keep getting the same error message when trying to run example.py on instabot. Says I am logged in but ImportError: cannot import name JSONDecodeError always shows up. I have tried looking is issue up and no luck. Thanks. 
<img width="1299" alt="screen shot 2018-07-23 at 7 00 36 pm" src="https://user-images.githubusercontent.com/41601876/43112527-5be4ee48-8eab-11e8-9a1f-d3b0bf0e3a9b.png">

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
