### ISSUE TITLE
Problem with Proxyservers

### ISSUE THREAD

**Issue by y9y** [instabot-py/instabot.py#1443]
<!--

Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ x] If so; have you tried running the code on your local machine?

#### Select one:

- [ x] Technical Help

### Operating System? (include version)
- [ x] Windows

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

Hi. I try to use a proxy. But i always gets error message.
if i have find a HTTP proxy: Do I have to insert it like: IP:Port ?
I always do this, but it never works. I tried other Proxies...
Does somone have a proxy which does work with this script ?

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by arsinator** [comment]
+1 does not work with proxy

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
