### ISSUE TITLE
"Except on get media!!"

### ISSUE THREAD

**Issue by 90302663** [instabot-py/instabot.py#1445]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows 
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.6

## Description of your issue
When running mode 2, after successful login, I get a repeated sequence of the following:

24.07.2018_17:52 daily_gooses : Get media id on recent feed 
 24.07.2018 17:52
24.07.2018_17:52 Except on get media!!
24.07.2018_17:52 ======> Get media id by Tag <======
24.07.2018_17:52 Get media by user success!
============================== 
Upss hajka is already in ex user list... 
==============================
24.07.2018_17:52 daily_gooses : Get media id on recent feed 
 24.07.2018 17:52
24.07.2018_17:52 Except on get media!!
24.07.2018_17:53 ======> Get media id by Tag <======
24.07.2018_17:53 Get media by user success!
============================== 
Upss hajka is already in ex user list... 
==============================

Can someone explain what this means, and how I can fix it?
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < 
```

    like_per_day=800,
    comments_per_day=0,
    tag_list=['goose', 'geese', 'bird', 'canadiangeese', 'bird', 'birds', 'followforfollowback', 'followforfollow',
              'followtrain','f4f','animal','animals'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=70,
    follow_per_day=300,
    follow_time=2 * 60,
    unfollow_per_day=200,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=["goose"],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags', 'free', 'like'
    ],
    unfollow_whitelist=['houseofhighlights', 'example_user_2'])

**Comment by nagisan0215** [comment]
same here

**Comment by 1yonatan** [comment]
Also here

**Comment by nbrubaker3459** [comment]
same here i don't know whats wrong with it

**Comment by victosuper** [comment]
same here to

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
