### ISSUE TITLE
New account can't use bot...

### ISSUE THREAD

**Issue by jeo96x** [instabot-py/instabot.py#1448]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ x] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ x] Technical Help
- [ ] Other

### Operating System? (include version)
- [x ] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ x] 2.x
- [ ] 3.x

## Description of your issue
Can log in on my original account but as soon as I change the credentials it doesn't let me log in..
```
Traceback (most recent call last):
  File "/Users/jackoconnell/Desktop/Insta/casuals.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/jackoconnell/Desktop/Insta/src/instabot.py", line 232, in __init__
    self.login()
  File "/Users/jackoconnell/Desktop/Insta/src/instabot.py", line 288, in login
    self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
```

## Config standard config

```
```

**Comment by badkamyk** [comment]
I've got the same issue.

**Comment by remyx11** [comment]
Same here

**Comment by ChrisL86** [comment]
I've got this same issue with a linux (ubuntu) vps and a local raspberry pi. Does anyone have a fix?

**Comment by mdrzn** [comment]
Same issue

**Comment by mdrzn** [comment]
This fixed it for me:

```
         })
 
         r = self.s.get(self.url)
-        self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
+        csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0)
+        self.s.headers.update({'X-CSRFToken': csrf_token})
         time.sleep(5 * random.random())
         login = self.s.post(
             self.url_login, data=self.login_post, allow_redirects=True)
```

**Comment by ChrisL86** [comment]
That worked for me thanks!

**Comment by zeus1921** [comment]
managed to fix the error but now it gives me this one:

_27.07.2018_11:44 Trying to login as xxxxxxxxx...
27.07.2018_11:45 Login error! Connection error!_

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
