### ISSUE TITLE
Log to file doesn't work

### ISSUE THREAD

**Issue by thomasssr** [instabot-py/instabot.py#145]
Hi, when I set **log_file=1** the log file is creating but it's empty. 
 **log_file=0** works and shows properly values in console. 

I have the latest version of instabot

**Comment by LevPasha** [comment]
@thomasssr what OS you use? Maybe some permission problem?

**Comment by thomasssr** [comment]
@LevPasha Windows 7

**Comment by chazney** [comment]
Same problem occurring on Windows 10

**Comment by polaroi8d** [comment]
Use linux guys :)

**Comment by nickzano** [comment]
You need to set the log location to a specific directory. I chose the same one as my script. To do this you need to import os and then find the line of code that says "log_file_path = ''" (line 92 in instabot.py) and change it to "log_file_path =os.path.dirname(os.path.realpath(__file__))" without the quotes

**Comment by hoseinit** [comment]
@nickzano 
Hi
By doing what you said I get
 ```
log_file_path = os.path.dirname(os.path.realpath(file))
NameError: name 'file' is not defined
```

**Comment by nickzano** [comment]
@hoseinit I edited my original post. You should have `log_file_path =os.path.dirname(os.path.realpath(__file__))`

**Comment by ChipWolf** [comment]
@nickzano make a pull request.
