### ISSUE TITLE
Follow_time does not work (unfollows right after follow)

### ISSUE THREAD

**Issue by MartinSit** [instabot-py/instabot.py#1457]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1285, #1259, #974)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
I've set my follow_time to 5 * 1500 (because x * x * x returned errors) but right after the bot follows someone, it immediately unfollows them back.

## Config

```
    like_per_day=1000,
    comments_per_day=150,
    tag_list=[xx,xx,xx,xx,xx,xx],
    tag_blacklist=[xx,xx,xx],
    user_blacklist={},
    max_like_for_one_tag=150,
    follow_per_day=300,
    follow_time=5 * 1500,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
```

**Comment by MartinSit** [comment]
Edit: x * x * x now does not return errors, but the bot still unfollows right after following:
```
27.07.2018_11:03 Trying to follow: 2233134824
27.07.2018_11:03 Followed: 2233134824 #1.
27.07.2018_11:03 Trying to unfollow #1:
27.07.2018_11:03 Getting user info : kinstudio_1981
27.07.2018_11:04 Checking user info..
27.07.2018_11:04 Follower : 361
27.07.2018_11:04 Following : 117
27.07.2018_11:04 Media : 485
   >>>This is probably Selebgram account
   >>>This user is active
   >>>This account is NOT following you
   >>>You are following this account
27.07.2018_11:04 kinstudio_1981
27.07.2018_11:04 Unfollowed: 2233134824 #1.
```

**Comment by polzav** [comment]
Same problem... = (

**Comment by minardimedia** [comment]
I am having the same problem

**Comment by Warmooo** [comment]
I am also experiencing this problem. Any suggestions?

**Comment by spaarkly** [comment]
Same, help pls

**Comment by CazGirl** [comment]
Same problem

**Comment by shikaismaru** [comment]
Same

**Comment by Th3BiSh0p** [comment]
I debugged the code, follow_time is never used anywhere... no wonder it's not working.
I managed to find a workaround, I will share this later...

**Comment by doejay** [comment]
@Th3BiSh0p do you mind sharing now? I set up my bot but it says that I am following the same amount of followers as I did before, even though it clearly says "follow number 5" (example)

**Comment by Th3BiSh0p** [comment]
#1495 

this is how I managed to workaround. Just change instabot.py and sql_updates.py files

**Comment by xxstartripper** [comment]
Hello!
Open instabot.py for edit
Make Line 701 a comment (Just add a '#' at the beginning of the line)
This shuts off the unfollow feature period...at least until @Th3BiSh0p get's his work around working

`def new_auto_mod(self):
        while True:
            now = datetime.datetime.now()
            if (
                    datetime.time(self.start_at_h, self.start_at_m) <= now.time()
                    and now.time() <= datetime.time(self.end_at_h, self.end_at_m)
            ):
                # ------------------- Get media_id -------------------
                if len(self.media_by_tag) == 0:
                    self.get_media_id_by_tag(random.choice(self.tag_list))
                    self.this_tag_like_count = 0
                    self.max_tag_like_count = random.randint(
                        1, self.max_like_for_one_tag)
                    self.remove_already_liked()
                # ------------------- Like -------------------
                self.new_auto_mod_like()
                # ------------------- Follow -------------------
                self.new_auto_mod_follow()
                # ------------------- Unfollow -------------------
#                self.new_auto_mod_unfollow()
                # ------------------- Comment -------------------
                self.new_auto_mod_comments()
                # Bot iteration in 1 sec
                time.sleep(3)
                # print("Tic!")`

**Comment by xxstartripper** [comment]
Hello!
Open instabot.py for edit
Make Line 701 a comment (Just add a '#' at the beginning of the line)
This shuts off the unfollow feature period...at least until @Th3BiSh0p get's his work around working

701 -   self.new_auto_mod_unfollow()

**Comment by Th3BiSh0p** [comment]
Well, I'm not used to pull requests/contributions on github, but the needed modifications can be found there (only modify instabot.py and sql_updates.py)
https://github.com/instabot-py/instabot.py/pull/1495/commits/84a72b31729c7d0bea0dc65c8c073f6682c4cd10

**Comment by Th3BiSh0p** [comment]
that's what the cleanup function is supposed to do I think

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
