### ISSUE TITLE
2 accounts running side by side error

### ISSUE THREAD

**Issue by jeo96x** [instabot-py/instabot.py#1458]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ x] Other

### Operating System? (include version)
- [ x] MAC
- [ ] Windows
- [x ] Linux
- [ ] Android

## Python Version?
- [x ] 2.x
- [x ] 3.x

## Description of your issue
#1454 same error as this, no issue actually fixed 
https://imgur.com/a/bubmNnD error in print screen, can't seem to get it working, tried pip install, it installed from cache... please help..
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config
vanilla config
```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by Banginpadr** [comment]
bro, how do you do that?? you downloaded the file twice and then just run it both in 2 different terminal windows?i have 2 accounts and i would like to have them 2 both running at the same time, too.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
