### ISSUE TITLE
cant open the bot

### ISSUE THREAD

**Issue by momododo** [instabot-py/instabot.py#1459]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [ x] 3.x

## Description of your issue

```
C:\Users\dab\Documents\INSTA\FXTOP>python example.py
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
TypeError: InstaBot() takes no arguments
```

## Config

everything work perfect
the bot run very good 30 days
and i restart my computer one time and after that i cant use the bot ever again
always this error show up again and again .
help please  
```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
