### ISSUE TITLE
Error when python example.py

### ISSUE THREAD

**Issue by JonasX01** [instabot-py/instabot.py#1461]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
Always when I try to start the bot (with "python example.py" in cmd) i get this message:
29.07.2018_12:15 Instabot v1.2.0 started at 29.07.2018 12:15:

29.07.2018_12:15 Trying to login as myusername...

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\jonas\Desktop\Instagram\instabot.py-master\src\instabot.py", line 234, in __init__
    self.login()
  File "C:\Users\jonas\Desktop\Instagram\instabot.py-master\src\instabot.py", line 285, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\jonas\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\jonas\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). #!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="myusername",
    password="mypassword",
    like_per_day=629,
    comments_per_day=0,
    tag_list=['follow4follow', 'f4f', 'cute', 'l:212999109'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 2

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

```
![1](https://user-images.githubusercontent.com/41859008/43365284-ca9516d2-932a-11e8-88dc-40e2ae0c5507.JPG)

**Comment by Andy2903** [comment]
I have the same issue on the banana pi.

![unbenannt](https://user-images.githubusercontent.com/41864446/43366530-af4753f8-933f-11e8-8873-238d13d46808.PNG)

**Comment by Ziiran** [comment]
same here

**Comment by p9ablo** [comment]
same here

**Comment by NuriaMartinXifre** [comment]
same here

**Comment by 1yonatan** [comment]
You able to use mode 2 tho? 
They fixed it?

**Comment by p9ablo** [comment]
I tried solution on this thread but still not working
https://github.com/instabot-py/instabot.py/issues/1377

**Comment by remyx11** [comment]
Got the same error.. the solution most people recommend is a solution which used to fix it months ago, but it doesn’t work anymore..

**Comment by CrisioDev** [comment]
_Same Here:_
> Did you try that one?
> [Attempt to use regex to extract CSRF token](https://github.com/instabot-py/instabot.py/pull/1292)
> 
> For me this fix seems to work.
> Good luck.

**Comment by remyx11** [comment]
Again, just as a said; this is a solution from months ago which isn’t working anymore

**Comment by petarpavlov5** [comment]
I find a solution in one of the discussions here.
So you basically need to edit the instabot.py file
Find this line
> self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})

Remove it and add these 2 instead:

> csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0)
        self.s.headers.update({'X-CSRFToken': csrf_token})

Make sure to have 
> import re 
at the top if not already added

**Comment by Andy2903** [comment]
@petarpavlov5 Thanks for your comment. This works 👍

**Comment by jaynemharper** [comment]
Adding these two lines:

csrf_token = re.search('(?<="csrf_token":")\w+', r.text).group(0)
self.s.headers.update({'X-CSRFToken': csrf_token})

and removing this line:  self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})

did not work for me :(

The bot works for my accounts, but does not work for my friend's account who lives across the country. I run the bot on my local machine. What do you think is the problem?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
