### ISSUE TITLE
Insta account shutdown

### ISSUE THREAD

**Issue by cwse89** [instabot-py/instabot.py#1463]
Hi,

I was really excited to use this however bad news...

After running this on mode 0 for only 7 or 8 hours my instagram account was shut down.

I can no longer log in or search for my account. It "no longer exists". I have tried accessing and contacting instagram for 2 days to no avail, so will have to start completely  from scratch.

So a big warning to all those considering Instabot, your hard work and previous posts will all likely be lost.

Cheers,
Cwse

**Comment by brocool** [comment]
it isn't shut down just login from another ip address. this is what i faced before

**Comment by cwse89** [comment]
I have tried 4 different  decices and vpns. Insta says my account no longer exists. 

Ive tried searching for my account on another login and its gone.

**Comment by lasloandrei** [comment]
@cwse89 

Hi, I have encountered the same thing with some accounts I was trying to grow. First of all, this past month the Instagram team hired some human resources to find accounts with bots and massive numbers of accounts were suspended. I'd recommend, if you absolutely need to use the software to use it to a maximum of 100 follow unfollow/day at the moment.

What you need to do is put an email together stating your Instagram account was shut down send it to them, they will get back to you in 24-48hrs with a 10 digit code or something like that and instructions. In my case, if it is personal account, they will ask a photo of the handwritten code so they know it's not a machine that does this and a picture with your face that appeared in pictures and the handwritten code. They'll run a face recognition software and match some key features with your old photos. And that will basically reactivate your account.

If it is a company account, they will need a copy of a document that the company exists, and the picture with handwritten code. 

If it is an entertainment account, I did not experience that yet so fingers crossed you can prove you are the owner. 

Hope it helps, 
Cheers.

**Comment by cwse89** [comment]
Hi @lasloandrei, I tried this 2 days ago, and unfortunately Instagram does not respond to emails anymore as they did in 2017. I checked this to confirm on forums also.

**Comment by cwse89** [comment]
They also sent an email response via Facebook:

![capture](https://user-images.githubusercontent.com/25198716/43459878-4c1a9af4-9512-11e8-94d2-3f91602c38cd.JPG)

**Comment by brocool** [comment]
@lasloandrei download a vpn from the app store or google play. make sure it works and run it. delete instagram and download again. make sure before using instagram that your vpn is on, enter instagram, type your username and password then login. dont use any other device

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
