### ISSUE TITLE
Not Liked 400

### ISSUE THREAD

**Issue by y9y** [instabot-py/instabot.py#1466]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x ] 3.x

## Description of your issue

**Hi :) I am using 5 bots on one machine. I used this 2 weeks with no problem. But now:
Bots can login without problem. But after 3min, all bot got error 400 NOT LIkEd.

Whtas the problem ? Can someone help me ?**

**Comment by jarosenthal** [comment]
Not sure if this is the same issue but try #1498

**Comment by b4ckbre4ker** [comment]
I believe the error 400 is IP ban.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
