### ISSUE TITLE
No 'requests' module

### ISSUE THREAD

**Issue by therandomgrl** [instabot-py/instabot.py#1468]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC (high sierra)
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x (3.7)

## Description of your issue

```
whenever I try to run example.py, it seems to be missing a module named 'requests'
```

## Config

```
Traceback (most recent call last):
  File "/Users/x/Downloads/instabot.py-master/example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/x/Downloads/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/x/Downloads/instabot.py-master/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/Users/x/Downloads/instabot.py-master/src/userinfo.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by antisocialmediamanager** [comment]
same issue.

**Comment by rareinator** [comment]
have you tried installing the requirements? do pip install -r requirements.txt

**Comment by therandomgrl** [comment]
@rareinator "Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'"
sorry if any of this is ridiculously obvious, I know very little when it comes to coding!

**Comment by therandomgrl** [comment]
@rareinator "Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'"
(sorry it any of this seems painfully obvious to you, I know very little when it comes to coding)

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
