### ISSUE TITLE
UnBoundLocalError

### ISSUE THREAD

**Issue by Samugrof** [instabot-py/instabot.py#1470]
Hi, i cant launch example.py, because it says:

> Traceback (most recent call last):
> File "example.py", line 46, in 
> unfollow_whitelist=['example_user_1', 'example_user_2'])
> File "/root/instabot.py/src/instabot.py", line 234, in init
> self.login()
> File "/root/instabot.py/src/instabot.py", line 283, in login
> csrf_token = re.search('(?<="csrf_token":")\w+', r.text).group(0)
> UnboundLocalError: local variable 'r' referenced before assignment

Please help me to fix, thank you.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
