### ISSUE TITLE
Issue Login Perfect but crash after

### ISSUE THREAD

**Issue by joaocpereiraa** [instabot-py/instabot.py#1471]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

After start, login perfect but after this error hapened:

`Traceback (most recent call last):
  File "C:\Users\joaoc\Downloads\instabot.py-master\instabot.py-master\COMENTARIOS - completar.py", line 67, in <module>
    bot.new_auto_mod()
  File "C:\Users\joaoc\Downloads\instabot.py-master\instabot.py-master\src\instabot.py", line 716, in new_auto_mod
    1, self.max_like_for_one_tag)
  File "C:\Users\joaoc\AppData\Local\Programs\Python\Python36\lib\random.py", line 220, in randint
    return self.randrange(a, b+1)
  File "C:\Users\joaoc\AppData\Local\Programs\Python\Python36\lib\random.py", line 198, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1,1, 0)
>>> `

How can i solved? It's work like a charm but now stop work, i don't change anything.
I solve the error CSRFToken but now i have +1.

**Comment by joaocpereiraa** [comment]
someone? please 👍 :)

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
