### ISSUE TITLE
Unsuccessful Login with no log

### ISSUE THREAD

**Issue by nadia986** [instabot-py/instabot.py#1472]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x ] 3.x

## Description of your issue
I modified example.py with my username/password but when I run the file the app writes anything on the console and no error information in the log file. It seems like the app is hanging, nothing happen for several minutes.

![run_python](https://user-images.githubusercontent.com/42178923/43780111-23d24d9c-9a5a-11e8-9fb2-a1c844fd4922.JPG)

I tried also running a file like this 

#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

##custom example

bot = InstaBot(
    login="xxx",
    password="xxx")
	
bot.auto_mod()

but nothing to do!

## Config

...

**Comment by awwdio** [comment]
it happends to me after error it tries to remove already liked medias and gets stuck doing so (same error)

**Comment by hackersteve41** [comment]
Same Problem Here. Even Though I Have Provided Correct Login Info It Gives me Login Error Message and stuck at Removing already liked medias....

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
