### ISSUE TITLE
geo_based_following

### ISSUE THREAD

**Issue by scriptvader** [instabot-py/instabot.py#1477]
I really want to know if its possible to use instabot.py to follow users based on their location or follow users that users that users I am following follow...if yes I would please need a short walk through

**Comment by uglyeoin** [comment]
Following the followers of certain accounts would be an excellent addition

**Comment by rets85** [comment]
The follow by location tag is actually not working:

14.08.2018_22:21 Removing already liked medias..
14.08.2018_22:21 Get media id by tag: l:5927494
14.08.2018_22:21 Except on get_media!
14.08.2018_22:21 Removing already liked medias..
14.08.2018_22:21 Get media id by tag: l:2999577
14.08.2018_22:21 Except on get_media!
14.08.2018_22:21 Removing already liked medias..
14.08.2018_22:21 Get media id by tag: l:5927494
14.08.2018_22:21 Except on get_media!
14.08.2018_22:21 Removing already liked medias..
14.08.2018_22:21 Get media id by tag: l:2999577
14.08.2018_22:21 Except on get_media!
14.08.2018_22:21 Removing already liked medias..

**Comment by alexlaza10** [comment]
me too 

> 14.08.2018_22:21 Removing already liked medias..
> 14.08.2018_22:21 Get media id by tag: l:5927494
> 14.08.2018_22:21 Except on get_media!
> 14.08.2018_22:21 Removing already liked medias..
> 14.08.2018_22:21 Get media id by tag: l:2999577
> 14.08.2018_22:21 Except on get_media!
> 14.08.2018_22:21 Removing already liked medias..
> 14.08.2018_22:21 Get media id by tag: l:5927494
> 14.08.2018_22:21 Except on get_media!
> 14.08.2018_22:21 Removing already liked medias..
> 14.08.2018_22:21 Get media id by tag: l:2999577
> 14.08.2018_22:21 Except on get_media!
> 14.08.2018_22:21 Removing already liked medias..

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
