### ISSUE TITLE
Logging error. Connection error. Suspect login attempt.

### ISSUE THREAD

**Issue by bboy519** [instabot-py/instabot.py#1478]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue

13.08.2018_03:35 Trying to login as <my_username>...

13.08.2018_03:35 Login error! Connection error!
13.08.2018_03:35 Removing already liked medias..
13.08.2018_03:35 Removing already liked medias..

Instagram popped up "Suspect login attempt."
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
