### ISSUE TITLE
Login Error. Connection Error. No error logs found.

### ISSUE THREAD

**Issue by bboy519** [instabot-py/instabot.py#1479]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [X] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X] 3.x

## Description of your issue
No error logs shown. When tried to log in the bot the first time Instagram popped up a "Suspicious Login attempt" note and asked me to verify my email address. After entering the code the browser logged in but the bot no longer works. There even isn't a "Suspicious Login attempt" notice. Nothing happened. Just can't log the bot in. Password correct. No two factor auth enabled.
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```

13.08.2018_03:49 Instabot v1.2.0 started at 13.08.2018 03:49:

13.08.2018_03:49 Trying to login as <my_username>...

13.08.2018_03:49 Login error! Connection error!
13.08.2018_03:49 Removing already liked medias..
13.08.2018_03:49 Removing already liked medias..
13.08.2018_03:49 Removing already liked medias..
13.08.2018_03:49 Removing already liked medias..
13.08.2018_03:49 Removing already liked medias..
13.08.2018_03:49 Removing already liked medias..
13.08.2018_03:50 Removing already liked medias..
13.08.2018_03:50 Removing already liked medias..
13.08.2018_03:50 Removing already liked medias..
13.08.2018_03:50 Removing already liked medias..
13.08.2018_03:50 Removing already liked medias..
13.08.2018_03:50 Removing already liked medias..
13.08.2018_03:50 Removing already liked medias..
13.08.2018_03:50 Removing already liked medias..
13.08.2018_03:50 Removing already liked medias..
13.08.2018_03:50 Removing already liked medias..

```

**Comment by rareinator** [comment]
Are you logging in using the email or the username? I had the same problem when using email, switching to username worked for me.

**Comment by bboy519** [comment]
@rareinator  I'm logging in with my username. And it's not working now.

**Comment by senatorlila** [comment]
With some account I do have the same problem, with some I don't. Using private proxies.

**Comment by rareinator** [comment]
I'm not using any proxy, and it's working for me with no issue

**Comment by caioladislau** [comment]
I got the same error. Someone can help with this?

```
16.08.2018_09:32 Instabot v1.2.0 started at 16.08.2018 09:32:

16.08.2018_09:32 Trying to login as ###...

16.08.2018_09:32 Login error! Connection error!
16.08.2018_09:32 Removing already liked medias..
16.08.2018_09:32 Removing already liked medias..
```

**Comment by NetRider88** [comment]
exactly the same with me already long time can anyone help, please

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
