### ISSUE TITLE
Login failed or not liked 403

### ISSUE THREAD

**Issue by remyx11** [instabot-py/instabot.py#1486]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Problem

Hi guys,

After fixing the latest CRSF Token issue, my bot won't work anymore; I either get "Login failed! Connection failed! or "Not liked: 403" it has been like this for over two weeks now, kind of annoying there has to be solution, right?

Can someone help me please.

**Comment by xthedevistatorx** [comment]
Having the same issue. I've researched but cannot find a solid solution. I have tried different and new accounts, still not working.

**Comment by b4ckbre4ker** [comment]
just started getting this issue yesterday

**Comment by Ruchit4601** [comment]
The same issue  I have been trying to deal with it for 2 hours!!!

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
