### ISSUE TITLE
KeyError Help.

### ISSUE THREAD

**Issue by ColeShelly** [instabot-py/instabot.py#1487]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [x] 3.x

## Description of your issue
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/root/Desktop/instabot.py/src/instabot.py", line 231, in __init__
    self.login()
  File "/root/Desktop/instabot.py/src/instabot.py", line 286, in login
    self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by protradingclub** [comment]
@ColeShelly I have the same issue now what is the fix for this?
