### ISSUE TITLE
user_blacklist doesn't seem to be working properly

### ISSUE THREAD

**Issue by Th3BiSh0p** [instabot-py/instabot.py#1490]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
I'm trying to use the user_blacklist but every user I put in this list give the same result :

> Account of user username was deleted or link is invalid

but the username is ok, I've tried to debug a bit the populate_user_blacklist function, user_id_url is ok, the url is working well in a browser but json.loads throws an exception :

> JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)

## Config

```
user_blacklist={'username1':'','username2':'','username3':'','username4':''},
```

**Comment by NodalPoint** [comment]
Same issue here!

**Comment by Th3BiSh0p** [comment]
Well, I debugged the code to try to find out why it's not working and I can't understand why, but I found a workaround. The  populate_user_blacklist function is used to populate the user_blacklist json string with a user_id. A quick workaround is to give the user_id in the string in your config file.

like this :
`user_blacklist={'username1':'user1_id','username2':'user2_id'},`

you can find the user_id using some website like https://codeofaninja.com/tools/find-instagram-user-id

**Comment by NodalPoint** [comment]
I've already done that, and even doing it like that doesn't solve the issue unfortunately.

**Comment by Th3BiSh0p** [comment]
The 'link is invalid' message remains but the user_blacklist seems to be correctly populated

**Comment by NodalPoint** [comment]
Hmm, can't seem to find that document.

**Comment by NodalPoint** [comment]
Do you mean in the instabot.py script?

**Comment by Th3BiSh0p** [comment]
yes

**Comment by NodalPoint** [comment]
Mine isn't filled in in the instabot.py script unfortunately. Do you think adding them manually will work?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
