### ISSUE TITLE
Stuck in follow code! Follow not getting executed!!

### ISSUE THREAD

**Issue by yrucbood** [instabot-py/instabot.py#1505]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ X] If so; have you tried running the code on your local machine?

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [X ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [ X] 3.x

## Description of your issue

Login successful but stuck at follow! Follow code not getting executed!!!
![image](https://user-images.githubusercontent.com/42598086/44443083-7bf3a080-a5f3-11e8-907b-dbd374b3b45b.png)

```

## Config

```

```

**Comment by yrucbood** [comment]
Hey! just happened this morning everything was working fine at night! The code stopped after logging in!
I specifically  call follow function so it is not getting executed!

Thanks in advance! It will be huge help! :)

**Comment by rmaranhao** [comment]
AFAIK instagram is changing some codes.
Mine is now stuck with the same small group of users to follow.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
