### ISSUE TITLE
Login error! connection error!

### ISSUE THREAD

**Issue by pratikshett** [instabot-py/instabot.py#1507]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by pratikshett** [comment]
![capture](https://user-images.githubusercontent.com/42581676/44444565-0ab7eb80-a5fb-11e8-976e-23424ffdbd59.PNG)

**Comment by senatorlila** [comment]
Same problem...

**Comment by MarshallJohansson** [comment]
Same problem((

**Comment by manzo1991** [comment]
Same problem, yesterday it was working, maybe instagram changed some policy in the logging procedure?

**Comment by mdrzn** [comment]
There's another issue open with a couple fixes for the login, but then it gets stuck to liking photos.

**Comment by sergiosre** [comment]
Some one can say the solution?

**Comment by VLNTNF** [comment]
same

**Comment by Anonumous21** [comment]
Same, first it stopped liking with error 403 then it stopped logging in altogether

**Comment by ritikitty** [comment]
same here...

**Comment by pooriant** [comment]
![untitled](https://user-images.githubusercontent.com/29506601/44565729-e1c06380-a77e-11e8-974a-5b51ad41c22a.png)
i have the same error from this morning , yesterday i had error 403 but after a while that disappeared automatically , but this morning when i saw this error !

**Comment by DanielDempsey** [comment]
I have been met with this error just after fixing the attribution error.... any help would be appreciated massively!

**Comment by pooriant** [comment]
i fixed this error , this happen because Instagram changed some policy , if you see this problem means you log in from different location and Instagram dosent know which location are true , 
1- log out from each devices 
2- log in into account from mobile or website 
3- if that asked you something about true location just select (this was me) 
4- exit from that device and start your bot again

**Comment by MarshallJohansson** [comment]
It did not help

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
