### ISSUE TITLE
Reduce delay between likes

### ISSUE THREAD

**Issue by fedex03** [instabot-py/instabot.py#1508]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

The bot works very well but I have a technical question. Is it possible to reduce the delay between likes? I receive back few likes to my photos in relation to the performed likes. 

Another question about the bot behavior: Does the bot likes several photos from the same user before pass to the next user or not?

Thanks for the help and for the great work!

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config
    start_at_h=6,
    start_at_m=10,
    end_at_h=23,
    end_at_m=55,
    like_per_day=1000,
    media_min_like=20,
    comments_per_day=0,
    tag_list=['xxx', 'xxx', 'xxx'],
    tag_blacklist=[],
    user_blacklist={},
    max_like_for_one_tag=150,
    follow_per_day=500,
    follow_time=5 * 60 * 60,
    unfollow_per_day=500,
    unfollow_break_min=15,
    unfollow_break_max=30,
```

```

**Comment by TutOsirisOm** [comment]
Go to /src/instabot.py and edit this part around line 180.
```python
        # Like
        self.like_per_day = like_per_day
        if self.like_per_day != 0:
        self.like_delay = self.time_in_day / self.like_per_day
```
Where it says this:
```python
self.like_delay = self.time_in_day / self.like_per_day
```
Change it to whatever you want, for example this will pick a random number everytime the delay is calculated which makes you less detectable by bots. The example below is for between 400ish - 500ish likes a day. If you do this make sure to use [prime numbers](https://www.mathsisfun.com/numbers/prime-numbers-to-10k.html).
```python
self.like_delay = self.time_in_day / random.randint(409,503)
```
To get more likes i'd recommend looking at your insights for your page and seeing how much of your engagement comes froms what and what your audience is. Try to adjust your settings based on that information. Also if you have 0 for hastags then use different ones in your actual post, don't use ones with too many posts in it though or you risk not having your posts seen. 

Let me know if you have any questions!

**Comment by fedex03** [comment]
Hi @TutOsirisOm,

thanks for the detailed explanation.

I have few questions:
- The variable **time_in_day**. Does this variable takes in account the bot working time (defined in the configuration) or it is set to 24h? 

- Does the value of variable **like_delay** is computed each time (or loop cycle if there is one) or is computed when the bot is started?

- How do you choose the upper and lower limit for the random function? Now i set 1000 likes for a day.


> To get more likes i'd recommend looking at your insights for your page and seeing how much of your engagement comes froms what and what your audience is. Try to adjust your settings based on that information. Also if you have 0 for hastags then use different ones in your actual post, don't use ones with too many posts in it though or you risk not having your posts seen.

Regarding the statement above, I set 6 hashtags in **tag_list** with millions of post to choose users that posts images similar to mine. Is right?

For the future post I'll try to choose post with less popular hashtags.

Thanks for your time!

BR,
Federico

**Comment by vicmunez85** [comment]
I have a question about this...

The higher the prime number here, the faster it likes an image? 
`self.like_delay = self.time_in_day / random.randint(409,503)`

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
