### ISSUE TITLE
Code Error Traceback (most recent call last)

### ISSUE THREAD

**Issue by K2X** [instabot-py/instabot.py#1519]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ x] If so; have you tried running the code on your local machine?

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [ x] 3.x

## Description of your issue

```
I'm having this code pop up on my Command Prompt and I don't know what to do further 
```

## Config

```
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\Shohruh\Downloads\instabot.py-master\src\instabot.py", line 234, in __init__
    self.login()
  File "C:\Users\Shohruh\Downloads\instabot.py-master\src\instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\Shohruh\Downloads\instabot.py-master\src\userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group' 
```

**Comment by ProUserGithub** [comment]
same

**Comment by K2X** [comment]
Can anyone help with this issue?

**Comment by ritikitty** [comment]
same

**Comment by DeepakSuryaS** [comment]
i have the same issue

**Comment by constantinosbou** [comment]
Same

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
