### ISSUE TITLE
Trying to unfollow #1 doesn't work

### ISSUE THREAD

**Issue by fedex03** [instabot-py/instabot.py#1520]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue

```
Hi there, 
I'm running the bot for 2 days and I'm very satisfied, but I have a doubt regarding the unfollow.
I use the mode 0 and I noticed that the unfollow doesn't work because I always see this log: **Trying to unfollow #1:**

> Getting user info : xxxxx
Trying to like media: xxxxx
Liked: xxxxx. Like #558.
Trying to like media: xxxxx
Liked: xxxxx. Like #559.
Trying to follow: xxxxx
Followed: xxxxx #392.
Trying to unfollow #1:
Getting user info : xxxxx
Trying to like media: xxxxx
Liked: xxxxx. Like #560.
Trying to like media: xxxxx
Liked: xxxxx. Like #561.
Trying to follow: xxxxx
Followed: xxxxx #393.
Trying to unfollow #1:
Getting user info : xxxxx
Trying to like media: xxxxx
Liked: xxxxx. Like #562.

I setup the following period equal to 5 hours but after this period no users was unfollowed.

Is this a bug or something related to my configuration?

Thanks for the help
 
```

## Config

```
start_at_h=6,
start_at_m=10,
end_at_h=23,
end_at_m=55,
like_per_day=1000,
media_min_like=20,
comments_per_day=0,
tag_list=['xxx', 'xxx', 'xxx', 'xxx'],
tag_blacklist=[],
user_blacklist={},
max_like_for_one_tag=150,
follow_per_day=500,
follow_time=5 * 60 * 60,
unfollow_per_day=500,
unfollow_break_min=15,
unfollow_break_max=30,
log_mod=1
```

**Comment by worldsdream** [comment]
Yes, the unfollow is not working. I have the same thing.

**Comment by variamus** [comment]
I have got the same problem.. also tried this fix with no luck: https://github.com/instabot-py/instabot.py/pull/1510

**Comment by fedex03** [comment]
@worldsdream How do you proceed to unfollow people since mode 5 doesn't work? 
I don't want to collect to many followers.
Thanks!

**Comment by worldsdream** [comment]
@fedex03 waiting for someone to fix the issue.

**Comment by Faprasem** [comment]
I have the same problem too.

**Comment by ximzavivka** [comment]
Did you got something like POST request to: https://www.instagram.com/web/friendships/<userid>/unfollow/ - Status: 403 ? I'm trying to fix, but still have this status 403

**Comment by EntaThaVoid** [comment]
Same problem as OP.

**Comment by Elywaen** [comment]
Same problem, impossible to find a solution on the web :(

**Comment by fillipemontenegro** [comment]
I am not sure if this is the right solution, but I think I got it to work.
I believe it's due to the fact that Instagram keeps changing its API. Please correct me if I am wrong.

On src/instabot.py, line 869 (or close to it) you should have this:

`all_data = json.loads(re.search('{"activity.+show_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]`

Simply change the "show_app" for "gatekeepers", so it will be like this:

`all_data = json.loads(re.search('{"activity.+gatekeepers', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]`

It seems to be working fine here now.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
