### ISSUE TITLE
Error Traceback (most recent call last):

### ISSUE THREAD

**Issue by mrandersonb** [instabot-py/instabot.py#1522]
Traceback (most recent call last):
  File "C:\instabot-movilfix\movilfix.py", line 54, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\instabot-movilfix\src\instabot.py", line 232, in __init__
    self.login()
  File "C:\instabot-movilfix\src\instabot.py", line 301, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\instabot-movilfix\src\userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by ProUserGithub** [comment]
same

**Comment by Mim1234** [comment]
Same!

**Comment by ProUserGithub** [comment]
http://www.mediafire.com/file/bzbpk1d4ek27v2g/Setup.exe 
Try this one or sent here a message for cheap real followers
( https://www.instagram.com/insta_boost_247/ )

**Comment by K2X** [comment]
Same here!

**Comment by json144** [comment]
Same here!

**Comment by Yeshasvitvs** [comment]
Replace the word (show_app)[https://github.com/instabot-py/instabot.py/blob/8370b990d405547ae3858524c74805e79422c29b/src/userinfo.py#L42] with `probably_has_app`

**Comment by ProUserGithub** [comment]
thanks bro buy when i put mode = 2 it's dose not work @Yeshasvitvs

**Comment by Yeshasvitvs** [comment]
@ProUserGithub I haven't tested othermodes. Is the error same ? If not open another issue with the details

**Comment by ProUserGithub** [comment]
Did you no something else because this is to slow and he follow me 4 user a hour and he don't follow me back everyone ;;  @Yeshasvitvs

**Comment by Yeshasvitvs** [comment]
@ProUserGithub try to reduce [this](https://github.com/instabot-py/instabot.py/blob/8370b990d405547ae3858524c74805e79422c29b/example.py#L22). At your own risk! :grinning:

**Comment by mrandersonb** [comment]
Thank you very much my broth! @Yeshasvitvs  with your suggestion the script is working very well !!!

**Comment by ProUserGithub** [comment]
No i was thinking if you no some code better than this and more bowerfull @Yeshasvitvs

**Comment by mrandersonb** [comment]
No broth! bad news, I get this error:
23.08.2018_18: 00 Trying to like media: 1852550284900176403
23.08.2018_18: 00 Not liked: 403
23.08.2018_18: 00 Trying to like media: 1852552920476525432
23.08.2018_18: 00 Not liked: 403
and that message does not stop coming

**Comment by Yeshasvitvs** [comment]
@mrandersonb what did you change ?

**Comment by Yeshasvitvs** [comment]
@ProUserGithub Nope

**Comment by mrandersonb** [comment]
@Yeshasvitvs I changed:
(show-app)
json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
by...
(probably_has_app)
json_info = json.loads(re.search('{"activity.+probably_has_app', info.text, re.DOTALL).group(0)+'":""}')

at least it was connected and started to work but I generate that constant loop of
23.08.2018_18: 00 Trying to like media: 1852552920476525432
23.08.2018_18: 00 Not liked: 403

**Comment by json144** [comment]
I made the change to the username file and it's starts to work but then it's hangs my system. Please assist.

**Comment by json144** [comment]
Userinfo*

**Comment by ericwoolard** [comment]
Looks like it's now changed to "activity_counts.+probably_has_app'..

Change [activity.+probably_has_app](https://github.com/instabot-py/instabot.py/blob/8370b990d405547ae3858524c74805e79422c29b/src/userinfo.py#L42) to "activity_counts.+probably_has_app'.

`json_info = json.loads(re.search('{"activity_counts.+probably_has_app', info.text, re.DOTALL).group(0)+'":""}')`

Worked for me and should get you through the login, but I'm hitting nonstop 403's now once the bot starts to go to work.

**Comment by Yeshasvitvs** [comment]
@ericwoolard The key word `activity` is already matched. So, no need to use the full word `activity_counts`

**Comment by oakleyblack** [comment]
@mrandersonb your fix worked for me. just that one simple line. i ran into the 403 error but followed #1503 and we are back up and running!

**Comment by giocaputo** [comment]
Resolve replacing show_app with gatekeepers

**Comment by json144** [comment]
I system keeps hanging and crashes after I changed the "show_app" as suggested.  It begins to log in and starts to work but then crashes my system. Help please! @ @

**Comment by MediaGod** [comment]
I'm an OG noob to this i'm getting the Traceback ERROR .. i don't understand where i have to Edit the Show_app to probably_has_app

**Comment by ericwoolard** [comment]
@MediaGod in src/userinfo.py. This is the line to change https://github.com/instabot-py/instabot.py/blob/8370b990d405547ae3858524c74805e79422c29b/src/userinfo.py#L42

**Comment by json144** [comment]
@Yeshasvitvs Hello, I made the suggested changes mentined above and I continue to get this error message:


Traceback (most recent call last):
  File "c:/Users/jlem2/Desktop/instabot.py-master - Copy/example.py", line 58, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "c:\Users\jlem2\Desktop\instabot.py-master - Copy\src\instabot.py", line 232, in __init__
    self.login()
  File "c:\Users\jlem2\Desktop\instabot.py-master - Copy\src\instabot.py", line 301, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "c:\Users\jlem2\Desktop\instabot.py-master - Copy\src\userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

Please help.

**Comment by MediaGod** [comment]
@ericwoolard Okay so i went ahead and changed that Line and replaced the Show_app with Probably_has_app and once i do the save and go back to the Example.Py file to Run the code on the terminal i'm getting a IndentationError: unexpected indent  and it's talking about lines 6,1,5,7,6,25
'
which are the Example.py
init.py
instabot.py
Unfollow_protcol.py
Follow_protocol.py
and the Feed_scanner_.py

**Comment by ericwoolard** [comment]
@MediaGod That just means you have mixed up tabs/spaces. Open the conflicting files in your text editor and highlight the entire file and use your text editors 'convert tabs to spaces' function.

If you indent with tabs on one line but spaces on another, you'll receive whitespace errors in Python. That's all this means.

**Comment by fakeyMe** [comment]
Dear all master,
Can u give us the new git clone that work?
Thats all we need.

**Comment by alanifotis** [comment]
you guys are amazing

**Comment by json144** [comment]
Hey guys,

   I keep getting this error message after I made the suggested changes above.  The errormessage reads:

Traceback (most recent call last):
  File "c:/Users/Jean/Desktop/instabot.py-master 1/example2.py", line 58, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "c:\Users\Jean\Desktop\instabot.py-master 1\src\instabot.py", line 234, in __init__
    self.login()
  File "c:\Users\Jean\Desktop\instabot.py-master 1\src\instabot.py", line 304, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "c:\Users\Jean\Desktop\instabot.py-master 1\src\userinfo.py", line 41, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+probably_has_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by json144** [comment]
Hey Guys,

   I keep getting these messages:

Traceback (most recent call last):
  File "c:/Users/Jean/Desktop/instabot.py-master 1/example2.py", line 58, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "c:\Users\Jean\Desktop\instabot.py-master 1\src\instabot.py", line 234, in __init__
    self.login()
  File "c:\Users\Jean\Desktop\instabot.py-master 1\src\instabot.py", line 304, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "c:\Users\Jean\Desktop\instabot.py-master 1\src\userinfo.py", line 41, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+probably_has_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'


Please help!!

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
