### ISSUE TITLE
Error Traceback (most recent call last)

### ISSUE THREAD

**Issue by Mim1234** [instabot-py/instabot.py#1523]
Hello I am having an issue loging in. 
I get the following error: 

Traceback (most recent call last):
  File "example.py", line 44, in <module>
    unfollow_whitelist=[''])
  File "C:\Users\Downloads\instabot.py-master\instabot.py-master\src\instabot.py", line 234, in __init__
    self.login()
  File "C:\Users\Downloads\instabot.py-master\instabot.py-master\src\instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\Downloads\instabot.py-master\instabot.py-master\src\userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

Everything was working fine. Turned off my computer. When i turned it back on and launched the program i got this error all of a sudden. 

This is my code: 

#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="x",
    password="x",
    like_per_day=303,
    comments_per_day=15,
    tag_list=['weighted blankets', 'insomnia', 'anxiety', 'anxietyrelief','anxietymanagement','stress','stressrelief','stress','sleepbetter','sleeplonger','sleephelp'],
    tag_blacklist=['free', 'promo','sex','pussy','swadl','nirvana','mycalmblanket','hushblanket'],
    user_blacklist={'nirvana','mycalmblanket','blanquil','hushblnaket'},
    max_like_for_one_tag=67,
    follow_per_day=107,
    follow_time=1 * 76,
    unfollow_per_day=93,
    unfollow_break_min=17,
    unfollow_break_max=33,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this","your"],
                  ["photo", "picture", "pic"],
                  ["is", "looks","is really"],
                  ["great", "super","cool","magnificent",
                   "very cool", "beautiful", "so beautiful",
                   "lovely",
                   "so lovely", "very lovely"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
      'free','sex','dick','pussy','nirvana','mycalmblanket','giveaway','mycalm','mycalmblanket','blanquil','roccabi','swadl','cheap','promo','gravityblanket'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

Can someone please help!

**Comment by Yeshasvitvs** [comment]
Replace the word (show_app)[https://github.com/instabot-py/instabot.py/blob/8370b990d405547ae3858524c74805e79422c29b/src/userinfo.py#L42] with `probably_has_app` @Mim1234

**Comment by arhajati** [comment]
Can some one fix a new commit to fix the current login issue?

**Comment by Yeshasvitvs** [comment]
@arhajati I opened a PR https://github.com/instabot-py/instabot.py/pull/1525

**Comment by Mehranp** [comment]
same

**Comment by Yeshasvitvs** [comment]
@Mehranp did you try this branch https://github.com/Yeshasvitvs/instabot.py/tree/fix/login_error

**Comment by khaleefaalhammadi** [comment]
same issue

**Comment by Mehranp** [comment]
@Yeshasvitvs Tnx Bro , worked !

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
