### ISSUE TITLE
get status_login in web from console

### ISSUE THREAD

**Issue by pooria920** [instabot-py/instabot.py#1524]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
i want use flask for my resful-api. i want get username and pass from user. when i run the app. the status_login show me on console and i login to my account successfully but i want return json format to my client. and when i open browser and go to my rout i have this error: 

```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. 
```

## Config
where is my mistake in code?

```
app = Flask(__name__)


@app.route("/login", methods=['POST', 'GET'])
def index():
    if request.method == 'GET':
        bot = InstaBot('user', 'pass')
        bot.auto_mod()
        var = bot.login_status
        while var:
            return jsonify({"login_status": var})


if __name__ == "__main__":
    app.run()
```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
