### ISSUE TITLE
[can't login] KeyError: csrftoken

### ISSUE THREAD

**Issue by mdrzn** [instabot-py/instabot.py#1526]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [X] Linux
- [ ] Android

## Python Version?
- [X] 2.x
- [ ] 3.x

## Description of your issue

Ok let's do it in order.
I download the master.zip, unzip it, set my credentials in the example.py and launch it:

```
File "/root/instabot.py-master/src/instabot.py", line 289, in login
    self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python2.7/dist-packages/requests/cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
```
so it doesn't work out of the box. 
Since the error is "csrftoken" which is mentioned in issue#1499, I tried to fix it using that code, but even after trying to fix userinfo.py line 42 and instabot.py etc. etc. I still get the csrftoken error, so what is the correct login code?

## Config

```
r = self.s.get(self.url)
        self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
        time.sleep(5 * random.random())
        login = self.s.post(self.url_login, data=self.login_post, allow_redirects=True)
        self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
        self.csrftoken = login.cookies['csrftoken']
        ig_vw=1536; ig_pr=1.25; ig_vh=772;  ig_or=landscape-primary;
        self.s.cookies['ig_vw'] = '1536'
        self.s.cookies['ig_pr'] = '1.25'
        self.s.cookies['ig_vh'] = '772'
        self.s.cookies['ig_or'] = 'landscape-primary'
        time.sleep(5 * random.random())
```

**Comment by mdrzn** [comment]
I've read other threads, still not sure on how to proceed from here or if I even have the correct login code.

**Comment by albaplaza** [comment]
Have you changed your password?
Maybe is because of that

**Comment by mdrzn** [comment]
Still stuck

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
