### ISSUE TITLE
Is there a way to unfollow people automatically?

### ISSUE THREAD

**Issue by fedex03** [instabot-py/instabot.py#1528]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue

```
Hi there,
since the automatically unfollow  and also the mode 5 don't work, is there a way to unfollow people automatically?

After three day, the bot add to my account several following ( ~800 ), I don't want to reach an high number of following. So is there a smart way to unfollow people with out do it manually?

Thanks for the help.

P.S. now I disabled the following feature setting **follow_per_day** equal to 0.
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by HartHerbert** [comment]
same here

**Comment by mohibk** [comment]
same here. please solve this.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
