### ISSUE TITLE
NoneType has no attribute group

### ISSUE THREAD

**Issue by oakleyblack** [instabot-py/instabot.py#1529]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
I have been using the bot for about 2 months and now i'm not able to successfully login < REPLACE THIS TEXT
```

## Config

```
Traceback (most recent call last):
  File "example.py", line 43, in <module>
    unfollow_whitelist=[])
  File "/Users/alexjefferson/Desktop/instabot.py-master/src/instabot.py", line 232, in __init__
    self.login()
  File "/Users/alexjefferson/Desktop/instabot.py-master/src/instabot.py", line 301, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/alexjefferson/Desktop/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by ricardoon** [comment]
I am having the same issue.

**Comment by ronecharles** [comment]
I am having the same issue too

**Comment by sausagerus** [comment]
same too 
+1

**Comment by BrianneHostutler** [comment]
+1 same issue with same OS and python 3.7.0

**Comment by GriffinAustin** [comment]
Same issue here. Windows 10 and python 3.6.4

**Comment by JustAnotherBrick** [comment]
+1 Same issue here on Windows 10 and python 3.6.3

**Comment by Katsugi** [comment]
Same here. Mac OS and python 2.7
Please help!

**Comment by Meekachu** [comment]
I had this same issue, but when away when I used the updated files from the Pull requests section #1502 and #1503

**Comment by nbgabriel** [comment]
Thanks Meekachu!! i'll try!

**Comment by erikpi** [comment]
This seems to be the reasons for unfollow not working either. 

```
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "F:\instabot\instabot.py-master\src\instabot.py", line 869, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+show_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by ericwoolard** [comment]
Looks like it's now changed to "activity_counts.+probably_has_app'..

Change [activity.+probably_has_app](https://github.com/instabot-py/instabot.py/blob/8370b990d405547ae3858524c74805e79422c29b/src/userinfo.py#L42) to "activity_counts.+probably_has_app'.

`json_info = json.loads(re.search('{"activity_counts.+probably_has_app', info.text, re.DOTALL).group(0)+'":""}')`

Worked for me and should get you through the login, but I'm hitting nonstop 403's now once the bot starts to go to work.

**Comment by oakleyblack** [comment]
i changed "activity.+show_app " to "activity.+probably_has_app" and that fixed it until i ran into the 403 error. i followed #1503 and we're back up and working!

**Comment by MarkoGroenendijk** [comment]
I have tried the solutions and maked the changes and double checked it but i still hit the inlog error and it started to remove already liked media. I have also try turn on a vpn aswell. Still stuck? NEed help please :)
