### ISSUE TITLE
Tags only in selected location

### ISSUE THREAD

**Issue by worldsdream** [instabot-py/instabot.py#1530]
I know that we need to get the id of the location and paste it in tags. But that will tag random stuff from that location tag. 

What I want is that it will like the tags that I specify in that selected location. 

What I want for example.

Location: san francisco
Tag: flowers, houses, buildings. 

What it does right now for example:
Tag: san francisco location, flowers, houses, buildings.

**Comment by BasileFerrante** [comment]
Hi Guys, 

I'm looking for this kind of specific research. Does anyone get the solution to link the tag and the location (ex: #gaming in Paris...) 

Thank you in advance for your help ! 

Regards, 
Basile

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
