### ISSUE TITLE
Add function to request and response a challenge 

### ISSUE THREAD

**Issue by sauky** [instabot-py/instabot.py#1534]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ x] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ x] 2.x
- [ ] 3.x

## Description of your issue
Please add function to request and response a challenge requirement.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
