### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by mrandersonb** [instabot-py/instabot.py#1538]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x ] 3.x

## Description of your issue

```
Traceback (most recent call last):
  File "C:\instabotnew\movilfix.py", line 54, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\instabotnew\src\instabot.py", line 234, in __init__
    self.login()
  File "C:\instabotnew\src\instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\instabotnew\src\userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'
>>> 

HELP ME PLEASE
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by greylabs-india** [comment]
Facing the same issue

**Comment by ChrisatYT** [comment]
Same issue.
Really would love some help please.

**Comment by CazGirl** [comment]
Same

**Comment by ericwoolard** [comment]
Make sure you check both open and closed issues for answers in the future. You can find a fix here https://github.com/instabot-py/instabot.py/issues/1529#issuecomment-416006738

**Comment by json144** [comment]
facing the same issue just that miones says:

Traceback (most recent call last):
  File "c:/Users/Jean/Desktop/instabot.py-master 1/example2.py", line 58, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "c:\Users\Jean\Desktop\instabot.py-master 1\src\instabot.py", line 234, in __init__
    self.login()
  File "c:\Users\Jean\Desktop\instabot.py-master 1\src\instabot.py", line 304, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "c:\Users\Jean\Desktop\instabot.py-master 1\src\userinfo.py", line 41, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+probably_has_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks

**Comment by MertisWee** [comment]
sameeee
