### ISSUE TITLE
Traceback (most recent call last) not working. 

### ISSUE THREAD

**Issue by wellingt0n** [instabot-py/instabot.py#1543]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
i, seen the other issues with this message(Traceback ("most recent call last):") and I tried everything and it didn't work. Maybe it's because it's a littlebit different than the others:

Traceback (most recent call last):
File "example.py", line 52, in <module> 
unfollow_whitelist=['example_user_1', 'example_user_2']>
file "c:\user\wellington\downloads\instabot.py-master\src\instabot.py", line 234, in_init_
     self.login<>
file "c:\user\wellington\downloads\instabot.py-master\src\instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login<self.user_login>
file "c:\user\wellington\downloads\instabot.py-master\src\userinfo.py" line 42, in get_user_id_by_login
     json_info = json.loads<re.search<'{"activity.+show_app', info.text, re.dotall>.group<0>+'":""}'>
attributeError: 'nonetype' object has no attribute 'group'

Can you help me please ?

attached is an error print! thank you
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```
![erro](https://user-images.githubusercontent.com/41695153/44662550-7b3c7f00-a9e4-11e8-9ce5-8fbb9c6032e1.PNG)

**Comment by MarkoGroenendijk** [comment]
I have exactly  the same issue since today? Hope there will be a solution

**Comment by adrianrossi46** [comment]
Exactly the same issue, today it stopped working without any apparent reason :/

**Comment by wellingt0n** [comment]
I have updated the codes as suggested in #1502, #1503 and #1529, but the error was changed to:
Traceback <most recent call last>:
File "example.py", line 6, in <module>
from src. instabot import instabot
File "C:\ User\wellington\downloads\instabot.py-master\src\_init_.py", line 1, in <module>
from .instabot import instabot
ImportError: cannot import name 'instabot'

Could you help me fix this new bug?

Follow the print!

![image](https://user-images.githubusercontent.com/41695153/44785885-cbdce500-ab68-11e8-967e-56329e4031d3.png)

**Comment by leoct69** [comment]
I Have this same problem, I've tried to fix this for days now. Anyone can help please?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
