### ISSUE TITLE
IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by manguszta** [instabot-py/instabot.py#1544]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue

I'm having this issue daily. The Bot stops running after a while, randomly.
![kepkivagas](https://user-images.githubusercontent.com/18244325/44665023-367d0c00-aa15-11e8-92a0-2e22851f5d94.PNG)

## Config

This is what I have before line 809, `del self.media_by_tag[0]` is 809:
```
    def new_auto_mod_like(self):
        if time.time() > self.next_iteration["Like"] and self.like_per_day != 0 \
                and len(self.media_by_tag) > 0:
            # You have media_id to like:
            if self.like_all_exist_media(media_size=1, delay=False):
                # If like go to sleep:
                self.next_iteration["Like"] = time.time() + \
                                              self.add_time(self.like_delay)
                # Count this tag likes:
                self.this_tag_like_count += 1
                if self.this_tag_like_count >= self.max_tag_like_count:
                    self.media_by_tag = [0]
            # Del first media_id
            del self.media_by_tag[0]
```

I noticed that this error occurs right after checking already liked medias or already followed accounts.
These are my code snippets around checking:

```
if check_already_liked(self, media_id=self.media_by_tag[i]['node']['id']) == 1:
                                self.write_log("  [-] You are trying to like what you have already liked before")
                                #del self.media_by_tag[0]
                                self.get_media_id_by_tag(random.choice(self.tag_list))
                                return False
```
```
if check_already_followed(self, user_id=self.media_by_tag[0]['node']["owner"]["id"]) == 1:
                self.write_log("  [-] You have already followed this user before: " + self.media_by_tag[0]['node']["owner"]["id"])
                #del self.media_by_tag[0]
                self.get_media_id_by_tag(random.choice(self.tag_list))
                self.next_iteration["Follow"] = time.time() + \
                                                self.add_time(self.follow_delay/2)
                return
```

I tried to include `del self.media_by_tag[0]`, but it doesn't influence anything.

I thought I include `self.get_media_id_by_tag(random.choice(self.tag_list))` because I want to check certain hashtags that doesn't have new posts too often, but I don't want to check them until max_like_for_one_tag, because I know that the bot would have a very hard time finding a post that it hasn't liked/followed before, I want the bot to stop trying after finding the first already liked/followed.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
