### ISSUE TITLE
Except on get info!

### ISSUE THREAD

**Issue by rayopositivo** [instabot-py/instabot.py#1548]
28.08.2018_11:42 Trying to login as xxxxx...

28.08.2018_11:42 xxxxx login success!
28.08.2018_11:42 xxxxx : Get user info
28.08.2018 11:42
28.08.2018_11:42 Checking user info..
28.08.2018_11:42 Except on get_info!
28.08.2018_11:43 datagenconsultora : Get user info
28.08.2018 11:43
28.08.2018_11:43 Checking user info..
28.08.2018_11:43 Except on get_info!
28.08.2018_11:43 datagenconsultora : Get user info
28.08.2018 11:43
28.08.2018_11:43 Checking user info..
28.08.2018_11:43 Except on get_info!
28.08.2018_11:44 datagenconsultora : Get user info
28.08.2018 11:44
28.08.2018_11:46 Checking user info..
28.08.2018_11:46 Except on get_info!
Traceback (most recent call last):
  File "C:\Users\pc\Downloads\bot\instabot.py", line 79, in <module>
    check_status(bot)
  File "C:\Users\pc\Downloads\bot\src\check_status.py", line 10, in check_status

    get_user_info(self, self.user_login)
  File "C:\Users\pc\Downloads\bot\src\user_info.py", line 84, in get_user_info
    time.sleep(20)
KeyboardInterrupt
28.08.2018_11:46 Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
28.08.2018_11:46 Bot work time: 0:03:59.959000
28.08.2018_11:46 Logout success!

**Comment by rayopositivo** [comment]
The problem was with mode 1

**Comment by tayloriuss** [comment]
have the same problem

**Comment by lucii21** [comment]
Got the same problem in mode 1.
Hope there will be help soon. 
Mode 0 is the only one I can use without problems.

**Comment by Z-Walt-734** [comment]
Not sure if you all are having this problem still but I found a way to fix it. By removing the first line of mode 1 (line 79 in the example file) it makes mode 1 work. I think the bot check was a little premature.

**Comment by nikilkumar9** [comment]
Same problem here

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
