### ISSUE TITLE
issue database error

### ISSUE THREAD

**Issue by rugge89lau** [instabot-py/instabot.py#1555]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

sorry guys i've search it but not find anything, this is my problem:

Traceback (most recent call last):
  File "example.py", line 16, in <module>
    log_mod = 1)
  File "/Users/ruggero/Downloads/instabot.py-master/src/instabot.py", line 162, in __init__
    check_and_update(self)
  File "/Users/ruggero/Downloads/instabot.py-master/src/sql_updates.py", line 7, in check_and_update
    self.follows_db_c.execute("CREATE TABLE IF NOT EXISTS usernames (username varchar(300))")
sqlite3.DatabaseError: database disk image is malformed
Mac-Pro-di-Ruggero:instabot.py-master ruggero$

**Comment by rugge89lau** [comment]
i tried to subscrive the SCR folder with the updated one, but still remain the problem

**Comment by rugge89lau** [comment]
no one know?

**Comment by rugge89lau** [comment]
No one have this problem? I don't understand what is the problem

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
