### ISSUE TITLE
Instabot problems

### ISSUE THREAD

**Issue by saidch1** [instabot-py/instabot.py#1556]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting? no
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [ x] 3.x

## Description of your issue
When instabot tries to login , i get this message pasted next:
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\Said\Downloads\instabot.py-master\src\instabot.py", line 234, in __init__
    self.login()
  File "C:\Users\Said\Downloads\instabot.py-master\src\instabot.py", line 304, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\Said\Downloads\instabot.py-master\src\userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by thecompix** [comment]
same here.

**Comment by leourl** [comment]
same here

**Comment by JustAnotherBrick** [comment]
I had this issue a few days ago. Try implementing fix from pull request [#1503](https://github.com/instabot-py/instabot.py/pull/1503/files)

**Comment by Pariahs** [comment]
Still having this issue.
Anyone knows how to deal with it?

**Comment by sanchezfranco** [comment]
The problem was solved with JustAnotherBrick reply. Thanks!

**Comment by leourl** [comment]
just tryied, didn't work

**Comment by sanchezfranco** [comment]
Did u get 403 error? @leourl

**Comment by leourl** [comment]
yes...

**Comment by sanchezfranco** [comment]
Try now adding this fix [#1498](https://github.com/instabot-py/instabot.py/pull/1498/commits/9f6a2840083f56a855ab700022b10a97bd50aac1)

**Comment by manguszta** [comment]
Interesting. I have a similar problem, only with my 2 accounts of 4... I replaced the lines @JustAnotherBrick suggested, and it doesn't make any difference.
`KeyError: "name='csrftoken', domain=None, path=None"`

**Comment by saidch1** [comment]
guys it worked for me, even the unfollow is working also - justanotherbrick reply!

**Comment by leourl** [comment]
@saidch1 can you upload your folder to us?

**Comment by Serhiy23** [comment]
it would be great to upload your folder @saidch1 
I tried as @JustAnotherBrick replied but there is now another problem:

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\Serhiy\Desktop\1\src\instabot.py", line 232, in __init__
    self.login()
  File "C:\Users\Serhiy\Desktop\1\src\instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\Serhiy\Desktop\1\src\userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'


fck

**Comment by manguszta** [comment]
Okay, this fix works for all 4 of my accounts: https://github.com/instabot-py/instabot.py/pull/1503/commits/503673b350f3361aba5534aa31ca7ef0b7a2d8be
I implemented this fix as well: https://github.com/instabot-py/instabot.py/pull/1510/commits/df74cae0444ba55a0b65b4d4f5446acc4ff88281

**Comment by JustAnotherBrick** [comment]
@manguszta this worked for me. Thank you!

**Comment by manguszta** [comment]
I don't know what to think, only one of my accounts work now, the other 3 makes suspicious logins in Instagram app, and stops with the same old error message: `KeyError: "name='csrftoken', domain=None, path=None"`
I'm at work right now - yesterday when I couldn't start 2 of my bots, I was trying to start them from work. From home all accounts worked fine. Maybe this issue is all about the IP address. Instagram marked my workplace IP address as suspicious on the accounts I was trying to log in many times yesterday (to try the fixes above).

**Comment by leourl** [comment]
@JustAnotherBrick can u please upload your files? mine did not work, no matter what i do

**Comment by casaoui86** [comment]
Hello @leourl : you just need to delete spaces 
When I did copy/past didn't work for me
[instabot.txt](https://github.com/instabot-py/instabot.py/files/2340889/instabot.txt)

**Comment by casaoui86** [comment]
By the way, for the 2 other accounts i have this : 

31.08.2018_18:44 Trying to login as XXXXX....

31.08.2018_18:44 Login error! Connection error!
31.08.2018_18:44 Removing already liked medias..

Of course the password is correct -_-" Any idea how can i remediate this ? 
Also already tried to run script from another location (from USA and i'm based in France) but still the same thing 

From Insta Application, i had notification, if it was me who was connected from USA... even if i say yes, the bot didn't work 

HEEEEEEEEEELP

**Comment by rzabm** [comment]
instabot => erroes.txt
error file in the instabot folder


ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "E:\dow\New folder\instabot.py\src\instabot.py", line 894, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+gatekeepers', info.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
NameError: name 'info' is not defined
ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "E:\dow\New folder\instabot.py\src\instabot.py", line 894, in auto_unfollow
    all_data = json.loads(re.search('{"activity.+gatekeepers', info.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
NameError: name 'info' is not defined
ERROR:root:Except on unfollow... Looks like a network error
Traceback (most recent call last):
  File "E:\dow\New folder\instabot.py\src\instabot.py", line 691, in unfollow_on_cleanup
    unfollow = self.s.post(url_unfollow)
  File "E:\Programs\python-3.7.0\lib\site-packages\requests\sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "E:\Programs\python-3.7.0\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Programs\python-3.7.0\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "E:\Programs\python-3.7.0\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "E:\Programs\python-3.7.0\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)



@leourl @saidch1 @thecompix @JustAnotherBrick 

Why the Instagram Speed slowly And Error 403
I am a beginner in Python programming
please heeeeeeeeeeeeelllllllppppppppppp me :(

**Comment by aekramer** [comment]
> I don't know what to think, only one of my accounts work now, the other 3 makes suspicious logins in Instagram app, and stops with the same old error message: `KeyError: "name='csrftoken', domain=None, path=None"`
> I'm at work right now - yesterday when I couldn't start 2 of my bots, I was trying to start them from work. From home all accounts worked fine. Maybe this issue is all about the IP address. Instagram marked my workplace IP address as suspicious on the accounts I was trying to log in many times yesterday (to try the fixes above).
> 
> UPDATE:
> Yes, all accounts work from home, and not all work from my workplace. Same notebook, different IP.
> 
> UPDATE day 2:
> All accounts work from my workplace too. I haven't changed the code. Something was with the IP address, Instagram might have put some kind of filter on it, made the bot bounce back and caused a KeyError.

Yes it is. Try logging into instagram from your browser, you will notice instagram flagged it as a Suspicious login and you need to enter a verification code you can send to your email. The bot isn't able to do this so login on that IP adress through the app or browser first to make sure instagram trusts it, then start the bot. In some cases this still wont work (if you are running from a VPS or some kind of publicly known IP for botting, especially if its from a different country)

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
