### ISSUE TITLE
make bot to only comment once for each user

### ISSUE THREAD

**Issue by moeinrahimi** [instabot-py/instabot.py#1559]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting? VPS - ubuntu server
- [ ] If so; have you tried running the code on your local machine? nope no reason to do that

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue

```
so bot comments on users posts more than one  time , is it anyway to stop that ?
i want the bot comments on each users posts only one time . 
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
