### ISSUE TITLE
ImportError: cannot import name UserInfo

### ISSUE THREAD

**Issue by lucae95** [instabot-py/instabot.py#1560]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue

```
Everytime when I want to tun the file in the terminal ist says:

Traceback (most recent call last):
  File "/Users/luca/Desktop/instabot.py-master/example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/luca/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/luca/Desktop/instabot.py-master/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/Users/luca/Desktop/instabot.py-master/src/userinfo.py", line 6, in <module>
    from .userinfo import UserInfo
ImportError: cannot import name UserInfo
```

## Config

```
```

**Comment by mackgbm** [comment]
Same Error.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
