### ISSUE TITLE
Unfollow Is Not Fuctioning

### ISSUE THREAD

**Issue by jfinly** [instabot-py/instabot.py#1561]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
The bot no longer unfollows accounts

01.09.2018_10:20 Trying to unfollow #1: 
01.09.2018_10:20 Getting user info : christina_bove
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/connection.py", line 56, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x10545b4a8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /p/BnLbP6ljZ5A/?__a=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10545b4a8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "barkerbeauty.py", line 71, in <module>
    bot.new_auto_mod()
  File "/Users/JoshuaAlexander/Desktop/instabot.py-master3/src/instabot.py", line 717, in new_auto_mod
    self.new_auto_mod_comments()
  File "/Users/JoshuaAlexander/Desktop/instabot.py-master3/src/instabot.py", line 785, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['shortcode']) == False:
  File "/Users/JoshuaAlexander/Desktop/instabot.py-master3/src/instabot.py", line 808, in check_exisiting_comment
    check_comment = self.s.get(url_check)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /p/BnLbP6ljZ5A/?__a=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10545b4a8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by VLNTNF** [comment]
Hi, 
I also figured it out... So I went on the app to unfollow manually people and I discovered that there is now a confirmation popup ! I think it's the cause of this problem...
Instagram devs are updating a lot lately

**Comment by jfinly** [comment]
What did you figure out? I have not received any pop-ups & I'm not being banned from following or unfollowing.

**Comment by VLNTNF** [comment]
Like this : https://gyazo.com/81f5c0006f2429c0f6afc78e805efd2d

**Comment by jfinly** [comment]
I'm not getting any pop-ups or being blocked from unfollowing; That only happens if you abuse the tool. My issue is in the algorithm somewhere.

**Comment by zahareevici** [comment]
Trying to unfollow #1: 

how to fix this ?

**Comment by RaspberryPiZero** [comment]
Following this cause I have this problem too. At first I thought that the program can only unfollow who it followed. But now that I see that there is also this new popup for the unfollow I guess we should wait for an update or start unfollowing manually...

**Comment by EntaThaVoid** [comment]
Getting this problem too. "Trying to unfollow #1:"

**Comment by eliareutlinger** [comment]
Same error here. When was the `new_auto_mod_unfollow()` def implemented?

**Comment by datarhan** [comment]
same error

**Comment by malakadj** [comment]
Here it only unfollows when I try to exit the program (On Mac by typing ctrl + c once). Shouldn't it continuously do unfollows? Anyone?

**Comment by TutOsirisOm** [comment]
Okay everyone, Go to pull requests and find one that says fixed unfollow method and merge that code into yours. It'll probably include other fixes to issues you might be encountering too. Just read the title and the comments and see which one fixes the issues you are having. You can Google how to apply a patch from GitHub as well which makes it easier to make these changes. And whoever is getting that popup you need to change your settings because that popup was to limit you.

**Comment by alexandercgf** [comment]
Any update? Can anybody send me their code? I've tried the pull requests and all the posted solutions. The bot still gets stuck trying to unfollow #1 or says there's nobody to unfollow.

**Comment by notjamesobrien** [comment]
I've tried pretty much every proposed fix throughout several issues and PRs and so far nothing has worked.

**Comment by jfinly** [comment]
> I had the same issue, but now it's working fine. Try my code.
> [src.zip](https://github.com/instabot-py/instabot.py/files/2411691/src.zip)

I get 403 not liked with your src

**Comment by mrallanodreman** [comment]
@datarhan tú código tiene algunos errores, está dejando de seguir a las personas que sigue sin esperar nada de tiempo y de esa manera no va a tener efecto efectivo.

Necesito que el botón deje de seguir a quienes no me siguen!

No a los nuevos seguidos!

**Comment by mrallanodreman** [comment]
@jfinly fixed!

**Comment by eliareutlinger** [comment]
If you still have issues with this and/or the `follow_time` which is not used at all, you can try my source I slightly edited: [InstaBotAllFixed.zip](https://github.com/instabot-py/instabot.py/files/2427010/InstaBotAllFixed.zip)

Keep in mind that with my code, whenever the `unfollow()` or `auto_unfollow()` method gets executed it will check for all possible unfollows regarding the defined `follow_time`.

I also upgraded the `comment_list` in my "startup-script" so it generates much more complex comments (including emojis) to prevent being detected by Insta 😆 

And there's some improvement in printing useful information/logging.

**Comment by cobrakaistudent** [comment]
> If you still have issues with this and/or the `follow_time` which is not used at all, you can try my source I slightly edited: [InstaBotAllFixed.zip](https://github.com/instabot-py/instabot.py/files/2427010/InstaBotAllFixed.zip)
> 
> Keep in mind that with my code, whenever the `unfollow()` or `auto_unfollow()` method gets executed it will check for all possible unfollows regarding the defined `follow_time`.
> 
> I also upgraded the `comment_list` in my "startup-script" so it generates much more complex comments (including emojis) to prevent being detected by Insta 😆
> 
> And there's some improvement in printing useful information/logging.

I am trying your version very good with all the printing information, one question though, what is this?

    >>> Skipped 7 Users: Next end of follow-time in 349 Minutes
15.10.2018|17:25| All Follows checked
    >>> Next Unfollow-Check in 108.00 Seconds <<<

What is this trying to explain?

**Comment by eliareutlinger** [comment]
> I am trying your version very good with all the printing information, one question though, what is this?
> 
> ```
> >>> Skipped 7 Users: Next end of follow-time in 349 Minutes
> ```
> 15.10.2018|17:25| All Follows checked
> >>> Next Unfollow-Check in 108.00 Seconds <<<
> 
> What is this trying to explain?

This tells you how many users aren't ready for an unfollow yet because of your defined follow-time. And in the end it tells when the next unfollow regarding that parameter is possible.

The bottom line will just give you the calculated result of your defined unfollows per day (So it should be always the same).

**Comment by cobrakaistudent** [comment]
> > I am trying your version very good with all the printing information, one question though, what is this?
> > ```
> > >>> Skipped 7 Users: Next end of follow-time in 349 Minutes
> > ```
> > 15.10.2018|17:25| All Follows checked
> > > > > Next Unfollow-Check in 108.00 Seconds <<<
> > 
> > 
> > What is this trying to explain?
> 
> This tells you how many users aren't ready for an unfollow yet because of your defined follow-time. And in the end it tells when the next unfollow regarding that parameter is possible.
> 
> The bottom line will just give you the calculated result of your defined unfollows per day (So it should be always the same).

this is a very very good improvement your printing information is actually very good, now, what i was looking was to unfollow all of the followed, i really don't want to follow anyone, i see that if someone doesn't follow you back you unfollow but what if i really want to unfollow everything the script follows, no matter if they follow back or the feed

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks

**Comment by fensterbankett** [comment]
> 
> 
> If you still have issues with this and/or the `follow_time` which is not used at all, you can try my source I slightly edited: [InstaBotAllFixed.zip](https://github.com/instabot-py/instabot.py/files/2427010/InstaBotAllFixed.zip)
> 
> Keep in mind that with my code, whenever the `unfollow()` or `auto_unfollow()` method gets executed it will check for all possible unfollows regarding the defined `follow_time`.
> 
> I also upgraded the `comment_list` in my "startup-script" so it generates much more complex comments (including emojis) to prevent being detected by Insta 😆
> 
> And there's some improvement in printing useful information/logging.

hi,

how did you get emojis in your example.py ?
