### ISSUE TITLE
Error after setup

### ISSUE THREAD

**Issue by joost-heijden** [instabot-py/instabot.py#1568]
I get this error:

Traceback (most recent call last):
  File "example.py", line 48, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
TypeError: __init__() takes at least 3 arguments (17 given)

**Comment by KyleTrimpe** [comment]
Having the same issue. I believe instagram updated something to break this? I'm not sure though.

**Comment by KyleTrimpe** [comment]
in -> src/userinfo.py -> line 42

remove this:
json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
add this:
json_info = json.loads(re.search('{"activity.+probably_has_app', info.text, re.DOTALL).group(0)+'":""}')

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
