### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by zeplintor** [instabot-py/instabot.py#1573]
after editing the python file and setting all things up i get this 

Traceback (most recent call last):
  ```
File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/moncefokbi/Desktop/instabot.py-master/src/instabot.py", line 234, in __init__
    self.login()
  File "/Users/moncefokbi/Desktop/instabot.py-master/src/instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/moncefokbi/Desktop/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by deanainsworth** [comment]
Same here...

**Comment by leourl** [comment]
try #1503, let me know if it works.... i had the same problem...

now mine gets stuck in "Getting user info" .... but it stills likes the hashtags normally...

**Comment by deanainsworth** [comment]
The change on line 42 of userinfo.py fixed it for me, thanks so much! Seems to be working perfectly now...

**Comment by leourl** [comment]
@deanainsworth everything is working? can you please upload your files? so i can compare to mines and try to fix it?

**Comment by deanainsworth** [comment]
I may have spoken too soon. It's liking media but doesn't appear to be following. I'll keep an eye on it for a little while and come back to you.

**Comment by colorful-soltuion** [comment]
I have the same problem, has someone a solution for this problem right now ?

**Comment by Fromthebottom** [comment]
Works as charm

**Comment by eibt** [comment]
@deanainsworth which change on line 42?

**Comment by deanainsworth** [comment]
This resolved my problem - 

https://github.com/instabot-py/instabot.py/pull/1503/commits/806e09414f73a461bdb81fd6d4fc2e1e34a54ef8

**Comment by zeplintor** [comment]
this https://github.com/instabot-py/instabot.py/commit/806e09414f73a461bdb81fd6d4fc2e1e34a54ef8 also resolve the probleme but i do get stuck in getting user info

**Comment by eibt** [comment]
https://github.com/instabot-py/instabot.py/commit/806e09414f73a461bdb81fd6d4fc2e1e34a54ef8 worked for me too 😎👍
