### ISSUE TITLE
SERIOUS INQUIRY 

### ISSUE THREAD

**Issue by glishe** [instabot-py/instabot.py#1575]
I need someone very experienced to program me a custom variant of this script that is able to comment on new posts from a specific group of Instagram accounts. Sorry if this type of message isn't allowed on here but I really need this. Please contact me through discord (lay#9999) I AM PAYING!!

**Comment by TutOsirisOm** [comment]
If you still need this I can do it. Discord: TutOsirisOm

**Comment by scotsfloki** [comment]
Hi did you do that code?

**Comment by TutOsirisOm** [comment]
Added you on discord. I didn't do it yet, I'll do it as a job for you if you pay for the work.
