### ISSUE TITLE
Like specific account likers media

### ISSUE THREAD

**Issue by smurgggg** [instabot-py/instabot.py#1577]
- [x] I have searched for other issues with the same problem. (including #1153)

- [x] Feature Request

### Operating System? (include version)
- [x] Windows

## Python Version?
- [x] 3.x

Hi,
i think it will be best in order to get focused likes&followers to have this feature:
- not look into hastags but into accounts media, given an account name ---> (look into "account" medias)
- start to like and follow the likers of that medias

i don't think is a very complicated thing, but if you could do that or try to explain me how to modify the code i would very appreciate that!

Thanks a lot

**Comment by TutOsirisOm** [comment]
If you still need this I can do it. Discord: @TutOsirisOm

**Comment by TutOsirisOm** [comment]
I'll work on this, just need to find correct endpoints.
