### ISSUE TITLE
Getting KeyError: "name='csrftoken', domain=None, path=None" durring login.

### ISSUE THREAD

**Issue by adodado** [instabot-py/instabot.py#1580]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue
I have it running on an raspberry pi, and i cannot get it to login. i am getting the well known error:
07.09.2018_23:38 Instabot v1.2.0 started at 07.09.2018 23:38:

07.09.2018_23:38 Trying to login as instado...

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/home/pi/Python/instabot.py/src/instabot.py", line 234, in __init__
    self.login()
  File "/home/pi/Python/instabot.py/src/instabot.py", line 289, in login
    self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "/home/pi/.local/lib/python2.7/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/home/pi/.local/lib/python2.7/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

I have tried all the solutions i could find here amongst the issues, changing the userinfo.py or instabot.py and so forth and nothing has worked. Any suggestions about what i might try?

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by claudiofrancesconi** [comment]
same here

**Comment by Tschingis0711** [comment]
same here. 
I think I'm banned. Has someone an idea how to handle it? Using a proxy? Unfortunately did not find the rght explication how to insert one...

**Comment by claudiofrancesconi** [comment]
i don't think it's the ip cause:
1. when i connect back with my phone (on the same wifi) it connects without problems (except the first time that says about the previous suspicious connection from the bot).. and
2. when i use a vps server from another country it gives me the same result and block the account temporally

so i guess is more a problem with the user agent or something like that

**Comment by oheidinger** [comment]
same here.

till yesterday everything was fine.

**Comment by alexlaza10** [comment]
Could anybody be so glad and share the src file dictionary. Bcz i've changed line 42 and line 289 and i get the same error ? 

Kind regards

**Comment by envie15** [comment]
I'm getting exactly the same error and I've also tried all the steps in other #'s.

**Comment by kamilk91** [comment]
this error tells you that you have 2FA (2 step) authorisation. Try to remove that from settings.

**Comment by envie15** [comment]
@kamilk91 just checked and it's not on, not using 2 step authorisation...

**Comment by palford7** [comment]
For me it was because I'd changed my username and forgot. Check your login details peeps :)

**Comment by kamilk91** [comment]
@envie15 check behaviour on opened via sellenium browser. Maybe it can help you? Are you sure to give good creditentials? Do you have newest chrome driver?
