### ISSUE TITLE
Please help this noob!

### ISSUE THREAD

**Issue by stuster123** [instabot-py/instabot.py#1584]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

Hi. Sorry as this is probably a stupid question but I am really new to this and running into some challenges! I am receiving the below errors even though I think I've followed everything as I should have so far. Could anyone take a look and point me in the right direction, please? I'd appreciate any help or support anyone can give me, and thank you in advance to anyone who takes the time to read :)

## Config

C:\Users\Stuart and Bon\Desktop\instabot.py-master> example.py
Traceback (most recent call last):
  File "C:\Users\Stuart and Bon\Desktop\instabot.py-master\example.py", line 6, in <module>
    from src import InstaBot
  File "C:\Users\Stuart and Bon\Desktop\instabot.py-master\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\Stuart and Bon\Desktop\instabot.py-master\src\instabot.py", line 305
    self.user_id = 8399637278
                            ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by ByrnesByrnes** [comment]
InstaBot.py that file
Look at or around line 305 and make sure your spaces are correct. 4 spaces  = 1 tab make sure it’s all fluid with that sequence.
