### ISSUE TITLE
Suspicious login attemt loop

### ISSUE THREAD

**Issue by TutOsirisOm** [instabot-py/instabot.py#1594]
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [x] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

Just wondering if anyone else is encountering the Suspicious login loop. Not sure if just on my end or Instagrams. I've tried various things such as changing my user-agent. Might just have to wait it out.

**Comment by loganyc1934** [comment]
Having the same issue. Using user-agent the same as my local machine. The same code works locally on my laptop but gets login error and "Unusual Attempt" blocks on EC2. What to change on the EC2 end? Anybody?
