### ISSUE TITLE
tag_list combination

### ISSUE THREAD

**Issue by maxlagrange** [instabot-py/instabot.py#1596]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

Hey guys,

wondering whether it's possible to combine the tag_list? Means, only 1 picture is getting liked if the picture has two/three/more predefined hashtags.

Thanks for your time.

**Comment by LopesX** [comment]
I think, not understand your issue
