### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by cheetowaffles** [instabot-py/instabot.py#1598]
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so; have you tried running the code on your local machine?

#### Select one:
- [X] Bug (Not sure)
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
- [X] MAC OSX Sierra
- [X] Windows 10 x64
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X] 3.x

## Description of your issue

```
ImportError: No module named requests
```

## Config

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login='example',
    password='example',
    like_per_day=1000,
    comments_per_day=0,
    tag_list=['dankmemes', 'epic', 'funny', 'memes'],
    tag_blacklist=['russ'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['skylar.holden', 'cheetowaffles'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 2

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")
```

**Comment by daylanvig** [comment]
Install the missing module.

On Windows, open your command prompt and type "pip install requests".
For Mac you'll have to google how to install a module.

**Comment by cheetowaffles** [comment]
Ive done pip3 install requests and requirements.txt neither fixes the
problem. all instructions in your video were followed and many others are
also having this problem.

**Comment by cheetowaffles** [comment]
?

**Comment by kimothorick** [comment]
If you're using a mac you need to use the sudo command so that it can get the administrator privileges to install the missing modules.
Try this: sudo python install -r requirements.txt.

**Comment by jsubet** [comment]
Having the same issue! `ImportError: No module named requests`

**Comment by kimothorick** [comment]
> Having the same issue! `ImportError: No module named requests`

are you using a mac or pc?

**Comment by jsubet** [comment]
Mac

Matteo Subet
Studente | Università di Genova - DAD
Product Manager & CEO | EMAT Digital Marketing
M. +39 3385448346 | L. +39 3924745120
matteosubet@gmail.com

**Comment by kimothorick** [comment]
Try this on your terminal:

sudo python install -r requirements.txt.

**Comment by kimothorick** [comment]
> Mac Matteo Subet Studente | Università di Genova - DAD Product Manager & CEO | EMAT Digital Marketing M. +39 3385448346 | L. +39 3924745120 matteosubet@gmail.com
> […](#)
> Il giorno 17 set 2018, alle ore 17:07, Kimotho Rick ***@***.***> ha scritto: Having the same issue! ImportError: No module named requests are you using a mac or pc? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Try this in the terminal to install all requirements:

sudo python install -r requirements.txt.

**Comment by Obsessi0n** [comment]
I'm having same problem on Ubuntu.

**Comment by jsubet** [comment]
@kimothorick display this error with your code “python: can't open file 'install': [Errno 2] No such file or directory”

**Comment by cheetowaffles** [comment]
> Install the missing module.
> 
> On Windows, open your command prompt and type "pip install requests".
> For Mac you'll have to google how to install a module.

i have done that multiple times in every directory. it successfully installs but continues to say that it cannot locate "requests"

**Comment by cheetowaffles** [comment]
> If you're using a mac you need to use the sudo command so that it can get the administrator privileges to install the missing modules.
> Try this: sudo python install -r requirements.txt.

I tryed what you said and received this messge:
The directory '/Users/skylarholden/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/skylarholden/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

**Comment by Obsessi0n** [comment]
Here is how i fixed it:
`git clone git://github.com/kennethreitz/requests.git`
then open the folder requests and type
`python setup.py install`

**Comment by Rinarikato** [comment]
> Here is how i fixed it:
> `git clone git://github.com/kennethreitz/requests.git`
> then open the folder requests and type
> `python setup.py install`

I'm with the same issue, but I tried this solution and it doesn't work, I've tried using a win7 x86 and Python 2.x, I'll try at my home machine it's x64 with newer Python, perhaps it's happening this because this machine use betwin, but I'll make more tests

**Comment by LopesX** [comment]
You try use virtualenv ?

**Comment by JanisSharma** [comment]
To install requests module on Debian/Ubuntu for Python2:

$ sudo apt-get install python-requests

And for Python3 the command is:

$ sudo apt-get install python3-requests

Full Source At [Here](https://icetutor.com/question/importerror-no-module-named-requests/)
