### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by bvttle** [instabot-py/instabot.py#1599]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [x] 3.7.0

## Description of your issue

```
I have transferred a version of the bot I was using on mac successfully. Trying to install on windows and get these issues:

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "D:\instabot.py-master\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "D:\instabot.py-master\src\instabot.py", line 283
    r = self.s.get(self.url)
                           ^
TabError: inconsistent use of tabs and spaces in indentation
```

## Config

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="xxxxxxxx",
    password="xxxxxxx",
    like_per_day=1000,
    comments_per_day=500,
    tag_list=['35mm', '35mmfilm', 'filmphotography', 'lomochromepurple', 'dubblefilm', 'analogphotography', 'filmphotography', 'filmshooters', 'staybrokeshootfilm', 'shootfilmstaybroke', 'shootfilm', 'analog'],
    tag_blacklist=['nswf'],
    user_blacklist={},
    max_like_for_one_tag=100,
    follow_per_day=0,
    follow_time=1 * 60,
    unfollow_per_day=1000,
    unfollow_break_min=1,
    unfollow_break_max=2,
    log_mod=0,
    proxy='',
    
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["amazing", "great", "cool", "nice", "neat"],
                  ["shot", "!", "ðŸ˜"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

```

**Comment by bvttle** [comment]
Fixed.. ! Was some issues with the indentation and a mixture of tabs and spaces. Converted all to spaces.

**Comment by bvttle** [comment]
> > Fixed.. ! Was some issues with the indentation and a mixture of tabs and spaces. Converted all to spaces.
> 
> What exactly did you do? Have been trying to fix for coming on a few hours and frustration is mounting. Thanks.

I opened up src/instabot.py and navigated to line 283. Removed all the spacing and tabs,
then replaced the spacing with manual spaces in sets of 4. Lines 283 - 297 e.g:
```
    r = self.s.get(self.url)
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
    time.sleep(5 * random.random())
    login = self.s.post(
        self.url_login, data=self.login_post, allow_redirects=True)
    self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
    self.csrftoken = login.cookies['csrftoken']
    #ig_vw=1536; ig_pr=1.25; ig_vh=772;  ig_or=landscape-primary;
    self.s.cookies['ig_vw'] = '1536'
    self.s.cookies['ig_pr'] = '1.25'
    self.s.cookies['ig_vh'] = '772'
     self.s.cookies['ig_or'] = 'landscape-primary'
    time.sleep(5 * random.random())
```

Basically run through that section and replace all the spacing with spaces in sets of 4, hope that makes sense?

**Comment by gumdropsteve** [comment]
@bvttle makes sense, tried something like that but was probably making frustration mistakes.. Will test out again later today and get back to you.. Thanks a million regardless 
👏👍

**Comment by gumdropsteve** [comment]
> 
> 
> @bvttle makes sense, tried something like that but was probably making frustration mistakes.. Will test out again later today and get back to you.. Thanks a million regardless
> 👏👍

Fixed the tabs and spaces error, thank you  @bvttle! Now I'm here:

`
C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master>python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master\src\instabot.py", line 298
    if login.status_code == 200:
    ^
IndentationError: unexpected indent

C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master>
`

**Comment by gumdropsteve** [comment]
> 
> 
> > @bvttle makes sense, tried something like that but was probably making frustration mistakes.. Will test out again later today and get back to you.. Thanks a million regardless
> > 👏👍
> 
> Fixed the tabs and spaces error, thank you @bvttle! Now I'm here:
> 
> `
> C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master>python example.py
> Traceback (most recent call last):
> File "example.py", line 6, in
> from src import InstaBot
> File "C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master\src__init__.py", line 1, in
> from .instabot import InstaBot
> File "C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master\src\instabot.py", line 298
> if login.status_code == 200:
> ^
> IndentationError: unexpected indent
> 
> C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master>
> `

Fixed it as spaces all the way to 312 (after that seems to be spaces, same with before 283)

Now I'm here:

`
C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master>python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master\src\instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master\src\userinfo.py", line 42
    json_info = json.loads(re.search(r'>window._sharedData = (.*?);</script>', info.text, re.DOTALL).group(1))
    ^
IndentationError: unexpected indent

C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master>
`

**Comment by gumdropsteve** [comment]
> 
> 
> > > @bvttle makes sense, tried something like that but was probably making frustration mistakes.. Will test out again later today and get back to you.. Thanks a million regardless
> > > 👏👍
> > 
> > 
> > Fixed the tabs and spaces error, thank you @bvttle! Now I'm here:
> > `
> > C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master>python example.py
> > Traceback (most recent call last):
> > File "example.py", line 6, in
> > from src import InstaBot
> > File "C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master\src__init__.py", line 1, in
> > from .instabot import InstaBot
> > File "C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master\src\instabot.py", line 298
> > if login.status_code == 200:
> > ^
> > IndentationError: unexpected indent
> > C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master>
> > `
> 
> Fixed it as spaces all the way to 312 (after that seems to be spaces, same with before 283)
> 
> Now I'm here:
> 
> `
> C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master>python example.py
> Traceback (most recent call last):
> File "example.py", line 6, in
> from src import InstaBot
> File "C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master\src__init__.py", line 1, in
> from .instabot import InstaBot
> File "C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master\src\instabot.py", line 6, in
> from .userinfo import UserInfo
> File "C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master\src\userinfo.py", line 42
> json_info = json.loads(re.search(r'>window._sharedData = (.*?);</script>', info.text, re.DOTALL).group(1))
> ^
> IndentationError: unexpected indent
> 
> C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master>
> `

Simple fix: my userinfo.py line 42 & 43 were one space too indented.

Presented new: 

C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master>python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master\src\instabot.py", line 25, in <module>
    class InstaBot:
  File "C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master\src\instabot.py", line 284, in InstaBot
    r = self.s.get(self.url)
NameError: name 'self' is not defined

C:\Users\USER\Downloads\GitHub\instabot.py-master\instabot.py-master>
