### ISSUE TITLE
Traceback call 

### ISSUE THREAD

**Issue by technotedesign** [instabot-py/instabot.py#1601]
Traceback (most recent call last):
  File "insta.py", line 6, in <module>
    from src import InstaBot
  File "/Users/name/Desktop/insta/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/name/Desktop/insta/src/instabot.py", line 5, in <module>
    from .unfollow_protocol import unfollow_protocol
  File "/Users/name/Desktop/insta/src/unfollow_protocol.py", line 7, in <module>
    from .follow_protocol import follow_protocol
  File "/Users/name/Desktop/insta/src/follow_protocol.py", line 6, in <module>
    from .feed_scanner import feed_scanner
  File "/Users/name/Desktop/insta/src/feed_scanner.py", line 24
    self.current_user = self.media_on_feed[chooser]["node"]["owner"]["username"]
    ^

**Comment by leoct69** [comment]
I'm still having this problem, i've tried everything.

**Comment by guitar9** [comment]
same

**Comment by copiapsp** [comment]
Same, 
any ideas?

**Comment by copiapsp** [comment]
SOLVED

1) downland the last instabot.py
2) Change src/userinfo.py  Line 42 
json_info = json.loads(re.search(r'>window._sharedData = (.*?);</script>', info.text, re.DOTALL).group(1))

[https://github.com/instabot-py/instabot.py/commit/806e09414f73a461bdb81fd6d4fc2e1e34a54ef8](url)

**Comment by kostasosfp** [comment]
> After this I'm getting this error.
> 
> Traceback (most recent call last):
> File "insta.py", line 6, in 
> from src import InstaBot
> File "/Users/davidvaclavik/Desktop/insta/src/**init**.py", line 1, in 
> from .instabot import InstaBot
> File "/Users/davidvaclavik/Desktop/insta/src/instabot.py", line 5, in 
> from .unfollow_protocol import unfollow_protocol
> File "/Users/davidvaclavik/Desktop/insta/src/unfollow_protocol.py", line 7, in 
> from .follow_protocol import follow_protocol
> File "/Users/davidvaclavik/Desktop/insta/src/follow_protocol.py", line 6, in 
> from .feed_scanner import feed_scanner
> File "/Users/davidvaclavik/Desktop/insta/src/feed_scanner.py", line 24
> self.current_user = self.media_on_feed[chooser]["node"]["owner"]["username"]
> ^
> IndentationError: unexpected indent

me too
