### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by canofcatfood** [instabot-py/instabot.py#1602]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [X] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [X] Windows
- [X] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X] 3.x

## Description of your issue

```
Include the contents of the error.log here (if applicable):
Traceback (most recent call last):
  File "/home/nut/Documents/Instabot.py/instabot.py-master/example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/home/nut/Documents/Instabot.py/instabot.py-master/src/instabot.py", line 234, in __init__
    self.login()
  File "/home/nut/Documents/Instabot.py/instabot.py-master/src/instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/home/nut/Documents/Instabot.py/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by coxsa216** [comment]
also having the same problem

**Comment by Elywaen** [comment]
Me too, anyone can help us ? Thanks.

**Comment by olaims** [comment]
the same here

**Comment by olaims** [comment]
solution

https://github.com/instabot-py/instabot.py/commit/806e09414f73a461bdb81fd6d4fc2e1e34a54ef8

**Comment by Metalzero2** [comment]
Indeed, that works.  Maybe this issue should be closed then

**Comment by Molar3NK** [comment]
i am on the same page here

**Comment by Molar3NK** [comment]
done !!! change line 42 on userinfo.py 

json_info = json.loads(re.search('{"activity.+probably_has_app', info.text, re.DOTALL).group(0)+'":""}')

**Comment by LopesX** [comment]
@canofcatfood If its working good, please close the issue!

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/pull/1732
