### ISSUE TITLE
Not starting also with the fix

### ISSUE THREAD

**Issue by Konoga** [instabot-py/instabot.py#1608]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

C:\Users\x\Downloads\instabot>python example1.py
Traceback (most recent call last):
  File "example1.py", line 6, in <module>
    from src import InstaBot
  File "C:\Users\x\Downloads\instabot\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\x\Downloads\instabot\src\instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "C:\Users\x\Downloads\instabot\src\userinfo.py", line 42
    json_info = json.loads(re.search(r'>window._sharedData = (.*?);</script>', info.text, re.DOTALL).group(1))

**Comment by raziraz** [comment]
Having the same issue

**Comment by mdrzn** [comment]
I'm stuck too.. and the dev stopped updating it couple months ago.
