### ISSUE TITLE
How can i run 2 accounts on a android device?

### ISSUE THREAD

**Issue by mrallanodreman** [instabot-py/instabot.py#1609]
Its possible?  

Moto g3
Lineage OS 7.1 
Using termux

**Comment by DubDubDan** [comment]
Its a long shot, but have you used TMUX tool within Linux? However, I'm not sure if the fake user agent could handle more than one account/connection. Give it a test and let us know!

**Comment by mrallanodreman** [comment]
Im using a android device!
In window only with copy and rename the bot folder you can ejecute both without problems but i just cant do that con termux

**Comment by DubDubDan** [comment]
ah, okay. Alternative solution. Sign up to cloud.google.com and use their free 12 month offer. Setup multiple tiny linux servers for each account you need to run. I followed this [https://medium.com/@rohanarun/how-to-build-an-instagram-bot-farm-in-15-minutes-for-free-14468c844f7a](url)

**Comment by Nocturnal-2** [comment]
@mrallanodreman I like to run from Android as well. Could you please explain me how to do that?

**Comment by mrallanodreman** [comment]
Sure!
I Will make a git!

**Comment by Nocturnal-2** [comment]
@mrallanodreman Thank you!
