### ISSUE TITLE
Fake useragent

### ISSUE THREAD

**Issue by bubol** [instabot-py/instabot.py#1610]
Hi guys could you help me? I have MacBook high Sierra, python 3,7,0 And my problem is this:

<img width="1280" alt="zrzut ekranu 2018-09-21 o 13 35 11" src="https://user-images.githubusercontent.com/36332158/45881835-a11f2e80-bdac-11e8-9273-2f47f751864c.png">

**Comment by ByrnesByrnes** [comment]
If you have root python set up
Go into terminal and install requests
Since you’re using a Mac
 Sudo pip install requests

**Comment by leoct69** [comment]
i've the same problem, i have installed requests and thats up to date, i have installed sudo pip install request but still get line 6 error. Please help!
