### ISSUE TITLE
What happens to followed users when bot terminated abruptly?

### ISSUE THREAD

**Issue by Nocturnal-2** [instabot-py/instabot.py#1614]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

I started the bot with _like_per_day=800_ and _follow_per_day=100_. It has been running for more than 10 hours and already followed many. Now I am in a compulsion to terminate the program. I am wondering what will happen to the users followed. Will they be unfollowed when I run the program next time?

## Config
""" like_per_day=800,
    comments_per_day=0,
    tag_list=['australia', 'sydney', 'seeaustralia', 'melbourne', 'australiagram', 'queensland', 'exploreaustralia',
              'ig_australia', 'brisbane', 'perth', 'westernaustralia', 'discoveraustralia', 'goldcoast', 'aussiephotos',
              'aussie', 'visitmelbourne', 'adelaide', 'ilovesydney', 'newsouthwales', 'exploringaustralia',
              'thisisqueensland', 'southaustralia', 'australia_shotz', 'nsw', 'victoria', 'thisiswa',
              'melbourneiloveyou', 'igersaustralia', 'discoverqueensland', 'wow_australia2016'],
    tag_blacklist=['sex', 'boobs', 'pussy'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=100,
    follow_time=1 * 60,
    unfollow_per_day=30,
    unfollow_break_min=15,
    unfollow_break_max=30,"""

**Comment by Amnoon** [comment]
I am also curious about this. Does anyone know? What happens when you stops the bot and restart it. does it keep checking the accounts on the database or does it resets it and starts again?
