### ISSUE TITLE
Stuck at trying to comment!

### ISSUE THREAD

**Issue by AyoubMarouan** [instabot-py/instabot.py#1620]
Hello there, i use the script in windows 10, python 3.5 : 
- like => 403
- comment : does not work, they repete it 4 to 5 times without any other messages
Can someone help please ?

**Comment by pinkoveralls** [comment]
I'm also having the same issue. I applied all the 403 error fixes from back in late august, but as of a couple days ago I'm getting 403 errors again.

**Comment by LopesX** [comment]
open a new issue following rules...
try with python 2.7
