### ISSUE TITLE
How to terminate instabot.py gracefully?

### ISSUE THREAD

**Issue by Nocturnal-2** [instabot-py/instabot.py#1624]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

I run instabot.py as a background process in my Linux machine. I like to shutdown the program once in a while to change the initialization parameters and experiment with it my strategy. 

When the bot is running from the terminal (interactive), when I give the first break command (Ctrl + 'C'), it terminates the original flow and runs the cleanup methods. Only on the second break command it quits the program completely. This is really cool! Thanks to everyone who came up with this idea and implemented it!!

When I run the bot as a background process, how can I achieve the same behavior? In other words, how can I end the bot in such a way the cleanup routines are executed before ending completely. Thanks in advance for your time!

## Config

Not applicable.

**Comment by bjbrown920** [comment]
I use 'htop' and search for "example.py" and then kill that process. You can either kill it with the GUI or get the PID, exit 'htop', and run 'kill <pid>'.
