### ISSUE TITLE
It was working but not anymore...

### ISSUE THREAD

**Issue by github19844** [instabot-py/instabot.py#1628]
Hello guys, 

the bot was working perfectly, but now every time I click on the "example" (python file) to open the file the cmd window opens up and then says "trying to log in as  ....." and then closed by itself. 

Any idea why it's doing this? 

Thanks, 

Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by yrucbood** [comment]
Same here the bot just stops after logging successfully. Please help us out here :)
