### ISSUE TITLE
Login successful, unable to perform any actions, errors in lines 67, 342 and 725

### ISSUE THREAD

**Issue by Faabsie** [instabot-py/instabot.py#1629]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ X] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [ X] 3.x

## Description of your issue

```Traceback (most recent call last):
  File "test.py", line 67, in <module>
    bot.new_auto_mod()
  File "C:\Users\fjsni\Desktop\Bot\instabot.py-master\src\instabot.py", line 725, in new_auto_mod
    time.sleep(3)
KeyboardInterrupt
30.09.2018_06:47 Trying to unfollow: 8595019584
30.09.2018_06:47 Slow Down - Pausing for 5 minutes so we don't get banned!
30.09.2018_06:47 Pausing for 17 seconds... 0 of 0
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\fjsni\Desktop\Bot\instabot.py-master\src\instabot.py", line 342, in cleanup
    time.sleep(sleeptime)
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Standard with some different parameters. 
```

Anyone has a clue? Thanks in advance!

**Comment by LopesX** [comment]
try with python 2.7, show same error ?

**Comment by yrucbood** [comment]
Same here the bot just stops after logging successfully. Please help us out here :)

**Comment by LopesX** [comment]
local machine ?
