### ISSUE TITLE
Instabot does not work anymore with me(comment and follow and Not liked 403) [SOLVED]

### ISSUE THREAD

**Issue by stepacker** [instabot-py/instabot.py#1631]
Hello everyone, i have problem with instabot, that was working good but recetly (almost 5 day) does not work anymore
that show me probem Not liked 403
and also comment or follow does not work anymore.

01.10.2018_16:17 Removing already liked medias..
01.10.2018_16:17 Trying to like media: 1880616231143019886
01.10.2018_16:17 Not liked: 403
01.10.2018_16:17 Trying to follow: 1529508958
01.10.2018_16:17 Trying to comment: 1880612106866652402
01.10.2018_16:17 Trying to like media: 1880612106866652402
01.10.2018_16:17 Not liked: 403
01.10.2018_16:17 Trying to like media: 1880609063195049508
01.10.2018_16:17 Not liked: 403
01.10.2018_16:17 Trying to like media: 1880606238094545338
01.10.2018_16:17 Not liked: 403
01.10.2018_16:17 Trying to like media: 1880603250367840070
01.10.2018_16:17 Not liked: 403
01.10.2018_16:17 Trying to like media: 1880602466619587726
01.10.2018_16:17 Not liked: 403
01.10.2018_16:17 Trying to like media: 1880601428462243473
01.10.2018_16:17 Not liked: 403
fixed #1631

**Comment by isayhow** [comment]
me too help

**Comment by pmella16** [comment]
same

**Comment by phum126** [comment]
broken.

**Comment by spikerang** [comment]
same

**Comment by JulianoCK** [comment]
Same here. =/

**Comment by b4ckbre4ker** [comment]
not yet.  i still have mine running past few days and they are working not risking turning off yet lol

**Comment by zininvyacheslav** [comment]
same problem after restart((

**Comment by majimashokaas** [comment]
I had this problem along with the same a while back in August. I fixed it back then with the multiple changes to the code according to the people here in the issues. I finally managed to fix it this time by downloading a fresh instabot.py and applying the fix for #1635. I have not gotten the 403 error in the new instance but I'm not sure how permanent the fix is. You guys can try it to see if it works for you too.

**Comment by isayhow** [comment]
thank you very much majimashokaas

**Comment by phum126** [comment]
> I had this problem along with the same a while back in August. I fixed it back then with the multiple changes to the code according to the people here in the issues. I finally managed to fix it this time by downloading a fresh instabot.py and applying the fix for #1635. I have not gotten the 403 error in the new instance but I'm not sure how permanent the fix is. You guys can try it to see if it works for you too.

doesn't work.

**Comment by bubublik** [comment]
Yes. Its helps! 

Fresh install and replacing line 42 of userinfo.py gets my bot working again.
> `json_info = json.loads(re.search(r'>window._sharedData = (.*?);</script>', info.text, re.DOTALL).group(1))`

**Comment by b4ckbre4ker** [comment]
https://github.com/LopesX/instabot.py

**Comment by stepacker** [comment]
> I had this problem along with the same a while back in August. I fixed it back then with the multiple changes to the code according to the people here in the issues. I finally managed to fix it this time by downloading a fresh instabot.py and applying the fix for #1635. I have not gotten the 403 error in the new instance but I'm not sure how permanent the fix is. You guys can try it to see if it works for you too.

Thank you that is work

**Comment by stepacker** [comment]
> > > I had this problem along with the same a while back in August. I fixed it back then with the multiple changes to the code according to the people here in the issues. I finally managed to fix it this time by downloading a fresh instabot.py and applying the fix for #1635. I have not gotten the 403 error in the new instance but I'm not sure how permanent the fix is. You guys can try it to see if it works for you too.
> > 
> > 
> > Can confirm. Fresh install and replacing line 42 of userinfo.py gets my bot working again.
> > `json_info = json.loads(re.search(r'>window._sharedData = (.*?);</script>', info.text, re.DOTALL).group(1))`
> 
> that fixed it perfectly for me too

Thank you that is work

**Comment by LopesX** [comment]
@stepacker If its working good, please close the issue
