### ISSUE TITLE
ModuleNotFoundError: No module named 'fake_useragent'

### ISSUE THREAD

**Issue by Molar3NK** [instabot-py/instabot.py#1634]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [x ] Other

### Operating System? (include version)
- [x ] MAC
- [ ] Windows
- [ ] Linux
- [x] Android

## Python Version?
- [x] 2.x
- [ x] 3.x

## Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```
Daniels-MacPro:~ 3Molar$ python /Users/thz/Desktop/instabot.py-master/example.py
Traceback (most recent call last):
  File "/Users/thz/Desktop/instabot.py-master/example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/thz/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/thz/Desktop/instabot.py-master/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'
Daniels-MacPro:~ 3Molar$
![noname](https://user-images.githubusercontent.com/43768756/46325228-49ab6a80-c5c5-11e8-96c1-9013e2f732c3.png)

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by Molar3NK** [comment]
first time trying to run instabot... need some help

**Comment by Molar3NK** [comment]
update phyton 3.7.0 
![noname](https://user-images.githubusercontent.com/43768756/46326318-2e8f2980-c5ca-11e8-9085-62d536fac687.png)

**Comment by Rinarikato** [comment]
the module fake_useragent is not installed, install it via pip

**Comment by pd-escher** [comment]
still gives the same error
