### ISSUE TITLE
module error

### ISSUE THREAD

**Issue by ESTEBANBpy** [instabot-py/instabot.py#1644]
Hi,(running windows 10, py 3.x)
I did everything exactly how it was shown in the video, unfortunately I have some problemedes with the bot.
I had a look at the code and everything seemed to be fine, the atachment shows the rsponse of the cmd prompt,
Thank you if you were able to help me
![cmd p jpg](https://user-images.githubusercontent.com/43906464/46572511-4e866a80-c987-11e8-80ac-6f391da63f07.JPG)

**Comment by afaque24** [comment]
GOT the same error.

**Comment by atongenow** [comment]
i have the same issue
