### ISSUE TITLE
What is the purpose of removing already liked medias

### ISSUE THREAD

**Issue by Nocturnal-2** [instabot-py/instabot.py#1645]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1008 #986 )

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [x] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

When I instabot.py, sometimes it keep removing the "Removing already liked medias..". I like to understand what is the purpose of this? Does this unlike the post which has been liked earlier?

I see that the same question has been asked earlier ( #1008 and #986 ) but couldn't find an answer.

**Comment by afaque24** [comment]
Lol I messed up with example.py to the extent i am getting only syntax
errors now.

**Comment by Nocturnal-2** [comment]
@afaque24 This is not related to the topic

**Comment by nolaguy002** [comment]
Have you been able to find the purpose of Removing already liked medias? And does it actually remove your like from the photo?

Thanks!

**Comment by Nocturnal-2** [comment]
@nolaguy002 I have no idea yet. I am waiting for a reply from experts.

**Comment by cobrakaistudent** [comment]
@Nocturnal-2 did you get any info on this? I am also trying to find out this..

**Comment by dimisdas** [comment]
@cobrakaistudent Hello! Please don’t bump old issues (necrothreading).

The bot keeps a record of all the posts it has already liked/commented.

When it grabs posts from a hashtag, it checks them against its local database to make sure it won’t like/comment on them twice. Hence the “Removed Already Liked Media” message.
