### ISSUE TITLE
Not Liked 403

### ISSUE THREAD

**Issue by thebrettism** [instabot-py/instabot.py#1649]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [x] 3.x

## Description of your issue

So a couple days ago after instagram going down, i had some issues with the fake useragent stuff, but now all that is sorted. Ive been trying to use the bot all morning, testing on python 3.6, 3.7 and 2.7 

I keep getting the Not Liked 403 error
![capture](https://user-images.githubusercontent.com/13056905/46586826-6de4db00-cae0-11e8-9ef0-60bddc3400ea.JPG)

Ive already changed the CSRFToken like in a previous fix.. still isnt helping the issue, did fix it in the past but now i believe it is a different issue.
![2](https://user-images.githubusercontent.com/13056905/46586843-b3090d00-cae0-11e8-8fbf-43ebbd57c4bc.JPG)

any ideas? ive checked through alot of other threads cause i know this is a common issue.

**Comment by ronecharles** [comment]
i too...same problem! Ive already changed the CSRFToken

**Comment by heldausberlin** [comment]
I have the same problem. Changing line 42 in userinfo.py didn’t fix it. The file is already up to date. So what could it be?

**Comment by alabialex** [comment]
i also have this same problem please we need help

**Comment by robkos442** [comment]
Having the same issue on windows 10. It's liking the first one that it tries, then everything else gives me Not Liked: 403
![instabot](https://user-images.githubusercontent.com/38138055/50443059-90141b00-08cf-11e9-83db-291ea7560cf5.PNG)

**Comment by ronecharles** [comment]
Closed?? What solution??

**Comment by dimisdas** [comment]
There’s been a major update on main branch. Update and try again. Closing old threads. If problem persists please create a new issue. 

Thanks
