### ISSUE TITLE
Not Liked: 400

### ISSUE THREAD

**Issue by innovative-designer** [instabot-py/instabot.py#1659]
Hello Everyone, 
yesterday everything was working fine. now I am trying to login it prompts me the following error

12.10.2018_03:37 naughtywotty login success!
12.10.2018_03:37 Get Media by location: 212999109
12.10.2018_03:37 Removing already liked medias..
12.10.2018_03:37 Trying to like media: 1888237482711869694
12.10.2018_03:37 Not liked: 400
12.10.2018_03:37 Trying to follow: 232914089
12.10.2018_03:37 Followed: 232914089 #1.
12.10.2018_03:37 Trying to unfollow #1:
12.10.2018_03:37 Getting user info : dlozano7

And after this nothing is happening... 

I have worked on this error: #1649  but haven't found any solution

**Comment by ggunay** [comment]
I got the same issue, tried both locally and on the cloud, so it is not related to IP ban.

20.10.2018_09:52 Get Media by tag: mcdonalds
20.10.2018_09:52 Removing already liked medias..
20.10.2018_09:52 Trying to like media: 1894224120946643481
20.10.2018_09:52 Not liked: 400
20.10.2018_09:52 Trying to follow: 1399429606
20.10.2018_09:52 Trying to unfollow #1:
20.10.2018_09:52 Getting user info : XXX (cencored)
20.10.2018_09:52 Trying to comment: 1894224069391068016
20.10.2018_09:53 Trying to like media: 1894224069391068016
20.10.2018_09:53 Not liked: 400
20.10.2018_09:53 Trying to like media: 1894221661450547690
20.10.2018_09:53 Not liked: 400
20.10.2018_09:54 Trying to like media: 1894223881980516448
20.10.2018_09:54 Not liked: 400

**Comment by ggunay** [comment]
I have rechecked with another account and it still works, so i believe that previous account is somehow blacklisted. Interesting thing is, I can still login on web and comment/like on the browser with that account, so it is related to the bot's behaviour, that's the thing blacklisted. Could it be some of the headers (like user agent) or maybe related to the timings?
