### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by lucaob** [instabot-py/instabot.py#1660]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue

Instabot does not run and I receive the following error:
Traceback (most recent call last):
  File "test.py", line 54, in <module>
    unfollow_whitelist=['user1', 'user2'])
  File "/home/luca/instabot.py-master/src/instabot.py", line 234, in __init__
    self.login()
  File "/home/luca/instabot.py-master/src/instabot.py", line 287, in login
    csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0)
AttributeError: 'NoneType' object has no attribute 'group'

I never used Instabot before so these are my first try.
This is the content of my errors.log file:
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): xxx.xxx.xxx.xxx

**Comment by lucaob** [comment]
I forgot to mention that I already applied Fix #1589.
I also modified line 42 of userinfo.py as follows:
json_info = json.loads(re.search(r'>window._sharedData = (.*?);</script>', info.text, re.DOTALL).group(1))

**Comment by sameerisa** [comment]
Same issue.

**Comment by ugurozturk** [comment]
@sameerisa can you test again via fresh clone ? the code itself updated

**Comment by sameerisa** [comment]
I did and it works thanks.

**Comment by lucaob** [comment]
I just tried with a fresh installation with no luck. I run the code two times without any change in the code from the first to the second run, but I obtained two different errors!

When I first run Instabot, the error obtained was this one:

> 16.11.2018_12:39 Instabot v1.2.0 started at 16.11.2018 12:39:
> 16.11.2018_12:39 Trying to login as XXXXXX...
> 16.11.2018_12:39 Login error! Check your login data!
> 16.11.2018_12:39 Removing already liked medias..
> 16.11.2018_12:39 Trying to unfollow #1:
> 16.11.2018_12:39 Looks like there is nobody to unfollow.
> 16.11.2018_12:39 Removing already liked medias..
> 16.11.2018_12:39 Removing already liked medias..
> 16.11.2018_12:39 Removing already liked medias..
> 16.11.2018_12:39 Removing already liked medias..
> ^X16.11.2018_12:40 Removing already liked medias..
> ^CTraceback (most recent call last):
>   File "InstabotTest.py", line 76, in <module>
>     bot.new_auto_mod()
>   File "/home/luca/instabot.py-master/src/instabot.py", line 736, in new_auto_mod
>     time.sleep(3)
> KeyboardInterrupt

The second run outcome was different (without any change in the code):

> 16.11.2018_12:42 Instabot v1.2.0 started at 16.11.2018 12:42:
> 16.11.2018_12:42 Trying to login as XXXXXXX...
> 
> Traceback (most recent call last):
>   File "IGbisonte.py", line 52, in <module>
>     'user1', 'user2'])
>   File "/home/luca/instabot.py-master/src/instabot.py", line 236, in __init__
>     self.login()
>   File "/home/luca/instabot.py-master/src/instabot.py", line 301, in login
>     r = self.s.get('https://www.instagram.com/')
>   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 249, in get
>     return self.request('get', url, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 229, in request
>     r.send(prefetch=prefetch)
>   File "/usr/lib/python2.7/dist-packages/requests/models.py", line 627, in send
>     raise ConnectionError(e)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: /
> 


No idea of what to do…
