### ISSUE TITLE
FakeUserAgentError: Maximum amount of retries reached

### ISSUE THREAD

**Issue by bvttle** [instabot-py/instabot.py#1662]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [x] 2.7.10
- [ ] 3.x

## Description of your issue

```
instabot.py-master Ben$ python bvttle.py 
Traceback (most recent call last):
  File "bvttle.py", line 38, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/Ben/Desktop/instabot.py-master/src/instabot.py", line 165, in __init__
    fake_ua = UserAgent()
  File "/Library/Python/2.7/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/Library/Python/2.7/site-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "/Library/Python/2.7/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
```

## Config

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="xxxxx",
    password="xxxxx",
    like_per_day=1000,
    comments_per_day=100,
    tag_list=['35mm', '35mmfilm', 'filmphotography', 'lomochromepurple', 'dubblefilm', 'analogphotography', 'filmshooters', 'staybrokeshootfilm', 'shootfilmstaybroke', 'shootfilm', 'revolog' ],
    tag_blacklist=['nswf', 'polaroid', 'believeinfilm'],
    user_blacklist={},
    max_like_for_one_tag=200,
    follow_per_day=0,
    follow_time=4 * 60 * 60,
    unfollow_per_day=100,
    unfollow_break_min=5,
    unfollow_break_max=15,
    log_mod=0,
    proxy='',
    
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["amazing", "great", "cool", "nice", "neat", "love this", "sweet"],
                  ["shot", "!", "😍"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'bags', 'follower', 'followers', 'sex', 'free', 'gain'],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

```

**Comment by Andy2903** [comment]
Seems like it was just temporary. Now it works again.

**Comment by Andy2903** [comment]
Seems like it was just a temporary problem. Now it works again.

**Comment by dkannoz** [comment]
Same problem here. It's already been a couple of days, never got this to work, same error. Any clue?

**Comment by flite3** [comment]
HI there,

This problem has started up for me again.  I moved over to @LopesX fork.  It seemed to work for the last couple of weeks. I tried to restart the script today, and I'm back to `fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached`

I've tried to upgrade my FakeUserAgent, but it can't because it's at the latest version.  I'm using Python version 3.7 on a mac.  I can't seem to install the requirements.txt on python 2.7 for some reason.  I'm not sure why the @LopesX version worked for a while and is now giving me this problem.

**Comment by flite3** [comment]
One of the things I kept noticing was this line in my errors
`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)>`

when I searched for this on the net, I noticed a few other python scripts that have had this problem.  Specifically for Mac os, apparently Python 2.7, 3.6, or 3.7, these versions don't install a command called certifi.  If you go into your applications folder -> python 2.7/3.6/3.7 there is a file there called Install Certificates.command.

If you run this file in terminal (open a terminal window, drag this file to the window, then hit return), this will install certifi, which will allow Fake_Useragent to verify ssl certificates, which seems to be causing this whole mess in the first place.  Well, that's what worked for me at least.  My version of instabot.py seems to be working fine now.

**Comment by sloth2012** [comment]
meet this too.

**Comment by cesaravina** [comment]
Thank you @flite3 !!! Ran Install Certificates.command from my Python application folder, and now my bot is back up and running.

**Comment by kddww8** [comment]
> Thank you @flite3 !!! Ran Install Certificates.command from my Python application folder, and now my bot is back up and running.

Can you provide cmd info like pip install certifi

**Comment by flite3** [comment]
> > Thank you @flite3 !!! Ran Install Certificates.command from my Python application folder, and now my bot is back up and running.
> 
> Can you provide cmd info like pip install certifi --upgrade

I'm sorry, I didn't really do anything but drag the file to my terminal window and pressed return, at least that's what a blog had said to do.  If someone else knows the command for what Install Certificates.command does, then please provide it.  Thank you very much.

**Comment by ndases** [comment]
> > Thank you @flite3 !!! Ran Install Certificates.command from my Python application folder, and now my bot is back up and running.
> 
> Can you provide cmd info like pip install certifi --upgrade

The command you probably looking for is:
pip install --upgrade certifi

**Comment by bvttle** [comment]
This seems to be an issue on Mac OSX which was fixed by @flite3 's solution. Thanks!

**Comment by mertopkaya** [comment]
thank you @flite3 !!! it's not my entire solution but reduce my errors.

**Comment by Wray14** [comment]
Here's what I did:

1. pip3 install fake_useragent --upgrade.  (on python 3, if you have lower version pip install works)
2. Type this in your python file (demo.py) ua=UserAgent(use_cache_server=False,verify_ssl=False)
3. Then work with UserAgents:

ua = UserAgent()
header = {'user-agent': ua.chrome}
print(ua.chrome)
