### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by stormdragon288** [instabot-py/instabot.py#1666]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC 10.12.6
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.7

## Description of your issue
How to solve ? Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/pc-1/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/pc-1/Desktop/instabot.py-master/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/Users/pc-1/Desktop/instabot.py-master/src/userinfo.py", line 5, in <module>
    import requests
ImportError: No module named requests﻿
```
Include the contents of the error.log here (if applicable). < How to solve ? Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/pc-1/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/pc-1/Desktop/instabot.py-master/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/Users/pc-1/Desktop/instabot.py-master/src/userinfo.py", line 5, in <module>
    import requests
ImportError: No module named requests﻿
```

## Config

```
Include the contents of your config here #!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="CLEAR",
    password="CLEAR",
    like_per_day=1000,
    comments_per_day=1000,
    tag_list=[ 'mensfashion',],
    tag_blacklist=['rain', 'thunderstorm', 'nsfw',],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=0,
    follow_time=1 * 60,
    unfollow_per_day=0,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

```

**Comment by 5ergi0** [comment]
Same for me! I installed python 3.6 in my mac then I installed the requirements with ''pip3 install -r requirements.txt'' after this I upgraded to 18.1 version using ''pip3 install --upgrade pip''. All of this was successful but now when I try to run the bot I get the same issue.
Hope someone can help me! 🙏

**Comment by volkovsurf** [comment]
Exactly the same problem, someone help

**Comment by volkovsurf** [comment]
What do you mean inside my virtual environment? I have changed the example to my proportions, updated surtindo.py, opened terminal a dialed following commands-
Cd desktop
Cd install....
Pip3 install -r requirements
Python example.py

**Comment by v4ult** [comment]
You should really run something like this inside a virtual environment. It makes life easier whenever you have to do updates. Never mind.

The traceback says that it can't find the requests module.

You will have to check that it is installed on your system.

In the terminal type 'python' to open the python interpreter.

Next type 'import requests'.

If you get an error at that point then the requests module is not installed.

Install it yourself then try running the script again.

**Comment by volkovsurf** [comment]
How do I install the requests module myself?

**Comment by 5ergi0** [comment]
Okay, I think to run the bot with the 3.6 version of python we have to type ''python3 example.py''. I've tried this and then I got issue [#1642](https://github.com/instabot-py/instabot.py/issues/1642).
The point is I installed python 3.6 version because I couldn't fix that issue. I've tried everything in the post... I don't know what's wrong with it.
In anycase thanks you all.

**Comment by volkovsurf** [comment]
yes I tried python3 and now it got stuck on the same issue #1642 I've also tried installing python 2.7 but it gets stuck there as well

**Comment by stormdragon288** [comment]
I'm running python 3.7 and still on this same issue and it's stuck. 

When trying to add requests I got:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named requests

How do I manually add that?

**Comment by volkovsurf** [comment]
> try py -m pip install requests

whats the exact command you are telling me to write because I tried : "py -m pip install requests" and "-m pip install requests" which told me that there is no such command and if I only try "pip install requests" it tells method the requirement is already satisfied

**Comment by Rinarikato** [comment]
so try python -m pip install requests

**Comment by volkovsurf** [comment]
Nope doesn’t work, all the requirements are already satisfied...

**Comment by stormdragon288** [comment]
>>> python -m pip install requests
  File "<stdin>", line 1
    python -m pip install requests
                ^
SyntaxError: invalid syntax

**Comment by stormdragon288** [comment]
> so try python -m pip install requests

>>> python -m pip install requests
  File "<stdin>", line 1
    python -m pip install requests
                ^
SyntaxError: invalid syntax

**Comment by jilliankeenan** [comment]
> > so try python -m pip install requests
> 
> What I got from this:
> 
> python -m pip install requests
> File "", line 1
> python -m pip install requests
> ^
> SyntaxError: invalid syntax

you are trying this in the python console try it in the directory of the project in the terminal window.

**Comment by stormdragon288** [comment]
> python -m pip install requests

/usr/bin/python: No module named pip

**Comment by jilliankeenan** [comment]
> > python -m pip install requests
> 
> /usr/bin/python: No module named pip

You need to install pip and add the path to your bash profile.

**Comment by v4ult** [comment]
It may not work with Python 3.7. 
Use a virtual environment. That way you can experiment with different versions of python to get it working.

1. Install Virtualenv and Pip: https://www.youtube.com/watch?v=dssx7_VBGJU
2. Make a folder for your virtual environments. Normally I would use a hidden folder but because you seem like you're new, put it in the home or Documents folder: mkdir ~/virtualenvs.
3. Change into this folder: cd ~/virtualenvs.
4. Create the virtualenv: virtualenv instabot
5. Activate the virtualenv: source ~/virtualenvs/instabot/bin/activate
6. Go to where ever you have this script and the requirements file saved on your machine: cd ~/Downloads/instabot.py/......
7. Run: pip install -r requirements.txt
8. If there are no errors now you can play.

Good luck!
There are videos in the readme file if you are stuck. Go and watch them.

**Comment by volkovsurf** [comment]
> It may not work with Python 3.7.
> Use a virtual environment. That way you can experiment with different versions of python to get it working.
> 
> 1. Install Virtualenv and Pip: https://www.youtube.com/watch?v=dssx7_VBGJU
> 2. Make a folder for your virtual environments. Normally I would use a hidden folder but because you seem like you're new, put it in the home or Documents folder: mkdir ~/virtualenvs.
> 3. Change into this folder: cd ~/virtualenvs.
> 4. Create the virtualenv: virtualenv instabot
> 5. Activate the virtualenv: source ~/virtualenvs/instabot/bin/activate
> 6. Go to where ever you have this script and the requirements file saved on your machine: cd ~/Downloads/instabot.py/......
> 7. Run: pip install -r requirements.txt
> 8. If there are no errors now you can play.
> 
> Good luck!
> There are videos in the readme file if you are stuck. Go and watch them.

I did exactly what you listed without any errors and when I tried running, it still gave me the initial error of this topic(((

**Comment by volkovsurf** [comment]
Oh sorry not the initial error of this topic the #1642 one

**Comment by stormdragon288** [comment]
> It may not work with Python 3.7.
> Use a virtual environment. That way you can experiment with different versions of python to get it working.
> 
> 1. Install Virtualenv and Pip: https://www.youtube.com/watch?v=dssx7_VBGJU
> 2. Make a folder for your virtual environments. Normally I would use a hidden folder but because you seem like you're new, put it in the home or Documents folder: mkdir ~/virtualenvs.
> 3. Change into this folder: cd ~/virtualenvs.
> 4. Create the virtualenv: virtualenv instabot
> 5. Activate the virtualenv: source ~/virtualenvs/instabot/bin/activate
> 6. Go to where ever you have this script and the requirements file saved on your machine: cd ~/Downloads/instabot.py/......
> 7. Run: pip install -r requirements.txt
> 8. If there are no errors now you can play.
> 
> Good luck!
> There are videos in the readme file if you are stuck. Go and watch them.

Searching for pip
Reading https://pypi.python.org/simple/pip/
Download error on https://pypi.python.org/simple/pip/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
Couldn't find index page for 'pip' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
No local packages or download links found for pip
error: Could not find suitable distribution for Requirement.parse('pip')

**Comment by stormdragon288** [comment]
Still need help

**Comment by v4ult** [comment]
Go to the #python channel on the freenode IRC. Someone there can help you in real time.

**Comment by papaloam** [comment]
> path to your bash profile

How I do this??

**Comment by papaloam** [comment]
same issue... Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/santiagoarizam/Desktop/instabot.py-master/src/instabot.py", line 234, in __init__
    self.login()
  File "/Users/santiagoarizam/Desktop/instabot.py-master/src/instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/santiagoarizam/Desktop/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+gatekeepers', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'
