### ISSUE TITLE
KeyError: 'likes' How to fix that?

### ISSUE THREAD

**Issue by kostasosfp** [instabot-py/instabot.py#1670]
**I have the problem below ...** 

16.10.2018_14:36 Trying to login as e@@@y...

16.10.2018_14:38 e@@@y login success!
16.10.2018_14:38 Get Media by tag: chania
16.10.2018_14:38 Removing already liked medias..
16.10.2018_14:38 Trying to like media: 1891377138534046314
16.10.2018_14:38 Liked: 1891377138534046314. Like #1.
16.10.2018_14:38 Trying to follow: 7506232445
16.10.2018_14:38 Followed: 7506232445 #1.
16.10.2018_14:38 e@@@y : Get media id on recent feed
 16.10.2018 14:38
16.10.2018_14:38 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
16.10.2018_14:38 e@@@y : Get media id on recent feed
 16.10.2018 14:38
16.10.2018_14:38 Except on get media!!
16.10.2018_14:38 ======> Get media id by Tag <======
16.10.2018_14:38 Get media by user success!
16.10.2018_14:38 Current Index = 1 of 70 medias
Traceback (most recent call last):
  File "example.py", line 85, in <module>
    bot.new_auto_mod()
  File "C:\Users\s@@@@s\Downloads\instabot.py-master\instabot.py-master\src\instabot.py", line 716, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "C:\Users\s@@@@s\Downloads\instabot.py-master\instabot.py-master\src\instabot.py", line 781, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "C:\Users\s@@@@s\Downloads\instabot.py-master\instabot.py-master\src\unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "C:\Users\s@@@@s\Downloads\instabot.py-master\instabot.py-master\src\follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File "C:\Users\s@@@@s\Downloads\instabot.py-master\instabot.py-master\src\feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "C:\Users\s@@@@s\Downloads\instabot.py-master\instabot.py-master\src\likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "C:\Users\s@@@@s\Downloads\instabot.py-master\instabot.py-master\src\likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
16.10.2018_14:38 Trying to unfollow: 7506232445
16.10.2018_14:38 Unfollow: 7506232445 #1 of 0.
16.10.2018_14:38 Pausing for 15 seconds... 1 of 0
16.10.2018_14:39 Logout: likes - 1, follow - 0, unfollow - 1, comments - 0.
16.10.2018_14:39 Bot work time: 0:02:15.552534
16.10.2018_14:39 Logout success!
PS C:\Users\s@@@@s\Downloads\instabot.py-master\instabot.py-master>

**Please could you help me solve this issue ?**

**Comment by kostasosfp** [comment]
anyone can help ?

**Comment by kostasosfp** [comment]
17.10.2018_11:40 Instabot v1.2.0 started at 17.10.2018 11:40:

17.10.2018_11:40 Trying to login as e#####y...

17.10.2018_11:40 e#####y login success!
17.10.2018_11:40 Get Media by tag: visitgreece
17.10.2018_11:40 Removing already liked medias..
17.10.2018_11:40 Trying to like media: 1892013534365420021
17.10.2018_11:40 Liked: 1892013534365420021. Like #1.
17.10.2018_11:40 Trying to follow: 1542600254
17.10.2018_11:40 Followed: 1542600254 #1.
17.10.2018_11:40 e#####y : Get media id on recent feed
 17.10.2018 11:40
17.10.2018_11:40 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
17.10.2018_11:40 e#####y : Get media id on recent feed
 17.10.2018 11:40
17.10.2018_11:40 Except on get media!!
17.10.2018_11:41 ======> Get media id by Tag <======
17.10.2018_11:41 Get media by user success!
17.10.2018_11:41 Current Index = 33 of 58 medias
Traceback (most recent call last):
  File "example.py", line 89, in <module>
    bot.new_auto_mod()
  File "C:\Users\s#####s\Downloads\instabot.py-master\src\instabot.py", line 716, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "C:\Users\s#####s\Downloads\instabot.py-master\src\instabot.py", line 781, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "C:\Users\s#####s\Downloads\instabot.py-master\src\unfollow_protocol.py", line 19, in unfollow_protocol
    follow_protocol(self)
  File "C:\Users\s#####s\Downloads\instabot.py-master\src\follow_protocol.py", line
23, in follow_protocol
    feed_scanner(self)
  File "C:\Users\s#####s\Downloads\instabot.py-master\src\feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "C:\Users\s#####s\Downloads\instabot.py-master\src\likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "C:\Users\s#####s\Downloads\instabot.py-master\src\likers_protocol.py", line
19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
17.10.2018_11:41 Trying to unfollow: 1542600254
17.10.2018_11:41 Unfollow: 1542600254 #1 of 0.
17.10.2018_11:41 Pausing for 28 seconds... 1 of 0
17.10.2018_11:41 Logout: likes - 1, follow - 0, unfollow - 1, comments - 0.
17.10.2018_11:41 Bot work time: 0:01:24.933464
17.10.2018_11:41 Logout success!
PS C:\Users\s#####s\Downloads\instabot.py-master>

**Comment by kostasosfp** [comment]
I TRIED THAT https://github.com/instabot-py/instabot.py/pull/1331 BUT IT DOESNT FIX THE PROBLEM

**Comment by lukaszwilk21** [comment]
Try to check "likers protocol" i have the same problem and i fix that by just change syntax in line 19 and 20:
def likers_protocol(self):
    if len(self.media_by_user) > 0:
        # You have media_id to like:
        self.current_index = random.randint(0, len(self.media_by_user) - 1)
        log_string = "Current Index = %i of %i medias" % (
            self.current_index, len(self.media_by_user))
        self.write_log(log_string)

    if self.media_by_user[self.current_index]["likes"]["count"] >= 10 and self.media_by_user[self.current_index]["likes"]["count"] < 100:
        get_user_id_post_page(self, self.media_by_user[self.current_index]["code"])
        username_checker(self)
    del self.media_by_user[self.current_index]


But now i have the problem cause bot try to unfollow just one account 
18.10.2018_19:59 XXXXX login success!
You choose mode : 5
CTRL + C to cancel this operation or wait 30 seconds to start
18.10.2018_19:59 XXXXX: Get media id on recent feed
 18.10.2018 19:59
18.10.2018_19:59 Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
18.10.2018_20:00 XXXXX : Get media id on recent feed
 18.10.2018 20:00
18.10.2018_20:00 Except on get media!!
18.10.2018_20:00 ======> Get media id by Tag <======
18.10.2018_20:00 Get media by user success!
18.10.2018_20:00 XXXX: Get user info
18.10.2018 20:00
18.10.2018_20:00 Checking user info..
18.10.2018_20:00 Except on get_info!
18.10.2018_20:00 ======> Get media id by user: hajka <======
18.10.2018_20:00 Reject this account
===================
Reason :
   Is Selebgram : False
   Is Fake Account : False
   Is Active User : False

18.10.2018_20:00 Trying to unfollow: hajka
18.10.2018_20:01 XXXXX: Get media id on recent feed
 18.10.2018 20:01
18.10.2018_20:01 Except on get media!!
18.10.2018_20:01 ======> Get media id by Tag <======
18.10.2018_20:01 Get media by user success!
==============================
Upss hajka is already in ex user list...
==============================
18.10.2018_20:01 XXXXX : Get media id on recent feed
 18.10.2018 20:01
18.10.2018_20:01 Except on get media!!
18.10.2018_20:02 ======> Get media id by Tag <======
18.10.2018_20:02 Get media by user success!
==============================
Upss hajka is already in ex user list...
==============================
18.10.2018_20:02 XXXXX : Get media id on recent feed
 18.10.2018 20:02
18.10.2018_20:02 Except on get media!!
18.10.2018_20:02 ======> Get media id by Tag <======
18.10.2018_20:02 Get media by user success!
==============================
Upss hajka is already in ex user list...
==============================

**Comment by kostasosfp** [comment]
so with the change you sent me all other than follow are fixed? Because i need instabot only for likes and comments, so if with the change in syntax that you wrote is likes and comments ok , its fine for me. i write 0 follow and 0 unfollow and no problem
