### ISSUE TITLE
How to set only to unfollow account that bot followed?

### ISSUE THREAD

**Issue by skigo** [instabot-py/instabot.py#1674]
Which mode should i use to unfollow only accounts that bot followed?

**Comment by flite3** [comment]
I think that might be mode 5, but that does it in a way that could get you banned.

If you want to mass unfollow from the script db, just set the unfollow number to a higher number than your follow number.  Maybe double it.  It will start to unfollow more and more people. It will take some time to go through a high number, but it will do it in a safe way.  Just my 2¢.
