### ISSUE TITLE
Login error! Connection error!

### ISSUE THREAD

**Issue by volkovsurf** [instabot-py/instabot.py#1675]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue

python example.py start issue
```
Login error! Connection error!
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['kellyslater'])
  File "/Users/volkovsurf/Desktop/instabot.py-master/src/instabot.py", line 235, in __init__
    self.populate_user_blacklist()
  File "/Users/volkovsurf/Desktop/instabot.py-master/src/instabot.py", line 245, in populate_user_blacklist
    from json import JSONDecodeError
ImportError: cannot import name JSONDecodeError
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by volkovsurf** [comment]
please help someone

**Comment by Daimonion1980** [comment]
Can you provide your example.py (of course without login data)

**Comment by volkovsurf** [comment]
I just fixed that but getting #1637 now, idk maybe you can help me with that

**Comment by LopesX** [comment]
@volkovsurf Can you provide your example.py (of course without login data) your is different #1637

**Comment by joaocpereiraa** [comment]
I got this error. Anyone can help?

28.10.2018_20:06 Login error! Connection error!
28.10.2018_20:06 Removing already liked medias..
28.10.2018_20:06 Removing already liked medias..

**Comment by alex-s435** [comment]
@joaocpereiraa I have the same oder like you have!!!!
Can someone fix??? thanks

**Comment by joaocpereiraa** [comment]
Anybody? xb
