### ISSUE TITLE
logging problem 

### ISSUE THREAD

**Issue by anonyboy** [instabot-py/instabot.py#1677]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [x] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

18.10.2018_00:41 Trying to login as a*******...

Traceback (most recent call last):
File "example.py", line 52, in 
unfollow_whitelist=['example_user_1', 'example_user_2'])
File "C:\Users\x\Desktop\instabot.py-master\src\instabot.py", line 234,
in init
self.login()
File "C:\Users\x\Desktop\instabot.py-master\src\instabot.py", line 303,
in login
self.user_id = ui.get_user_id_by_login(self.user_login)
File "C:\Users\x\Desktop\instabot.py-master\src\userinfo.py", line 41, i
n get_user_id_by_login
all_data = json.loads(info.text)
File "C:\Users\x\AppData\Local\Programs\Python\Python37-32\lib\json_in
it_.py", line 348, in loads
return _default_decoder.decode(s)
File "C:\Users\x\AppData\Local\Programs\Python\Python37-32\lib\json\deco
der.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users\x\AppData\Local\Programs\Python\Python37-32\lib\json\deco
der.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by Apao123** [comment]
yeah I also have the same problem. poorly, instagram detected my log in from my google cloud service ;(

**Comment by juanrojasm** [comment]
I also have the same problem

**Comment by YurieCo** [comment]
Solved my problem followed code
```

import instabot

bot = instabot.Bot("login", "password")
```

**Comment by juanrojasm** [comment]
> Solved my problem followed code
> 
> ```
> 
> import instabot
> 
> bot = instabot.Bot("login", "password")
> ```

Where?

**Comment by YurieCo** [comment]
@juanrojasm 
another way is folllow 
1. turn on the brain in case u forgot it 
`instagram_bot.login(username='***', password='*********')`
