### ISSUE TITLE
Error to connect account 

### ISSUE THREAD

**Issue by handrex95** [instabot-py/instabot.py#1685]
Hi, I installed the python, after i try to connect  there show this error

Traceback (most recent call last):
  File "examplee.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/src/instabot.py", line 232, in __init__
    self.login()
  File "/src/instabot.py", line 301, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/src/userinfo.py", line 39, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'
root@srv58772:/#

![inst](https://user-images.githubusercontent.com/44442131/47444412-b37af680-d7b6-11e8-9447-c551fb263d6a.png)

**Comment by yleyvag** [comment]
I have the same problem

**Comment by hhamza1** [comment]
Same here :hand:

**Comment by Hemil96** [comment]
works for me #1589

**Comment by handrex95** [comment]
ok perfect, works forme this #1589
