### ISSUE TITLE
Except on get_media (unfollow problem)

### ISSUE THREAD

**Issue by Abdox3** [instabot-py/instabot.py#1688]
I am having a problem with every mode (except for mode 0) where I get "except on get_media" whenever it tries to unfollow.
In mode 0 it tries to unfollow but it doesn't, yet it keeps working without problems.

**Comment by Nickrmking23** [comment]
I also have a similar problem (except on get user_info) looping in every mode except the original mode :/

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
