### ISSUE TITLE
Again a fake useragent error but no current solution could help 

### ISSUE THREAD

**Issue by Nickrmking23** [instabot-py/instabot.py#1694]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x ] Linux
- [ ] Android

## Python Version?
- [ x] 2.x
- [x ] 3.x

## Description of your issue

Get Error message:

Traceback (most recent call last):
  File "/home/pi/instagramBot/instabot.py/example.py", line 6, in <module>
    from src import InstaBot
  File "/home/pi/instagramBot/instabot.py/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/pi/instagramBot/instabot.py/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ImportError: No module named 'fake_useragent'

## Config
I tried: 
pip install requirements
pip install fake-useragent

No one could answer this in other threads with the solution I need 
Thanks for your help!^^

I use the Raspberrypi 3 via remote desktop

**Comment by Stefamen23** [comment]
Pip install -r requirements
