### ISSUE TITLE
Except on get_info!

### ISSUE THREAD

**Issue by Nickrmking23** [instabot-py/instabot.py#1699]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [x] 3.x

## Description of your issue

```
After logging in this happens and this error keeps looping 👎 


Checking user info..
Except on get_info!
[User] : Get user info
```

## Config

```
The default config is working fine in mode 0 so i don´t think that the config has to do something with this only modes 1-5 don´t work fine
```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
