### ISSUE TITLE
Traceback....

### ISSUE THREAD

**Issue by ricocaine** [instabot-py/instabot.py#1700]
Hello guys,
so when I run : **python example.py**
this is what I have... 

**Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/XXX/Documents/virtualenvs/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/XXX/Documents/virtualenvs/instabot.py-master/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'**

Then I did this command **pip install fake_useragent** 

and I obtained this: **fake_useragent in /Library/Python/2.7/site-packages (0.1.11)**

But when I retry to launch the file example.py I re-have the same problem
Any ideas fro helping me ?
Thank you very much
R

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
