### ISSUE TITLE
traceback

### ISSUE THREAD

**Issue by pitopo** [instabot-py/instabot.py#1718]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [ x] 3.x

## Description of your issue

Traceback (most recent call last):
  File "example.py", line 47, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/home/pi/Desktop/instabot.py-master/src/instabot.py", line 234, in __init__
    self.login()
  File "/home/pi/Desktop/instabot.py-master/src/instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/home/pi/Desktop/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by pitopo** [comment]
Hello, I'm trying to run instabot on a raspberry pi 3b+ but when trying to login that's what I get in response. What shall I do?

**Comment by ofekch** [comment]
i have the same problem too...

**Comment by renatojen** [comment]
Solved by changing line 42 of userinfo.py to:

`json_info = json.loads(re.search('window._sharedData = (.*?);</script>', info.text, re.DOTALL).group(1))`
