### ISSUE TITLE
Json error Line 42 of userinfo.py

### ISSUE THREAD

**Issue by eliottf** [instabot-py/instabot.py#1725]
Hi guys,

I still have the problem about the line 42 "AttributeError: 'NoneType' object has no attribute 'group' " in userinfo.py, i already changed the line with this "json_info = json.loads(re.search('{"activity.+gatekeepers', info.text, re.DOTALL).group(0)+'":""}')" and it was working perfectly yesterday but today the error is back on tracks, do you have any idea if instagram changed their json structure again ? Is it working for you ?

Eliott

**Comment by w3x10e8** [comment]
Hey Im getting the same here, most probably instagram did some changes

**Comment by renatojen** [comment]
Solved here:
https://github.com/instabot-py/instabot.py/issues/1718#issuecomment-437235593

#1722

**Comment by ryanbrewster124** [comment]
wow this worked! So i downloaded a fresh copy of the instabot and did the fix renatjen posted and it kicked through first time.

**Comment by eliottf** [comment]
It worked ! Thanks Renato 👍

**Comment by b4ckbre4ker** [comment]
line 42 src/userinfo.py
        json_info = json.loads(re.search('window._sharedData = (.*?);</script>', info.text, re.DOTALL).group(1))

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/pull/1732
