### ISSUE TITLE
Proxy problem

### ISSUE THREAD

**Issue by Martypary** [instabot-py/instabot.py#1734]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
Dear instabot users, 
I am on window's 10, VSC 1.26.1 and Python 3.6.5

I have a strange problem. With the json_info fix from @daniellovell, everything seemed to work. My bot worked without a proxy, but when I entered my proxies correctly, he did not

What was even more odd was when I removed the proxy again he did not do it anymore. Sometimes VSC presents a problem in instabot.py (photo attached)

I use proxies from proxy6.net and they have always worked. I do not know what the problem is.

I hope someone could help me.

kind regards,
Martijn
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```
![foto vsc](https://user-images.githubusercontent.com/39266285/48317839-6ee5bc80-e5f8-11e8-86a6-9bb161b6ddc9.jpg)

**Comment by theinfinityproject** [comment]
OT: Idk if u want ur ig name exposed here. If not i recommend to edit the attached screenshot (top left corner)
