### ISSUE TITLE
Not Allowing me to login

### ISSUE THREAD

**Issue by lanceboyer** [instabot-py/instabot.py#1735]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [m ] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
When attempting to login i am faced with this error:
```
Traceback (most recent call last):
  File "/Users/lanceboyer/Desktop/instabot.py-master/example.py", line 51, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/lanceboyer/Desktop/instabot.py-master/src/instabot.py", line 234, in __init__
    self.login()
  File "/Users/lanceboyer/Desktop/instabot.py-master/src/instabot.py", line 303, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/lanceboyer/Desktop/instabot.py-master/src/userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+gatekeepers', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by BurningNacho** [comment]
Same, changing line 42 +gatekeepers to +probably_has_app as suggested in #1529 reports same error

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/pull/1732
