### ISSUE TITLE
Suspicious Login Attempt - Login error! Connection Error

### ISSUE THREAD

**Issue by itsmejamie** [instabot-py/instabot.py#1739]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
- [X] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [X] 2.7.13
- [ ] 3.x

## Description of your issue

Have downloaded the most recent version of instabot and it was working well for a day. But now when I run it I get a log in error and the IG app asks if it was me logging in. 

14.11.2018_08:40 Instabot v1.2.0 started at 14.11.2018 08:40:

14.11.2018_08:40 Trying to login as XXXX

14.11.2018_08:40 Login error! Connection error!
14.11.2018_08:40 Removing already liked medias..
14.11.2018_08:40 Trying to unfollow #1: 
14.11.2018_08:40 Removing already liked medias..
14.11.2018_08:40 Removing already liked medias..
14.11.2018_08:40 Removing already liked medias..
14.11.2018_08:40 Removing already liked medias..
14.11.2018_08:40 Removing already liked medias..
14.11.2018_08:40 Removing already liked medias..
14.11.2018_08:40 Removing already liked medias..
14.11.2018_08:41 Removing already liked medias..
14.11.2018_08:41 Trying to unfollow #1: 
14.11.2018_08:41 Removing already liked medias..
14.11.2018_08:41 Removing already liked medias..
14.11.2018_08:41 Removing already liked medias..
14.11.2018_08:41 Removing already liked medias..
14.11.2018_08:41 Removing already liked medias..
14.11.2018_08:41 Removing already liked medias..
14.11.2018_08:41 Removing already liked medias..
14.11.2018_08:41 Trying to unfollow #1: 
14.11.2018_08:41 Removing already liked medias..
14.11.2018_08:41 Removing already liked medias..
14.11.2018_08:41 Removing already liked medias..

```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by ugurozturk** [comment]
![image](https://user-images.githubusercontent.com/7994408/48471392-dec89280-e804-11e8-9cf2-ac08c7ca4bfa.png)
