### ISSUE TITLE
Login Error! Connection Error! again

### ISSUE THREAD

**Issue by magnumtank** [instabot-py/instabot.py#1751]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [ ] 3.x

## Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by neiram44** [comment]
Same for me here. Last time I had been able to just modify a part of the code.
This morning after a clean start here is the output...

`20.11.2018_09:15 Login error! Connection error!
20.11.2018_09:15 Removing already liked medias..
20.11.2018_09:15 Removing already liked medias..
20.11.2018_09:15 Removing already liked medias..
20.11.2018_09:15 Removing already liked medias..
20.11.2018_09:15 Removing already liked medias..
20.11.2018_09:15 Removing already liked medias..
20.11.2018_09:15 Removing already liked medias..
20.11.2018_09:15 Removing already liked medias..
20.11.2018_09:15 Removing already liked medias..
20.11.2018_09:15 Removing already liked medias..
20.11.2018_09:15 Removing already liked medias..
20.11.2018_09:15 Removing already liked medias..
20.11.2018_09:15 Removing already liked medias..
20.11.2018_09:15 Removing already liked medias..
20.11.2018_09:15 Removing already liked medias..
20.11.2018_09:15 Removing already liked medias..
20.11.2018_09:16 Removing already liked medias..
20.11.2018_09:16 Removing already liked medias..
20.11.2018_09:16 Removing already liked medias..
20.11.2018_09:16 Removing already liked medias..
20.11.2018_09:16 Removing already liked medias..
20.11.2018_09:16 Removing already liked medias..`

**Comment by keshamin** [comment]
I face this as well. 
What's weird, I caught this issue with my second account. For my first account I already have the bot working (on another server) and it works fine, without any errors.
Tried to change a password of the account to log out from all devices, but that didn't help.
Also tried to run the bot locally and the issue stays the same! Crazy.

**Comment by Mehranp** [comment]
same , plz help me

**Comment by bendaniels052** [comment]
It's because Instagram doesn't not recognise the login location/device, so it blocks the login attempt from that IP. Is there away we can disable this Instagram side?

**Comment by Alexyoe** [comment]
Have you made sure you disabled Two-Step Authentication on instagram?

**Comment by AZAH197** [comment]
Yes it is disabled.

**Comment by suvrodeepta** [comment]
Login error! Connection error!

Same problem here

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
