### ISSUE TITLE
Unfollow not work

### ISSUE THREAD

**Issue by Massimosso** [instabot-py/instabot.py#1753]
So, I've 307 follow, this is the problem:
...
Try to unfollow: #3
Unfollowed: #3
Try to unfollow: #4
Unfollowed: #4
Try to unfollow: #5
Unfollowed: #5
...

and up to this point it's ok, it works. But when I go on my instagram profile my follow is always at the same number (307). Why?

**Comment by Brcalvo** [comment]
I have the same issue. In mode 0 my followers just keep growing!

**Comment by jinnishdalal** [comment]
The unfollow seems not to be working

**Comment by Brcalvo** [comment]
Check the latest version of the code, it´s now fixed. My unfollows are working again.

**Comment by iLeGiTiMx** [comment]
Hello, I have the same problem (kinda).
For me, I don´t get errors. It just writes "Trying to unfollow #1" sometimes, when it should unfollow someone.
The problem: It´s always #1 and it doesn´t unfollow users..

Fixes out there? 
Thank you :)

**Comment by Brcalvo** [comment]
Did you download the latest version of the code? It´s now working.

**Comment by Brcalvo** [comment]
Main code section:
https://github.com/instabot-py/instabot.py

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
