### ISSUE TITLE
Warn About Data Collection in README.MD

### ISSUE THREAD

**Issue by Robert-Wett** [instabot-py/instabot.py#1755]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [x] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

I think it would be responsible to declare on the README.MD that all information is going through https://ink361.com/ and being logged for data collection purposes. I'm not sure if ink361 is your company or just a company that provides the service - either way I think it should be made clear in the README.MD for people thinking about using this.

## Config

N/A

**Comment by theinfinityproject** [comment]
Could u point to the file, so i can remove that 'feature'?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
