### ISSUE TITLE
Possible new mode for instabot.py

### ISSUE THREAD

**Issue by teeeclip** [instabot-py/instabot.py#1756]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

 
```

```

## Config

Hi, 
I'd like to thank you all for this awesome work.

After using it for a while and trying to get behind the code i was thinking about "rebuilding" it as a 'light' version with just the function of liking posts.
since the target audience for your profiles mostly never use the hashtags on their own posts, u'll never reach them.

So what I'm thinking is:  to collect _relevant_ profiles of competitors in your branch. Bigger ones as you are. Grab the last post of one of them and collect the people that liked that post.
So you can guarantee that those profiles are active and interested because those are the ones you want to reach out to!

Sadly I just don't have time to do that on my own.
I'd love to see that function as a mode of instabot.py
```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
