### ISSUE TITLE
Traceback error 

### ISSUE THREAD

**Issue by antoniyaaaa** [instabot-py/instabot.py#1758]
Hello, I have this issue. I tried changing line 42 of the userinfo file and nothing changes. Please help :( 
Traceback (most recent call last):
  File "c:/instabot.py-fix-login_error/example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "c:\instabot.py-fix-login_error\src\instabot.py", line 234, in __init__
    self.login()
  File "c:\instabot.py-fix-login_error\src\instabot.py", line 302, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "c:\instabot.py-fix-login_error\src\userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity_counts.+probably_has_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'
PS C:\Users\ASUS>

**Comment by JULIANCRACK** [comment]
Same here !! 

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/julienjung/Desktop/instabot-3.py-master/src/instabot.py", line 236, in __init__
    self.login()
  File "/Users/julianXXXX/Desktop/instabot-3.py-master/src/instabot.py", line 287, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Python/2.7/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
MacBook-Pro-de-Julian:instabot-3.py-master julianXXXX$

**Comment by visionsofparadise** [comment]
getting the same error

**Comment by iraizo** [comment]
same

**Comment by walik-walik** [comment]
same

**Comment by bennibenny** [comment]
same error

**Comment by BurningNacho** [comment]
go to #1377 (comment)

**Comment by alcorac74** [comment]
Hello,
I have similar problem and no solution.. someone to help me?

This is my code on Android devise 

   #!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="n.coo_",
    password="IPirate29Nico",
    like_per_day=900,
    comments_per_day=0,
    tag_list=['follow4follow', 'blackandwhite', 'street', 'photo', 'city', 'nature', 'forest', 'urban', 'landscape', 'art', 'forest', 'mushroom', 'flowers', 'paysage', 'lumiere', 'portrait', 'belgium', 'cities', 'botanique', 'nude', 'photographe', 'style', 'architecture', 'pattern', 'animals', 'dog', 'rivers', 'wood', 'fox', 'clouds', 'rain', 'storm'],
    tag_blacklist=['hunt', 'luxury', 'weapon', 'politic'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=60,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['francoiscoorens', 'juliettedebxl'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

**Comment by Tankr3d** [comment]
You should not send your example file here purely because your password and username is included!

**Comment by alcorac74** [comment]
Yes my account has hacked..  Forget erase my password. ^^

**Comment by BurningNacho** [comment]
You should change your password

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: alcorac74 <notifications@github.com>
Enviado: Sunday, December 2, 2018 9:10:05 PM
Para: instabot-py/instabot.py
Cc: BurningNacho; Comment
Asunto: Re: [instabot-py/instabot.py] Traceback error (#1758)


Yes my account has hacked.. Forget erase my password. ^^

**Comment by JULIANCRACK** [comment]
> go to #1377 (comment)

i did but it still doesn't work ...

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
