### ISSUE TITLE
Skip already liked posts

### ISSUE THREAD

**Issue by ortschun** [instabot-py/instabot.py#176]
Would be good to be able to skip liking the posts that are already liked.

**Comment by polaroi8d** [comment]
Hey @ortschun do you think about this? #167 its working...

**Comment by ortschun** [comment]
#167 is skipping our own media, but we should be able to skip the posts that we liked, it's different

**Comment by nekfeu** [comment]
@ortschun yes we must add it

**Comment by polaroi8d** [comment]
Sorry, I am misunderstand.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
