### ISSUE TITLE
I am using this json to get following list is it possible to get email too?

### ISSUE THREAD

**Issue by alyysaafan** [instabot-py/instabot.py#1760]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ no] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [ x] Linux
- [ ] Android

## Python Version?
- [x ] 2.x
- [ ] 3.x

Can i get business_email from json using this code?

 API.getUsernameInfo(user_id)
    API.LastJson
    following = []
    next_max_id = True
    while next_max_id:
        print next_max_id
        # first iteration hack
        if next_max_id is True:
            next_max_id = ''
        _ = API.getUserFollowings(user_id, maxid=next_max_id)
        following.extend(API.LastJson.get('users', []))
        next_max_id = API.LastJson.get('next_max_id', '')

    len(following)
    unique_following = {
        f['username']: f
        for f in following

    }
    len(unique_following)

instead of getting following list usernames i want to get emails but i can't

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
