### ISSUE TITLE
Instabot follow function not working

### ISSUE THREAD

**Issue by Yosoycoder** [instabot-py/instabot.py#1761]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [ ] 3.x

## Description of your issue

Hi everyone! This week I started using the latest version of Instabot, and I am having problems trying to follow new users. 

The bot like function works properly, but when it tries to follow a new user it appears the message "Trying to follow user xxxxxxxx", and then it does not get to follow the user (there is no "followed" message as it should be and I have checked that there are no new follows) and it jumps to the next action. The result is that the bot does like posts, but everytime it tries to follow a user, it fails (it does not stop working, it just tries to do it and then it goes to the next action). 

I have not changed anything at all in the original code other than the username, password and hashtags, and I have searched for every issue published, but I do not find anything about this problem. I am suspecting this is a new issue related with recent changes in the Instagram API or something like that. 

Is anyone getting the same problem?

Thanks!

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by wakiprats** [comment]
Any fix to this? Im getting the same issue

**Comment by yahgiggle** [comment]
same problem, but i think IG has blocked the follow as at first it was too aggressive, i slowed mine right down and hope in 72 hours they lift the ban

**Comment by LeSKUNK** [comment]
> same issue here
> the bot just stopped following/unfollowing people today
> just says 'trying to follow' / 'trying to unfollow' and doesn't do anything after that
> the likes work tho



> Any fix to this? Im getting the same issue

Did you guys solve this? Mine is still the same... Not following and no one here on github replies to my questions.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
