### ISSUE TITLE
CSRF Token Error since the new IG update

### ISSUE THREAD

**Issue by clickandwatch** [instabot-py/instabot.py#1764]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ x] If so; have you tried running the code on your local machine?

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [ x] 3.x

## Description of your issue
Error when login, it seems to be related to the new IG update. Everything was running well and I needed to change my tag list, I restarted my bots, can't login
```
30.11.2018_15:15 Trying to login as _stonecat...

Traceback (most recent call last):
  File "C:\Users\alban\Desktop\Instabot\pics_streetphoto_bnw.py", line 55, in <module>
    unfollow_whitelist=[])
  File "C:\Users\alban\Desktop\Instabot\src\instabot.py", line 236, in __init__
    self.login()
  File "C:\Users\alban\Desktop\Instabot\src\instabot.py", line 287, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\alban\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\alban\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"


## Config
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="_stonecat",
    password="**********",
    like_per_day=697,
    comments_per_day=0,
    tag_list=['lensible', 
	'photoobserve', 'blackandwhite','bnwdark', 'noiretblanc', 'noiretblancphotographie', 'photoderue', 'photographiederue',
	'fineartphg','landscapephotography'],
    tag_blacklist=['f4f','like','follow'],
    user_blacklist={},
    max_like_for_one_tag=150,
    follow_per_day=000,
    follow_time=0* 60,
    unfollow_per_day=0,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "your", "the atmosphere in this", "the atmosphere in your",
	               "the framing in this", "the composition in your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "looks so", "is really", "is so", "is very"],
                  ["great", "super", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "cool", "stylish", "beautiful",
                   "professional", "lovely",
                   "glorious",
                   "excellent", "amazing"],
                  [".", "...", "!", "!!", "!!!", ":)", "o_O", "*_*"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'food', 'blog',
        'free', 'keren', 'indo', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=[])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

**Comment by manguszta** [comment]
Same here....

![kepkivagas](https://user-images.githubusercontent.com/18244325/49296585-fff1da00-f4b8-11e8-84b5-b9f169b517b5.PNG)

**Comment by LadikCZ** [comment]
Same here.

**Comment by Trantor92** [comment]
Same here, please help

**Comment by bvttle** [comment]
same issue here!

**Comment by clickandwatch** [comment]
I tried with a vpn connected outside Europe, I get an other error, the bot is looping on "removing already liked media".

**Comment by babakyfar** [comment]
I have same issue here, anyone could help?

**Comment by Alexyoe** [comment]
I'm connecting with no issues. I'm running version 1.2.0 on python 2.7.1 from a Mac.

**Comment by spud-dog** [comment]
😒 getting the same issue today if anyone has a fix for this I'd be eternally grateful.

Running Python 3.6.5
Instabot v1.2.0

**Comment by monanabanana** [comment]
same here! :(

**Comment by iLeGiTiMx** [comment]
Same..

**Comment by duart38** [comment]
@Alexyoe  what version of the 'requests' package are you running?

**Comment by duart38** [comment]
this fixed the issue for me
https://github.com/instabot-py/instabot.py/issues/1377#issuecomment-401545692

the line is not current so ctrl-f and find the line and replace it with the comment..

for the lazy peeps like me (i copied and pasted)

Replace line 283
self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})

with this:
csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0)
self.s.headers.update({'X-CSRFToken': csrf_token})

and use mode = 0

**Comment by babakyfar** [comment]
thank you, but got log in error, connection error

**Comment by gemoritzt** [comment]
Same error here under Mac OS.

**Comment by Alexyoe** [comment]
@duart38 I'm not sure where I find that. 😳

**Comment by clickandwatch** [comment]
Also worked for me thanks !

**Comment by deanainsworth** [comment]
> this fixed the issue for me
> [#1377 (comment)](https://github.com/instabot-py/instabot.py/issues/1377#issuecomment-401545692)
> 
> The modification should be done in the instabot.py (inside the src folder)
> 
> the line is not current so ctrl-f and find the line and replace it with the comment..
> 
> for the lazy peeps like me (i copied and pasted)
> 
> Replace line 283
> self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
> 
> with this:
> csrf_token = re.search('(?<="csrf_token":")\w+', r.text).group(0)
> self.s.headers.update({'X-CSRFToken': csrf_token})
> 
> and use mode = 0

This worked for me too, cheers.

**Comment by rugge89lau** [comment]
> this fixed the issue for me
> [#1377 (comment)](https://github.com/instabot-py/instabot.py/issues/1377#issuecomment-401545692)
> 
> The modification should be done in the instabot.py (inside the src folder)
> 
> the line is not current so ctrl-f and find the line and replace it with the comment..
> 
> for the lazy peeps like me (i copied and pasted)
> 
> Replace line 283
> self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
> 
> with this:
> csrf_token = re.search('(?<="csrf_token":")\w+', r.text).group(0)
> self.s.headers.update({'X-CSRFToken': csrf_token})
> 
> and use mode = 0


use mode = 0 where? on log_mod? :(

**Comment by duart38** [comment]
> > this fixed the issue for me
> > [#1377 (comment)](https://github.com/instabot-py/instabot.py/issues/1377#issuecomment-401545692)
> > The modification should be done in the instabot.py (inside the src folder)
> > the line is not current so ctrl-f and find the line and replace it with the comment..
> > for the lazy peeps like me (i copied and pasted)
> > Replace line 283
> > self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
> > with this:
> > csrf_token = re.search('(?<="csrf_token":")\w+', r.text).group(0)
> > self.s.headers.update({'X-CSRFToken': csrf_token})
> > and use mode = 0
> 
> use mode = 0 where? on example.py? :(

@rugge89lau 

if you look in the example file inside this repo you'll find the following lines
```python
     # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0  # <<<<<<<<  this is the mode

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)
```

or if you are coding this on your own mode 0 is the following
```python
bot.new_auto_mod()
```
