### ISSUE TITLE
How to save the consoles output to a file?

### ISSUE THREAD

**Issue by iLeGiTiMx** [instabot-py/instabot.py#1765]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ X] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [X ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ X] 2.x
- [ ] 3.x

## Description of your issue

Hello. How can I let the console write its output to a file? Maybe an INI file with "Likes,Followed,Unfollowed". I just want to have a file with the current bot values so I don´t need to look into the console :)
Thank you

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
