### ISSUE TITLE
Login error! Connection error!

### ISSUE THREAD

**Issue by mactrash** [instabot-py/instabot.py#1770]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
Login error! Connection error!
```

## Config

The config have run from couple months

**Comment by iLeGiTiMx** [comment]
Same here. I also am stuck in the "We have detected a suspicious login attempt" loop

**Comment by acollamat** [comment]
Same thing. Waiting for a nice guy to fix this problem.

**Comment by chemidlin** [comment]
I reset my password and it seemed to fix the issue. I reset it, waited about 5 hrs, then tried to log back in. Good as new on my end

**Comment by mactrash** [comment]
reset password no fix the problem, and done and test!

**Comment by acollamat** [comment]
There is some changes with Instagram login I think. Downloaded a new one yesterday, install the pip requirements and it works. But this morning stops working.

**Comment by mactrash** [comment]
> There is some changes with Instagram login I think. Downloaded a new one yesterday, install the pip requirements and it works. But this morning stops working.

Just test the new one... not work

**Comment by mactrash** [comment]
Why other ppl don't have such issue?

**Comment by pierrechn** [comment]
I click 'that wasn't me' , reset my password, and it worked just fine.

**Comment by mactrash** [comment]
fix as https://github.com/instabot-py/instabot.py/pull/1788
