### ISSUE TITLE
What is fake_useragent

### ISSUE THREAD

**Issue by ChaseEmeryDavis** [instabot-py/instabot.py#1772]
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src.instabot import InstaBot
  File "/Users/*********/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/*********/Desktop/instabot.py-master/src/instabot.py", line 22, in <module>
    from .fake_useragent import UserAgent
ImportError: No module named fake_useragent

there is no fake_useragent, so what do they mean?

**Comment by ChaseEmeryDavis** [comment]
Yes that's right, I hadn't noticed this came up:

Installing collected packages: fake-useragent
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/fake_useragent'
Consider using the `--user` option or check the permissions.

How do I fix it?

**Comment by Alexyoe** [comment]
Did you try installing with --user? `Example: pip install -r requirements.txt --user`

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
