### ISSUE TITLE
X-CSRFToken Error

### ISSUE THREAD

**Issue by skigo** [instabot-py/instabot.py#1773]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ x] 2.x
- [ ] 3.x

## Description of your issue
I changed the following but still nothing:
- self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
+        csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0)
+        self.s.headers.update({'X-CSRFToken': csrf_token})

Traceback (most recent call last):
  File "/Users/dimitris.skigopoulos/Desktop/instabot.py-master/example.py", line 39, in <module>
    [".", "..", "...", "!", "!!", "!!!"]],
  File "/Users/dimitris.skigopoulos/Desktop/instabot.py-master/src/instabot.py", line 236, in __init__
    self.login()
  File "/Users/dimitris.skigopoulos/Desktop/instabot.py-master/src/instabot.py", line 292, in login
    self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

Its the default

**Comment by Conikalpha** [comment]
same here

**Comment by instabotter** [comment]
happens to me whenever i need phone verification
try logging in on a browser/phone and check if that's the case

**Comment by ryanbrewster124** [comment]
> happens to me whenever i need phone verification
> try logging in on a browser/phone and check if that's the case

that was the case at the start but after changing my password the phone verification stopped and it was fine but i still got the csrftoken problem..

this is what I'm getting:

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/narayanbrewer/Desktop/instabot.py-master/src/instabot.py", line 236, in __init__
    self.login()
  File "/Users/narayanbrewer/Desktop/instabot.py-master/src/instabot.py", line 287, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
narayans-imac:instabot.py-master narayanbrewer$

**Comment by gbikas16** [comment]
same here

**Comment by gincarbone** [comment]
same here. Nobody have a solution?

**Comment by ryanbrewster124** [comment]
still no fix? I'm in Barcelona now and hoped it would work. Still have the same issue

**Comment by ryanbrewster124** [comment]
Ok guys it works!!!

Here is what I did. I deleted my instabot.py master folder. Then I downloaded another version of that folder which you can find here at the top of the thread it's a zip ( https://github.com/instabot-py/instabot.py/pull/1788).

After downloading it I ran this command  (pip install -r requirements.txt)
And it ended up installing ( instaloader-4.1.1)

Then i just ran the script and prayed and it kicked through and started working.

Best of luck guys.

**Comment by heldausberlin** [comment]
@ryanbrewster124 I tried to do this. But now I get: `No module named 'fake_useragent'`
`pip install -U fake-useragent` doesn’t work. Any ideas?

**Comment by ryanbrewster124** [comment]
> @ryanbrewster124 I tried to do this. But now I get: `No module named 'fake_useragent'`
> `pip install -U fake-useragent` doesn’t work. Any ideas?

Ok I have run into this problem before and (pip install -U fake-useragent) did'nt work there was another command and it was something like this (pip install -U fake-useragent upgrade)  I can't remember the exact command but it was something along those lines, just google 'fake user agent instabot' and read through all the posts, your answer is there somewhere as thats how i fixed it. sorry i cant be anymore help, best of luck

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
