### ISSUE TITLE
Can't download fake_useragent from Requirements.txt

### ISSUE THREAD

**Issue by ChaseEmeryDavis** [instabot-py/instabot.py#1774]
Just realised that this did not download properly:

Installing collected packages: fake-useragent
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/fake_useragent'
Consider using the --user option or check the permissions.

How can I fix it so that it downloads?

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
