### ISSUE TITLE
I got this error Traceback (most recent call last):   File "example.py", line 52, in <module>     unfollow_whitelist=['blackops4.fans', 'blackops4intel']) TypeError: __init__() got an unexpected keyword argument 'login'

### ISSUE THREAD

**Issue by fixedblur** [instabot-py/instabot.py#1780]
I get this issue any helpfull fixes?

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['blackops4.fans', 'blackops4intel'])
TypeError: __init__() got an unexpected keyword argument 'login'

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
