### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by b4ckbre4ker** [instabot-py/instabot.py#1782]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ x] If so; have you tried running the code on your local machine?

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x ] 3.x

## Description of your issue

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/jeffglasser/Desktop/synergy/instabot.py-master/src/instabot.py", line 234, in __init__
    self.login()
  File "/Users/jeffglasser/Desktop/synergy/instabot.py-master/src/instabot.py", line 304, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/jeffglasser/Desktop/synergy/instabot.py-master/src/userinfo.py", line 41, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+probably_has_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
