### ISSUE TITLE
looks like there is nobody to unfollow

### ISSUE THREAD

**Issue by marcosenno88** [instabot-py/instabot.py#1796]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (#1422 #1015 #1127)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x ] Windows 7
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x ] 3.x

## Description of your issue
Yesterday: 
-fixed all with #1775
-start the bot doesn't works..
-on the app said suspicious access
-"selected this was me"

today: the bot login but

the unfollow doesent works
![cattura](https://user-images.githubusercontent.com/37532558/49795956-a9e42880-fd3b-11e8-8be2-d3f37915f4c3.JPG)

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by cristianvia** [comment]
Same here with the exception that in the app it doesn't suspects a suspicious access. Any idea? Fixed all with #1775 too

**Comment by Nuggedo** [comment]
I have the same problem. but in my opinion it is still unfollowing one user, but in the end, bot doesnt unfollow him :/

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
