### ISSUE TITLE
Traceback issue when logging in

### ISSUE THREAD

**Issue by Therichiefleming** [instabot-py/instabot.py#1797]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
- [x ] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x ] 3.x

## Description of your issue
Keep getting traceback error when trying to log in, tried replacing line 287 in code to:
 
#self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
        csrf_token = re.search('(?<=\"csrf_token\":\")\w+',  r.text).group(0)
        self.s.headers.update({'X-CSRFToken': csrf_token})
        time.sleep(5 * random.random())

```
Traceback (most recent call last):
  File "/Users/Richiemane/Desktop/Business/JDMBOIS Bot/example.py", line 48, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/Richiemane/Desktop/Business/JDMBOIS Bot/src/instabot.py", line 232, in __init__
    self.login()
  File "/Users/Richiemane/Desktop/Business/JDMBOIS Bot/src/instabot.py", line 304, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/Richiemane/Desktop/Business/JDMBOIS Bot/src/userinfo.py", line 42, in get_user_id_by_login
    json_info = json.loads(re.search('{"activity.+show_app', info.text, re.DOTALL).group(0)+'":""}')
AttributeError: 'NoneType' object has no attribute 'group'
```

## Config

```
N/a
```

**Comment by cicciokof** [comment]
Same since 2 days ago, tried the #1788 but isn't working.

**Comment by alaintainguyen** [comment]
Same , impossible to fix it

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
