### ISSUE TITLE
Like and follow 404

### ISSUE THREAD

**Issue by lacari3ff** [instabot-py/instabot.py#1798]
Default config with everything else set to default. It follows and likes a few times but then it constantly tries and gives 404 error.
![screenshot_3](https://user-images.githubusercontent.com/42448960/49823698-99a26c80-fd80-11e8-91e5-8adfbf5037f9.png)

**Comment by lacari3ff** [comment]
This continues infinite btw

**Comment by waynoedm** [comment]
That's a 404 error.

**Comment by waynoedm** [comment]
That's a 403 error.

**Comment by dimisdas** [comment]
Could you give this pull request a try and report back please? Thanks!

https://github.com/instabot-py/instabot.py/pull/1788

**Comment by reliefs** [comment]
Here is a working fix
https://github.com/reliefs/instagrambot

**Comment by Orezhon** [comment]
![cattura](https://user-images.githubusercontent.com/1127823/49900949-4a336d80-fe60-11e8-8d8e-dc96fd102e3a.JPG)

how can I fix?

**Comment by budstankz** [comment]
how can we fix this?

**Comment by dimisdas** [comment]
it's already fixed in the latest pull request

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
