### ISSUE TITLE
Login error! Connection error!

### ISSUE THREAD

**Issue by guido-n** [instabot-py/instabot.py#1799]
I get a 400 response when login, including the infamous _checkpoint_rquired_

I applied #1788 and followed many of the proposed solutions

- tried "this wasn't me" and changed the password
- tried to deactivate my account, waited 6 hours, re-logged in
- tried to go forward with the challenge on my web browser, and got through it successfully
- tried to logout from all previous sessions, cleared all cookies

but no luck. Every time I run instabot, I get the following (redacted)

```
guido@guido-X:~/instabot.py$ python3 example.py 
12.12.2018_01:47 Instabot v1.2.0 started at 12.12.2018 01:47:

12.12.2018_01:47 Trying to login as XXXXXX...

Challenge required at https://instagram.com/challenge/111111111/XXXXXXXXXX/
Login failed, response: 

{"message": "checkpoint_required", "checkpoint_url": "/challenge/11111111/XXXXXXXXX/", "lock": false, "status": "fail"}
```

Now, I read the comment about leaving it be for a day or two and then retrying. However I couldn't help but notice that using the same _user_agent_ that I use with my browser to follow up the challenge, makes the challenge go through. Without it, it just keeps stonefacing me with "susipcious login attempt"

Anyone having the same problem?

**Comment by Kredly** [comment]
i have too this problem)

**Comment by dimisdas** [comment]
Instagram has upped their game and now does some sort of heuteristic assessment during the challenges. Matching the IP and the user agent might help, but while testing it the success rate varies.

I'm trying to write a method for dealing with challenges. It asks for challenge verification (email), asks the user to type the code, submits the code and logins.

Unfortunately, I ironically no longer get challenges and it just lets me login. So ... I can't really reproduce it and finish it.

It would help if someone could capture all requests, cookies, and headers during the challenge. I got halfway through, up until the code submission step.

**Comment by psannino77** [comment]
I have the some problem on 3 of my 4 accounts. Only one is working, I suppose until the next reboot.

**Comment by guido-n** [comment]
@dimisdas thank you for the explanation. I am currently exercising abstinence from _instabot_ as prescribed, I'll update in a day or two on the results.

Although I was thinking, would it be possible to draw up the list of _http headers_ that is needed for the correct functioning of the script, and use a normal browser to go through the login process, collect the raw HTTP messages, and feed the values to the script with some sort of configuration? At least that would give you a consistent way to test it repeatedly .

**Comment by dimisdas** [comment]
@guido-n any tool similar to Charles Proxy will do

https://www.charlesproxy.com

**Comment by guido-n** [comment]
@dimisdas yes thank you. I was actually thinking to simply use Firefox developer tools. However the tricky part is the list of what's needed in each HTTP request subsequent to login, the list of http headers - so to speak.

**Comment by guido-n** [comment]
Hi, unfortunately I have to confirm that after 3 days of inactivity, instabot is still not working - same situation as above. It's a shame : /

**Comment by dimisdas** [comment]
Have you tried the latest export on my pull request with the modified headers?

**Comment by dimisdas** [comment]
Instagram verifies content with hash signatures, and having content length default to zero I’d argue is a *major* issue, way beyond trivial.

Have a look at  the 'x-instagram-gis’ header for example, which contains an MD5 hash of rhx + parameters to validate the request, and is slowly taking the place of CSRFToken.

So if for example you’re sending a message that has a length of 140, but you state in your headers that it’s 0, there’s something seriously wrong with your application.

**Comment by zwave00** [comment]
Same problem right now... Can't get a fix on it

**Comment by guido-n** [comment]
> Instagram verifies content with hash signatures, and having content length default to zero I’d argue is a *major* issue, way beyond trivial. 

I was really hoping that is gets replaced when you set a body on a request by python or whatever is used there. In that sense, that modification didn't make much of a difference.

> Have a look at the 'x-instagram-gis’ header for example, which contains an MD5 hash of rhx + parameters to validate the request, and is slowly taking the place of CSRFToken.

Yep - that's definitely one of the missing headers I noticed. And that's why I was on about a list of all headers and what they meant / how they work etc.
