### ISSUE TITLE
error when starting

### ISSUE THREAD

**Issue by pablo3600** [instabot-py/instabot.py#1800]
error when logging in that someone help me please or if someone works with example.py and share the url that works for you. Thank you

working to python 3.7.1

12.12.2018_01:47 Trying to login as XXXXXX..

Traceback (most recent call last):

  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\Dogi\Downloads\instabot.py-master\src\instabot.py", line 236, in __init__
    self.login()
  File "C:\Users\Dogi\Downloads\instabot.py-master\src\instabot.py", line 287, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\Dogi\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\Dogi\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

thanks

**Comment by bsantos09** [comment]
> Have you tried any of the fixes listed in the pull requests? If yes, which?

yes I tried all of them im using python 3

**Comment by dimisdas** [comment]
Could you be more specific?

**Comment by pablo3600** [comment]
i am remplace the line 287 in instabot.py but follow  other problem.

**Comment by pablo3600** [comment]
if someone works instabot could share the url where I downloaded the file to run with python 3 without errors, since the compressed file that downloaded a week ago does not start and I guess the writing of the lines has changed

**Comment by dimisdas** [comment]
There you go https://github.com/dimisdas/instabot.py/archive/master.zip

**Comment by pablo3600** [comment]
Is this instabot working for you? if so, thank you so much fuck

**Comment by iLeGiTiMx** [comment]
> There you go https://github.com/dimisdas/instabot.py/archive/master.zip

Nope. Still the error on some accounts. Stuck in login authentication loop

**Comment by pablo3600** [comment]
God bless you brother works a lot thank you
