### ISSUE TITLE
 File "example.py", line 6, in <module>     from src import InstaBot

### ISSUE THREAD

**Issue by pablo3600** [instabot-py/instabot.py#1801]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [ x] 3.x

## Description of your issue

when starting python example.py in the cmd I get the following error in the line 6

help please friends thanks

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
ModuleNotFoundError: No module named 'src'

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="xxxxxxx",
    password="xxxxxxxx",
    like_per_day=1200,
    comments_per_day=0,
    tag_list=['follow4follow', 'f4f', 'cute', 'l:212999109'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=150,
    follow_per_day=1000,
    follow_time=2 * 60,
    unfollow_per_day=900,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 2

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by dimisdas** [comment]
These are 2 diferrent commands, meant to be run one line at a time.

First "pip3 install -r requirements.txt”, then "pip3 install instaloader"

**Comment by pablo3600** [comment]
C:\Users\Dogi\Downloads>cd instabot.py-master

C:\Users\Dogi\Downloads\instabot.py-master>dir
 El volumen de la unidad C no tiene etiqueta.
 El número de serie del volumen es: 7C5A-A14F

 Directorio de C:\Users\Dogi\Downloads\instabot.py-master

13/12/2018  00:49    <DIR>          .
13/12/2018  00:49    <DIR>          ..
12/12/2018  10:15             1.115 .gitignore
13/12/2018  00:50             4.145 example.py
12/12/2018  10:15             1.290 ISSUE_TEMPLATE.md
12/12/2018  10:15             1.111 LICENSE
12/12/2018  10:15             5.255 README.md
12/12/2018  10:15                36 requirements.txt
               6 archivos         12.952 bytes
               2 dirs  225.036.587.008 bytes libres

C:\Users\Dogi\Downloads\instabot.py-master>pip3 install -r requirements.txt
Requirement already satisfied: requests in c:\users\Dogi\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 1)) (2.20.1)
Requirement already satisfied: fake-useragent in c:\users\Dogi\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 2)) (0.1.11)
Requirement already satisfied: instaloader in c:\users\Dogi\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 3)) (4.1.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\Dogi\appdata\local\programs\python\python37\lib\site-packages (from requests->-r requirements.txt (line 1)) (2018.10.15)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\Dogi\appdata\local\programs\python\python37\lib\site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\Dogi\appdata\local\programs\python\python37\lib\site-packages (from requests->-r requirements.txt (line 1)) (1.24.1)
Requirement already satisfied: idna<2.8,>=2.5 in c:\users\Dogi\appdata\local\programs\python\python37\lib\site-packages (from requests->-r requirements.txt (line 1)) (2.7)

C:\Users\Dogi\Downloads\instabot.py-master>pip3 install instaloader
Requirement already satisfied: instaloader in c:\users\Dogi\appdata\local\programs\python\python37\lib\site-packages (4.1.1)
Requirement already satisfied: requests>=2.4 in c:\users\Dogi\appdata\local\programs\python\python37\lib\site-packages (from instaloader) (2.20.1)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\Dogi\appdata\local\programs\python\python37\lib\site-packages (from requests>=2.4->instaloader) (1.24.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\Dogi\appdata\local\programs\python\python37\lib\site-packages (from requests>=2.4->instaloader) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\Dogi\appdata\local\programs\python\python37\lib\site-packages (from requests>=2.4->instaloader) (2018.10.15)
Requirement already satisfied: idna<2.8,>=2.5 in c:\users\Dogi\appdata\local\programs\python\python37\lib\site-packages (from requests>=2.4->instaloader) (2.7)

C:\Users\Dogi\Downloads\instabot.py-master>python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
ModuleNotFoundError: No module named 'src'

C:\Users\Dogi\Downloads\instabot.py-master>_

**Comment by pablo3600** [comment]
I have a lot of instabot problem
 continually if it is not a fault is another, that instability. it will be impossible for instabot to work a fucking month without touching the eggs

**Comment by dimisdas** [comment]
Instagram keeps changing their APIs and methods.

But since you’re unhappy, please send me your account and I’ll refund your zero dollars back.

**Comment by pablo3600** [comment]
instagram much change your methods, and then you see in instagram profiles running a bot that in 10 minutes ago 60,000 comments and 1,000,000 mentions of users in the comments and in a day 80 k followers.

that user will not use instabot since this gives more errors than helping your profile
