### ISSUE TITLE
pass me instabot.py-master.zip

### ISSUE THREAD

**Issue by pablo3600** [instabot-py/instabot.py#1806]

**Comment by pablo3600** [comment]
someone who works instabot.py. let share url the compressed file please. since the one I have only gives me errors continuously, and wasting time so that after only 10 minutes work is not worth it

**Comment by acollamat** [comment]
I've downloaded 2 days ago and still working right now. One thing I didn't do is I disable the follow/unfollow option. Seems that cause a lot of problem for now.
