### ISSUE TITLE
login with wrong checkpoint url with redirect to next=/accounts/login/

### ISSUE THREAD

**Issue by psannino77** [instabot-py/instabot.py#1807]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x]  I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x]  If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [x] 2.x
- [x] 3.x

## Description of your issue

When try to login I receive this:
{"message": "checkpoint_required", "checkpoint_url": "https://www.instagram.com/integrity/checkpoint/checkpoint_logged_out_main/21797168/lb25z6qGAn/?next=%2F", "lock": false, "status": 
"fail"}

via website I receive the same response with a redirect (302) to:
https://www.instagram.com/integrity/checkpoint/checkpoint_logged_out_main/21797168/Acx4liB7eg/?next=/accounts/login/

It's a loop. So I think that a issues related to the my accounts.

## Config
default

Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by psannino77** [comment]
Some problem via mobile web-browser. Only the app is working.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
