### ISSUE TITLE
the bot starts and says it follows someone but I watch instagram and not followed  

### ISSUE THREAD

**Issue by pablo3600** [instabot-py/instabot.py#1808]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

14.12.2018_12:27 Instabot v1.2.0 started at 14.12.2018 12:27:

14.12.2018_12:27 Trying to login as bonkgang...

14.12.2018_12:28 bonkgang login success!
14.12.2018_12:28 Get Media by tag: gang
14.12.2018_12:28 Removing already liked medias..
14.12.2018_12:28 Already followed before 246231269
14.12.2018_12:28 Trying to like media: 1932738307335522334
14.12.2018_12:28 Liked: 1932738307335522334. Like #1.
14.12.2018_12:29 Trying to follow: 3408333707
14.12.2018_12:29 Followed: 3408333707 #1.
14.12.2018_12:30 Trying to like media: 1932628407217466238
14.12.2018_12:30 Liked: 1932628407217466238. Like #2.
14.12.2018_12:31 Trying to follow: 8753059550
14.12.2018_12:31 Followed: 8753059550 #2.
14.12.2018_12:31 Trying to like media: 1932627394737536894
14.12.2018_12:31 Liked: 1932627394737536894. Like #3.
14.12.2018_12:33 Trying to follow: 2282914265
14.12.2018_12:33 Followed: 2282914265 #3.
14.12.2018_12:33 Trying to like media: 1932541435959908116
14.12.2018_12:33 Liked: 1932541435959908116. Like #4.
14.12.2018_12:33 Get Media by tag: gang
14.12.2018_12:33 Removing already liked medias..
14.12.2018_12:35 Already followed before 246231269
14.12.2018_12:35 Trying to like media: 1932317074627457650
14.12.2018_12:35 Liked: 1932317074627457650. Like #5.
14.12.2018_12:36 Trying to follow: 7739696383
14.12.2018_12:36 Followed: 7739696383 #4.
14.12.2018_12:37 Trying to like media: 1932177166285329619
14.12.2018_12:37 Liked: 1932177166285329619. Like #6.
14.12.2018_12:38 Already followed before 3408333707

the bot starts and says it follows someone but I watch instagram and not followed by anyone and so subserviently with the second follower, third, fourth etc etc some solution

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by Alexyoe** [comment]
Did you wait a bit and see if they came through. I know sometimes follows and unfollows show delayed on my app vs my bot.
