### ISSUE TITLE
Potential Shadowban?

### ISSUE THREAD

**Issue by bvttle** [instabot-py/instabot.py#1811]
I've noticed the last post I added has received much less engagement than usual. I'd usually get around 200 likes after a day, and this has dropped to about half. I've also noticed that a few times when I've gone to like a post manually over the last week or so, i've got an error a few times.

I'd been running the bot with 2000 likes, which i realise is a lot, so maybe that's the cause?

The bot is still liking posts, and has liked without any errors, but something seems a bit fishy..

Should I just lay off using the bot for a while or something?

Edit:
I've checked a few hashtags on an alternate account and the post seems to be showing. So I'm unsure..

**Comment by dimisdas** [comment]
Definitely lower those numbers! And take a small break. I keep my account at 900-1100 likes per day and haven’t noticed a drop in likes.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
