### ISSUE TITLE
Suspicious Login Attempt Loop [Fix Included]

### ISSUE THREAD

**Issue by edmundpf** [instabot-py/instabot.py#1812]
## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [x] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

Every login was prompting a challenge on Instagram's end. Fix has been implemented by removing unnecessary headers. Through testing I have confirmed that the current login request headers trigger the challenges every time. To test, I purposely tried to login with the bad headers and confirmed the suspicious login loop. When I removed those headers, the suspicious login loop was immediately fixed after solving the challenge/selecting "this was me" then logging in with the bot (must solve challenge first). In the login method, replace the `self.s.headers.update({...})` line with: 
```		
self.s.headers.update({
	'Accept-Language': 'en-US',
	'Referer': 'https://www.instagram.com',
	'User-Agent': self.user_agent,
	'X-Instagram-AJAX': '1',
	'X-Requested-With': 'XMLHttpRequest'
})
```
If someone could put in a pull request for this that'd be appreciated as my code is custom. Also I hard-coded in my accept language just to verify it is working in English, if you need another language that will need to be changed I'm assuming.

**Comment by dimisdas** [comment]
I honestly think the headers are generally good, EXCEPT for content-length: 0.

Requests module should automatically calculate this header. Defaulting to zero is wrong and not the standard behavior in any browser I know.

It’s a possible candidate for the login issues. Will update tomorrow after I’ve tested it. Thanks for posting your configuration!

**Comment by edmundpf** [comment]
the old headers basically matched the login headers you will see by manually logging into chrome, which are as follows 
```
:authority: www.instagram.com
:method: POST
:path: /accounts/login/ajax/
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
content-length: 92
content-type: application/x-www-form-urlencoded
cookie: mid=XBPsTwALAAEgGC9L9nVAjnNP2w6r; mcd=3; shbid=6034; shbts=1544809615.375004; rur=FRC; csrftoken=LgfTOm0L4UMlHgFUTVnxhC2bwZHSTyql; urlgen="{\"98.118.184.2\": 701}:1gXrYt:ojxn3Kk2wp0C9fcHUfsUVbmgPPQ"
origin: https://www.instagram.com
referer: https://www.instagram.com/accounts/login/?source=auth_switcher
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
x-csrftoken: LgfTOm0L4UMlHgFUTVnxhC2bwZHSTyql
x-instagram-ajax: 6ecc2973decd
x-requested-with: XMLHttpRequest
```
But, I have another bot written in nodejs which did not break that only had the headers above and had no login problems. That's where I got the idea and it worked as expected in python as well. Should we try sending this `x-instagram-ajax` header that is automatically sent in a browser but isn't with a manual request?

**Comment by guido-n** [comment]
Yep, same here - tested your patch, same IP addr etc. - not working : - /

Although the devil is definitely in the headers, that's for sure.

also #1799

**Comment by edmundpf** [comment]
> Yep, same here - tested your patch, same IP addr etc. - not working : - /
> 
> Although the devil is definitely in the headers, that's for sure.
> 
> also #1799
Did you try selecting "this was me" or verifying phone/email manually before using my fix? The steps I did to solve this were to solve the challenge on the same IP that triggered the challenge, then login with the boot and it worked smoothly on every account I tried.

**Comment by edmundpf** [comment]
> Im with Suspicious Login Attempt opened to two accounts and tested your self.s.headers.update @edmundpf and not work for me =\
have to select "this was me" then log in with the bot.

**Comment by edmundpf** [comment]
Challenge now implemented in login, example of challenge fix below:
![instabot_fix py](https://user-images.githubusercontent.com/25672477/50102814-0f309180-01f4-11e9-91b1-2c459cd21981.PNG)

**Comment by dimisdas** [comment]
Could you please share your implantation?! Wow!

**Comment by edmundpf** [comment]
> Could you please share your implementation ?! Wow!

I'm gonna get around to this tomorrow, mine has been heavily customized so I have to merge the changes with the current implementation.

**Comment by LopesX** [comment]
Thank you my friend @edmundpf

**Comment by JD2719** [comment]
@edmundpf Any luck? I could really use some help on this. 

Thanks in advanced!

**Comment by edmundpf** [comment]
> @edmundpf Any luck? I could really use some help on this.
> 
> Thanks in advanced!

Sorry guys been really busy at work this week, will put in pull request forwhat I have this weekend

**Comment by waynoedm** [comment]
Has anyone confirmed the solution to this issue?

**Comment by waynoedm** [comment]
I used to be able to get around the issue before by logging in and out of Instagram. Bot was running for several days and I stopped it to change my configuration. Has been looping on the challenge regardless of 'This was me' and putting in the code.

Swapped the lines in the code as per your recommendation and issue is still not solved.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
