### ISSUE TITLE
Trace back recent call (line 52,236,287,329,400

### ISSUE THREAD

**Issue by johndole** [instabot-py/instabot.py#1818]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\marie_000\Desktop\Pro instagram\instabot.py-master\src\instabot.py", line 236, in __init__
    self.login()
  File "C:\Users\marie_000\Desktop\Pro instagram\instabot.py-master\src\instabot.py", line 287, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\marie_000\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\cookies.py", line 329, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\marie_000\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\cookies.py", line 400, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

```

## Config

```
bot = InstaBot(
    login="",
    password="",
    like_per_day=1000,
    comments_per_day=20,
    tag_list=['bordeaux', 'bordeauxmaville', 'miroirdeau', 'art','photography','visualjournal','creativejournal','creativelife','abstractogram','dailybraverypaintings','abstractpainting','artoftheday','gallery','paint','instaart','creative','artwork','inspiration','music'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=100,
    follow_time=1 * 60,
    unfollow_per_day=0,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
```

**Comment by cicciokof** [comment]
exactly same error and same configuration. Was working fine until like 5 days ago then suddenly stopped. Rebooted and same error with no login possible. Tried loads of fix, nothing works.

**Comment by cicciokof** [comment]
last time i tried #1153 . it was last month and it worked fine since. Stopped like 5 days ago, restarted and got this. tried loads of fix now.

**Comment by dimisdas** [comment]
Hello. Please update to latest version on master branch. Create a new issue if the problem persists. Thanks!

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
