### ISSUE TITLE
Profile picture

### ISSUE THREAD

**Issue by tobeyond** [instabot-py/instabot.py#1826]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows 10
- [x] Linux Debian 9
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
Hello,
Is there any way to change the profile picture with instabot?
Thank you.
```

**Comment by dimisdas** [comment]
This is not supported, sorry.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
