### ISSUE TITLE
Again KeyError: "name=' csrftoken'

### ISSUE THREAD

**Issue by chris0211** [instabot-py/instabot.py#1827]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [X] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [X] 2.6
- [ ] 3.x

Hi all,

of course I already included the known solution regarding the given error message to my code (see below), and it worked fine for me. Today I stopped the bot for a while and tried to restart. And the error occured again. 

Is there something I did wrong?

THX
Chris

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

python example.py
18.12.2018_08:54 Instabot v1.2.0 started at 18.12.2018 08:54:

18.12.2018_08:54 Trying to login as ...

Traceback (most recent call last):
  File "example.py", line 43, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\insta\src\instabot.py", line 236, in __init__
    self.login()
  File "C:\insta\src\instabot.py", line 292, in login
    self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "C:\Users\s0851\AppData\Local\Programs\Python\Python36\lib\site-packages\
requests\cookies.py", line 327, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\s0851\AppData\Local\Programs\Python\Python36\lib\site-packages\
requests\cookies.py", line 398, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"



Corrected Code

> r= self.s.get(self.url)
>         csrf_token = re.search('(?<=\"csrf_token\":\")\w+', r.text).group(0)  
>         self.s.headers.update({'X-CSRFToken': csrf_token})
>         time.sleep(5 * random.random())

**Comment by Eggwise** [comment]
same error

**Comment by manguszta** [comment]
Hello! Since this CSRFtoken thing error occurs and the solution was posted, 1 of my 4 accounts hasn't worked, until yesterday. I figured out I had to change the URL which was in my bio... a simple "/" was enough at the end... and the bot miraculously logged in. Some people had to change their passwords to make these accounts work - but that alone wasn't enough in my case. Hope this helps.

**Comment by dimisdas** [comment]
Please update to latest version. Thank you!

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
