### ISSUE TITLE
Issue with instabot 18_12_2018 (new user)

### ISSUE THREAD

**Issue by pipsgrdp** [instabot-py/instabot.py#1828]
Hello guyz. I'm using the script for the first time. I'm a moderate script user.

When I run it I get this error:

Traceback (most recent call last):
  File "example.py", line 50, in <module>
    'follow', 'follower', 'gain', '.id', '_id', 'bags'
  File "C:\Users\Spyridon\Downloads\instabot.py-master\src\instabot.py", line 236, in __init__
    self.login()
  File "C:\Users\Spyridon\Downloads\instabot.py-master\src\instabot.py", line 287, in login
    self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
  File "C:\Users\Spyridon\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\Spyridon\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

What should I do? I searched around for related answers to related questions but I could not figure out any solution whatsoever.

**Comment by psannino77** [comment]
I have the some issue #1807.
Try to conntect via web browser (without fbook conntect). You can try in incognito mode.
I recevice a 301 with redirect to login wihout challange verification.
I don't know why. Is it a ban? I don't know.
But Yesterday I was able to start an account . The other three that I manage have this error that I do not think is bound to the instabot.

**Comment by chris0211** [comment]
Nope, I have the same Issue and I'm pretty sure that it isn't caused by invalid password or blocked account. When I try to login via web browser, everything is pretty normal. There were several users with the same message last days, but the solution isn't working anymore.

**Comment by dimisdas** [comment]
**Closed/Inactive**
Please create a new issue if the problem persists.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
