### ISSUE TITLE
How to like explore page images only?

### ISSUE THREAD

**Issue by neospeed83** [instabot-py/instabot.py#1839]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
Trying to make the bot comment and like only the images on explore page. Any idea how to achieve this?

**Comment by dimisdas** [comment]
This not a supported feature AFAIK. You can search and like media by tags only.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
