### ISSUE TITLE
No verification send from instagram

### ISSUE THREAD

**Issue by reliefs** [instabot-py/instabot.py#1842]
But seems instagram does not send any code to me.

Is there anything i'm mistaking?

Thanks in advance!
C

_Originally posted by @rollsappletree in https://github.com/instabot-py/instabot.py/pull/1788#issuecomment-449377855_

**Comment by Fan1s4444** [comment]
I have the same problem.. I have no autentification with sms or etc.. when I set it up, nothing changed. Still the same, waiting for code and nothing comming. When I set up 2way autentification I've got a couple of codes for restore my account. When I used it, nothing still happened. It is not possilble to login account with this commit.
