### ISSUE TITLE
1788 Pull: Challenge Required 

### ISSUE THREAD

**Issue by waynoedm** [instabot-py/instabot.py#1845]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X ] I have searched for other issues with the same problem. (including #1153)

## Hosting
Hosted on a Linux box in my home network.

#### Select one:
- [X ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [X ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X ] 3.x

## Description of your issue
Installed fresh 1788, dependencies are installed. Works perfectly for another account, however this account requires the challenge. When I put the proper challenge code in, it does not make a successful connection. Giving the same results regardless of putting in the correct code or not.

>>> Please install the latest version of pip
22.12.2018_22:18 Checking for updates...
22.12.2018_22:18 You are running the latest stable version
22.12.2018_22:18 Instabot v1.2.0/2 started at 22.12.2018 22:18:
22.12.2018_22:18 Trying to login as USERNAME ...
22.12.2018_22:18 Challenge required at https://instagram.com/challenge/2046661911/iy0wLjDxOA/
Challenge Required.

Enter the code sent to your mail/phone: ENTERED CODE
22.12.2018_22:18 {"message": "", "challenge": {"challengeType": "VerifyEmailCodeForm", "errors": ["Please check the code we sent you and try again."], "experiments": {}, "extraData": {"__typename": "GraphChallengePage", "content": [{"__typename": "GraphChallengePageHeader", "description": null, "title": "Enter Your Security Code"}, {"__typename": "GraphChallengePageText", "alignment": "center", "html": null, "text": "Enter the 6-digit code we sent to the email address w*******n@b*****.com."}, {"__typename": "GraphChallengePageForm", "call_to_action": "Submit", "display": "inline", "fields": [{"__typename": "GraphChallengePageFormSecurityCodeField", "input_name": "security_code", "input_type": "security_code", "value": {"label": "Security code", "placeholder": null, "value": null}}], "href": null}, {"__typename": "GraphChallengePageSecondaryText", "html": "Didn't receive your code? \u003ca href=\"javascript:_replay()\"\u003eGet a new one\u003c/a\u003e.", "text": null}]}, "fields": {"security_code": "None", "resend_delay": 60, "contact_point": "w*******n@b*****.com", "form_type": "email"}, "navigation": {"forward": "/challenge/2046661911/iy0wLjDxOA/", "replay": "/challenge/replay/2046661911/iy0wLjDxOA/", "back": "/challenge/reset/2046661911/iy0wLjDxOA/"}, "privacyPolicyUrl": "/about/legal/privacy/", "type": "CHALLENGE"}, "status": "fail"}
22.12.2018_22:18 Login error! Connection error!
22.12.2018_22:18 Removing already liked medias..
22.12.2018_22:18 Removing already liked medias..
22.12.2018_22:18 Removing already liked medias..

## Config

The config is examply.py with a single hashtag and unfollow set to 0. For testing purpose.

**Comment by itsmejamie** [comment]
Have updated to the latest version of the bot, where I get the request to enter the code. But don't seem to be getting anything sent through. I've looked in my spam folder and nothing there. It's set up to go to a gmail account. I do get the 'New Login' emails, so its not an incorrect email address entered.

**Comment by budstankz** [comment]
same problem here

**Comment by waynoedm** [comment]
I'm getting the codes through, but doesn't let me through when the code is entered.

**Comment by waynoedm** [comment]
So I'm assuming the input isn't being passed on to instagram through the instabot?

**Comment by itsmejamie** [comment]
It took a while to log in, but I didn't get the challenge today.

**Comment by JD2719** [comment]
Has anyone been able to get through the checkpoint?

I am running 2 accounts right now, that did not require a verification checkpoint.

**Comment by waynoedm** [comment]
Previously I was able to solve the challenge issue by logging out and logging back in. But when I had posted this a few days ago, that has stopped working. I have found that once the challenge is required, the bot will no longer function.

I would suggest once you find settings that work, not to stop your bot as when I went to run it again the last time, the challenge came up.

**Comment by waynoedm** [comment]
Just tried. Looks like challenge requirement is over. Guess it just needed a few days to clear.

**Comment by waynoedm** [comment]
With that said, it would be nice to not have to wait.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
