### ISSUE TITLE
Python3 vs. Python ( Login error! Connection error!)

### ISSUE THREAD

**Issue by JD2719** [instabot-py/instabot.py#1846]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ X] Windows (Windows 10)
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X ] 3.x

## Description of your issue
Like many Windows users on here, it seems the latest fix is not working. We are able to get through the email verification checkpoint, (`"status": "ok"`) but then receive "`Login error! Connection error!`"

I see many people stressing that you must use the latest Python, and Pip run "python3 example.py"

I have downloaded the latest versions of python (tried both 3.6 and 3.7) and installed the latest Pip but "`python3 example.py`" always gives me an error `python3' is not recognized as an internal or external command, operable program or batch file.`

Is there something I'm missing?

Bellow is the error I receive when attempting " `python example.py`

```
C:\Users\*******\Desktop\instabot.fix>python3 example.py
'python3' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\*******\Desktop\instabot.fix>python example.py
23.12.2018_01:01 Checking for updates...
23.12.2018_01:01 You are running the latest stable version
23.12.2018_01:01 Instabot v1.2.0/2 started at 23.12.2018 01:01:
23.12.2018_01:01 Trying to login as  ***********...
23.12.2018_01:01 Challenge required at https://instagram.com/challenge/7154159344/Au6U1Zbdtc/
Challenge Required.

Enter the code sent to your mail/phone: 643520
23.12.2018_01:02 {"location": "https://www.instagram.com/", "type": "CHALLENGE_REDIRECTION", "status": "ok"}
23.12.2018_01:02 Login error! Connection error!
23.12.2018_01:02 Removing already liked medias..
23.12.2018_01:02     >>>Waiting for database to populate before unfollowing (progress 0/10)
23.12.2018_01:02 Removing already liked medias..
23.12.2018_01:02 Removing already liked medias..

**Comment by trrinsta** [comment]
I've had the same problem for a week now and idk what to do or where to begin?!? I'm kinda new on how to run python and how to program on it so I have no idea what is what.

**Comment by TRys8** [comment]
Hi, I had the same issue.  You can use the command "py -3" instead of "python3".  That worked for me.  If you want to run v2 of python, you can type "py -2".

**Comment by JD2719** [comment]
> Hi, I had the same issue. You can use the command "py -3" instead of "python3". That worked for me. If you want to run v2 of python, you can type "py -2".

I tried that. It doesn't appear to make any difference. Still stuck at the `Login error! Connection error!`

**Comment by JD2719** [comment]
> I've had the same problem for a week now and idk what to do or where to begin?!? I'm kinda new on how to run python and how to program on it so I have no idea what is what.

Have you checked out [1788](url)?  Some users are running after doing that. Not me

**Comment by dimisdas** [comment]
Unfortunately I have a hard time replicating this issue since I can't get the challenge myself again. So my pull request you downloaded might not work 100% of the time.

If someone has a spare account that gets challenges or any insight on how to fix my pull request, I'm open to anything really.

**Comment by JD2719** [comment]
> Unfortunately I have a hard time replicating this issue since I can't get the challenge myself again. So my pull request you downloaded might not work 100% of the time.
> 
> If someone has a spare account that gets challenges or any insight on how to fix my pull request, I'm open to anything really.

Want to try it on my account? 

I appreciate all the work you've done here, and if it could help solve this, I'd be more than happy to help. Unfortunately I'm a real rookie when it comes to this stuff

**Comment by DarkSuniuM** [comment]
https://docs.python.org/3/using/windows.html#from-the-command-line

All Python versions on Windows works with `py` and `python` command in CMD, it will run the latest version u got installed

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
