### ISSUE TITLE
How does Selebgram work?

### ISSUE THREAD

**Issue by itsmejamie** [instabot-py/instabot.py#1850]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

I'm getting quite a few accounts recognised as Selebgram accounts which are genuine accounts. What is the criteria for an account to be flagged as Selebgram? 

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by Brcalvo** [comment]
You can see this in the code:

if follows == 0 or follower / follows > 2

So it means if they don't follow anyone or if they have too many followers vs the people they follow. I have deactivated this option as I don´t believe I should unfollow all accounts which meet this criteria.

**Comment by itsmejamie** [comment]
@Brcalvo 

Thanks, that's good to know. Interestingly enough, one of the accounts I follow didn't meet this criteria. So wondering if it's been tweaked slightly.

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
