### ISSUE TITLE
Challenge Required

### ISSUE THREAD

**Issue by Massimosso** [instabot-py/instabot.py#1860]
Someone know how resolve the problem of the Challenge required with python3? 

Thanks. 👍 

Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [X] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X] 3.x

## Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by Massimosso** [comment]
Do you have any alternative? @pablo3600

**Comment by pablo3600** [comment]
uninstall instabot give me case this shit is not worth it just waste time

**Comment by dimisdas** [comment]
User resolved it 
https://github.com/instabot-py/instabot.py/pull/1788#issuecomment-452542778

**Comment by DarkSuniuM** [comment]
Closed all the issues till 2019-01-09, We updated the repo, Please create a new issue if you need! Thanks
