### ISSUE TITLE
The bot is not unfollowing

### ISSUE THREAD

**Issue by Th3BiSh0p** [instabot-py/instabot.py#1873]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [X] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X] 3.x

## Description of your issue
I've updated the bot with the code released today, it's working fine except for one point : the bot is not unfollowing at all, stuck with `Trying to unfollow #1:`
I'm using mode 0

**Comment by dimisdas** [comment]
Could you please post the whole log? Is it possible to check your DB and see how many users it has. Is there any content in error.log?

Thanks

**Comment by Th3BiSh0p** [comment]
[log.log](https://github.com/instabot-py/instabot.py/files/2740941/log.log)
error.log is empty
20999 entries in usernames table from db

**Comment by dimisdas** [comment]
I cannot reproduce the bug. If you create a new DB file (change the name of the old one, keep back up), does unfollow work?

**Comment by Th3BiSh0p** [comment]
Unfollow seems to work well with an empty db

**Comment by dimisdas** [comment]
Is it possible that your DB has become corrupt? Do you have any way to check?

Else, I'd suggest you start a new .db file and let it populate again. And/or perhaps migrate the usernames manually using some other tool.

**Comment by JD2719** [comment]
I started over, and It didn't work. It simply kept bring up users based on my recent feed, then not unfollowing them.

**Comment by dimisdas** [comment]
> I started over, and It didn't work. It simply kept bring up users based on my recent feed, then not unfollowing them.

There's a timer before unfollowing someone you just inserted in the DB, to avoid follow/unfollowing people within the span of a few minutes.

**Comment by dimisdas** [comment]
I’d suggest running manually the SQL select queries from the sql database functions, and see if any errors come up. Otherwise, perhaps begin anew?

The new version populates based on recent feed too.

**Comment by JD2719** [comment]
Anyone Have a solution to this yet? Ive tried everything mentioned, no luck.

**Comment by floppydrive** [comment]
I see this behavior as well. I looked into the database and it seems that the name is always "0" of all the users. Is this a problem?
Thanks in advance.
-Stefan
