### ISSUE TITLE
ValueError: No JSON object could be decoded in Python

### ISSUE THREAD

**Issue by 247614** [instabot-py/instabot.py#1874]
Getting Failed at Build output section.

from __future__ import print_function
import json
import sys

def load_json_file(template_file_location):
    """
    Load json file and return as python object
    """
    try:
        return json.load(open(template_file_location))
    except ValueError as error:
        print('Error parsing: {}'.format(template_file_location))
        raise error
    except IOError as error:
        print('Cannot open file: {}'.format(template_file_location))
        raise error

def get_builders_from_config(packer_config):
    builders = {}

    for builder in packer_config['builders']:
        name = builder['name']
        region = builder['region']
        builders[name] = {}
        builders[name][region] = None

        if 'ami_regions' in builder:
            for region in builder['ami_regions']:
                builders[name][region] = None

    return builders

def compare_builders(builders, output):
    missing_output = {}
    for builder, regions in builders.iteritems():
        missing_output[builder] = []
        if builder in output:
            for region in regions:
                if region not in output[builder]:
                    missing_output[builder].append(region)
        else:
            missing_output[builder].extend(regions.keys())

    return missing_output

def main():
    packer_config = load_json_file(sys.argv[1])
    packer_output = load_json_file(sys.argv[2])

    builders = get_builders_from_config(packer_config)
    diff = compare_builders(builders, packer_output)
    failed_builders = False

    for builder, regions in diff.iteritems():
        if len(regions) > 0:
            failed_builders = True
            print(
                'Builder {} failed for region(s): {}'.format(
                    builder,
                    ', '.join(regions)
                )
            )
        else:
            print(
                'Builder {} completed succesfully!'.format(
                    builder
                )
            )

    if failed_builders:
        sys.exit(1)

if __name__ == '__main__':
    main()

![build_output](https://user-images.githubusercontent.com/46528925/50903410-019ab000-141e-11e9-9cf0-ac8e0be2bcc4.PNG)

**Comment by DarkSuniuM** [comment]
Are u even using instabot?

**Comment by 247614** [comment]
No

**Comment by 247614** [comment]
Issue Got Resolved. Thank You :)
