### ISSUE TITLE
Error after update: "Please install the latest version of pip"

### ISSUE THREAD

**Issue by heldausberlin** [instabot-py/instabot.py#1876]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

I updated the latest version of instabot.py and also updated Python (3.7.2) and pip (18.1). But i still get the message:

```
>>> Please install the latest version of pip
  Could not find a version that satisfies the requirement lxkeymap==0.1 (from -r requirements.txt (line 25)) (from versions: )
No matching distribution found for lxkeymap==0.1 (from -r requirements.txt (line 25))
```

I already did 
`pip3 install -r requirements.txt`

So what could be wrong? I'm grateful for any help.

## Config

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="username",
    password="password",
    like_per_day=992,
    comments_per_day=354,
    tag_list=['follow4follow', 'f4f', 'cute', 'l:212999109'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=45,
    follow_per_day=0,
    follow_time=1 * 60,
    unfollow_per_day=0,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        bot.bot_mode = 3
        while(bot.login_status == 1):
            bot.unfollow_recent_feed()
            time.sleep(5)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

```

**Comment by DarkSuniuM** [comment]
As the error says, u have to update PIP
`pip install -U pip` should work

**Comment by heldausberlin** [comment]
As I said I did. I have version 18.1. So why does it say it has to be updated?

**Comment by DarkSuniuM** [comment]
What is the output of `pip -V` and `pip3 -V`?

**Comment by heldausberlin** [comment]
Both are:
`pip 18.1 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)`

So, I have installed Python 3.7.2, why is there still 3.5? What did I wrong? Thanks a lot for your help!

**Comment by DarkSuniuM** [comment]
What is your operating system? is `python -V` returning `Python 3.7.2`?

**Comment by dimisdas** [comment]
“sudo python -m pip install -U pip==8.0.1”

**Comment by heldausberlin** [comment]
Ah, I think we're getting closer. 

with `python -V` it says: `Python 2.7.13`

`python3 -V` says: `Python 3.7.2`

`sudo python3 -m pip install -U pip==8.0.1` says: `/usr/local/bin/python3: No module named pip`

and with `sudo python -m pip install -U pip==8.0.1` comes out:
```
Collecting pip==8.0.1
  Downloading https://files.pythonhosted.org/packages/45/9c/6f9a24917c860873e2ce7bd95b8f79897524353df51d5d920cd6b6c1ec33/pip-8.0.1-py2.py3-none-any.whl (1.2MB)
    100% |################################| 1.2MB 41kB/s 
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed pip-8.0.1
```

`sudo python3 example.py` comes to:
`>>> Please install the latest version of pip`

and `sudo python example.py`to:
`Python v3.5 or above required for Instaloader module at the moment. Exiting...`

So it seems not to use the latest python, because of the old existing version. How can I change it?

The OS is raspbian Jessie. Thanks a lot!

**Comment by DarkSuniuM** [comment]
Again, whats your OS ?

**Comment by DarkSuniuM** [comment]
Okey then, use this method to install pip for Python 3.7.2

`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`
`python3 get-pip.py`

Source: https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py

**Comment by heldausberlin** [comment]
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1622k  100 1622k    0     0   927k      0  0:00:01  0:00:01 --:--:--  927k
curl: (6) Could not resolve host: python3
curl: (6) Could not resolve host: get-pip.py
```

☹️

**Comment by DarkSuniuM** [comment]
> ```
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 1622k  100 1622k    0     0   927k      0  0:00:01  0:00:01 --:--:--  927k
> curl: (6) Could not resolve host: python3
> curl: (6) Could not resolve host: get-pip.py
> ```
> 
> frowning_face

Those where 2 different commands, splitting in 2 lines, did you run both together?

**Comment by heldausberlin** [comment]
Yes, sorry. I recognized it afterwards. Thanks. 

`python3 get-pip.py` comes out with: 
```
Traceback (most recent call last):
  File "get-pip.py", line 20890, in <module>
    main()
  File "get-pip.py", line 197, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    import pip._internal
  File "/tmp/tmp87fym7if/pip.zip/pip/_internal/__init__.py", line 40, in <module>
  File "/tmp/tmp87fym7if/pip.zip/pip/_internal/cli/autocompletion.py", line 8, in <module>
  File "/tmp/tmp87fym7if/pip.zip/pip/_internal/cli/main_parser.py", line 12, in <module>
  File "/tmp/tmp87fym7if/pip.zip/pip/_internal/commands/__init__.py", line 6, in <module>
  File "/tmp/tmp87fym7if/pip.zip/pip/_internal/commands/completion.py", line 6, in <module>
  File "/tmp/tmp87fym7if/pip.zip/pip/_internal/cli/base_command.py", line 18, in <module>
  File "/tmp/tmp87fym7if/pip.zip/pip/_internal/download.py", line 38, in <module>
  File "/tmp/tmp87fym7if/pip.zip/pip/_internal/utils/glibc.py", line 3, in <module>
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
```

**Comment by DarkSuniuM** [comment]
Something is wrong with your Python installation, `ctypes` is a standard library which gets install by Python itself

**Comment by dimisdas** [comment]
Sorry to interrupt. The pip error is only
Important when trying to install the dependencies through the bot. If you have installed them using

pip3 install -r requirements.txt

And run the bot with

python3 example.py

The error should still appear (todo, change it to NOTICE) but the bot should run normally.

**Comment by heldausberlin** [comment]
> The error should still appear (todo, change it to NOTICE) but the bot should run normally.
What exactly do you mean with “todo, change it to NOTICE“?

**Comment by dimisdas** [comment]
Note to self, change the code.

Does the rest of the script work?

**Comment by heldausberlin** [comment]
No, it doesn’t start.

**Comment by DarkSuniuM** [comment]
> Note to self, change the code.
> 
> Does the rest of the script work?

pip3 is installing modules for Python 3.5
python3 is running Python 3.7.2

The problem is not instabot

**Comment by dimisdas** [comment]
Have you tried 

sudo python3 -m pip uninstall pip && sudo apt install python3-pip --reinstall

**Comment by DarkSuniuM** [comment]
> Have you tried
> 
> sudo python3 -m pip uninstall pip && sudo apt install python3-pip --reinstall

Sinse he is using Raspian jessie, python3-pip will install pip for Python 3.4

**Comment by heldausberlin** [comment]
`sudo python3 -m pip uninstall pip && sudo apt install python3-pip --reinstall`
comes out with: 
`/usr/local/bin/python3: No module named pip`

**Comment by dimisdas** [comment]
I really don’t know. I’d refer you to a forum for Raspberry’s Jessie. This is beyond me or the scope of this repo :(

**Comment by heldausberlin** [comment]
Okay, thanks a lot to all of you! I appreciate the time you spent with my problem.
