### ISSUE TITLE
Bot stopped when unfollow, it only works few seconds.

### ISSUE THREAD

**Issue by eflames** [instabot-py/instabot.py#1884]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

Bot stuck in the first attempt to unfollow. I tried with fresh database too.

The error log it's empty but this is the whole message, it stoped after seconds of working.

12.01.2019_02:14 Checking for updates...
12.01.2019_02:14 You are running the latest stable version
12.01.2019_02:14 Instabot v1.2.0/3 started at 12.01.2019 02:14:
12.01.2019_02:14 Trying to login as myaccount...
12.01.2019_02:16 myaccount login success!

12.01.2019_02:16 Get Media by tag: miami
12.01.2019_02:16 Removing already liked medias..
12.01.2019_02:16 Trying to like media: 1954996421321235990
12.01.2019_02:16 Liked: 1954996421321235990. Like #1.
12.01.2019_02:16 Trying to follow: 6056694099
12.01.2019_02:16 Followed: 6056694099 #1.
12.01.2019_02:16     >>>Waiting for database to populate before unfollowing (progress 4/20)
                        (Will try to populate using recent feed)
12.01.2019_02:16 myaccount : Get media id on recent feed
12.01.2019_02:16 Media in recent feed = 12
Traceback (most recent call last):
  File "myaccount.py", line 68, in <module>
    bot.new_auto_mod()
  File "/Users/ernestoflames/Instabot/src/instabot.py", line 869, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "/Users/ernestoflames/Instabot/src/instabot.py", line 955, in new_auto_mod_unfollow
    self.populate_from_feed()
  File "/Users/ernestoflames/Instabot/src/instabot.py", line 939, in populate_from_feed
    feed_username = mediafeed_user["node"]["owner"]["username"]
KeyError: 'owner'
12.01.2019_02:16 Trying to unfollow: 6056694099
12.01.2019_02:16 Unfollow: 6056694099 #1 of 1.
12.01.2019_02:16 Pausing for 28 seconds... 1 of 1
12.01.2019_02:16 Logout: likes - 1, follow - 1, unfollow - 1, comments - 0.
12.01.2019_02:16 Bot work time: 0:01:45.329593
12.01.2019_02:16 Logout success!

## Config

bot = InstaBot(
    login="myaccount",
    password="mypassword",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=['web', 'paginas', 'diseño', 'programacion','caracas','venezuela','miami','doral'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["😎", "🔥", "💪"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:
    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")
    ################################
    ##  WARNING   ###
    ################################
    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD
    mode = 0
    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)
    if mode == 0:
        bot.new_auto_mod()
    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)
    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()
    elif mode == 3:
        bot.bot_mode = 3
        while(bot.login_status == 1):
            bot.unfollow_recent_feed()
            time.sleep(5)
    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)
    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)
    else:
        print("Wrong mode!")

## Apologize

Sorry for my english btw.. xD

**Comment by DarkSuniuM** [comment]
Did you try the new update?

**Comment by dickmagness** [comment]
I’m having the exact same issue. Account is following 2700 users.

**Comment by dickmagness** [comment]
Tried latest update - exact same issue. Following 2700.

**Comment by kingrelic670** [comment]
what does "Waiting for database to populate before unfollowing (progress 11/20)"
mean?

**Comment by vasquezandres** [comment]
me esta pasando exactamente lo mismo trabaja bien por uno minutos y deja de funcionar

**Comment by dimisdas** [comment]
This issue should be resolved in latest version. The function is wrapped around a try/catch and it should produce an appropriate error and resume. Please reopen if the problem persists.
