### ISSUE TITLE
Failed to populate from recent feed.

### ISSUE THREAD

**Issue by Stevio2000** [instabot-py/instabot.py#1885]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

When running the script I sometimes get the error:
> 12.01.2019_14:28 Notice: could not populate from recent feed
I just keeps going after getting the error, but what does it means and is there anything I can do to fix it?

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT

It's not showing up in the Error.log, only in the console.

## Config

[***]
username = ***
password = ***
like_per_day = 709
comments_per_day = 31
max_like_for_one_tag = 36
follow_per_day = 310
follow_time = 90
unfollow_per_day = 297
unfollow_break_min = 3
unfollow_break_max = 17
tag_list = ["***", "***", "***", "***"]

**Comment by dimisdas** [comment]
How many people are you following on that account?

**Comment by Stevio2000** [comment]
Currently I'm on 94 following.

**Comment by dimisdas** [comment]
Well it tries to get new posts from your following feed and it’s failing for some reason. It’s just a notice, not an error. The bot still works. 

:)

**Comment by Stevio2000** [comment]
Yeah that's what I thought as well, I wonder why it's failing though! 🤔

**Comment by dimisdas** [comment]
Visit http://instagram.com from your browser and login. Is the feed appearing normally or are there any messages for you there?

**Comment by Stevio2000** [comment]
No nothing strange is happening, it just opens as normal.

**Comment by dimisdas** [comment]
Unfortunately I cannot reproduce this. :/

**Comment by Stevio2000** [comment]
Hmmhm, thanks for taking your time to look into this! Maybe someone else has seen this notice before.

**Comment by dimisdas** [comment]
Could you replace your instabot.py with this?

https://gist.github.com/dimisdas/3fc18521c00a477e8edc4d9ee9cbf886

It's going to crash and print a veeeery long output. Could you please send it to me?

**Comment by JD2719** [comment]
Same problem. Ive tried deleted followers.db and starting over, but nothing works. I ran the bot up to 5,000 following, and I need a way to dump them

**Comment by dimisdas** [comment]
I feel like something is missing from that output, the page is incomplete. Are you sure you copied the whole thing?

**Comment by Stevio2000** [comment]
Yup, A friend of me just installed the bot aswell and gets the same notice.

**Comment by Stevio2000** [comment]
UPDATE:
I just installed the bot on my Synology NAS and now it works perfectly fine. Not sure what it is.
