### ISSUE TITLE
Challenge required again

### ISSUE THREAD

**Issue by Fan1s4444** [instabot-py/instabot.py#1887]
Hey,

the bot is now working well, he comments great etc.. but when I stop it and I want to re-run I get again Challenge required. When I try to log in in browser, everything OK, no challenge required but only in bot. When I wait about 3 days or more, I can start it and it will be working well, until restart (because of changing tags or something).

Is is it possible to do something with it? Or it is a Instagram problem. My accounts dont require any challenge.

Thank you for answer :-)

_btw. yesterday was a problem with csfr again, but today it is working great, I think it was problem of Instagram._

```
12.01.2019_15:40 Checking for updates...
12.01.2019_15:40 You are running the latest stable version
12.01.2019_15:40 Instabot v1.2.1/0 started at 12.01.2019 15:40:
12.01.2019_15:40 Trying to login as marley_chin...
12.01.2019_15:40 Challenge required at https://instagram.com/challenge/2086208382/SOGkbLh8gX/
Challenge Required.

Enter the code sent to your mail/phone: 
```

**Comment by dimisdas** [comment]
Use the new session_file parameter in your example.py, or use run.py.

This will save the cookies and you won't have to login every time you run the script.

**Comment by Fan1s4444** [comment]
I use run.py everytime. I type nickname login and after this I get challenge required. When I download clear package and set up new bot, still challenge required. I dont know why.

**Comment by DarkSuniuM** [comment]
Working on it right now, I will push a commit in an hour

**Comment by DarkSuniuM** [comment]
#1861 Duplicated by the way

**Comment by murlikanne** [comment]
@DarkSuniuM you have no idea how much i'm looking forward to this update.

**Comment by DarkSuniuM** [comment]
@murlikanne I updated the repo, did u try it?

**Comment by murlikanne** [comment]
@DarkSuniuM omg, i did try now again with the updated files, both conventional and via run.py, the login fails everytime :(

**Comment by DarkSuniuM** [comment]
Can u be more specific?

**Comment by murlikanne** [comment]
> Can u be more specific?

@DarkSuniuM sure, so this is the error I see while I try to run using python filename.py command:

12.01.2019_23:15 Checking for updates...
12.01.2019_23:15 You are running the latest stable version
12.01.2019_23:15 Instabot v1.2.1/0 started at 12.01.2019 23:15:
12.01.2019_23:15 Trying to login as username...
12.01.2019_23:15 Something is wrong with Instagram! Please try again later...
12.01.2019_23:15 Error => Sorry, there was a problem with your request.
12.01.2019_23:15 Exit Program... GoodBye

===========================================

While I configured, run.py:

C:\Users\DELL\Music\5>python run.py
     _________LOGIN_________
     (To change user settings, type "config")

     Please enter your username: username
     Loading settings for lily.never!
     (Tip: Log in directly by running 'run.py username')


     >>> Starting bot >>>
________________________________________________
12.01.2019_23:18 Checking for updates...
12.01.2019_23:18 You are running the latest stable version
12.01.2019_23:18 Instabot v1.2.1/0 started at 12.01.2019 23:18:
12.01.2019_23:18 Trying to login as username...
12.01.2019_23:18 Something is wrong with Instagram! Please try again later...
12.01.2019_23:18 Error => Sorry, there was a problem with your request.
12.01.2019_23:18 Exit Program... GoodBye

**Comment by Fan1s4444** [comment]
I dont have a error I still have a problem with challenge. When I run it it want challenge my account unfortunately browser no. 

When I set up in example.py way for clear .session file and .db file I got follow error.

```
12.01.2019_18:52 Checking for updates...
12.01.2019_18:52 You are running the latest stable version
12.01.2019_18:52 Instabot v1.2.1/0 started at 12.01.2019 18:52:
12.01.2019_18:52 Found session file marley_chin.session
Traceback (most recent call last):
  File "example.py", line 54, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/home/fanda/instacek/src/instabot.py", line 291, in __init__
    self.login()
  File "/home/fanda/instacek/src/instabot.py", line 356, in login
    cookies = pickle.load(i)
EOFError: Ran out of input
```

**Comment by murlikanne** [comment]
> I dont have a error I still have a problem with challenge. When I run it it want challenge my account unfortunately browser no.
> 
> When I set up in example.py way for clear .session file and .db file I got follow error.
> 
> ```
> 12.01.2019_18:52 Checking for updates...
> 12.01.2019_18:52 You are running the latest stable version
> 12.01.2019_18:52 Instabot v1.2.1/0 started at 12.01.2019 18:52:
> 12.01.2019_18:52 Found session file marley_chin.session
> Traceback (most recent call last):
>   File "example.py", line 54, in <module>
>     unfollow_whitelist=['example_user_1', 'example_user_2'])
>   File "/home/fanda/instacek/src/instabot.py", line 291, in __init__
>     self.login()
>   File "/home/fanda/instacek/src/instabot.py", line 356, in login
>     cookies = pickle.load(i)
> EOFError: Ran out of input
> ```

@Fan1s4444 I was sure, I was doing something wrong, can you help me create a session file and test? appreciated.

**Comment by DarkSuniuM** [comment]
> > Can u be more specific?
> 
> @DarkSuniuM sure, so this is the error I see while I try to run using python filename.py command:
> 
> 12.01.2019_23:15 Checking for updates...
> 12.01.2019_23:15 You are running the latest stable version
> 12.01.2019_23:15 Instabot v1.2.1/0 started at 12.01.2019 23:15:
> 12.01.2019_23:15 Trying to login as username...
> 12.01.2019_23:15 Something is wrong with Instagram! Please try again later...
> 12.01.2019_23:15 Error => Sorry, there was a problem with your request.
> 12.01.2019_23:15 Exit Program... GoodBye
> 
> ===========================================
> 
> While I configured, run.py:
> 
> C:\Users\DELL\Music\5>python run.py
> _********LOGIN********_
> (To change user settings, type "config")
> 
> ```
>  Please enter your username: username
>  Loading settings for username
>  (Tip: Log in directly by running 'run.py username')
> 
> 
>  >>> Starting bot >>>
> ```
> 
> 12.01.2019_23:18 Checking for updates...
> 12.01.2019_23:18 You are running the latest stable version
> 12.01.2019_23:18 Instabot v1.2.1/0 started at 12.01.2019 23:18:
> 12.01.2019_23:18 Trying to login as username...
> 12.01.2019_23:18 Something is wrong with Instagram! Please try again later...
> 12.01.2019_23:18 Error => Sorry, there was a problem with your request.
> 12.01.2019_23:18 Exit Program... GoodBye

This is an error from the instagram itself not the bot

**Comment by DarkSuniuM** [comment]
> I dont have a error I still have a problem with challenge. When I run it it want challenge my account unfortunately browser no.
> 
> When I set up in example.py way for clear .session file and .db file I got follow error.
> 
> ```
> 12.01.2019_18:52 Checking for updates...
> 12.01.2019_18:52 You are running the latest stable version
> 12.01.2019_18:52 Instabot v1.2.1/0 started at 12.01.2019 18:52:
> 12.01.2019_18:52 Found session file marley_chin.session
> Traceback (most recent call last):
>   File "example.py", line 54, in <module>
>     unfollow_whitelist=['example_user_1', 'example_user_2'])
>   File "/home/fanda/instacek/src/instabot.py", line 291, in __init__
>     self.login()
>   File "/home/fanda/instacek/src/instabot.py", line 356, in login
>     cookies = pickle.load(i)
> EOFError: Ran out of input
> ```

Move session to somewhere else, try again

**Comment by murlikanne** [comment]
> > > Can u be more specific?
> > 
> > 
> > @DarkSuniuM sure, so this is the error I see while I try to run using python filename.py command:
> > 12.01.2019_23:15 Checking for updates...
> > 12.01.2019_23:15 You are running the latest stable version
> > 12.01.2019_23:15 Instabot v1.2.1/0 started at 12.01.2019 23:15:
> > 12.01.2019_23:15 Trying to login as username...
> > 12.01.2019_23:15 Something is wrong with Instagram! Please try again later...
> > 12.01.2019_23:15 Error => Sorry, there was a problem with your request.
> > 12.01.2019_23:15 Exit Program... GoodBye
> > ===========================================
> > While I configured, run.py:
> > C:\Users\DELL\Music\5>python run.py
> > _********LOGIN********_
> > (To change user settings, type "config")
> > ```
> >  Please enter your username: username
> >  Loading settings for username
> >  (Tip: Log in directly by running 'run.py username')
> > 
> > 
> >  >>> Starting bot >>>
> > ```
> > 12.01.2019_23:18 Checking for updates...
> > 12.01.2019_23:18 You are running the latest stable version
> > 12.01.2019_23:18 Instabot v1.2.1/0 started at 12.01.2019 23:18:
> > 12.01.2019_23:18 Trying to login as username...
> > 12.01.2019_23:18 Something is wrong with Instagram! Please try again later...
> > 12.01.2019_23:18 Error => Sorry, there was a problem with your request.
> > 12.01.2019_23:18 Exit Program... GoodBye
> 
> This is an error from the instagram itself not the bot

I'm able to log into these accounts on a browser, is this the end for me? :(

**Comment by murlikanne** [comment]
> @murlikanne No there is no End, Are u using the same IP which u are using with bot?

@DarkSuniuM yes never set up a proxy, should i buy a proxy and try?

**Comment by DarkSuniuM** [comment]
No, don't need to use a bot, Open a new issue for it

**Comment by murlikanne** [comment]
> No, don't need to use a bot, Open a new issue for it

you mean don't use the bot for now and create a new issue for it? Okay, on it. Thanks though, much appreciated.

**Comment by DarkSuniuM** [comment]
> > No, don't need to use a bot, Open a new issue for it
> 
> you mean don't use the bot for now and create a new issue for it? Okay, on it. Thanks though, much appreciated.

Sry meant to type proxy, Just Create an issue for your problem

**Comment by murlikanne** [comment]
> > > No, don't need to use a bot, Open a new issue for it
> > 
> > 
> > you mean don't use the bot for now and create a new issue for it? Okay, on it. Thanks though, much appreciated.
> 
> Sry meant to type proxy, Just Create an issue for your problem

It's okay, created a new issue for this error.
