### ISSUE TITLE
When someone is following you, dont unfriend that person

### ISSUE THREAD

**Issue by worldsdream** [instabot-py/instabot.py#1889]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so; have you tried running the code on your local machine?

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [X] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X] 3.x

## Description of your issue

The bot is working great. But the issue that I am having is, it’s unfriending the people that are following me. Yes I do know that there is a whitelist option, I have added all the friends in it. But what if the bot follows someone and that person follows you back. It should not unfollow that person. How can I get this working? Thank you.

**Comment by yahgiggle** [comment]
i was thinking mode 3 does this but when turned on it just crash's on start up so its broken oO
