### ISSUE TITLE
Raspberry Pi 

### ISSUE THREAD

**Issue by koeniig2** [instabot-py/instabot.py#1890]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [x] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

i cant install instaloader on raspberry pi 3+.. it is installed, but when i run python3 example.txt .. it says instaloader needs python 3.5 to run.. but what command i use to get it to run? 

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by yurilaaziz** [comment]
Could you please give us the output of 
- 'uname -a '
- 'python --version '

**Comment by yurilaaziz** [comment]
I think you're using python2, this project give up support for python2 (not bad).
Please install python3 by doing 
``` apt-get install python3 python3-venv```
 
As your system is based on python2 you may create a python3 virtualenv  and work inside it 

Inside where you clone this repo do the following 
```
python3 -m venv venv
source venv/bin/activate 
pip install -r requirements.txt
python example.py
```

@dimisdas I already explained this in previous PR, but it was dropped.

**Comment by heldausberlin** [comment]
Hey, yurilaaziz, thanks a lot. That is helpful! I was getting crazy about it.

**Comment by yurilaaziz** [comment]
@heldausberlin glad to here that it works for you. 
please close this issue as it's not needed anymore

**Comment by dimisdas** [comment]
@yurilaaziz saves the day! Closed 🥇

**Comment by heldausberlin** [comment]
Since the latest update of instabot it stops with
```
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/home/pi/instabot/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/pi/instabot/src/instabot.py", line 35
    python_version_test = f"If you are reading this error, you are not running Python 3.6 or greater. Check 'python --version' or 'python3 --version'."
```
But the latest version of python3 I can install is 3.5.3-1. How can I get 3.6?

**Comment by dimisdas** [comment]
Which Linux flavor are you using? Post output of “uname -a”

**Comment by heldausberlin** [comment]
`Linux Pi 4.14.79+ #1159 Sun Nov 4 17:28:08 GMT 2018 armv6l GNU/Linux`

**Comment by yard91** [comment]
I cannot run it too on raspberryPi3+

**Comment by dimisdas** [comment]
Raspberry does not ship with Python 3.6 or above AFAIK.

Take a look at this guide:
https://gist.github.com/SeppPenner/6a5a30ebc8f79936fa136c524417761d

You’ll have to compile from source and use altinstall. Then, you can use python3.7 or pip3.7

**Comment by Iiviin** [comment]
Worked for me, Thanks!

**Comment by olaims** [comment]
> 
> 
> Raspberry does not ship with Python 3.6 or above AFAIK.
> 
> Take a look at this guide:
> https://github.com/instabot-py/instabot.py/wiki/Raspberry-Pi-Python-3.7---Read-This
> 
> You’ll have to compile from source and use altinstall. Then, you can use python3.7 or pip3.7

I'm trying that without success on a Pi3 :(

**Comment by cala095** [comment]
hello guys, when i run: 
`sudo pip3.7 install -e .`
i get 

>pip is configured with locations that require TLS/SSL hower the ssl module in Python is not available
and other lines of errors of the pi3 retrying

I've spent 3 days trying to make this work i'm getting mad over it, i'm using a raspberry pi3.

**Comment by cala095** [comment]
> pip is configured with locations that require TLS/SSL hower the ssl module in Python is not available

ok so apparently my problem is related to my version of debian "jessie"

**Comment by cala095** [comment]
Guys i did it! i updated my pi3 to stretch, installed python3.7.2, runned instabot and it worked!
