### ISSUE TITLE
[Feature Request] Avoid repetitions while commenting or re-following the unfollowers

### ISSUE THREAD

**Issue by murlikanne** [instabot-py/instabot.py#1892]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

It's great to remove repetitions to avoid miscommunication and avoid guilt while using the bot

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by murlikanne** [comment]
> good feature

Yeah, would be greatly useful

**Comment by cliftonscott** [comment]
Agreed.

**Comment by waynoedm** [comment]
Agreed. I have had a nastygram telling me to stop following and unfollowing a guy as I had done it a few times to him. When the bot unfollows someone, it would be good idea to have list that user in a "Do Not Disturb" database that it could check against when following a new user.

**Comment by murlikanne** [comment]
@dimisdas

**Comment by nickgryg** [comment]
This is already implemented in last versions of instabot-py. It will never follow a user who was followed before by it. Of course, if we always use the same local database for it.
