### ISSUE TITLE
Add setup.py and package it in Python Pypi

### ISSUE THREAD

**Issue by yurilaaziz** [instabot-py/instabot.py#1893]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

## Description of your issue
It's great to add setup.py and package it in pypi. to let anyone use this project as a package from pypi ``` pip install instabot-py ```
``` pip install git+https://github.com/instabot-py/instabot.py```

**Comment by yurilaaziz** [comment]
@dimisdas  I could help with this if you didn't already started in it

**Comment by dimisdas** [comment]
Hey @yurilaaziz, any help would be greatly appreciated because I'm swamped with work this week.

If you want to get it started, fork and pull and I'll create a new branch so we can test it out.

Thanks!

**Comment by yurilaaziz** [comment]
I am working on it

**Comment by yurilaaziz** [comment]
@dimisdas  https://github.com/instabot-py/instabot.py/pull/1930
this repo still needs another work to be more pretty on pypi

**Comment by yurilaaziz** [comment]
Should I work for travis ci ?

**Comment by ashlardev** [comment]
@yurilaaziz if you need help with this, i will gladly assist in any way I can!
