### ISSUE TITLE
response 400 on comment, not in auto mode

### ISSUE THREAD

**Issue by lukakostic** [instabot-py/instabot.py#1897]
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [X] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X] 3.x

## Description of your issue

bot.comment status response is 400 (malformed request), instead of 200 which would be a successful one.
It does login , response 400, logs out.

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from src import InstaBot
bot = InstaBot(login="",password="") #it successfully logs in with real info
bot.comment('BsgPXdfnyQP','Queen')
```

**Comment by lukakostic** [comment]
How do i get the id?

**Comment by DarkSuniuM** [comment]
> How do i get the id?

Can u tell my what exactly are u trying to do?
Just add `?__a=1` at the end of the post link
Like https://www.instagram.com/p/BOEkjjxgxTR/ will became https://www.instagram.com/p/BOEkjjxgxTR/?__a=1

It will return a JSON now, u can get the id from there

**Comment by lukakostic** [comment]
Well im just trying to leave a comment on a post (by url) so i guess ill need to make a thing to get the id from url automatically

**Comment by DarkSuniuM** [comment]
Well it depends, there is already a methods defined for that purpose, It can get media id of the posts by tag or recent feed

**Comment by lukakostic** [comment]
Im using this as a part of a bigger bot, with ui made in c# and i tried the way of automating an embedded chromium browser but cant get javascript to fill the comment textarea so ill have to call the python script to comment certain text onto a certain post (given the url) so im pretty much just using this to comment, not other automation features such as searching by tag and getting from feed

**Comment by lukakostic** [comment]
In fact ill probably strip the code to just have the commenting

**Comment by DarkSuniuM** [comment]
You can use `new_auto_mode_comments` method instead of `new_auto_mode` to do that

**Comment by lukakostic** [comment]
What exactly does that do? Im not using new_auto_mode , just bot.comment

**Comment by DarkSuniuM** [comment]
> What exactly does that do? Im not using new_auto_mode , just bot.comment

Starts to automatically comment based on given tags

**Comment by lukakostic** [comment]
What do you mean by tag? Im provided just the url, eg instagram.com/p/BsgPXdfnyQP

**Comment by DarkSuniuM** [comment]
Also there is a better option for you, Instead of using this library u can use 
https://github.com/ping/instagram_private_api
or
https://github.com/LevPasha/Instagram-API-python

This library has a purpose, but the Instagram API libraries are general purpose and u I guess u can do what you wanna do easier using them

**Comment by lukakostic** [comment]
Do they work with user + pass or do i need the api key? Do they also accept proxy like this one?

**Comment by DarkSuniuM** [comment]
> Do they work with user + pass or do i need the api key? Do they also accept proxy like this one?

They work with User/Pw, no API Key needed, I guess they accept proxy, even if they dont on a Unix-like/Unix-Based os you can provide proxy to them using environment variables, So the proxy is not really important, but since you are using C# I assume you are writing a program for Windows, No idea about it

**Comment by lukakostic** [comment]
yes
