### ISSUE TITLE
Challenge required at ... don't accept number

### ISSUE THREAD

**Issue by wjohnw** [instabot-py/instabot.py#1903]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
When i try add Enter the code sent to your mail/phone its always end up with : 
```
Include the contents of the error.log here (if applicable).
14.01.2019_13:08 Entered code is wrong, Try again later!
14.01.2019_13:08 Exit Program... GoodBye

```

## Config
Python 3.5
Ubuntu 16.04

**Comment by DarkSuniuM** [comment]
Your account is stuck in a challenge loop, there is no guaranteed method to get this fixed, 

Still you can try this methods:
- Use a private proxy
- Login to your account using your browser and retry
- Stop using this account for a while ( maybe a day or even more )

**Comment by wjohnw** [comment]
Ok, i will try. When i need add code i need added in browser on in console? 
Thank you

**Comment by wjohnw** [comment]
But It weird this number was not accepted not even one time, and i had correct number.

**Comment by yahgiggle** [comment]
you add the code to your console then hit enter

**Comment by wjohnw** [comment]
Always replay WRONG CODE.

**Comment by wjohnw** [comment]
In the post for a challenge, you are not sending rollout_hash. `clg.headers.update({'x-instagram-ajax': rollout_hash})`
But even after this getting 400 response.
