### ISSUE TITLE
Python v3.5 or above required Instaloader

### ISSUE THREAD

**Issue by remyx11** [instabot-py/instabot.py#1905]
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
- [X] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X] 3.x

## Description of your issue

Hi,

I was using an old version of Instabot for a long time, but since everything changed and I got lost in the code I decided to redownload the latest version and start from scratch.

But i've came across a new error. It keeps saying I don't have the latest version of Python which I clearly do. What is the solution for this problem?

```
Python v3.5 or above required for Instaloader module at the moment. Exiting...
Exit status: 0
```

**Comment by dimisdas** [comment]
While you may _have installed_ the latest version of python, are you sure you are using it when running the script?

Some installations keep both Python 2 and 3, and you have to use `python3 example.py` explicitly. 

Else, you could check yourself by running `python --version`

**Comment by remyx11** [comment]
Oke, did all of the above and checked the thread of #1876, i've got a new error now.

`Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/Remy/Desktop/instabot.py-master/src/instabot.py", line 216, in __init__
    fake_ua = UserAgent()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached`

**Comment by DarkSuniuM** [comment]
Ok now u have to upgrade all the requirements to the latest version
If you're using `python` then `python -m pip install -r requirements.txt` should get the job done,
If you're using `python3` then `python3 -m pip instlal -r requirements.txt` should work

**Comment by remyx11** [comment]
Did python3, it says the following (all has been up to date i think);

```
iMac-van-Remy:instabot.py-master Remy$ python3 -m pip install -r requirements.txt -U
Requirement already up-to-date: requests in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (2.21.0)
Requirement already up-to-date: fake-useragent in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (0.1.11)
Requirement already up-to-date: instaloader in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from -r requirements.txt (line 3)) (4.2)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->-r requirements.txt (line 1)) (2018.11.29)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->-r requirements.txt (line 1)) (2.8)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests->-r requirements.txt (line 1)) (1.24.1)
```

**Comment by dimisdas** [comment]
I see you're on a Mac. Did you install Python through the .pkg file?

Try the following,
`pip3 install certifi`

Then head to `/Applications/Python\ 3.*/` and run `Install\ Certificates.command`

**Comment by remyx11** [comment]
I think i did. Certifi install worked. However `/Applications/Python\ 3.6 /` keeps saying that there isn't such file. But I can see its right there in Finder. (A folder called Python 3.6)

**Comment by dimisdas** [comment]
Yeah, just head to the folder using Finder and double click on the command

**Comment by remyx11** [comment]
Haha that makes sense. 

Thanks guys, it worked!

**Comment by dimisdas** [comment]
Take care! 🤸‍♀️ 👊

**Comment by sepehr-alipour** [comment]
use this commands
sudo apt-get install python3-dev libffi-dev libssl-dev -y
wget https://www.python.org/ftp/python/3.6.3/Python-3.6.3.tar.xz
tar xJf Python-3.6.3.tar.xz
cd Python-3.6.3
./configure
make
sudo make install
sudo pip3 install --upgrade pip

and then
do it : 
python3.6 -m pip install instabot-py
