### ISSUE TITLE
How to stop unfollow of previous followed person

### ISSUE THREAD

**Issue by neolamb93** [instabot-py/instabot.py#1906]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

Hi

I've tried to find this but i'm unable.
My previous bot was working on an older version and never had the issue, but since the last update, the bot is unfollowing anyone, even if they were followed before the start of the bot.

Does this mean that i have to add all my previous followed to the whitlist, or is it possible to make the bot only unfollow the ones that the bot has followed ?

Also the unfollow time (5*3600) seems to not be working, but i see that this is normal in mode 0 i think.

Thanks

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="",
    password="",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=['swissrider', 'swisshorse', 'swisshorses', 'swissriders', 'horsesofinstagrsm', 'horseofinstagram', 'csibasel', 'rolexgrandslam', 'showjumping', 'sautdobstacles'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=991,
    follow_time=5 * 3600,
    unfollow_per_day=991,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

```

**Comment by cerber717** [comment]
you do realize you passed your password here ?

**Comment by neolamb93** [comment]
> you do realize you passed your password here ? 🤦‍♂️

Well, that's done....

Thanks, changed !

**Comment by Massimosso** [comment]
Same. I hate this function.. the bot stop to follow my friends. I can’t use the unfollow function 😓

**Comment by yahgiggle** [comment]
16.01.2019_15:48 Getting user info : keeliagrace
16.01.2019_15:48 Checking user info..
16.01.2019_15:48 Follower : 21146
16.01.2019_15:48 Following : 6671
16.01.2019_15:48 Media : 1029
16.01.2019_15:48    >>>This is probably Selebgram account
16.01.2019_15:48    >>>This user is active
16.01.2019_15:48    >>>This account is following you
16.01.2019_15:48    >>>You are following this account
16.01.2019_15:48 keeliagrace
16.01.2019_15:48 Unfollowed: 1780787880 #1.

ok so keeliagrace is one of my friends real friends the problem is i don't want the bot to unfollow them but the but unfollow them oO

**Comment by yahgiggle** [comment]
i ran the new repo as a clean install in a new folder 
i then tried mode e and the cmd repeated this 
Wrong mode!
Wrong mode!
Wrong mode!
Wrong mode!
Wrong mode!
Wrong mode!
Wrong mode!
Wrong mode!
Wrong mode!
Wrong mode!
Wrong mode!
Wrong mode!

**Comment by dimisdas** [comment]
Run on mode 0. Make sure to set the new options.

**Comment by yahgiggle** [comment]
if  keeliagrace =  following AND User = following then do nothing else if not following remove

**Comment by yahgiggle** [comment]
> Run on mode 0. Make sure to set the new options.

it was set to mode 0 the first time with no options changes from your default, thanks for your time BTW i know a little code so i know how this can be lol  im java, lua, html, i guess i should learn python now its all much the same anyway oO

**Comment by dimisdas** [comment]
What you are suggesting is unrelated to what the OP of this issue submitted.

If you’d like, you could change the unfollow conditions directly on the class and remove “Selebgram”, or submit a feature request to add it as an additional option.

The changes in the new branch are meant to optionally stop the bot from unfollowing your current following base, and also enforce the follow_time setting.

**Comment by yahgiggle** [comment]
maybe getting mixed up a little, the OP did talk about adding users to the whitelist because its the bot is now unfollowing anyone, even if they were followed before the start of the bot. 

seems to me we are talking about the same problem

**Comment by dimisdas** [comment]
Unfortunately no.

> if keeliagrace = following AND User = following then do nothing else if not following remove

That’s an inclusive disjunction that results in the exclusion of an action. Meaning if both constituent statements are true (using AND), the user won’t be unfollowed.

Currently the bot functions in another way, checking and deciding based on the following,

- is the account “selebgram” **OR**
- is the account not following us back

If any of the above is true, the user will be unfollowed.

Yet, the original issue brought forth — unfollowing people not followed by the bot — which was done by means of scanning the recent feed, is mitigated by an additional option.

I wouldn’t oppose a feature request for variable unfollow criteria support. But it’s clearly a separate issue.

**Comment by yahgiggle** [comment]
i get what your saying i guess the problem is how it removes selebgram accounts even if that account was added to your follow list before you started using instabot, i see how you see that as a driffent problem oO

**Comment by dimisdas** [comment]
With the unfollow_recent_feed option set to False it won’t anymore 🖖💁‍♂️

Just make sure to delete your .db file or remove the users.

**Comment by dimisdas** [comment]
Could you set your example.py without the username and password?

**Comment by neolamb93** [comment]
Hi, on my side everything seems working. I've modified as you said before. It's been runing for 3h, and for the moment it didnt unfollow anyone (because of the 5h wait) I will get back at you if i see any of mine disapear.

Thanks !

**Comment by dimisdas** [comment]
Same on my side. Will make a pull request. Let me know if any issues occur in the meantime.

**Comment by dimisdas** [comment]
https://github.com/instabot-py/instabot.py/pull/1913

**Comment by oh2thirteen** [comment]
@dimisdas do you mean if unfollow_recent_feed is false the bot unfollow only people who dont follow me ?? 
and in which data you make the config?
 igot no example.py only config.ini data where i can see the config things like unfollow_recent_feed.
