### ISSUE TITLE
CSRF token 

### ISSUE THREAD

**Issue by mehisn** [instabot-py/instabot.py#1907]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [x] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
When i'm running the script I get an error:

Traceback (most recent call last):
  File "/home/pi/Desktop/Scripts/instabot.py-master/src/instabot.py", line 291, in __init__
    self.login()
  File "/home/pi/Desktop/Scripts/instabot.py-master/src/instabot.py", line 449, in login
    self.s.cookies['csrftoken'] = self.csrftoken
AttributeError: 'InstaBot' object has no attribute 'csrftoken'

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config
python3 -v
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 

pip3 show pip
Name: pip
Version: 18.1

Requirements were all installed.

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by mehisn** [comment]
Hello,

It seems that there was a configuration problem and now this issue is irrelevant. 

Another issue appeared. 

Everything else is the same as stated previous. 


14.01.2019_19:48 Checking for updates...
14.01.2019_19:48 You are running the latest stable version
14.01.2019_19:48 Instabot v1.2.1/0 started at 14.01.2019 19:48:
14.01.2019_19:48 Trying to login as 
14.01.2019_19:49 Login error! Check your login data!
14.01.2019_19:49 Exit Program... GoodBye
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x75c6a0c0>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x75c6a0c0>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x75c6a0c0>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable

**Comment by mehisn** [comment]
Hello,

The problem is fixed.

At first I did use e-mail for login process, then I've changed it to username which randomly seems to work. 

Did I miss something that it's not allowed to use e-mail for login? 

Kind regards

**Comment by DarkSuniuM** [comment]
> Hello,
> 
> It seems that there was a configuration problem and now this issue is irrelevant.
> 
> Another issue appeared.
> 
> Everything else is the same as stated previous.
> 
> 14.01.2019_19:48 Checking for updates...
> 14.01.2019_19:48 You are running the latest stable version
> 14.01.2019_19:48 Instabot v1.2.1/0 started at 14.01.2019 19:48:
> 14.01.2019_19:48 Trying to login as
> 14.01.2019_19:49 Login error! Check your login data!
> 14.01.2019_19:49 Exit Program... GoodBye
> Exception ignored in: <function WeakValueDictionary.**init**..remove at 0x75c6a0c0>
> Traceback (most recent call last):
> File "/usr/lib/python3.5/weakref.py", line 117, in remove
> TypeError: 'NoneType' object is not callable
> Exception ignored in: <function WeakValueDictionary.**init**..remove at 0x75c6a0c0>
> Traceback (most recent call last):
> File "/usr/lib/python3.5/weakref.py", line 117, in remove
> TypeError: 'NoneType' object is not callable
> Exception ignored in: <function WeakValueDictionary.**init**..remove at 0x75c6a0c0>
> Traceback (most recent call last):
> File "/usr/lib/python3.5/weakref.py", line 117, in remove
> TypeError: 'NoneType' object is not callable

This one is a bug in Python, try to use a different version of Python

**Comment by DarkSuniuM** [comment]
> Hello,
> 
> The problem is fixed.
> 
> At first I did use e-mail for login process, then I've changed it to username which randomly seems to work.
> 
> Did I miss something that it's not allowed to use e-mail for login?
> 
> Kind regards

Yeah we did mention about that on README.md
