### ISSUE TITLE
json.decoder.JSONDecodeError: Unterminated string starting at:

### ISSUE THREAD

**Issue by husligc** [instabot-py/instabot.py#1908]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
ever since the code fix for "edge media error", we have been experiencing the following error randomly.

I don't have the actual error.log but the error message is the following.
This is an example of the like/comment that works then after so many of them the bot dies with the following messages. I have included errors from two different runs.

14.01.2019_10:17 Get Media by tag: xxxxxxxxxxxx
14.01.2019_10:17 Removing already liked medias..
14.01.2019_10:17 Trying to like media: 19393948584017117033
14.01.2019_10:17 Liked: 1956748584017117033. Like instabot-py#12.
14.01.2019_10:17 Trying to comment: 1956748322224232493
14.01.2019_10:17 Write: "jf;ljafljfafj;lajfl;afjl;fjl ?". instabot-py#8.
14.01.2019_10:18 Trying to like media: 1956747672228064722632
14.01.2019_10:18 Liked: 1956747672228064722632. Like instabot-py#13.

Traceback (most recent call last):
File "myfilename", line 63, in 
bot.new_auto_mod()
File "C:\Users\user\Downloads\blankedout\src\instabot.py", line 901, in new_auto_mod
self.new_auto_mod_comments()
File "C:\Users\user\Downloads\blankedout\src\instabot.py", line 1018, in new_auto_mod_comments
and self.check_exisiting_comment(self.media_by_tag[0]['node']['shortcode']) == False:
File "C:\Users\user\Downloads\blankedout\src\instabot.py", line 1043, in check_exisiting_comment
all_data = json.loads(re.search('window.sharedData = (.?);', check_comment.text, re.DOTALL).group(1))['entry_data']['PostPage'][0] #window._sharedData = (.?);
File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json_init.py", line 354, in loads
return _default_decoder.decode(s)
File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 355, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 18183 (char 18182)
14.01.2019_10:20 Logout: likes - 13, follow - 0, unfollow - 0, comments - 8.
14.01.2019_10:20 Bot work time: 0:20:54.270379
14.01.2019_10:20 Logout success!

I restart the bot and it will run for a random number of likes / comments and die again.
Note the column number of the unterminated string is always different.

Traceback (most recent call last):
File "myfilename", line 63, in 
bot.new_auto_mod()
File "C:\Users\user\Downloads\blankedout\src\instabot.py", line 901, in new_auto_mod
self.new_auto_mod_comments()
File "C:\Users\user\Downloads\blankedout\src\instabot.py", line 1018, in new_auto_mod_comments
and self.check_exisiting_comment(self.media_by_tag[0]['node']['shortcode']) == False:
File "C:\Users\user\Downloads\blankedout\src\instabot.py", line 1043, in check_exisiting_comment
all_data = json.loads(re.search('window.sharedData = (.?);', check_comment.text, re.DOTALL).group(1))['entry_data']['PostPage'][0] #window._sharedData = (.?);
File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json_init.py", line 354, in loads
return _default_decoder.decode(s)
File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 355, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 12180 (char 12179)
14.01.2019_12:51 Logout: likes - 53, follow - 0, unfollow - 0, comments - 34.
14.01.2019_12:51 Bot work time: 1:29:40.872635
14.01.2019_12:51 Logout success!
```

## Config

```
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
      login="loginame",
    password="password",
    database_name="databasename.db",
    like_per_day=900,
    comments_per_day=565,
    tag_list=['name1', 'name2','name3','name4','name5’,'name6','name7','name8'],
    tag_blacklist=['sex', 'porn'],
    user_blacklist={},
    max_like_for_one_tag=1400,
    follow_per_day=0,
    follow_time=1 * 60,
    unfollow_per_day=0,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["Wow example1", "wow example 2", "wow example3", "wow example4", "wow example 5", "wowexmple 6"],
                  ["??", "?", "?!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'porn'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

```

**Comment by dimisdas** [comment]
Instagram changed their comments structure recently. Do you have a shortcode (link) perhaps of a post it's trying to comment where it's failing?

**Comment by husligc** [comment]
Is this what your asking for?

14.01.2019_18:49 Write: " message  ?". #7.
14.01.2019_18:50 Trying to like media: 1956633610868785723
14.01.2019_18:50 Liked: 1956633610868785723. Like #11.
14.01.2019_18:50 Get Media by tag: nametagex
14.01.2019_18:50 Removing already liked medias..
14.01.2019_18:51 Trying to like media: 1957001532558635127
14.01.2019_18:51 Liked: 1957001532558635127. Like #12.
Traceback (most recent call last):
  File "myname", line 63, in <module>
    bot.new_auto_mod()
  File "C:\Users\user\Downloads\mybot\src\instabot.py", line 901, in new_auto_mod
    self.new_auto_mod_comments()
  File "C:\Users\user\Downloads\mybot\src\instabot.py", line 1018, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['shortcode']) == False:
  File "C:\Users\user\Downloads\mybot\src\instabot.py", line 1043, in check_exisiting_comment
    all_data = json.loads(re.search('window._sharedData = (.*?);', check_comment.text, re.DOTALL).group(1))['entry_data']['PostPage'][0] #window._sharedData = (.*?);
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 9839 (char 9838)
14.01.2019_18:51 Logout: likes - 12, follow - 0, unfollow - 0, comments - 7.
14.01.2019_18:51 Bot work time: 0:18:20.186671
14.01.2019_18:51 Logout success!

thanks for the assistance!

**Comment by dimisdas** [comment]
Could you replace instabot.py with this [instabot.py](https://gist.github.com/dimisdas/9a31cfdd1ea9c06c6b2d425791dcbd1a), it will print the URL it's trying to check and will help debug.

**Comment by husligc** [comment]
I ran your version that you gave me and found something very interesting.
If you look at the first url after the "Checking for existing comments" that link exists but
the second one doesn't and then it dies.  Could that be the issue that we are trying to comment on a record that doesn't actually exist any longer or isn't active?   Thanks very much for you help!!!!

14.01.2019_23:05 Get Media by tag: travelblog
14.01.2019_23:05 Removing already liked medias..
14.01.2019_23:05 Trying to like media: 1957135167346526002
14.01.2019_23:05 Liked: 1957135167346526002. Like #5.
14.01.2019_23:05 Checking for existing comments at **https://www.instagram.com/p/BspI7eElTd2/**
14.01.2019_23:05 Trying to comment: 1957134784179550070
14.01.2019_23:05 Write: "How did you decide to go there? what are your tips? follow for follow ?!". #4.
14.01.2019_23:06 Trying to like media: 1957133365624045333
14.01.2019_23:06 Liked: 1957133365624045333. Like #6.
14.01.2019_23:08 Checking for existing comments at **https://www.instagram.com/p/BrtYjm2A9S0/**
Traceback (most recent call last):
  File "moldingf", line 63, in <module>
    bot.new_auto_mod()
  File "C:\Users\user\Downloads\MyTestBot\src\instabot.py", line 905, in new_auto_mod
    self.new_auto_mod_comments()
  File "C:\Users\user\Downloads\MyTestBot\src\instabot.py", line 1022, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['shortcode']) == False:
  File "C:\Users\user\Downloads\MyTestBot\src\instabot.py", line 1048, in check_exisiting_comment
    all_data = json.loads(re.search('window._sharedData = (.*?);', check_comment.text, re.DOTALL).group(1))['entry_data']['PostPage'][0] #window._sharedData = (.*?);
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 16023 (char 16022)
14.01.2019_23:08 Logout: likes - 6, follow - 0, unfollow - 0, comments - 4.
14.01.2019_23:08 Bot work time: 0:11:10.781504
14.01.2019_23:08 Logout success!

C:\Users\user\Downloads\MyTestBot>

**Comment by dimisdas** [comment]
That's very interesting, and admittedly I haven't seen it happen before. 

Could you try this version of [instabot.py](https://gist.github.com/dimisdas/6bad9cd8c683f06a8bee447c0c566bd1) and see if it still crashes when trying to comment?

It should now display an error instead and resume. Let me know if it works so I can update the repo.

Thanks!

**Comment by husligc** [comment]
Your fix worked great!!! 

It displayed the message "Couldn't comment post, resuming!" .
and continued to run

Thank you so much!!!!

**Comment by dimisdas** [comment]
Cheers!
