### ISSUE TITLE
Something is wrong..Exit program... Goodbye !

### ISSUE THREAD

**Issue by Massimosso** [instabot-py/instabot.py#1910]
I'm using two different Cloud VPS online: On the first VPS all running good, but on the second VPS I can't login with any account. I've tried with more account, but I've always this error...

Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. 

## Hosting
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [X] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X] 3.x

## Description of your issue

```
root@BotIn:~# python3 unk.py
16.01.2019_00:48 Checking for updates...
16.01.2019_00:48 You are running the latest stable version
16.01.2019_00:48 Instabot v1.2.1/0 started at 16.01.2019 00:48:
16.01.2019_00:48 Trying to login as unknownarti...
16.01.2019_00:48 Something wrong with login
16.01.2019_00:48 {"errors": {"error": ["Sorry, there was a problem with your request."]}, "status": "ok", "error_type": "generic_request_error"}
16.01.2019_00:48 Something is wrong with Instagram! Please try again later...
16.01.2019_00:48 Error => Sorry, there was a problem with your request.
16.01.2019_00:48 Exit Program... GoodBye

```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by murlikanne** [comment]
#1891

**Comment by Massimosso** [comment]
@murlikanne thanks, but there is not a solution 😥

How did u solve it? I've been waiting for 24 hours already
