### ISSUE TITLE
Can't use mode 4

### ISSUE THREAD

**Issue by rajch3** [instabot-py/instabot.py#1911]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. 

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux
- [ ] Android
mate 19.1
## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
Traceback (most recent call last):
  File "example.py", line 103, in <module>
    feed_scanner(bot)
  File "/home/che/Desktop/instabot.py-master/src/feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "/home/che/Desktop/instabot.py-master/src/likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "/home/che/Desktop/instabot.py-master/src/likers_protocol.py", line 20, in likers_protocol
    if self.media_by_user[self.current_index]["likes"]["count"] >= 10 \
KeyError: 'likes'
I get this error when i try mode 4.
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < #!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="",
    password="",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=[ 'l:224902394','l:590922014','l:741328593','l:42578247','l:221058090','l:734621568','l:461132937','l:1020387645','l:236102187','l:216921375','l:236090044','l:252488589','l:1111076','l:769929','l:215944043','l:1022125622', 'l:513625776','l:224732301','l:279948431','l:170816656832059','l:252094885','l:258690785','l:256187464','l:235484247','l:10070947','l:1022331213','l:1630513','l:359152783','l:235603087','l:393254340','l:332145947172746','l:235507215', 'l:1747254395493252', 'l:215684389', 'l:192801', 'l:1020206518', 'l:33752352', 'l:215471115', 'l:217958846', 'l:4536000', 'l:537372600', 'l:1026762035', 'l:943515679', 'l:1803989769717503', 'l:1807054192905770',],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 4

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        bot.bot_mode = 3
        while(bot.login_status == 1):
            bot.unfollow_recent_feed()
            time.sleep(5)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")
```

**Comment by dimisdas** [comment]
I cannot wrap my head around mode 4. Could anyone explain to me its purpose?

> FOLLOW USERS BASED ON RECENT FEED ONLY

Isn't the recent feed already comprised of people you follow?

**Comment by yahgiggle** [comment]
> I cannot wrap my head around mode 4. Could anyone explain to me its purpose?
> 
> > FOLLOW USERS BASED ON RECENT FEED ONLY
> 
> Isn't the recent feed already comprised of people you follow?

i think well how i understand it, mode 4 will only follow users who have posted something recently, and ignoring anything else

**Comment by dimisdas** [comment]
> i think well how i understand it, mode 4 will only follow users who have posted something recently, and ignoring anything else

After reading the code, I'm not confident in that interpretation.

**Comment by yahgiggle** [comment]
> > i think well how i understand it, mode 4 will only follow users who have posted something recently, and ignoring anything else
> 
> After reading the code, I'm not confident in that interpretation.

well what else do they mean by it oO FOLLOW USERS BASED ON RECENT FEED ONLY <---- that to me says, only follow users who have posted something recently, and ignoring anything else,  if it means something else then who ever made that needs to explain more oO

**Comment by petaeventos** [comment]
I have the same problem. >> KeyError: 'likes' << Anyone can help us? Thanks!!

**Comment by dimisdas** [comment]
> I have the same problem. >> KeyError: 'likes' << Anyone can help us? Thanks!!

What exactly are you trying to achieve with mode 4?

**Comment by petaeventos** [comment]
> > I have the same problem. >> KeyError: 'likes' << Anyone can help us? Thanks!!
> 
> What exactly are you trying to achieve with mode 4?

I'm trying to get the bot follow accounts with the same kind of pictures as my feed with my users followed. Sorry my english isn't good

**Comment by petaeventos** [comment]
> > I have the same problem. >> KeyError: 'likes' << Anyone can help us? Thanks!!
> 
> What exactly are you trying to achieve with mode 4?

I have been trying to change the word "likes" and the KeyError has changed to the word that I changed.

**Comment by dimisdas** [comment]
> that to me says, only follow users who have posted something recently, and ignoring anything else

Well, mode 0 does the same thing and likes/comments/follows (depending on your options; each could be set to zero). 

> I'm trying to get the bot follow accounts with the same kind of pictures as my feed with my users followed.

The bot cannot do analysis of your photos or the photos in your feed. Check manually, learn your audience, find the right hashtags, and fine-tune the bot.

<img src="https://imgs.xkcd.com/comics/tasks_2x.png" width="300" />

Modes will probably cease to exist in future versions of the bot in favour of more options in auto mod. More options will yield similar behaviours, and even combinations.

**Comment by petaeventos** [comment]
> > eso me dice, solo sigue a los usuarios que han publicado algo recientemente, e ignorando cualquier otra cosa
> 
> Bueno, el modo 0 hace lo mismo y le gusta / comentarios / sigue (dependiendo de sus opciones; cada uno podría establecerse en cero).
> 
> > Estoy tratando de hacer que el bot siga las cuentas con el mismo tipo de imágenes que mis seguidores con mis usuarios seguidos.
> 
> El bot no puede hacer un análisis de tus fotos o las fotos en tu feed. Comprueba manualmente, aprende a tu audiencia, encuentra los hashtags correctos y ajusta el bot.
> 
> <img alt="" width="300" src="https://camo.githubusercontent.com/bafa540210b7169b76fa35c406d38ba8415785b7/68747470733a2f2f696d67732e786b63642e636f6d2f636f6d6963732f7461736b735f32782e706e67">
> 
> Los modos probablemente dejarán de existir en futuras versiones del bot a favor de más opciones en la modificación automática. Más opciones producirán comportamientos similares, e incluso combinaciones.

Thanks for your time!! Thanks
