### ISSUE TITLE
how to get list of "close friends"

### ISSUE THREAD

**Issue by rzettler** [instabot-py/instabot.py#1918]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem. 

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x ] Windows
- [x ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x ] 3.x

## Description of your issue

```
Does anybody have code to retrieve the newly introduced "close friends" list? Any help welcome. Thanks.

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```n/a

## Config

```n/a
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```n/a

**Comment by dimisdas** [comment]
Hello,

Instabot, as the name suggests, is a bot framework and not a scrapper or general API wrapper. Unfortunately this feature is not currently planned to be supported. Thanks!

**Comment by rzettler** [comment]
Hi, but wouldn't it be good to have a subroutine to get the closed friends list ... e. g. if you unfollow users you could exlude those who are in the "close friends" list ... just as one idea

**Comment by dimisdas** [comment]
Instabot uses the web version of Instagram, which does not currently return in its JSON response if the user is a close friend.
