### ISSUE TITLE
Error on both example.py and run.py on first start

### ISSUE THREAD

**Issue by flagdizero** [instabot-py/instabot.py#1919]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem. 

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [ x] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x ] 3.x

## Description of your issue
I got first error when i run run.py, the second when i run example.py. I didnt make any change to code, only username and password. Yes i installed the requirements

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
File "run.py", line 201
    confvar = input(f"Enter value for '{setting}' (Required): ")
                                                              ^
SyntaxError: invalid syntax

------------------------

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/home/pi/instabot.py/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/pi/instabot.py/src/instabot.py", line 83
    f"Cannot continue without module {modname} Please install dependencies in requirements.txt. Exiting."
                                                                                                        ^
SyntaxError: invalid syntax

**Comment by dimisdas** [comment]
Added an f-string at the top of both files. It should cause a syntax error explaining more appropriately to the user that he is not running Python < 3.6.

https://github.com/instabot-py/instabot.py/commit/5faaa9a960fdfe06a6cad7fddeaf0a42bf39c715
