### ISSUE TITLE
Max retries exceeded with url

### ISSUE THREAD

**Issue by davidwaite** [instabot-py/instabot.py#192]
Im getting this when i try to log in... been working fine until today.  I run a few account off this computer with pretty standard settings ie.. < 850 likes etc

`
Traceback (most recent call last):
  File "example.py", line 16, in <module>
    log_mod=0)
  File "/var/instabot.py-master/instabot.py", line 151, in __init__
    self.login()
  File "/var/instabot.py-master/instabot.py", line 174, in login
    r = self.s.get(self.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by <class 'socket.error'>: [Errno 113] No route to host)
`

**Comment by polaroi8d** [comment]
There are any new instagram account? All your account get this message? Which OS do you use?

**Comment by davidwaite** [comment]
I'm running this on Linux Mint 17.3 ... This was happening on an IP at work where i was running more than 7-10 accounts.  I then took it home and ran the same accounts on another IP and it worked fine.  Which tells me the accounts were fine, but maybe Instagram is throttling IPs or something.

Would they throttle or limit request from api calls that aren't authenticated with access tokens??  Makes me second question how many accounts to run on a single IP

**Comment by LevPasha** [comment]
@davidwaite have no idea. Test it and give us this answer...

**Comment by ChipWolf** [comment]
I think what we've learned here is that we need to add connectivity checking to the remote host before making requests or on errors.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
