### ISSUE TITLE
Hide story and post

### ISSUE THREAD

**Issue by Massimosso** [instabot-py/instabot.py#1921]
Is it possible to insert a function that automatically hides the stories and posts of the accounts followed by the bot?

Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. 

## Hosting
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [X] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [X] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [X] 3.x

## Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by DarkSuniuM** [comment]
I can't understand how it can be related to the Instabot?

**Comment by Massimosso** [comment]
@DarkSuniuM 

When the bot starts to follow more than 1000 accounts on your profile it's boring to see lots of posts and stories of people you do not know. 

A year ago I used a bot online that disabled the stories and posts of each individual account that followed... This made surfing on instagram much better. 

It is not essential for instabot, but I was indicating it as a possible improvement! 😊

**Comment by lukasdeang** [comment]
It would not be bad, follow this issue

**Comment by dimisdas** [comment]
Instabot uses the web version of Instagram, which does not currently expose an API endpoint to mute/unmute users.
