### ISSUE TITLE
Instabot logging out after one like when ran on nohup

### ISSUE THREAD

**Issue by serendipity1004** [instabot-py/instabot.py#1922]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. 

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [ ] Windows
- [x] Linux ubuntu 16.04
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

When I run `nohup python3 example.py &` the bot stops working after a single like and logs out. When I run it with `python3 example.py` it works fine and continues on until I stop it.

Following is my settings (I erased login and password for obvious reasons)
![2019-01-18_13-30-28](https://user-images.githubusercontent.com/20388249/51365903-051cee00-1b26-11e9-9d2f-cbab54e1849d.png)

Following is what shows at `cat nohup.py` after running.
![2019-01-18_13-36-54](https://user-images.githubusercontent.com/20388249/51365937-339ac900-1b26-11e9-819c-5fc9080a7d33.png)

I know you guys have closed this type of issue as of January this year but it seems to persist. I am pretty sure I am running the most updated version of the bot. It says v1.2.1

## Config

Following is my settings (I erased login and password for obvious reasons)
![2019-01-18_13-30-28](https://user-images.githubusercontent.com/20388249/51365903-051cee00-1b26-11e9-9d2f-cbab54e1849d.png)

**Comment by dimisdas** [comment]
Try redirecting output streams `< /dev/null > output.out 2> error.out &` and see if it works.

I'd also suggest using `screen`. It's been working for me.

**Comment by adelra** [comment]
Use Screen or tmux instead of nohup
