### ISSUE TITLE
KeyError:id

### ISSUE THREAD

**Issue by grego31430** [instabot-py/instabot.py#1926]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
root@Serveur:/# python3 --version
Python 3.6.7
```

#### Pip Version?
```
root@Serveur:/# pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
```

#### Description of your issue
I want to comment all liked post. So I have uncomment 
"comment = self.comment(self.media_by_tag[i]['id'],'cool!')"
but when I lauch bot I have this error:
```
File "/root/instabot.py-master/src/instabot.py", line 721, in like_all_exist_media
    comment = self.comment(self.media_by_tag[i]['id'],'cool!')
KeyError: 'id'
```

#### Config

```
import os
import time

from src import InstaBot

bot = InstaBot('user','pass',
                comment_list=['Sooo cute','cute cute cute','just so beautiful','fall in love','cuteeeeeee','cuuuuuuuuute','handsoooome','handsome !','I like your potato dog !','sweetie','sweeeeeeeeee$
                comments_per_day=1000)
bot.get_media_id_by_tag('dogsofinstagram')
bot.like_all_exist_media(1)
```

**Comment by dimisdas** [comment]
I don't understand what exactly you're trying to do...

> I want to comment all liked post.

All posts liked by the bot? Or ... ?

**Comment by grego31430** [comment]
Yes, when the bot like a post, I want he comment the same post

**Comment by dimisdas** [comment]
Can you show me the configuration of the bot that likes the posts?

**Comment by grego31430** [comment]
"import os
import time

from src import InstaBot

bot = InstaBot('user','pass',
                comment_list=['Sooo cute','cute cute cute','just so beautiful','fall in love','cuteeeeeee','cuuuuuuuuute','handsoooome','handsome !','I like your potato dog !','sweetie','sweeeeeeeeee$
                comments_per_day=1000)
bot.get_media_id_by_tag('dogsofinstagram')
bot.like_all_exist_media(1)"

I have just uncomment the line "comment = self.comment(self.media_by_tag[i]['id'],'cool!')"

**Comment by dimisdas** [comment]
I see. Im terribly sorry. I’m not extrapolating any meaning from this discussion. Wish I could be more helpful. 

In order to simultaneously comment all the posts you like, you’ll have to modify the script and create your own iterator using the class methods.

This is complicated, and might be beyond your current skill level. That’s okay.

You might be interested in just using the provided automod, as illustrated in the example.py. Increase the comments_per_day value, but be careful not to overdo it. Too many comments will risk getting your account suspended.

Good luck!
