### ISSUE TITLE
Feature Request : follow_min_followers / follow_max_followers / unfollow_min_followers / unfollow_max_followers

### ISSUE THREAD

**Issue by rubensben** [instabot-py/instabot.py#1927]
This is me again, I'm opening a new issue in addition to the [previous one](https://github.com/instabot-py/instabot.py/issues/1912). I'm requesting additional options in order to be able to reach only "more famous" instagram accounts by adding these 4 options :  

follow_min_account : Only follow accounts with a minimum of XX followers
follow_max_account : Only follow accounts with a maximum of XX followers
unfollow_min_account : Only unfollow accounts with maximum XX followers
unfollow_max_account : Only unfollow accounts with a minimum of XX followers

The aim is give more flexibility to A/B testing and help to reach "higher quality" instagram accounts instead of interacting with small ones. I believe it would help to find the "right formula" for everyone to gain more followers and help to reach a wider audience withing the Instagram algorithm.

BLESS

**Comment by wjohnw** [comment]
Are you working on this?

**Comment by wjohnw** [comment]
Are you working on it?

**Comment by dimisdas** [comment]
> Are you working on it?

Currently working on the pip package, the run.py executable, config.ini and a much needed refactoring of internal functions. Bot modes will be removed in favour of new options.

I don't think it's a good idea to start working on other stuff yet, so it's on hold. But we'll get back to feature requests soon and update their status.

**Comment by wjohnw** [comment]
> > Are you working on it?
> 
> Currently working on the pip package, the run.py executable, config.ini and a much needed refactoring of internal functions. Bot modes will be removed in favour of new options.
> 
> I don't think it's a good idea to start working on other stuff yet, so it's on hold. But we'll get back to feature requests soon and update their status.

HI, is possible somehow help?
Than you

**Comment by rubensben** [comment]
thank you for the user_min/max_follow implementation <3 !

**Comment by dimisdas** [comment]
Kudos to @macd2 
https://github.com/instabot-py/instabot.py/pull/1951
