### ISSUE TITLE
Login Access Failure

### ISSUE THREAD

**Issue by amitrao999** [instabot-py/instabot.py#1929]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

#### Environment
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [X] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [ ] I am using Python 3.6 or above

#### Exact Python Version?
`3.5.2`
Include here the response of 'python --version' or 'python3 --version'
`3.5.2`

#### Pip Version?
`8.1.1`
Include here the response of 'pip --version' or 'pip3 --version'
`8.1.1`

#### Description of your issue

`Unable to run the bot when I call the bot with command "python3 example.py"'

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT

``Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/home/amitrao99/instabot.py/instabot.py/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/amitrao99/instabot.py/instabot.py/src/instabot.py", line 35
    python_version_test = f"If you are reading this error, you are not running Python 3.6 or greater. Check 'python --version' or 'python3 --version'."
                                                                                                                                                      ^
SyntaxError: invalid syntax
amitrao99@instance-1:~/instabot.py/instabot.py$ `

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
`#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import time
from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol
bot = InstaBot(
    login="",
    password="",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=["follow4follow", "f4f","cute",
              "natgeo",
              "natgeo",
              "natgeoyourshot",
              "natgeohub",
              "natgeoadventure",
              "natgeotraveller",
              "natgeoexpeditions",
              "natgeotravel",
              "natowild_hd",
              "natgeoindia",
              "instatravel",
              "instaart",
              "instaphoto",
              "nikontop_",
              "nikonindia",
              "india_undiscovered",
              "india_gram",
              "india_ig",
              "india_clicks",
              "indianphotography",
              "indiaturism",
              "indiatravel",
              "India",
              "architecture",
              "architecturephotography",
              "architecturelovers",
              "naturelover",
              "nature_skyshotz",
 ],`
 tag_blacklist=["rain", "thunderstorm"],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy="",
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[
        ["this", "the", "your"],
        ["photo", "picture", "pic", "shot", "snapshot"],
        ["is", "looks", "feels", "is really"],
        [
            "great",
            "super",
            "good",
            "very good",
            "good",
            "wow",
            "WOW",
            "cool",
            "GREAT",
            "magnificent",
            "magical",
            "very cool",
            "stylish",
            "beautiful",
            "so beautiful",
            "so stylish",
            "so professional",
            "lovely",
            "so lovely",
            "very lovely",
            "glorious",
            "so glorious",
            "very glorious",
            "adorable",
            "excellent",
            "amazing",
        ],
        [".", "..", "...", "!", "!!", "!!!"],
    ],
    # Use unwanted_username_list to block usernames containing a string
    # Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    # 'free_followers' will be blocked because it contains 'free'
unwanted_username_list=[
        "second",
        "stuff",
        "art",
        "project",
        "love",
        "life",
        "food",
        "blog",
        "free",
        "keren",
        "photo",
        "graphy",
        "indo",
        "travel",
        "art",
        "shop",
        "store",
        "sex",
        "toko",
        "jual",
        "online",
        "murah",
        "jam",
        "kaos",
        "case",
        "baju",
        "fashion",
        "corp",
        "tas",
        "butik",
        "grosir",
        "karpet",
        "sosis",
        "salon",
        "skin",
        "care",
        "cloth",
        "tech",
        "rental",
        "kamera",
        "beauty",
        "express",
        "kredit",
        "collection",
        "impor",
        "preloved",
 ],
    unfollow_whitelist=["example_user_1", "example_user_2"],
)
while True:
    # print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    # print("## MODE 1 = MODIFIED MODE BY KEMONG")
    # print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    # print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    # print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    # print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")
    ################################
    ##  WARNING   ###
    ################################
    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    # USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

 mode = 0
    # print("You choose mode : %i" %(mode))
    # print("CTRL + C to cancel this operation or wait 30 seconds to start")
    # time.sleep(30)
    if mode == 0:
        bot.new_auto_mod()
    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)
    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()
    elif mode == 3:
        bot.bot_mode = 3
        while bot.login_status == 1:
            bot.unfollow_recent_feed()
            time.sleep(5)
    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)
    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)
    else:
        print("Wrong mode!")

**Comment by amitrao999** [comment]
How do I upgrade to version 3.6 or above in the Ubuntu 16.04.5 LTS (GNU/Linux 4.15.0-1026-gcp x86_64) ?

**Comment by dimisdas** [comment]
Sorry for the closed issue before, but the difference now is day and night!

Ubuntu 16.04 (Xenial) doesn't have Python 3.6 or 3.7 in their official repos as far as I remember. You should be able to download the source code and build it yourself, or use an alternative repo.

`sudo add-apt-repository ppa:deadsnakes/ppa`
`sudo apt-get update`
`sudo apt-get install python3.7`

and then run using `python3.7 example.py` (and `pip3.7 install -r requirements.txt` respectively).

**Comment by amitrao999** [comment]
Hi,

I ran the bot in Ubuntu 18.04 and it runs fine but I am getting an error when I add a proxy in the code. The format I used for the proxy is as follows:

proxy = "http://username:password@IP:PORT"

Can you please confirm if the format for the proxy to be used is correct ?

Thanks,
Amit

**Comment by joaocpereiraa** [comment]
On windowns i try to install and i got this error:

Python version 3.6.3
PIP 18.0
''
C:\Users\joaoc\Downloads\instabot.py-master>pip3 install -r requirements.txt
Requirement already satisfied: requests in c:\users\joaoc\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 1)) (2.12.4)
Requirement already satisfied: fake-useragent in c:\users\joaoc\appdata\local\programs\python\python36\lib\site-packages (from -r requirements.txt (line 2)) (0.1.10)
Collecting instaloader (from -r requirements.txt (line 3))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Uma ligação existente foi forçada a fechar pelo anfitrião remoto', None, 10054, None))': /simple/instaloader/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Uma ligação existente foi forçada a fechar pelo anfitrião remoto', None, 10054, None))': /simple/instaloader/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Uma ligação existente foi forçada a fechar pelo anfitrião remoto', None, 10054, None))': /simple/instaloader/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Uma ligação existente foi forçada a fechar pelo anfitrião remoto', None, 10054, None))': /simple/instaloader/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'Uma ligação existente foi forçada a fechar pelo anfitrião remoto', None, 10054, None))': /simple/instaloader/
  Could not find a version that satisfies the requirement instaloader (from -r requirements.txt (line 3)) (from versions: )
No matching distribution found for instaloader (from -r requirements.txt (line 3))''
