### ISSUE TITLE
following and unfollowing list

### ISSUE THREAD

**Issue by MrJur1** [instabot-py/instabot.py#193]
Hi all,
first of all, great work!
I would like to know if you can add usernames which the bot will follow and unfollow in loop?
Thanks!

**Comment by virginsince1997** [comment]
Can someone please help me out with my python

**Comment by virginsince1997** [comment]
please im getting this error help


Traceback (most recent call last):
  File "C:\Python27\example.py", line 16, in <module>
    log_mod=0)
  File "C:\Python27\instabot.py", line 151, in __init__
    self.login()
  File "C:\Python27\instabot.py", line 187, in login
    ui = UserInfo()
  File "C:\Python27\userinfo.py", line 30, in __init__
    self.hello()
  File "C:\Python27\userinfo.py", line 35, in hello
    main = self.s.get(self.url_list[self.i_a]["main"])
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

**Comment by polaroi8d** [comment]
Hello @virginsince1997 its the last pr problem i think. Just download the 7053054e3d61fe0e0c83f419269129f1e511c18b commit hash.

**Comment by MrJur1** [comment]
anyone an idea regarding my issue?!

**Comment by polaroi8d** [comment]
@MrJur1 in the instabot.py line 369 there is a follow funciton with the user_id argument, i think you can set here the user id what you want to follow, same in the unfollow function.

**Comment by MrJur1** [comment]
insert user_ids there but the bot still randome users / from hashtags?!

**Comment by dave240170** [comment]
I think the function is meant so you can follow unfollow certain users as suggested in the documentation, however when debugged got 404 error, as appeared to do nothing. I might be completely wrong as I am completely new to python.

as in;

bot = InstaBot(login="instagram", password="password") <<< try it, probably will work!
bot.follow('hello')

follow = self.s.post(url_follow)
self.write_log(follow) **** <Response [404]>

**Comment by MrJur1** [comment]
yeah but i will that the bot will follow and unfollow a list of 50 users in loop?!

**Comment by dave240170** [comment]
It would if not for the 404 on my windows 10.

**Comment by virginsince1997** [comment]
Please does anyone has a bot that likes your feed?

**Comment by drewhga** [comment]
The bot cannot lookup a username as ink361 does not provide that
information (I think). You can use third party sites such as
http://www.otzberg.net to find the user id of a particular user and then
your follow function should look like this.

bot.follow('1111111111111')

**Comment by drewhga** [comment]
You get the 404 error because no user names are found.

**Comment by mumzspahgetti** [comment]
how are you getting the bot to follow multiple users from hashtags? 
my code looks like this:

#!/usr/bin/env python
# -*- coding: utf-8 -*-

from instabot import InstaBot

bot = InstaBot(login="xxxxxx", password="xxxxxxxxxx",
               like_per_day=1000,
               media_max_like=20,
               media_min_like=0,
               comments_per_day=0,
               tag_list=['dog',],
               max_like_for_one_tag=200,
               follow_per_day=1000,
               follow_time=5*60*60,
               unfollow_per_day=0,
               unfollow_break_min=0,
               unfollow_break_max=0,
               log_mod=0)			   

bot.new_auto_mod()

It likes pictures fine but follows one user and then repeats trying to follow that user.
Any help is appreciated :)

**Comment by drewhga** [comment]
@mumzspahgetti 
I also get that problem then I noticed the culprit was
max_like_for_one_tag=200
when set to a value other than 1.
So i advise you set it to 1

**Comment by MrJur1** [comment]
so nobody can help me with me issue?

**Comment by 179skr** [comment]
Just code it in manually without the list and stick the script on a loop

**Comment by mumzspahgetti** [comment]
@drewhga 
thank you, I will try that!

**Comment by mumzspahgetti** [comment]
@drewhga 
I set the value to 1 and still does the same thing. Would it be possible to send your code so I can check if there is something wrong on my end?
Thanks.

**Comment by drewhga** [comment]
Here's my code @mumzspahgetti

#!/usr/bin/env python
# -*- coding: utf-8 -*-

from instabot import InstaBot

bot = InstaBot(login="*******", password="*******",
               like_per_day=100,
               comments_per_day=0,
               tag_list=['follow4follow','f4f'],
               max_like_for_one_tag=1,
               follow_per_day=200,
               follow_time=10*60,
               unfollow_per_day=200,
               unfollow_break_min=1,
               unfollow_break_max=30,
               log_mod=0)

bot.new_auto_mod

**Comment by mumzspahgetti** [comment]
@drewhga thank you I appreciate the help

**Comment by drewhga** [comment]
Alright. Got it running now?

**Comment by mumzspahgetti** [comment]
@drewhga No I couldn't get it running properly but I got massplanner since I need to run more accounts anyway

**Comment by drewhga** [comment]
Massplanner?. What's that

**Comment by dave240170** [comment]
I'm thinking this may make it multi user for follow / unfollow mass list;

self.s.cookies.update({'sessionid': str(uuid.uuid4()), 'mid': '', 'ig_pr': '1',

If your script occasionally closes, you can do this, runs if not already running, windows only.

@echo off
:LOOP
@For /f "Delims=:" %%A in ('tasklist /v /fi "WINDOWTITLE eq a"') do @if %%A==INFO start /min "a" python.exe a.py
TIMEOUT /T 10
@For /f "Delims=:" %%A in ('tasklist /v /fi "WINDOWTITLE eq b"') do @if %%A==INFO start /min "b" python.exe b.py
TIMEOUT /T 1000
goto :LOOP

**Comment by mumzspahgetti** [comment]
@drewhga check out their website it has heaps of helpful features! http://www.massplanner.com/instagram-poster/

**Comment by virginsince1997** [comment]
i got this error while trying to run example.py  , i just installed python 27 on my windows 7 32 bit
`Traceback (most recent call last):
  File "C:\python27\example.py", line 4, in <module>
    from instabot import InstaBot
  File "C:\python27\instabot.py", line 4, in <module>
    from userinfo import UserInfo
  File "C:\python27\userinfo.py", line 4, in <module>
    import requests
ImportError: No module named requests
`

**Comment by dave240170** [comment]
read the documentation! Its number2.

How to install and run:

1) Download and install Python to your computer.

2) Install Python lib requests. Run command pip3 install requests if you use Python 3, or type pip install requests if you use Python 2.

3) Download ZIP and extract

4) Modify example.py to your pleasing

5) Run program python3 example.py or python example.py on Mac, Linux or Windows

**Comment by virginsince1997** [comment]
@dave240170 thank you bro skipped my mind ,,, is there any way to modify the bot to like my feeds

**Comment by polaroi8d** [comment]
@virginsince1997 there is in the example.py if you read the README.md you can enable to do that.

**Comment by dave240170** [comment]
How many feeds?

**Comment by virginsince1997** [comment]
@polaroi8d okay bro , my python only runs scripts i paste in C:\Python27 , anything apart from that it doesnt , tried change environment variable to other parts in python , still dosent work ..

**Comment by virginsince1997** [comment]
@dave240170 my instagram feed ,,, automtically like the pictures posted by the people am following....

**Comment by dave240170** [comment]
In the instabot script do this;

Example

bot_follow_list=[13453356,753563676]

I've not tried it myself. You put in the id's of the instagram user and not
the actual name! This might be it, might not. Try it and let us know.

**Comment by virginsince1997** [comment]
@dave240170 id give that a try , but that i actually meant was that the got gets feeds of the pepz you follow without you declaring the user id , it just picks up pictures from your feeds and like them. like an instagram feed liker

**Comment by MrJur1** [comment]
@dave240170 
i have tried it: TypeError: __init__() got an unexpected keyword argument 'bot_follow_list'

**Comment by virginsince1997** [comment]
I need an instagram feed liker bot
, help..

**Comment by mromrell** [comment]
I love the Bot, BUT it seems be stuck in a loop, and doesn't appear to be doing much. 
**Can you explain what this code is doing and if it's actually stuck and how I can fix it?**
(I've tried operating in mode 2 and mode 4, but I get the same issue each time. Also I have a very new instagram account with just 6 posts right now.)

```
======> Get media id by Tag <======
Get media by user success!
============================== 
Upss gencfotografcl is already in ex user list... 
==============================
filmswift : Get media id on recent feed 
 01.03.2017 18:23
Except on get media!!
```

**Comment by luisramirez-m** [comment]
Hello @mromrell problem with Instagram API changes. You check this https://github.com/LevPasha/instabot.py/issues/397 and maybe this pull request https://github.com/LevPasha/instabot.py/pull/395

**Comment by mromrell** [comment]
Got it! Thanks for the help. 
Also is there a way to Copy followers of certain users?
Example, I want to follow all of the people following my competitors. is there a place I can enter in the list of competitor users, and let the bot follow followers of those competitors?

**Comment by penarubah** [comment]
@mromrell maybe you can check @ohld script at `https://github.com/instagrambot/instabot`
it inspire from this script and have follow followers script.

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
