### ISSUE TITLE
Following Similar accounts

### ISSUE THREAD

**Issue by wjohnw** [instabot-py/instabot.py#1933]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

Is possible grab all similar accounts for some specific one? 
The url is https://www.instagram.com/userID/similar_accounts/  but i can not find way how to get all this accounts. Anyone one help? 

Thank you

**Comment by dimisdas** [comment]
Can't find any documentation on` https://www.instagram.com/userID/similar_accounts/` or get it to work. Do you have any working examples? Thanks!
