### ISSUE TITLE
Cannot continue without Instaloader

### ISSUE THREAD

**Issue by Leivaster** [instabot-py/instabot.py#1934]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.6.5
```

#### Pip Version?
```
pip 19.0.1
```

#### Description of your issue

When i try to execute "python3.6 example.py" i receive the following error:
"Cannot continue without module instaloader. Please install dependencies  in requirements.txt. Exiting."
I have already installed the dependencies launching the command "pip3.6 install -r requirements.txt" and tells me that all the requirements have been satisfied. Please help me

**Comment by sewdough** [comment]
I am having the same issue utilizing CENTOS 7. Same version and everything.

**Comment by dimisdas** [comment]
What is the output of “python3.6 -m instaloader”?

**Comment by sewdough** [comment]
[root@server1 instabot.py]# python3.6 -m instaloader
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.6/site-packages/instaloader/__init__.py", line 16, in <module>
    from .instaloader import Instaloader
  File "/usr/local/lib/python3.6/site-packages/instaloader/instaloader.py", line 3, in <module>
    import lzma
  File "/usr/local/lib/python3.6/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
[root@server1 instabot.py]# yum install lzma
Loaded plugins: fastestmirror, security, universal-hooks
Setting up Install Process
Loading mirror speeds from cached hostfile
 * EA4: 149.56.181.210
 * cpanel-addons-production-feed: 149.56.181.210
 * epel: epel.mirror.constant.com
Package xz-lzma-compat-4.999.9-0.5.beta.20091007git.el6.x86_64 already installed and latest version
Nothing to do

**Comment by suri4desplaines** [comment]
uninstall an re install installoader , with powershell , it work for me

**Comment by Shukuls** [comment]
> You’ll have to install lzma-dev and recompile python

How install it? With apt-get?? 
And how recompile python?

I have the same problem and installing lzma with apt-get I still having the same problem.
