### ISSUE TITLE
Auto DM new followers? 

### ISSUE THREAD

**Issue by damoenceno** [instabot-py/instabot.py#1936]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

Hi All!!

Just wondering if some of you have worked out how to Auto DM new followers with a welcome message? If so, could you possibly share? 

Thanks!

**Comment by dimisdas** [comment]
Hello,

This is not currently possible given how instabot uses the website’s API, and does not require client or device keys to work. 

If the website over at Instagram.com is updated in the future and supports messaging (DMs) then this issue shall be revisited.

Thank you :)

**Comment by mcy260** [comment]
any updates on this?
