### ISSUE TITLE
Bot logs out after less than 10 comments every time

### ISSUE THREAD

**Issue by murlikanne** [instabot-py/instabot.py#1937]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < 

27.01.2019_02:46 Get Media by tag: wordswithqueens
27.01.2019_02:46 Removing already liked medias..
Traceback (most recent call last):
  File "inf.py", line 75, in <module>
    bot.new_auto_mod()
  File "C:\Users\DELL\Music\5\src\instabot.py", line 901, in new_auto_mod
    self.new_auto_mod_comments()
  File "C:\Users\DELL\Music\5\src\instabot.py", line 1018, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['shortcode']) == False:
  File "C:\Users\DELL\Music\5\src\instabot.py", line 1043, in check_exisiting_comment
    all_data = json.loads(re.search('window._sharedData = (.*?);', check_comment.text, re.DOTALL).group(1))['entry_data']['PostPage'][0] #window._sharedData = (.*?);
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 2908 (char 2907)
27.01.2019_02:49 Logout: likes - 0, follow - 0, unfollow - 0, comments - 7.
27.01.2019_02:49 Bot work time: 0:23:16.729964
27.01.2019_02:49 Logout success!
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by dimisdas** [comment]
Which version of the bot are you using? Have you pulled the latest changes?

**Comment by murlikanne** [comment]
the latest commit always says the code was wrong so i'm using the previous one like from 10 days ago

**Comment by dimisdas** [comment]
The issue you are describing has been resolved during which time. Feel free to use a session_file and use the same DB to keep the connection/session between versions and avoiding having to login.

**Comment by murlikanne** [comment]
> The issue you are describing has been resolved during which time. Feel free to use a session_file and use the same DB to keep the connection/session between versions and avoiding having to login.

I'll try that, i have a question, may sound dumb but what would be the file extension for session file? is it .session or .session_file? .session doesn't seem to be helping or maybe i was using too many accounts on one ip. I've been facing too many problems lately

**Comment by dimisdas** [comment]
Using too many accounts on one IP won't help in both cases. It's best to wait for some time and try again.
