### ISSUE TITLE
I was getting the 403 error like a month ago and someone fix it by changing to "follow: 0"

### ISSUE THREAD

**Issue by bokornuevedos** [instabot-py/instabot.py#1938]
Is this fixed now? I need to follow people I'm not getting any followers and yes I try to add follows again and failed in 403 does anyone else have a fix?

**Comment by dimisdas** [comment]
Closed because of missing issue template. Also, it's not really an issue.

Try the latest version from the GitHub repo, and if it still doesn't work, then open a bug issue.
