### ISSUE TITLE
Issue with Instabot on Raspbian - sqlite3

### ISSUE THREAD

**Issue by DavyJones71** [instabot-py/instabot.py#1939]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
3.7.2
Include here the response of 'python --version' or 'python3 --version'
Python 3.7.2

#### Pip Version?
9.0.1
Include here the response of 'pip --version' or 'pip3 --version'
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)

#### Description of your issue
Hi!

I have an issue with Instabot on Raspbian. 
After installing instabot and the requirements i have python 2.7 and python 3.5. on the system. 
When I then install the newest python version and try to run instabot it always says that i don't have sqlite3. 
I tried to install libsqlite3-dev but the same problem happens again.
I also tried to uninsall python 2.7 to just have one python version on the system, but it aint help either.

Do you have an idea where my failure is? i am missing something here. 

Thank you in advance. 
Cheers Jones
```

python3 /home/pi/instaBot/instabot.py/example.py
Traceback (most recent call last):
  File "/home/pi/instaBot/instabot.py/example.py", line 6, in <module>
    from src import InstaBot
  File "/home/pi/instaBot/instabot.py/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/pi/instaBot/instabot.py/src/instabot.py", line 5, in <module>
    from .sql_updates import check_and_insert_user_agent
  File "/home/pi/instaBot/instabot.py/src/sql_updates.py", line 2, in <module>
    import sqlite3
  File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

#### Config

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="",
    password="",
    like_per_day=863,
    comments_per_day=0,
    tag_list=["visualambassadors", "visualart", "manipulationteam", "digitalart", "splendid_visuals", "hubs_united", agameoftones"],
    tag_blacklist=["trump", "fpoe"],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=113,
    follow_time=1 * 60 * 60,
    unfollow_per_day=176,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy="",
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[
        ["this", "the", "your"],
        ["photo", "picture", "pic", "shot", "snapshot"],
        ["is", "looks", "feels", "is really"],
        [
            "great",
            "super",
            "good",
            "very good",
            "good",
            "wow",
            "WOW",
            "cool",
            "GREAT",
            "magnificent",
            "magical",
            "very cool",
            "stylish",
            "beautiful",
            "so beautiful",
            "so stylish",
            "so professional",
            "lovely",
            "so lovely",
            "very lovely",
            "glorious",
            "so glorious",
            "very glorious",
            "adorable",
            "excellent",
            "amazing",
        ],
        [".", "..", "...", "!", "!!", "!!!"],
    ],
    # Use unwanted_username_list to block usernames containing a string
    # Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    # 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        "second",
        "stuff",
        "art",
        "project",
        "love",
        "life",
        "food",
        "blog",
        "free",
        "keren",
        "bush",
        "graphy",
        "indo",
        "travel",
        "art",
        "shop",
        "store",
        "sex",
        "toko",
        "jual",
        "online",
        "murah",
        "jam",
        "kaos",
        "case",
        "baju",
        "fashion",
        "corp",
        "tas",
        "butik",
        "grosir",
        "karpet",
        "sosis",
        "salon",
        "skin",
        "care",
        "cloth",
        "tech",
        "rental",
        "trump",
        "beauty",
        "express",
        "kredit",
        "collection",
        "impor",
        "preloved",
        "follow",
        "follower",
        "gain",
        ".id",
        "_id",
        "bags",
    ],
    unfollow_whitelist=["example_user_1", "example_user_2"],
)
while True:

    # print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    # print("## MODE 1 = MODIFIED MODE BY KEMONG")
    # print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    # print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    # print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    # print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    # USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    # print("You choose mode : %i" %(mode))
    # print("CTRL + C to cancel this operation or wait 30 seconds to start")
    # time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        bot.bot_mode = 3
        while bot.login_status == 1:
            bot.unfollow_recent_feed()
            time.sleep(5)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")
```

**Comment by dimisdas** [comment]
> I also tried to uninsall python 2.7 to just have one python version on the system, but it aint help either.

Python 2 is essential in Raspbian. Congratulations on essentially breaking your system! Try to reinstall `sudo apt-get install python-minimal`.

You can keep multiple versions installed at once. 

> I tried to install libsqlite3-dev but the same problem happens again.

That only works if you're recompiling Python from source afterwards.

> After installing instabot and the requirements i have python 2.7 and python 3.5. on the system.

Instabot requires 3.6+

Read our helpful guide on compiling Python 3.7 on Raspbian. It includes all the required packages, including `libsqlite3-dev`. Even if you _have_ installed Python 3.7, if you didn't have those packages during compiling then they won't be included in your Python installation.

https://github.com/instabot-py/instabot.py/wiki/Raspberry-Pi-Python-3.7---Read-This

Good luck!

**Comment by DavyJones71** [comment]
Thank you for your help. 
As you can see I am a big noob in this field. I already recoverd python 2 before. 

I haven't seen the Read-This Page, thanks. It kind of helped. 
The problem is that now "requests" is missing

 File "/home/pi/instaBot/instabot.py/example.py", line 6, in <module>
    from src import InstaBot
  File "/home/pi/instaBot/instabot.py/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/pi/instaBot/instabot.py/src/instabot.py", line 26, in <module>
    from .userinfo import UserInfo
  File "/home/pi/instaBot/instabot.py/src/userinfo.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by DavyJones71** [comment]
I tried several things
pip3 install requests
sudo apt-get install python3-requests
sudo pip3 install requests --upgrade

nothing works

**Comment by dimisdas** [comment]
What was the output in each case and why didn’t they work?

Please don’t omit trace back errors or outputs

**Comment by DavyJones71** [comment]
Yes, I followed the Guide. 
The Pip Version is now:
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5) - dont know why it says python 3.5, my python is 3.7.2...

I didt the installation (from the guide) of this line in one:
 sudo apt-get install build-essential tk-dev libncurses5-dev libncursesw5-dev libreadline6-dev libdb5.3-dev libgdbm-dev libsqlite3-dev libssl-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev libffi-dev -y

it didnt showed any error.. but tonight i will install them 1 by 1. maybe there was something wrong which i have overseen. 

Thanks for your help :)

**Comment by dimisdas** [comment]
Does python3.7 --version work?

**Comment by DavyJones71** [comment]
i tried to install every component from the list seperately..

sudo apt-get install build-essential tk-dev libncurses5-dev libncursesw5-dev libreadline6-dev libdb5.3-dev libgdbm-dev libsqlite3-dev libssl-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev libffi-dev -y

just to try out if it makes a difference and shows some erros.. but everything went fine without error.
unfortunately i get the same result when i try to run the script:


pi@raspberrypi:~ $ python3 /home/pi/instaBot/instabot.py/example.py

Traceback (most recent call last):
  File "/home/pi/instaBot/instabot.py/example.py", line 6, in <module>
    from src import InstaBot
  File "/home/pi/instaBot/instabot.py/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/pi/instaBot/instabot.py/src/instabot.py", line 26, in <module>
    from .userinfo import UserInfo
  File "/home/pi/instaBot/instabot.py/src/userinfo.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

I am kind of getting desperate xD

**Comment by slacker3007** [comment]
You get this error if you use "apt-get install", you need to use "pip3 install". Make sure its pip3 otherwise it will drop you error about python.
