### ISSUE TITLE
<module> errors

### ISSUE THREAD

**Issue by Zere** [instabot-py/instabot.py#1945]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ X ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ X ] macOS 10.12.6
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [ X ] I am using Python 3.6 or above

#### Exact Python Version?
`3.7.2
`

#### Pip Version?

```
3.5

```
#### Description of your issue

Various module issues

#### Config

```
everything is completely stock
```

Error I am receiving:

```
Derens-MacBook-Pro:instabot.py-master deren$ python3.7 example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/deren/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/deren/Desktop/instabot.py-master/src/instabot.py", line 26, in <module>
    from .userinfo import UserInfo
  File "/Users/deren/Desktop/instabot.py-master/src/userinfo.py", line 44
    def get_user_id_by_login(self, user_name):
```

**Comment by joevill** [comment]
Can we reopen this by any chance?  I've had the same exact issue as well

**Comment by Zere** [comment]
Hey @joevill I solved this issue by making sure I had chromedriver installed. I installed chromedriver with homebrew. After this it worked. Lmk if you need help.

**Comment by dimisdas** [comment]
Instabot has zero dependencies on chromedriver and is definitely not required to run Instabot.

I think you might have been using InstaPy or a similar bot that works with Selenium.

**Comment by joevill** [comment]
@Zere @dimisdas  Thanks guys - what exactly should I go with then?  chromedriver, or is there something else?

**Comment by dimisdas** [comment]
@joevill open a new issue and post your configuration. Probably a config problem, or you are using a mode other than zero that are not working atm and will be removed.

**Comment by joevill** [comment]
@dimisdas sure thing, I'll post this evening, thanks!
