### ISSUE TITLE
Help: Only unfollow accounts followed by the bot

### ISSUE THREAD

**Issue by bvttle** [instabot-py/instabot.py#1947]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [X] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.2
```

#### Pip Version?
```
pip 18.1 from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip (python 3.7)
```

#### Description of your issue

```
I recently upgraded to the new version of the bot, however still have been using a working version of the old one for this reason.

I have the bot set to follow and unfollow 100 accounts a day. However it seems to be building a database of everyone I follow and just unfollowing anyone who doesn't follow me back.

The previous version of the bot built the database from accounts followed by the bot, any accounts from before would be left as they were.

I don't want the bot to affect anyone I'm following before I run the bot.. is there a specific way to disable this?

```

#### Config

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="xxxxx",
    password="xxxxxx",
    like_per_day=1000,
    comments_per_day=20,
    tag_list=['follow4follow'],
    tag_blacklist=['nsfw'],
    user_blacklist={},
    max_like_for_one_tag=10,
    follow_per_day=100,
    follow_time=12 * 60 * 60,
    unfollow_per_day=100,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["so good!", "amazing!", "cool shot", "nice", "love this", "sweet", "😍", "sweet 😍", "nice 😍", "awesome 😍", "nice shot!", "great shot!", "sweet shot!", "neat shot", "love it!", "✨✨✨" ]
    ],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'bags', 'follower', 'followers', 'sex', 'free', 'gain'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        bot.bot_mode = 3
        while(bot.login_status == 1):
            bot.unfollow_recent_feed()
            time.sleep(5)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

```

**Comment by dropitlikecross** [comment]
Take a look at:

https://github.com/instabot-py/instabot.py/issues/1906#issuecomment-454604506

**Comment by dimisdas** [comment]
@dropitlikecross is spot on. This has been fixed & added as a parameter, but admittedly it might have gone unnoticed. Try it out and drop a comment if it doesn't work for any reason, and I shall reopen the issue.

Cheers!

**Comment by bvttle** [comment]
> Take a look at:
> 
> [#1906 (comment)](https://github.com/instabot-py/instabot.py/issues/1906#issuecomment-454604506)

Looks like the branch they refer to in that comment is missing?

Would I add this parameter in to example.py? e.g.

    unfollow_per_day=5000,
    unfollow_break_min=15,
    unfollow_break_max=30,
    unfollow_recent_feed=False,

etc..?

**Comment by dimisdas** [comment]
The branch has been merged with master and was deleted. The parameters should work fine in the latest version.

Yup! That's the way you set it :)

**Comment by bvttle** [comment]
> The branch has been merged with master and was deleted. The parameters should work fine in the latest version.
> 
> Yup! That's the way you set it :)

Awesome thank you!

**Comment by bvttle** [comment]
> The branch has been merged with master and was deleted. The parameters should work fine in the latest version.
> 
> Yup! That's the way you set it :)

Hi, sorry to open this up again, but the bot seems to be unfollowing before the follow time has passed as well.. is there something I can do to get this working too? It has followed and unfollowed in less than an hour some people, and I think my follow time should have been set to 12h? "12 * 60 * 60"

**Comment by dimisdas** [comment]
follow_time_enabled parameter defaults to True. It shouldn’t, and doesn’t on my local build.

If you have steps on how to reproduce this, please open a separate issue, detailing if you are using the same .db file, when that user was first followed, when they were unfollowed etc.
