### ISSUE TITLE
Script incomplete

### ISSUE THREAD

**Issue by LandoLabrum** [instabot-py/instabot.py#195]
Do I have to let the script run all the way through to get any results? I saw the script was working then I exited out of the script to check it's progress. When I logged onto instagram it showed that nothing had happened.

**Comment by LevPasha** [comment]
@LandoLabrum show your settings. This is program - when i run - it is work.

**Comment by polaroi8d** [comment]
@LandoLabrum do you still have the problem? If not please close the issue.

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
