### ISSUE TITLE
metrics

### ISSUE THREAD

**Issue by macd2** [instabot-py/instabot.py#1952]
#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ x] Technical Help
- [ ] Other

The metric themes quote off are there any suggestions for a better metric calculation?
Example:

```
Getting user info : ...
Checking user info..
Follower : 77
Following : 12
Media : 30
    >>>This is probably Selebgram account
    >>>This user is active
    >>>This account is NOT following you
    >>>You are NOT following this account
```
the corresponding code:
```
 if follows == 0 or follower / follows > 2:
    self.is_selebgram = True
    self.is_fake_account = False
    self.write_log("   >>>This is probably Selebgram account")

```
what i don't get is `if follows == 0 ` == self.is_selebgram = True ?

i think we agree calling this account a Selebgram is to far from true this issue could be fixed by using the [proposed filter](https://github.com/instabot-py/instabot.py/pull/1951) to apply this metric only on account > X followers?

**Comment by dimisdas** [comment]
`follows = user_info["edge_follow"]["count"]`

This is how many people the user follows. If they are like ... let's say _Beyonce_, they won't be following anyone. These people aren't likely to engage with your account, and we don't need to keep following them.

![screenshot 2019-02-02 at 13 48 55](https://user-images.githubusercontent.com/1391441/52163864-49e18100-26f1-11e9-96c9-b9b360099e58.jpg)

I'd agree that the second part of that if statement could be improved. 

`or follower / follows > 2:`

That's the follower/following ratio. If a user has 20k followers, and only follows back 300 of them, 

20000 / 300 = 66,66
66,66 > 2

The accepted ratio threshold could become a parameter.

**Comment by macd2** [comment]
alright ok so than i got you `they won't be following anyone.`

for the ratio im sure there are some metrics out there that have been proven to work, the goal should be to to be able to hand tailor a reasonable target audience, there for my [proposal](https://github.com/instabot-py/instabot.py/pull/1951#issuecomment-459710163) in the last pull request to set "all_data" globally once per loop, than we could go ahead and add a "target_audience_selector" or something like this where you have all the parameters to fine tune your target audience...
