### ISSUE TITLE
Login error! Check your login data!

### ISSUE THREAD

**Issue by Gx0st** [instabot-py/instabot.py#1957]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [x ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue
My password and username as correct, I checked it twice, copy pasted it and everything just to make sure I wasn't making a typo. Any help!? I just update my Instabot.PY because it said in the console there was a new version. Now it will not work. :(
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```
02.02.2019_22:07 Checking for updates...
02.02.2019_22:07 You are running the latest stable version
02.02.2019_22:07 Instabot v1.2.2/0 started at 02.02.2019 22:07:
02.02.2019_22:07 Trying to login as (Ididntwanttopustmyusernamehere)...
02.02.2019_22:07 Login error! Check your login data!
02.02.2019_22:07 Exit Program... GoodBye
#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by Gx0st** [comment]
LOL. For anyone having this issue, capital letters matter for the USERNAME AND PASSWORD. Only for the first letter!

**Comment by Jucinei** [comment]
was it correct?
