### ISSUE TITLE
Log followed users by tag

### ISSUE THREAD

**Issue by petergriffin1986** [instabot-py/instabot.py#196]
Is there a way to get the logs for following to also write the hashtag that helped find a user?

For example, right now this are the lines for logging follow:

```
2016-09-22 23:47:43,200 - xxxx  - Get media id by tag: XXXX
2016-09-22 23:47:44,103 - xxxx  - Trying to follow: 23688507
2016-09-22 23:47:44,579 - xxxx - Followed: 23688507 #1.
```

Is there a way to have it say something like:

```
2016-09-22 23:47:43,200 - xxxx  - Get media id by tag: XXXX
2016-09-22 23:47:44,103 - xxxx  - Trying to follow: 23688507
2016-09-22 23:47:44,579 - xxxx - Followed: 23688507 #1 tag XXXX.
```

This would be a major improvement because it would help identify which tags bring the most followers.

**Comment by virginsince1997** [comment]
@petergriffin1986 can I get your email, want to ask something

**Comment by dave240170** [comment]
I'd guess something like this;

log_string = "Followed: %s #%i." % (user_id, self.follow_counter) " " % (tag)

**Comment by nickzano** [comment]
Can we use a hash map/table for this and store the user's id in the map/table then just check the map/table for it?

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
