### ISSUE TITLE
Media_min_like how work?

### ISSUE THREAD

**Issue by adamski888** [instabot-py/instabot.py#1963]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Config

username = user
unfollow_per_day = 797
unfollow_break_max = 160
like_per_day = 1238
media_min_like = 200
unfollow_break_min = 3
comments_per_day = 0
follow_per_day = 651
max_like_for_one_tag = 60
password =  pass
follow_time = 24*60*60
session_file = user.session
user_min_follow = 500
unlike_per_day = 500
time_till_unlike = 24*60*60

###Question
hi, bot like post below 200 like. how work the media_min_like option???

**Comment by dimisdas** [comment]
Can you post an example of a picture it liked when it shouldn't? And the relevant console output.

**Comment by adamski888** [comment]
05.02.2019_08:09 Trying to like media: 1972404218245536857
    (https://www.instagram.com/p/BtfYy-uAdxZ/)
05.02.2019_08:09 Liked: 1972404218245536857. Like #2.
