### ISSUE TITLE
Login failed after entering the challenge code

### ISSUE THREAD

**Issue by madalingrigorie** [instabot-py/instabot.py#1965]
I am trying to login and I can't even though I am entering the correct code and I also tried login in to incognito before 
this is the error that I am getting
Login failed, response: 

{"message": "checkpoint_required", "checkpoint_url": "/challenge/20801049/b3n7jJE42c/", "lock": false, "status": "fail"} "name='csrftoken', domain=None, path=None"

I saw that I might be locked into the challenge loop, but I was waiting for 2 weeks and nothing changed. 
If any of you had the same issue, how did you fixed it?

**Comment by Mehranp** [comment]
same

**Comment by dieselp** [comment]
I got the same problem :/

**Comment by madalingrigorie** [comment]
I finally got over that step.  What I did was to open the Instagram account into a new Incognito page, confirm the code received and then instantly run the script and it worked

**Comment by dieselp** [comment]
Sadly this is not a solution for me. After confirmation via Incognito page, I got the same issue in the script and I'm unable to log in every time - even that code is correct...

11.02.2019_11:54 Checking for updates...
11.02.2019_11:54 Could not check for updates
11.02.2019_11:54 Instabot v1.2.2/0 started at 11.02.2019 11:54:
11.02.2019_11:54 Trying to login as XXX...
11.02.2019_11:55 Something wrong with login
11.02.2019_11:55 {"message": "checkpoint_required", "checkpoint_url": "/challenge/671879/xoeXW6r4jk/", "lock": false, "status": "fail"}
11.02.2019_11:55 Challenge required at https://instagram.com/challenge/671879/xoeXW6r4jk/
Challenge Required.

Enter the code sent to your mail/phone: 506749
11.02.2019_11:55 Entered code is wrong, Try again later!
11.02.2019_11:55 Exit Program... GoodBye

**Comment by madalingrigorie** [comment]
@dieselp Keep trying to enter your code in the browser. It's not gonna work if you're entering it in the terminal. you need somehow to confirm that it's you on the browser by entering the code and when you enter the run command in the script is not gonna ask you for the challenge code.

**Comment by dieselp** [comment]
Nope - it's doesn't work for me. Every time I try to do that this way, I get a login error for about 6 hours and I'm unable to log in via page/bot/app... :/

**Comment by matrpedreira** [comment]
Hi, I got it to work by disabling the phone 2 step authentication on my Instagram then using the code that they send by email. I think the 2 step phone authentication is the problem.

**Comment by henriqueblobato** [comment]
Is this the only solution? Disabling two step auth does not seem to be very secure :(
