### ISSUE TITLE
Follow/Unfollow - want to have constantly the same amount of people I'm following

### ISSUE THREAD

**Issue by enrifer** [instabot-py/instabot.py#1966]
Hey, can somebody explain how the standard follow/unfollow mode is exactly working?
I'm following more and more people. 
follow_per_day=500,
follow_time= 4* 60 * 60,
unfollow_per_day=5000,
I want the number of people I'm following should stay around the same at the end of the day compared to the beginning of the day.
At the end of the day I stop following people and only unfollow people, but still the amount of people I'm following is higher than when the bot started working...
(Bot is working fine... it follows and unfollows, but only not enough unfollows)

Any suggestions? Thanks a lot for your help 👍🙏

**Comment by rudyvanbebu** [comment]
Hi Enrifer,

I experience the same behaviour in mine. Bot compensates when it is closed but never seem to make sense while running constantly. 

Did you have any better luck changing settings or after being assisted by anyone else?

Thanks

**Comment by Pitti1981** [comment]
Hi everybody,

the same question I ask myself too. 
If I set the values ​​at follow / unfollow the same, then the number of people I follow should be constant ...

Can someone enlighten this?

thanks a lot - and have a nice day!

**Comment by pipofoin** [comment]
Hi there,

Same pb for me as well, number of people I'm following in always increasing no matter the settings.
Btw, since the last update, when killing the program with ctrl+c, it won't unfollow all the users followed in the db. What is the way to unfollow everyone now?

Thanks a lot!

**Comment by dimisdas** [comment]
Closing this in favour of the better articulated https://github.com/instabot-py/instabot.py/issues/2095
