### ISSUE TITLE
What is the point of time_till_unlike ? Why should we use it?

### ISSUE THREAD

**Issue by AlainPilon** [instabot-py/instabot.py#1968]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Description of your issue

```
What is the reason behind _time_till_unlike_? Why would you want to unlike something?
```

**Comment by nickgryg** [comment]
Instabot-py bot can also unlike photos which it liked before. If you want to use this functionality, you need to define time to wait until unlike medias. 
To sum up, you need to define two settings in a configuration:

unlike_per_run | int | Number of media to unlike that the bot has previously liked. Set to 0 to disable. | 0
-- | -- | -- | --
time_till_unlike | int | How long to wait after liking media before unliking them. | 3 * 24 * 60 * 60 (3 days)
