### ISSUE TITLE
Russian tags not working

### ISSUE THREAD

**Issue by Redas17** [instabot-py/instabot.py#1970]
I've change tags to the Russian ones like "ютуб", after that I get error.
"Syntax error: (unicode error) "utf-8" codec can't decode  byte 0xe2 in position 0: invalid continuation byte.
How to fix it? Russian tag used to work perfectly in older versions, thank you!

**Comment by dimisdas** [comment]
Please resubmit issue with the template filled in, including a reproducible example (like your config file).
