### ISSUE TITLE
Like Action blocked

### ISSUE THREAD

**Issue by alaintainguyen** [instabot-py/instabot.py#1973]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

#### Environment
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [X] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
When I launched instabot 2 days ago, it worked with 900 likes , 300 follow 300 comments / day.
Now when I would like to like a picture on Instagram, I have this following error : 
"Action Blocked. Based on previous use of this feature, your account has been temporarily blocked from taking this action. So I have to wait until this end of day.
What can I do ? 

```

#### Config

```
    login="someLogin",
    password="somePassword",
    like_per_day=900,
    comments_per_day=300,
    tag_list=["traveller","holiday", "holidays", "beautiful", "perfect", "travel", "enjoy", "lifestyle", "voyage",
              "love","instagood","me","cute","photooftheday","instamood","picoftheday","instadaily","summer","bestoftheday",
              "happy","fashion","sky","nofilter","fun","sun","pretty","instagramers","like","friends","funny","life","cool","beach",
              "sunset","photo","amazing","awesome","instalove","beauty", "nice",
              "look","instalike","picoftheday","food","instadaily","instafollow",
              "instagood","instacool","instago","style"],
    tag_blacklist=["rain", "thunderstorm"],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60 * 60,
    unfollow_per_day=0,
    unlike_per_day=0,
    time_till_unlike=3 * 24 * 60 * 60,  # 3 days
    unfollow_break_min=15,
    unfollow_break_max=30,
    user_max_follow=0,  etc...
```

**Comment by ma1rius** [comment]
stop using instagram for 24h and lower your likes 400

**Comment by alaintainguyen** [comment]
@ma1rius  Ok thank you , so i will lower my likes for 400, 300 for comment and follow is ok ?

**Comment by ma1rius** [comment]
if its a new account try first week 300 likes and 200 comments the next week 400 likes and 300 comm 
i use on my 3  account 1500 likes and 500 comm  for the new ones and for my old one  700 comm and 
 1800  likes slowly up x100 every week

**Comment by cobrakaistudent** [comment]
Did the new values work @alaintainguyen? also why are you setting the unfollow to 0?

**Comment by alaintainguyen** [comment]
@ma1rius my account is an old account (4 years I mean) so what do you suggest for the value?

**Comment by alaintainguyen** [comment]
@cobrakaistudent I set the unfollow to 0 because I dont want that the bot unfollow random people ( sometime its unfollowed my friends ... ) maybe i didnt configure

**Comment by mrallanodreman** [comment]
@alaintainguyen the bot Will unfollow who dont follow you!

**Comment by cobrakaistudent** [comment]
@alaintainguyen I dont think it does that, there is a data set created in your folder where the likes and follows are stored, and the unfollows come from that list once the time of follow is fulfilled.

**Comment by dimisdas** [comment]
> @alaintainguyen I dont think it does that, there is a data set created in your folder where the likes and follows are stored, and the unfollows come from that list once the time of follow is fulfilled.

Actually it does. The bot by default populates the database with people from the recent feed, unless you have the parameter `unfollow_recent_feed` set to False.

**Comment by alaintainguyen** [comment]
Hello guys, @ma1rius  

After 3days I start the bot again with 400 likes and 200 comments...
2 hours after, I have the same problem : 
"Action Blocked. Based on previous use of this feature, your account has been temporarily blocked from taking this action" until the end of this day.

What can I do ?
