### ISSUE TITLE
Welcome Message

### ISSUE THREAD

**Issue by Ofido** [instabot-py/instabot.py#1974]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x] Feature Request
- [x] Technical Help
- [x] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Linux (include flavour)
- [x] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
3.7 -- Last ever

#### Pip Version?
19.1? -- Last Ever

#### Description of your issue

Have a form that i send direct messages to new people that start to follow me?
I see that have a issue about this but is too old
if I do not have a way, how can I implement the instagran API to do just that?
Thanks

**Comment by dimisdas** [comment]
Not possible using Instabot. We use the web api. There's no way to send DMs using the website currently.
