### ISSUE TITLE
command to start example.py doesn't work

### ISSUE THREAD

**Issue by crime89** [instabot-py/instabot.py#1975]
Hello,

I have tried with many different commands to open the example.py file and make the changes, but none works.

test 1
sudo nano example.py --> sudo: nano: command not found
test 2
example.py --> -bash: example.py: command not found
test 3
python example.py --> -bash: python: command not found
test 4
python3 example.py --> 

11.02.2019_14:31 Checking for updates...
11.02.2019_14:31 You are running the latest stable version
11.02.2019_14:31 Instabot v1.2.2/0 started at 11.02.2019 14:31:
11.02.2019_14:31 Trying to login as username...
11.02.2019_14:31 Login error! Check your login data!
11.02.2019_14:31 Exit Program... GoodBye

ehm... it is saying goodbye. 

I make reference to this folder “git clone https://github.com/instabot-py/instabot.py.git” 

What should I do?

Thanks

**Comment by dimisdas** [comment]
Please edit your post and include the Issue Template. I cannot help you if I don't know what OS you're using.

The telegram group is more appropriate for getting help on how to install/run Python and basic OS functions or tools.

**Comment by crime89** [comment]
Hi dimisdas,
I am not a developer.
I would like to get some help. May you add me in this telegram group?
I have written an email to your address.
Hope you can help me

Thank you

**Comment by dimisdas** [comment]
The Telegram group is open for everyone using this link:
https://t.me/joinchat/DYKH-0G_8hsDDoN_iE8ZlA

See you there :)
