### ISSUE TITLE
The code is messed up pretty badly.

### ISSUE THREAD

**Issue by Domtaholic** [instabot-py/instabot.py#1976]
Im not quite sure what happend there, but i think you kinda searched and replaced and messed up everything or things on my side work not they should be.

Example:
instabot.py

`python_version_test = f"If`

this f" is in a lot of files and in different variations. like f" or f[] or (f) 

And another question, in my log the userdata isnßt replaced, like {like_counter} is printed and not the data itself, do i need to update something there?

Cheers and good work on this one ;) expect that f problem :D

**Comment by dimisdas** [comment]
They are called f-strings and there is nothing wrong with them.

PEP 498

**Comment by Domtaholic** [comment]
I use Python 3.7.1 and get Syntax Errors when i run the script. 

Is there some setting i need to update?

Thanks for fast response

**Comment by dimisdas** [comment]
Could you post the syntax error in full? Thanks
