### ISSUE TITLE
Unfollow doesn't work

### ISSUE THREAD

**Issue by mastercake10** [instabot-py/instabot.py#198]
Hello,
the bot tries to unfollow every user followed during the bot process on exit, but after about 20 users it fails.

It is possible to add a function that returns the users follows?
For example I have 3.000+ follows now and I want to unfollow them all, I know there is a limit but the function described above would allow me to unfollow users every x minutes.

This function would be awesome.

**Comment by 179skr** [comment]
You'll have to code it using the new Instagram-API

**Comment by mastercake10** [comment]
@179skr but i think this would be possible in this python bot?

**Comment by davisonio** [comment]
@LevPasha @kemong can you help with this? The bot stops after 24 unfollows when on mode 5.

**Comment by davisonio** [comment]
Ok, the problem is that there is a limit set in unfollow_protocol.py.

**Comment by tbudd23** [comment]
@davisonio Where in unfollow_protocol.py did you find this???

**Comment by davisonio** [comment]
Change this line to `limit = 9999999` https://github.com/LevPasha/instabot.py/blob/5eaacfaac866c35e766206a2f8a483f1e7eb68b6/src/unfollow_protocol.py#L13

**Comment by gersanchez** [comment]
not working... :(
<img width="552" alt="captura de pantalla 2017-02-18 a las 11 58 12 a m" src="https://cloud.githubusercontent.com/assets/2736208/23095062/a685fa38-f5d1-11e6-8513-5e00365d8434.png">

**Comment by mastercake10** [comment]
I think there must be a reason why this value is limited.

**Comment by loganyc1934** [comment]
What's this `limit`? What I want is simply to unfollow at a pace around x minutes.

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
