### ISSUE TITLE
Option to mute new followings

### ISSUE THREAD

**Issue by SebastianThiebaud** [instabot-py/instabot.py#1983]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.6.3
```

#### Pip Version?
```
pip 19.0.2 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
```

#### Description of your issue
Could we include a new option to mute new followings? So feeds are not full of noise.

**Comment by dimisdas** [comment]
Hello,

Unfortunately this is not currently possible. Mute option is not available in the web version of the API that Instabot uses. Thanks
