### ISSUE TITLE
syntax error : invalid syntax

### ISSUE THREAD

**Issue by Tkr5092** [instabot-py/instabot.py#1984]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ x] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
3.7.2

#### Description of your issue
after I run example.py it comes up 
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/home/tyler5ricco/instabot.py/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/tyler5ricco/instabot.py/src/instabot.py", line 33
    python_version_test = f"If you are reading this error, you are not running Python 3.6 or greater. Check 'python --version' or 'python3 --version'."
                                                                                                                                                      ^
SyntaxError: invalid syntax

```
import os
import time
from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol
bot = InstaBot(
    login="",  # Enter username (lowercase). Do not enter email!
    password=",
    like_per_day=100,
    comments_per_day=0,
    tag_list=["digitalmarkteingagency", "martking", "smallbussiness", "philadelphia_citylife"],
    tag_blacklist=["rain", "thunderstorm"],
    user_blacklist={},
    max_like_for_one_tag=20,
    follow_per_day=5,
    follow_time=1 * 60,
    unfollow_per_day=0,
    unlike_per_day=0,
    unfollow_recent_feed=True,  # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
    time_till_unlike=3 * 24 * 60 * 60,  # 3 days
    unfollow_break_min=15,
    unfollow_break_max=30,
    user_max_follow=0,
    # session_file=False, # Set to False to disable persistent session, or specify custom session_file (ie ='myusername.session')
    user_min_follow=0,
    log_mod=0,
    proxy="",

**Comment by dimisdas** [comment]
> If you are reading this error, you are not running Python 3.6 or greater

What is the output of “python --v” and “python3 --v“? How exactly are you running the script, I don’t see the command in your output.

**Comment by onesecondleft** [comment]
I'm also having the same issue, but in macOS. 
The output of “python --v” is Python 2.7.10 and “python3 --v“ is Python 3.7.2. But I only have the 3.7.2 version installed, I can't find the 2.7.10 version it says I also have installed.

**Comment by dimisdas** [comment]
Python 2.7 is preinstalled in macOS and some major Linux distros. It is a necessary component of many applications, like the Debian/Ubuntu package manager.

It is not unusual for systems to carry multiple python installations, and you shouldn’t uninstall 2.7 unless you are completely sure of what you’re doing. 

Running the program using the “python” command I guess is calling Python 2.7 in your case.

You should try “python3 example.py” and “pip3 install -r requirements.txt”.

If you need more help, feel free to join our telegram group. It is more appropriate for installation issues and you’ll get faster responses.

Thanks!
