### ISSUE TITLE
bot does not comment on media it liked

### ISSUE THREAD

**Issue by Haterz-D** [instabot-py/instabot.py#1985]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.6.3
```

#### Pip Version?
```
pip 18.1
```

#### Description of your issue

```
The bot does not comment on media it liked and comments on next found media instead:
For example, if number of likes and comments per day is the same:

> Trying to like media: 10000
> Liked: 10000. Like #1.
> Trying to comment: 10001
> Write: comment. #1. 
> Trying to like media: 10002
> Liked: 10002. Like #2.
> Trying to comment: 10003
> Write: comment. #2 


It used to comment on the media it liked:
For example:

> Trying to like media: 10000
> Liked: 10000. Like #1.
> Trying to comment: 10000
> Write: comment. #1. 
> Trying to like media: 10001
> Liked: 10001. Like #2.
> Trying to comment: 10001
> Write: comment. #2 

I also have the problem described here https://github.com/instabot-py/instabot.py/issues/1953
in case it can be related
```

#### Config

```
[root@southwestcandy 50]# cat example.fly.py 
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    like_per_day=322,
    comments_per_day=322,
    tag_list=['tag', 'list'],
    user_blacklist={},
    max_like_for_one_tag=150,
    follow_per_day=0,
    follow_time=1 * 60 * 60,
    unfollow_per_day=0,
    unlike_per_day=0,
    unfollow_recent_feed=False,  # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
    time_till_unlike=3 * 24 * 60 * 60,  # 3 days
    unfollow_break_min=15,
    unfollow_break_max=30,
    user_max_follow=0,
    # session_file=False, # Set to False to disable persistent session, or specify custom session_file (ie ='myusername.session')
    user_min_follow=0,
    log_mod=1,
    proxy="",
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["Nice","comment"]],
    # Use unwanted_username_list to block usernames containing a string
    # Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    # 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=['123']
    # Enable the following to schedule the bot. Uses 24H
    # end_at_h = 23, # Hour you want the bot to stop
    # end_at_m = 30, # Minute you want the bot stop, in this example 23:30
    # start_at_h = 9, # Hour you want the bot to start
    # start_at_m = 10, # Minute you want the bot to start, in this example 9:10 (am).
)

bot.mainloop()
```

**Comment by spud-dog** [comment]
Hey I am also getting this problem.Plus tag blacklist doesn't work for comments. Likes and comments seem to now work independently.

**Comment by Haterz-D** [comment]
@dimisdas can you look into this? it affects efficiency of the bot a lot

**Comment by dimisdas** [comment]
I can't seem to find when it used to work like this. Comments and Likes are different intervals. Could you help me by pinpoint the commit or date when this stopped happening? Thanks

**Comment by Haterz-D** [comment]
I checked the logs and the bug appeared after I updated from 1.2.0 to 1.2.1 on Jan 13
same with bug described here: https://github.com/instabot-py/instabot.py/issues/1953

**Comment by Haterz-D** [comment]
verstion.txt in 1.2.1 : 1547307065
1.2.0 does not have version.txt file

**Comment by Tris10w** [comment]
Modify the instabot.py file. In there, you can call the comment method during the like.

**Comment by m-ketan** [comment]
@Tris10w Can you maybe post the code here for that? Would be really helpful.

**Comment by the-unknown** [comment]
I have the same issue! 
How can I call the comment method within the Like method?

**Comment by heldausberlin** [comment]
@dimisdas, why did you close it when it is still up?

**Comment by yurilaaziz** [comment]
Marked as duplicate 
https://github.com/instabot-py/instabot.py/issues/1953
