### ISSUE TITLE
Logging Abilities

### ISSUE THREAD

**Issue by gothraven** [instabot-py/instabot.py#1988]
Add the ability to log in stdout and a file in the same time.

- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

#### Operating System? (include version)
- [x] macOS
- [x] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

**Comment by dimisdas** [comment]
This issue is missing its template, but I'm very keen to agree on this feature request. If you are able to make a push request, I'll be glad to accept it :)

**Comment by gothraven** [comment]
I don't see why you're being so closed about the ISSUE TEMPLATE thing, but i did update the issue for that.


> This issue is missing its template, but I'm very keen to agree on this feature request. If you are able to make a push request, I'll be glad to accept it :)

I'll work on it in the next few days then
