### ISSUE TITLE
comment function is not working

### ISSUE THREAD

**Issue by f1schhh** [instabot-py/instabot.py#1989]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by f1schhh** [comment]
18.02.2019_21:49 Trying to comment: 1982168701822207554
18.02.2019_21:49 Write: Du pic är 👉 magnificent.. #1.
18.02.2019_21:50 > Waiting for database to populate before unfollowing (progress 7 /20)
18.02.2019_21:50 Will try to populate using recent feed
18.02.2019_21:50 (username): Get media id on recent feed
18.02.2019_21:50 Media in recent feed = 11
18.02.2019_21:50 Notice: could not populate from recent feed

**Comment by dimisdas** [comment]
I don't see anywhere on the log the comment function malfunctioning. ?
