### ISSUE TITLE
Whitelist loop

### ISSUE THREAD

**Issue by smoki3** [instabot-py/instabot.py#1996]
Hi  I am using the whitelist feature.

But it ends sometimes in a loop and only a manual kill stops it:

<img width="580" alt="bildschirmfoto 2019-02-22 um 22 31 58" src="https://user-images.githubusercontent.com/9723729/53272649-29a25200-36f2-11e9-9e86-3fcb689f8faf.png">

as you can see on the picuture. 

@dimisdas 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
3.7

**Comment by smoki3** [comment]
https://github.com/instabot-py/instabot.py/pull/1776/commits/540539c727834c6632898e95eda94c13785b2c41

check this

**Comment by dimisdas** [comment]
https://github.com/instabot-py/instabot.py/commit/9da5c61b53dc7232af858906ac97b543d1ea3155
