### ISSUE TITLE
Unable to Get Media By Location

### ISSUE THREAD

**Issue by waynoedm** [instabot-py/instabot.py#1997]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Kali Linux
- [ ] Android (include terminal)

#### Python Version Requirement
- [X ] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.6.7
```

#### Pip Version?
```
18.1
```

#### Description of your issue

```
Unable to get / like media by location.  Fresh install. Works as should on tags. Just realized it can work with location as well so giving it a try.  No luck.


23.02.2019_18:16 Get Media by location: 1017523603
23.02.2019_18:16 Removing already liked medias..
23.02.2019_18:16 Get Media by location: 275053674
23.02.2019_18:16 Removing already liked medias..
23.02.2019_18:16 Get Media by location: 285632728
23.02.2019_18:16 Removing already liked medias..
23.02.2019_18:17 Get Media by location: 1017523603
23.02.2019_18:17 Removing already liked medias..
23.02.2019_18:17 Get Media by location: 7028133
23.02.2019_18:17 Removing already liked medias..
23.02.2019_18:17 Get Media by location: 1017523603
23.02.2019_18:17 Removing already liked medias..
23.02.2019_18:17 Get Media by location: 261649551
23.02.2019_18:17 Removing already liked medias..
23.02.2019_18:17 Get Media by location: 1534506603258269
23.02.2019_18:17 Removing already liked medias..
23.02.2019_18:18 Get Media by location: 449220398433220
23.02.2019_18:18 Removing already liked medias..
23.02.2019_18:18 Get Media by location: 7028133
23.02.2019_18:18 Removing already liked medias..
23.02.2019_18:18 Get Media by location: 4014250
23.02.2019_18:18 Except on get_media!
23.02.2019_18:18 Removing already liked medias..
Could not remove media
23.02.2019_18:18 Get Media by location: 7028133
23.02.2019_18:18 Removing already liked medias..

```

#### Config

```
username = USERNAME
password = PASSWORD
like_per_day = 707
comments_per_day = 0
max_like_for_one_tag = 10
follow_per_day = 300
follow_time = 259200
unfollow_per_day = 310
unfollow_break_min = 3
unfollow_break_max = 17
tag_list = ["l:7028133", "l:1028831277", "l:272349856207649", "l:1033653074", "l:297990142", "l:257232678", "l:3761792", "l:275053674", "l:258782591", "l:282449147", "l:335778401", "l:358925822", $
"l:261649551", "l:449220398433220", "l:285632728"]


```

**Comment by waynoedm** [comment]
ERROR:root:get_media_id_by_tag
Traceback (most recent call last):
  File "/root/Instagram/rustico/src/instabot.py", line 658, in get_media_id_by_tag
    all_data = json.loads(r.text)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ericvtheg** [comment]
I was having the same problem for a while. In a different helper method they used a different way of reading the json. I just moved that way into get_media_id_by_tag all worked perfect after.
This is what mine looks like:
`try:
                        r = self.s.get(url_location)
                        all_data = json.loads(r.text)
                        self.media_by_tag = list(
                            all_data["graphql"]["location"]["edge_location_to_media"]["edges"])
                    except:
                        self.media_by_tag = []
                        self.write_log("Except on get_media!")
                        logging.exception("get_media_id_by_tag")`

If yours already looks like that, try this version I used for get_userinfo_by_name:
`try:
                    r = self.s.get(url_info)

                    all_data = json.loads(
                        re.search(
                            "window._sharedData = (.*?);</script>", r.text, re.DOTALL
                        ).group(1)
                    )["entry_data"]["ProfilePage"][0]`

Not the best response, but I hope this helps

**Comment by llemonS** [comment]
same problem, somebody can give a permanent solution please?
