### ISSUE TITLE
I have problem with codes

### ISSUE THREAD

**Issue by proexot** [instabot-py/instabot.py#200]
I will very happy to use this code for my work, I want to follow if who interesting about my work ( tags )

I dont need unfollow someone, I have just tried a few time. I have deleted parts about errors and it works but cant understand work well or not

for example my tag is "game" it start follow and comment someone if who wrote tag game, then again myself wrote tag game and nothing happened.

i need comment them and follow them and like them thats all :)
All time i got error

 File "example.py", line 18
    log_mod=0))

then I have deleted this part :))) for see which error I will have
then that
 File "example.py", line 17, in <module>
    unfollow_break_max=30)
  File "C:\Python34\master\instabot.py", line 157, in **init**
    self.populate_user_blacklist()
  File "C:\Python34\master\instabot.py", line 167, in populate_user_blacklist
    id_user = all_data['user']['media']['nodes'][0]['owner']['id']
IndexError: list index out of range

What can I do ? I need help

[http://i66.tinypic.com/23wtso1.png](url)

**Comment by bobduckling221** [comment]
you need to delete the ['nodes'][0] part in line 167 instabot.py.
And maybe delete self.populate_user_blacklist() in line 157.

I think that's what i did. @proexot

**Comment by polaroi8d** [comment]
@proexot so you still have the problem? If not please close the issue.

**Comment by proexot** [comment]
I have just deleted nodes and 0 in line 167 didnt help me
Traceback (most recent call last):
  File "C:/Python34/instabot.py-master/example.py", line 18, in <module>
    log_mod=0)
  File "C:\Python34\instabot.py-master\instabot.py", line 157, in __init__
    self.populate_user_blacklist()
  File "C:\Python34\instabot.py-master\instabot.py", line 167, in populate_user_blacklist
    id_user = all_data['user']['media']['owner']['id']
KeyError: 'owner'



And I have deleted line 157 it worked.

My question so i must add again nodes 0 area ??
And second question
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Couldn't find caption - not liking
Trying to like media: 1354975840026622641
Liked: 1354975840026622641. Like #1.

All is fine ? i mean find caption - not liking is not an error right ?

**Comment by fire829** [comment]
I have the same issue. It appears when I have blacklisted user, who have no posts (media) in his account. So code crashed because all_data does not have nodes in media array. It for example can be simply checked by all_data['user']['media']['count'] == 0

**Comment by fire829** [comment]
And I think it's strange way to get user id in populate_user_blacklist() routine (in instabot.py). Why to use user_id of first media? user_id simply present in user data, as far as I can see.
So, we can replace this code:
id_user = all_data['user']['media']['nodes'][0]['owner']['id']

to this:
id_user = all_data['user']['id']


It works for me.

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
