### ISSUE TITLE
Pause feature

### ISSUE THREAD

**Issue by manguszta** [instabot-py/instabot.py#2003]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Description of your issue

This has been an issue recently. I'm running 4-5 accounts on my PC. I start them on my workplace, then after work I just put my PC to sleep mode and bring it home, bots continue running. I purposely start running the bots from my workplace on different times, but from home, all continue in the same time.  Basically everything was fine until last weekend. Instagram somehow now detects that I use the bot from a different IP and put a 24-hour ban on all accounts.

I was thinking about a manual user-controlled pause feature (like pressing space). I would just pause the bots from my workplace before leaving, and start them again from home (in different starting times), perhaps Instagram wouldn't detect this as a suspicious action.

I'm not an expert to Python, can't code it myself, but I would really appreciate this upgrade.

**Comment by dimisdas** [comment]
If I may ask, could you not simply shut down the bots and restart them again once you’re home?

Given that sessions are enabled by default, the bots wouldn’t have to relogin.

**Comment by manguszta** [comment]
@dimisdas Well, the bots run until a random number of likes, follows and unfollows. I don't want to shut down the bots, as on a restart I won't know how many likes, follows, unfollows I made already with them.

**Comment by dimisdas** [comment]
It’s understandable how this might have been misunderstood. The _per_day parameters actually set an interval. For example,

86400 seconds in a day
divided by
1000 likes per day 
——————————
One like per 86,4 seconds

The bot is not actually “counting” or compensating for likes. It simply sets a timer for when the next like/comment/follow should happen.

**Comment by manguszta** [comment]
Oh, yes, I forgot that I have set a maximum number of likes, follows and unfollows. This maximum number is randomized in the configure files. As soon as maximum number is reached, bot stops that certain feature.

`
# ------------------- Like -------------------
                if self.banned == True and time.time() > self.ban_end_time:
                    self.banned = False
                    self.error_400 = 0
                    self.ban_end_time = 0
                    self.write_log("  [!] Safety shutdown ends! Liking begins...")
                elif self.banned == True:
                    self.next_iteration["Like"] = time.time() + self.add_time(self.like_delay)
                if self.banned == False:
                    if self.like_counter < self.max_like_per_day:
                        self.new_auto_mod_like()
                    elif self.like_counter == self.max_like_per_day:
                        self.write_log("MAXIMUM NUMBER OF LIKES IS REACHED: %s" % (self.max_like_per_day))
                        self.max_like_per_day -= 1
                        self.stop_like = True
                    else:
                        self.next_iteration["Like"] = time.time() + self.add_time(self.like_delay)
                # ------------------- Follow -------------------
                if self.follow_counter < self.max_follow_per_day:
                    if self.banned == True and time.time() > self.next_iteration["Follow"]:
                        self.get_media_id_by_tag(random.choice(self.tag_list))
                    self.new_auto_mod_follow()
                elif self.follow_counter == self.max_follow_per_day:
                    self.write_log("MAXIMUM NUMBER OF FOLLOWS IS REACHED: %s" % (self.max_follow_per_day))
                    self.max_follow_per_day -= 1
                    self.stop_follow = True
                else:
                    self.next_iteration["Follow"] = time.time() + self.add_time(self.follow_delay)
                # ------------------- Unfollow -------------------
                if self.unfollow_counter < self.max_unfollow_per_day:
                    self.new_auto_mod_unfollow()
                elif self.unfollow_counter == self.max_unfollow_per_day:
                    self.write_log("MAXIMUM NUMBER OF UNFOLLOWS IS REACHED: %s" % (self.max_unfollow_per_day))
                    self.max_unfollow_per_day -= 1
                    self.stop_unfollow = True
                else:
                    self.next_iteration["Unfollow"] = time.time() + self.add_time(self.unfollow_delay)
                # ------------------- Comment -------------------
                if self.comments_counter < self.max_comment_per_day:
                    self.new_auto_mod_comments()
                elif self.comments_counter == self.max_comment_per_day:
                    self.write_log("MAXIMUM NUMBER OF COMMENTS IS REACHED: %s" % (self.max_comment_per_day))
                    self.max_comment_per_day -= 1
                    self.stop_comment = True
                else:
                    self.next_iteration["Comments"] = time.time() + self.add_time(self.comments_delay)
                # ------------------- Logout(?) -------------------
                if self.stop_comment == True and ((self.stop_follow == True or self.stop_unfollow == True) and self.stop_like == True):
                    self.logout()
`

**Comment by dimisdas** [comment]
I have no idea what you posted. You have modded I presume the bot in some way? 

You’re not using the official version? Which build is this based on?

**Comment by manguszta** [comment]
Yes, it's modded, uses InstagramAPI.py too for a complete list of followings, to get rid of only those accounts that don't follow back (certain modes didn't seem to work perfectly, that's why I altered the code). I keep following the necessary changes only. As I said I'm not an expert, but I personalized the bot to my needs. I just have zero idea how to add this pause feature :) I thought it would be useful to others too, that's why I opened this 'issue'.

**Comment by dimisdas** [comment]
Given how this not an issue in the current build (the bot will simply follow an interval),  I cannot see why it would be a good fit *project wide*. Sessions, as I said, are enabled by default. The bot doesn’t have to relogin and will simply continue after a restart, not prompting a challenge.

However, I wouldn’t mind helping you, even if my vote is to not include this feature.

My suggestion is to save in the database or in a file the persistent values for the counters you’re using. That way, when the bot resumes after a crash, sleep, or restart, it can load from disk your last used counters. You should also add on the cleanup function a reset mechanism. 

I’ll be closing this issue now but feel free to comment, we will still receive your responses.

Cheers!
