### ISSUE TITLE
Like Action blocked on Cloud Hosting

### ISSUE THREAD

**Issue by alaintainguyen** [instabot-py/instabot.py#2007]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

#### Environment
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [X] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
```
python3.6
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
Hello guys,
When I start the bot on Cloud hosting, Some minute / hours later, 
my Like action is blocked.
Even if I put 100 or 400 likes / day

But it works perfectly on my computer with 700 for example
```

#### Config

```
```

**Comment by dimisdas** [comment]
Instagram probably detects that you're using a VPS from the IP and enforcing restrictions. Unfortunately, there's nothing you can do, unless you can use a private proxy or a local server.
