### ISSUE TITLE
Syntax Error: Invalid Character in Identifier

### ISSUE THREAD

**Issue by ghastinzer** [instabot-py/instabot.py#2010]
I'm running Mac OS 10.10, Python 3.7, PIP 18 with the newest instabot. Why doesn't it like my username?

Last login: Tue Feb 26 16:05:41 on ttys000
iMacs-iMac:~ iMac$ cd
iMacs-iMac:~ iMac$ cd desktop
iMacs-iMac:desktop iMac$ cd juxdesign
iMacs-iMac:juxdesign iMac$ python3 design.py
  File "design.py", line 13
    login=“myusername”,
                           ^
**SyntaxError: invalid character in identifier**

Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ X] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ X] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [ X] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by ghastinzer** [comment]
So if anyone is having the same problem, I did manage to fix it. The quotation marks were the wrong ones. Once I replaced the characters on the username and password, it finally started working.

"" <---- correct quotation marks
“” <---- wrong quotation marks

**Comment by dimisdas** [comment]
Glad to hear it's working now :)
