### ISSUE TITLE
How does the follow / unfollow work?

### ISSUE THREAD

**Issue by PikaLink89** [instabot-py/instabot.py#2012]
Hi, can someone explain to me how follow / unfollow works?

follow_per_day=200,
    follow_time=5 * 60 * 60,
    unfollow_per_day=200,
    unlike_per_day=0,
    unfollow_recent_feed=True,  # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
 
    unfollow_break_min=15,
    unfollow_break_max=30,

follow per day 200 but how does time work? And.. what is break min and max? 
What configuration do you recommend?

I run 12 hours, I did Control + C to exit and after a while a message appears "pausing for 5 minutes to avoid getting baned", is that bad?

Thanks

**Comment by dimisdas** [comment]
Hi, This question is more suitable for our Telegram group, or maybe Facebook. Thank you, and hope to see you there :)
