### ISSUE TITLE
Already followed before

### ISSUE THREAD

**Issue by netobor** [instabot-py/instabot.py#2017]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X ] Technical Help
- [ ] Other

#### Environment
- [ X] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [X ] Linux (include flavour) Amazon
- [ ] Android (include terminal)

#### Python Version Requirement
- [X ] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 2.7.15
Python 3.6.7
```

#### Pip Version?
```
pip 9.0.3 from /usr/lib/python2.7/dist-packages (python 2.7)
pip 19.0.3 from /home/ec2-user/.local/lib/python3.6/site-packages/pip (python 3.6)
```

#### Description of your issue
```01.03.2019_18:19 Get Media by location: 3190091
01.03.2019_18:19 Removing already liked medias..
01.03.2019_18:19 Already followed before 1100871602
01.03.2019_18:19 Get Media by location: 3190091```

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config
```
[DEFAULT]
username = none
password = none
like_per_day = 709
comments_per_day = 31
max_like_for_one_tag = 36
follow_per_day = 310
follow_time = 3600
unfollow_per_day = 297
unfollow_break_min = 3
unfollow_break_max = 17
log_mod = 0
proxy = 
comment_list = [["this", "the", "your"], ["photo", "picture", "pic", "shot", "snapshot"], ["is", "looks", "feels", "is really"], ["great", "super", "good", "very good", "good", "wow", "WOW", "cool", "GREAT", "magnificent", "magical", "very cool", "stylish", "beautiful", "so beautiful", "so stylish", "so professional", "lovely", "so lovely", "very lovely", "glorious", "so glorious", "very glorious", "adorable", "excellent", "amazing"], [".", "..", "...", "!", "!!", "!!!"]]
tag_list = ["follow4follow", "f4f", "cute", "l:212999109"]
tag_blacklist = ["rain", "thunderstorm"]
unwanted_username_list = ["second", "stuff", "art", "project", "love", "life", "food", "blog", "free", "keren", "photo", "graphy", "indo", "travel", "art", "shop", "store", "sex", "toko", "jual", "online", "murah", "jam", "kaos", "case", "baju", "fashion", "corp", "tas", "butik", "grosir", "karpet", "sosis", "salon", "skin", "care", "cloth", "tech", "rental", "kamera", "beauty", "express", "kredit", "collection", "impor", "preloved", "follow", "follower", "gain", ".id", "_id", "bags"]
unfollow_whitelist = ["example_user_1", "example_user_2"]

[user]
username = "user"
password = "pass"
like_per_day = 0
comments_per_day = 0
max_like_for_one_tag = 1
follow_per_day = 310
follow_time = 0
unfollow_per_day = 0
unfollow_break_min = 0
unfollow_break_max = 0
tag_list = ["l:3190091"]
```

```
I saw other issues, I checked that they are closed, I made the clone yesterday and I made the configuration, I also saw that it was updated in January but I did not understand how to solve this question, could it explain better?
```

**Comment by waynoedm** [comment]
The feeds for the location aren't large so you have a smaller pool to follow and like. So that is going to happen. And you max max like for tag set to 1. Increase that and you may see more results.

I have the same issue with a bunch of my locations that I have set. Went through all the recent media in less than a day. Now I have to wait for summer before they hit the beaches again before I'll see any new content. ;)

**Comment by netobor** [comment]
> The feeds for the location aren't large so you have a smaller pool to follow and like. So that is going to happen. And you max max like for tag set to 1. Increase that and you may see more results.
> 
> I have the same issue with a bunch of my locations that I have set. Went through all the recent media in less than a day. Now I have to wait for summer before they hit the beaches again before I'll see any new content.

Hello, waynoedm, 
Thank you, I understood, I believed that he searched for all users who had already posted a photo in the location and not recent.

I'll take the test and increase the max like

**Comment by dimisdas** [comment]
@netobor Any luck?

**Comment by netobor** [comment]
> @netobor Any luck?

Yes, it improved well, increasing the locations and like photos.

Sorry for the delay in answering I was able to change only on Wednesday.

As said he believed that he checked all the history and not the recent photos.

Many Thanks!
