### ISSUE TITLE
Opens then crashes

### ISSUE THREAD

**Issue by marzoonobrega** [instabot-py/instabot.py#2019]
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ x] macOS
- [ x] Windows
- [ ] Linux (include flavour)
- [x] Android (include terminal)

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Description of your issue
Just opens the code and then crashes the code was working before I updated. Download the code a retried twice and still have the same problem.

**Comment by tanjilrahman** [comment]
I'm also facing the same problem!

**Comment by dimisdas** [comment]
What's the error? Where's the config you're using? What is the exact python version? Is there anything in error.log?

How am I supposed to help? Please fill the template and resubmit.
