### ISSUE TITLE
Traceback errors after a fresh installation

### ISSUE THREAD

**Issue by francescogosce** [instabot-py/instabot.py#2025]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (Raspberry Pi 3)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
3.7.2

Include here the response of 'python --version' or 'python3 --version'

Python 2.7.13
Python 3.7.2

#### Pip Version?
19.0.3

Include here the response of 'pip --version' or 'pip3 --version'

Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main

#### Description of your issue
Since I flashed a fresh NOOBS version on my Pi 3 this morning I am not able to run instabot anymore.
May I forget something?

Traceback (most recent call last):
  File "example.py", line 4, in <module>
    from instabot_py import InstaBot
  File "/home/pi/Desktop/instabot.py-master/instabot_py/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/pi/Desktop/instabot.py-master/instabot_py/instabot.py", line 17, in <module>
    import sqlite3
  File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

<img width="1680" alt="Schermata 2019-03-10 alle 19 24 51" src="https://user-images.githubusercontent.com/12472983/54089560-631dc300-436a-11e9-8709-f143af769f97.png">

**Comment by dimisdas** [comment]
You'll have to follow this guide. There are packages missing in your Python installation. You must install the -dev libraries first, and recompile anew in order to include them in Python.

https://github.com/instabot-py/instabot.py/wiki/Raspberry-Pi-Python-3.7---Read-This

**Comment by francescogosce** [comment]
> You'll have to follow this guide. There are packages missing in your Python installation. You must install the -dev libraries first, and recompile anew in order to include them in Python.
> 
> https://github.com/instabot-py/instabot.py/wiki/Raspberry-Pi-Python-3.7---Read-This

TY I'm gonna fix it! I also have downloaded the new instant.py zip and I can't see requirements.tx anymore! Has it been moved to another folder?

**Comment by dimisdas** [comment]
Use` pip3 install -e .` instead
