### ISSUE TITLE
Failed to load module instaloader

### ISSUE THREAD

**Issue by mbaker95** [instabot-py/instabot.py#2026]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 
https://github.com/instabot-py/instabot.py/issues/2009

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour) MINT
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
Python 3.6.2
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
pip 19.0.3 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
```

#### Description of your issue
Failing to load modules when trying to run run.py or example.py
I used pip3.6 to install packages, I also used python3.6 when running programs. 
I've tried using python 3.7 as it worked for someone that had the same issue but I've had no luck.
I've also tried uninstalling and installing instaloader but i've had no luck.

Requirement already satisfied: instaloader==4.2.1 in /usr/local/lib/python3.6/site-packages (from -r requirements/base.txt (line 2)) (4.2.1)

```
Failed to load module instaloader. Make sure you have installed correctly dependencies in requirements.txt.
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by dimisdas** [comment]
What's the output of `python3.7 -m instaloader` ? 

How did you install 3.7, did you compile it yourself? 

Thanks

**Comment by mbaker95** [comment]
The output is 
/usr/local/bin/python3.7: No module named instaloader

Yes, excuse my ignorance I believe I compiled it myself here's what I used.
https://tecadmin.net/install-python-3-7-on-ubuntu-linuxmint/

Thank you

**Comment by dimisdas** [comment]
Try to install all prerequisites, including some not mentioned in the guide you linked:

```
sudo apt-get update -y
sudo apt-get install build-essential tk-dev libncurses5-dev libncursesw5-dev libreadline6-dev libdb5.3-dev libgdbm-dev libsqlite3-dev libssl-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev libffi-dev -y

```

and after downloading the libraries above, follow Step 2  again (download source, recompile).

Then head into the Instabot.py directory and try `pip3.7 install -e .`

**Comment by mbaker95** [comment]
Working! Thank you

**Comment by Molar3NK** [comment]
I got the same issue but on Mac ????
