### ISSUE TITLE
Unfollow All Except Those on Whitelist

### ISSUE THREAD

**Issue by spinstonchurchill** [instabot-py/instabot.py#2029]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [ x] Linux (include flavour) Raspbian
- [ ] Android (include terminal)

#### Python Version Requirement
- [ x] I am using Python 3.6 or above

#### Exact Python Version?
``` 
Include here the response of 'python --version' or 'python3 --version'
``` python3 -- 3.7.2

#### Pip Version?
``` 
Include here the response of 'pip --version' or 'pip3 --version'
pip -- 9.0.1
```

#### Looking for a mode that will allow me to unfollow all currently following, regardless of follow-back status, except for those on the whitelist.

Mode 0 currently recognizes the whitelist, but will not unfollow users who are also following me. 

Mode 5, which I would expect to use for this, unfortunately does not. 

Any ideas? Thank you!

```

```

#### Config

```

```

**Comment by dimisdas** [comment]
This has just been reintroduced. 

Use the new version (install via pip), and add to your config "unfollow_everyone=True" and "unfollow_recent_feed=True"
