### ISSUE TITLE
Can't start Python cmd closed after wanna start directly

### ISSUE THREAD

**Issue by Legendary1989** [instabot-py/instabot.py#2030]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
``` Python 3.7.2
Include here the response of 'python --version' or 'python3 --version'
```Python 3.7.2

#### Pip Version?
```pip3 i think
Include here the response of 'pip --version' or 'pip3 --version'
```pip3 i think

#### Description of your issue

```i try to start python 3.7.2 after i downloaded it and install it....changed the python order have to download zip order and changed....take in password and name ....so wanna start cmd window shows momently and closed direckly no pproblems ....whre show me...so i dont know what i can do....pls help 
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by dimisdas** [comment]
I'm not able to help without sufficient data or error messages. I don't know which python or pip version you're using (you think), or what your config is. 

I think it's best to join the [Telegram group](
https://t.me/joinchat/DYKH-0G_8hsDDoN_iE8ZlA) and ask help over there. People would be able to guide you in real time :)

Hope it gets resolved, good luck!
