### ISSUE TITLE
still getting "failed to load module instaloader" error after updating

### ISSUE THREAD

**Issue by bathieu** [instabot-py/instabot.py#2031]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. #2009 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```python 3.7.0

#### Pip Version?
```pip 19.0.3

#### Description of your issue

``` when i try to run any of the python files (even example) i get the error that my requirements arent installed correctly. i tried following the video tutorial and used pip3 to install requirements but it still isnt working? im new to this i apologize 

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < C:\Users\kaiem\Downloads\instabot.py-master>python run.py
Failed to load module instaloader. Make sure you have installed correctly dependencies in requirements.txt.
C:\Users\kaiem\Downloads\instabot.py-master>pip3 install -r requirements.txt
Requirement already satisfied: requests in c:\users\kaiem\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 1)) (2.19.1)
Requirement already satisfied: fake-useragent in c:\users\kaiem\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 2)) (0.1.10)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\kaiem\appdata\local\programs\python\python37\lib\site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kaiem\appdata\local\programs\python\python37\lib\site-packages (from requests->-r requirements.txt (line 1)) (2018.8.24)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in c:\users\kaiem\appdata\local\programs\python\python37\lib\site-packages (from requests->-r requirements.txt (line 1)) (1.23)
Requirement already satisfied: idna<2.8,>=2.5 in c:\users\kaiem\appdata\local\programs\python\python37\lib\site-packages (from requests->-r requirements.txt (line 1)) (2.7)

```

**Comment by dimisdas** [comment]
There's no requirements.txt file anymore in the latest update. 

Please try `python -m instaloader` and post the output.

**Comment by bathieu** [comment]
> C:\Users\kaiem\AppData\Local\Programs\Python\Python37\python.exe: No module named instaloader

I tried following tutorials to figure out why its not installed but I still can't figure it out, I even reinstalled instabot.py
Should I try reinstalling Python?

**Comment by bathieu** [comment]
oh, I think I made a typo/error when installing instaloader but I got it figured out. the program still isnt running but the error is gone. I think it may be because instagram has been down today?

**Comment by dimisdas** [comment]
Could be, instagram and facebook have been down for 14+ hours.

Let us know if another error arrises, otherwise feel free to close this issue if everything works fine.

**Comment by dimitristzam** [comment]
I get this error too
C:\Users\dimit\AppData\Local\Programs\Python\Python36-32\python.exe: No module named instaloader
