### ISSUE TITLE
Login without username/ password

### ISSUE THREAD

**Issue by tobeyond** [instabot-py/instabot.py#2032]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.1
```

#### Pip Version?
```
pip 18.1
```

#### Description of your issue

```
I would like to login to my account using only the session id (I've seen it in a website and a goland script, but I don't know how to translate it to Python), without my username and password informations. I saw this https://github.com/instabot-py/instabot.py/issues/475, but it didn't really helped me out.  
Is is possible to add this feature? So I don't start the script with bot = InstaBot('login', 'password'), but bot = InstaBot(sessionid = SESSIONID).
Thank you.
```

**Comment by dimisdas** [comment]
If session file is enabled, then it will load it. You can unpickle it and see what's included. You'll need to repickle it before saving it.

**Comment by tobeyond** [comment]
I will try, thanks.
