### ISSUE TITLE
Like by hashtags it's not working

### ISSUE THREAD

**Issue by jeffsnow88** [instabot-py/instabot.py#2033]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [ x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [ ] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```
Hi, I'm running default configuration. Using python like_hashtags.py, console shows that it's putting like on the posts, but if you check your activity on Instagram app/website by "posts I have liked" it doesn't show anything. I'm wondering if this function of the Instagram bot is actually working. Anyone facing that?
#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by jinnoflife** [comment]
> I'm wondering if this function of the Instagram bot is actually working.

It is actually working. Just checked the media.
I'm running it with:
* `Python 3.7.2`
* `pip 19.0.3`

**Comment by dimisdas** [comment]
You are using a different bot https://github.com/instagrambot/instabot
