### ISSUE TITLE
Dockerfile using old requirements.txt

### ISSUE THREAD

**Issue by Recharger** [instabot-py/instabot.py#2034]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour) (18.04)
- [ ] Android (include terminal)

**Comment by ycodryn** [comment]
I was thinking about same thing and thank you that you already post it.

**Comment by dimisdas** [comment]
Project is on PyPi now and can be installed from there.

If anyone’s interested in changing the docker file and making a PR that would be really appreciated.
