### ISSUE TITLE
Instagram is Down - Bot crashes response status 500

### ISSUE THREAD

**Issue by EducatedMF** [instabot-py/instabot.py#2037]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ X] Bug
- [ ] Feature Request
- [X ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [X ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X ] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue
Response Status:  500
===============
Response Content:
 Oops, an error occurred.

===============
Response Header:
 {'Content-Type': 'text/html; charset=utf-8', 'Vary': 'Accept-Language, Cookie', 'Content-Language': 'en', 'Access-Control-Allow-Origin': 'https://www.instagram.com', 'Access-Control-Allow-Credentials': 'true', 'Date': 'Wed, 13 Mar 2019 19:51:01 GMT', 'Strict-Transport-Security': 'max-age=2592000', 'Cache-Control': 'private, no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': 'Sat, 01 Jan 2000 00:00:00 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'content-security-policy': "report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src https: data: blob:; font-src https: data:; media-src 'self' blob: https://www.instagram.com https://*.cdninstagram.com https://*.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://*.cdninstagram.com wss://www.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://*.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://*.www.instagram.com https://graph.instagram.com https://*.graph.instagram.com https://*.cdninstagram.com https://api.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://*.facebook.com https://*.fbcdn.net https://*.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests", 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'Set-Cookie': 'csrftoken=""; Domain=instagram.com; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/, csrftoken=""; Domain=.instagram.com; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/, csrftoken=""; Domain=i.instagram.com; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/, csrftoken=""; Domain=.i.instagram.com; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/, csrftoken=""; Domain=www.instagram.com; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/, csrftoken=""; Domain=.www.instagram.com; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/, csrftoken=""; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/', 'Connection': 'keep-alive', 'Content-Length': '25'}
===============
13.03.2019_20:48 Exit Program... GoodBye

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by BartekChojnacki** [comment]
Hello,

I've got the same issue:

[ec2-user@darkstar instabot.py]$ python3 run.py
     _________LOGIN_________
     (To change user settings, type "config")

     Please enter your username: XXX
     Loading settings for XXX!
     (Tip: Log in directly by running 'run.py XXX)'


     >>> Starting bot >>>
________________________________________________
13.03.2019_20:57 Checking for updates...
13.03.2019_20:57 You are running the latest stable version
13.03.2019_20:57 Instabot v1.2.3/0 started at 13.03.2019 20:57:
13.03.2019_20:57 Trying to login as XXX...
13.03.2019_20:57 Request didn't return 200 as status code!
13.03.2019_20:57 Here is more info for debbugin or creating an issue
===============
Response Status:  500
===============
Response Content:
 Oops, an error occurred.

===============
Response Header:
 {'Content-Type': 'text/html; charset=utf-8', 'Vary': 'Cookie', 'Set-Cookie': 'csrftoken=wBTJWZJAfBoY0a7VGA29T47YIPWk7287; expires=Wed, 11-Mar-2020 19:57:18 GMT; Max-Age=31449600; Path=/; Secure', 'Date': 'Wed, 13 Mar 2019 19:57:18 GMT', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive'}
===============
13.03.2019_20:57 Exit Program... GoodBye

**Comment by nachovoss** [comment]
Same happened to me when I tried to run example.py from Git Bash, 
on Windows terminal it logged in, but is running  with some trouble on the like protocol
500 error
here is what i'm getting:

13.03.2019_21:19 Trying to follow: 8070720293
13.03.2019_21:19 Trying to comment: 1998905510595607070
13.03.2019_21:19 Trying to like media: 1998905510595607070
                 https://www.instagram.com/p/Bu9ifiinzoe/
13.03.2019_21:19 Not liked: 500 message Oops, an error occurred.

13.03.2019_21:19 Trying to like media: 1998901597066732964
                 https://www.instagram.com/p/Bu9hmlyH6Wk/
13.03.2019_21:19 Liked: 1998901597066732964. Like #1.
13.03.2019_21:19 therealnachovossler : Get media id on recent feed
13.03.2019_21:19 Media in recent feed = 12
13.03.2019_21:19 Trying to unfollow #1:
13.03.2019_21:19 Getting user info : caroline_cabiro
13.03.2019_21:21 Get Media by tag: detroittechno
13.03.2019_21:21 Removing already liked medias..
13.03.2019_21:21 Trying to like media: 1998761530238665054
                 https://www.instagram.com/p/Bu9BwWYl4Fe/
13.03.2019_21:21 Not liked: 500 message Oops, an error occurred.

13.03.2019_21:21 Trying to like media: 1998762687286570082
                 https://www.instagram.com/p/Bu9CBL-BWxi/
13.03.2019_21:21 Liked: 1998762687286570082. Like #2.
13.03.2019_21:22 Get Media by tag: mix
13.03.2019_21:22 Removing already liked medias..
13.03.2019_21:22 Trying to like media: 1998835127833877026
                 https://www.instagram.com/p/Bu9SfVfHFoi/
13.03.2019_21:22 Liked: 1998835127833877026. Like #3.
13.03.2019_21:22 Trying to follow: 5494310708

All help will be much appreciated 
peace :)

**Comment by ycodryn** [comment]
Mine is not crashing but I`m getting Not liked: 500 message and when trying to comment nothing happens.

2019-03-13 21:02:52 | stdout | 13.03.2019_21:02 Not liked: 500 message Oops, an error occurred.
-- | -- | --
2019-03-13 21:02:51 | stdout | https://www.instagram.com/p/Bu8-qKLFs5w/
2019-03-13 21:02:51 | stdout | 13.03.2019_21:02 Trying to like media: 1998747910670831216
2019-03-13 21:02:50 | stdout |  
2019-03-13 21:02:50 | stdout | 13.03.2019_21:02 Not liked: 500 message Oops, an error occurred.
2019-03-13 21:02:50 | stdout | https://www.instagram.com/p/Bu8-spgFhaG/
2019-03-13 21:02:50 | stdout | 13.03.2019_21:02 Trying to like media: 1998748081748055686
2019-03-13 21:02:49 | stdout |  
2019-03-13 21:02:49 | stdout | 13.03.2019_21:02 Not liked: 500 message Oops, an error occurred.

**Comment by waynoedm** [comment]
Started happening today for me as well on a couple accounts.

**Comment by ycodryn** [comment]
I read news from internet I think is not the bot but the instagram and facebook, they are having problems.

**Comment by waynoedm** [comment]
Could be. Logging in on android, I was having issues getting status updates on two account. They were getting the 500 errors. I am now getting status updates and appears as of twenty minutes ago, the errors have decreased.

**Comment by tobeyond** [comment]
I got the same here:

`>>> Starting bot >>>

13.03.2019_20:37 Checking for updates...
13.03.2019_20:37 You are running the latest stable version
13.03.2019_20:37 Instabot v1.2.3/0 started at 13.03.2019 20:37:
13.03.2019_20:37 Trying to login as ...
13.03.2019_20:37 Request didn't return 200 as status code!
13.03.2019_20:37 Here is more info for debbugin or creating an issue

Response Status: 500

Response Content:
Oops, an error occurred.

Response Header:
{'Content-Type': 'text/html; charset=utf-8', 'Vary': 'Accept-Language, Cookie', 'Content-Language': 'en', 'Access-Control-Allow-Origin': 'https://www.instagram.com', 'Access-Control-Allow-Credentials': 'true', 'Date': 'Wed, 13 Mar 2019 23:37:51 GMT', 'Strict-Transport-Security': 'max-age=2592000', 'Cache-Control': 'private, no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': 'Sat, 01 Jan 2000 00:00:00 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'content-security-policy': "report-uri https://www.instagram.com/security/csp_report/; default-src 'self' https://www.instagram.com; img-src https: data: blob:; font-src https: data:; media-src 'self' blob: https://www.instagram.com https://.cdninstagram.com https://.fbcdn.net; manifest-src 'self' https://www.instagram.com; script-src 'self' https://instagram.com https://www.instagram.com https://.www.instagram.com https://.cdninstagram.com wss://www.instagram.com https://.facebook.com https://.fbcdn.net https://.facebook.net 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' https://.www.instagram.com https://www.instagram.com 'unsafe-inline'; connect-src 'self' https://instagram.com https://www.instagram.com https://.www.instagram.com https://graph.instagram.com https://.graph.instagram.com https://.cdninstagram.com https://api.instagram.com wss://www.instagram.com wss://edge-chat.instagram.com https://.facebook.com https://.fbcdn.net https://.facebook.net chrome-extension://boadgeojelhgndaghljhdicfkmllpafd; worker-src 'self' blob: https://www.instagram.com; frame-src 'self' https://instagram.com https://www.instagram.com https://staticxx.facebook.com https://www.facebook.com https://web.facebook.com https://connect.facebook.net https://m.facebook.com; object-src 'none'; upgrade-insecure-requests", 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'Set-Cookie': 'rur=ATN; Domain=.instagram.com; HttpOnly; Path=/; Secure, csrftoken= XXXXXXXX; Domain=.instagram.com; expires=Wed, 11-Mar-2020 23:37:51 GMT; Max-Age=31449600; Path=/; Secure', 'Connection': 'keep-alive', 'Content-Length': '25'}

13.03.2019_20:37 Exit Program... GoodBye`

**Comment by Willies31** [comment]
I have exactly the same issue...what is weird for me is that with the previous instabot version, i dont have this logging problem...

**Comment by waynoedm** [comment]
Getting the error on all four bots that I am running right now. Bot still seems to like, follow, and unfollow so unsure of how much of the problem this is, or the overall effect on likes.

Perhaps new limits put in place to limit bot traffic? Related to other instagram problems earlier in the day?

**Comment by waynoedm** [comment]
Logs showing the messages cleared up between 7- 8pm MST for all of my accounts as of now. Last one was a half hour ago. 51 minutes ago on another, and 1:51 for another.

**Comment by dimisdas** [comment]
This is an issue with Facebook and Instagram. They have been down for 14 hours, one of the longest outages.

https://www.cnet.com/news/cant-update-status-facebook-and-instagram-are-down/

**Comment by tobeyond** [comment]
Alright, today it's fine.
