### ISSUE TITLE
clarifai 2.6.1 has requirement jsonschema<3,>=2.5

### ISSUE THREAD

**Issue by lepri13** [instabot-py/instabot.py#2038]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (Ubuntu 18.04)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
Python 3.6.7
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
pip 19.0.3 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
```

#### Description of your issue

```
Repo steps:
Install default 18.04 Ubuntu from digital ocean
git clone https://github.com/InstaPy/instapy-quickstart.git
cd instapy-quickstart/installation/Linux/
sh install.sh
most of the install runs fine I get:
clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.
press any key to complete install

Looking around there isnt any clear ways around it.
```

#### Config

```
Not applicable
```

**Comment by dimisdas** [comment]
You are using a different bot. This is the wrong repo to submit this issue.
