### ISSUE TITLE
HOW TO LIKE CERTAIN HASHTAGS IN LOCATION RATHER THEN ALL IN LOCATION

### ISSUE THREAD

**Issue by MoneyMikeOttawa** [instabot-py/instabot.py#2039]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x ] Feature Request
- [x ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [ x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

 HEY GUYS, SO I KEEP GETTING BANNED BECAUSE I RUN A CANNABIS PAGE AND WHEN I FOLLOW JUST A LOCATION THE HATERS KEEP REPORTING ME - IS TEHRE A WAY TO LIKE CERTAIN HASHTAGS BUT BASE IT IN A CERTAIN LOCATION? THANK!

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by dimisdas** [comment]
There's not. Sorry.
