### ISSUE TITLE
Couldn't comment post, resuming. Instabot

### ISSUE THREAD

**Issue by ZdravkoDimov** [instabot-py/instabot.py#2045]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows 10
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
3.6.3
```

#### Pip Version?
19.0.3
```

#### Description of your issue

```
Hi. Today I tried in hours to fix the problem, read everything (2 similar questions), but the problem is still there. I upgrade my pip version, reinstall the packet with the bot (python) files several times, of course, download python. Tried this(https://github.com/instabot-py/instabot.py/issues/1908) also several times. But the error: 
Couldn't comment post, resuming.
is still there. I don't know what to do. Please help me, I would be thankful.
```

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from instabot_py import InstaBot

bot = InstaBot(
    login="user",  # Enter username (lowercase). Do not enter email!
    password="user",
    like_per_day=2000,
    comments_per_day=20,
    tag_list=["javascript", "webdeveloper", "webdevelopment"],
    tag_blacklist=["rain", "thunderstorm"],
    user_blacklist={},
    max_like_for_one_tag=100,
    follow_per_day=300,
    follow_time=1 * 60 * 60,
    unfollow_per_day=0,
    unlike_per_day=0,
    unfollow_recent_feed=True,
    # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
    time_till_unlike=3 * 24 * 60 * 60,  # 3 days
    unfollow_break_min=15,
    unfollow_break_max=30,
    user_max_follow=0,
    # session_file=False, # Set to False to disable persistent session, or specify custom session_file (ie ='myusername.session')
    user_min_follow=0,
    log_mod=0,
    proxy="",
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[
        ["this", "the", "your"],
        ["photo", "picture", "pic", "shot"],
        ["is", "looks", "is really"],
        [
            "great",
            "super",
            "good",
            "very good",
            "good",
            "wow",
            "WOW",
            "cool",
            "GREAT",
            "magnificent",
            "magical",
            "very cool",
            "stylish",
            "beautiful",
            "so beautiful",
            "so stylish",
            "so professional",
            "excellent",
            "amazing"
        ],
        [".", "ðŸ™Œ", "... ðŸ‘", "!", "! ðŸ˜", "ðŸ˜Ž"]
    ],
    # Use unwanted_username_list to block usernames containing a string
    # Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    # 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        "second",
        "stuff",
        "art",
        "project",
        "love",
        "life",
        "food",
        "blog",
        "free",
        "keren",
        "photo",
        "graphy",
        "indo",
        "travel",
        "art",
        "shop",
        "store",
        "sex",
        "toko",
        "jual",
        "online",
        "murah",
        "jam",
        "kaos",
        "case",
        "baju",
        "fashion",
        "corp",
        "tas",
        "butik",
        "grosir",
        "karpet",
        "sosis",
        "salon",
        "skin",
        "care",
        "cloth",
        "tech",
        "rental",
        "kamera",
        "beauty",
        "express",
        "kredit",
        "collection",
        "impor",
        "preloved",
        "follow",
        "follower",
        "gain",
        ".id",
        "_id",
        "bags",
    ],
    unfollow_whitelist=["example_user_1", "example_user_2"],
    # Enable the following to schedule the bot. Uses 24H
    # end_at_h = 23, # Hour you want the bot to stop
    # end_at_m = 30, # Minute you want the bot stop, in this example 23:30
    # start_at_h = 9, # Hour you want the bot to start
    # start_at_m = 10, # Minute you want the bot to start, in this example 9:10 (am).
)

bot.mainloop()

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by ZdravkoDimov** [comment]
Please help me! Today I moved the bot on my android device, so I won't need to buy Raspberry, because it will work on the background of my phone. Amazing! But even on another operating system, the problem is still there. It just can't comment. Have a powerful day!!

**Comment by dimisdas** [comment]
Can you post the output before and after the error? ±20 lines

**Comment by ZdravkoDimov** [comment]
23.03.2019_19:45 Checking for updates...
23.03.2019_19:45 You are running the latest stable version
23.03.2019_19:45 Instabot v1.2.5/0 started at 23.03.2019 19:45:
23.03.2019_19:45 Found session file MYUSERNAME.session
23.03.2019_19:45 MYUSERNAME login success!

23.03.2019_19:45 Saving cookies to session file MYUSERNAME.session
23.03.2019_19:45 Get Media by tag: javascript
23.03.2019_19:45 Trying to like media: 2006077824397989285
                 https://www.instagram.com/p/BvXBScTB9Wl/
23.03.2019_19:45 Liked: 2006077824397989285. Like #1.
23.03.2019_19:45 Already followed before 1774337029
23.03.2019_19:45 Couldn't comment post, resuming.
23.03.2019_19:45 Couldn't comment post, resuming.
23.03.2019_19:45 Couldn't comment post, resuming.
23.03.2019_19:45 Couldn't comment post, resuming.
23.03.2019_19:45 Couldn't comment post, resuming.
23.03.2019_19:47 Trying to like media: 2006075249103561439
                 https://www.instagram.com/p/BvXAs93hWLf/
23.03.2019_19:47 Liked: 2006075249103561439. Like #2.
23.03.2019_19:47 MYUSERNAME: Get media id on recent feed
23.03.2019_19:47 Media in recent feed = 12
23.03.2019_19:47 Inserted user frustrating_codes from recent feed
23.03.2019_19:47 Inserted user slothmachineblog from recent feed
23.03.2019_19:47 Inserted user israel.codes from recent feed
23.03.2019_19:47 Inserted user de.webster from recent feed
23.03.2019_19:47 Inserted user andrewclarke80 from recent feed
23.03.2019_19:47 Inserted user connecto_agency from recent feed
23.03.2019_19:47 Inserted user modus.anonimo from recent feed
23.03.2019_19:47 Inserted user webyugg from recent feed
23.03.2019_19:47 Inserted user turing.programming from recent feed
23.03.2019_19:47 Inserted user coding_with_front_end from recent feed
23.03.2019_19:47 Inserted user coder.girl.12 from recent feed
23.03.2019_19:47 Inserted user laxmandreams from recent feed
23.03.2019_19:47 Trying to unfollow #1:
23.03.2019_19:47 Getting user info : version_of_binary
23.03.2019_19:47 Checking user info..
23.03.2019_19:47 Follower : 609
23.03.2019_19:47 Following : 145
23.03.2019_19:47 Media : 4929
23.03.2019_19:47    >This user is active
23.03.2019_19:47    >This account is NOT following you
23.03.2019_19:47    >You are NOT following this account
23.03.2019_19:47 version_of_binary
23.03.2019_19:47 Unfollowed: 8441282064 #1.
23.03.2019_19:47 Couldn't comment post, resuming.
23.03.2019_19:47 Couldn't comment post, resuming.
23.03.2019_19:47 Couldn't comment post, resuming.
23.03.2019_19:47 Couldn't comment post, resuming.
23.03.2019_19:47 Couldn't comment post, resuming.
23.03.2019_19:47 Couldn't comment post, resuming.
23.03.2019_19:47 Couldn't comment post, resuming.
23.03.2019_19:47 Couldn't comment post, resuming.
23.03.2019_19:47 Couldn't comment post, resuming.
23.03.2019_19:47 Couldn't comment post, resuming.
23.03.2019_19:47 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Get Media by tag: javascript
23.03.2019_19:48 Already followed before 11925819345
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Trying to like media: 2006073694536195541
                 https://www.instagram.com/p/BvXAWWEFd3V/
23.03.2019_19:48 Liked: 2006073694536195541. Like #3.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:48 Couldn't comment post, resuming.
23.03.2019_19:49 Couldn't comment post, resuming.

**Comment by ZdravkoDimov** [comment]
Today I tried again to fix the bug, but no result. I consider learning python..

**Comment by dimisdas** [comment]
Changed the error to print the URL of the post it cannot comment
https://github.com/instabot-py/instabot.py/commit/5edef90607542c0359f67c03257bb17d68ff1d6a

**Comment by ZdravkoDimov** [comment]
Thank you that you're helping man. I appreciate it, so I will send you an e-mail with my contacts to contact me if you need any help, whatever it is with JavaScript, or HTML/CSS. It's all my ground, I am a master at it and there's no need to say that it's free for you. Just fix the problem. I downloaded the new version and yea, it's showing the URL of the post it can't comment. Have a nice day!

**Comment by ZdravkoDimov** [comment]
I am here.

**Comment by ZdravkoDimov** [comment]
HELP MEEEE!

**Comment by merichierich** [comment]
same problem for me any solution ??

**Comment by ZdravkoDimov** [comment]
Yeah, just install the packages by your own. I mean to go in requirements/base and just to install every one by one, trough the cmd.

**Comment by merichierich** [comment]
I don’t know How to do it. can you elaborate?. I don’t even know codes for that 😅

**Comment by ordo77** [comment]
Hi, same problem
What do you mean with install packages? can you make an example?

Thank you!

**Comment by blackityblackburn** [comment]
Hi, I've installed everything in requirements/base through cmd but I still get this:

> 2019-12-18 18:59:51,420 - InstaBot - DEBUG - Trying to follow: ########
> 2019-12-18 18:59:55,302 - InstaBot - WARNING - Couldn't comment post, resuming. https://www.instagram.com/p/############/
> 2019-12-18 18:59:55,302 - InstaBot - ERROR - 'graphql'
> Traceback (most recent call last):
>   File "c:\######\#######\appdata\local\programs\python\python37\lib\site-packages\instabot_py\instabot.py", line 1117, in check_exisiting_comment
>     self.current_owner = all_data["graphql"]["shortcode_media"]["owner"][
> KeyError: 'graphql'
> 2019-12-18 18:59:56,653 - InstaBot - WARNING - Couldn't comment post, resuming. https://www.instagram.com/p/############/

Anyone have any leads to resolve?

**Comment by nickgryg** [comment]
Please use instabot-py version 0.5.20 or later. All above issues should be fixed there.
