### ISSUE TITLE
More followers and likes improvement

### ISSUE THREAD

**Issue by golfw** [instabot-py/instabot.py#2047]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
Python 3.7.2

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
pip 19.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

#### Description of your issue

I noticed how to gain more followers, for that it would have to have an option users_to_follow
Our bot will have to follow these accounts then unfollow them, like every 30minutes (probably another var) and re-follow the account to stay at the top of the thread of the followers, other bot target the last followers which makes our account stay visible for the other bots

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by dimisdas** [comment]
Spamming follow/unfollow on the same user is a sure way to get reported and banned.

There are plenty of users to work with, and if someone doesn’t interact with us, best not follow him again
