### ISSUE TITLE
Instagram algorithm 

### ISSUE THREAD

**Issue by channelblackri** [instabot-py/instabot.py#2048]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [x] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

Well I was watching a YouTube Video about Instagram algorithm and the guy mentioned some points which stroke me bad, I hope to discuss here with more persons here. 

Main Points were: 

- Instagram  algorythm can find out that you’re using bots easily and derank or give your post lower priority, if you do it the organic way again. 

- once you used bot‘s, the account is doomed to not get verified in future. (With the blue check mark on profiles.) 

I hope to learn more about the Instagram algorithm.. maybe you know better. 
The guy seemed very superficial in his statements so I wanna question those points. 

Link of the Vid: 
 https://youtu.be/mi3pZpZqpXo

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by murlikanne** [comment]
Instagram knows about the bot biz however they cannot rank an account low based on bot usage. As long as you're a renowned brand or an individual, verification shouldn't be a problem. White boys on YouTube blabber to generate content, a very few actually make sense.
