### ISSUE TITLE
Feature request, read followers story

### ISSUE THREAD

**Issue by mactrash** [instabot-py/instabot.py#2049]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [X] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [X] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```
Story is become more important this days... people care about who read their story... is that possible to add "read followers story" in up coming version?

**Comment by elmissouri16** [comment]
+1

**Comment by ata91** [comment]
+1

**Comment by dimisdas** [comment]
Please be directed to this issue instead https://github.com/instabot-py/instabot.py/issues/2052

**Comment by dimisdas** [comment]
Closed by mistake.

**Comment by nickgryg** [comment]
All work is going on in #2382 

Cheers!
