### ISSUE TITLE
Can I still use IDLE?

### ISSUE THREAD

**Issue by itsmejamie** [instabot-py/instabot.py#2050]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [X] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [X] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
3.7
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

Downloaded the latest version of the bot, but when I click to open the example.py file it quickly opens Python and then closes? Wondering if something has changed since the earlier versions?

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

**Comment by dimisdas** [comment]
You don’t need to download the bot from GitHub. Install using 

python3 -m pip install instabot-py

And then run from command line using the “instabot-py” command.

If you still want to use example.py, download **only** the example.py file, edit it with your configuration and run it with “python3 example.py” or using IDLE for Python 3. You still need to install with pip first.

**Comment by itsmejamie** [comment]
Thanks, I think part of the issue is that I cannot copy over emojis from the example.py. 

Do you know what would be causing this, and how to fix?

**Comment by itsmejamie** [comment]
Able to get bot working if I ignore the emojis. However, would be interested to know how I incorporate them in my bot, still using IDLE.

**Comment by dimisdas** [comment]
Not sure about IDLE and Unicode. Which version of IDLE are you using exactly?

**Comment by itsmejamie** [comment]
IDLE version 3.7.0.

**Comment by dimisdas** [comment]
This is a [known bug](https://bugs.python.org/issue13153) 

Tcl supports only characters in the 16bit range. So tkinter (which IDLE is based on) will not work with Emoji. This is unfortunately not a problem with Instabot. 

It’s supposed to be supported in TCL 9+. Current main version is [8.6](https://www.tcl.tk/software/tcltk/choose.html)
