### ISSUE TITLE
Your text has unicode problem!

### ISSUE THREAD

**Issue by senatorlila** [instabot-py/instabot.py#2051]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
Python 3.6.8

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
pip 19.0.3

#### Description of your issue

I am running the bot on new VPS. Setup as always with sudo locale-gen de_DE.UTF-8 but now I get  "Your text has unicode problem!" with comments including emojis. What do I need to change?

**Comment by dimisdas** [comment]
Could you please upload your configuration to take a look? 

Either include it in your original post (it was actually required in the template) or upload it to a pastebin (paste.ubuntu.com). Remove your username and password.

How are you editing your file? Are you using config.ini or example.py?

Thank you

**Comment by senatorlila** [comment]
I dont think that this has something to do with my instant config. It is a general unicode problem on my machine. Any ideas?

**Comment by dimisdas** [comment]
You haven’t really responded to the following:

> How are you editing your file? 

> Are you using config.ini or example.py?
