### ISSUE TITLE
unlike_delay

### ISSUE THREAD

**Issue by HEATRsports** [instabot-py/instabot.py#2054]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ X] Are you hosting the bot on a VPS or other Cloud hosting?
- [X ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [X ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X ] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
unlike_delay is not defined and instead is using unfollow_delay in new_auto_mod_unlike() method.
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by dimisdas** [comment]
https://github.com/instabot-py/instabot.py/commit/d7d4e5b92a12f652cbb80c62ca44e1278f9f4273
