### ISSUE TITLE
Not working on Windows10

### ISSUE THREAD

**Issue by S1monSay** [instabot-py/instabot.py#2057]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.0
```

#### Pip Version?
```
pip 19.0.3
```

#### Description of your issue

```
Traceback (most recent call last):
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\Scripts\instabot-py.exe\__main__.py", line 9, in <module>
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\site-packages\instabot_py\__main__.py", line 318, in main
    setupinteractive(config, config_location)
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\site-packages\instabot_py\__main__.py", line 278, in setupinteractive
    _label = f"{term.underline(setting)} : {configsettings_labels[setting]}"
NameError: name 'term' is not defined
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by minsuh04** [comment]
after using the latest version, I have the same issue... please help...

->window7
->python --version
Python 3.7.0
>pip --version
pip 19.0.3 

---------------------------------------------------------------------------------------------------
C:\Users\ming\Downloads\instabot (2).py-master_20190326\instabot.py-master
>instabot-py


=============


Config file does not exist. Would you like to setup now? (yes/no):  : yes


=============

Your username is NOT your email or your phone number!
Please enter the username you wish to configure: : @username


=============

This field is required
Enter value for 'password': : username
Traceback (most recent call last):
  File "c:\users\ming\appdata\local\programs\python\python37\lib\runpy.py"
, line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ming\appdata\local\programs\python\python37\lib\runpy.py"
, line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ming\AppData\Local\Programs\Python\Python37\Scripts\insta
bot-py.exe\__main__.py", line 9, in <module>
  File "c:\users\ming\appdata\local\programs\python\python37\lib\site-pack
ages\instabot_py\__main__.py", line 318, in main
    setupinteractive(config, config_location)
  File "c:\users\ming\appdata\local\programs\python\python37\lib\site-pack
ages\instabot_py\__main__.py", line 278, in setupinteractive
    _label = f"{term.underline(setting)} : {configsettings_labels[setting]}"
NameError: name 'term' is not defined

C:\Users\ming\Downloads\instabot (2).py-master_20190326\instabot.py-master
>

**Comment by dimisdas** [comment]
This is a bug.

I'll have fixed it on my local tree and will commit the changes too. You should expect an update to PyPi within the week.

Until then, [please download the example.py file](https://github.com/instabot-py/instabot.py/raw/master/example.py), edit it with a text editor and run it using "python example.py"

**Comment by dimisdas** [comment]
https://github.com/instabot-py/instabot.py/commit/a384c5c27a2f1ecf4934c8f1da950ff27dc58d9e

**Comment by dimisdas** [comment]
Updated on PyPi ` instabot-py-0.4.6`,

please upgrade with "pip install --upgrade --no-cache-dir instabot-py". 
Make sure 0.4.6 is being installed (sometimes the pip CDN cache keeps the old version).

**Comment by S1monSay** [comment]
Thx dude.

út 26. 3. 2019 v 15:48 odesílatel Dimis <notifications@github.com> napsal:
