### ISSUE TITLE
Cannot execute setup.py

### ISSUE THREAD

**Issue by Venomz33** [instabot-py/instabot.py#2062]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [X ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [X ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X ] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.2
```

#### Pip Version?
```
pip 19.0.3 from c:\python37\lib\site-packages\pip (python 3.7)
```

#### Description of your issue

```
I execute command "python setup.py" and get this error logs:

Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    README = open(os.path.join(here, "README.md")).read()
  File "C:\Python37\lib\encodings\cp1254.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 1259: character maps to <undefined>
```

#### Config

```
I don't have any config file, because i cannot pass setup
```

**Comment by dimisdas** [comment]
Could you please try changing line 8 of setup.py to

`with open(os.path.join(here, "requirements/base.txt"), encoding="utf-8") as f:`

![Screenshot 2019-03-26 at 16 33 56](https://user-images.githubusercontent.com/1391441/55005645-0d415000-4fe5-11e9-8217-bd7f75b636b2.jpg)

**Comment by pierrechn** [comment]
where is this line located? not seeing it on mines. I'm running python 3.7

**Comment by dimisdas** [comment]
It's in your setup.py file. 

The PyPi already has the changes, you could update from there.
