### ISSUE TITLE
Problem with unfollow everyone except whitelist

### ISSUE THREAD

**Issue by BartekChojnacki** [instabot-py/instabot.py#2064]
#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
Python 3.6.7

#### Pip Version?
pip 18.1

#### Description of your issue

Is it any possibility to clean up after bot follows and likes?

I want to unfollow everyone,  except peoples on whitelist. Bot is trying to do that but it looks that it build list of people to unfollow from recent feed not from my current following list and compare it to whitelist. In result script do nothing.

ex:

    ______Starting bot_____
27.03.2019_08:07 Checking for updates...
27.03.2019_08:07 Could not check for updates
27.03.2019_08:07 Instabot v1.2.5/0 started at 27.03.2019 08:07:
27.03.2019_08:07 Found session file zuzannachyba.session
27.03.2019_08:07 XXXX login success!

27.03.2019_08:07 Saving cookies to session file XXXXXXX.session
27.03.2019_08:07 Get Media by tag: XXXX
27.03.2019_08:07 Trying to follow: 10662283496
27.03.2019_08:07 Followed: 10662283496 #1.
27.03.2019_08:08 XXXX : Get media id on recent feed
27.03.2019_08:08 Media in recent feed = 12
27.03.2019_08:08 Trying to unfollow #1:
27.03.2019_08:08 Looks like there is nobody to unfollow.
27.03.2019_08:08 Trying to unfollow #1:
27.03.2019_08:08 Looks like there is nobody to unfollow.
27.03.2019_08:08 Trying to unfollow #1:
27.03.2019_08:08 Looks like there is nobody to unfollow.
27.03.2019_08:08 Trying to unfollow #1:
27.03.2019_08:08 Looks like there is nobody to unfollow.
27.03.2019_08:08 Trying to like media: 2008458557596175027
                 https://www.instagram.com/p/Bvfemq3nQqz/
27.03.2019_08:08 Liked: 2008458557596175027. Like #1.
27.03.2019_08:08 Trying to unfollow #1:
27.03.2019_08:08 Looks like there is nobody to unfollow.
27.03.2019_08:08 Trying to unfollow #1:
27.03.2019_08:08 Looks like there is nobody to unfollow.
27.03.2019_08:08 Get Media by tag: XXXXXX
27.03.2019_08:09 Trying to unfollow #1:
27.03.2019_08:09 Looks like there is nobody to unfollow.
27.03.2019_08:09 Trying to unfollow #1:
27.03.2019_08:09 Looks like there is nobody to unfollow.
27.03.2019_08:09 Trying to unfollow #1:
27.03.2019_08:09 Looks like there is nobody to unfollow.
27.03.2019_08:09 Trying to unfollow #1:
27.03.2019_08:09 Looks like there is nobody to unfollow.
27.03.2019_08:09 Trying to unfollow #1:
27.03.2019_08:09 Looks like there is nobody to unfollow.
27.03.2019_08:09 Trying to unfollow #1:
27.03.2019_08:09 Looks like there is nobody to unfollow.
27.03.2019_08:09 Trying to unfollow #1:
27.03.2019_08:09 Looks like there is nobody to unfollow.
27.03.2019_08:10 Trying to unfollow #1:
27.03.2019_08:10 Looks like there is nobody to unfollow.
27.03.2019_08:10 Get Media by tag: XXXXXXX
27.03.2019_08:10 Trying to unfollow #1:
27.03.2019_08:10 Looks like there is nobody to unfollow.
27.03.2019_08:10 Trying to unfollow #1:
27.03.2019_08:10 Looks like there is nobody to unfollow.
27.03.2019_08:10 Trying to unfollow #1:
27.03.2019_08:10 Looks like there is nobody to unfollow.
27.03.2019_08:10 Trying to unfollow #1:
27.03.2019_08:10 Looks like there is nobody to unfollow.
27.03.2019_08:10 Trying to unfollow #1:
27.03.2019_08:10 Looks like there is nobody to unfollow.
27.03.2019_08:11 Trying to unfollow #1:
27.03.2019_08:11 Looks like there is nobody to unfollow.
27.03.2019_08:11 Trying to unfollow #1:
27.03.2019_08:11 Looks like there is nobody to unfollow.
27.03.2019_08:11 Get Media by tag: like4like
27.03.2019_08:11 Trying to unfollow #1:
27.03.2019_08:11 Looks like there is nobody to unfollow.
27.03.2019_08:11 Trying to unfollow #1:
27.03.2019_08:11 Looks like there is nobody to unfollow.
27.03.2019_08:11 Trying to unfollow #1:
27.03.2019_08:11 Looks like there is nobody to unfollow.
27.03.2019_08:11 Trying to unfollow #1:
27.03.2019_08:11 Looks like there is nobody to unfollow.
27.03.2019_08:11 Trying to unfollow #1:
(...)

Currently I'm following ~800 peoples, and there is ~350 people on whitelist, so definitely there is a lot of people to unfollow...

#### Config
[XXXXXX]
username = XXXX
password =XXXX
#start_at_h = 07
#start_at_m = 00
#end_at_h = 00
#end_at_m = 00
comments_per_day = 0
max_like_for_one_tag = 5
like_per_day = 1
unlike_per_day = 1
media_max_like = 100
media_min_like = 30
follow_per_day = 1
follow_time = 1
time_till_unlike = 1
unfollow_per_day = 10000
unfollow_break_min = 3
#unfollow_break_max = 17
#unfollow_selebgram = True
#unfollow_probably_fake = True
#unfollow_inactive = True
unfollow_everyone=True
#unfollow_recent_feed = True
unfollow_whitelist = ["x,y,z...... ]

**Comment by dimisdas** [comment]
`#unfollow_recent_feed = True`

is commented out, you need to reënable it. With this option, the bot will only insert people from your recent feed and queue them for unfollow, so it might not actually unfollow _everyone_ everyone.
