### ISSUE TITLE
cant install instabot.py tried several things

### ISSUE THREAD

**Issue by paoloscan** [instabot-py/instabot.py#2065]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x ] Linux (ubuntu 16.04)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
3.5.2 3.6.8 3.7.2
```
Include here the response of 'python --version' or 'python3 --version'
```
Python 2.7.12 3.5.2
#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```
pip 19.0.3
#### Description of your issue

```
Hi there ive tried installing instabot.py on my hetzner server but no luck, first installation got me a working bot but it couldnt connect, then ive tried on my computer and it would work. My server connection is open so it should connect! Ive tried now installing it on python 3.7 it seems to work but i keep getting these:

     ______Starting bot_____
28.03.2019_13:39 Checking for updates...
28.03.2019_13:39 You are running the latest stable version
28.03.2019_13:39 Instabot v1.2.5/0 started at 28.03.2019 13:39:
28.03.2019_13:39 Trying to login as XXXXX(my username)...
28.03.2019_13:39 Something wrong with login
28.03.2019_13:39 {"errors": {"error": ["Sorry, there was a problem with your request."]}, "status": "ok", "error_type": "generic_request_error"}
28.03.2019_13:39 Something is wrong with Instagram! Please try again later...
28.03.2019_13:39 Error =>Sorry, there was a problem with your request.
28.03.2019_13:39 Exit Program... GoodBye


Thank you very much for your help!

#### Config

**Comment by dimisdas** [comment]
Perhaps you could debug this by checking if Instagram is accessible from your server on a OS level.
Instagram has banned several cloud providers. But it could still be a firewall on your side.
