### ISSUE TITLE
"Save tags" - function

### ISSUE THREAD

**Issue by Calavera85** [instabot-py/instabot.py#207]
It would be really cool if the bot could save and accumulate ALL the associated tags for each and every pic it rolls through. Perhaps write them to a separate file or something. One could then, by studying the frequency of these different tags, deduce which tags are used the most within the topic.

Or perhaps this "tag-frequency-count" can be done in the code as well? And the bot could then present the 50 most common tags after each run.

Great work!

**Comment by ChipWolf** [comment]
A tag cloud? Heh, seems a bit out-of-scope, but it'd be cool

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
