### ISSUE TITLE
Instabot Login error

### ISSUE THREAD

**Issue by v4l3ntyn112** [instabot-py/instabot.py#2070]
w

Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.3
```

#### Pip Version?
```
19.03

#### Description of your issue

After that error, the window dissapears and then nothing.
Please help!

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```
![Untitled](https://user-images.githubusercontent.com/49078673/55261703-54914000-5274-11e9-96dc-0c64975c5fc7.png)

**Comment by dimisdas** [comment]
You need to open the example.py file with a code/text editor (like Atom) and change the settings. Chief amongst them, your username and password.
