### ISSUE TITLE
Can't open example.py in new fix. Tech: Python 3.7, Windows x64

### ISSUE THREAD

**Issue by murlikanne** [instabot-py/instabot.py#2071]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by murlikanne** [comment]
@dimisdas wait up man, just updated the problem.

**Comment by dimisdas** [comment]
You should open example.py using a text editor like ATOM.

Also see possible duplicate  [Can I still use IDLE? - Issue #2050](https://github.com/instabot-py/instabot.py/issues/2050)

**Comment by murlikanne** [comment]
> You should open example.py using a text editor like ATOM.
> 
> Also see possible duplicate [Can I still use IDLE? - Issue #2050](https://github.com/instabot-py/instabot.py/issues/2050)

@dimisdas Oh thanks man, I'll use a text editor. IDLE automatically closes down every time i use an emoji. Thanks for the help.
