### ISSUE TITLE
Cannot activate bot

### ISSUE THREAD

**Issue by lidoramrani** [instabot-py/instabot.py#2073]
#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

#### Environment
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [X] Linux (Ubuntu 18.04)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Pip Version?
```
 'pip3 --version'
```

I try to launch the bot, but I recieve:

```
31.03.2019_21:30 Checking for updates...
31.03.2019_21:30 You are running the latest stable version
31.03.2019_21:30 Instabot v1.2.5/0 started at 31.03.2019 21:30:
31.03.2019_21:30 Found session file redteallo.session
Traceback (most recent call last):
  File "example.py", line 122, in <module>
    unfollow_whitelist=["worldstar","nba",],
  File "/home/lidoramrani21/instabot.py/instabot_py/instabot.py", line 365, in __init__
    self.login()
  File "/home/lidoramrani21/instabot.py/instabot_py/instabot.py", line 584, in login
    self.csrftoken = re.search('(?<="csrf_token":")\w+', r.text).group(0)
AttributeError: 'NoneType' object has no attribute 'group'```

"""

**Comment by dimisdas** [comment]
Is it possible that your cloud IP is blacklisted?

Does it work on your local computer with the same settings?

**Comment by lidoramrani** [comment]
Nope, I run it on Google Console and using a proxy

**Comment by dimisdas** [comment]
Many proxies and cloud IPs are restricted.

Does it work locally?

**Comment by sucrilhos0** [comment]
This can be fixed by confirming your account, it is just blocked.. lower your numbers to avoid this. Happened to me and when i tried to login through browser i confirmed phone number and its all good. 

Hope this helps someone!
