### ISSUE TITLE
KeyError: edge_media_to_comment

### ISSUE THREAD

**Issue by yungmichas** [instabot-py/instabot.py#2077]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [X] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.1
```

#### Pip Version?
```
19.0.3
```

#### Description of your issue

```
after opening the program it closing with this error:
Traceback (most recent call last):
File "C:\Users\x\Desktop\igbot\x\example.py", line 67, in 
bot.new_auto_mod()
File "C:\Users\x\Desktop\igbot\x\src\instabot.py", line 730, in new_auto_mod
self.new_auto_mod_comments()
File "C:\Users\x\Desktop\igbot\x\src\instabot.py", line 798, in new_auto_mod_comments
and self.check_exisiting_comment(self.media_by_tag[0]['node']['shortcode']) == False:
File "C:\Users\x\Desktop\igbot\x\src\instabot.py", line 829, in check_exisiting_comment
comment_list = list(all_data['graphql']['shortcode_media']['edge_media_to_comment']['edges'])
KeyError: 'edge_media_to_comment'
```

#### Config

```
bot = InstaBot(
    login="x",
    password="x",
    like_per_day=1440,
    comments_per_day=1440,
    tag_list=['tag'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=60,
    follow_per_day=0,
    follow_time=1*60,
    unfollow_per_day=0,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["Something is here"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[],
    unfollow_whitelist=[])
```

**Comment by nimrodazoulai** [comment]
Hey! Go to the instabot.py script, head over to the check_exisiting_comment function.
and **_instead comment_list = list(all_data['graphql']['shortcode_media']['edge_media_to_comment']['edges'])_**
**_paste comment_list = list(all_data['graphql']['shortcode_media']['edge_media_to_parent_comment']['edges'])_**
Let me know if it helps. It solved the issue for me.

**Comment by dimisdas** [comment]
You are using an old version. It’s been fixed many months ago. 

There is no “src” folder anymore.

**Comment by yungmichas** [comment]
Where can i download a new version?

**Comment by yungmichas** [comment]
> Hey! Go to the instabot.py script, head over to the check_exisiting_comment function.
> and **_instead comment_list = list(all_data['graphql']['shortcode_media']['edge_media_to_comment']['edges'])_**
> **_paste comment_list = list(all_data['graphql']['shortcode_media']['edge_media_to_parent_comment']['edges'])_**
> Let me know if it helps. It solved the issue for me.

Its working ty :D

**Comment by PepiMarquez** [comment]
Do you mean this?
   try:
                    comment_list = list(
                        all_data["graphql"]["shortcode_media"]["edge_media_to_comment"][
                            "edges"
                        ]
                    )
                except:
                    comment_list = list(
                        all_data["graphql"]["shortcode_media"][
                            "edge_media_to_parent_comment"
                        ]["edges"]
                    )
