### ISSUE TITLE
Could Not Remove Media in CMD / SRC Error on IDLE 3.7

### ISSUE THREAD

**Issue by pierrechn** [instabot-py/instabot.py#2078]
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

not sure, i'm using the bot on a regular laptop so it shouldn't be cloud hosting.

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version? 
3.7.2
```
Include here the response of 'python --version' or 'python3 --version'
C:\Users\Pierre>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```
  pip3 <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion.
  help                        Show help for commands.

General Options:
  -h, --help                  Show help.
  --isolated                  Run pip in an isolated mode, ignoring environment variables and user configuration.
  -v, --verbose               Give more output. Option is additive, and can be used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output. Option is additive, and can be used up to 3 times (corresponding to
                              WARNING, ERROR, and CRITICAL logging levels).
  --log <path>                Path to a verbose appending log.
  --proxy <proxy>             Specify a proxy in the form [user:passwd@]proxy.server:port.
  --retries <retries>         Maximum number of retries each connection should attempt (default 5 times).
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists: (s)witch, (i)gnore, (w)ipe, (b)ackup,
                              (a)bort).
  --trusted-host <hostname>   Mark this host as trusted, even though it does not have valid or any HTTPS.
  --cert <path>               Path to alternate CA bundle.
  --client-cert <path>        Path to SSL client certificate, a single file containing the private key and the
                              certificate in PEM format.
  --cache-dir <dir>           Store the cache data in <dir>.
  --no-cache-dir              Disable the cache.
  --disable-pip-version-check
                              Don't periodically check PyPI to determine whether a new version of pip is available for
                              download. Implied with --no-index.
  --no-color                  Suppress colored output
![Screenshot (537)](https://user-images.githubusercontent.com/43892593/55376112-77219400-54d4-11e9-85af-836190e158e6.png)
![Screenshot (539)](https://user-images.githubusercontent.com/43892593/55376118-7be64800-54d4-11e9-9028-fdd4ace3a00c.png)

####
```

Hello,

I'm having 2 different issues. If I run 'instabot-py' on CMD it successfully logs in but keeps giving me the black screen that seems to just keep scanning hashtags without actually automating anything.

Is there a fix for this sort of issue? I previously ran the Instabot via IDLE 3.7 but that no longer works as well with the latest version. If I run it via IDLE I get the src issue featured on the blue screen. 

I'm searching but do not see any fixes to these issues.

Lastly, on the older version of 'Instabot' it allowed you to create a custom comment - on this new version, it doesn't seem to have the option - is this an error or was it removed?

Thanks in advance!

**Comment by pierrechn** [comment]
![Screenshot (537)](https://user-images.githubusercontent.com/43892593/55376328-8b19c580-54d5-11e9-8a19-ce4a05bdcf5d.png)

![Screenshot (539)](https://user-images.githubusercontent.com/43892593/55376332-8e14b600-54d5-11e9-8de1-b76d169c3043.png)

**Comment by dimisdas** [comment]
There is no src folder/module anymore. The file you’re using is old. You should download the **new** example.py file.

**Comment by pierrechn** [comment]
Hello,

I just downloaded the example.py file featured on the main page here. When I open it manually in IDLE 3.7 it appears to be blank - also, when I try copying and pasting the code manually it just shuts it down.

Also, I completely deleted Instabot and re-downloaded it yesterday as a whole so everything should be 100% up to date. The error I get in CMD is not the error I get on Python. I should be able to run the bot on either platform correct?
