### ISSUE TITLE
How to only interact (like/follow) with posts no older than a day?

### ISSUE THREAD

**Issue by olishingerz** [instabot-py/instabot.py#2080]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ x] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.1
```

#### Pip Version?
```
pip 18.1
```

#### Description of your issue

```
Is it possible to only like posts that are no older than a day? The bot is currently liking posts that are from last month which is not desired. 
```

**Comment by dimisdas** [comment]
Not currently. You could avoid that by using a higher number of popular hashtags, including a small max_like_for_one_tag value (~3-5) if they are really low traffic tags.

**Comment by olishingerz** [comment]
Okay thank you very much
