### ISSUE TITLE
Python PIP install problem

### ISSUE THREAD

**Issue by realwudoka** [instabot-py/instabot.py#2081]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS Mojave
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above - 3.6.8

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
``` python --version - Python 2.7.6
``` python3 --version - Python 3.4.0

#### Pip Version?
```19
Include here the response of 'pip --version' or 'pip3 --version'
```pip 19.0.3 from /usr/local/lib/python3.4/dist-packages/pip (python 3.4)

#### Description of your issue

```
I can't install instabot on my VPS. There is problem when i try to execute command: python3 -m pip install instabot-py. Server returns me this info:
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting instabot-py
  Using cached https://files.pythonhosted.org/packages/aa/06/bd861f008b1bc9f260d7784c36afcc818af9c936e7dffd942af3c5f01ded/instabot_py-0.4.6-py3-none-any.whl
Collecting instaloader==4.2.1 (from instabot-py)
  Could not find a version that satisfies the requirement instaloader==4.2.1 (from instabot-py) (from versions: 1.1, 1.2, 1.2.1, 1.2.2, 1.3, 2.0, 2.1, 2.2, 2.2.1)
No matching distribution found for instaloader==4.2.1 (from instabot-py)

I dont know how to fix that
```

#### Config

```
not required
```

**Comment by dimisdas** [comment]
You checked the box “I am using Python 3.6 or above”, however you go on about having 3.4.0 installed.

This is the problem. You need to check the README guide, or some other guide, on how to install the newest version of Python. I have no idea where to direct you because while it’s stated you’re using macOS, it seems like you’re not running the bot on a Mac but on a Linux VPS.
