### ISSUE TITLE
Updating Auto Comment On Latest Instabot

### ISSUE THREAD

**Issue by pierrechn** [instabot-py/instabot.py#2086]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

Everything is up to date as well PIP, everything,
----

I have configured the instabot via CMD but it doesn't give me the option to edit the comment it leaves on posts, how can you edit this on the latest version of Instabot? 

I've ran setup but don't see the option. I use to run Instabot with IDLE 3.7 so it always gave the option but not this CMD version, kindly walk me through it.

**Comment by joaocpereiraa** [comment]
I have this error  on comment bot:

Traceback (most recent call last):
  File "C:\Users\joaoc\Downloads\instabot\iamcoment.py", line 68, in <module>
    bot.new_auto_mod()
  File "C:\Users\joaoc\Downloads\instabot\src\instabot.py", line 707, in new_auto_mod
    self.new_auto_mod_comments()
  File "C:\Users\joaoc\Downloads\instabot\src\instabot.py", line 775, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['shortcode']) == False:
  File "C:\Users\joaoc\Downloads\instabot\src\instabot.py", line 806, in check_exisiting_comment
    comment_list = list(all_data['graphql']['shortcode_media']['edge_media_to_comment']['edges'])
KeyError: 'edge_media_to_comment'
>>>

**Comment by nickgryg** [comment]
Please use instabot-py version 0.5.20 or later. Now it is clear how to set proper configuration before start it.
