### ISSUE TITLE
Failed to load instaloader

### ISSUE THREAD

**Issue by diogots** [instabot-py/instabot.py#2089]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [X] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```Python3.6.8

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```pip19

#### Description of your issue
Hi! I've installed the correct version of python and pip (3.6.8 and 19) and I've installed the instabot-py using the pip command **"python3.6 -m pip install instabot-py"**, but when I run my _example.py_ or call the command _instabot-py_ returns the error message:

"Failed to load module instaloader. Make sure you have installed correctly all dependencies.
If instaloader keeps failing and you are running this script on a Raspberry, please visit this project's Wiki on GitHub (https://github.com/instabot-py/instabot.py/wiki) for more information."

Someone can help me?

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by dimisdas** [comment]
Please include your Linux flavour. 

What’s the output of “python3 -m instaloader” ?

**Comment by diogots** [comment]
> Please include your Linux flavour.
> 
> What’s the output of “python3 -m instaloader” ?

Thanks @dimisdas When I compiled Python3.6, I didn't install some packages used by instaloader. It's running Ok now!

**Comment by dimisdas** [comment]
Great to hear :)

(was it lzma?)

**Comment by diogots** [comment]
> Great to hear :)
> 
> (was it lzma?)

exactly!

**Comment by Raul1231** [comment]
I have the same problem Failed to load module instaloader but I am not able to solve it.

I have tried with this python3 -m instaloader, but  I cant.

Please, how can i solve this?
