### ISSUE TITLE
How to like everything on my time line feed or posts my followers have made? 

### ISSUE THREAD

**Issue by Pr0x1mo** [instabot-py/instabot.py#2090]
So i'm running this and it works fine.  My question is, and maybe i'm over looking this.  I know this thing likes things by media hashtags but is there a way i can like the media of a particular user if i know their user_id or username? 
```

**Comment by Jon309** [comment]
Run the like_users.py script

**Comment by Pr0x1mo** [comment]
> Run the like_users.py script

Am i missing a script because i don't see that in the folder. I have it alphabetized and i only see likers_protocol.py and likers_graber_protocol.py
