### ISSUE TITLE
failed to load module request on mac osx after python3 example.py

### ISSUE THREAD

**Issue by randomepx** [instabot-py/instabot.py#2097]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x ] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [ x] I am using Python 3.6 or above

#### Exact Python Version?
python3

#### Pip Version?
pip3

#### Description of your issue

Before I had the problem that I needed to copy the  normal requirements path to a txt file. Because before it said   " Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt''
Now installation works I think, there is no error anymore. Just that when I python3 example.py it says "Failed to load module requests. Make sure you have installed correctly all dependencies."
The installation process is like max 1 sec charging and there is no confirmation in terminal that it had installed or smth.

#### Config

Requirements.txt : fake-useragent==0.1.11
instaloader==4.2.1
requests==2.21.0
blessings==1.7.0
tox
pytest-cov
pytest
pytest-cov
flake8

**Comment by dimisdas** [comment]
Install using pip as outlined in the README.md.

There is no requirements.txt. You don’t need to download any folders. Not sure what you’re trying to achieve. The guide is pretty good if you follow it exactly.

Good luck! :)
