### ISSUE TITLE
Invalid syntax when trying to run the bot

### ISSUE THREAD

**Issue by winnetouch** [instabot-py/instabot.py#2098]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```
Python 3.7.0
#### Pip Version?
```
I get no response here but as far as I know pip is included in python 3.7.0.
```

#### Description of your issue

```
There is NO requirements.txt file to be found on the raspberry pi anywhere. All tutorials state it should be in the root directory. Well it's not. I've had the same problem with running the bot on windows.

I've searched for similar issues but they were all closed before a solution was found or the OP never stated how he resolved the issue.

When I try to run the bot I get the message: Failed to load module requirements. Make sure you have installed correctly all dependencies.

I'd be grateful for any tip on how to resolve this.

```

#### Config

```
The config is not the issue.
```

**Comment by dimisdas** [comment]
Follow the guide on GitHub (README.md). There is no mention of requirements.txt in our guide.

Also not sure what version of Instabot you’re using. You mention in the title a syntax error but all you’ve given me is that one the modules could not be imported. No stack error. Not syntax error. Please follow the instructions.
