### ISSUE TITLE
New Feature Request - Like by Location

### ISSUE THREAD

**Issue by octavianfeodot** [instabot-py/instabot.py#2099]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [ ] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

Hello, I would like to request a new feature. It is cool to like people by 'hashtags', but would it be possible to do that by location? example this: https://www.instagram.com/explore/locations/73959962/bucharest-romania/ 

This way it would be a lot more accurate. 

Although I know programming, there's a lot of OOP and it seems confusing for me to find out the implementation solution. If I get some guidance at first I think I can sort it out by myself and merge this solution.

Thank you in advance.
Tavi

**Comment by elmissouri16** [comment]
@octavianfeodot  that's already exist  read the documentation

**Comment by octavianfeodot** [comment]
@elmissouri16 Thank you and sorry for opening an issue just for that.

For any other noob that didn't figure it out from the documentation, instead of adding a tag in the tag_list as ['cat', 'car', 'dog'] , you need to add a tag with the geographical coordinates of the location eg. ['l:212999109'] for Los Angeles California. The coordinates are found in the link of the location from the instagram : https://www.instagram.com/explore/locations/**212999109**/los-angeles-california/

You can also combine tags and locations.

**Comment by elmissouri16** [comment]
@octavianfeodot  no problem just to be clear that's not  geographical coordinates its location id

**Comment by rrdd** [comment]
@octavianfeodot 

How can i combine location id with hashtags?

Best
