### ISSUE TITLE
Could not install packages due to an EnvironmentError

### ISSUE THREAD

**Issue by winnetouch** [instabot-py/instabot.py#2100]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
pi@raspberrypi:~ $ python --version
Python 3.7.2

```

#### Pip Version?
```
pi@raspberrypi:~ $ pip --version
pip 19.0.3 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)
```

#### Description of your issue

```
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/blessings-1.7.dist-info'
Consider using the `--user` option or check the permissions.
```

#### Config

```
Haven't gotten that far yet.
```

**Comment by DayS1eeper** [comment]
Run it as a root
```bash
sudo pip install ...
```

**Comment by dimisdas** [comment]
https://github.com/instabot-py/instabot.py/wiki/Installing-Python-3.7-on-Raspberry-Pi 

Try following this guide.
