### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by winnetouch** [instabot-py/instabot.py#2101]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
pi@raspberrypi:~/instabot $ python --version
Python 3.7.2

```

#### Pip Version?
```
pi@raspberrypi:~/instabot $ pip --version
pip 19.0.3 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)

```

#### Description of your issue

```
pi@raspberrypi:~/instabot $ instabot-py
Traceback (most recent call last):
  File "/usr/local/bin/instabot-py", line 6, in <module>
    from instabot_py.__main__ import main
  File "/usr/local/lib/python3.5/dist-packages/instabot_py/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/usr/local/lib/python3.5/dist-packages/instabot_py/instabot.py", line 33
    python_version_test = f"If you are reading this error, you are not running Python 3.6 or greater. Check 'python --version' or 'python3 --version'."
                                                                                                                                                      ^
SyntaxError: invalid syntax

```

Not there yet.

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by elmissouri16** [comment]
@winnetouch  Read this   python_version_test = f"If you are reading this error, you are not running Python 3.6 or greater. Check 'python --version' or 'python3 --version'." its mean python version need to be 3.6 or higher

**Comment by winnetouch** [comment]
If i type python - - version it states what I've pasted above. That I am running python 3.7.2.

If i type python3 - - version it states i am using python 3.5.3. Eh?

Every time i boot up the pi the default python version changes to 2.x.x. So I manually change it with

alias python='python3.7'

Should I do the same for python3?

**Comment by elmissouri16** [comment]
I think yes

**Comment by dimisdas** [comment]
Why use an alias? It’s only an alias on your current shell.

Uninstall Instabot using “pip uninstall instabot-py”.

Then reinstall using python 3.7

“python3.7 -m pip install instabot-py  --upgrade”

And run with “instabot-py”

**Comment by winnetouch** [comment]
I did as you suggested. Got an error.

pi@raspberrypi:~/instabot $ python3.7 -m pip install instabot-py --upgrade
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting instabot-py
  Using cached https://files.pythonhosted.org/packages/aa/06/bd861f008b1bc9f260d7784c36afcc818af9c936e7dffd942af3c5f01ded/instabot_py-0.4.6-py3-none-any.whl
Collecting instaloader==4.2.1 (from instabot-py)
  Using cached https://www.piwheels.org/simple/instaloader/instaloader-4.2.1-py3-none-any.whl
Collecting blessings==1.7.0 (from instabot-py)
  Using cached https://files.pythonhosted.org/packages/03/74/489f85a78247609c6b4f13733cbf3ba0d864b11aa565617b645d6fdf2a4a/blessings-1.7-py3-none-any.whl
Collecting requests==2.21.0 (from instabot-py)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting fake-useragent==0.1.11 (from instabot-py)
  Using cached https://www.piwheels.org/simple/fake-useragent/fake_useragent-0.1.11-py3-none-any.whl
Collecting six (from blessings==1.7.0->instabot-py)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests==2.21.0->instabot-py)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests==2.21.0->instabot-py)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.21.0->instabot-py)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests==2.21.0->instabot-py)
  Using cached https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
Installing collected packages: idna, urllib3, chardet, certifi, requests, instaloader, six, blessings, fake-useragent, instabot-py
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.7/site-packages/idna'
Consider using the `--user` option or check the permissions.

**Comment by winnetouch** [comment]
Never mind. Got it going now :). Typed is with SUDO.
