### ISSUE TITLE
Challenge Required

### ISSUE THREAD

**Issue by michaelosten** [instabot-py/instabot.py#2120]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ X] Bug

#### Operating System? (include version)

- [X ] Linux (Ubuntu 18.04.2 LTS)

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
Python 3.6.7

Include here the response of 'python --version' or 'python3 --version'
Python 3.6.7

#### Pip Version?
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
Include here the response of 'pip --version' or 'pip3 --version'
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```
root@plex-linux:~/INSTAGRAM/4-26-2019/instabot.py# python3 example.py 
26.04.2019_20:48 Checking for updates...
26.04.2019_20:48 You are running the latest stable version
26.04.2019_20:48 Instabot v1.2.5/0 started at 26.04.2019 20:48:
26.04.2019_20:48 Trying to login as gravitybored...
26.04.2019_20:48 Challenge required at https://instagram.com/challenge/26733951/nV9AzfM6XS/
Challenge Required.

Enter the code sent to your mail/phone:

#### Config

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from instabot_py import InstaBot

bot = InstaBot(
    login="username",  # Enter username (lowercase). Do not enter email!
    password="password",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=["follow4follow", "f4f", "cute", "l:212999109"],
    tag_blacklist=["rain", "thunderstorm"],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60 * 60,
    unfollow_per_day=300,
    unlike_per_day=0,
    unfollow_recent_feed=True,
    # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
    time_till_unlike=3 * 24 * 60 * 60,  # 3 days
    unfollow_break_min=15,
    unfollow_break_max=30,
    user_max_follow=0,
    # session_file=False, # Set to False to disable persistent session, or specify custom session_file (ie ='myusername.session')
    user_min_follow=0,
    log_mod=0,
    proxy="",
   # For example: "This shot feels wow!"
    comment_list=[
        ["this", "the", "your"],
        ["photo", "picture", "pic", "shot"],
        ["is", "looks", "is 👉", "is really"],
        [
            "great",
            "super",
            "good",
            "very good",
            "good",
            "wow",
            "WOW",
            "cool",
            "GREAT",
            "magnificent",
            "magical",
            "very cool",
            "stylish",
            "beautiful",
            "so beautiful",
            "so stylish",
            "so professional",
            "lovely",
            "so lovely",
            "very lovely",
            "glorious",
            "so glorious",
"amazing",
        ],
        [".", "🙌", "... 👏", "!", "! 😍", "😎"],
    ],
    # Use unwanted_username_list to block usernames containing a string
    # Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    # 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
    "second",
     "stuff",
],
    unfollow_whitelist=["example_user_1", "example_user_2"],
    unfollow_whitelist=["example_user_1", "example_user_2"],
    # Enable the following to schedule the bot. Uses 24H
    # end_at_h = 23, # Hour you want the bot to stop
    # end_at_m = 30, # Minute you want the bot stop, in this example 23:30
    # start_at_h = 9, # Hour you want the bot to start
    # start_at_m = 10, # Minute you want the bot to start, in this example 9:10 (am).
)

bot.mainloop()
```

**Comment by michaelosten** [comment]
No code is ever sent to phone or email.  I have verified that both the email and phone number are correct.

**Comment by keithhill3** [comment]
do you have two-factor authentication running on your insta account. ?
If you do disable it and try again.

**Comment by michaelosten** [comment]
2-factor is disabled

**Comment by guztavoalves** [comment]
First go to your account using the anonymous window on google chrome desktop, then run the bot, the challenge message will appear, go back to the anonymous window on the PC and refresh, confirm the new access and try again the login with the bot.

**Comment by guztavoalves** [comment]
First login with your ig account using the anonymous window on google chrome desktop, now run the bot in terminal, the challenge message will appear again, go back to the anonymous window on the PC and refresh, confirm the new access and try again the login with the bot in terminal.

**Comment by manguszta** [comment]
2 of my 4 accounts require challenge. No 2-factor, not working after login confirm in app or incognito window.

**Comment by dimisdas** [comment]
Instagram has marked your IP. I'm afraid there's not much that can be done.
