### ISSUE TITLE
Unused classes and codes

### ISSUE THREAD

**Issue by arvand** [instabot-py/instabot.py#2121]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [x] Other

I'm confused by the source code of the project, some of the files appear to not be used and all the logic seems to be in instabot.py. What is the use of other classes and methods such as 'unfollow_protocol()'? Am I missing something?

**Comment by clementin35** [comment]
Only instabot.py is being used, others prototyped but not used.

**Comment by dimisdas** [comment]
There were plenty of modes in Instabot, that more or less did the same stuff. It was a mess. All modes have been removed in favour of new parameters that provide the same functionality. There's still some unused legacy code left that needs to be removed.
