### ISSUE TITLE
Pythonanywhere issue

### ISSUE THREAD

**Issue by Modderov** [instabot-py/instabot.py#2122]
hi, i'm receiving this message while  running example.py on Pythonanywhere:

Failed to load module instaloader. Make sure you have installed correctly all dependencies.
If instaloader keeps failing and you are running this script on a Raspberry, please visit this project's Wiki on GitHub (https://github.com/instabot-py/instabot.py/wiki) for more information.
Traceback (most recent call last):
  File "./instabot_py/instabot.py", line 42, in <module>
    globals()[modname] = importlib.import_module(modname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'instaloader'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/myname/instabot.py/example.py", line 4, in <module>
    from instabot_py import InstaBot
  File "./instabot_py/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "./instabot_py/instabot.py", line 52, in <module>
    quit()
  File "/usr/lib/python3.7/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None
>>>

**Comment by clementin35** [comment]
just import following libraries in instabot.py

import requests
import instaloader

**Comment by Modderov** [comment]
i tried this but error occurrs: 

19:02 ~/instabot.py (master)$ pip install --user instaloader
Looking in links: /usr/share/pip-wheels
Collecting instaloader
  Using cached https://files.pythonhosted.org/packages/86/be/95b14652bc85ce9c43da508d2d63954a736aa22ffedfb8b9cbed4d752a12/instaloader-2.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Instaloader requires Python >= 3.5.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-MF4yGA/instaloader/

**Comment by dimisdas** [comment]
pip3.6 install --user instabot-py

**Comment by clementin35** [comment]
Pip install -r requirements.txt 

You need >3.5 Python

**Comment by dimisdas** [comment]
@clementin35 there’s no “requirements.txt” anymore. The best course of action would be installing the instabot-py module through PyPi. It will install all dependencies automatically.

**Comment by Modderov** [comment]
pip3.6 install --user instabot-py worked :
19:52 ~/instabot.py/instabot_py (master)$ pip3.6 install --user instabot-py
Looking in links: /usr/share/pip-wheels
Requirement already satisfied: instabot-py in /home/Pizzaefocaccia/.local/lib/python3.6/site-packages (0.4.7)
Requirement already satisfied: blessings==1.7.0 in /home/Pizzaefocaccia/.local/lib/python3.6/site-packages (from instabot-py) (1.7)
Requirement already satisfied: fake-useragent==0.1.11 in /home/Pizzaefocaccia/.local/lib/python3.6/site-packages (from instabot-py) (0.1.11)
Requirement already satisfied: requests==2.21.0 in /home/Pizzaefocaccia/.local/lib/python3.6/site-packages (from instabot-py) (2.21.0)
Requirement already satisfied: instaloader==4.2.1 in /home/Pizzaefocaccia/.local/lib/python3.6/site-packages (from instabot-py) (4.2.1)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from blessings==1.7.0->instabot-py) (1.11.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests==2.21.0->instabot-py) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3.6/site-packages (from requests==2.21.0->instabot-py) (2.7)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests==2.21.0->instabot-py) (1.23)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.6/site-packages (from requests==2.21.0->instabot-py) (2018.8.13)
19:52 ~/instabot.py/instabot_py (master)$ 


but still error:

Failed to load module instaloader. Make sure you have installed correctly all dependencies.
If instaloader keeps failing and you are running this script on a Raspberry, please visit this project's Wiki on GitHub (https://github.com/instabot-py/instabot.py/wiki) for more information.
Traceback (most recent call last):
  File "./instabot_py/instabot.py", line 42, in <module>
    globals()[modname] = importlib.import_module(modname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'instaloader'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/Pizzaefocaccia/instabot.py/example.py", line 4, in <module>
    from instabot_py import InstaBot
  File "./instabot_py/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "./instabot_py/instabot.py", line 52, in <module>
    quit()
  File "/usr/lib/python3.7/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

**Comment by dimisdas** [comment]
You installed Instabot using pip3.6 but running it using 3.7.

Try installing again with pip3.7 instead. Version must match.

**Comment by clementin35** [comment]
@dimisdas, I have used requirements.txt to install all libraries 2 days ago, it’s working on me flawlessy. Sorry, I didn’t know that you removed

**Comment by Modderov** [comment]
great, solved!!! thanks a lot

**Comment by dimisdas** [comment]
Cheers :)
