### ISSUE TITLE
Follow Function blocked

### ISSUE THREAD

**Issue by chris0211** [instabot-py/instabot.py#2123]
#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
``` 3.7
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
login="",  # Enter username (lowercase). Do not enter email!
    password="",
    like_per_day=1000,
    comments_per_day=300,
    tag_list=["follow4follow", "f4f", "cute", "l:212999109", "instatravel", "travelgram", "traveller", "travel", "traveler", "blackandwhite", "instaphoto", "streetphotography"],
    tag_blacklist=["rain", "thunderstorm"],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60 * 60,
    unfollow_per_day=0,
    unlike_per_day=0,
    unfollow_recent_feed=True,
    # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
    time_till_unlike=3 * 24 * 60 * 60,  # 3 days
    unfollow_break_min=15,
    unfollow_break_max=30,
    user_max_follow=0,
    # session_file=False, # Set to False to disable persistent session, or specify custom session_file (ie ='myusername.session')
    user_min_follow=0,
    log_mod=0,
```

Hi, 
first, the instabot by itself is running fine. Logon is working and the bot is doing it's job. But after a few auto-follows, Insta block my account from the following function.

Somebody here with the same problem? Any Ideas how to solve this issue?

THX
Chris

**Comment by dimisdas** [comment]
300 comments per day are too many. You are getting rate limited.

Also, if this is a new account, the limits are WAY lower for the first 6-12 months. If you are using other bots or apps (i.e. "Who Unfollowed You" or "Analytics" types of apps), then there's a chance you are already spending your quota there. Lower your settings, try increasing them slowly. Cheers :)
