### ISSUE TITLE
How to avoid getting same users to follow in follow_user_followers?

### ISSUE THREAD

**Issue by rodrigosnader** [instabot-py/instabot.py#2125]
Hi guys, please excuse me if there's anything wrong with this question, but it's one of my first questions/issues here in GitHub.

I'm trying to schedule to follow 100 user followers every hour. The problem is that after the first hour I get: 

"After filtering followed, unfollowed and skipped, 0 user_ids left to follow."

How do I get followers from a certain checkpoint instead of getting always the same user's followers?

Thank you in advance.

**Comment by dimisdas** [comment]
I think you are using a different bot :)
