### ISSUE TITLE
ValueError: Unable to configure handler 'telegram'

### ISSUE THREAD

**Issue by nachovoss** [instabot-py/instabot.py#2133]
python 3.7 
 i' m getting the following error?  
Telegram is now connected to the bot? what for?

Traceback (most recent call last):
  File "example.py", line 4, in <module>
    from instabot_py import InstaBot
  File "C:\Users\Nacho\Desktop\instabot.py-2019\mayo\instabot.py\instabot_py\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\Nacho\Desktop\instabot.py-2019\mayo\instabot.py\instabot_py\instabot.py", line 22, in <module>
    from instabot_py.config import config
  File "C:\Users\Nacho\Desktop\instabot.py-2019\mayo\instabot.py\instabot_py\config.py", line 43, in <module>
    logging.config.dictConfig(config.get("logging"))
  File "C:\Users\Nacho\AppData\Local\Programs\Python\Python37\lib\logging\config.py", line 799, in dictConfig
    dictConfigClass(config).configure()
  File "C:\Users\Nacho\AppData\Local\Programs\Python\Python37\lib\logging\config.py", line 570, in configure
    '%r' % name) from e
ValueError: Unable to configure handler 'telegram'

**Comment by yurilaaziz** [comment]
In your instabot.config.yml
Please remove this part if you don’t want to forward logs to your telegram account.


logging.formatters.telegram.format: "%(name)s - %(levelname)s - %(message)s"
logging.handlers.telegram:
  level: INFO
  formatter: telegram
  class: telegram_handler.TelegramHandler
  token: TELEGRAM_BOT_TOKEN
  chat_id: TELEGRAM_CHAT_ID

logging.loggers.InstaBot.handlers:
  - telegram
  - console


Install python-telegram-handler if you would like to use telegram

> pip install python-telegram-handler

To activate it,create yourself a telegram bot and receive a chat id 

Register a new telegram bot and obtain a ``authentication token``. (Instructions here https://core.telegram.org/bots#3-how-do-i-create-a-bot)

After that, you must obtain a ``chat_id``. You can do that using included simple script. Start a new conversation with newly created bot, write something to it (it is important to initiate conversation first).

**Comment by Liturgikus** [comment]
I had the same issue, and did what you told him to do. But know I have this issue :
/usr/local/lib/python3.7/site-packages/config42/handlers/files/yaml.py:13: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(f)
INFO:instabot_py.config:Setting configuration from instabot.config.yml : OK
Traceback (most recent call last):
  File "example.py", line 127, in <module>
    start_at_m = 00, # Minute you want the bot to start, in this example 9:10 (am).
  File "/home/pi/flaskenv/frenchsowine/instabot_py/instabot.py", line 60, in __init__
    self.persistence = PersistenceManager(config.get('database'))
  File "/home/pi/flaskenv/frenchsowine/instabot_py/persistence/manager.py", line 10, in __new__
    from instabot_py.persistence.sql import Persistence
  File "/home/pi/flaskenv/frenchsowine/instabot_py/persistence/sql.py", line 3, in <module>
    from sqlalchemy import Column, Integer, String, DateTime
ModuleNotFoundError: No module named 'sqlalchemy'

**Comment by OGProgrammer** [comment]
I'm confused, I did the `example.py` route but that seems to be using the python object directly vs the cli cmd. I tried running the cli cmd `instabot-py` which generates the config `instabot.config.ini` but this isn't what the readme/docs say about the config being a `yml` file called `instabot.config.yml`

I've gotten the bot to work with the python script directly how I want but how the hell do you get telegram configured? I tried added the telegram token/chat id in the yml file but I have a feeling this yml file isn't even being read.

**Comment by vahid172002** [comment]
this is my problem . please help .i want config telegram bot , but a cant

**Comment by wahengchang** [comment]
same, do u guys have a solution

**Comment by yurilaaziz** [comment]
I explain the change made here https://medium.com/@asker_amine/instabot-py-rework-7fa68a6cadab

**Comment by wahengchang** [comment]
@yurilaaziz  you are right. fix my problem with ：   
### 1) install
```
$ pip install python-telegram-handler
```

### 2) install telegram on my phone

### 3) create a channel and getting token by the bad ass `@BotFather`

### 4) getting my new bot id by the bad ass `@get_id`

### 5) put the `channel id` and `token` on the yml config
