### ISSUE TITLE
Module Not Found Error:

### ISSUE THREAD

**Issue by Martypary** [instabot-py/instabot.py#2135]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [x ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```python 3.7.2
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```
pip 19.1

#### Description of your issue

```
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. All rights reserved.

PS C:\Users\Administrator> & C:/Users/Administrator/AppData/Local/Programs/Pytho
n/Python37/python.exe c:/Users/Administrator/Desktop/instabot1.db/example1.py
Traceback (most recent call last):
  File "c:/Users/Administrator/Desktop/instabot1.db/example1.py", line 4, in <module>
    from instabot_py import InstaBot
  File "c:\Users\Administrator\Desktop\instabot1.db\instabot_py\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "c:\Users\Administrator\Desktop\instabot1.db\instabot_py\instabot.py", line 22, in <module>
    from instabot_py.config import config
  File "c:\Users\Administrator\Desktop\instabot1.db\instabot_py\config.py", line 4, in <module>
    from config42 import ConfigManager
ModuleNotFoundError: No module named 'config42'
PS C:\Users\Administrator>

I tried everything I could think of, but nothing works
```

**Comment by beakman** [comment]
This new version introduced new dependencies. You should install config42==0.3.1 module :-)

**Comment by Martypary** [comment]
Hahha oww thanks 😅
