### ISSUE TITLE
Proxies don't work for me.

### ISSUE THREAD

**Issue by Pantic14** [instabot-py/instabot.py#2138]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [X] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32```

#### Pip Version?
```
pip 19.0.3 from c:\users\pantic\appdata\local\programs\python\python37-32\lib\site-packages\pip (python 3.7)```

#### Description of your issue

```
Traceback (most recent call last):
  File "--.py", line 7, in <module>
    proxy_chrome_extension = create_proxy_extension(proxy)
  File "D:\salvado\Automatas\Instagram\Instapyv3\instabot.py-master\proxy_extension.py", line 69, in create_proxy_extension
    with zipfile.ZipFile(pluginfile, 'w') as zp:
  File "C:\Users\-\AppData\Local\Programs\Python\Python37-32\lib\zipfile.py", line 1204, in __init__
    self.fp = io.open(file, filemode)
OSError: [Errno 22] Invalid argument: 'assets/chrome_extensions/proxy_auth_XXXX.zip'
```

It was working perfectly for me until a few days ago.
I've tested that the proxies are working properly and they are.
Without proxies it works.

**Comment by Pantic14** [comment]
why close?

**Comment by dimisdas** [comment]
Sorry, the tag wasn't saved apparently. You have posted to the wrong repo. The output in your description indicates that you are using a different bot (possibly InstaPy?)
