### ISSUE TITLE
HTTP 500 on Like

### ISSUE THREAD

**Issue by skvie** [instabot-py/instabot.py#2139]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ x ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ x ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [ x ] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.2
```

#### Pip Version?
```
pip 18.1
```

#### Description of your issue
I can successfully log in, but when trying to like media I get a HTTP Status Code 500
```
 def like(self, media_id):
        """ Send http request to like media by ID """
        if self.login_status:
            url_likes = self.url_likes % (media_id)
            try:
                like = self.s.post(url_likes)
                last_liked_media_id = media_id
                print(like.status_code) # Std out returns 500 here 
            except:
                logging.exception("Except on like!")
                like = 0
            return like
```

**Comment by yurilaaziz** [comment]
could you print the stack trace ?
