### ISSUE TITLE
doesn't work with generated code

### ISSUE THREAD

**Issue by nemoback** [instabot-py/instabot.py#2140]
root@servername:~# instabot-py username
     Loading settings for username!
     Config: /root/instabot.config.ini 

     ______Starting bot_____
10.05.2019_00:09 Checking for updates...
10.05.2019_00:09 You are running the latest stable version
10.05.2019_00:09 Instabot v1.2.5/0 started at 10.05.2019 00:09:
10.05.2019_00:09 Trying to login as username...
10.05.2019_00:09 Something wrong with login
10.05.2019_00:09 {"message": "checkpoint_required", "checkpoint_url": "/challenge/300343039/EIoQUnHDOx/", "lock": false, "status": "fail"}
10.05.2019_00:09 Challenge required at https://instagram.com/challenge/300343039/EIoQUnHDOx/
Challenge Required.

Enter the code sent to your mail/phone: 217549
10.05.2019_00:09 Entered code is wrong, Try again later!
10.05.2019_00:09 Exit Program... GoodBye
root@servername:~# 

Code is definitely correct one, tried many times, simply doesn't work.

**Comment by manguszta** [comment]
It happened to me in a couple of days ago, code is incorrect.
If you run your bot from your PC and you have a mobile data provider, try turn your phone into a wifi hotspot and connect your PC to this network. Run the bot again. Switch back to your internet provider on your PC after the bot made a couple of likes.
