### ISSUE TITLE
Showing error while running instabot.py file...help me

### ISSUE THREAD

**Issue by arun1kumar31** [instabot-py/instabot.py#2155]
I am attaching error below... fix it, please

C:\Users\PC\Downloads\instabot.py-master>python example.py
C:\Users\PC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\config42
\handlers\files\yaml.py:13: YAMLLoadWarning: calling yaml.load() without Loader=
... is deprecated, as the default Loader is unsafe. Please read https://msg.pyya
ml.org/load for full details.
  return yaml.load(f)
INFO:instabot_py.config:Setting configuration from instabot.config.yml : OK
Traceback (most recent call last):
  File "example.py", line 122, in <module>
    unfollow_whitelist=["example_user_1", "example_user_2"],
  File "C:\Users\PC\Downloads\instabot.py-master\instabot_py\instabot.py", line
60, in __init__
    self.persistence = PersistenceManager(config.get('database'))
  File "C:\Users\PC\Downloads\instabot.py-master\instabot_py\persistence\manager
.py", line 10, in __new__
    from instabot_py.persistence.sql import Persistence
  File "C:\Users\PC\Downloads\instabot.py-master\instabot_py\persistence\sql.py"
, line 3, in <module>
    from sqlalchemy import Column, Integer, String, DateTime
ModuleNotFoundError: No module named 'sqlalchemy'

C:\Users\PC\Downloads\instabot.py-master>

**Comment by uzairnz** [comment]
Did you fixed this problem?

**Comment by arun1kumar31** [comment]
Nope.. did not get any solution...
