### ISSUE TITLE
Can't find example.py

### ISSUE THREAD

**Issue by Liturgikus** [instabot-py/instabot.py#2157]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
3.7
Include here the response of 'python --version' or 'python3 --version'
Python 3.7.2

#### Pip Version?
pip 18.1
Include here the response of 'pip --version' or 'pip3 --version'
pip 18.1

#### Description of your issue

I installed the nex version of instabot on my raspberry pi in a virtual environment folder; but I can't find the folder where example.py was usually installed. I can run the bot correctly with the new command instabot-py, but, I don't know where is example.py. I can only edit config.ini file.

**Comment by dimisdas** [comment]
Download example.py by itself (don’t need the rest of the files). Edit it and run it.

`curl -O https://raw.githubusercontent.com/instabot-py/instabot.py/master/example.py`
