### ISSUE TITLE
The bot not getting media with location

### ISSUE THREAD

**Issue by khaleefaalhammadi** [instabot-py/instabot.py#2158]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [X] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
Python 3.7.2
Include here the response of 'python --version' or 'python3 --version'
```
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> python --version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'python' is not defined
```
#### Pip Version?
pip 19.1.1 
Include here the response of 'pip --version' or 'pip3 --version'
```
pip 19.1.1 from c:\users\alhammadi\appdata\local\programs\python\python37-32\lib\site-packages\pip (python 3.7)
```
#### Description of your issue

When I'm trying to run Instabot and and I used interaction with location  to find post, the bot looking and not getting any post to like or comment. 

  ______Starting bot_____
15.05.2019_14:44 Checking for updates...
15.05.2019_14:44 > UPDATE AVAILABLE Please update Instabot 'python3 -m pip install instabot-py --upgrade'
15.05.2019_14:44 Instabot v1.2.4/0 started at 15.05.2019 14:44:
15.05.2019_14:44 Found session file instarooooom.session
15.05.2019_14:44 instarooooom login success!

15.05.2019_14:44 Saving cookies to session file instarooooom.session
15.05.2019_14:44 Get Media by location: 328670654
15.05.2019_14:44 Trying to like media: 2044254662278628790
                 https://www.instagram.com/p/BxepsjPjcW2/
15.05.2019_14:44 Liked: 2044254662278628790. Like #1.
15.05.2019_14:44 Trying to follow: 5989141959
15.05.2019_14:44 Followed: 5989141959 #1.
15.05.2019_14:44 Trying to comment: 2044203409485307994
15.05.2019_14:44 Trying to unfollow #1:
15.05.2019_14:44 Getting user info : mtjar_sara2018
15.05.2019_14:44 Checking user info..
15.05.2019_14:44 Follower : 1223
15.05.2019_14:44 Following : 2689
15.05.2019_14:44 Media : 1177
15.05.2019_14:44    >This user is active
15.05.2019_14:44    >This account is following you
15.05.2019_14:44    >You are following this account
15.05.2019_14:45 Get Media by location: 582170077
15.05.2019_14:45 Get Media by location: 217485961
15.05.2019_14:45 Get Media by location: 107702695950474
15.05.2019_14:45 Get Media by location: 225910740
15.05.2019_14:45 Get Media by location: 328670654
15.05.2019_14:46 Get Media by location: 74029867
15.05.2019_14:46 Get Media by location: 107702695950474
15.05.2019_14:46 Get Media by location: 107702695950474
15.05.2019_14:46 Get Media by location: 1699667666729889
15.05.2019_14:46 Get Media by location: 107702695950474
15.05.2019_14:47 Get Media by location: 1699667666729889
15.05.2019_14:47 Get Media by location: 542845074
15.05.2019_14:47 Get Media by location: 217485961
15.05.2019_14:48 Get Media by location: 225910740
15.05.2019_14:48 Trying to like media: 2028170174003193352
                 https://www.instagram.com/p/BwlggcNgKYI/
15.05.2019_14:48 Liked: 2028170174003193352. Like #2.
15.05.2019_14:48 Get Media by location: 5139740
15.05.2019_14:48 Get Media by location: 1699667666729889
15.05.2019_14:48 Get Media by location: 582170077
15.05.2019_14:48 Get Media by location: 328670654
15.05.2019_14:49 Get Media by location: 107702695950474
15.05.2019_14:49 Get Media by location: 74029867
15.05.2019_14:49 Get Media by location: 74029867
15.05.2019_14:50 Get Media by location: 242883449
15.05.2019_14:50 Get Media by location: 582170077
15.05.2019_14:50 Get Media by location: 225910740
15.05.2019_14:50 Get Media by location: 5139740

```

#### Config

```
[DEFAULT]
username = none
password = none
like_per_day = 400
comments_per_day = 31
max_like_for_one_tag = 36
follow_per_day = 260
follow_time = 36000
unfollow_per_day = 247
unfollow_break_min = 3
unfollow_break_max = 17
log_mod = 0
proxy = 
unfollow_selebgram = False
unfollow_probably_fake = True
unfollow_inactive = True
unfollow_recent_feed = False
comment_list = [["Special Ramdan Offer from Next Step GYM at Mushrif Mall @nextstep_gym","Hurry up and get Ramadan Discount @nextstep_gym","The best Ramdan Offer and discount @nextstep_gym","Burn Fat and Lose Weight with Best Ramdan Discount @nextstep_gym","Never Give UP everyone has bad days, pick yourself up and keep Going to Get Ramdan Offer @nextstep_gym","It doesn't get easier, you just get better and better Ramadan Discount @nextstep_gym","Nothing Will Work Unless You Do. Special Ramdan Discount  @nextstep_gym","Best Offer till 10th Ramdan at Mushrif Mall branch @nextstep_gym","Next Step Gym Give you special Ramdan Offer till 10th of the holy month @nextstep_gym","@nextstep_gym You will get the best Ramdan Discount for the membership","Amazing Ramdan Discount with Next Step Fitness Center @nextstep_gym","Membership Discount with Next Step Center until 10th of Ramadan @nextstep_gym","Enjoy Ramdan Meals, and enjoy the best workout program and Ramdan discount @nextstep_gym","Come and Get Special discount with best gym, the offer is valid till 10th Ramdan @nextstep_gym","Ramdan is different this year with best Discount at Next Step Center @nextstep_gym","Don't miss the best Ramdan discount with Next step GYM @nextstep_gym","You are eligible for Ramdan Discount, come and Join Next Step Gym Before 10th Ramdan @nextstep_gym","Ramdan Mubarak. Hurry up and get Ramdan discount @nextstep_gym","Hurry up and find the Ramdan Offers at Next Step Bodybuilding and Fitness Center @nextstep_gym","Workout harder in Ramdan and get Ramdan Offer @nextstep_gym","Next Step GYM offer you Ramdan Discount for a few days @nextstep_gym","Fitness, in my opinion, is a mental exercise more than just physical. Hurry up for Ramdan Discount @nextstep_gym","Join Next Step Centers and Don't miss Ramdan Offers @nextstep_gym","Ramdan Mubarak, till 10th Ramdan you will get special offer with @nextstep_gym","Really Ramdan Discount with @nextstep_gym","Always remember: good things take time. Hurry up and get Ramdan Offer @nextstep_gym","Pain is weakness leaving the body.Get Ramdan Offer at @nextstep_gym","Best Trainers, Best Workout Program and Best Ramdan Offer @nextstep_gym","Hard work beats talent when talent doesn’t work hard. Ramdan Mubarak, Hurry up for Ramdan Offer  @nextstep_gym","Winners Train, Losers Complain. Ramdan Offer valid till 10th Ramdan @nextstep_gym"], ["....", "!!!", "..!", ".!!", "..!!!"]]
tag_list = ["follow4follow", "f4f", "cute", "l:212999109"]
tag_blacklist = ["rain", "thunderstorm"]
unwanted_username_list = []
unfollow_whitelist = ["example_user_1", "example_user_2"]

[instarooooom]
username = 
password = 
like_per_day = 400
comments_per_day = 200
max_like_for_one_tag = 40
follow_per_day = 200
follow_time = 36000
unfollow_per_day = 200
tag_list = ["l:242883449", "l:582170077", "l:107702695950474", "l:1699667666729889", "l:225910740", "l:328670654", "l:217485961", "l:5139740", "l:542845074", "l:630005440476151", "l:74029867"]
unfollow_selebgram = False
unfollow_probably_fake = True
unfollow_inactive = True
unfollow_recent_feed = False
```

**Comment by bogxxy** [comment]
I have the same issue, any help ?

**Comment by nureinspiel** [comment]
SAME! PLEASE HELP!

**Comment by mactrash** [comment]
Have update to the latest code and got same issue

Just loop as below

2019-05-28 19:31:32,080 - InstaBot - DEBUG - Get Media by tag: xxxxxx
2019-05-28 19:31:34,875 - InstaBot - DEBUG - Tic!
2019-05-28 19:31:35,879 - InstaBot - DEBUG - Tic!
2019-05-28 19:31:36,883 - InstaBot - DEBUG - Tic!
2019-05-28 19:31:37,887 - InstaBot - DEBUG - Tic!
2019-05-28 19:31:38,891 - InstaBot - DEBUG - Tic!
2019-05-28 19:31:39,895 - InstaBot - DEBUG - Tic!
2019-05-28 19:31:40,899 - InstaBot - DEBUG - Tic!
2019-05-28 19:31:41,903 - InstaBot - DEBUG - Tic!
2019-05-28 19:31:42,907 - InstaBot - DEBUG - Tic!
2019-05-28 19:31:43,911 - InstaBot - DEBUG - Tic!
2019-05-28 19:31:44,915 - InstaBot - DEBUG - Tic!
2019-05-28 19:31:45,919 - InstaBot - DEBUG - Tic!
2019-05-28 19:31:46,923 - InstaBot - DEBUG - Tic!

**Comment by dimisdas** [comment]
Please upgrade via pip. You are using an older version.
