### ISSUE TITLE
Proxy and CMD Installs

### ISSUE THREAD

**Issue by jorianj** [instabot-py/instabot.py#2162]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [X] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```
python 3.7.3

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```
pip 19.1.1
#### Description of your issue
Hi,

I have some questions :) First of all I made some accounts in CMD But I can't find a file where the installs I made be. I need the files to install it better like example.py. Second question How can I add proxy to the accounts I made in CMD. 
Thanks for your help!

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by dimisdas** [comment]
The file is in your active directory. However, you'll need to download example.py and edit it for setting up the proxy.

Cheers
