### ISSUE TITLE
INSABOT - DEBUG - TIC!

### ISSUE THREAD

**Issue by marcosenno88** [instabot-py/instabot.py#2163]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue
i've just donwloaded the last version unpdate the requiments run it but i have have a loop of this: "INSABOT - DEBUG - TIC!
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```
INSABOT - DEBUG - TIC!
![Cattura](https://user-images.githubusercontent.com/37532558/58006663-dff6b700-7ae8-11e9-8977-4abdae887763.JPG)
![Cattura](https://user-images.githubusercontent.com/37532558/58006679-eb49e280-7ae8-11e9-8bf6-70151aee5601.JPG)
![Cattura](https://user-images.githubusercontent.com/37532558/58006690-f3a21d80-7ae8-11e9-8785-6ed9ea09a5d1.JPG)

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by uzairnz** [comment]
same problem

**Comment by dimisdas** [comment]
Change the debug value in instabot.config.yml to disable debug log.

**Comment by marcosenno88** [comment]
nothing change still the same
![Cattura](https://user-images.githubusercontent.com/37532558/58025371-9754f300-7b14-11e9-99c6-4367186622a9.JPG)

**Comment by ycodryn** [comment]
Same here. Changed from 0 to 1 to false but I have same error

**Comment by mykrov** [comment]
Same issue here, On instabot.config.yml debug: 0 is default. I was change to 1 and 2 but still that.

2019-05-20 10:17:52,407 - InstaBot - INFO - Liked: 2047668165275297766. Like #2 https://www.instagram.com/p/Bxqx1jpHCfm/.
INFO:InstaBot:Liked: 2047668165275297766. Like #2 https://www.instagram.com/p/Bxqx1jpHCfm/.
2019-05-20 10:17:53,408 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-20 10:17:54,410 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-20 10:17:55,428 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-20 10:17:56,428 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-20 10:17:57,438 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-20 10:17:58,444 - InstaBot - DEBUG - Tic!
DEBUG:InstaBot:Tic!
2019-05-20 10:17:59,445 - InstaBot - DEBUG - Tic!

**Comment by marcosenno88** [comment]
some one has find a solution to this?

**Comment by FlawlessEnt** [comment]
Why is this marked as closed? I also changed the debug value in instabot.config.yml to disable debug log with no success. Still need solution.

**Comment by husligc** [comment]
same thing happening to me.

**Comment by FlawlessEnt** [comment]
So I see where the action is being called in the file instabot.py Line 828:... but wedo we do about this 🤔 
`def mainloop(self):
        while self.prog_run and self.login_status:
            now = datetime.datetime.now()
            # distance between start time and now
            dns = self.time_dist(datetime.time(self.start_at_h,
                                               self.start_at_m),
                                 now.time())
            # distance between end time and now
            dne = self.time_dist(datetime.time(self.end_at_h,
                                               self.end_at_m),
                                 now.time())
            if (dns == 0 or dne < dns) and dne != 0:
                # ------------------- Get media_id -------------------
                if len(self.media_by_tag) == 0:
                    self.get_media_id_by_tag(random.choice(self.tag_list))
                    self.this_tag_like_count = 0
                    self.max_tag_like_count = random.randint(
                        1, self.max_like_for_one_tag
                    )
                    self.remove_already_liked()
                # ------------------- Like -------------------
                self.new_auto_mod_like()
                # ------------------- Unlike -------------------
                self.new_auto_mod_unlike()
                # ------------------- Follow -------------------
                self.new_auto_mod_follow()
                # ------------------- Unfollow -------------------
                self.new_auto_mod_unfollow()
                # ------------------- Comment -------------------
                self.new_auto_mod_comments()
                # Bot iteration in 1 sec
                time.sleep(1)
                self.logger.debug("Tic!")
            else:
                self.logger.debug(
                    "Sleeping until {hour}:{min}".format(
                        hour=self.start_at_h, min=self.start_at_m
                    )
                )
                time.sleep(100)
        self.logger.info("Exit Program... GoodBye")
        sys.exit(0)``

**Comment by omidcse** [comment]
> some one has find a solution to this?

Nope!  I have the same issue and the threads are all closed in this manner!

**Comment by ycodryn** [comment]
Is easier to close I think. Use an older version.

**Comment by marcosenno88** [comment]
The todays updated version works fine 👌🏻

Il giorno gio 30 mag 2019 alle 14:20 ycodryn <notifications@github.com> ha
scritto:

**Comment by husligc** [comment]
Still doesn't work correctly.  It changes hashtags after each comment, this makes the comment the first one on each post, seconds after the person posted.  Very unauthentic.  Still no fix? @dimisdas

**Comment by FlawlessEnt** [comment]
Alrighty... I'll give the updated version a shot and report back 😉
