### ISSUE TITLE
trying to unfollow not working

### ISSUE THREAD

**Issue by nilix-nl** [instabot-py/instabot.py#2167]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.5.3

Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)


#### Description of your issue
The bot is not unfollow  anybody
I see the tekst steel but it is not working..
Make likes is oke en follow people is also oke..

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
20.05.2019_21:17 Trying to unfollow #1

#### Config

[nilix_bies]
username = me
password = me
like_per_day = 963
comments_per_day = 80
max_like_for_one_tag = 300
follow_per_day = 1
tag_list = ["xx "xx", "xx",
follow_time =120
unfollow_per_day = 247
unfollow_break_min = 2
unfollow_break_max = 17
comment_list = [["this", "the", "your"], ["photo", "picture", "pic", "shot", "snapshot"], ["is", "looks", "feels", "is re"] 
unfollow_selebgram = False
unfollow_probably_fake = True
unfollow_inactive = True
unfollow_recent_feed = False
unfollow_whitelist = ["mamablof", "robin18_2", "biancs6675", "xliezie", "justinklaasse", "tweety_x", "kim.heijmans", "isb"]

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by dimisdas** [comment]
Who exactly do you want the bot to unfollow?

According to the config you posted, you only follow 1 account per day. The bot will only attempt to unfollow this account.

If you need to unfollow other accounts (that were NOT followed by the bot), then you need to set unfollow_recent_feed=True
