### ISSUE TITLE
Error on the first run: "No module named 'sqlalchemy'"

### ISSUE THREAD

**Issue by leonaestrada8** [instabot-py/instabot.py#2169]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])

- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting? Google Cloud
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour) - Ubuntu 18.0.4 LTS
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
Python 3.6.8

#### Pip Version?
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

#### Description of your issue

Thanks for your help. I'm out of alternatives.

When I start a new Google Cloud Ubuntu 18.04 LTS (or Ubuntu 19.04 LTS) I'm using the following commands to install the bot:

                               sudo -H apt-get update
                               sudo -H apt-get install git -y
                               sudo -H apt-get install python-pip -y 
                               sudo -H apt-get install python3-pip -y
                               sudo -H python3 -m pip install instabot-py
                               sudo -H git clone https://github.com/instabot-py/instabot.py.git
                               sudo -H pip3 install requests
                               sudo -H pip3 install -e ./instabot.py
                               python3 example.py

Then, doesn't matter the content of example.py, I receive a similar error as shown below below:

GENERIC EXAMPLE.PY:

INFO:instabot_py.config:Setting configuration from instabot.config.yml : OK
Traceback (most recent call last):
  File "example.py", line 122, in <module>
    unfollow_whitelist=["example_user_1", "example_user_2"],
  File "/home/leo_c_passos_gmail_com/instabot.py/instabot_py/instabot.py", line 60, in __init__
    self.persistence = PersistenceManager(config.get('database'))
  File "/home/leo_c_passos_gmail_com/instabot.py/instabot_py/persistence/manager.py", line 10, in __new__
    from instabot_py.persistence.sql import Persistence
  File "/home/leo_c_passos_gmail_com/instabot.py/instabot_py/persistence/sql.py", line 3, in <module>
    from sqlalchemy import Column, Integer, String, DateTime
ModuleNotFoundError: No module named 'sqlalchemy'

EDITED EXAMPLE.PY:

INFO:instabot_py.config:Setting configuration from instabot.config.yml : OK
Traceback (most recent call last):
  File "leo.py", line 78, in <module>
    start_at_m = 10,
  File "/home/leo_c_passos_gmail_com/instabot.py/instabot_py/instabot.py", line 60, in __init__
    self.persistence = PersistenceManager(config.get('database'))
  File "/home/leo_c_passos_gmail_com/instabot.py/instabot_py/persistence/manager.py", line 10, in __new__
    from instabot_py.persistence.sql import Persistence
  File "/home/leo_c_passos_gmail_com/instabot.py/instabot_py/persistence/sql.py", line 3, in <module>
    from sqlalchemy import Column, Integer, String, DateTime
ModuleNotFoundError: No module named 'sqlalchemy'

#### Config

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from instabot_py import InstaBot

bot = InstaBot(
    login="XXXXX",  # Enter username (lowercase). Do not enter email!
    password="XXXX",
    like_per_day=1000,
    comments_per_day=100,
    tag_list=["mochilão", "amongthewild", "travelgram", "montanhismo", "trilha", "escalada", "wanderlust", "blogdeviagem", "mochileiros","florestaamazonica", "mataatlantica", "paisagem", "biodiversidade", "roadtrip", "ferias", "cachoeira", "motocicleta", "kaferacer", "caferacer", "deserto", "travelphotography", "trekking", "vibenaviagem", "hiking", "travelblogger", "neverstopexploring", "roamtheplanet", "exploremore", "maenatureza", "fotografos_brasileiros", "gohiking", "forceofnature", "adventureislife", "adventureiscalling", "getoutandexplore", "travelingislife", "traveladdicted", "travelaroundtheworld", "westbysouthwest", "igsouthwest", "trilheiros", "trilhando", "trekkingbrasil", "trilhasetravessias", "trilhaseaventuras", "trilhandomontanhas" ],
    tag_blacklist=["hotelsoftheworld", "hotelsofinstagram", "noivas2019", "noivas", "aluguetemporada", "alugase", "politica", "lulalivre", "bolsonaro", "motogadget", "sexy", "gravida", "pregnant", "marriage", "travelagent", "bolsomito", "fotoinfantil", "kidsphotoshoot", "criança", "fotodecriança", "sorteio", "autos", "automovil", "compras", "moda", "jesus", "obrigadoDeus", "obgdDeus", "obrigadosenhor", "cvcviagens", "hospedesqueridos", "hospedesfelizes", "besttour", "clubmed", "club", "vegan", "vegetarian", "tour", "gay", "couple", "gaycouple", "lgbt" ],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=2 * 60 * 60,
    unfollow_per_day=100,
    unlike_per_day=0,
    unfollow_recent_feed=True,
    # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
    time_till_unlike=3 * 24 * 60 * 60,  # 3 days
    unfollow_break_min=15,
    unfollow_break_max=30,
    user_max_follow=5000,
    # session_file=False, # Set to False to disable persistent session, or specify custom session_file (ie ='myusername.session')
    user_min_follow=0,
    log_mod=0,
    proxy="XXXXX",
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
        comment_list=[
        [ "??", "??" ],
   ],
    # Use unwanted_username_list to block usernames containing a string
    # Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    # 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        "project",
        "love",
        "life",
        "food",
        "blog",
        "free",
        "indo",
        "travel",
        "art",
        "shop",
        "store",
        "sex",
        "online",
        "fashion",
        "corp",
        "butik",
        "karpet",
        "salon",
        "skin",
        "care",
        "cloth",
        "tech",
        "rental",
        "kamera",
        "beauty",
        "express",
        "kredit",
        "collection",
        "impor",
        "follow",
        "follower",
        "gain",
        ".id",
        "bags",
    ],
    unfollow_whitelist=["raul"],
    # Enable the following to schedule the bot. Uses 24H
     end_at_h = 23, # Hour you want the bot to stop
     end_at_m = 55,# Minute you want the bot stop, in this example 23:30
start_at_h = 8,
start_at_m = 10,
)

bot.mainloop()

**Comment by zurex76** [comment]
Hey, Just want to write that I have the exact same issue. Since I updated it (about 5 days ago). It doesnt work anymore :(

**Comment by dimisdas** [comment]
Fixed :)

**Comment by agung00978654** [comment]
Closed#2169
Pada tanggal 22 Mei 2019 10.40 PM, "Dimis" <notifications@github.com>
menulis:

**Comment by zurex76** [comment]
I update the bot and I still have the same issue
