### ISSUE TITLE
Install on Pythonanywhere

### ISSUE THREAD

**Issue by armin671** [instabot-py/instabot.py#2171]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
v3.7 
```

#### Pip Version?
```
v18
```

#### Description of your issue

instabot.py-master was downloaded, it is working on win10 (example.py is not working) when i cmd: instabot-py (twice, first for config, second for running)
i tried to use it on pythonanywhere.com:
1.there is no tutorial for new version of bot
2.after clone it, typing>> instabot-py= Error
3. typing>>example.py=Error

I dont know how to deal with it, help me please ! 

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by numanozel** [comment]
yes I have same issue
