### ISSUE TITLE
Error: No module named 'config42' 

### ISSUE THREAD

**Issue by harshitsinghwap** [instabot-py/instabot.py#2172]
throwing an error while running example.py on pythonanywhere.com:
Traceback (most recent call last):
  File "/home/har7787/instabot.py/example.py", line 3, in <module>
    from instabot_py import InstaBot
  File "./instabot_py/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "./instabot_py/instabot.py", line 22, in <module>
    from instabot_py.config import config
  File "./instabot_py/config.py", line 4, in <module>
    from config42 import ConfigManager
ModuleNotFoundError: No module named 'config42'

**Comment by dimisdas** [comment]
1. It has been posted again. You need to install the dependencies properly. Search the previous issues. :)

2. You’re missing the issue template. All issues posted  without the template are closed regardless of their content.

3. You have made low effort to describe the issue appropriately as outlined in the guidelines (help us help you better).

Don’t worry though. If you need informal advice, or if you’re inexperienced with issues on GitHub, feel free to join the Telegram group and ask around. 

Cheers!
