### ISSUE TITLE
Looks like account was deleted, skipping

### ISSUE THREAD

**Issue by AluminumChassis** [instabot-py/instabot.py#2173]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
3.7.2
```

#### Pip Version?
```
19.1.1
```

#### Description of your issue
I am trying to unfollow a large number of people, but maybe 19/20 attempts to unfollow by the bot come out like this:
```
Looks like account was deleted, skipping : 0
```
And I do not know why.
#### Config

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from instabot_py import InstaBot

bot = InstaBot(
    login="", 
    password="",

    like_per_day=0,
    follow_per_day=0,
    comments_per_day=0,

    unfollow_per_day=19200,
    unfollow_everyone=True,

    unfollow_break_min=5,
    unfollow_break_max=10
)

bot.mainloop()

```

**Comment by likafox** [comment]
Same here............
