### ISSUE TITLE
Bot is ignoring "unfollow_everyone = true"

### ISSUE THREAD

**Issue by waynoedm** [instabot-py/instabot.py#2174]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [X] Kali Linux
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.3rc1
```

#### Pip Version?
```
pip 18.1 
```

#### Description of your issue

```
Running several versions of the bot. unfollow_everyone = true has no effect on operation.  Even with the other settings set to false, or removed entirely, it is still checking all users against the criteria and not unfollowing:

22.05.2019_04:37    >This is a normal account
22.05.2019_04:37    >This user is active
22.05.2019_04:37    >This account is following you
22.05.2019_04:37    >You are following this account

```

#### Config

```
like_per_day = 0
comments_per_day = 0
max_like_for_one_tag = 6
follow_per_day = 0
follow_time_enabled = false
unfollow_per_day =900
unfollow_break_min = 3
unfollow_break_max = 17
unfollow_everyone = true
unfollow_selebgram = false
unfollow_probably_fake = false
unfollow_inactive = false
unfollow_recent_feed = false

```

**Comment by dimisdas** [comment]
Fixed https://github.com/instabot-py/instabot.py/commit/0c93cf8e7ea3e24a38a5659fa89e0e05d1023418
