### ISSUE TITLE
Can't unfollow

### ISSUE THREAD

**Issue by likafox** [instabot-py/instabot.py#2177]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
v3.7 

#### Pip Version?
v18

#### Description of your issue

I can't do unfollow. Already tried several modification on configuration. Did last update, tried python3.7 and python3... Tried change following time from 5 * 60 * 60 to 90 seconds to make it faster..., tried to change unfollow_recent_feed=False as well (would like to work with True). Would like to work in Mode 0. 

First was getting this:
Looks like there is nobody to unfollow

Now after few changes:

Trying to unfollow #1:
Getting user info : 0
Looks like account was deleted, skipping : 0

(already 6h like this)

#### Config

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from instabot_py import InstaBot

bot = InstaBot(
    login="xxxxxxx",  # Enter username (lowercase). Do not enter email!
    password="xxxxxxxxx",
    like_per_day=800,
    comments_per_day=150,
    tag_list=["portrait", "portrait", "barcelonaphotographer", "portraitpage", "bravogreatphoto", "portraitphotography", "portrait_vision", "theportraitpr0ject", "connectBCN", "barcelona", "barcelone", "barcelonacity", "barcelona_cat", "frenchboys", "barcelona_cat", "moodyports"],
    tag_blacklist=[],
    user_blacklist={},
    max_like_for_one_tag=30,
    follow_per_day=0,
    follow_time=5 * 60 * 60,
    unfollow_per_day=600,
    unlike_per_day=0,
    unfollow_recent_feed=True,
    # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
    time_till_unlike=3 * 24 * 60 * 60,  # 3 days
    unfollow_break_min=15,
    unfollow_break_max=30,
    user_max_follow=0,
    # session_file=False, # Set to False to disable persistent session, or specify custom session_file (ie ='myusername.session')
    user_min_follow=0,
    log_mod=0,
    proxy="",
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[
        [ "🙌🙌", " 👏👏", "☺️☺️", "😊😊", "😀😀"],
    ],
    # Use unwanted_username_list to block usernames containing a string
    # Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    # 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
    ],
    unfollow_whitelist=["example_user_1", "example_user_2"],
    # Enable the following to schedule the bot. Uses 24H
    # end_at_h = 23, # Hour you want the bot to stop
    # end_at_m = 30, # Minute you want the bot stop, in this example 23:30
    # start_at_h = 9, # Hour you want the bot to start
    # start_at_m = 10, # Minute you want the bot to start, in this example 9:10 (am).
)

bot.mainloop()

**Comment by dimisdas** [comment]
Please update via pip. Thanks!
