### ISSUE TITLE
Looks like there is nobody to unfollow

### ISSUE THREAD

**Issue by CodeitIT** [instabot-py/instabot.py#2179]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x ] Linux (Raspbian)
- [ ] Android (include terminal)

#### Python Version Requirement
- [ x] I am using Python 3.6 or above

#### Exact Python Version?
```
'python --version'
Python 3.7.0
```

#### Pip Version?
```
'pip3 --version'
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)
```

#### Description of your issue

```
The bot works fine, I can follow, like and comment. But everytime after the database finished populating. The bot says 
'26.05.2019_23:20 Trying to unfollow #1:'
'26.05.2019_23:20 Looks like there is nobody to unfollow.'

I already updated, reinstalled and deleted the database.

```

#### Config

```
[DEFAULT]
username = none
password = none
like_per_day = 709
comments_per_day = 31
max_like_for_one_tag = 36
follow_per_day = 260
follow_time = 36000
unfollow_per_day = 247
unfollow_break_min = 3
unfollow_break_max = 17
log_mod = 0
proxy = 
unfollow_selebgram = False
unfollow_probably_fake = True
unfollow_inactive = True
unfollow_recent_feed = False
comment_list = [["this", "the", "your"], ["photo", "picture", "pic", "shot", "snapshot"], ["is", "looks", "feels", "is really"], ["great", "super", "good", "very good", "good", "wow", "WOW", "cool", "GREAT", "magnificent", "magical", "very cool", "stylish", "beautiful", "so beautiful", "so stylish", "so professional", "lovely", "so lovely", "very lovely", "glorious", "so glorious", "very glorious", "adorable", "excellent", "amazing"], [".", "..", "...", "!", "!!", "!!!"]]
tag_list = ["follow4follow", "f4f", "cute", "l:212999109"]
tag_blacklist = ["rain", "thunderstorm"]
unwanted_username_list = ["second", "stuff", "art", "project", "love", "life", "food", "blog", "free", "keren", "photo", "graphy", "indo", "travel", "art", "shop", "store", "sex", "toko", "jual", "online", "murah", "jam", "kaos", "case", "baju", "fashion", "corp", "tas", "butik", "grosir", "karpet", "sosis", "salon", "skin", "care", "cloth", "tech", "rental", "kamera", "beauty", "express", "kredit", "collection", "impor", "preloved", "follow", "follower", "gain", ".id", "_id", "bags"]
unfollow_whitelist = ["example_user_1", "example_user_2"]

[------------]
username = xxxxxxxx
password = xxxxxxxxx
like_per_day = 1000
comments_per_day = 0
max_like_for_one_tag = 36
follow_per_day = 220
follow_time = 36000
unfollow_per_day = 240
tag_list = ["meme", "memes", "gg", "gj", "hi", "memesdaily", "memedaily", "dailymeme", "dailymemes", "daily", "mumes", "meeeems", "meems", "haha", "ha", "haa"]
unfollow_everyone = True
unfollow_selebgram = True
unfollow_probably_fake = True
unfollow_inactive = True
unfollow_recent_feed = True

```

**Comment by dimisdas** [comment]
> I already updated, reinstalled and deleted the database.

Please post the details and the relevant output of all the steps.

**Comment by CodeitIT** [comment]
'When I update'
pi@raspberrypi:~/instabot.py $ sudo pip3 install instabot-py --no-cache-dir --upgrade
Requirement already up-to-date: instabot-py in /usr/local/lib/python3.5/dist-packages
Requirement already up-to-date: blessings==1.7.0 in /usr/local/lib/python3.5/dist-packages (from instabot-py)
Requirement already up-to-date: requests==2.21.0 in /usr/local/lib/python3.5/dist-packages (from instabot-py)
Requirement already up-to-date: fake-useragent==0.1.11 in /usr/local/lib/python3.5/dist-packages (from instabot-py)
Requirement already up-to-date: instaloader==4.2.1 in /usr/local/lib/python3.5/dist-packages (from instabot-py)
Requirement already up-to-date: six in /usr/lib/python3/dist-packages (from blessings==1.7.0->instabot-py)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests==2.21.0->instabot-py)
Requirement already up-to-date: idna<2.9,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests==2.21.0->instabot-py)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests==2.21.0->instabot-py)
Requirement already up-to-date: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests==2.21.0->instabot-py)

**Comment by CodeitIT** [comment]
The thing is everything works fine. And I can also read that the database isn't empty...

`26.05.2019_23:40 Get Media by tag: hi
26.05.2019_23:40 Trying to like media: 2052581371536240600
                 https://www.instagram.com/p/Bx8O-HjAG_Y/
26.05.2019_23:40 Liked: 2052581371536240600. Like #1.
26.05.2019_23:40 Trying to follow: 1600074686
26.05.2019_23:40 Followed: 1600074686 #1.
26.05.2019_23:40 miofreaks : Get media id on recent feed
26.05.2019_23:40 Media in recent feed = 12
26.05.2019_23:40 Inserted user theanointingofbadboys from recent feed
26.05.2019_23:40 Inserted user gorilasgotcha from recent feed
26.05.2019_23:40 Trying to unfollow #1:
26.05.2019_23:40 Looks like there is nobody to unfollow.
26.05.2019_23:41 Get Media by tag: memesdaily
26.05.2019_23:41 Trying to like media: 2052580848322197766
                 https://www.instagram.com/p/Bx8O2gRA7kG/
26.05.2019_23:41 Liked: 2052580848322197766. Like #2.`

**Comment by dimisdas** [comment]
You’re using pip3 which is connected to python3.5 judging by the logs. But you’re mentioning in your initial post that you are using 3.7.0.

You need to upgrade the 3.7 modules. Perhaps using pip3.7 or python3.7 -m pip

**Comment by dimisdas** [comment]
Please also try to force upgrade instaloader

**Comment by CodeitIT** [comment]
How can i force upgrade it ? 
(Instaloader)

**Comment by dimisdas** [comment]
--no-cache-dir --upgrade --force-reinstall

**Comment by CodeitIT** [comment]
While force upgrading INSTALOADER i get this 2 ERROR lines but in the end it says sucessoflly installed.

ERROR: instabot-py 0.4.7 has requirement instaloader==4.2.1, but you'll have instaloader 4.2.7 which is incompatible.
ERROR: instabot-py 0.4.7 has requirement requests==2.21.0, but you'll have requests 2.22.0 which is incompatible.

**Comment by CodeitIT** [comment]
`pip --version`
pip 19.1.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

**Comment by Malper19** [comment]
how do i update ??

 UPDATE AVAILABLE Please update Instabot 'python3 -m pip install instabot-py --upgrade'

can some one help me step by step

**Comment by kaschmirrr** [comment]
Hello,
i have time same problem and too few linux knowledge to update. Can you please write the instabot Update command to Update the bot successful. Would bei very kind.
Thanks

**Comment by CodeitIT** [comment]
I just let the bot do for 1-2 days and now everything works fine just make sure that in your config.ini you write True not true and you set unfollow_recent_feed=True

**Comment by CodeitIT** [comment]
This thread can be closed. Just wait a afew days 😁 Thank you all

**Comment by Malper19** [comment]
And for windows do I need to update or will it fix its self ?

**Comment by kenanEkici** [comment]
Updating pip, using Python3.7 and a complete package reinstall fixed it for me
