### ISSUE TITLE
Issue Line 1 Instabot Issue Line 22 import config Issue Line 4 ConfigManager

### ISSUE THREAD

**Issue by laz1791** [instabot-py/instabot.py#2180]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```
Hello Everyone I ran across this issue when installing instabot.py. Does anyone have a solution to this problem?

_____________________________________________________________________________________________________

ERROR CODE BELOW

C:\Users\DELL\Desktop\IG_BOT\instabot.py-master>python example.py
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    from instabot_py import InstaBot
  File "C:\Users\DELL\Desktop\IG_BOT\instabot.py-master\instabot_py\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\DELL\Desktop\IG_BOT\instabot.py-master\instabot_py\instabot.py", line 22, in <module>
    from instabot_py.config import config
  File "C:\Users\DELL\Desktop\IG_BOT\instabot.py-master\instabot_py\config.py", line 4, in <module>
    from config42 import ConfigManager
ModuleNotFoundError: No module named 'config42'

**Comment by dimisdas** [comment]
Please upgrade via pip. Thanks!
