### ISSUE TITLE
Huge issues with raspberry pi and conflicting python versions

### ISSUE THREAD

**Issue by friendlytherapist** [instabot-py/instabot.py#2182]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x ] Linux (raspbian)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
3.7.3
Include here the response of 'python --version' or 'python3 --version'
3.7.3, 3.7.3

#### Pip Version?
latest
Include here the response of 'pip --version' or 'pip3 --version'
latest

#### Description of your issue

When installing instabot on a raspberry pi you get LOADS of confliction between python 3.7 and 3.5. Following your 3.7 build tutorial does work. BUT running instabot-py does not since it defaults to 3.5 for some reason I tried update-alternatives, alias and "ln" no success. I havent tried it but you should add "./configure --prefix=/usr/local/opt/python-3.7.0" to the tutorial or something like that because its definitely wrong. The only way i got it to work was to completely rip out python3.5 by running "sudo apt-get purge python3.5*" and im sure my system is fucked now but at least instabot works.

**Comment by dimisdas** [comment]
You can specify the python version you wish to run a module with by `python3.7 -m instabot_py`. Installing via `python3.7 -m pip install instabot-py` should work, even with multiple python installations.

If you accidentaly install using 3.5, then pip will add it to your path and run it using 3.5. You'll have to uninstall using `python3 -m pip uninstall instabot-py` first before reinstalling using 2.7

The installation guide for Raspberry uses alt-install and should not cause any conflicts between versions.

Whatever the case, I strongly suggest you look up on virtual environment and start using it to avoid any future troubles.

Good luck! Cheers

**Comment by friendlytherapist** [comment]
Thanks for the reply, I wiped my raspian install and installed python with your instructions but calling python3.7 returns "command not found"
