### ISSUE TITLE
Exception: account details are missing

### ISSUE THREAD

**Issue by crayss** [instabot-py/instabot.py#2188]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by crayss** [comment]
I completed the initial configuration but when I run the script I get the message **exception: account details are missing** 

I have checked the config files and my account details are there so I really dont know why I get this massage.. 

What am I doing wrong?

**Comment by dimisdas** [comment]
Which version are you running and how did you install? Thanks

**Comment by mvanio** [comment]
In the config.ini file use the 'username' param. When using the example.py script the 'login' param is needed instead.

**Comment by crayss** [comment]
@dimisdas version info: ubuntu 19.04, python 3.7.3, pip 18.1. I installed it with python3 -m pip install instabot-py, then i used python3 -m instabot_py to start the bot, instabot.config.ini was created then i tried running it again but all i get is exception: account details are missing.

**Comment by crayss** [comment]
@mvanio i'm not quite sure what you mean, but i'm not trying to run example.py, anyway when i run example i get the same massage.

**Comment by crayss** [comment]
Thanks but i run python3 -m instabot_py from the dir instabot_py and now it works.
