### ISSUE TITLE
Can u help me please i have this problem !!!

### ISSUE THREAD

**Issue by Doggi2112** [instabot-py/instabot.py#2190]
I apologize because it is just my beginning.

![Screenshot from 2019-05-29 18-48-40](https://user-images.githubusercontent.com/44559039/58602618-755d1e00-8242-11e9-80de-b7668fd59201.png)

**Comment by kenanEkici** [comment]
You need to install instabot using **pip3 install instabot**

**Comment by Doggi2112** [comment]
> You need to install instabot using **pip3 install instabot-py**

man how can i contact you to help me 

![Screenshot from 2019-05-30 16-18-06](https://user-images.githubusercontent.com/44559039/58671195-8e270b80-82f6-11e9-90d1-0d7af787205f.png)
