### ISSUE TITLE
Not unfollowing anyone

### ISSUE THREAD

**Issue by jeevanu** [instabot-py/instabot.py#2191]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

Waiting for database to populate before unfollowing (progress 0 /20)

**Comment by jkyp91** [comment]
I am having this issue too!

**Comment by roviraleix** [comment]
Hello, same issue here, it looks like the boot can not obtain the user id

Traceback (most recent call last):
  File "C:\Users\xxx \Desktop\IG\config\xxx\instabot_py\instabot.py", line 560, in get_username_by_user_id
    profile = instaloader.Profile.from_id(self.instaload.context, user_id)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\instaloader\structures.py", line 409, in from_id
    rhx_gis=context.root_rhx_gis)['data']['user']
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python36\lib\site-packages\instaloader\instaloadercontext.py", line 507, in root_rhx_gis
    self._root_rhx_gis = self.get_json('', {})['rhx_gis']
KeyError: 'rhx_gis'

**Comment by dimisdas** [comment]
Which version are you running?

**Comment by Gaafar** [comment]
@dimisdas I'm facing the same issue. Not sure about this, but it seems that this commit changed the table name for getting the users count from `usernames` to `followers`, so it's no longer counting the users in old .db files

https://github.com/instabot-py/instabot.py/commit/d022f0379cdf87775a3427631472c56cdce1eae9#diff-ae5142c11a03ceef6573815aa44ccfa9

**Comment by dimisdas** [comment]
Pretty sure the error above is related to Instaloader, one of the dependencies. The newer version has been updated and the gis token is correctly retrieved. 

You'll need to upgrade via pip. Let me know if it persists to reopen it.
