### ISSUE TITLE
REQUEST: Suppress "debug" or "info" in log output

### ISSUE THREAD

**Issue by saabia** [instabot-py/instabot.py#2193]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x ] Feature Request
- [] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [X ] Linux (include flavour) raspberry pi
- [ ] Android (include terminal)

#### Python Version Requirement
- [ x] I am using Python 3.6 or above

#### Exact Python Version?
```3.7
Include here the response of 'python --version' or 'python3 --version'
```3.7.2

#### Pip Version?
```19.1.1
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```Hello  how can i change the log to console output? Since the update today everytime it says:
"2019-05-30 11:37:43,456 - InstaBot **- INFO -** "
"2019-05-30 11:37:43,472 - InstaBot **- DEBUG -** "
i want to remove the INFO and DEBUG text in the logs like it was before because i got a tiny screen and this is breaking the line to the next line where instabot is running on my raspberry.

Further i got the problem if i LOG OUT with CTRL + C i got "Exit Program... GoodBye" again. 
With the last version i fixed this with setting the session file to false. But since the update the massage comes again and i dont get the Likes, Follows, Unfollows and so on if i try to log out with ctrl + c. How can i fix this?

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from instabot_py import InstaBot

bot = InstaBot(
    login="xxx",  # Enter username (lowercase). Do not enter email!
    password="xxx",
    like_per_day=1009,
    comments_per_day=257,
    tag_list = ["doesnt matter"],
#   tag_blacklist=["rain", "thunderstorm"],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=1003,
    follow_time=43200,
    unfollow_per_day=1003,
    unlike_per_day=0,
#   unfollow_recent_feed=True,
    unfollow_not_following=True,
    unfollow_selebgram = True,
    unfollow_probably_fake = True,
    unfollow_inactive = True,
#   unfollow_everyone = True,
    # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
#   time_till_unlike=3 * 24 * 60 * 60,  # 3 days
    unfollow_break_min=5,
    unfollow_break_max=10,
    user_max_follow=0,
    session_file=False, # Set to False to disable persistent session, or specify custom session_file (ie ='myusername.session')
    user_min_follow=0,
    log_mod=0,
    proxy="",
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list = [["doesnt matter"]]
,
    # Use unwanted_username_list to block usernames containing a string
    # Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    # 'free_followers' will be blocked because it contains 'free
    unfollow_whitelist=["example_user_1", "example_user_2"],
    # Enable the following to schedule the bot. Uses 24H
    # end_at_h = 23, # Hour you want the bot to stop
    # end_at_m = 30, # Minute you want the bot stop, in this example 23:30
    # start_at_h = 5, # Hour you want the bot to start
    # start_at_m = 30, # Minute you want the bot to start, in this example 9:10 (am).
)

bot.mainloop()

**Comment by saabia** [comment]
Also it looks like it doesnt use the right config file, since today for the update i had to install yml it says by start: 
root@pihole:~# python3.7 example.py
INFO:instabot_py.config:Setting configuration from instabot.config.yml : OK
2019-05-30 11:49:39,166 - InstaBot - INFO - Checking for updates...
2019-05-30 11:49:39,747 - InstaBot - INFO - You are running the latest stable version
2019-05-30 11:49:39,748 - InstaBot - INFO - Instabot v1.2.6/0 started at 30.05.2019 11:49:
2019-05-30 11:49:39,748 - InstaBot - INFO - Trying to login as

**Comment by kj2shin** [comment]
I am seeing a similar behaviour here after the update.

**Comment by gershee** [comment]
same problem. how do we downgrade to previous version?

**Comment by yurilaaziz** [comment]
https://medium.com/@asker_amine/whats-new-in-the-instagram-bot-0-5-2-fe52154fdc8a
run it using the newer cli 

`instabot-py -c config.yml -v ` INFO
`instabot-py -c config.yml -vv` DEBUG

**Comment by impshum** [comment]
```
from instabot import Bot
import logging

bot = Bot()
bot.logger.setLevel(logging.WARNING)
```

DEBUG, INFO, WARNING, ERROR , CRITICAL
