### ISSUE TITLE
help ,does not start

### ISSUE THREAD

**Issue by PABLOSKI6652** [instabot-py/instabot.py#2194]
I have this problem when logging in, I did boot the bot and I throw the bug in the following lines before I had this problem I had a stable old python version I do not remember which and the instabot.py-master folder with its requirements.txt file now there is a new file reposion but its content is very different from what it was before I do not understand anything is more complicated everything just ask that someone can help me tell me what version of python you use and if you can share the link where I download the folder instabot.py-master with its respective content as it was before and not as now that there are many things and it is not understood and I would say that it changes the writing of the commands in the cmd and I do not understand much of this I have only asked that someone help me if you have the boot running help me , share link instabot.py-master and version python using

thanks

Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])

  I have searched for other issues with the same problem or similar feature requests.
Select one:
  Bug
  Feature Request
  Technical Help
[x ] Other
Environment
  Are you hosting the bot on a VPS or other Cloud hosting?
[x ] If so, have you tried running the code on your local machine?
Operating System? (include version)
  macOS
[x ] Windows
  Linux (include flavour)
  Android (include terminal)
Python Version Requirement
[x ] I am using Python 3.6 or above
Exact Python Version?3.6.3
Include here the response of 'python --version' or 'python3 --version'
Pip Version?3.6.3
Include here the response of 'pip --version' or 'pip3 --version'
Description of your issue
C:\Users\chip\Downloads\instabot.py-master>python example.py
29.05.2019_10:53 Instabot v1.2.0 started at 29.05.2019 10:53:

29.05.2019_10:53 Trying to login as WTFT...

Traceback (most recent call last):
File "example.py", line 52, in 
unfollow_whitelist=['example_user_1', 'example_user_2'])
File "C:\Users\chip\Downloads\instabot.py-master\src\instabot.py", line 236, in init
self.login()
File "C:\Users\chip\Downloads\instabot.py-master\src\instabot.py", line 287, in login
self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
File "C:\Users\chip\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\cookies.py", line 328, in getitem
return self._find_no_duplicates(name)
File "C:\Users\chip\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

C:\Users\chip\Downloads\instabot.py-master>

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT

#### Config

#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="WTFT",
    password="66666444422",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=['spain', 'photooftheday', 'malaga', 'madrid','BCN','love','followxfollow'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=500,
    follow_per_day=800,
    follow_time=120 * 60,
    unfollow_per_day=200,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

**Comment by dimisdas** [comment]
You're using a really old version.

**Comment by PABLOSKI6652** [comment]
@dimisdas   could you share the links with the python version for windows 10 and the file instabot

**Comment by dimisdas** [comment]
No. Everything is in README

**Comment by PABLOSKI6652** [comment]
I do not understand

**Comment by PABLOSKI6652** [comment]
one thing in the cmd of windows wrote pip install -r requirements.txt but now I write that and I can not continue could you please the commands that I have to write in the cmd thanks for your patience
