### ISSUE TITLE
proxy error help

### ISSUE THREAD

**Issue by qtwe** [instabot-py/instabot.py#2195]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [ x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

I have a problem with a proxy, when I insert a proxy into the code, this one comes out. Does anyone know what this is about?
thank you

C:\Users\Biljana\Desktop\instabot.py-master\instabot_py>python instabot.py
  File "instabot.py", line 144
    self.s.proxies = {"https" : "http://181.40.122.102:8080"}
    ^
IndentationError: unexpected indent

C:\Users\Biljana\Desktop\instabot.py-master\instabot_py>python instabot.py
  File "instabot.py", line 144
    self.s.proxies = {"https" : "http://181.40.122.102:8080"}
    ^
IndentationError: unexpected indent

**Comment by dimisdas** [comment]
Python is very sensitive with syntax and indents (tabs, spaces, etc).

You'll need to lookup how to write syntaxically correct Python, and perhaps get an editor/IDE to highlight your errors.
