### ISSUE TITLE
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default L

### ISSUE THREAD

**Issue by djmarcosban** [instabot-py/instabot.py#2199]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [X] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
```
python --version
```

#### Pip Version?
```
pip 19.1.1 from c:\users\marcos\appdata\local\programs\python\python37-32\lib\site-packages\pip (python 3.7)
```

#### Description of your issue

```
C:\instabot.py>instabot-py link.universitarios
C:\Users\Marcos\AppData\Roaming\Python\Python37\site-packages\config42\handlers\files\yaml.py:13: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(f)
INFO:instabot_py.config:Setting configuration from instabot.config.yml : OK
     Loading settings for link.universitarios!
     Config: C:\instabot.py\instabot.config.ini
```

#### Config

```
default config get this problem.
```

I've updated the instabot, reinstalled python and pip so far I still have this problem ...
This began to happen after the upgrade. :(

**Comment by yurilaaziz** [comment]
thank you for your interest. 
this warning is related to config42 library. 
could you please transfer it to this repo please https://github.com/yurilaaziz/config42/issues

**Comment by mrallanodreman** [comment]
This is solved? im having this problem

**Comment by yurilaaziz** [comment]
Fixed in newer releases
