### ISSUE TITLE
get_user_pictures(user)

### ISSUE THREAD

**Issue by shayanb** [instabot-py/instabot.py#22]
Any plans to implement get_user_pictures(user, limit = 20) ? 
I think it might be possible with ink361, but couldn't find appropriate url for this case.

**Comment by ageorgios** [comment]
+1 for this

**Comment by LevPasha** [comment]
@shayanb and @ageorgios i think you can use https://data.ink361.com/v1/tags/<TAG>/media/recent?callback=&count=50. But there is just 50 limit, or you should read how they paginatioin work.
