### ISSUE TITLE
instabot.py instantly crashing on raspberry pi

### ISSUE THREAD

**Issue by jhnprivate** [instabot-py/instabot.py#2203]
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    from instabot_py import InstaBot
  File "/home/pi/Downloads/instabot1/instabot.py-master/instabot_py/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/pi/Downloads/instabot1/instabot.py-master/instabot_py/instabot.py", line 58
    config.set("session_file", f"{login.lower()}.session", default=True)

what is this?

**Comment by emerutus** [comment]
I am experiencing exactly the same issue. Please someone help me

**Comment by friendlytherapist** [comment]
How did you install python3.7?  I wiped my raspian install and installed python with the instructions but calling python3.7 returns command not found. I have done this about 5 times and it does not work.

**Comment by emerutus** [comment]
I was able to get it to work by running the following command line

pip install -r requirements/base.txt

**Comment by yurilaaziz** [comment]
Please follow the template
