### ISSUE TITLE
Post in another language

### ISSUE THREAD

**Issue by Beta3** [instabot-py/instabot.py#2204]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [x] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by Beta3** [comment]
Hello, 
Where can I change the Random Posts texts ?
I want to post them in spanish

Thank you very much

**Comment by LolaReilly** [comment]
Hola. En "comment_list". por ejemplo:
comment_list=[
                  ["Guau", "Wow"],
                  ["me"],
                  ["encanta", "gusta"],
                  ["la", "esa"],
                  ["foto", "fotografía", "imagen"]
                  ],

La idea es que en cada corchete pongas, entre paréntesis y separadas por comas, palabras que se puedan combinar entre sí para formar las frases.
