### ISSUE TITLE
start

### ISSUE THREAD

**Issue by taghaviali34** [instabot-py/instabot.py#2210]
hi how can i understaand its started ,

and where can i change the parametres in in 

instabot.config.ini

or 
instabot.py?
thanks

do u have any video to learn this

**Comment by nikolasvargas** [comment]
after installed, just run instabot-py. You will setup your instagram account by an CLI. After configured, the instabot.config.ini file will be generated.

For more advanced parameters and configurations download and edit example.py and run python3 example.py
