### ISSUE TITLE
Bot tries to follow same user

### ISSUE THREAD

**Issue by regoautomatic** [instabot-py/instabot.py#2211]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [x] Linux (include flavour) Ubuntu Mate on Raspberry Pi3
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
Python 3.6.1
Include here the response of 'python --version' or 'python3 --version'
Python 3.6.1

#### Pip Version?
9.0.1
Include here the response of 'pip --version' or 'pip3 --version'
pip 9.0.1 from c:\users\miguel\appdata\local\programs\python\python36-32\lib\site-packages (python 3.6)

#### Description of your issue
When I start the bot, it tries to follow the same user more than once at the same minute. So after a time, my account will be blocked for follows.

07.06.2019_15:03 xxxxxx login success!
07.06.2019_15:03 Get media id by tag: xxxxxxxx
07.06.2019_15:03 NOT Removing already liked medias..
07.06.2019_15:03 Trying to like media: 2061017205346307929
07.06.2019_15:03 Liked: 2061017205346307929. Like #1.
07.06.2019_15:03 Trying to follow: 3621150435
07.06.2019_15:03 Followed: 3621150435 #1.
07.06.2019_15:03 Trying to follow: 3621150435
07.06.2019_15:03 Followed: 3621150435 #2.
07.06.2019_15:03 Trying to follow: 3621150435
07.06.2019_15:03 Followed: 3621150435 #3.
.
.
.
This is happening on my Raspberry Pi 3 with Ubuntu Mate, and in my laptop with Windows 10.

My example.py file:

bot = InstaBot(
    login="xxxxxxx",
    password="xxxxxxx",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=['sport','model', 'landscape', 'sunset', 'travel','travelgram', 'car', 'nature', 'naturelovers', 'instanature','like4like', 'follow4follow','photographer'],
    tag_blacklist=[],
    user_blacklist={},
    max_like_for_one_tag=30,
    follow_per_day=200,
    follow_time=3 * 60 * 60,
    unfollow_per_day=0,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,

**Comment by nickgryg** [comment]
This is very outdated issue. If you still have it, please update instabot-py to version 0.5.20 or later.
