### ISSUE TITLE
"You may have shared your username...."

### ISSUE THREAD

**Issue by PirateSchmirate** [instabot-py/instabot.py#2212]
![image000000](https://user-images.githubusercontent.com/42244567/59152054-0d10f800-8a0b-11e9-8286-48182aeba7df.jpg)

Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ x] Other

#### Environment
- [ no] Are you hosting the bot on a VPS or other Cloud hosting? (Running in Windows 10)
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [ x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
3.7.2

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

Instagram's fighting bots apparently. This is the 2nd time in a week we've received this error message. We're only using instabot for like automation. No comments, follows, unfollows, or any of that jazz. Can't attach config, as posting from home, not at comp. Screenshot attached.


Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by yurilaaziz** [comment]
please dump your configuration

**Comment by PirateSchmirate** [comment]
@yurilaaziz, do you mean clear it, or post it?

**Comment by PirateSchmirate** [comment]
Dumping the config did not work. Just got shadow banned "based on previous," error message.

**Comment by ChipWolf** [comment]
@PirateSchmirate they mean show us your config..

**Comment by PirateSchmirate** [comment]
@ChipWolf I might need some help with that. I did pip install instabot-py, and I'm having problems locating the config, or even example.py. :/ I download/installed while in my Downloads folder, but it looks like I'm seeing and older instabot download

**Comment by PirateSchmirate** [comment]
`[DEFAULT]
username = none
password = none
like_per_day = 709
comments_per_day = 31
max_like_for_one_tag = 36
follow_per_day = 260
follow_time = 36000
unfollow_per_day = 247
unfollow_break_min = 3
unfollow_break_max = 17
log_mod = 0
proxy = 
unfollow_selebgram = False
unfollow_probably_fake = True
unfollow_inactive = True
unfollow_recent_feed = False
comment_list = [["this", "the", "your"], ["photo", "picture", "pic", "shot", "snapshot"], ["is", "looks", "feels", "is really"], ["great", "super", "good", "very good", "good", "wow", "WOW", "cool", "GREAT", "magnificent", "magical", "very cool", "stylish", "beautiful", "so beautiful", "so stylish", "so professional", "lovely", "so lovely", "very lovely", "glorious", "so glorious", "very glorious", "adorable", "excellent", "amazing"], [".", "..", "...", "!", "!!", "!!!"]]
tag_list = ["follow4follow", "f4f", "cute", "l:212999109"]
tag_blacklist = ["rain", "thunderstorm"]
unwanted_username_list = ["second", "stuff", "art", "project", "love", "life", "food", "blog", "free", "keren", "photo", "graphy", "indo", "travel", "art", "shop", "store", "sex", "toko", "jual", "online", "murah", "jam", "kaos", "case", "baju", "fashion", "corp", "tas", "butik", "grosir", "karpet", "sosis", "salon", "skin", "care", "cloth", "tech", "rental", "kamera", "beauty", "express", "kredit", "collection", "impor", "preloved", "follow", "follower", "gain", ".id", "_id", "bags"]
unfollow_whitelist = ["example_user_1", "example_user_2"]

[username]
username = ""
password = ""
like_per_day = 500
comments_per_day = 0
max_like_for_one_tag = 50
follow_per_day = 0
follow_time = 36000
unfollow_per_day = 0
tag_list = ["weightlosshelp", "obesetofit", "weightlossjourney", "momgetsfit", "fitnessjourney", "momofteens", "gettingfitagain", "fitmom", "projectmanager", "strongnotskinny"]
unfollow_selebgram = 0
unfollow_probably_fake = 0
unfollow_inactive = 0
unfollow_recent_feed = 0

`

**Comment by dicrigius1** [comment]
Same issue for me... I have follow already blocked from 2 weeks...

**Comment by ChipWolf** [comment]
You've gotta go easy on the likes. That's far too many. Especially with newer accounts.
You have to ramp it up slowly

**Comment by PirateSchmirate** [comment]
@ChipWolf, this isn't a new account, but I get that. Been using instabot for almost a year now, and the account has almost 4000 followers. Lol. What's a good starting point since the bot starts at 750 but default?

**Comment by dicrigius1** [comment]
Also mine, not new over 5.6k follower but something is changed
