### ISSUE TITLE
Start and stop time missing in config.ini

### ISSUE THREAD

**Issue by mbe9477** [instabot-py/instabot.py#2215]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [X] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

I am simply missing the "start_at..." and "end_at..." option in my instabot.confit.ini file. 
Can anybody help me and explain how to add these options because now my bot is running 24/7 and I was already banned a few times.
Thank you!

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

[DEFAULT]
username = none
password = none
like_per_day = 709
comments_per_day = 31
max_like_for_one_tag = 36
follow_per_day = 260
follow_time = 36000
unfollow_per_day = 247
unfollow_break_min = 3
unfollow_break_max = 17
log_mod = 0
proxy = 
unfollow_selebgram = False
unfollow_probably_fake = True
unfollow_inactive = True
unfollow_recent_feed = False
comment_list = [["this", "the", "your"], ["photo", "picture", "pic", "shot", "snapshot"], ["is", "looks", "feels", "is really"], ["great", "super", "good", "very good", "good", "wow", "WOW", "cool", "GREAT", "magnificent", "magical", "very cool", "stylish", "beautiful", "so beautiful", "so stylish", "so professional", "lovely", "so lovely", "very lovely", "glorious", "so glorious", "very glorious", "adorable", "excellent", "amazing"], [".", "..", "...", "!", "!!", "!!!"]]
tag_list = ["follow4follow", "f4f", "cute", "l:212999109"]
tag_blacklist = ["rain", "thunderstorm"]
unwanted_username_list = ["second", "stuff", "art", "project", "love", "life", "food", "blog", "free", "keren", "photo", "graphy", "indo", "travel", "art", "shop", "store", "sex", "toko", "jual", "online", "murah", "jam", "kaos", "case", "baju", "fashion", "corp", "tas", "butik", "grosir", "karpet", "sosis", "salon", "skin", "care", "cloth", "tech", "rental", "kamera", "beauty", "express", "kredit", "collection", "impor", "preloved", "follow", "follower", "gain", ".id", "_id", "bags"]
unfollow_whitelist = ["example_user_1", "example_user_2"]

[MY_ACCOUNT]
username = XXX
password = XXX
like_per_day = 500
comments_per_day = 50
max_like_for_one_tag = 100
follow_per_day = 75
follow_time = 36000
unfollow_per_day = 0
tag_list = [XXX]
unfollow_selebgram = False
unfollow_probably_fake = True
unfollow_inactive = True
unfollow_recent_feed = False

**Comment by yurilaaziz** [comment]
I suggest that you run the Instabot as crontab.
Running Instabot as Service/Daemon is not well optimised for

**Comment by taghaviali34** [comment]
Hi, I went ahead step by step with readme , but how can i understan  robot activated? Please help me be completely confused.

**Comment by nickgryg** [comment]
This is very outdated issue. Version 0.5.20 of instabot-py is available right now. Now it is clear how to create configuration and start a bot.
