### ISSUE TITLE
Something wrong with login - Instabot

### ISSUE THREAD

**Issue by LolaReilly** [instabot-py/instabot.py#2217]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version? 
```
Python 3.7.3
```

#### Pip Version?
```
19.1.1
```

#### Description of your issue

```
I'm using the updated version of Instabot. It throws an error "name='csrftoken', domain=None, path=None".

I've tried all the solutions that I've found, changed the password, tried with a different Instagram account... Nothin works. I get this all the time:

INFO:instabot_py.config:Setting configuration from instabot.config.yml : OK
2019-06-11 13:31:03,001 - InstaBot - INFO - Checking for updates...
2019-06-11 13:31:03,764 - InstaBot - INFO - You are running the latest stable version
2019-06-11 13:31:03,764 - InstaBot - INFO - Instabot v1.2.6/0 started at 11.06.2019 13:31:
2019-06-11 13:31:03,766 - InstaBot - INFO - Trying to login as user...
2019-06-11 13:31:08,957 - InstaBot - WARNING - Something wrong with login
2019-06-11 13:31:08,958 - InstaBot - DEBUG - {"message": "checkpoint_required", "checkpoint_url": "/challenge/10642887005/q9Q3eHvIPA/", "lock": false, "status": "fail"}
2019-06-11 13:31:08,958 - InstaBot - ERROR - "name='csrftoken', domain=None, path=None"
Traceback (most recent call last):
  File "C:\Users\construcman\Desktop\instabot.py-master\instabot_py\instabot.py", line 332, in login
    self.csrftoken = login.cookies["csrftoken"]
  File "C:\Python37-32\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Python37-32\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
2019-06-11 13:31:08,959 - InstaBot - INFO - Challenge required at https://instagram.com/challenge/10642887005/q9Q3eHvIPA/
Challenge Required.

Enter the code sent to your mail/phone: 048362
2019-06-11 13:31:36,454 - InstaBot - INFO - Entered code is wrong, Try again later!
2019-06-11 13:31:36,458 - InstaBot - INFO - Exit Program... GoodBye


I've also tried to log into instagram and mark the "it was me" option with no success.
```

#### Config

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from instabot_py import InstaBot

bot = InstaBot(
    login="",  # Enter username (lowercase). Do not enter email!
    password="",
    like_per_day=1000,
    comments_per_day=80,
    tag_list=['reforma', 'reformas','vivienda', 'mudanza', 'calor', 'aireacondicionado', 'madrid', 'españa', 'verano'],
    tag_blacklist=['porn', 'sex', 'porno'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60 * 60,
    unfollow_per_day=150,
    unlike_per_day=0,
    unfollow_recent_feed=True,
    # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
    time_till_unlike=3 * 24 * 60 * 60,  # 3 days
    unfollow_break_min=15,
    unfollow_break_max=30,
    user_max_follow=0,
    # session_file=False, # Set to False to disable persistent session, or specify custom session_file (ie ='myusername.session')
    user_min_follow=0,
    log_mod=0,
    proxy="",
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["Hey", "Que", "Wow", ":)", "Vaya!", "Genial!"],
                  ["nos", "me"],
                  ["encanta", "maravilla", "fascina"],
                  ["esta foto", "esta fotografía", "esta imagen", "este post", "esta publicación", "tu reflexión",
                   "tus ideas", "tu creatividad", "tu talento","tu perfil", "tu estilo",
                   "tu estilazo", "esto", "el texto"],
                  [".", "!", "!!", "!!!" ":)" ":D"]],
    # Use unwanted_username_list to block usernames containing a string
    # Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    # 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
       'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'gratis', 'graphy', 'indo', 'travel', 'insta', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags',
    ],
    unfollow_whitelist=[])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

```

**Comment by eduardoegos** [comment]
i'm having the exact same issue, it says the number is wrong even though it is correct, and clicking the "it was me" button in the app doesn't solve it either

**Comment by bleuys** [comment]
it's the same here

**Comment by eduardoegos** [comment]
Just an update,it worked the day after with a new code, i clicked the "it was me" thing first, then typed the code, not sure if that is necessary or if just waiting for a day does the trick, but it worked for me

**Comment by LolaReilly** [comment]
Ok, I waited for a day, ran the bot, clicked the "it was me" and then used the code. I got this error

2019-06-12 11:59:10,255 - InstaBot - INFO - You are running the latest stable version
2019-06-12 11:59:10,256 - InstaBot - INFO - Instabot v1.2.6/0 started at 12.06.2019 11:59:
2019-06-12 11:59:10,256 - InstaBot - INFO - Trying to login as homeppy__es...
2019-06-12 11:59:15,691 - InstaBot - WARNING - Something wrong with login
2019-06-12 11:59:15,692 - InstaBot - DEBUG - {"message": "checkpoint_required", "checkpoint_url": "/challenge/1790379786/oGqW8SvHLc/", "lock": false, "status": "fail"}
2019-06-12 11:59:15,692 - InstaBot - ERROR - "name='csrftoken', domain=None, path=None"
Traceback (most recent call last):
  File "C:\Users\construcman\Desktop\instabot.py-master\instabot_py\instabot.py", line 332, in login
    self.csrftoken = login.cookies["csrftoken"]
  File "C:\Python37-32\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Python37-32\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"
2019-06-12 11:59:15,731 - InstaBot - INFO - Challenge required at https://instagram.com/challenge/1790379786/oGqW8SvHLc/
Challenge Required.

Enter the code sent to your mail/phone: 074912
2019-06-12 12:01:13,017 - InstaBot - DEBUG - Login failed, response:

{"message": "checkpoint_required", "checkpoint_url": "/challenge/1790379786/oGqW8SvHLc/", "lock": false, "status": "fail"} "name='csrftoken', domain=None, path=None"


So I guess that clicking the "it was me" option before using the code, the bot works, but mine has some problem...

**Comment by apiatto** [comment]
I still can't log in.. even of I clicked the "it was me" thing first, then typed the code.
Any suggestions?

**Comment by yankerssnh** [comment]
Same problem

**Comment by ByBilal** [comment]
when  u were trying to login, did you get an error? I  did t he  config, setup properly but could not login, is it because 2-factor?

**Comment by Skiid** [comment]
I have exactly the same problem.

**Comment by gnucho** [comment]
Same problem here, have turned off the 2 way verification. 

But then i get the following measseage "Enter the code sent to your mail/phone:" and entered the 6-digit code from the SMS sent to my cellphone and the following happends.

InstaBot - INFO - Entered code is wrong, Try again later!

InstaBot - INFO - Exit Program... GoodBye

Any solution for this issue?

**Comment by pristis** [comment]
I have the same issue and I can't login. Tells me the code is wrong, but the code is correct. Any solution?

**Comment by remyx11** [comment]
I've got this problem as well. I've tried the "incognito method" but somehow I can't even login in via the browser the normal way. It just refreshes the page without login in. No error, nothing. But when I clear my cookies Instagram comes up with "want to login in as .." and it works like normal again. Very strange.

**Comment by Baatun** [comment]
This worked for me:
1. disconnect from your current wifi
2. make hotspot on your phone from cellular data and connect your device to it
3. run instabot.by and wait for the script to do a few likes and comments
4. stop the script and reconnect to your previous network
I hope that it will solve your problem too :)

**Comment by remyx11** [comment]
Thinking outside the box, I like it! And it worked. Thanks man.

**Comment by gnucho** [comment]
Thanks, it worked for me as well.

**Comment by husligc** [comment]
> This worked for me:
> 
> 1. disconnect from your current wifi
> 2. make hotspot on your phone from cellular data and connect your device to it
> 3. run instabot.by and wait for the script to do a few likes and comments
> 4. stop the script and reconnect to your previous network

This still isn't working for me.  When i switch back to my normal wifi, challenge login again... 

Any ideas fellas?

**Comment by mmgteixeira** [comment]
> This worked for me:
> 
> 1. disconnect from your current wifi
> 2. make hotspot on your phone from cellular data and connect your device to it
> 3. run instabot.by and wait for the script to do a few likes and comments
> 4. stop the script and reconnect to your previous network

Also tried that and still not working.

**Comment by keshamin** [comment]
Guys, I found a reason! 
I inspected what my browser requests and responds when doing challenge manually. There's a page where Instagram asks where to send a verification code - email, phone, etc...
As a reply this page expects a POST request with a user choice. In **Instabot** this choice is hardcoded with value **1** (see the code snippet below), but in my case Instagram expected to get **0**.

_instabot.py, line 383_
```
 # Ask for option 1 from challenge, which is usually Email or Phone
challenge_post = {"choice": 1}

# Update headers for challenge submit page
clg.headers.update({"X-CSRFToken": challenge_csrf_token})
clg.headers.update({"Referer": challenge_url})

# Request instagram to send a code
challenge_request_code = clg.post(
challenge_url, data=challenge_post, allow_redirects=True
)
```

So in my case changing `challenge_post = {"choice": 1}` to `challenge_post = {"choice": 0}` in source code makes it work. 
I'm not an expert in Instagram authorization system, but it seems like this value **should not be hardcoded.**

**Comment by husligc** [comment]
> Guys, I found a reason!
> I inspected what my browser requests and responds when doing challenge manually. There's a page where Instagram asks where to send a verification code - email, phone, etc...
> <img alt="Снимок экрана 2019-07-14 в 17 47 12" width="890" src="https://user-images.githubusercontent.com/25623173/61185256-d78da900-a65f-11e9-9128-d5c79d3803e0.png">
> 
> As a reply this page expects a POST request with a user choice. In **Instabot** this choice is hardcoded with value **1** (see the code snippet below), but in my case Instagram expected to get **0**.
> 
> ![image](https://user-images.githubusercontent.com/25623173/61185285-2c312400-a660-11e9-8e35-344d6efbfd58.png)
> 
> _instabot.py, line 383_
> 
> ```
>  # Ask for option 1 from challenge, which is usually Email or Phone
> challenge_post = {"choice": 1}
> 
> # Update headers for challenge submit page
> clg.headers.update({"X-CSRFToken": challenge_csrf_token})
> clg.headers.update({"Referer": challenge_url})
> 
> # Request instagram to send a code
> challenge_request_code = clg.post(
> challenge_url, data=challenge_post, allow_redirects=True
> )
> ```
> 
> So in my case changing `challenge_post = {"choice": 1}` to `challenge_post = {"choice": 0}` in source code makes it work.
> I'm not an expert in Instagram authorization system, but it seems like this value **should not be hardcoded.**

This didn't work for me... any ideas? code isn't sending

**Comment by macd2** [comment]
the problem is:
```complete_challenge = clg.post(
                            challenge_url,
                            data=challenge_security_post,
                            allow_redirects=True,
                        )````

`challenge_url` does not change and redirects to the challenge choice page

**Comment by yurilaaziz** [comment]
Thank you guys for the detail, I will add a prompt to ask the user if it's received by email or sms

**Comment by macd2** [comment]
@yurilaaziz and what should that prompt be good for? 
The issue is the wrong URL `challenge_url`  which does not change from choice of challenge and enter code, since the "enter code" form is handles via javascript....

**Comment by MassimoCastell** [comment]
It seems the @macd2 is right. I get the prompt, but the code is not accepted.

**Comment by PranavSanghvi** [comment]
Has anyone found a solution?

**Comment by ByBilal** [comment]
> > Guys, I found a reason!
> > I inspected what my browser requests and responds when doing challenge manually. There's a page where Instagram asks where to send a verification code - email, phone, etc...
> > <img alt="Снимок экрана 2019-07-14 в 17 47 12" width="890" src="https://user-images.githubusercontent.com/25623173/61185256-d78da900-a65f-11e9-9128-d5c79d3803e0.png">
> > As a reply this page expects a POST request with a user choice. In **Instabot** this choice is hardcoded with value **1** (see the code snippet below), but in my case Instagram expected to get **0**.
> > ![image](https://user-images.githubusercontent.com/25623173/61185285-2c312400-a660-11e9-8e35-344d6efbfd58.png)
> > _instabot.py, line 383_
> > ```
> >  # Ask for option 1 from challenge, which is usually Email or Phone
> > challenge_post = {"choice": 1}
> > 
> > # Update headers for challenge submit page
> > clg.headers.update({"X-CSRFToken": challenge_csrf_token})
> > clg.headers.update({"Referer": challenge_url})
> > 
> > # Request instagram to send a code
> > challenge_request_code = clg.post(
> > challenge_url, data=challenge_post, allow_redirects=True
> > )
> > ```
> > 
> > 
> > So in my case changing `challenge_post = {"choice": 1}` to `challenge_post = {"choice": 0}` in source code makes it work.
> > I'm not an expert in Instagram authorization system, but it seems like this value **should not be hardcoded.**
> 
> This didn't work for me... any ideas? code isn't sending

@husligc what file in the  package is that 0 value in so I can change it to 1? Great find.

**Comment by PranavSanghvi** [comment]
> > > Guys, I found a reason!
> > > I inspected what my browser requests and responds when doing challenge manually. There's a page where Instagram asks where to send a verification code - email, phone, etc...
> > > <img alt="Снимок экрана 2019-07-14 в 17 47 12" width="890" src="https://user-images.githubusercontent.com/25623173/61185256-d78da900-a65f-11e9-9128-d5c79d3803e0.png">
> > > As a reply this page expects a POST request with a user choice. In **Instabot** this choice is hardcoded with value **1** (see the code snippet below), but in my case Instagram expected to get **0**.
> > > ![image](https://user-images.githubusercontent.com/25623173/61185285-2c312400-a660-11e9-8e35-344d6efbfd58.png)
> > > _instabot.py, line 383_
> > > ```
> > >  # Ask for option 1 from challenge, which is usually Email or Phone
> > > challenge_post = {"choice": 1}
> > > 
> > > # Update headers for challenge submit page
> > > clg.headers.update({"X-CSRFToken": challenge_csrf_token})
> > > clg.headers.update({"Referer": challenge_url})
> > > 
> > > # Request instagram to send a code
> > > challenge_request_code = clg.post(
> > > challenge_url, data=challenge_post, allow_redirects=True
> > > )
> > > ```
> > > 
> > > 
> > > So in my case changing `challenge_post = {"choice": 1}` to `challenge_post = {"choice": 0}` in source code makes it work.
> > > I'm not an expert in Instagram authorization system, but it seems like this value **should not be hardcoded.**
> > 
> > 
> > This didn't work for me... any ideas? code isn't sending
> 
> @husligc what file in the package is that 0 value in so I can change it to 1? Great find.

Husligc changed the value from 1 to 0. The value is in the file instabot.py

However, this did not work for me. Please let me know if it works for you!

**Comment by Venomz33** [comment]
@yurilaaziz Hi, you replied 12 days ago, did you add the choose option by chance?

**Comment by MassimoCastell** [comment]
Still not working for me.

**Comment by Andy2903** [comment]
I'm having the Same issue, but changing the value from 1 to 0 didn't work

**Comment by nickgryg** [comment]
This is very outdated issue. If you still have it, please try to use instabot-py version 0.5.20 or later.
