### ISSUE TITLE
Database for each bot not created

### ISSUE THREAD

**Issue by MrRobotoGit** [instabot-py/instabot.py#2219]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [ x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```
Python 3.6.3
#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```
pip 19.1.1 

#### Description of your issue

I run 4 bots so I added for each username.py the string:

database_name="username.db"

and restarted the bots. After restart seem not new db are created I see only the sqlite.db.

Any idea?

```

```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by yurilaaziz** [comment]
Thank you for your interest.
It should be fixed in the next release.

but as a workaround, you may use the YAML configuration file and set a database name per user.

**Comment by MrRobotoGit** [comment]
Where can I find documentation about YAML set up?

**Comment by eduardoegos** [comment]
i have a workaround, i think. instead of writing:
database_name=<name>.db
write:
database={"type": "sql", "connection_string": "sqlite:///<name>.db"}

**Comment by eduardoegos** [comment]
i have a workaround, i think. instead of writing:
database_name=name.db
write:
database={"type": "sql", "connection_string": "sqlite:///name.db"}

**Comment by MrRobotoGit** [comment]
doesn't work

**Comment by MrRobotoGit** [comment]
> i have a workaround, i think. instead of writing:
> database_name=name.db
> write:
> database={"type": "sql", "connection_string": "sqlite:///name.db"}

doesn't work

**Comment by yurilaaziz** [comment]
last changes should fix this issue 
please download the last version
