### ISSUE TITLE
I cannot make it work

### ISSUE THREAD

**Issue by raheem429** [instabot-py/instabot.py#222]
Hey all, 

First of all many thanks for sharing this genius bot, but as I'm very new to the whole coding thing, I couldn't make it run, yet. 
I followed all steps, but when I run example.py I get this message as below:

  File "/Users/RahJah/Downloads/instabot.py-master/instabot.py", line 156, in **init**
    self.login()
  File "/Users/RahJah/Downloads/instabot.py-master/instabot.py", line 195, in login
    r = self.s.get(self.url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, *_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, *_send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x102570950>: Failed to establish a new connection: [Errno 65] No route to host',))

**Comment by ArgonQQ** [comment]
To debug this share your configuration file with us. This could help a lot!

Verify you're not sharing personal stuff.

**Comment by raheem429** [comment]
Thanks for coming back to me.
I just used the example.py from here and changed the login and pw. Or what exactly do you mean by configuration file?

**Comment by raheem429** [comment]
New but different error message:

Traceback (most recent call last):
  File "example.py", line 18, in <module>
    log_mod=0)
  File "/Users/Downloads/instabot.py-master/instabot.py", line 157, in __init__
    self.populate_user_blacklist()
  File "/Users/Downloads/instabot.py-master/instabot.py", line 167, in populate_user_blacklist
    id_user = all_data['user']['media']['nodes'][0]['owner']['id']
IndexError: list index out of range

**Comment by bobduckling221** [comment]
@raheem429 

delete [0] in line 167
and then delete self.populate_user_blacklist() in line 157

**Comment by raheem429** [comment]
You are my hero bobduckling221 !!! It works now. 

Another stupid question: Can I close my mac now while it's processing/running?

**Comment by bobduckling221** [comment]
i am not sure.... You can try, but you risk shutting the program down at the same time @raheem429

**Comment by virginsince1997** [comment]
@raheem429,  keep your screen display active, to continue to run it.

**Comment by raheem429** [comment]
@virginsince1997 @bobduckling221 thanks a lot guys, but I'm in a coffee shop and want to leave soon :D 

Well, need to restart the whole thing again once at home I reckon? And get rid of my screen saver

**Comment by drewhga** [comment]
You should explore other reliable execution options like online script hosting services.

@raheem429

**Comment by virginsince1997** [comment]
@drewhga can you suggest one?

**Comment by kemong** [comment]
hi @raheem429  you need your own VPS (Virtual Private Server) to keep your bot running
But for cheaper option you can buy cheap android tablet/ phone. Root the android, run linux (Debian) via linux deploy and you start your bot on the android. It's more cheap option based on initial cost and power consumption. I've done that and manage 10 clients who pay me $2 per 3 days of service, and they even don't know what is bot, what is python, they just want their instagram account "keep active" whole day 24/7. and what i really do is just that, plug charger on my android, and launch the bash script to trigger the python script.

**Comment by raheem429** [comment]
@kemong I'm on the metro now, so a very quick thank you! I really do appreciate your explanation and sharing your insights with me. Imo it all seems very doable I must say! Merci

**Comment by bobduckling221** [comment]
how do you advertise automation marketing? @kemong

**Comment by kemong** [comment]
It's a growing market, especially in my country. Being the top most country which searching keyword "Instagram Bot". 
![instabottrend](https://cloud.githubusercontent.com/assets/22748697/19306720/2eea336c-90a1-11e6-8fb3-82b1bffe4896.png)
![instagrambot2](https://cloud.githubusercontent.com/assets/22748697/19306721/2eee9808-90a1-11e6-9617-4e96a99c6678.png)
![instagrambot3](https://cloud.githubusercontent.com/assets/22748697/19306722/2ef3182e-90a1-11e6-99db-c8319eee2ec4.png)

**Comment by Bossishere** [comment]
@kemong are you interested in selling some?

**Comment by LevPasha** [comment]
@kemong Businessman! I want part of your profits! )))

**Comment by kemong** [comment]
@LevPasha i already give the code which i use back to the community. For the profits i'll considering donation. It's just hard to make an anonymous transaction to other country here. I'll figure it out. Credit Cards are uncommon and hard to get in my country.

**Comment by LevPasha** [comment]
@kemong this is joke! ))

**Comment by raheem429** [comment]
Hey guys, 

Again I'm very thankful for all your help. I will probably go for the cheap smartphone solution. However, today I realised that after 18 hours it logged me out (mac was plugged in and just screen was turned off - it worked during the whole night like that) but the bot didn't do any un/following.

**Comment by drewhga** [comment]
I'd advise you not to go for the smartphone option but use the money to be
spent in purchasing the phones to purchase runtime on services like Heroku
which will keep your app running all day

**Comment by raheem429** [comment]
@drewhga What other services could you recommend? Also Amazon for instance?

**Comment by raheem429** [comment]
And does anyone have an idea why the bot is not following any other profiles?

**Comment by virginsince1997** [comment]
Lol @kemong he was joking...

**Comment by drewhga** [comment]
You can also try Python Anywhere

**Comment by virginsince1997** [comment]
thank you

**Comment by raheem429** [comment]
Thanks a lot @drewhga 

But as mentioned earlier the bot is only liking but not following anyone. What am I doing wrong?

instabot.py-master/example.py'  && echo Exit status: $? && exit 1
Instabot v1.0.1 started at 13.10.2016 17:35:

Trying to login as xxxxxxx...

xxxxxxxx login success!
Get media id by tag: cars
Trying to like media: 1360267318110580464
Liked: 1360267318110580464. Like #1.

---

#!/usr/bin/env python
# -*- coding: utf-8 -*-

from instabot import InstaBot

bot = InstaBot(login="xxxx", password="xxxx",
               like_per_day=1000,
               comments_per_day=0,
               tag_list=['xxx', 'xxx', 'xxx'],
               tag_blacklist=['rain', 'thunderstorm'],
               user_blacklist={'hellokitty':'', 'hellokitty3':''},
               max_like_for_one_tag=50,
               follow_per_day=125,
               follow_time=5*60*60,
               unfollow_per_day=125,
               unfollow_break_min=15,
               unfollow_break_max=30,
               log_mod=0)

bot.auto_mod()

**Comment by drewhga** [comment]
The bot performs actions spread over 24 hours.
So 125 a day will probably be performed unnoticeably. So it does follow
just that not frequently. Increasing the follows per day to 1000 should help

**Comment by raheem429** [comment]
@drewhga Thanks again, but does is it not shown in Terminal?

I'm still seeing the bot's liking:

Trying to like media: 1360606762344900862
Liked: 1360606762344900862. Like #1070.
Trying to like media: 1360606760112644839
Liked: 1360606760112644839. Like #1071.
Trying to like media: 1360606749359123652
Liked: 1360606749359123652. Like #1072.
Trying to like media: 1360606604110386980
Liked: 1360606604110386980. Like #1073.
Trying to like media: 1360606594672844148
Liked: 1360606594672844148. Like #1074.
Trying to like media: 1360606479925105105
Liked: 1360606479925105105. Like #1075.
Trying to like media: 1360606389520726472
Liked: 1360606389520726472. Like #1076.

**Comment by drewhga** [comment]
How many follows have you set. Per day?

**Comment by raheem429** [comment]
150 @drewhga

**Comment by drewhga** [comment]
As I said,  150 won't produce a noticeable effect, try setting it to 1000
and restart the app

**Comment by virginsince1997** [comment]
Haha 1079 likes!!

**Comment by raheem429** [comment]
1000 follows and 1000 likes a day?

**Comment by drewhga** [comment]
Not necessarily, I just want you to set it to 1000 so the follow log will
be conspicuous instead of being lost in a stream of likes

**Comment by Bossishere** [comment]
my bot isnt working a long time why?
Just 1 hour max and then 
 raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by drewhga** [comment]
I think this occurs when the bot encounters an account with either 0
following or 0 followers it then crashes since it can't work with 0 so you
should try handling the exception so the bot skips these accounts.

For example

except JSONDecodeError:
            print " Zero Account Error n/ Restarting Bot)
            unfollow_protocol(bot)

**Comment by welaunch** [comment]
Hello - having problems running the .py file. Even if I just run the example copy I'm served up the following messages?

Users-iMac:~ myname$ cd '/Users/myname/Downloads/instabot.py-master/src/' && '/usr/bin/pythonw'  '/Users/myname/Downloads/instabot.py-master/src/example.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/myname/Downloads/instabot.py-master/src/example.py", line 12, in <module>
    from instabot import InstaBot
  File "/Users/myname/Downloads/instabot.py-master/src/instabot.py", line 16, in <module>
    import requests
ImportError: No module named requests
Users-iMac:src myname$

**Comment by kemong** [comment]
You have to install module named requests

pip install requests

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
