### ISSUE TITLE
Bot isn't unfollowing people

### ISSUE THREAD

**Issue by ShubhamPandeyy** [instabot-py/instabot.py#2228]
Bot isn't unfollowing users automatically and I have to do this manually.
Here is my script:
-
    like_per_day=1700,
    comments_per_day=0,
    tag_list=["l:292101274556108", "bffs", "bhaii", "bhai_bhai", "msti", "schoolfrnds", "frnds", "mahol", "after_exams", "pagal",  "schoolmemories", "fullmasti", "mstii", "fullonmasti", "l:236996402", "l:238547784"],
    tag_blacklist=["rain", "thunderstorm"],
    user_blacklist={},
    max_like_for_one_tag=110,
    follow_per_day=500,
    follow_time=1 * 60 * 60,
    unfollow_per_day=500,
    unlike_per_day=0,
    # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
    time_till_unlike=3 * 24 * 60 * 60,  # 3 days
    unfollow_break_min=30,
    unfollow_break_max=40,
    user_max_follow=800,
    # session_file=False, # Set to False to disable persistent session, or specify custom session_file (ie ='myusername.session')
    user_min_follow=50,
    log_mod=0,

**Comment by Brcalvo** [comment]
The same here. I'm getting the message "Looks like there is nobody to unfollow"

**Comment by Brcalvo** [comment]
The same here, I´m getting the message "Looks like there is nobody to unfollow"

**Comment by diogojesus95** [comment]
Having the same problem

**Comment by nickgryg** [comment]
This is definitely fixed in instabot-py after version 0.5.13. Just install it from PyPi, performing:
``` 
python3 -m pip install instabot-py
```
