### ISSUE TITLE
Issue running example.py suddenly. Worked for a month and then suddenly had an error.

### ISSUE THREAD

**Issue by tectonapparel** [instabot-py/instabot.py#2236]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS
- [x] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.3
```

#### Pip Version?
```
pip 19.0.3
```

#### Description of your issue

```
2019-06-21 16:26:09,857 - InstaBot - INFO - Saving cookies to session file tectonapparel.session
Traceback (most recent call last):
  File "example.py", line 42, in <module>
    unfollow_whitelist=["example_user_1", "example_user_2"],
  File "C:\Users\avsom\Downloads\instabot.py-master\instabot_py\instabot.py", line 211, in __init__
    self.populate_user_blacklist()
  File "C:\Users\avsom\Downloads\instabot.py-master\instabot_py\instabot.py", line 271, in populate_user_blacklist
    self.user_blacklist[user] = id_user
TypeError: 'set' object does not support item assignment
```

#### Config

```
database:
  type: sql
  connection_string: sqlite:///username.db

debug: 0
follow_time: 604800

like_per_day: 1000
comments_per_day: 500
max_like_for_one_tag: 50
follow_per_day: 0
follow_time: 0
unfollow_per_day: 0
unfollow_break_min: 0
unfollow_break_max: 0
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false
```

**Comment by nikolasvargas** [comment]
hello :)

make sure you are not entering only a string in the user_blacklist dict.

`user_blacklist = {'username'}` **# that's will create a set (immutable (wrong use))**
`user_blacklist = {'username': None}` **works fine**

**Comment by nikolasvargas** [comment]
> Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
> 
> * [x ] I have searched for other issues with the same problem or similar feature requests.
> 
> #### Select one:
> * [ ]  Bug
> * [ ]  Feature Request
> * [x]  Technical Help
> * [ ]  Other
> 
> #### Environment
> * [ ]  Are you hosting the bot on a VPS or other Cloud hosting?
> * [x]  If so, have you tried running the code on your local machine?
> 
> #### Operating System? (include version)
> * [x]  macOS
> * [x]  Windows
> * [ ]  Linux (include flavour)
> * [ ]  Android (include terminal)
> 
> #### Python Version Requirement
> * [x]  I am using Python 3.6 or above
> 
> #### Exact Python Version?
> ```
> Python 3.7.3
> ```
> 
> #### Pip Version?
> ```
> pip 19.0.3
> ```
> 
> #### Description of your issue
> ```
> 2019-06-21 16:26:09,857 - InstaBot - INFO - Saving cookies to session file tectonapparel.session
> Traceback (most recent call last):
>   File "example.py", line 42, in <module>
>     unfollow_whitelist=["example_user_1", "example_user_2"],
>   File "C:\Users\avsom\Downloads\instabot.py-master\instabot_py\instabot.py", line 211, in __init__
>     self.populate_user_blacklist()
>   File "C:\Users\avsom\Downloads\instabot.py-master\instabot_py\instabot.py", line 271, in populate_user_blacklist
>     self.user_blacklist[user] = id_user
> TypeError: 'set' object does not support item assignment
> ```
> 
> #### Config
> ```
> database:
>   type: sql
>   connection_string: sqlite:///username.db
> 
> debug: 0
> follow_time: 604800
> 
> like_per_day: 1000
> comments_per_day: 500
> max_like_for_one_tag: 50
> follow_per_day: 0
> follow_time: 0
> unfollow_per_day: 0
> unfollow_break_min: 0
> unfollow_break_max: 0
> unfollow_selebgram: false
> unfollow_probably_fake: true
> unfollow_inactive: true
> unfollow_recent_feed: false
> ```
hello :)

make sure you are not entering only a string in the user_blacklist dict.

user_blacklist = {'username'} # that's will create a set (immutable (wrong use))
user_blacklist = {'username': None} works fine
