### ISSUE TITLE
Instabot is detected by Instagram algorithm

### ISSUE THREAD

**Issue by nativecodeabuser** [instabot-py/instabot.py#2247]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [X] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [X] Linux Debian
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

---

Not really a code related issue, rather a warning for users.

I use a moderate setting of 400 likes per day, no comments, no follows.

Recently Instagram showed this popup (I already got it twice):

_

> “We’re removing Inauthentic Likes and Follows. It looks like you may have shared your username and password with an app offering followers or likes. We’re removing activity like new followers from these apps to protect our community from inauthentic activity. Change your password to stop them from accessing your account."

_

After the first time I tried changing the user agent for one matching my desktop browser. Also I run the script on the machine in my home network so the public IP is the same for Instabot and my desktop and mobile devices. Still got the second one.

We might need to investigate how they determine if actions are automated. Otherwise we might see some accounts banned...

**Comment by eduardoegos** [comment]
i've read somewhere, i think it was in another issue around here,  that instagram is now allowing only 6000 iterations a month, if you are doing 400 likes a day, that is 12000 likes a month, so maybe that is the problem?

**Comment by bleshik** [comment]
Not sure, but it might be related to this issue as well: https://github.com/instabot-py/instabot.py/issues/2250

Instagram's anti-bot team is coming for us :(

**Comment by nativecodeabuser** [comment]
> i've read somewhere, i think it was in another issue around here, that instagram is now allowing only 6000 iterations a month, if you are doing 400 likes a day, that is 12000 likes a month, so maybe that is the problem?

The 6000/month limit is for follows, not post likes.

**Comment by marcelofox** [comment]
Did anyone check this information about 6000 follow/month? Or it's just speculation?

**Comment by eduardoegos** [comment]
i cannot find the source were i've read it, so i cannot guarantee it, but the new limit would be 6000 iterations, that is a sum of likes, dislikes, comments, follows and unfollows, which limits the bot by quite a lot, doesn't seem very reasonable, even without a bot, 6000 is very little, it must be wrong. nevertheless i've reduced my follows to about 20 a day until i can verify it

**Comment by murlikanne** [comment]
So Facebook recently sued a company for giving out fake likes and fake follows. They're removing likes and followers users have bought from services like these ones. I'm not sure about iteration limitations but I don't think facebook will limit interactions on Instagram! I mean, it's just a bad idea. Only a portion of IG userbase knows about automations.

**Comment by nativecodeabuser** [comment]
Restrictions are getting tighter, it seems...

200 likes/day, no comments, no follows. Result:

2019-07-01 09:36:22,484 - InstaBot - INFO - Not liked: 400 message {"message": "feedback_required", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/instagram_like_add/", "status": "fail"}

**Comment by urbels** [comment]
I received same message. First at 2019-07-01 19:22:31 GMT+2

**Comment by nativecodeabuser** [comment]
Does it even still work for anyone? After a week without launching still...

`2019-07-09 10:19:37,728 - InstaBot - INFO - Not liked: 400 message {"message": "feedback_required", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/instagram_like_add/", "status": "fail"}`

It works fine on my mobile so it is not the account that was limited...

**Comment by tombraider74** [comment]
no, does still not work anymore

**Comment by bayilyas** [comment]
Deleting {username}.session file solved the issue

**Comment by bayilyas** [comment]
Emptying {username}.session file solved the issue.

**Comment by Bout2GitIt** [comment]
How do you empty {uusername}.session file? Sorry, I am new to Ubuntu 14

**Comment by Wolfofcryptos** [comment]
> How do you empty {uusername}.session file? Sorry, I am new to Ubuntu 14

BRO:
$. sudo rm -r (username).session

EASY

**Comment by Wolfofcryptos** [comment]
im trying to solve this keeping a longer break between every like, follow, coment. i need a week to be sure, wair for my reply nice day.

ALWAYS REMEMBER DELETE THE USERNAME.SESSION AND CHANGE THE PASSWORD BEFORE TO TRY ANYTHING.
