### ISSUE TITLE
The new kind of 400 error

### ISSUE THREAD

**Issue by bleshik** [instabot-py/instabot.py#2250]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux Ubuntu
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.3
```

#### Pip Version?
```
pip 19.0.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
```

#### Description of your issue

Hi everyone,
Around a week ago I've started getting unusual 400 errors. Unlike, the 400 errors I had previously, these differ in the following aspects:
1) It does not block the whole account, just the bot's session. Meaning, I still can put likes from my phone with no problems.
2) It does not specify date when the block will expire.
3) It seems like it never expires. Previously, a sleep for 24 hours helped, but not with this one.
4) Re-login helps, because it does not block the whole account, just the current session.

```
{
    "message": "feedback_required",
    "spam": true,
    "feedback_title": "Action Blocked",
    "feedback_message": "This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.",
    "feedback_url": "repute/report_problem/instagram_like_add/",
    "status": "fail"
}
```

**Comment by bleshik** [comment]
More info on this: https://github.com/instagrambot/instabot/issues/926

**Comment by hakey1408** [comment]
Hi, i'm facing this problem too!
Here is the log of the error:
`Not liked: 400 message {"message": "feedback_required", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/instagram_like_add/", "status": "fail"}`

It is the first time that this kind of error shows up, I'm running the bot on AWS.
Is there any workaround for this problem? I tried changing the instance IP and the header's user agent but the bot still get blocked after a few minutes.
On the other end using the app everything works fine.

**Comment by mrallanodreman** [comment]
Disculpen que hable en español, pero si  yo logro comprenderlos en ingles se bien que encontraran la forma de traducir esto, AMO INSTABOT y pretendo ser parte de la comunidad que ayude a crecer esto

por eso el siguiente comentario:

Sobre el error 404: creo que la mejor manera de evitar el ban o cualquier tipo de alerta roja es simplemente agregando el factor humano a nuestra ecuacion, suelo encender y apagar los bots sobre una misma comunidad, mis cuentas nunca tienen un comportamiento lineal, los enciendo durante unas 7 horas (horas laborables humanas) , dentro de esas 7 horas inicio con cantidades pequeñas durante la mañana y voy subiendo... todo esto sin un plan exacto. solo una linea de intencion  , solo el conteindo tiene una agenda, pero no la interaccion, por lo cual yo uso cantidades como "cantidad de likes por dia = 3500 " sin tener un ban o una alerta

ellos estan mejorando su algoritmo para encontrar "bots", pues que nuestros "bots" sean lo mas humanos posible... siempre estaremos ahorrando muchas hroas de trabajo manual...  aun hay mucho trabajo por hacer!

**Comment by mrallanodreman** [comment]
im getting this error, but no alert on the app of Instagram!
only in the cmd console!

pd: WTF!?

**Comment by Rick1998** [comment]
Same Issue here!!

**Comment by farbraum** [comment]
Any Ideas? I've updatet the User-Agent list --> same situation :-(

**Comment by Rick1998** [comment]
Hey guys I seem to figure it out. Since I use vpn，after changed my vpn to another route/location，it starts working. I also changed my password. hope that helps. seems like Instagram banned my ip address

**Comment by farbraum** [comment]
> Hey guys I seem to figure it out. Since I use vpn，after changed my vpn to another route/location，it starts working. I also changed my password. hope that helps. seems like Instagram banned my ip address

I've tried this, but doesen't work for all accounts... what is to do?

**Comment by farbraum** [comment]
Now it works...

**Comment by bleshik** [comment]
it's an AI detecting bots, so I think there are no strict rules

**Comment by farbraum** [comment]
I think so too!

**Comment by farbraum** [comment]
I dont know what to do! I have to change my passwort twise a day. I have deleted some keywords and only ask for 350 likes a day. what shall I do?

**Comment by AKwoKWH** [comment]
> Hey guys I seem to figure it out. Since I use vpn，after changed my vpn to another route/location，it starts working. I also changed my password. hope that helps. seems like Instagram banned my ip address

@Rick1998 
I have changed my IP address, but being blocked again in 1 day
I only liked less then 100 pic

**Comment by mrallanodreman** [comment]
> I dont know what to do! I have to change my passwort twise a day. I have deleted some keywords and only ask for 350 likes a day. what shall I do?

350 per day on this momento is to much!

Im working fine under the 200 likes

**Comment by waynoedm** [comment]
I haven't been able to do a single like and it's already identifying me.

**Comment by keithgmitchell** [comment]
Remove 'username'.session file that is created and stores cookies. Seemed to work for me along with VPN.
