### ISSUE TITLE
Always uses sqlite.db

### ISSUE THREAD

**Issue by smoki3** [instabot-py/instabot.py#2253]
Hi,

I noticed that the bot is now using a file sqlite.db insted of %username%.db

So if I use different session on one computer the share the db which is not working

**Comment by smoki3** [comment]
the problem is that the variable database_name has no function.

i added
database= {"type": "sql", "connection_string": "sqlite:///mydatabase.db"},

to my config now it seems to work

**Comment by Mystrious123** [comment]
Where do i add that line of code?

**Comment by smoki3** [comment]
https://github.com/instabot-py/instabot.py/commit/30f542faa298b11550bfc179ccca89e1cec6b3b5

A fix is already merged. Update to latest version
