### ISSUE TITLE
Bot stops automatically in 5-10 minutes for no reason.

### ISSUE THREAD

**Issue by murlikanne** [instabot-py/instabot.py#2254]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
Include the contents of the error.log here (if applicable). 

I've recently started facing this problem with the previous version and updated to the latest version of Instabot! The bot works fine for 5-10 minutes and gets stuck. I'm only running one bot at the moment. 

Any help is appreciated.

#### Config

```
Include the contents of your config here 

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from instabot_py import InstaBot

bot = InstaBot(
   =

    like_per_day=600,
    comments_per_day=0,
    tag_list=['poetry_addicts','poetryporn','instagrampoetry','bleedink','wordporn','poetrytribe',
              'poetslife','poetrydaily','poemporn','worldofpoets','poetsoftheworld','communityofwriters','writerssociety',
              'wordsofig','writersuniverse','writingcommunity','writingsociety',
              'igpoems','typewriterpoetry','poetslife','menwhowrite','poetryisart','rupikaur','milkandhoney',
                'spilledink','womenwhowrite','atticus',
              'herheartpoetry','omypoetry','poemoftheday','lovepoetry','spokenwordpoetry',
              'lovepoem','instapoem','igpoem','lovepoems','blackoutpoem',
                'wordswithqueens','wordswithkings','prose',
              'poetrycommunity', 'poet', 'poetry','poetryinmotion','poetsofinstagram','writersofinstagram',
              'writerscommunity','poetrysociety','poetrycommunityofinstagram','poetryporn',
              'poetryisnotdead','poetrygram','poetrylove','poetrylovers','poetryslam','poetryislife',
              'poetrybook','poetryhive','instapoetry','micropoetry','typewriterpoetry','lovepoetry',
              'sadpoetry','spokenwordpoetry','instagrampoetry',
              'blackoutpoetry','writersofig','writersblock','writerscorner',
              'instawriter','writersofinsta','writersnetwork','bymepoetry','herheartpoetry',
              'omypoetry','artlixirpoetry','poetryclub','globalpoetcult',
              'poetry_addicts','poemsofinsta','poetryporn','instagrampoetry','spilledink','tumblr','poetrytribe','poetry','poetryporn',
              'poetslife','poetrydaily','poemporn','worldofpoets','poetsoftheworld','communityofwriters','writerssociety','atticuspoetry'
              'mirakeeapp','wordsofig','writersuniverse','writingcommunity','writingsociety','writersworld','madewords','instaquote',
              'igpoems','writtenword','typewriterpoetry','sayingsandquotes','menwhowrite','poetryisart',
                'spilledword','womenwhowrite','quotesaboutlife','quoteoftheday','poetryisnotdead','wordporn','writersnetwork',
                    'readersofinstagram','couplequotes', 'writersofinstagram','poetsofinstagram',
                        'lovequotes','untwineme','omypoetry','micropoetry',
              'selfpublishedauthor','poemsofinstagram','poeta','bymepoetry','poetess','spilledthoughts',
              'herheartpoetry','poetscorner','relationshipquotes','poetryclub','omypoetry','poetryoftheday',
                'bleedink','lovepoetry','spokenwordpoetry','poemoftheday',
                    'tumblrquotes','instapoem','igpoem','lovepoems','instapoetry',
                'wordswithqueens','wordswithkings','prose',],
    tag_blacklist=[],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=0,
    follow_time=1 * 60 * 60,
    unfollow_per_day=0,
    unlike_per_day=0,
    unfollow_recent_feed=True,
    # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
    time_till_unlike=3 * 24 * 60 * 60,  # 3 days
    unfollow_break_min=15,
    unfollow_break_max=30,
    user_max_follow=0,
    # session_file=False, # Set to False to disable persistent session, or specify custom session_file (ie ='myusername.session')
    user_min_follow=0,
    log_mod=0,
    proxy="",
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[
        [],
    ],
    # Use unwanted_username_list to block usernames containing a string
    # Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    # 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[],
    unfollow_whitelist=[],
    # Enable the following to schedule the bot. Uses 24H
    # end_at_h = 23, # Hour you want the bot to stop
    # end_at_m = 30, # Minute you want the bot stop, in this example 23:30
    # start_at_h = 9, # Hour you want the bot to start
    # start_at_m = 10, # Minute you want the bot to start, in this example 9:10 (am).
)

bot.mainloop()

```

**Comment by smoki3** [comment]
check your tag list:

after 'atticuspoetry' for example you miss the ,

**Comment by murlikanne** [comment]
> check your tag list:
> 
> after 'atticuspoetry' for example you miss the ,

fixed it, still the same problem! It definitely isn't the comma.

**Comment by x3l51** [comment]
It's the same for me. 

```
     ______Starting bot_____
2019-07-09 21:10:18,457 - InstaBot - INFO - Checking for updates...
2019-07-09 21:10:18,678 - InstaBot - INFO - You are running the latest stable version
2019-07-09 21:10:18,678 - InstaBot - INFO - Instabot v1.2.6/0 started at 09.07.2019 21:10:
2019-07-09 21:10:18,679 - InstaBot - INFO - Found session file NAME.session
2019-07-09 21:10:20,393 - InstaBot - INFO - NAME login success!

2019-07-09 21:10:20,393 - InstaBot - INFO - Saving cookies to session file NAME.session
2019-07-09 21:10:20,394 - InstaBot - DEBUG - Get Media by tag: arduino
2019-07-09 21:10:22,173 - InstaBot - DEBUG - Trying to like media: 2084392248067165698, https://www.instagram.com/p/BztP7S-nw4C/
2019-07-09 21:10:23,598 - InstaBot - INFO - Liked: 2084392248067165698. Like #1 https://www.instagram.com/p/BztP7S-nw4C/.
2019-07-09 21:10:28,369 - InstaBot - DEBUG - Trying to follow: 7851133387
2019-07-09 21:10:29,461 - InstaBot - INFO - Followed: https://www.instagram.com/megaelectronics99/ #1.
2019-07-09 21:10:48,497 - InstaBot - DEBUG - NAME : Get media id on recent feed
2019-07-09 21:10:49,598 - InstaBot - DEBUG - Media in recent feed = 12
2019-07-09 21:10:49,635 - InstaBot - DEBUG - Trying to unfollow #1:
2019-07-09 21:10:49,637 - InstaBot - DEBUG - Looks like there is nobody to unfollow.
2019-07-09 21:11:34,692 - InstaBot - DEBUG - Get Media by tag: maker
2019-07-09 21:12:45,089 - InstaBot - DEBUG - Get Media by tag: python
2019-07-09 21:13:54,517 - InstaBot - DEBUG - Get Media by tag: python
2019-07-09 21:14:17,747 - InstaBot - INFO - Exit Program... GoodBye

```

I'm running the latest version of the bot, python3.6 and meet all dependencies too.

**Comment by smoki3** [comment]
Its wired. Are you sure you are calling the right config?

The tag arduiono, python and maker is not in your config and the bot is looking for it so. Make sure that  you are running the right config file

**Comment by x3l51** [comment]
> Its wired. Are you sure you are calling the right config?
> 
> The tag arduiono, python and maker is not in your config and the bot is looking for it so. Make sure that you are running the right config file

@smoki3 I am a different person than the one that opened the issue. For me those tags in fact are in my config. Here's my config:

```
[NAME]
username = NAME
password = PASSWORD
like_per_day = 200
comments_per_day = 0
max_like_for_one_tag = 5000
follow_per_day = 50
follow_time = 86400
unfollow_per_day = 200
user_min_follow = 20
tag_list = ["f4f", "maker", "adafruit", "rpi", "engineering", "atmega", "raspberrypi", "arduino", "max7219", "electronics", "python", "embedded", "sensors", "makersgonnamake"]
unfollow_selebgram = True
unfollow_probably_fake = True
unfollow_inactive = True
unfollow_recent_feed = True
unfollow_not_following = True
unfollow_whitelist = []
log_mod = 0

```

**Comment by nickgryg** [comment]
This is very outdated issue. If you still have it, please try to use instabot-py version 0.5.20 or later.
