### ISSUE TITLE
[Feature Request] Interact with followers of other accounts

### ISSUE THREAD

**Issue by kaykyr** [instabot-py/instabot.py#2255]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

Hello! I am interested in developer this feature... I'll try to contribute with this, because it is the best feature to gain followers. If anyone here is working in something like this and would like to work together, please, let me know.

So, this feature will work like this:

```python
usernames_target = ['username1', 'username2', 'username3'];
```

The script will get the followers from the usernames_target and will interact with them: liking photos, following or commenting.

The script needs to be able to change target from usernames to tags (if it was filled) or to locations (if it was filled).

**Comment by mitchpa** [comment]
Sounds good 👍 any progress with this? highly requested feature

**Comment by mitchpa** [comment]
I've found targeting profiles that like the posts of influencer's or pages in a similar niche is very effective at finding engaged users

**Comment by danielcharrua** [comment]
Any updates on this issue?

**Comment by nickgryg** [comment]
It is impossible to get list of followers of some user: https://stackoverflow.com/questions/32407851/instagram-api-how-can-i-retrieve-the-list-of-people-a-user-is-following-on-ins

Closing this issue.
