### ISSUE TITLE
Action Blocked for following anyone

### ISSUE THREAD

**Issue by spodZ** [instabot-py/instabot.py#2258]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [X] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [X] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

I think Instagram is started to detecting bots or I could have reached the limit but for the past 3 days I’ve been Action Blocked to follow anyone.

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by spodZ** [comment]
I messed up the formatting.

**Comment by marcelofox** [comment]
I was doing around 300 follows/unfollows per day and I got blocked.

It's been 3 days straight that I can't follow anyone. Even tough I total disabled the bot. ;(

**Comment by spodZ** [comment]
I think Instagram changed the daily or hourly limit but they lifted my Action Blocked after 6 days.
