### ISSUE TITLE
Always getting error in modules

### ISSUE THREAD

**Issue by tiagofabrica** [instabot-py/instabot.py#2261]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X ] I have searched for other issues with the same problem or similar feature requests. 

I have the last update

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X ] Technical Help
- [ ] Other

#### Operating System? (include version)
- [ ] macOS
- [X ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [ X] I am using Python 3.6 or above

#### Exact Python Version?
 3.7.3
Include here the response of 'python --version' or 'python3 --version'
 3.7.3

#### Pip Version?
19.0.3
Include here the response of 'pip --version' or 'pip3 --version'
19.0.3

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT

C:\Users\YELLLOOWWW>cd desktop\instabot.py-master

C:\Users\YELLLOOWWW\Desktop\instabot.py-master>example.py
Traceback (most recent call last):
  File "C:\Users\YELLLOOWWW\Desktop\instabot.py-master\example.py", line 4, in <module>
    from instabot_py import InstaBot
  File "C:\Users\YELLLOOWWW\Desktop\instabot.py-master\instabot_py\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\YELLLOOWWW\Desktop\instabot.py-master\instabot_py\instabot.py", line 19, in <module>
    import instaloader
ModuleNotFoundError: No module named 'instaloader'


![](https://i.imgur.com/BcJypUm.png)

**Comment by yurilaaziz** [comment]
please install using pip install instabot-py

**Comment by Molar3NK** [comment]
> please install using pip install instabot-py

how
