### ISSUE TITLE
 InstaBot - INFO - Not liked: 400 message

### ISSUE THREAD

**Issue by Boxer1990** [instabot-py/instabot.py#2265]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ X] Bug
- [ ] Feature Request
- [ X] Technical Help
- [ ] Other

#### Environment
- [X ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [ X 18.04.02 LTS] Linux (include flavour) 
- [ ] Android (include terminal)

#### Python Version Requirement
- [X ] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.6.8
```

#### Pip Version?
```
pip 19.1.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
```

#### Description of your issue
Bot has stopped working due to error message below when trying to like/comment/follow.
```
root@ubuntu-2gb-fsn1-1:~# 2019-07-02 11:03:45,039 - InstaBot - DEBUG - Trying to like media: 2079014385171765452, https://www.instagram.com/p/BzaJJF3FxjM/
2019-07-02 11:03:45,240 - InstaBot - INFO - Not liked: 400 message {"message": "feedback_required", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/instagram_like_add/", "status": "fail"}

```

#### Config

```
[DEFAULT]
username = none
password = none
like_per_day = 709
comments_per_day = 31
max_like_for_one_tag = 36
follow_per_day = 260
follow_time = 36000
unfollow_per_day = 247
unfollow_break_min = 3
unfollow_break_max = 17
log_mod = 0
proxy =
unfollow_selebgram = False
unfollow_probably_fake = True
unfollow_inactive = True
unfollow_recent_feed = False
comment_list = [["this", "the", "your"], ["photo", "picture", "pic", "shot", "s$
tag_list = ["follow4follow", "f4f", "cute", "l:212999109"]

[*****]
username = *****
password = *********
like_per_day = 399
comments_per_day = 66
max_like_for_one_tag = 88
follow_per_day = 299
follow_time = 36000
unfollow_per_day = 199
tag_list = ["brisbane", "qld", "goldcoast", "bosniangirl", "audi", "fitgirl"]
unfollow_selebgram = True
unfollow_probably_fake = True
unfollow_inactive = True
unfollow_recent_feed = True

```

**Comment by velvetflower** [comment]
Same problem. Showed up after latest update.

**Comment by v78007800** [comment]
Have the same.
If you delete session file it allows to make 15-20 likes and got block again.

**Comment by mactrash** [comment]
Same issue, but still can like with mobile web client, seems the bot is got detect in some way.

**Comment by velvetflower** [comment]
> If you delete session file it allows to make 15-20 likes and got block again.
Confirmed. After removing session file it makes 10 likes and then stuck again.

**Comment by mrallanodreman** [comment]
I have a account working under the 300 likes and she still working without error!

**Comment by tombraider74** [comment]
Same problem here since yesterday. First like (after deleting session file) is possible, afterwards blocked.

**Comment by Boxer1990** [comment]
Seems to be an IP ban for both of my accounts.

Re-Deployed from new VPS and new IP and seems to be working fine for the last hour.

**Comment by velvetflower** [comment]
I found solution for my case.
Just connected from current PC to my vps via openvpn so I was used same ip with my vps where script placed.
Then I opened browser (for me it was opera), log in into instagram and set 1 like manually, then take User-Agent from request headers to like activity and put it into default_config.py with remove everyone else user agents except this. 
And it works now for about few hours without changing ip and vps.

**Comment by malaybasu** [comment]
@velvetflower could you post your useragent string. Thanks.

**Comment by velvetflower** [comment]
@malaybasu 

> Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.21 Safari/537.36 MMS/1.0.2531.0

**Comment by Boxer1990** [comment]
Woke up and error has re-appeared seems only a few hours in to the new IP -

"
2019-07-04 00:18:38,786 - InstaBot - INFO - Not liked: 400 message {"message": "feedback_required", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/instagram_like_add/", "status": "fail"}
"

**Comment by Boxer1990** [comment]
> 
> 
> I found solution for my case.
> Just connected from current PC to my vps via openvpn so I was used same ip with my vps where script placed.
> Then I opened browser (for me it was opera), log in into instagram and set 1 like manually, then take User-Agent from request headers to like activity and put it into default_config.py with remove everyone else user agents except this.
> And it works now for about few hours without changing ip and vps.

I may have to give this a go. Please update if still valid in 24hrs.

**Comment by mrallanodreman** [comment]
Some update!?!

**Comment by velvetflower** [comment]
> I may have to give this a go. Please update if still valid in 24hrs.

Nah. My acc got banned after about 9 hours of non-stop working. Now can't send likes from all my devices and ip. Probably need to increase time between likes. Also need add to "elif like.status_code == 400:" section removing current session file and re-login actions.
```
elif like.status_code == 400:
    ... # default
    if self.error_400 >= config.get("error_400_to_ban"):
        ... # default
    else:
        time.sleep(self.like_delay) # await
        os.remove(self.session_file) # remove session file
        self.__init__() # re init
        self.error_400 += 1
```

This helps to avoid error when bot recieve 400 error code, but you can manually send likes. Not the best way at all to avoid the error, but it allows to skip about 50 or more "400 status code error". Ha-ha.

**Comment by azor0** [comment]
I assigned a new IP to my machine and deleted the session file. Seems to be working, but this should be verified after 24 hours.

Unrelated question:
Could someone give a link/video on how to make own VPN?

**Comment by yurilaaziz** [comment]
@velvetflower  seems Instagram is tracking us by session id. 
do you have any idea to alter the session id from time to time?

**Comment by mrallanodreman** [comment]
or how to copy the sesision id from another place and replae with the banned id sesión?

**Comment by wahengchang** [comment]
same !

**Comment by MrRobotoGit** [comment]
Same here

**Comment by mrallanodreman** [comment]
i dont know how but im working again fine!

what i did:
 Delete the Session.file, with a new ip, use instagram app oficial for windows 10 to save cookies of session on the local machine, afther that go to browser (for me chronome in develop mode)  and find the same option inside Acc configuration and save cookies for the session.

afther you interact with the app, the browser, change your old configuration, put ir to work under the 300 likes and follows! 

ant then run de instabot. i tried this for last 19hrs. or something like that! 
and is working fine

**Comment by Martypary** [comment]
@mrallanodreman 

Sorry but can you only delate your session.file with a new ip ?

**Comment by mrallanodreman** [comment]
i mean, delete it but after you change your ip because you Will log again! and you need that the instabot request a new sesión.file or at least i understand that! 

but i suggest, put to work until the 5 or 6 hours, not for 24/7 because im sure that yuu get catch again!

**Comment by darkroker** [comment]
Hi guys. this was what i did it. 
1) update everything again.
2) I erased the session file and the db file and  put it run, worked perfetly fine.  (worked like 72 hrs) til i had to reset my laptop. for updates from windows.
in this case i had to erased everyting in the folder except my .py file and copied everything else from the Compressed file  and put it on run again ... for now it working, have 7 hrs running 

Pd: (i didnt used VPN or change my IP) sorry for my english

**Comment by mrallanodreman** [comment]
> Hi guys. this was what i did it.
> 
> update everything again.
> I erased the session file and the db file and  put it run, worked perfetly fine.  (worked like 72 hrs) til i had to reset my laptop. for updates from windows.
> in this case i had to erased everyting in the folder except my .py file and copied everything else from the Compressed file  and put it on run again ... for now it working, have 7 hrs running
> 
> Pd: (i didnt used VPN or change my IP) sorry for my english

Working Fine this solution!

**Comment by mactrash** [comment]
> Hi guys. this was what i did it.
> 
> 1. update everything again.
> 2. I erased the session file and the db file and  put it run, worked perfetly fine.  (worked like 72 hrs) til i had to reset my laptop. for updates from windows.
>    in this case i had to erased everyting in the folder except my .py file and copied everything else from the Compressed file  and put it on run again ... for now it working, have 7 hrs running
> 
> Pd: (i didnt used VPN or change my IP) sorry for my english

It stop working after couple hrs. confirmed

**Comment by darkroker** [comment]
> > Hi guys. this was what i did it.
> > 
> > 1. update everything again.
> > 2. I erased the session file and the db file and  put it run, worked perfetly fine.  (worked like 72 hrs) til i had to reset my laptop. for updates from windows.
> >    in this case i had to erased everyting in the folder except my .py file and copied everything else from the Compressed file  and put it on run again ... for now it working, have 7 hrs running
> > 
> > Pd: (i didnt used VPN or change my IP) sorry for my english
> 
> It stop working after couple hrs. confirmed

ok, tell me what did you do ? cause min still working

**Comment by mrallanodreman** [comment]
im working fine with the last solution, i suggest work with slow strategy!

**Comment by mactrash** [comment]
> > > Hi guys. this was what i did it.
> > > 
> > > 1. update everything again.
> > > 2. I erased the session file and the db file and  put it run, worked perfetly fine.  (worked like 72 hrs) til i had to reset my laptop. for updates from windows.
> > >    in this case i had to erased everyting in the folder except my .py file and copied everything else from the Compressed file  and put it on run again ... for now it working, have 7 hrs running
> > > 
> > > Pd: (i didnt used VPN or change my IP) sorry for my english
> > 
> > 
> > It stop working after couple hrs. confirmed
> 
> ok, tell me what did you do ? cause min still working

Latest instaBot code 4 days ago del db and session file
 200 like 100 comment per day run in VPS background

Android instagram original client VPN to same VPS

Result: no new likes show in instagram > setting > account > Post you've Liked after 8 hrs or so.

The I login the vps and kill the background job, and run in manual mode... and it show the 400 error until I del the session file again.

**Comment by tombraider74** [comment]
i have two accounts. the mentioned workaround seems to work only for one account. maybe there is a ban time for which you should not generate the 400 message until you try the workaround?

**Comment by wahengchang** [comment]
nono, it only works for 5min and then dead.

**Comment by velvetflower** [comment]
Depends on your account how much likes it will send. In my case I waited about 3 or 5 days and only then run the bot again. It sent ~ 75 likes and then received 400 error code.

**Comment by mrallanodreman** [comment]
im working fine!
deleting the session.file im working with 300likes per day, withouth Vpn 
4 accounts working fine!

**Comment by juanrojasm** [comment]
Hi! 
Im trying everything, can you say me how muchs follow, unfollows comments and likes per day ?
Thank you

**Comment by darkroker** [comment]
hi i dont use comments and likes 980 per day ... and 100 unfollows

**Comment by SpringboLives** [comment]
> > > Hi guys. this was what i did it.
> > > 
> > > 1. update everything again.
> > > 2. I erased the session file and the db file and  put it run, worked perfetly fine.  (worked like 72 hrs) til i had to reset my laptop. for updates from windows.
> > >    in this case i had to erased everyting in the folder except my .py file and copied everything else from the Compressed file  and put it on run again ... for now it working, have 7 hrs running

Following this strategy, I did some experimenting. My hypothesis is that the 400 errors are triggered by the ratio of likes to follows.

I wasn't able to get more than 2 likes/follows before the error message came up, so I turned my follows off and cranked likes up to 1000 to see how quickly I could trip the error message and I'm at 17 likes with no error message. Going to readjust down to 300 likes/day and see what happens. Will report back!

Thanks for all of the help in this thread.

**Comment by tombraider74** [comment]
> 
> 
> > > > Hi guys. this was what i did it.
> > > > 
> > > > 1. update everything again.
> > > > 2. I erased the session file and the db file and  put it run, worked perfetly fine.  (worked like 72 hrs) til i had to reset my laptop. for updates from windows.
> > > >    in this case i had to erased everyting in the folder except my .py file and copied everything else from the Compressed file  and put it on run again ... for now it working, have 7 hrs running
> 
> Following this strategy, I did some experimenting. My hypothesis is that the 400 errors are triggered by the ratio of likes to follows.
> 
> I wasn't able to get more than 2 likes/follows before the error message came up, so I turned my follows off and cranked likes up to 1000 to see how quickly I could trip the error message and I'm at 17 likes with no error message. Going to readjust down to 300 likes/day and see what happens. Will report back!
> 
> Thanks for all of the help in this thread.

Hi, just to give me my experience. I have two accounts, where one of them is working fine with the bot, and the other has problems, after trying to like once. But i got it working since yesterday by doing following: i stopped the bot, and deleted the session file and the database file. Then in waited about 1 day. After i got a new IP Address on my WAN Port, i started the bot again. It is still working after 24 hours, liking 1000 posts per day, doing some comments, unfollows and follows as well. Btw.: my first account had the same problems where i got it working by deleting the session file, Afterwards i connected via VPN to get another WAN IP and started the bot. During the bot was running, i cancelled the VPN connection. Since then i am able to run it on any network with any WAN IP.

**Comment by SpringboLives** [comment]
Been running for a day (sleeping from 10pm to 10am) with 150 likes/7 followers after I got a new IP for my VPN.

Had one hang up that I didn't report were I tried to do 190 likes/10 followers and it threw errors after following 3 people.

I hope the inactivity on the thread means that everybody else is running smoothly, as well :)

**Comment by Jangojack14** [comment]
Hi all , I have some clue to give to try to help for this probleme because i had it too. 

1 : Not a problem of IP or network settings : im running a bot from an other country for one account and i still can go up to 700 likes easy without any problems ( i have no vps,vpn ) nothing and it works well for this account. 

2 : It arrived to a new account i add 2 days ago ( the other accounts or this problems occured i just deleted the Session.files and all was fix) 

3 : I just see that the accounts  who worked is working that a different way that this one i have the this troubble : I try to explain -

I have always one line for my two accounts who works perfectly well :  
2019-07-13 23:05:54,804 - InstaBot - DEBUG - Get Media by tag: blackpanther
DEBUG:InstaBot:Get Media by tag: blackpanther

and for this account who doesnt work ( i put a lot of tags for both of them ) : 
2019-07-13 22:50:25,218 - InstaBot - DEBUG - Get Media by tag: artlovers
2019-07-13 22:51:37,198 - InstaBot - DEBUG - Get Media by tag: myart
2019-07-13 22:52:49,406 - InstaBot - DEBUG - Get Media by tag: painter
2019-07-13 22:54:01,702 - InstaBot - DEBUG - Get Media by tag: paintings
2019-07-13 22:55:13,835 - InstaBot - DEBUG - Get Media by tag: gallery
2019-07-13 22:56:26,198 - InstaBot - DEBUG - Get Media by tag: painting
2019-07-13 22:57:38,075 - InstaBot - DEBUG - Get Media by tag: acrylic
2019-07-13 22:57:48,088 - InstaBot - DEBUG - Trying to like media: 2087348593039108991, https://www.instagram.com/p/Bz3wHxyget_/
2019-07-13 22:57:48,930 - InstaBot - INFO - Liked: 2087348593039108991. Like #3 https://www.instagram.com/p/Bz3wHxyget_/.

I hope all i see can help if u have some idea or clue about this. 

Sorry for my mistake ^^

**Comment by Elektrokid1** [comment]
same issue, here it's clearly related to bot detection by the algorithm of Instagram, I think adding a random time process for the like can "maybe" solve the problem. it will not be easy

**Comment by Molar3NK** [comment]
I got the same issue, how do i delete the session .file? where i find this file?

**Comment by darkroker** [comment]
> I got the same issue, how do i delete the session .file? where i find this file?

in the instabot master folder this file create when you start using the bot...

**Comment by Molar3NK** [comment]
> > I got the same issue, how do i delete the session .file? where i find this file?
> 
> in the instabot master folder this file create when you start using the bot...

![image](https://user-images.githubusercontent.com/43768756/61254678-4a1b8900-a733-11e9-8de8-eb3b740c3ce2.png)

this is what is inside of my master folder ????

**Comment by darkroker** [comment]
> > > I got the same issue, how do i delete the session .file? where i find this file?
> > 
> > 
> > in the instabot master folder this file create when you start using the bot...
> 
> ![image](https://user-images.githubusercontent.com/43768756/61254678-4a1b8900-a733-11e9-8de8-eb3b740c3ce2.png)
> 
> this is what is inside of my master folder ????
ok in that folder will create the file session. name it with you user name of instagram...

**Comment by SpringboLives** [comment]
> 2019-07-13 22:50:25,218 - InstaBot - DEBUG - Get Media by tag: artlovers
2019-07-13 22:51:37,198 - InstaBot - DEBUG - Get Media by tag: myart
2019-07-13 22:52:49,406 - InstaBot - DEBUG - Get Media by tag: painter

@jangojack14 do you have the same likes per day for each bot? This just looks like the likes are turned down low on the second. Maybeee?

**Comment by wahengchang** [comment]
no luck for any solution. 
 - removed `*.session`
 - `like_perday = 200`

3 bots were running just for 1,2 hours

**Comment by Molar3NK** [comment]
> > > > I got the same issue, how do i delete the session .file? where i find this file?
> > > 
> > > 
> > > in the instabot master folder this file create when you start using the bot...
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/43768756/61254678-4a1b8900-a733-11e9-8de8-eb3b740c3ce2.png)
> > this is what is inside of my master folder ????
> > ok in that folder will create the file session. name it with you user name of instagram...

Working !!!!! removed  *.session

**Comment by Jangojack14** [comment]
> > 2019-07-13 22:50:25,218 - InstaBot - DEBUG - Get Media by tag: artlovers
> > 2019-07-13 22:51:37,198 - InstaBot - DEBUG - Get Media by tag: myart
> > 2019-07-13 22:52:49,406 - InstaBot - DEBUG - Get Media by tag: painter
> 
> @Jangojack14 do you have the same likes per day for each bot? This just looks like the likes are turned down low on the second. Maybeee?

Exactly, when i go as quick as the working account the bot get kicked out too quick like nearly the 27th likes..

**Comment by dwohl12** [comment]
has anyone got it  past 500 actions  i.e likes  comments and follows and unfollows ?

**Comment by tombraider74** [comment]
My bot is running 24 hours per day. i do ~950 likes ~50 comments ~ 80 follows and unfollows. once a day i do a relogin, and every second day i delete the session file before i do the relogin.  works fine so far.

**Comment by svinc** [comment]
@tombraider74 Is it still working for you?

**Comment by tombraider74** [comment]
@svinc yes it is still working fine.

**Comment by olaims** [comment]
in my case after 5 likes I got "banned" 

Changing IP helps to work less than 1h
Removing the .session files helps to work less than 15 minutes

**Comment by dwohl12** [comment]
how do I remove the file I have my bots running off google cloud vm   whats the commands to  fine and remove the file the .session file?

**Comment by wahengchang** [comment]
```
$ cd ./somthing/
$ rm *..session
```

**Comment by svinc** [comment]
@tombraider74 My apologies for asking again. But is it still working with no issues as of today? Just want to confirm because if this is true, I may have figured out IG's logic.

**Comment by tombraider74** [comment]
@svinc No, since two days i have problems to comment and like with the bot. Deleting the session file does not work at all. So i will wait until tomorrow to try it again...

**Comment by olaims** [comment]
the same here, but only doing "likes"

**Comment by etaxi341** [comment]
I'm coding my own Instagram application. It's not even a Bot. I just came here because google sent me here for googling "feedback required". So this error also appears for people that create legit programms that do not automate liking. Any ideas how to solve this? My accounts stop working after exactly 48hours with feedback required and spam=true

**Comment by paulzhang0610** [comment]
Had this problem several days ago. 
1. Delete .session file
2. rerun the script
3. works for 24 hrs and then error pops up again
4. go to step1 and repeat

**Comment by dwohl12** [comment]
any one find a new solution ?

**Comment by Elektrokid1** [comment]
https://medium.com/@asker_amine/whats-new-in-the-instagram-bot-0-5-2-fe52154fdc8a

**Comment by cala095** [comment]
> 
> 
> https://medium.com/@asker_amine/whats-new-in-the-instagram-bot-0-5-2-fe52154fdc8a

Worked for me

**Comment by husligc** [comment]
Does the medium article change help avoid the not liked 400 problem? Thanks and sorry for all of the questions.

**Comment by juanrojasm** [comment]
> > https://medium.com/@asker_amine/whats-new-in-the-instagram-bot-0-5-2-fe52154fdc8a
> 
> Worked for me

Im using this, but i dont know how to edit parameters like numbers of likes or hashtags!

**Comment by husligc** [comment]
Does the new update on github work well? the version from 5 days ago? @juanrojasm

**Comment by juanrojasm** [comment]
I think so, because i did install it today!

**Comment by husligc** [comment]
What numbers are you running? no not liked yet?

**Comment by juanrojasm** [comment]
i dont knwo how to run in windows, 
python -m instabot_py
You didn't provide your Instagram login & password or you didn't specify the configuration file
Try again :

   instabot-py --login YOUR_LOGIN --password YOUR_PASSWORD
   instabot-py -c your-config.yml
You can export and modify the default configuration by typing the command below
    instabot-py --dump

**Comment by husligc** [comment]
i am trying as well.  Seems way more complicated than the prior version

**Comment by wahengchang** [comment]
any one find a new solution ?

**Comment by joaocpereiraa** [comment]
> i dont knwo how to run in windows,
> python -m instabot_py
> You didn't provide your Instagram login & password or you didn't specify the configuration file
> Try again :
> 
> instabot-py --login YOUR_LOGIN --password YOUR_PASSWORD
> instabot-py -c your-config.yml
> You can export and modify the default configuration by typing the command below
> instabot-py --dump

use this on cmd python3 -m instabot_py

**Comment by arielgithub** [comment]
Hi, 

I tryed all possibility for avoid this error, but nothings solve this problems:
My solutions:
- Rotational proxy IP
- 60 Tags elements in tag list
- Delete de session file
- Remove, reinstall and rerun
- Change password
- Low value of like (50) and followers (50)
- Crontab shell script for delete the session file and relogin every one hour.
- Change User-Agent with my user-agent

**Comment by Elektrokid1** [comment]
Fork ------- https://github.com/yurilaaziz/neo-instabot

**Comment by jack75015** [comment]
Hey

I fixed it (maybe temporally) by going to my instagram web page --> accounts --> settings --> connexion activity and then accept the new connexion.
Next, I deleted the session file and reload the py bot and now it's working :) 

If someone did the same steps and still be block, please tell me :)

**Comment by sebasware** [comment]
@jack75015 Hi, failed to solve, where I find the session file, does not exist in my directories T_T

**Comment by DanielZanchi** [comment]
happening here :(
