### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by asainboi** [instabot-py/instabot.py#2267]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
3.7.3
```

#### Pip Version?
```
19.0.3
```

#### Description of your issue

```
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    from instabot_py import InstaBot
  File "/Users/ml/Desktop/yaga/instabot_py/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/ml/Desktop/yaga/instabot_py/instabot.py", line 58
    config.set("session_file", f"{login.lower()}.session", default=True)
                                                        ^
SyntaxError: invalid syntax
```

#### Config

```

```

**Comment by velvetflower** [comment]
@asainboi use python version 3.8.

**Comment by mrallanodreman** [comment]
Update python
