### ISSUE TITLE
Hashtags

### ISSUE THREAD

**Issue by asainboi** [instabot-py/instabot.py#2268]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
3.7.3
```

#### Pip Version?
```
19.1.1
```

#### Description of your issue

```
is there any way to make the bot only like posts in the "top" section and not the "recent" section of a hashtag?
```

#### Config

```

```

**Comment by mrallanodreman** [comment]
yes, just adjust the ammount of likes per tag to only 3, 6 or 12, Will be like only the first 3, 6 or 12 post from the hastag feed
