### ISSUE TITLE
How to setup follow_time

### ISSUE THREAD

**Issue by IshakBen** [instabot-py/instabot.py#2273]
Hello,
I have one simple question, i'm trying to understand how follow_time works?
is it like that:
days * hours * min or hours * min * sec
wich one is correct ?

**Comment by IshakBen** [comment]
Hello,
I have one simple question, i'm trying to understand how **follow_time** works?
is it like that:
 days*hours*min   or   hours*min*sec
wich one is correct ?

**Comment by danielcoam** [comment]
Hello,
The **follow_time** parameter is in `seconds`.
You can configure it like that:
```python
follow_time=1 * 60 * 60, # 1=Hours, 60=Minutes, 60=Seconds

# Examples:
follow_time=30 * 60, # 30 Minutes
follow_time=2 * 60 * 60, # 2 Hours
```

**Comment by IshakBen** [comment]
Thank you so much @danielcoam
