### ISSUE TITLE
Attribute Error: InstaBot object has no attribute 'csrftoken'

### ISSUE THREAD

**Issue by smoki3** [instabot-py/instabot.py#2278]
#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
```
3.7.3
```

#### Pip Version?
```
19.1.1
```

#### Description of your issue

```
Attribute Error: InstaBot object has no attribute 'csrftoken'

I got an IP ban. Then I deleted the session file and refreshed my ip. Since this I can not log in. Always get an csrf token error. If I restore my old session file, I can log in, but got still the ip ban.
```

**Comment by mrallanodreman** [comment]
we are triying deleting all the folder and unzipagain, configure again and change your password! 
please use lowaction strategi for at least 1 week
