### ISSUE TITLE
Security challenge - code not coming through 

### ISSUE THREAD

**Issue by husligc** [instabot-py/instabot.py#2279]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [ x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue
I was getting not liked 400 often on only one of my two accounts.  Now its giving me the security challenge and i'm not receiving anything.  Wait it out?
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by nativecodeabuser** [comment]
I had the same issue a few months ago. It would either not send me the code or not accept the code when entered. I changed the IP address as it seemed that Instagram really does not like certain providers and hostings. It stopped asking for a code.

**Comment by fernanespejo** [comment]
I have the same issue now.

Installed the latest version of pip (and upgraded instabot) but encountering the security challenge at every step.

I've scoured through the past issues and tried out logging in on Instagram on the same machine (in the hopes that the challenge will disappear) with no progress.

I have no session file to fall back into because I have done a clean install in to machine. Anyone know what I am missing?

**Comment by lachlanpage** [comment]
Noticing the same issue too

**Comment by husligc** [comment]
> I had the same issue a few months ago. It would either not send me the code or not accept the code when entered. I changed the IP address as it seemed that Instagram really does not like certain providers and hostings. It stopped asking for a code.

@nativecodeabuser How do you change your IP address? I googled it but I can't get it to work..

**Comment by husligc** [comment]
> I have the same issue now.
> 
> Installed the latest version of pip (and upgraded instabot) but encountering the security challenge at every step.
> 
> I've scoured through the past issues and tried out logging in on Instagram on the same machine (in the hopes that the challenge will disappear) with no progress.
> 
> I have no session file to fall back into because I have done a clean install in to machine. Anyone know what I am missing?

how do you delete the session file? I can't find it

**Comment by maxiwebb** [comment]
Same situation. First i got the 400 error why I created a new VPS with a different IP and now i'm getting this code challenge problem.

**Comment by husligc** [comment]
> Same situation. First i got the 400 error why I created a new VPS with a different IP and now i'm getting this code challenge problem.

Any ideas on what to try from here? @dimisdas

**Comment by maxiwebb** [comment]
Oh, I think I've solved it... I changed my password and tried it again. But this time the bot accepted my new code.

**Comment by husligc** [comment]
@maxiwebb were you not getting any code at first?
how did you  fix that?

**Comment by maxiwebb** [comment]
yes, i was getting a code at first. but the bot didn't accept it at first. then i changed my insta password and tried it gain. this time i had also to enter a code but this time it worked and the bot is running now.

**Comment by husligc** [comment]
let me know how it goes by tomorrow.  If its still working. I will try again in the morning USA time

**Comment by maxiwebb** [comment]
Hm, it worked for exactly one like... now it's the same problem again.

**Comment by atsuii** [comment]
I've also run into this problem after doing a clean install of the bot after reviving the 400 spam issue noted here: https://github.com/instabot-py/instabot.py/issues/2250

- I am hosting the bot on an AWS instance and re-newing the ip address doesn't solve the issue
- Challenge code isn't automatically generated so I need to manually visit the challenge url and request an sms code
- Inputing the 'challenge code' into the bot after generating it via the link throws an error saying it is incorrect
- Accepting the 'suspicious login' via the instagram app also doesn't resolve the issue
- Have also tried restarting my password and logging out of the account from all other points

**Comment by husligc** [comment]
Tried again this morning.  I still get the challenge and then it doesn't send a code or anything ...

**Comment by fernanespejo** [comment]
Exact same situation as atsuii, ive tried changing the password to test but still does not work.

**Comment by nickgryg** [comment]
This is very outdated issue. If you still have it, please try to use instabot-py version 0.5.20 or later.
