### ISSUE TITLE
Instaloader requires Python >= 3.5.

### ISSUE THREAD

**Issue by canpoyrazoglu** [instabot-py/instabot.py#2280]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (Raspbian/Raspberry PI)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.6.1
```

#### Pip Version?
```
pip 1.5.6
```

#### Description of your issue

```
I was using the bot a few months ago. I've decided to pull the latest version, tried to install the dependencies but I've got the error `Instaloader requires Python >= 3.5.` even though I'm on a higher Python version and I'm using pip3. 
```

**Comment by nickgryg** [comment]
This issue is for sure fixed in last instabot-py versions after 0.5.13. If you want to use it, just perform:
```
python3 -m pip install instabot-py
```
