### ISSUE TITLE
How can I follow/like accounts of a specific list of accounts?

### ISSUE THREAD

**Issue by maxiwebb** [instabot-py/instabot.py#2284]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (Ubuntu 19.04 x64)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
3.7.3
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
I would like to know if there is an option to create a list with users that followers I want to follow and like their posts?
```

#### Config

```

```

**Comment by nickgryg** [comment]
Duplicate to issue #2255
