### ISSUE TITLE
Not Liked error 400

### ISSUE THREAD

**Issue by jfinly** [instabot-py/instabot.py#2285]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
3.7
Include here the response of 'python --version' or 'python3 --version'
Python 3.7.0

#### Pip Version?
18.0
Include here the response of 'pip --version' or 'pip3 --version'
pip 18.0 from /Library/Python/2.7/site-packages/pip (python 2.7)#### Description of your issue
Not locked out of the account and only running a single instance, yet i started receiving, error 400 msg after the newest IG update
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
09.07.2019_22:35 Not liked: 400 message {"message": "feedback_required", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/instagram_like_add/", "status": "fail"}

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by atsuii** [comment]
I am also experiencing this issue today. Looks like instagram has identified the bot as spam.

**Comment by 1337C0D3RS** [comment]
same here

**Comment by husligc** [comment]
Any fix yet?

**Comment by maxiwebb** [comment]
> Any fix yet?

Come down man...you don't need to ask every few hours if it's working now. They will inform you when they've fixed something.

**Comment by waynoedm** [comment]
Yes. Bot is being identified by Instagram, and unfortunately they're blocking it.

**Comment by husligc** [comment]
If you go only comments and no likes, it works perfectly. ;)

**Comment by LorisBalsamo** [comment]
I deleted the .session file and now it works with a new session file.

**Comment by Molar3NK** [comment]
> I deleted the .session file and now it works with a new session file.

how do you do this ?? where is the session.file location

**Comment by philipborgmann** [comment]
Deleting the .session file worked for me as well. 

> > I deleted the .session file and now it works with a new session file.
> 
> how do you do this ?? where is the session.file location

it should be named [username].session and should be located in the parent folder of your instabot folder.

**Comment by olaims** [comment]
Hopefully there is a solution to "renew" the .session somehow :)

**Comment by basicBrogrammer** [comment]
The follow/unfollow still works .... Might be worth adding a `like_break` || `time_between_likes` config to manage it. I wonder if it would be possible to pick a Rand(20) or something to help it be untrackable.

**Comment by husligc** [comment]
> The follow/unfollow still works .... Might be worth adding a `like_break` || `time_between_likes` config to manage it. I wonder if it would be possible to pick a Rand(20) or something to help it be untrackable.

Any progress on this? Still having loads of problems with not liked 400 on low comment/like settings,

Would appreciate it greatly!

**Comment by dsmh** [comment]
Same problem here

> > The follow/unfollow still works .... Might be worth adding a `like_break` || `time_between_likes` config to manage it. I wonder if it would be possible to pick a Rand(20) or something to help it be untrackable.
> 
> Any progress on this? Still having loads of problems with not liked 400 on low comment/like settings,
> 
> Would appreciate it greatly!

**Comment by renelikestacos** [comment]
Had same error, but apparently delete session file works for me too.
