### ISSUE TITLE
'InstaBot' object has no attribute 'write_log'

### ISSUE THREAD

**Issue by joemaffia** [instabot-py/instabot.py#2290]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x ] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.3
```

#### Pip Version?
```
pip 19.0.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7
```

#### Description of your issue
Issue seems happening when I want to use the -keywords- tag 
```
Traceback (most recent call last):
  File "/usr/local/bin/instabot-py", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/instabot_py/__main__.py", line 395, in main
    bot.mainloop()
  File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 804, in mainloop
    self.new_auto_mod_follow()
  File "/usr/local/lib/python3.7/site-packages/instabot_py/instabot.py", line 956, in new_auto_mod_follow
    self.write_log(
AttributeError: 'InstaBot' object has no attribute 'write_log'
```

#### Config

```
like_per_day = 250
comments_per_day = 31
max_like_for_one_tag = 36
follow_per_day = 260
follow_time = 36000
unfollow_per_day = 247
tag_list=["something", "here"]
keywords=["something", "here"]
unfollow_selebgram = False
unfollow_probably_fake = True
unfollow_inactive = True
unfollow_recent_feed = False
```

**Comment by nickgryg** [comment]
Issue is commented in #2294
