### ISSUE TITLE
trying to comment

### ISSUE THREAD

**Issue by DasteS** [instabot-py/instabot.py#2293]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)
Windows 10

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.3
```

#### Pip Version?
```
pip 19.1.1 from c:\users\daste\appdata\local\programs\python\python37-32\lib\site-packages\pip (python 3.7)
```

#### Description of your issue

```
When the bot tries to comment, It says: Trying to comment: xxx
https://user-images.githubusercontent.com/51968163/61176835-06f0d700-a5c8-11e9-9809-4b84e1fdd44b.PNG
```

#### Config

```
like_per_day = 0
comments_per_day = 200
max_like_for_one_tag = 36
follow_per_day = 200
follow_time = 36000
unfollow_per_day = 0
tag_list = ["zenskagarderoba", "zenskaodeca", "odeca", "haljinezamaturu", "haljineprodaja", "haljineikrpice", "suknje", "odecazazene", "zenskamoda", "serbiafashion", "garderoba", "beogradnocu", "gdeizaci", "belgrafenight", "kragujevacplaza", "deltacity", "usceshoppingcenter", "l:2168115820111606", "l:213718229", "l:215287775", "l:213801245", "l:219804570", "l:251062676"]
unfollow_selebgram = True
unfollow_probably_fake = True
unfollow_inactive = True
unfollow_recent_feed = False

``

**Comment by ShovanDhara** [comment]
I'm having the same issue. Please help

**Comment by nickgryg** [comment]
This is very outdated issue. If you still have it, please try to use instabot-py version 0.5.20 or later.
