### ISSUE TITLE
Trying to like media no response 

### ISSUE THREAD

**Issue by CammeIlo** [instabot-py/instabot.py#2298]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```Python 3.7.3```
Include here the response of 'python --version' or 'python3 --version'
```Python 3.7.3```

#### Pip Version?
```9.0.3```
Include here the response of 'pip --version' or 'Python 3.7.3'
```pip 9.0.3 from /usr/lib/python3.7/site-packages (python 3.7)```

#### Description of your issue

``` Hi, it's been a while since when I run (in screen or nohup or normally) the .py keeps trying to put "like" without getting feedback. Sometimes it works for few beginning minutes, sometimes instead it's starts like this:  ```

####
2019-07-16 14:23:29,307 - InstaBot - DEBUG - Trying to like media: id: 2089286458209088716, url: https://www.instagram.com/p/Bz-ovbXljTM/
2019-07-16 14:23:31,357 - InstaBot - DEBUG - Trying to like media: id: 2089282894660828023, url: https://www.instagram.com/p/Bz-n7kjjvt3/
2019-07-16 14:23:33,409 - InstaBot - DEBUG - Trying to like media: id: 2089280757504765382, url: https://www.instagram.com/p/Bz-nceLIW3G/
2019-07-16 14:23:34,458 - InstaBot - DEBUG - Trying to like media: id: 2089279729455816420, url: https://www.instagram.com/p/Bz-nNguo17k/
2019-07-16 14:23:35,507 - InstaBot - DEBUG - Trying to like media: id: 2089275165666986031, url: https://www.instagram.com/p/Bz-mLGXoEgv/
2019-07-16 14:23:36,555 - InstaBot - DEBUG - Trying to like media: id: 2089278501489029656, url: https://www.instagram.com/p/Bz-m7pGHTIY/
2019-07-16 14:23:37,609 - InstaBot - DEBUG - Trying to like media: id: 2089277608052180495, url: https://www.instagram.com/p/Bz-mupBIMYP/
2019-07-16 14:23:39,662 - InstaBot - DEBUG - Trying to like media: id: 2089274157322918961, url: https://www.instagram.com/p/Bz-l8bRotwx/
2019-07-16 14:23:40,713 - InstaBot - DEBUG - Trying to like media: id: 2089264302107251243, url: https://www.instagram.com/p/Bz-jtA5AdIr/
2019-07-16 14:23:41,769 - InstaBot - DEBUG - Trying to like media: id: 2089268576918536764, url: https://www.instagram.com/p/Bz-krOHnYI8/
2019-07-16 14:23:42,822 - InstaBot - DEBUG - Trying to like media: id: 2089268548313580135, url: https://www.instagram.com/p/Bz-kqzeoIJn/
2019-07-16 14:23:43,873 - InstaBot - DEBUG - Trying to like media: id: 2089267602319988510, url: https://www.instagram.com/p/Bz-kdCdA9ce/

#### Config

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from instabot_py import InstaBot

bot = InstaBot(
    login="",  # Enter username (lowercase). Do not enter email!
    password="",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=["planche", "calisthenics", "frontlever", "muscleup"],
    tag_blacklist=["rain", "thunderstorm"],
    user_blacklist={},
    max_like_for_one_tag=5000,
    follow_per_day=300,
    follow_time=1 * 60 * 60,
    unfollow_per_day=300,
    unlike_per_day=0,
    unfollow_recent_feed=True,
    # If True, the bot will also unfollow people who dont follow you using the recent feed. Default: True
    time_till_unlike=0 * 24 * 60 * 60,  # 3 days
    unfollow_break_min=15,
    unfollow_break_max=30,
    user_max_follow=0,
    # session_file=False, # Set to False to disable persistent session, or specify custom session_file (ie ='myusername.session')
    user_min_follow=0,
    log_mod=0,
    proxy="",
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"

```

**Comment by umbrellr** [comment]
This seems to happen when an Instagram account gets a temporary block for misuse. If you try and manually like something on the account, you'll maybe see it's an issue with the Instagram account itself, and not the bot.

**Comment by CammeIlo** [comment]
If I try to like or do any other action on my account there aren’t any limitations.

**Comment by umbrellr** [comment]
Try deleting the .session file from the directory and restarting the bot.

**Comment by CammeIlo** [comment]
I try do to it . It's seems to work , almost 1 hour from the run.

**Comment by CammeIlo** [comment]
Nothing to do. The issue come back , even if i try to delete .session every time.

**Comment by samkerm** [comment]
Yeah, comes back

**Comment by umbrellr** [comment]
Clearly Instagram is flagging the session as suspicious, so maybe try reducing the activity of the bot and then try running it again after the temporary block has been lifted. Slow and cautious rather than fast and suspicious activity.

**Comment by JonO7694** [comment]
You have most likely been banned from liking for a period of time. I would stop using the bot for a full day and reduce your likes per 24 hours to 400 Max for the next 2 days. After that you can increase your likes per 24 hours accordingly

**Comment by CammeIlo** [comment]
Ok , I've done it. So from what I understand, is that simply a problem due to ig control algorithm  ?

**Comment by JonO7694** [comment]
Yes. And if you keep pushing it you risk your account getting banned for
bot activity

----------------------------------------------------
Please be warned that any attachments used in a email are confidential and
may be protected under copyright laws. Please do not share email
attachments without explicit permission from Remix Lyrics.
Failing to comply may lead to Remix Lyrics taking lawful action
----------------------------------------------------

**Comment by clarelou0128** [comment]
I am experiencing the same problem right now.. I was blocked temporarily by instagram for a day. After i can reuse my instagram, the instabot is still not working. It's trying to like & follow people but doesn't work. I deleted the .session file and it doesn't help.. not sure what happened... If I go on instagram myself, i can like, comment & follow people.

**Comment by CammeIlo** [comment]
> I am experiencing the same problem right now.. I was blocked temporarily by instagram for a day. After i can reuse my instagram, the instabot is still not working. It's trying to like & follow people but doesn't work. I deleted the .session file and it doesn't help.. not sure what happened... If I go on instagram myself, i can like, comment & follow people.

I had the same experience, affected also by the shadowban. For at least 7 days I was blocked, the only thing I've done was to wait. Now I still i can like, comment ecc. and bot works some days , other days don't ..

**Comment by JonO7694** [comment]
I'm having that same issue. I'm unable to find a solution

----------------------------------------------------
Please be warned that any attachments used in a email are confidential and
may be protected under copyright laws. Please do not share email
attachments without explicit permission from Remix Lyrics.
Failing to comply may lead to Remix Lyrics taking lawful action
----------------------------------------------------

**Comment by hakey1408** [comment]
I have the same issue. I will try to change user agent and reduce bot activity.

**Comment by roviraleix** [comment]
Same here, I can like posts on my phone/pc but not with the bot

**Comment by candiii** [comment]
I WAS HAVING THIS PROB SO WAT I DID WAS CHANGE THE VALUE OF THE LIKES PER DAY TO 0 AND IT WORKED AND AFTER 24 OR 48 HOURS U CAN CHANGE THE VALUE BACK. THE THING IS INSTA SUSPECTS U AS A BOT SO IF U KEEP USING IT TOO MUCH UR ACC MIGHT ALSO GET BANNED SO WAIT FOR ONE DAY OR SO.(P.S DONT MIND THE CAPS*WHISPERS*)

**Comment by OpeningIntroduction** [comment]
I'm having the same issue as well. Decided to try and implement a different bot until I read this thread.

**Comment by shubhamkothari2808** [comment]
Any update on this guys? My bot is still stuck on 'Trying to like media...." nothing happens beyond this.
Any idea how to resolve?

**Comment by crithcrith03** [comment]
I will not improve the same problem.
