### ISSUE TITLE
Bug in mention post owner

### ISSUE THREAD

**Issue by mrb0098** [instabot-py/instabot.py#2308]
#### Select one:
- [ ] Bug
- [ ] Feature Request
- [#] Technical Help
- [ ] Other

#### Environment
- [#] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [#] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [#] I am using Python 3.6 or above

#### Config

```
change :
comment_text = comment_text.replace("@username@", self.current_owner)
to :
comment_text = comment_text.replace("@username@", "@"+self.current_owner+" ")
because in instagram we need '@' mark to mention others :smile:  
```

**Comment by nickgryg** [comment]
This issue is very outdated. It should have been fixed many releases ago. Please update `instabot-py` to the latest version and check if this issue still exists.
