### ISSUE TITLE
Avoid commenting on same users

### ISSUE THREAD

**Issue by petergriffin1986** [instabot-py/instabot.py#231]
Hello,

Is there a way to avoid commenting on same users?
This would help people from noticing that it is a bot. For instance, if the bot commented on some media, it shouldn't comment again on same user for 2-3 weeks or something.
This value can be configurable...

Regards,
Peter Griffin

**Comment by mactrash** [comment]
Please add this many thanks.

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
