### ISSUE TITLE
Unable to unfollow everyone

### ISSUE THREAD

**Issue by Trazmor** [instabot-py/instabot.py#2313]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?

```
3.7.3
```

#### Pip Version? 
```
19.1.1
```

#### Description of your issue
I try to unfollow at one time everyone the bot has previously followed and to keep the accounts I manually followed. The bot is unfollowing slowly but I cant make it unfollow in one time despite the "follow_time = 1"

#### Config

```
like_per_day = 0
comments_per_day = 0
max_like_for_one_tag = 36
follow_per_day = 0
follow_time = 1
unfollow_per_day = 1247
unfollow_selebgram = False
unfollow_probably_fake = True
unfollow_inactive = True
unfollow_recent_feed = False
unfollow_everyone = True
```

**Comment by nickgryg** [comment]
According to you configuration, bot will unfollow 1247 users in a day. That means it will try to unfollow them every 60 * 60 * 24 / 1247 = 69 seconds. "follow_time = 1" means to unfollow user who has been just followed after 1 second.
