### ISSUE TITLE
python: can't open file 'example.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jrotier16** [instabot-py/instabot.py#2315]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by jrotier16** [comment]
Hi everyone ! I'm new in programming and code but I tried to install instabot. Everything was perfect as the many tutorials on internet but for the last code wich is : "python example.py" 
I've got an error message : "python: can't open file 'example.py': [Errno 2] No such file or directory"

If someone can help me with that it will be very kind ! Have a good day everyone :) 

Jerome

**Comment by whocodes** [comment]
@jrotier16 how are you installing `instabot.py`? with `pip` or with `git`?

**Comment by whocodes** [comment]
if you are using `pip`, but you are wishing to make changes to the python app, you should check out a tutorial for `using python with git` (there's one by realpython that i used) and one for `building python from git` (there's one on the python website that i used)

**Comment by jrotier16** [comment]
I'm using code with pip ! Do you have the link of your tutorial ? Thank's :)

**Comment by jrotier16** [comment]
![Capture d’écran 2019-07-29 à 10 58 48](https://user-images.githubusercontent.com/53404662/62035345-e80d5a00-b1ef-11e9-843d-28eabb755fa1.png)

**Comment by nickgryg** [comment]
Version 0.5.20 was recently released. It has clear description how to create configuration and run the bot.
