### ISSUE TITLE
ModuleNotFoundError: No module named 'config42'

### ISSUE THREAD

**Issue by lidoramrani** [instabot-py/instabot.py#2316]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

#### Environment
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so, have you tried running the code on your local machine?
Same problem

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [X] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?

```
Python 3.7.3
```
'

#### Pip Version?
```
pip 8.1.1
```

I am trying to run the example.py file but this is the response I get:
```
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    from instabot_py import InstaBot
  File "/home/lidoramrani21/instabot.py/instabot_py/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/lidoramrani21/instabot.py/instabot_py/instabot.py", line 22, in <module>
    from instabot_py.config import config
  File "/home/lidoramrani21/instabot.py/instabot_py/config.py", line 4, in <module>
    from config42 import ConfigManager
```

Any ideas of what to do?

**Comment by anzora95** [comment]
pip install config42 on your bash
