### ISSUE TITLE
Improve documentation for using yml file

### ISSUE THREAD

**Issue by scaraux** [instabot-py/instabot.py#2320]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

#### Environment
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [X] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Description of your issue

It took me literally a day to figure out how to use instabot with the `.yml`configuration file, instead of the `.ini`. It is not mentioned in the README, and I finally understood that I was supposed to run the bot like so: `python3 -m instabot --`

We should improve the readme and make it clear that there are multiple ways to run the bot..

**Comment by limerick11** [comment]
@scaraux Are you able to provide steps on how you used the yml file? I have both ini and yml and although the bot said it's reading from the yml file, nothing happens.

**Comment by scaraux** [comment]
> @scaraux Are you able to provide steps on how you used the yml file? I have both ini and yml and although the bot said it's reading from the yml file, nothing happens.

Yes, luckily I found the following article: [https://medium.com/@asker_amine/instabot-py-rework-7fa68a6cadab](medium)

The only way I found to tell the bot to use the .yml file is to pass `--` as argument of the bot.

Example `$ python3 instabot_py --`

**Comment by limerick11** [comment]
@scaraux you, i already read that but it didn't explain what should be in the ini and yml file. Can you provide examples? 
Also, do i create instabot.config.yml and instabot.config.ini and just run python3 instabot_py -- on the command line?

**Comment by scaraux** [comment]
@limerick11 I am not sure to be honest. I never maintained the code.
By inspecting the code, I see that the way it works is that it first reads the yml file and then the .ini and does some sort of merged dictionnary from the key-values it finds in both files.

If you specify `--` as parameter, then it only reads the .yml file and does not do the interactive mode (.ini config)

**Comment by scaraux** [comment]
#2330

**Comment by nickgryg** [comment]
This is very outdated issue. If you still have it, please try to use instabot-py version 0.5.20 or later.
