### ISSUE TITLE
Randomize action interval?

### ISSUE THREAD

**Issue by nativecodeabuser** [instabot-py/instabot.py#2321]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux
- [ ] Android (include terminal)

#### Python Version Requirement
- [ ] I am using Python 3.6 or above

As we can all see, Instagram got pretty damn accurate in detecting automated activities. I'm using the same IP and same UserAgent as on my desktop and still it gets detected. Wouldn't it make sense to randomize the interval between actions to make them look more humanlike?

**Comment by mrallanodreman** [comment]
Put your bots on android, go and conect from any wifi, use data, and that will make humanlike... you can spoof the gps

**Comment by yurilaaziz** [comment]
Random intervals were improved in the 0.5.2 release 
please update
