### ISSUE TITLE
There was a problem logging you into Instagram. Please try again soon.

### ISSUE THREAD

**Issue by bboy519** [instabot-py/instabot.py#2322]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```3.7.4
Include here the response of 'python --version' or 'python3 --version'
```
Python 3.7.4
#### Pip Version?
```

```

#### Description of your issue

```"There was a problem logging you into Instagram. Please try again soon."
When login via the web it shows the message above
when login via the old version of the bot it shows
"Login error! Check your login data!"
The new version keeps "trying to like post"

```

#### Config

```

```

**Comment by AbdulBariKhan** [comment]
You can delete my issue ..... thanks for contacting me
