### ISSUE TITLE
using yaml

### ISSUE THREAD

**Issue by limerick11** [instabot-py/instabot.py#2325]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x ] Linux (Raspbian Buster )
- [ ] Android (include terminal)

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```
Python 3.7.3
#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
#### Description of your issue

Can someone provide steps on how to use yaml file to configure the bot? What information should be in the file and where should it be located? How do we run the bot with yaml file?

Thanks!

**Comment by yurilaaziz** [comment]
please check this https://medium.com/@asker_amine/whats-new-in-the-instagram-bot-0-5-2-fe52154fdc8a
