### ISSUE TITLE
"Cannot choose from an empty sequence" while viewing stories

### ISSUE THREAD

**Issue by booksix** [instabot-py/instabot.py#2326]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.6.5
```

#### Pip Version?
```
pip 18.0
```

#### Description of your issue
I am running "watch_user_likers_stories.py" and I'm 5ish minutes I'm getting output that says
```
"INFO - Cannot choose from an empty sequence" 
```
which is then followed by another 5 minutes of no action (so I lose 5 minutes of progress). Unfortunately the output from this is very limited so I don't even know where it is in the code when the message occurs.

I also get the following messages/errors:
```
ERROR - Request returns 400 error!
INFO - Instagram's error message: Invalid reel id list
INFO - Instagram's error message: {}
INFO - 'list' object has no attribute 'items'
```

**Comment by ElliotPadfield** [comment]
Not a solution but if you change the sleep time in your config, you can remove the 5 minutes of no action. Might help until a fix can be found.

**Comment by nickgryg** [comment]
This issue is not about `instabot-py`. We don't even have `watch_user_likers_stories.py` in our library.
