### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by hawshiet** [instabot-py/instabot.py#2328]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows (W10)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.4
```

#### Pip Version?
```
pip 19.2.1
```

#### Description of your issue
```
  File "example.py", line 9
    comments_per_day=0,
                   ^
SyntaxError: invalid syntax
```

#### Config

```
[...]
bot = InstaBot(
    login="xxxxxx",  # Enter username (lowercase). Do not enter email!
    password="xxxxxx"
    comments_per_day=0,
[...]
```

**Comment by hawshiet** [comment]
I can't figure what i'm missing. I've been fixing stuff all along by myself but can't figure this one :/

**Comment by svinc** [comment]
@hawshiet you forgot a comma after   password="xxxxxx"

**Comment by hawshiet** [comment]
OMG how did i missed that ! -_-"
Thanks a lot @svinc
