### ISSUE TITLE
Any idea to spoof Instagram app action?

### ISSUE THREAD

**Issue by bboy519** [instabot-py/instabot.py#2329]
@blauergolfer it did happened.
However I can like at the instagram app.
It seems the only way to get around this is to spoof like action as it was generated from the app.

**Comment by ByBilal** [comment]
> @blauergolfer it did happened.
> However I can like at the instagram app.
> It seems the only way to get around this is to spoof like action as it was generated from the app.

what do u mean, spoof like? Thanks

**Comment by bboy519** [comment]
Mimicking in-app action
