### ISSUE TITLE
Can i help your team for developing this project and be your student?

### ISSUE THREAD

**Issue by mehedad3131r** [instabot-py/instabot.py#2331]
Hi 
Im a server side developer in iran and i use php/laravel/python/django/perl for my projects 

Can i be your student in this project?

Please talk me by email and see my demo projects im very interested to instagram api

Mehrdad3131r@gmail.com
Whatsapp skype and etc : +989054623745

**Comment by yurilaaziz** [comment]
the project is opensource feel free to contribute.
I will add a code of conduct to manage this project
