### ISSUE TITLE
instabot database issue (new download)

### ISSUE THREAD

**Issue by mcarlock1** [instabot-py/instabot.py#2332]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ x] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.3
```

#### Pip Version?
```
pip 19.1.1 from /anaconda3/lib/python3.7/site-packages/pip (python 3.7)
```

#### Description of your issue
```
after reinstalling instabot and running example.py there is a database error that keeps occurring
```
Traceback (most recent call last):
  File "example.py", line 122, in <module>
    unfollow_whitelist=["example_user_1", "example_user_2"],
  File "Desktop/instabot.py-master/instabot_py/instabot.py", line 60, in __init__
    self.persistence = PersistenceManager(self.config.get("database"))
  File "/anaconda3/lib/python3.7/site-packages/config42/config_manager.py", line 110, in get
    return self.render_recursive(value) if render else value
  File "/anaconda3/lib/python3.7/site-packages/config42/config_manager.py", line 195, in render_recursive
    return {key: self.render_recursive(value) for key, value in obj.items()}
  File "/anaconda3/lib/python3.7/site-packages/config42/config_manager.py", line 195, in <dictcomp>
    return {key: self.render_recursive(value) for key, value in obj.items()}
  File "/anaconda3/lib/python3.7/site-packages/config42/config_manager.py", line 193, in render_recursive
    return self.render(obj)
  File "/anaconda3/lib/python3.7/site-packages/config42/config_manager.py", line 182, in render
    rendered_value = self.jinja2_env.from_string(rendered_template).render(self.as_dict())
  File "/anaconda3/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/anaconda3/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'database' is undefined

**Comment by mrallanodreman** [comment]
How can i get the older version

**Comment by mcarlock1** [comment]
> How can i get the older version

are you having the same issue?

**Comment by mrallanodreman** [comment]
Im having the same issue when i do

**Comment by flaggz** [comment]
same for me
if I use interactive the bot simply doesn't start. it stays stuck on
 ______Starting bot_____
if I use instabot-py it says Exception: Account details are missing and I checked that the option login is written instead of username

**Comment by mo-username** [comment]
Hello! Did you found a solution for this error? @mcarlock1

**Comment by stachyc** [comment]
Tha same issue.

**Comment by mcarlock1** [comment]
> Hello! Did you found a solution for this error? @mcarlock1

no i have not

**Comment by mcarlock1** [comment]
@yurilaaziz i see you made a commit 16hours ago? did you fix the issue?

**Comment by yurilaaziz** [comment]
I am writing an article to answer to all your questions

**Comment by yurilaaziz** [comment]
https://medium.com/@asker_amine/whats-new-in-the-instagram-bot-0-5-2-fe52154fdc8a

**Comment by mcarlock1** [comment]
@yurilaaziz having trouble running  instabot-py --login my_username_example --password fun!23

error:
-bash: !4: event not found

how do I fix?

**Comment by mo-username** [comment]
> https://medium.com/@asker_amine/whats-new-in-the-instagram-bot-0-5-2-fe52154fdc8a
Thank you, sir! @yurilaaziz

**Comment by brainskittles** [comment]
wait, so I'm kind of a newbie, what do I do to fix the error?

**Comment by mo-username** [comment]
> wait, so I'm kind of a newbie, what exaxtly do I do to fix the error?

I’m not a programmer as well, haha.
I’m using Windows 10.
I’m now trying to create the configuration sample file, but the prompt shows: instabot-py: error: unrecognized arguments: --dump. 
The command line “instabot-py --login YOUR_LOGIN --password YOUR_PASSWORD” works perfectly, but it loads the bot’s default configuration.
I’m trying to solve by myself, haha.

**Comment by limerick11** [comment]
@mo-username i fixed this issue by updating.
python3 -m pip install instabot-py --no-cache-dir --upgrade
The new version I see is 0.5.4

**Comment by itsmejamie** [comment]
@mo-username 

Same, can get up to that point, but can never edit my config and don't know where to put my username as password 

@limerick11 

Tried doing that and now I get the error:

clarifai 2.6.1 has requirement jsonschema<3,>=2.5, but you'll have jsonschema 3.0.1 which is incompatible.

I've tried following @yurilaaziz medium.com instructions, but always get stuck on the myconfig part

**Comment by mo-username** [comment]
> @mo-username i fixed this issue by updating.
> python3 -m pip install instabot-py --no-cache-dir --upgrade
> The new version I see is 0.5.4

Thank you so much, @yurilaaziz and @limerick11 ! After many tries, it finally worked! I don't know exactly how, haha!

I really appreciate and value your work, guys! Cheers from Brazil!

**Comment by brainskittles** [comment]
didnt work for me :(

**Comment by mo-username** [comment]
> didnt work for me :( still getting the default settings.

@brainskittles I will try explaining what I did (my English is so good as my Python skills, :D):

- Download the file sample.instabot.config.yml from https://github.com/instabot-py/instabot.py and save at the same folder of the myconfig.yml

- Rename sample.instabot.config.yml to instabot.config.yml

- You need to edit the instabot.config.yml
-- Add the line “tag_list”
-- Edit username and password
-- Save the file

---
tag_list: ['TAG_1', 'TAG_2', 'TAG_3']
login : "username"
password : "password"
…
…

- Now run the bot

instabot-py

**Comment by itsmejamie** [comment]
Tried doing what you have done and still having issues. Would someone be able to confirm what I'm doing is correct considering I'm on a Mac. 

- I created a new folder called 'Instabot' in my home folder (it has my name with a little house beside it)
- I followed the instructions as per the two videos on the medium.com instructions.
- My instabot folder holds the .db and .session files as well as the myconfig.yml and venv folder. 
- When I try to copy over the sample.instabot.config yml and edit it as per the instruction above I'm still met with the missing credentials issue. 

- When I runs the  instabot-py --login "" --password "" I still get the cat/dog/car tags.

**Comment by mo-username** [comment]
@itsmejamie did you added the line "tag_list" to "myconfig.yml"?

See print screen:
 
![instabot-py](https://user-images.githubusercontent.com/53695380/62531443-d859cb00-b818-11e9-8499-9f324a5d85e2.jpg)

**Comment by itsmejamie** [comment]
Yes, I did. So just to confirm. I will have all my files in a folder called "Instabot"
This file holds:

- the .db file
- the .session file
- myconfig.yml file
- instabot.config.yml file 
- venv folder 

Is that correct? Do need to make any changes to the myconfig.yml file? Or only instabot.config.yml?

**Comment by itsmejamie** [comment]
@mo-username I think I have it working now! Many thanks for your help. It followed the instructions step by step and this time it seemed to have worked!

**Comment by mo-username** [comment]
@itsmejamie Very good!
I don’t know if it’s the right solution, but it’s working great, haha!
Add the line comment_list. See the image:
![instabot-py_02](https://user-images.githubusercontent.com/53695380/62546336-ad33a380-b839-11e9-8ae4-732e5134cfbf.jpg)

**Comment by itsmejamie** [comment]
@mo-username Yeah! Thats what I ended up doing too. Is your unfollow working? I added a unfollow_whitelist, but I think that has caused issues with the bot unfollowing.

**Comment by mo-username** [comment]
@itsmejamie I didn’t realize that the “unfollow” wasn’t working. I was using only “like” and “comment” options. Perhaps Instagram had made some changes. We need a professional programmer, :D.

**Comment by wallstreetbets** [comment]
The unfollow is not working, I tried turning off the `unfollow_recent_feed=False` but I kept getting the same error.

**Comment by DayS1eeper** [comment]
> How can i get the older version

you can see release history of instabot-py here https://pypi.org/project/instabot-py/#history and install arbitrary version with commands below (it installs instabot-py Jul,4 release and solves this error):
```
pip uninstall instabot-py
```

```
pip install instabot-py==0.4.10
```
