### ISSUE TITLE
Add a check to see if posts have commenting enabled

### ISSUE THREAD

**Issue by svinc** [instabot-py/instabot.py#2339]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Ubuntu 16.04 Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
3.6
```
#### Description of your issue

```
If the bot tries to comment on a post that has comments disabled, IG will block the account. Add a check to see if each IG post has commenting enabled.
 ```

**Comment by nickgryg** [comment]
This feature was added in version `0.7.5`.
