### ISSUE TITLE
Latest version 0.5.7 won't unfollow?

### ISSUE THREAD

**Issue by itsmejamie** [instabot-py/instabot.py#2343]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Operating System? (include version)
- [X] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
3.7

```

#### Pip Version?
Pip 3
```

#### Description of your issue

I've installed the latest update and can get it to run with comments and tags that I want, but the bot doesn't seem to be unfollowing anyone, even when I ramp up the unfollow number. Ive got my unfollow number in an instabot.config.yml file. I'd like to be able to unfollow but also use the unfollow whitelist.
```

#### Config

---
tag_list: [ 'top_portraits', 'discoverportrait', 'life_portraits', 'makeportrait']
login : ""
password : ""
debug: 0
follow_time: 604800
like_per_day: 500
comments_per_day: 50
max_like_for_one_tag: 36
follow_per_day: 200
unfollow_time: 36000
unfollow_per_day: 5000
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false
comment_list:
- - Amazing
  - Killer
  - Awesome
  - Great
  - Fantastic
  - A really cool
  - Cool
  - Such a killer
  - Dope
  - What a dope
- - shot
  - pic
  - image
- - .
  - '!'
  - '!!'
  - '!!!'
  - '🔥'
  - '👌'
  - '🔥🔥🔥'
unfollow_whitelist:[]

**Comment by itsmejamie** [comment]
Update, I changed my unfollow per day to 502 (so not ending in 00) and that seems that have made it work better!

**Comment by yurilaaziz** [comment]
please close the issue if it works for you

**Comment by panwyll** [comment]
I've got the same issue using these commands:


 `instabot-py --login <MY_USER> --password <MY_PASS> --unfollow-per-run 102 --unfollow-everyone True --follow-time 10`

**Comment by itsmejamie** [comment]
@panwyll 

I recommend following the instructions on the open issue

#2332 instabot database issue (new download) 

Thats how I set mine up.
