### ISSUE TITLE
[Feature Request] Play sound when action is blocked

### ISSUE THREAD

**Issue by manguszta** [instabot-py/instabot.py#2348]
####
- [x] I have searched for other issues with the same problem or similar feature requests. 

####
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

####
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ ] If so, have you tried running the code on your local machine?

####
- [ ] macOS
- [x] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

####
- [x] I am using Python 3.6 or above

####
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [x] example.py (Deprecated, please install newer version) 

#### Description of your issue
Hi! I'm running 4 accounts, after API has changed, I started running 2 in my workplace, 2 at home. I noticed I'm getting action blocks almost daily, but with a password reset the bot runs perfectly on the account which was blocked.
I was thinking - we need some kind of notification, that we hit an action block, but Python runs in the background, there could be hours until I notice that my bot is not liking and/or following.
I don't know Python's possibilities, but wouldn't it be nice that it played some kind of pop-up sound when this happens? I could examine what's wrong immediately, and terminate the bot that is failing to do actions.

**Comment by eduardoegos** [comment]
you can do it with one line of code, really, using winsound. idk where the error handling code is, but just add this line to it, replacing file.wav with you sound file actual name:

winsound.PlaySound('file.wav', winsound.SND_FILENAME)

**Comment by nickgryg** [comment]
Starting from version `0.7.15` if any of actions have been blocked, bot stops at once with appropriate message with the reason of it.
