### ISSUE TITLE
configuration not working

### ISSUE THREAD

**Issue by JesuTinto** [instabot-py/instabot.py#2349]
instabot-py -c el.yml 

[dark@localhost-live instabot.py-master]$ instabot-py -c your-config.yml 
You didn't provide your Instagram login & password or you didn't specify the configuration file
Try again :

   instabot-py --login YOUR_LOGIN --password YOUR_PASSWORD
   instabot-py -c your-config.yml
You can export and modify the default configuration by typing the command below
    instabot-py --dump
[dark@localhost-live instabot.py-master]$ instabot-py -c el.yml 
You didn't provide your Instagram login & password or you didn't specify the configuration file
Try again :

   instabot-py --login YOUR_LOGIN --password YOUR_PASSWORD
   instabot-py -c your-config.yml
You can export and modify the default configuration by typing the command below
    instabot-py --dump

**Comment by vinilvasani** [comment]
I'm facing the same issue

**Comment by DRXDesign** [comment]
Same problem 
and the config.ini file doesn't show up

**Comment by Mehranp** [comment]
Same Problem
i setup on windows but config file doesnt show up and i cant change settings such as Tag , Comment and .... plz help me

**Comment by Woonohyo** [comment]
Same problem here.
I guess instabot-py cannot read configuration file containing NON-ASCII characters.
I resolved it by input encoded UTF-8 instead using website below.
http://coderstoolbox.net/string/#!encoding=url&action=encode&charset=utf_8

**Comment by ttuhin123** [comment]
> Same problem here.
> I guess instabot-py cannot read a configuration file containing NON-ASCII characters.
> I resolved it by input encoded UTF-8 instead using website below.
> http://coderstoolbox.net/string/#!encoding=url&action=encode&charset=utf_8
> 
> ex)
> 테스트 -> %ED%85%8C%EC%8A%A4%ED%8A%B8%0A

Absolutely.It cannot read NON-ASCII characters.

**Comment by terzano** [comment]
Make sure the indentation of the YAML config is proper. Please provide sample

**Comment by yurilaaziz** [comment]
this issue is related to config42 library that cannot read configuration with non ASCII.
I will fix the config lib

**Comment by ttuhin123** [comment]
> this issue is related to config42 library that cannot read configuration with non ASCII.
> I will fix the config lib

Its not fixed yet, I tried today.
