### ISSUE TITLE
myconfig.yml vs default_config.py

### ISSUE THREAD

**Issue by Elektrokid1** [instabot-py/instabot.py#2352]
I ask some help !
the bot is running on the default settings on **default_config .py** so he like "cat dog and car" 
<img width="709" alt="Screenshot 2019-08-09 at 23 37 21" src="https://user-images.githubusercontent.com/52871117/62810698-15ff7200-baff-11e9-95b5-14bab4274f13.png">
<img width="707" alt="Screenshot 2019-08-09 at 23 36 48" src="https://user-images.githubusercontent.com/52871117/62810705-1bf55300-baff-11e9-8414-343d3a685a0b.png">
 so ive create **myconfig.yml** , everything is fine but My question is ..... where are the comments , tag list , black list etcetera ... ive missed someting ? 

can someone make an updated tutorial to "how to edit myconfig.yml" 

because I'm lost and I think I'm not the only one 

Thanks

_Originally posted by @Elektrokid1 in https://github.com/instabot-py/instabot.py/issues/2342#issuecomment-520074638_

**Comment by DRXDesign** [comment]
You can add them yourself
`tag_list: []`

**Comment by mbe9477** [comment]
I got the same problem @DRXDesign ....
I've modified myconfig.yml and ran the bot with this command:
instabot-py --login MY_LOGIN  --password MY_PASSWORD
but it still likes "cat" tagged pics. (I truely removed "cat" from the tag list!)
This latest change is really confusion to me as I am no expert in this stuff ;)

**Comment by Elektrokid1** [comment]
Solved for me Thanks

**Comment by rickyrosso** [comment]
> Solved for me Thanks

How? Thanks

**Comment by Elektrokid1** [comment]
just use the myconfig.yml and pimp it like your old congfig.ini.

add line like below existing one
tag_list: [“x1”, “x2”, .. ]
withe_list: [“x1”, “x2”, .. ]
black_list: [“x1”, “x2”, .. ]
....

easy ;)

**Comment by mbe9477** [comment]
> I use this command line to launch the bot after created the virtual env
> 
> " python3 -m instabot_py -c myconfig.yml " bot start with your .yml
> 
> easy ;)

When I do this command, this happens to me...

`Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/xxx/Desktop/instabot-august2019/instabot_py/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/xxx/Desktop/instabot-august2019/instabot_py/instabot.py", line 72
    self.user_agent = Mozilla/5.0 (iPhone; CPU iPhone OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Mobile/15E148 Safari/604.1, 1)[0]
                                         ^
SyntaxError: invalid syntax
`

Any idea what's now wrong?

**Comment by Elektrokid1** [comment]
No sorry, my bot run on a Rasp3 maybe start from scratch following this medium post ?
https://medium.com/@asker_amine/whats-new-in-the-instagram-bot-0-5-2-fe52154fdc8a

Good Luck
