### ISSUE TITLE
Invalid Synthax

### ISSUE THREAD

**Issue by mbe9477** [instabot-py/instabot.py#2355]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ ] If so, have you tried running the code on your local machine?

```
Running on MacOS 10.14.6

```
#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
Darwin marc-iMac-2.fritz.box 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
3.7.3
```

#### Pip Version?
```
19.0.3
```

#### Instabot Version?
```
0.5.7
```

#### How you use the instabot
- [x] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 


#### Description of your issue

```
I've copied the sample config file and adjusted the settings such as likes, tags, follow per day and so on. When I start the bot with:
python3 -m instabot_py -c marc.yml
the below error appears in terminal 

> (venv) marc-iMac-2:instabot_NEW marc$ python3 -m instabot_py -c marc.yml
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 183, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 142, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 109, in _get_module_details
>     __import__(pkg_name)
>   File "/Users/marc/Desktop/instabot_NEW/instabot_py/__init__.py", line 1, in <module>
>     from .instabot import InstaBot
>   File "/Users/marc/Desktop/instabot_NEW/instabot_py/instabot.py", line 72
>     self.user_agent = Mozilla/5.0 (iPhone; CPU iPhone OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Mobile/15E148 Safari/604.1, 1)[0]
>                                          ^
> SyntaxError: invalid syntax

The bot only runs with: 
`instabot-py --login XXX --password XXX`
but it does no use all settings I need. Only liking specified tags!
```

#### Config

```

> accept_language: en-US,en;q=0.5
> ban_sleep_time: 10800
> comment_list:
> - - great
>   - super
>   - good
>   - very good
>   - good
>   - wow
>   - WOW
>   - cool
>   - GREAT
> - - .
>   - ..
>   - '...'
>   - '!'
>   - '!!'
>   - '!!!'
> comments_per_day: 50
> comments_per_run: '{{comments_per_day}}'
> config:
>   file: instabot2.config.yml
> database:
>   connection_string: sqlite:///{{database.path}}
>   path: '{{login}}.db'
>   type: sql
> debug: 0
> dump_configuration: false
> end_at_h: 0
> end_at_m: 59
> error_400_to_ban: 3
> follow_per_day: 50
> follow_per_run: 0
> follow_time: 18000
> follow_time_enabled: true
> like_per_day: 600
> like_per_run: 600
> list_of_ua:
> - Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.6.01001)
> - Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.7.01001)
> - Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.5.01003)
> - Mozilla/5.0 (Windows NT 6.1; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0
> - Mozilla/5.0 (X11; U; Linux x86_64; de; rv:1.9.2.8) Gecko/20100723 Ubuntu/10.04 (lucid)
>   Firefox/3.6.8
> - Mozilla/5.0 (Windows NT 5.1; rv:13.0) Gecko/20100101 Firefox/13.0.1
> - Mozilla/5.0 (Windows NT 6.1; WOW64; rv:11.0) Gecko/20100101 Firefox/11.0
> - Mozilla/5.0 (X11; U; Linux x86_64; de; rv:1.9.2.8) Gecko/20100723 Ubuntu/10.04 (lucid)
>   Firefox/3.6.8
> - Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; .NET CLR 1.0.3705)
> - Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)
> - Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727;
>   .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)
> - Opera/9.80 (Windows NT 5.1; U; en) Presto/2.10.289 Version/12.01
> - Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727)
> - Mozilla/5.0 (Windows NT 5.1; rv:5.0.1) Gecko/20100101 Firefox/5.0.1
> - Mozilla/5.0 (Windows NT 6.1; rv:5.0) Gecko/20100101 Firefox/5.02
> - Mozilla/5.0 (Windows NT 6.0) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/13.0.782.112
>   Safari/535.1
> - Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows NT 5.0) Opera 7.02 Bork-edition
>   [en]
> log_mod: 0
> logging:
>   disable_existing_loggers: false
>   formatters:
>     simple:
>       format: '%(asctime)s - {{login}} - %(name)s - %(levelname)s - %(message)s'
>   handlers:
>     console:
>       class: logging.StreamHandler
>       formatter: simple
>       level: DEBUG
>       stream: ext://sys.stdout
>   loggers:
>     InstaBot:
>       handlers:
>       - console
>       level: DEBUG
>       propagate: 'no'
>     Persistence:
>       handlers:
>       - console
>       level: DEBUG
>       propagate: 'no'
>   root:
>     level: INFO
>   version: 1
> max_like_for_one_tag: 5
> tag_list: [“XXX”, “XXX”, "XXX", "XXX"; "XXX"]
> withe_list: []
> black_list: []
> media_max_like: 150
> media_min_like: 0
> proxies: {}
> session_file: '{{login}}.session'
> start_at_h: 6
> start_at_m: 30
> tag_blacklist: []
> tag_list:
> - XXX
> - XXX
> - XXX
> - XXX
> time_till_unlike: 259200
> unfollow_break_max: 30
> unfollow_break_min: 15
> unfollow_everyone: false
> unfollow_inactive: true
> unfollow_not_following: true
> unfollow_per_day: 0
> unfollow_per_run: 0
> unfollow_probably_fake: true
> unfollow_recent_feed: true
> unfollow_selebgram: false
> unfollow_whitelist: []
> unlike_per_day: 0
> unlike_per_run: 0
> unwanted_username_list: []
> user_blacklist: {}
> user_max_follow: 0
> user_min_follow: 0
> window_check_every: 300
> 

```

**Comment by yurilaaziz** [comment]
you should specify the configuration file by typing -c

**Comment by mbe9477** [comment]
I did... See above :)

> python3 -m instabot_py -c marc.yml

**Comment by yurilaaziz** [comment]
add quotes to strings, (user agents )

**Comment by mbe9477** [comment]
Thanks that you try to help me. 
But I didn’t catch it ;)
