### ISSUE TITLE
use arabic/farsi charecter for tag_list

### ISSUE THREAD

**Issue by MostafaEwig** [instabot-py/instabot.py#2360]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ ] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [x] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
3.6.8
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
19
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Instabot Version?
```
Include here the response of 'instabot-py --version'
latest

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [X] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 


#### Description of your issue

i want to use arabic/farsi charecter for tag_list
in deparetd version i have no problem with utf-8 charecter for tag list
what should i do?
my tag list:
['کباب', 'غذا', 'سالاد', 'جوجه']

Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Ensure that you specify the configuration file in the command line.
Ensure that the default file instabot.config.yml contains only common settings if you use multiple accounts.
Include the contents of your config here (instabot-py -c config.yml --dump) (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT

```

**Comment by yurilaaziz** [comment]
include the error content please

**Comment by ghostmcf** [comment]
> include the error content please


2019-08-23 01:35:33,695 - ********* - InstaBot - ERROR - Expecting value: lin
e 1 column 1 (char 0)
Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\site-packages\instabot_py\instabo
t.py", line 500, in get_media_id_by_tag
    all_data = json.loads(r.text)
  File "c:\program files (x86)\python37-32\lib\json\__init__.py", line 348, in l
oads
    return _default_decoder.decode(s)
  File "c:\program files (x86)\python37-32\lib\json\decoder.py", line 337, in de
code
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\program files (x86)\python37-32\lib\json\decoder.py", line 355, in ra
w_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "c:\program files (x86)\python37-32\lib\runpy.py", line 193, in _run_modu
le_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python37-32\Scripts\instabot-py.exe\__main__.py",
 line 9, in <module>
  File "c:\program files (x86)\python37-32\lib\site-packages\instabot_py\__main_
_.py", line 304, in main
    bot.mainloop()
  File "c:\program files (x86)\python37-32\lib\site-packages\instabot_py\instabo
t.py", line 751, in mainloop
    self.logger.debug(f"Retrieved {len(medias_raw)} medias")
TypeError: object of type 'NoneType' has no len()





this happens on arabic/farsi tags (UTF-8)

**Comment by payanthe** [comment]
@yurilaaziz Its All about encoding from reading config file .
I tried This
   self.tag_list = config.get("tag_list")
   self.tag_list = ["هیجان"]
and it worked good.
