### ISSUE TITLE
media_min_like / media_max_like doesn't work

### ISSUE THREAD

**Issue by F4bri92** [instabot-py/instabot.py#2362]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
Raspberry Pi Zero
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [x] Linux (archlinux-arm)
- [ ] Android (include terminal)

```
Linux pi 4.19.37-1-ARCH #1 SMP PREEMPT Wed May 1 00:35:16 UTC 2019 armv6l GNU/Linux
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.3
```

#### Pip Version?
```
pip 19.2.1 from /usr/lib/python3.7/site-packages/pip (python 3.7)
```

#### Instabot Version?
```
Installed version 0.5.7
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [x] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
media_min_like and media_max_like are ignored, either passing parameters from the yml configuration file or using command line arguments
```

#### Config

```
login : (removed)
password : (removed)
debug: 0
follow_time: 0
like_per_day: 550
comments_per_day: 0
max_like_for_one_tag: 10
media_min_like: 100
media_max_like: 250
tag_list:
- (removed)
follow_per_day: 0
follow_time: 0
unfollow_per_day: 0
unfollow_break_min: 0
unfollow_break_max: 0
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: false
unfollow_recent_feed: false

```

**Comment by yurilaaziz** [comment]
the last update fixes this , please update

**Comment by F4bri92** [comment]
Updated to latest version but I still have this bug
