### ISSUE TITLE
How do I get it to stop liking cat pictures?

### ISSUE THREAD

**Issue by sora592** [instabot-py/instabot.py#2364]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ ] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [ ] macOS
- [x ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Instabot Version?
```
Include here the response of 'instabot-py --version'
```

#### How you use the instabot
- [x ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [x ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue
How on Earth can I get the bot to like something other than cars, cats, and dogs? I've tried modifying the default yml file, and I've tried making my own. I even tried modifying the default config Python file to use the tags I want. Nothing works, and cats, dogs, and cars still reign supreme.
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Ensure that you specify the configuration file in the command line.
Ensure that the default file instabot.config.yml contains only common settings if you use multiple accounts.
Include the contents of your config here (instabot-py -c config.yml --dump) (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT

```

**Comment by pavensharma** [comment]
I'm getting the same issue - it's ignoring custom config yml file and reverting to the default one. Would appreciate any help or pointers as I've tried everything and also looked at the tutorial too.

**Comment by maloklori** [comment]
same here... tried to set custom config yml file, turned out returning the file instead of loading it...

**Comment by sora592** [comment]
The cause of the issue, discovered after experiment, is that we're putting the .yml file in the wrong directory. Which directory is it? I don't know. I pasted it in every single one and it worked - sometimes, but not all the time.

**Comment by onerfusion** [comment]
I know most of you guys don’t use termux but maybe this guide will help ya

https://telegra.ph/Instabot-py-057-Tutorial-on-Termux-Android-08-12

**Comment by sora592** [comment]
I'm comfortable with Termux and powershell (Windows, which is what I'm running this script on). No, I think the problem is the directories.

**Comment by pavensharma** [comment]
> I know most of you guys don’t use termux but maybe this guide will help ya
> 
> https://telegra.ph/Instabot-py-057-Tutorial-on-Termux-Android-08-12

This tutorial worked for me (it's not liking the cat tags) and  I ran it on my mac instead of andorid. Will try raspberry pi later.

Thanks!!
