### ISSUE TITLE
Error After Success Login

### ISSUE THREAD

**Issue by Mehranp** [instabot-py/instabot.py#2365]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [x] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [ ] macOS
- [x] Windows 10
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Instabot V
![Error](https://user-images.githubusercontent.com/42107280/62914884-7dd7e600-bda7-11e9-8ffc-19f31fa188ed.png)
ersion?
```
Include here the response of 'instabot-py --version'
```

#### How you use the instabot
- [x] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue
Helow Guys ,
After working for a few momentsThe attached Error is displayed.
what's wrong ?
plz help me

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

---
login : ""
password : ""
debug: 1
follow_time: 604800
like_per_day: 250
comments_per_day: 30
max_like_for_one_tag: 36
follow_per_day: 150
follow_time: 36000
unfollow_per_day: 100
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false
tag_list: ["raghs_irani", "raghs", "varzesh", "eshgh", "eshgham", "mashin", "tehran_iran", "tehranparty", "tehranluxury", "tehranfashion", "tehrani", "tehrantattoo", "tehrangardi", "lebasmajlesi", "lebasaroos", "lebasshab", "mezon", "ahang", "khandeh", "ghaza", "tabriz", "esfahan", "shiraz", "shomal", "refigh", "doost", "dokhtar", "pesar", "mard", "zan", "mosaferat", "yas", "hichkas", "zedbazi", "ho3ein"]
comment_list: [["Perfect", "Awli", "Mofid", "Jaleb", "Shik", "Bahal", "Bi Nazir", "Kheyli Khub", "Kheyli Bahal", "Ziba", "Shik", "Kheyli Awli"], ["Bood!", "Bood!!", "Bood!!!", "Bood!!!!"], ["Az Ma ham Didan Konid <3", "Be Ma Ham Sar Bezanid <3", "Be Page Ma Ham Sar Bezanid <3", "Az Page Ma Ham Didan Konin <3"], [":)", ":) :)", ":) :) :)"], [".", "...", "!", "!!"]]

```
Ensure that you specify the configuration file in the command line.
Ensure that the default file instabot.config.yml contains only common settings if you use multiple accounts.
Include the contents of your config here (instabot-py -c config.yml --dump) (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT

```

**Comment by nickgryg** [comment]
This is very outdated issue. If you still have it, please use instabot-py version 0.5.20 or later.
