### ISSUE TITLE
Bring Back that Nice UI

### ISSUE THREAD

**Issue by ghostmcf** [instabot-py/instabot.py#2366]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [X] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] Are you running the code on your phone 
- [X] If so, have you tried running the code on your local machine?

```
Im running the bot on Windows , Kali , termux
``

#### Operating System? (include version)
- [ ] macOS
- [X] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [X] Linux (include flavour)
- [X] Android (include terminal)


#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
```
3.7
```

#### Pip Version?
```
19.2.1
```

#### Instabot Version?
```
0.5.9
```

#### How you use the instabot
- [X] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 


#### Description of your issue

```
Truly its hard to work with this type . please improve the UI or return the old one cause on of your bot's great feature was its simple-to-work UI . currently i didnt see any manual guid to use your new version . its a problem dude . 
put releases.
Update the README.
```

#### Config

```

```

**Comment by eduardoegos** [comment]
i second that. the nice thing about previous version was that i had an individual file for each account i had (as in the deprecated example.py), that i could just double click and start running

**Comment by onerfusion** [comment]
There is one manual guide he posted was this and it seems to be working if u don’t put location in tags and emoticons on comments 

instabot-py --dump > myconfig.yml
