### ISSUE TITLE
I'm still getting error with config.yml 

### ISSUE THREAD

**Issue by JesuTinto** [instabot-py/instabot.py#2367]
aaron@love:~/Downloads/instabot.py-master$ instabot-py -c el-config.yml 
You didn't provide your Instagram login & password or you didn't specify the configuration file
Try again :

   instabot-py --login YOUR_LOGIN --password YOUR_PASSWORD
   instabot-py -c your-config.yml
You can export and modify the default configuration by typing the command below
    instabot-py --dump

**Comment by iammoez** [comment]
same issue happened with me.

**Comment by rickyrosso** [comment]
same issue

**Comment by maxhoer** [comment]
same issue

**Comment by pavensharma** [comment]
- First create a configuration file per account that contains the Common configuration (config.file) and account credentials (login & password)

content of account1.yml
config.file: myconfig.yml
login: YOUR_LOGIN_ACCOUNT_1
password: YOUR_PASSWORD_1

- Then: instabot-py -c account1.yml 

This sort of works for me, as I'm able to log in but it doesn't seem to connect to my customised  config yml file.

**Comment by iammoez** [comment]
> * First create a configuration file per account that contains the Common configuration (config.file) and account credentials (login & password)
> 
> content of account1.yml
> config.file: myconfig.yml
> login: YOUR_LOGIN_ACCOUNT_1
> password: YOUR_PASSWORD_1
> 
> * Then: instabot-py -c account1.yml
> 
> This sort of works for me, as I'm able to log in but it doesn't seem to connect to my customised config yml file.
> 
> I used this post for help: https://medium.com/@asker_amine/whats-new-in-the-instagram-bot-0-5-2-fe52154fdc8aI have followed all the steps in this video .. i still getting the error 

instabot-py -c conifg.yml
You didn't provide your Instagram login & password or you didn't specify the configuration file
Try again :

   instabot-py --login YOUR_LOGIN --password YOUR_PASSWORD
   instabot-py -c your-config.yml
You can export and modify the default configuration by typing the command below
    instabot-py --dump

_______________________
am not familiar of creating a new config.file , could you please help . how we can do it . thank you very much

**Comment by pavensharma** [comment]
You dont have to create the config file yourself. Follow this tutorial, it works: 

https://telegra.ph/Instabot-py-057-Tutorial-on-Termux-Android-08-12

**Comment by iammoez** [comment]
> You dont have to create the config file yourself. Follow this tutorial, it works:
> 
> https://telegra.ph/Instabot-py-057-Tutorial-on-Termux-Android-08-12

am working on mac ((((

**Comment by shadynasrat** [comment]
got same issue here too working on mac 😕

**Comment by rickyrosso** [comment]
> You dont have to create the config file yourself. Follow this tutorial, it works:
> 
> https://telegra.ph/Instabot-py-057-Tutorial-on-Termux-Android-08-12

It doesn't work. It's incredible that I cannot use the Bot

**Comment by soulpawa** [comment]
> > You dont have to create the config file yourself. Follow this tutorial, it works:
> > https://telegra.ph/Instabot-py-057-Tutorial-on-Termux-Android-08-12
> 
> It doesn't work. It's incredible that I cannot use the Bot

I can use the bot using this:

instabot-py --login YOUR_LOGIN --password YOUR_PASSWORD

**Comment by iammoez** [comment]
> > > You dont have to create the config file yourself. Follow this tutorial, it works:
> > > https://telegra.ph/Instabot-py-057-Tutorial-on-Termux-Android-08-12
> > 
> > 
> > It doesn't work. It's incredible that I cannot use the Bot
> 
> I can use the bot using this:
> 
> instabot-py --login YOUR_LOGIN --password YOUR_PASSWORD

me to but am getting this error    

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: medias.id
[SQL: SELECT medias.id AS medias_id, medias.created AS medias_created, medias.status AS medias_status, medias.code AS medias_code 
FROM medias 
WHERE medias.id = ?]
[parameters: ('2112454986622099146',)]
(Background on this error at: http://sqlalche.me/e/e3q8)  


something wrong with the database i don't know how to fix that .. ( 
any suggestions ?

**Comment by soulpawa** [comment]
try this

https://github.com/instabot-py/instabot.py/issues/2270

**Comment by rickyrosso** [comment]
I want use Instabot with my personal config but after the command instabot-py -c namemyconfig.yml get this error:

You didn't provide your Instagram login & password or you didn't specify the configuration file
Try again :
instabot-py --login YOUR_LOGIN --password YOUR_PASSWORD
instabot-py -c your-config.yml
You can export and modify the default configuration by typing the command below
instabot-py --dump

**Comment by MassimoCastell** [comment]
Same issue here.

**Comment by JesuTinto** [comment]
I finally got it to work under FreeBSD and Linux. What I did was. To create each file with login credentials and password. But the only problem I’m having is that every time I logged in the bot only stay Connected for like 40 minutes, and then I get banned from Instagram until the next day. The old code was great, new code works fine, but still too glitchy. Hopefully the authors can work something out. To get a script, to do the configuration for you, ready to go. Well thank you all for reading out my  errors. And I hope I can see the code to get better.

**Comment by MassimoCastell** [comment]
How did you create them? If I "--dump" one and then try to use it with "-c" it doesn't work. I'm running it in a virtualenv in Ubuntu.

**Comment by monothorn** [comment]
this is most likely because you don't have a space between colon (:) and value for that property for some property :smile:

**Comment by MassimoCastell** [comment]
Probably. I copied the config file from the medium post and I repaired the Python virtual environment. Now it's working.

**Comment by manguszta** [comment]
Each of my .yml has their own login creditentials and configure
Works: `instabot-py -c myconfig1.yml -v`
Doesn't work: `instabot-py -c myconfig2.yml -v`
"You didn't provide your Instagram login & password or you didn't specify the configuration file"

**Comment by MassimoCastell** [comment]
I had this issue in my python virtual environment. Mine was corrupt. After repairing it, the problem was gone.
At the moment I am on mobile so I can't give you the way to repair it. But I found it here in the threads or on the medium post. Search here for the solution.

**Comment by JesuTinto** [comment]
> I had this issue in my python virtual environment. Mine was corrupt. After repairing it, the problem was gone.
> At the moment I am on mobile so I can't give you the way to repair it. But I found it here in the threads or on the medium post. Search here for the solution.

as you read, in the project main github. it was frozen. Now there is another project called neo instabot which is the same.

**Comment by nickgryg** [comment]
Version 0.5.19 has been released. Starting from this version it should be clear how to get config file, modify it and start the bot
