### ISSUE TITLE
Fix instabot please

### ISSUE THREAD

**Issue by JesuTinto** [instabot-py/instabot.py#2370]
Hi this is like my second, post about Reading the configuration files to run the bot.

aaron@love:~/Downloads/instabot.py-master$ instabot-py -c sample.instabot.config.yml 
You didn't provide your Instagram login & password or you didn't specify the configuration file
Try again :

   instabot-py --login YOUR_LOGIN --password YOUR_PASSWORD
   instabot-py -c your-config.yml
You can export and modify the default configuration by typing the command below
    instabot-py --dump

**Comment by onerfusion** [comment]
First dump the file with 

instabot-py --dump > myconfig.yml

Then put login details on yml

**Comment by JesuTinto** [comment]
> First dump the file with
> 
> instabot-py --dump > myconfig.yml
> 
> Then put login details on yml

aaron@love:~/instabot.py-master$ instabot-py --dump > instabot.config.yml 
aaron@love:~/instabot.py-master$ instabot-py -c instabot.config.yml 
You didn't provide your Instagram login & password or you didn't specify the configuration file
Try again :

   instabot-py --login YOUR_LOGIN --password YOUR_PASSWORD
   instabot-py -c your-config.yml
You can export and modify the default configuration by typing the command below
    instabot-py --dump

**Comment by onerfusion** [comment]
> > First dump the file with
> > instabot-py --dump > myconfig.yml
> > Then put login details on yml
> 
> aaron@love:~/instabot.py-master$ instabot-py --dump > instabot.config.yml aaron@love:~/instabot.py-master$ instabot-py -c instabot.config.yml
> You didn't provide your Instagram login & password or you didn't specify the configuration file
> Try again :
> 
> instabot-py --login YOUR_LOGIN --password YOUR_PASSWORD
> instabot-py -c your-config.yml
> You can export and modify the default configuration by typing the command below
> instabot-py --dump

u didn't put login details on YML file 
edit that instabot.config.yml file
2nd line put 
login: <Your login details>
3rd line: <your password>

and make dump_configuration: false

**Comment by andreagiugio** [comment]
> > > First dump the file with
> > > instabot-py --dump > myconfig.yml
> > > Then put login details on yml
> > 
> > 
> > aaron@love:~/instabot.py-master$ instabot-py --dump > instabot.config.yml aaron@love:~/instabot.py-master$ instabot-py -c instabot.config.yml
> > You didn't provide your Instagram login & password or you didn't specify the configuration file
> > Try again :
> > instabot-py --login YOUR_LOGIN --password YOUR_PASSWORD
> > instabot-py -c your-config.yml
> > You can export and modify the default configuration by typing the command below
> > instabot-py --dump
> 
> u didn't put login details on YML file
> edit that instabot.config.yml file
> 2nd line put
> login:
> 3rd line:
> 
> and make dump_configuration: false

Hello all,

sorry for reopening this thread.
Can you please explain me how to edit instabot.config.yml file using Termux for Android?
I am stuck.

Thanks in advance

**Comment by nickgryg** [comment]
Version 0.5.19 has been released. Starting from this version it should be clear how to get config file, modify it and start the bot

**Comment by paulnbrewer421** [comment]
> Version 0.5.19 has been released. Starting from this version it should be clear how to get config file, modify it and start the bot

sorry does this instaboot still work i just download the new version and t's so different than the old example file i have no idea how to set it up this time can you please provide me a link on how to set it up on mac, im pretty sure i have the latest python3 installed just not sure how to do the parameters
