### ISSUE TITLE
Bot stops after login

### ISSUE THREAD

**Issue by yfedorovsky** [instabot-py/instabot.py#2371]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

Running on Windows 10 in Command Prompt. Used to work fine, but now it errors out immediately after logging in. 

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
Python 3.7.3

#### Pip Version?
Pip 19.2.2

#### Instabot Version?
0.5.9

#### How you use the instabot
- [x] instabot-py -c instabot.config.yml
- [ ] instabot-py --login LOGIN --password PASSWORD

#### Description of your issue
Traceback (most recent call last):
  File "C:\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python37-32\lib\site-packages\instabot_py\__main__.py", line 308, in <module>
    main()
  File "C:\Python\Python37-32\lib\site-packages\instabot_py\__main__.py", line 294, in main
    bot = InstaBot(config=config)
  File "C:\Python\Python37-32\lib\site-packages\instabot_py\instabot.py", line 214, in __init__
    self.login()
  File "C:\Python\Python37-32\lib\site-packages\instabot_py\instabot.py", line 425, in login
    self.user_id = self.get_user_id_by_username(self.user_login)
  File "C:\Python\Python37-32\lib\site-packages\instabot_py\instabot.py", line 230, in get_user_id_by_username
    id_user = json_info["entry_data"]["ProfilePage"][0]["graphql"]["user"]["id"]
KeyError: 'graphql'

#### Config
accept_language: en-US,en;q=0.5
ban_sleep_time: 10800
comment_list: []
comments_per_day: 0
comments_per_run: '{{comments_per_day}}'
config:
  file: instabot.config.yml
database:
  connection_string: sqlite:///{{database.path}}
  path: '{{login}}.db'
  type: sql
debug: 0
end_at_h: 23
end_at_m: 59
error_400_to_ban: 3
follow_per_day: 0
follow_per_run: 0
follow_time: 18000
follow_time_enabled: true
like_per_day: 1500
like_per_run: 1500
list_of_ua:
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.6.01001)
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.7.01001)
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.5.01003)
- Mozilla/5.0 (Windows NT 6.1; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0
- Mozilla/5.0 (X11; U; Linux x86_64; de; rv:1.9.2.8) Gecko/20100723 Ubuntu/10.04 (lucid)
  Firefox/3.6.8
- Mozilla/5.0 (Windows NT 5.1; rv:13.0) Gecko/20100101 Firefox/13.0.1
- Mozilla/5.0 (Windows NT 6.1; WOW64; rv:11.0) Gecko/20100101 Firefox/11.0
- Mozilla/5.0 (X11; U; Linux x86_64; de; rv:1.9.2.8) Gecko/20100723 Ubuntu/10.04 (lucid)
  Firefox/3.6.8
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; .NET CLR 1.0.3705)
- Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)
- Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727;
  .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)
- Opera/9.80 (Windows NT 5.1; U; en) Presto/2.10.289 Version/12.01
- Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727)
- Mozilla/5.0 (Windows NT 5.1; rv:5.0.1) Gecko/20100101 Firefox/5.0.1
- Mozilla/5.0 (Windows NT 6.1; rv:5.0) Gecko/20100101 Firefox/5.02
- Mozilla/5.0 (Windows NT 6.0) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/13.0.782.112
  Safari/535.1
- Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows NT 5.0) Opera 7.02 Bork-edition
  [en]
log_mod: 0
logging:
  disable_existing_loggers: false
  formatters:
    simple:
      format: '%(asctime)s - {{login}} - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      level: DEBUG
      stream: ext://sys.stdout
  loggers:
    InstaBot:
      handlers:
      - console
      level: DEBUG
      propagate: 'no'
    Persistence:
      handlers:
      - console
      level: DEBUG
      propagate: 'no'
  root:
    level: INFO
  version: 1
login: [removed]
max_like_for_one_tag: 20
media_max_like: 100
media_min_like: 0
password: [removed]
proxies: {}
session_file: [removed].session
start_at_h: 0
start_at_m: 0
tag_blacklist: []
tag_list: []
time_till_unlike: 259200
unfollow_break_max: 30
unfollow_break_min: 15
unfollow_everyone: false
unfollow_inactive: true
unfollow_not_following: false
unfollow_per_day: 0
unfollow_per_run: 0
unfollow_probably_fake: true
unfollow_recent_feed: false
unfollow_selebgram: false
unfollow_whitelist: []
unlike_per_day: 0
unlike_per_run: 0
unwanted_username_list: []
user_blacklist: []
user_max_follow: 0
user_min_follow: 0
window_check_every: 300

**Comment by xi4** [comment]
Same problem. I use 4g poroxy

**Comment by Andy2903** [comment]
Same issue with the Raspberry Pi

**Comment by IsaackHazaell** [comment]
Same problem, someone knows the solution?

**Comment by canpoyrazoglu** [comment]
I have 3 accounts and this started happening randomly on one of them.

**Comment by heldausberlin** [comment]
Same here.

**Comment by parkzinc** [comment]
Same problem!

**Comment by nickgryg** [comment]
It is very outdated issue. If you still have it, please use instabot-py version 0.5.20 or later.
