### ISSUE TITLE
2 factor authentifcation issue

### ISSUE THREAD

**Issue by sterio123** [instabot-py/instabot.py#2379]
Dear all,

instaling the instabot is my first Raspberry Pi project, and programming is not my main domain of activity. 
Nevertheless, I have installed everything and due to the 2 factor authentification I only use the manual multis cript running the following comands: 
`cd /home/pi/instabot/examples`
`Python multi_script_CLI.Py`

When I run  `instabot-py -c myconfiguration.yml `, I get blocked by the 2 factor authentification. Is there any log in step that I might have missed? 

Thanks for your help!

**Comment by marcularis04** [comment]
Just disable the 2 step authentification, login with instabot, then re-enable it. You won't ever need to disable it again, unless you delete the .session file of instabot
