### ISSUE TITLE
Mouse movement detection

### ISSUE THREAD

**Issue by bboy519** [instabot-py/instabot.py#2383]
Device operations: information about operations and behaviors performed on the device, such as whether a window is foregrounded or backgrounded, or mouse movements (which can help distinguish humans from bots).

https://help.instagram.com/519522125107875

**Comment by dsmh** [comment]
This is very important, since with this information would be pretty easy to detect a bot.

**Comment by ProgrammingLife** [comment]
I think there are very low amount of people that use instagram in browser because of its restricted functionality. Most of people use mobile devices. So all browser-bots at potential risk.

**Comment by nickgryg** [comment]
`instabot-py` doesn't use browser to communicate with Instagram. Pure https requests are used here. So it is not possible to implement mouse movements etc.
