### ISSUE TITLE
7-day ban for likes.

### ISSUE THREAD

**Issue by nativecodeabuser** [instabot-py/instabot.py#2386]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [x] Other

#### Description of your issue

Be careful with your bots. Today after ~100 likes, no follows, no comments my account got action-banned for 7 days. 

> InstaBot - INFO - Not liked: 400 message {"message": "feedback_required", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "Your account has been temporarily blocked from taking this action. Sharing your account with a service that helps you get more likes or followers goes against our Community Guidelines. This block will expire on 2019-08-28. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/user_restriction_LIKE_RESTRICT/", "status": "fail"}

No, deleting the session file does not help and yes, ban is active across all devices.

**Comment by canpoyrazoglu** [comment]
There is nothing to do other than to wait for a week. Were you using the bot on a cloud instance or locally?

**Comment by nativecodeabuser** [comment]
I know. No biggie for me, just warning others. It might be worth noting that the message is different now than it used to be two weeks ago. I was running it from my local network (same IP as my other devices at home).

**Comment by Orange06** [comment]
I have 0 comments, 50 likes per day and it fails after 20-25mins of running every single time. I am so furious at myself that I've upgraded to this latest version.. With previous version, bot was running for more than a month with not a single error or "action not allowed" warning, and it was running on 5 different accounts - for more than a month - worked like a charm.. This version I cant get it to run for an hour... what a fucking waste..

**Comment by nativecodeabuser** [comment]
The above is not a standard "action not allowed" message. It's a temp, 7-day ban, not just a halt on single action that you could easily override. That is why I decided to warn other users in a separate topic.

**Comment by macd2** [comment]
@nativecodeabuser 
What you mean by: "not just a halt on single action that you could **easily override**. "

**Comment by pihomeserver** [comment]
> I have 0 comments, 50 likes per day and it fails after 20-25mins of running every single time. I am so furious at myself that I've upgraded to this latest version.. With previous version, bot was running for more than a month with not a single error or "action not allowed" warning, and it was running on 5 different accounts - for more than a month - worked like a charm.. This version I cant get it to run for an hour... what a fucking waste..

Same issue here. The script crashes after few minutes/hours. I will try to debug next days

**Comment by Orange06** [comment]
> 
> 
> The above is not a standard "action not allowed" message. It's a temp, 7-day ban, not just a halt on single action that you could easily override. That is why I decided to warn other users in a separate topic.

Would you please be so kind and enlighten us ? How do you "override" this ?

**Comment by H00kahMan** [comment]
Same problem, I used the bot for like 20 days or sth, follow,unfollow, and like. I recently got 3 days ban but idk how their algorithm works, I've been running the bot on local network, its so frustrating, getting banned out of nowhere.

**Comment by nativecodeabuser** [comment]
> How do you "override" this ?

If it's "action not allowed" then just delete session file and try again. If you got banned ("Your account has been temporarily blocked from taking this action") then there's nothing you can do.

**Comment by Orange06** [comment]
Anyone got idea why is this happening now ? Why did previous version work like a charm and this one cant ? What has changed ?

**Comment by pihomeserver** [comment]
The JSON parsing of the Instagram response seems to be different as the reply could not be parsed. I added some traces in a clone of the program and rerun it to understand what's the problem (new reply or different parsing). I will also check previous versions but i'm not a python expert

**Comment by giovannaparadiso80** [comment]
I don't know if  mine is the same issue  because  when I try to log in with the instabot the error message is the same,  but how can I be banned if I can normally like photos on the app?

**Comment by ProgrammingLife** [comment]
@nativecodeabuser @H00kahMan @pihomeserver @Orange06 
Hey, guys. Did you try to make such amount of likes but manually with your mobile phone using that instagram account? Is it allowed to do more likes count or it doesn't matter are you using a bot or you are doing such actions manually with your phone?

**Comment by H00kahMan** [comment]
@ProgrammingLife
Sorry for l8 reply, I never tested the limit but whenever I get that 'like problem: 400' or sth, I can manually like photos with phone. But I got a 3-day-action-ban recently, and I didn't use the both since. I dunno if I should try again but I don't wanna get banned permanently.

**Comment by ProgrammingLife** [comment]
@H00kahMan what limits do you used before the ban?

**Comment by pihomeserver** [comment]
@H00kahMan in my case was 3000 likes per day no follow and no comments, running hours from 7am to 11pm. The bot was running fine for few weeks and then IG started to reply 400 messages until i got the 3 days ban...
