### ISSUE TITLE
Can I press like only on people I follow?

### ISSUE THREAD

**Issue by lgs777** [instabot-py/instabot.py#2392]
Can I press LIKE only on people I follow?

I wonder if instabot offers this feature.

**Comment by nickgryg** [comment]
Yes, starting from version 0.5.15 you can like only photos of people you followed using instabot. It is "like_followers_per_run" config setting:

like_followers_per_run | int | Number of your old followers to like their last photo per day (set to 0 to disable) | 0
-- | -- | -- | --

**Comment by lgs777** [comment]
Thanks for the reply. But I want to press like on people I'm following, not people following me. Is this feature not supported?
