### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by tobskool** [instabot-py/instabot.py#2395]
> Hi. Most probably you can fix it with `pip install instaloader`.

Stephens-Macbook-Pro:~ stephenfayemi$ pip install instaloader
Requirement already satisfied: instaloader in ./anaconda3/lib/python3.7/site-packages (4.2.8)
Requirement already satisfied: requests>=2.4 in ./anaconda3/lib/python3.7/site-packages (from instaloader) (2.22.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./anaconda3/lib/python3.7/site-packages (from requests>=2.4->instaloader) (1.24.1)
Requirement already satisfied: idna<2.9,>=2.5 in ./anaconda3/lib/python3.7/site-packages (from requests>=2.4->instaloader) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./anaconda3/lib/python3.7/site-packages (from requests>=2.4->instaloader) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/lib/python3.7/site-packages (from requests>=2.4->instaloader) (2018.11.29)
Stephens-Macbook-Pro:~ stephenfayemi$ 

It has said that I have already installed it but when I run python, it says 'No module named 'instaloader'', help.

Also:

ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

how do I manually uninstall it then?

**Comment by milesdunkley** [comment]
yeah having the same problem. Why is this software so impossible to install?

**Comment by smolyakov26** [comment]
run as admin , it helped me
