### ISSUE TITLE
Executable shortcut file for new instabot-py 0.5.2

### ISSUE THREAD

**Issue by manguszta** [instabot-py/instabot.py#2397]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Feature Request

#### Operating System? (include version)
- [x] Windows

#### Description of your issue

Can you guys make a user-friendly executable batch file that people can use instead of typing in to command prompt? Running the example.py was so much easier. It was just a double click. But now I need to open cmd, FIND the folder of my instabot config files, and remember what to type in to run the bot.

**Comment by nickgryg** [comment]
Version 0.5.19 has been just released. Starting from this version it should be clear how to get config file, modify it and start the bot
