### ISSUE TITLE
0.5.10 will not start up, hangs with no logs

### ISSUE THREAD

**Issue by martygriffin** [instabot-py/instabot.py#2398]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ X] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
Raspberry Pi
- [ ] Are you running the code on your phone 
No
- [x ] If so, have you tried running the code on your local machine?
Yes, on a raspberry pi

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [X ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
Linux raspberrypi 4.19.58+ #1245 Fri Jul 12 17:20:08 BST 2019 armv6l GNU/Linux
```

#### Python Version Requirement
- [X ] I am using Python 3.6 or above

#### Exact Python Version?

3.6.5

#### Pip Version?
19.2.2

#### Instabot Version?

0.5.10

#### How you use the instabot
- [x ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

After upgrading to 0.5.10, instabot hangs at start up with no logs, no error log file.

#### Config

debug: 1
start_at_h: 7
start_at_m: 0
end_at_h: 19
end_at_m: 0
unfollow_per_run: 30
follow_per_run: 30
comments_per_day: 30
max_like_for_one_tag: 100
like_per_run: 150
follow_time: 86400
unfollow_selebgram: True
unfollow_probably_fake: True
unfollow_inactive: True
unfollow_recent_feed: False

logging.loggers.InstaBot.handlers:
  - console

tag_list: ["tavel", "tavelgram", "travelphotography", "tavelpics", "traveladdict", "travelblog"]
comment_list: [["","So"], ["Cool", "Awesome", "Sick", "Solid", "Righteous"], [".", "!", "!!", "!!!"]]

**Comment by nickgryg** [comment]
Version 0.5.12 has been just released. You can try it on your environment, just perform:
```
python3 -m pip install instabot-py --no-cache-dir --upgrade
```
