### ISSUE TITLE
Blocked (how do I fix or reduce comment/ add speed)

### ISSUE THREAD

**Issue by mcarlock12** [instabot-py/instabot.py#2399]
I'm blocked now, do we know how to slow the configuration down, i think mine is going too fast? can we do it in the default_config.py file? @zacharimayer @yurilaaziz

I posted this in another but no response. Im unblocked now but need to know how to prevent myself from getting blocked again?

**Comment by neok** [comment]
You can set `comments_per_day` or `comments_per_run`
