### ISSUE TITLE
More randomization in .yml config files

### ISSUE THREAD

**Issue by manguszta** [instabot-py/instabot.py#2400]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ ] If so, have you tried running the code on your local machine?
#### Description of your issue

Can we use RANDOM function in the .yml config files?
I believe this way the run of our algorhythms would not be easily detected as spamming.

#### Config

Like shown below:
```
start_at_h: 18
start_at_m: 30
end_at_h: 8
end_at_m: 0
like_per_run: 1998
max_like_for_one_tag: 100
follow_per_run: 450
follow_time: 12000
unfollow_per_run: 766

```
->

```
start_at_h: 18
start_at_m: random.randint(10, 50)
end_at_h: 8
end_at_m: random.randint(0, 30)
like_per_run: random.randint(1900, 2000)
max_like_for_one_tag: random.randint(50, 150)
follow_per_run: random.randint(300, 550)
follow_time: random.randint(10000, 14000)
unfollow_per_run: random.randint(600, 800)

```

**Comment by joe6ar** [comment]
Does it work?

**Comment by nickgryg** [comment]
Randomization has been added in version 0.5.18: #2482
