### ISSUE TITLE
Anyone able to run bot without getting detected for suspicious activity?

### ISSUE THREAD

**Issue by neospeed83** [instabot-py/instabot.py#2401]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [x] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] Are you running the code on your phone 
- [ ] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```
Termux
#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [x] Android (Termux)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.4
```

#### Pip Version?
```
pip 19.0.3
```

#### Instabot Version?
```
Not using it right now because I got detected.
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [x] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Ensure that you specify the configuration file in the command line.
Ensure that the default file instabot.config.yml contains only common settings if you use multiple accounts.
Include the contents of your config here (instabot-py -c config.yml --dump) (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT

```

**Comment by mrallanodreman** [comment]
Me, changing the user agent for my device user agent

**Comment by marrobHD** [comment]
How can I change it?

**Comment by marrobHD** [comment]
Can someone sent the best config

**Comment by neospeed83** [comment]
@mrallanodreman  What did you change it to?

**Comment by heldausberlin** [comment]
> Me, changing the user agent for my device user agent

@mrallanodreman may I ask you how you did it exactly? Which file and which line did you edit?

**Comment by mrallanodreman** [comment]
On instabot.py there a line only one with "list_of_ua" you have to delete it and put one mobile user agent web browser

**Comment by nickgryg** [comment]
Starting from version 0.5.15 it is possible to define User Agent in configuration file. It is  "user_agent" setting.
