### ISSUE TITLE
Telegram bot error

### ISSUE THREAD

**Issue by dikeckaan** [instabot-py/instabot.py#2405]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [x] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```
Linux ftp-sunucu 4.15.0-1040-gcp #42-Ubuntu SMP Wed Aug 7 15:17:54 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
(venv) 
#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```
Python 3.6.8
#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```
pip 19.2.3 from /home/atgafasi10/venv/lib/python3.6/site-packages/pip (python 3.6)
#### Instabot Version?
```
Include here the response of 'instabot-py --version'
```

#### How you use the instabot
- [x] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue
When i add telegram bot info in yaml it gives me error
logging.handlers.telegram:
  level: INFO
  class: telegram_handler.TelegramHandler
  token: 9*****0:A*************************************8
  chat_id: 3*******3
logging.loggers.InstaBot.handlers:
  - telegram
  - console
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Ensure that you specify the configuration file in the command line.
Ensure that the default file instabot.config.yml contains only common settings if you use multiple accounts.
Include the contents of your config here (instabot-py -c config.yml --dump) (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT

```

**Comment by nickgryg** [comment]
Project's documentation has been improved with the information how to create Telegram bot and how to send `instabot-py`'s logs into Telegram channel.
