### ISSUE TITLE
New Development Team

### ISSUE THREAD

**Issue by ohld** [instabot-py/instabot.py#2411]
Hi there! I saw you've stopped the development of instabot.py. 

We have a strong development team in our Open Source Instagram Hackers Organization https://github.com/instagrambot. And we would like to help. 

The only condition is to move your project from your GitHub organization (which has only one project) to ours (which has a lot of huge projects and participants already). All admins will remain all the rights they already have, we just unite all our forces, knowledge and traffic under one organization.

**Comment by neospeed83** [comment]
That's rude.

**Comment by Zettt** [comment]
At least show some decency, and write your own link correct.

**Comment by Zettt** [comment]
@ohld You're welcome. ;-)

**Comment by nikolasvargas** [comment]
good idea
