### ISSUE TITLE
How to change the user agent on Raspbian?

### ISSUE THREAD

**Issue by fuanegua** [instabot-py/instabot.py#2412]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
Linux Pi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.5.3
```

#### Pip Version?
```
pip 19.2.3
```

#### Instabot Version?
```
Include here the response of 'instabot-py --version'
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [x] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

I would like to change the user agent on my Raspberry Pi (Raspbian). And I really don’t know where to find the userinfo.py. Can anybody please help me and tell me the exact path and file? Thanks a lot.

**Comment by nickgryg** [comment]
It is possible to install custom User Agent since version 0.5.15. It is 'user_agent' variable in a configuration file.
