### ISSUE TITLE
Could not find user in settings. Would you like to add now?

### ISSUE THREAD

**Issue by canpoyrazoglu** [instabot-py/instabot.py#2421]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ ] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [x] macOS (10.15)
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```
Darwin can-mbp.local 19.0.0 Darwin Kernel Version 19.0.0: Tue Sep 17 01:59:51 PDT 2019; root:xnu-6153.11.24~17/RELEASE_X86_64 x86_64

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.4
```

#### Pip Version?
```
pip 19.0.3
```

#### Instabot Version?
```
Not applicable, can't check, read below.
```

#### How you use the instabot
- [x] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
I used to have an older version of instabot, I removed it. Then, I followed the Medium post to install: https://medium.com/@asker_amine/whats-new-in-the-instagram-bot-0-5-2-fe52154fdc8a (I've initially tried the official installation at repo readme but didn't work either)

 I've set up a virtual environment, installed instabot. Then I've created a config file as I've pasted into the `Config` section below. (obviously, in the real file I have my login and password correct and have tags that make sense)

I'm inside the virtualenv, cd to the directory with the config file and run:

`instabot-py`
or
`instabot-py -c instabot.config.yml`

But I get the configurator screen saying ` Config file does not exist. Would you like to setup now? (yes/no)`.

I've also tried creating it interactively, then ran instabot again and it also landed to the same place as if I haven't run the configurator anyway.

In addition, when I type `instabot-py --version` I also get to the configurator, instead of printing the version, so I can't check for the version either.

What am I doing wrong?

```

#### Config

```
---
tag_list: ['some', 'tags', 'come', 'here']
login : "xxx"
password : "xxx"
follow_time: 36000
unfollow_per_day: 200
follow_per_day: 400
like_per_day: 800
unlike_per_day: 100
```

**Comment by nicammazzalorso** [comment]
Having the same issue with no luck fixing it yet

**Comment by hushv01** [comment]
same issue here. Any help appreciated.

**Comment by loganyc1934** [comment]
Same. Whenever I type `instabot-py --xxx` it asks me for user setting again. 

For example

```
instabot-py --login xxx --password xxx
```

I already went through that process and have setting in `instabot.config.ini`, I see the settings there, but it can't tell. Even `instabot-py --help` leads to setting up user settings. So

1. The help message for this cli tool isn't properly set.
2. The mechanism to check user setting is broken.

I can get it to work with just `instabot-py` with no param but I would like to run it in the background with something like `nohup instabot-py &`. This gives error

```
INFO:instabot_py.config:Setting configuration from instabot.config.yml : OK
Traceback (most recent call last):
  File "/home/pi/Web/insta/venv/bin/instabot-py", line 8, in <module>
    sys.exit(main())
  File "/home/pi/Web/insta/venv/lib/python3.7/site-packages/instabot_py/__main__.py", line 392, in main
    configdict = interactive()
  File "/home/pi/Web/insta/venv/lib/python3.7/site-packages/instabot_py/__main__.py", line 328, in interactive
    prepend="@",
  File "/home/pi/Web/insta/venv/lib/python3.7/site-packages/instabot_py/__main__.py", line 34, in ask_question
    with TERM.location(int((TERM.width / 2) - (len(header) / 2)), 1):
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

**Comment by loganyc1934** [comment]
Got around it by installing from source. Apparently I got a non-working version from the initial `pip install`. Check https://github.com/instabot-py/instabot.py/issues/2314#issuecomment-548610782

**Comment by nickgryg** [comment]
Version 0.5.19 has been just released. Starting from this version it should be clear how to get config file, modify it and start the bot
