### ISSUE TITLE
Manual User Agent

### ISSUE THREAD

**Issue by Leo675** [instabot-py/instabot.py#2426]
I think some traffic is being flagged suspicious due to user agent.

Using a random user agent does not seem to be a good choice. It would be good to manually set the user agent without having to change code in `instabot_py/instabot.py`

I can work on getting a url on a my instagram that would show you your user agent of the actual app. I believe it actuall does say instagram in the UA string along with phone model/os version.

**Comment by elmissouri16** [comment]
this API built based on the web version of Instagram so its need web browser ua, not the app ua

**Comment by Leo675** [comment]
> this API built based on the web version of Instagram so its need web browser ua, not the app ua
ohhh interesting

**Comment by mrallanodreman** [comment]
Very very very interesting!!!! i was thinking the same " i need simulate the user agent of the app to proyect the human behavior" but i didnt remember that the bot is based on the webbroser version of instagram.

**Comment by elmissouri16** [comment]
> 
> 
> Very very very interesting!!!! i was thinking the same " i need to simulate the user agent of the app to project the human behavior" because even when i change the user agent, instagram recognize the activity from windows... and no from any phone how i tried, however we have to fix this!

use for example chrome ua of android but thats not the issue of the bot , the issue is how its do actions , for example when you do like its simply send HTTP request of like its to ignore all the steps before thats human do thats the main issue

**Comment by mrallanodreman** [comment]
you have to see others medias before like! for example for the geotags, see more medias in the same location before like, something like a buffering_medias with a randomizer!

**Comment by nickgryg** [comment]
It is possible to install custom User Agent since version 0.5.15. It is 'user_agent' variable in a configuration.
