### ISSUE TITLE
Not like 400 and not banned

### ISSUE THREAD

**Issue by boyboywow** [instabot-py/instabot.py#243]
Hi everyone,

I use instabot for long time and now I get this error.. The app arrives to like only 1 or 2 media the other I get this message "Not liked: 400".

I have two account and it's exactly the same and I'm not banned I can like.

**Comment by polaroi8d** [comment]
> 400 Bad Request

The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modifications.

**Comment by LevPasha** [comment]
@boyboywow look like ban.

**Comment by hanoncs** [comment]
FYI: I had this issue just now on a brand new account. Turned out that the link in my profile was not allowed. After removing it, I was able to like right away from the bot.

**Comment by testinghack** [comment]
@hanoncs What do you mean by the link on your profile, I did not understand how you fixed the issue, as I have a similar one.

**Comment by faboviral** [comment]
me pasa lo mismo no me corre, cuando va ejecutarce inicia seccion y sale un error (not like 400) y no se como repararlo

**Comment by hanoncs** [comment]
Not sure why I was voted down for a tip.

@testinghack  I had a link in my Instagram profile. As soon as you place a link in your profile, Instagram automatically crawls the site and checks if they think its malicious. If yes, they 400 you until you remove the link in your profile. Once I removed it, I stopped getting the 400 errors.

**Comment by CamiloB** [comment]
@hanoncs hi i already delete the  link of the profile and still got the not like 400

**Comment by ugurozturk** [comment]
use https://github.com/instabot-py/instabot.py/issues/887 for tracking in the future
