### ISSUE TITLE
YOUR `LIKE` ACTION IS BLOCKED

### ISSUE THREAD

**Issue by findios69** [instabot-py/instabot.py#2430]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ x] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ x] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ x] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```
4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

#### Python Version Requirement
- [ x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```
Python 3.6.8

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```pip 9.0.1

#### Instabot Version?
```
Include here the response of 'instabot-py --version'
```
Installed version 0.5.9

#### How you use the instabot
- [x ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

Hello I keep getting blocked from liking pictures, in multiple accounts, is there a work around like using a proxy that i should be using? How is instagram able to detect this activity all of the sudden? It was fine for years.

```
InstaBot - INFO - Could not like media: id: 2151650428465688754, url: https://www.instagram.com/p/B3cMqotg7Cy/. Reason: {"message": "feedback_required", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/instagram_like_add/", "status": "fail"}
```

#### Config

```
Ensure that you specify the configuration file in the command line.
Ensure that the default file instabot.config.yml contains only common settings if you use multiple accounts.
Include the contents of your config here (instabot-py -c config.yml --dump) (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT

```

**Comment by linkfy** [comment]
#2420 Check this, if you dont have problems with mobile hotspot data consumption maybe is the way to go.

**Comment by findios69** [comment]
I tried it, I still have the same problem

**Comment by fenau88** [comment]
i get the same problem

https://github.com/instabot-py/instabot.py/issues/2433

**Comment by algarih** [comment]
same issue here, any update ? could VPN solve this issue ?

**Comment by WindsofRose** [comment]
Same problem

**Comment by cala095** [comment]
same problem

**Comment by petrstepanov** [comment]
Same problem.

**Comment by gp187** [comment]
same

**Comment by LUF3N** [comment]
anyone got a fix?
