### ISSUE TITLE
return "feedback_required" is absent in API

### ISSUE THREAD

**Issue by Eran111** [instabot-py/instabot.py#2433]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [X] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [ ] macOS
- [X] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
```
3.7
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Instabot Version?
```
Include here the response of 'instabot-py --version'
```
0.68
#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [X] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
if something is blocked,
a "feedback_required" is not returned in the "api.py" file
this line is absent in newer versions of instabot but was exist in previous versions (0.54 for example as i saw):

```
![image](https://user-images.githubusercontent.com/32398770/66793538-7d261200-ef06-11e9-9b7d-a382ba18872b.png)

**Comment by mrallanodreman** [comment]
what means this?

**Comment by fenau88** [comment]
i get the same feedback error

**Comment by isorrentino** [comment]
I get the same feedback error!

**Comment by nickgryg** [comment]
This issue is very outdated. It should have been fixed many releases ago. Please update `instabot-py`to the latest version and check if this issue still exists.
