### ISSUE TITLE
Did I install the bot correctly? It seems so simple, and no YML file.

### ISSUE THREAD

**Issue by remyx11** [instabot-py/instabot.py#2434]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [X] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [X] If so, have you tried running the code on your local machine?

```
Just local on my mac.
```

#### Operating System? (include version)
- [X] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Instabot Version?
```
Instabot v1.2.5/0
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [X] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

So, i'd like to know if i did the install correctly. I was using the old version for over a year, without problems. I noticed a new version came out, but didn't bother, until that old version start saying "400" as an error.

Because of the error I tried to install the newer version. And im not sure if i did it the correct way because I see people talk about YML files and such which I don't have. And the bot seems to be working.

I simply just typed in my new Terminal window (just base directory) "pip install instabot-py" it did is thing and then i typed in "instabot-py --version" to see on what version I was, but it prompted me with a config editor inside Terminal (kind of neat). I went a head to fill in everything, I use the bot for liking only tbh. After that, I run the bot with "instabot-py", it asks which account and off it goes.

I just have a instabot.config.ini file in my /Users/Remy directory. Thats it. Which isn't a YML file where everybody talks about. Do I need that or will this work as well?

**Comment by remyx11** [comment]
Oke, nevermind. After 11 likes i get this error;

Not liked: 400 message {"message": "feedback_required", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/instagram_like_add/", "status": "fail"}

Sadly.

**Comment by alaintainguyen** [comment]
what is the solution to avoid that?

**Comment by remyx11** [comment]
I'd like to know that as well. Somehow the community seems gone lately, might be because of the bot not working.
