### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by pcj2** [instabot-py/instabot.py#244]
I havn't changed any code other than the user name and password. 
I am running mac, python 3. 
I am getting an invalid syntax error, pointing to the " character enclosing the username. 

It seems as though the two characters it likes the last are ' and "

**Comment by pcj2** [comment]
I am also getting random other errors such as the following,

File "example.py", line 3
    +import sys, os
    ^
IndentationError: unexpected indent

**Comment by polaroi8d** [comment]
Try simple `python`

**Comment by drewhga** [comment]
Which lines were highlighted in the traceback?

**Comment by maitrimarg** [comment]
Getting the same problem, also with python, it appears in line 14.
If anyone can suggest
