### ISSUE TITLE
Keeps Looping

### ISSUE THREAD

**Issue by JattHer01** [instabot-py/instabot.py#2440]
The Bot keeps on looping the commands and doesn't pull over any results I've tried doing everything but the bot keeps looping and I'm able to read an error which says "Unable to remove media".Please HELP me if anybody can.

**Comment by nickgryg** [comment]
Please update instabot to the latest version by performing ```python3 -m pip install --no-cache-dir --upgrade git+https://github.com/instabot-py/instabot.py``` and provide log output here.

**Comment by dankismylifestyle** [comment]
> Please update instabot to the latest version by performing `python3 -m pip install --no-cache-dir --upgrade git+https://github.com/instabot-py/instabot.py` and provide log output here.

For me it solved the Issue but now the bot does not recognize the instabot.config.yml file when I try to start the bot
