### ISSUE TITLE
like_medias_by_locaton.py - UnicodeEncodeError

### ISSUE THREAD

**Issue by pentalobebnu** [instabot-py/instabot.py#2441]
when running the script like_medias_by_locaton.py
Write location name:
blumenau
How much likes per location?
1
1. Blumenau, Santa Catarina, Brazil
2. Blumenau, S/C
3. Blumenau, Santa Catarina - Sc
4. Blumenau Norte Shopping
5. Blumenau Itoupava Norte
6. Blumenau S / C .
Traceback (most recent call last):
  File "like_medias_by_location.py", line 93, in <module>
    print(u"{}. {}".format(n, location["title"]))
UnicodeEncodeError: 'ascii' codec can't encode character '\xe2' in position 12: ordinal not in range(128)
2019-10-24 14:38:56,337 - INFO - Total requests: 1013

**Comment by nickgryg** [comment]
@pentalobebnu, what is the `like_medias_by_locaton.py` file? Is it some custome file? I don't see it in this repo.
