### ISSUE TITLE
Commenting isn't working for me

### ISSUE THREAD

**Issue by NikolayKolibarov** [instabot-py/instabot.py#2460]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [x] macOS Mojave
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
3.6.1
Include here the response of 'python --version' or 'python3 --version'
3.6.1

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
pip 9.0.1 from /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (python 3.6)

#### Instabot Version?
```
Include here the response of 'instabot-py --version'
0.5.4

#### How you use the instabot
- [x] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue
The bot isn't able to post comments.
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
raceback (most recent call last):
  File "/anaconda3/bin/instabot-py", line 10, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.7/site-packages/instabot_py/__main__.py", line 252, in main
    bot.mainloop()
  File "/anaconda3/lib/python3.7/site-packages/instabot_py/instabot.py", line 757, in mainloop
    self.new_auto_mod_comments(media)
  File "/anaconda3/lib/python3.7/site-packages/instabot_py/instabot.py", line 1025, in new_auto_mod_comments
    if self.iteration_ready("comments") and self.verify_media_before_comment(media):
  File "/anaconda3/lib/python3.7/site-packages/instabot_py/instabot.py", line 1080, in verify_media_before_comment
    if all_data["graphql"]["shortcode_media"]["owner"]["id"] == self.user_id:
KeyError: 'graphql'


#### Config

```
Ensure that you specify the configuration file in the command line.
Ensure that the default file instabot.config.yml contains only common settings if you use multiple accounts.
Include the contents of your config here (instabot-py -c config.yml --dump) (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
follow_per_day: 100
follow_per_run: '{{follow_per_day}}'
follow_time: 18000

like_per_day: 0
like_per_run: '{{like_per_day}}'
unlike_per_day: 0
unlike_per_run: '{{unlike_per_day}}'

comment_list: [['this', 'your'], ['photo', 'picture', 'pic', 'shot'], ['is', 'looks', 'is really'], ['great', 'super', 'good'], ['.', '...', '!', '!!']]
comments_per_day: 50
comments_per_run: '{{comments_per_day}}'

---
So I tried to debug it myself. It seems that "all_data" is an empty object.
raw_data = re.search("window._sharedData = (.*?);", resp.text, re.DOTALL).group(1)
all_data = json.loads(raw_data)["entry_data"]["PostPage"][0]
However PostPage is an array with one empty object. 
The program expects all_data to have -> all_data["graphql"]["shortcode_media"]["owner"]["id"] but it doesn't since the API returns PostPage: [{}].

Is there a solution already, is it only me, how should I proceed?

**Comment by nickgryg** [comment]
Duplicate to #2442
