### ISSUE TITLE
Can't start the Config setup

### ISSUE THREAD

**Issue by buu777** [instabot-py/instabot.py#2472]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [x ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ ] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [x ] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Instabot Version?
```
Include here the response of 'instabot-py --version'
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

Can't start the Config setup
I try Python3 -m instabot_py and then i get a error
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Ensure that you specify the configuration file in the command line.
Ensure that the default file instabot.config.yml contains only common settings if you use multiple accounts.
Include the contents of your config here (instabot-py -c config.yml --dump) (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT

```

**Comment by dankismylifestyle** [comment]
what error do you get? I have the same problem after updating the Bot. It just cant read my config anymore and its telling me to enter my login details even though they are there

**Comment by pantocrator77** [comment]
I have the same problem, I have installed the bot for the first time and looks like it doesn't read the configuration file I have done (as per instruction, it should work with "instabot-py -c myconfig.yml", it's like it's stucked in the config example

**Comment by nickgryg** [comment]
Version 0.5.19 has been just released. Starting from this version it should be clear how to get config file, modify it and start the bot

**Comment by dankismylifestyle** [comment]
ill give it a try but running it with instabot-py -c myconfig.yml doesnt work since he cant pull from the config and it says i need to enter password and username

**Comment by dankismylifestyle** [comment]
i tried it again and it says when I run the bot with instabot-py instabot.config.yml "unrecognized arguments" am I missing something? ive set up the config and all the requirements right

**Comment by nickgryg** [comment]
What's the bot version? What's the name of config file? Is it in folder where you are when you start a bot?

**Comment by dankismylifestyle** [comment]
i got it now, thanks :)

**Comment by rickardbroberg** [comment]
@dankismylifestyle  how did you solve it? I have same problem.
