### ISSUE TITLE
How to I run the bot

### ISSUE THREAD

**Issue by muygd** [instabot-py/instabot.py#2476]
Ive installed instabot and after that I wanted to customise example.py file. However, there no any information in the example.py file.

So how and where should I type my settings?

**Comment by muygd** [comment]
@dimisdas @bruvv @LevPasha  @ChipWolf @yurilaaziz

**Comment by muygd** [comment]
@dimisdas @bruvv @ChipWolf @LevPasha @yurilaaziz

**Comment by bruvv** [comment]
Do not mention me again.... Go and learn.

**Comment by muygd** [comment]
> Do not mention me again.... Go and learn.

Thank you for your suggestion....... Go and learn to be kinf

**Comment by IggsGrey** [comment]
@muygd check the README.md file, you'll find a detailed guide on how to start the bot.
example.py is deprecated.

**Comment by wojtekdera** [comment]
I red this file. But how i can edit the my login and password?  Im new to python

**Comment by bruvv** [comment]
OMG some one please close this...

**Comment by wojtekdera** [comment]
Oh. Sorry but this is not obvious for me how to edit this config file.
