### ISSUE TITLE
Action Block - Bypass - [Feature]

### ISSUE THREAD

**Issue by elvirmuslic** [instabot-py/instabot.py#2497]
Since instagram takes into account device, usage and similar. 
It would be a **wise** option to implement a fake action seeder or behave like a human for a period of time. 
Also send statistics after how many action the profile gets blocked and such so we can make a better strategy on how to proceed.

What do I mean? 
Make a human like bot for a few days that will act like a human, just liking and similar and then do actual bot actions, mass follow and such. 

Why?
Instagram takes into account if you just logged from another device and suddenly start doing mass like/follow or similar. It takes a few days until instagram recognizes and starts trusting the new device.

Tehnical -
It seems that Instagram has a **Trust** **Score** of the device amongst other things. Implement a feature i.e. script that will roam and do everyday tasks.
- Scroll
- Like few pages 
- Stop at random points 
- Swipe to see more (in album) 

We could skip this step if we could emulate **OUR own devices** that we use regularly and it wouldn't it would automatically inherit our **Trust Factor**.

**Comment by nickgryg** [comment]
We don't use browser in this project. Bot just sends https requests and parses responses' output.  Unfortunately, above suggestions cannot be implemented in this project.
