### ISSUE TITLE
Re-uses stored cookies, while randomizing Browser fingerprint

### ISSUE THREAD

**Issue by the-rccg** [instabot-py/instabot.py#2504]
The current version reuses the stored login cookie, but randomizes the browser in the request headers upon startup. This can lead to some pretty easily detectable behavior, for example using the same login cookie for a Firefox 12 version, and then later Firefox 11. 
Possible fixes:
- Use default browser with Selenium 
- Fix fingerprint in request header
- Delete cookie / logout upon exit of file execution with a hook

**Comment by nickgryg** [comment]
Another possible fix is to use your custom User Agent in a configuration file (this is default behavior starting from version 0.5.19).

**Comment by thehackedone** [comment]
How would one go about doing that nick?
