### ISSUE TITLE
New liking feature

### ISSUE THREAD

**Issue by asainboi** [instabot-py/instabot.py#2506]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ X] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Operating System? (include version)
- [X ] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [ X] I am using Python 3.6 or above

#### Description of your issue

```
There should be a new liking feature where the bot randomly likes photos at random intervals, which will make it harder for instagram to detect.
```

**Comment by nickgryg** [comment]
We already have this feature in version 0.5.19 and later. Bot randomly likes photos at random intervals.
