### ISSUE TITLE
Config File Not Able to Be Read Correctly By Bot

### ISSUE THREAD

**Issue by b-rad42** [instabot-py/instabot.py#2507]
python 3.6.9 (nice) on ubuntu mate 64-bit running on a raspberry pi
instabot installs perfectly, but doesn't recognize anything in the config file.
Since I have two accounts I want to use this for, I originally made my modifications to instabot.config.yml and saved the new files as khi.config.yml and wywf.config.yml. I tried running instabot -c ~/khi.config.yml, but it told me it couldn't find the username and password. I thought maybe it was a permissions error, so I did chmod 777 ~/khi.config.yml, but to no avail. After that, I tried running instabot --username (my username) --password (my password) -c ~/khi.config.yml (or whatever the syntax is; that's not the point). It connected to my account successfully and started running, but completely ignored all the parameters I set in the config file like tags, etc. So obviously it's not reading the config file.
Nothing worked. I don't know why it doesn't work, but it doesn't. Previous versions (with the easy config and the manual config before that; I've had this for at least a year) have all worked perfectly, including on Ubuntu Mate. I honestly don't know what up. In the meantime, is there any way to use an older version of this? Thanks either way :)
(my khi.config.yml file is attached; had to change to txt for github to support it)
[khi.config.txt](https://github.com/instabot-py/instabot.py/files/4017403/khi.config.txt)

**Comment by nickgryg** [comment]
What version of instabot-py do you use? Please show the logs when bot starts until its first action.

**Comment by liadlevy** [comment]
@nickgryg 
I have it too running on kali linux,
I've downlaod from git the program.
edited the instabot.config.yml
and then run the command: instabot-py -c instabot.config.yml
I had 1 good run but after editing and running it again it looks like it reads the default config.
cant find username/password and such, I even did mistakes in the config file and it still runned without errors.
verbose:

> instabot-py -c instabot.conf.yml --login *****--password ********
Reading configuration (4 settings) from instabot.conf.yml
2020-01-03 21:06:17,510 - ****** - Persistence - DEBUG - Init SQL Perisitence sqlite:///*******.db
2020-01-03 21:06:17,531 -  ******- InstaBot - INFO - Instabot v0.5.20 started at 03.01.2020 21:06:
2020-01-03 21:06:17,531 -  ******- InstaBot - DEBUG - User agent 'Mozilla/5.0 (Windows ***; rv:***) ****' is used
2020-01-03 21:06:17,532 - *****- InstaBot - INFO - Found session file *****.session
2020-01-03 21:06:19,193 - *****- InstaBot - INFO - ****** has logged in successfully!
2020-01-03 21:06:19,193 - ******- InstaBot - INFO - Saving cookies to the session file ********.session
2020-01-03 21:06:34,556 - ******- InstaBot - DEBUG - Getting media by tag: cat
2020-01-03 21:06:36,401 - ******- InstaBot - DEBUG - Retrieved 71 medias
2020-01-03 21:06:36,464 - ****- InstaBot - DEBUG - Selected 3 medias to process. Increase max_like_for_one_tag value for more processing medias 

I've put the **** to keep it secret
and runs...

**Comment by nickgryg** [comment]
According to your log, it seems that your configuration is not a valid yaml file, because only 4 settings were loaded from it.
I've just released instabot-py version 0.5.21 where config file is validated before starting a bot. Please upgrade your instabot-py and try again.

**Comment by liadlevy** [comment]
@nickgryg 
Thanks for fixing the bug.

it seems instagram understands its a bot,
how to bypass it?

> Your Account Was Compromised
It looks like you shared your password with a service to help you get more likes or followers, which goes against our Community Guidelines.
Change your password to continue using Instagram. If you share your new password with one of these services, you may get blocked from following, liking or commenting.

**Comment by nickgryg** [comment]
It could be that you started a bot from some network which is already blacklisted in IG. A bot works like you are using your browser, so if these requests are coming from some cloud network, they are identifying them as suspicious. Same for amount of likes, user agent setting etc. But that's not a question of this issue. There are a lot of issues opened in this repo about blockings.
