### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'. Error in get_followers_count

### ISSUE THREAD

**Issue by KanzXI** [instabot-py/instabot.py#2510]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
Python 3.8.1

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Instabot Version?
0.5.21
Include here the response of 'instabot-py --version'
```

#### How you use the instabot
- [x] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 


#### Description of your issue

I just pull the latest version from github and run the bot. When the bot try to follow someone, I always got this error.

Traceback (most recent call last):
  File "/Users/kanz/Desktop/instabot.py/instabot_py/instabot.py", line 914, in get_followers_count
    re.search(
AttributeError: 'NoneType' object has no attribute 'group'

How can I fix this?

**Comment by iamklaus** [comment]
+1
