### ISSUE TITLE
List of all followers / following

### ISSUE THREAD

**Issue by iamklaus** [instabot-py/instabot.py#2512]
Hey guys, this is more a question, not a but. Do you know any url that can be called to retrieve all your followers / following from instagram? I would like to add a feature to clean up my following-List.

Cheers,
Klaus

**Comment by nickgryg** [comment]
Right now it is not possible to get list of followers/followings from Instagram API, details you can find [here](https://stackoverflow.com/questions/32407851/instagram-api-how-can-i-retrieve-the-list-of-people-a-user-is-following-on-ins).

What do you mean by "clean up my following-List"?
