### ISSUE TITLE
stop after one follow

### ISSUE THREAD

**Issue by ubiga** [instabot-py/instabot.py#2517]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [X ] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ X] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [X ] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [ ] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Instabot Version?
```
Include here the response of 'instabot-py --version'
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [X ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Ensure that you specify the configuration file in the command line.
Ensure that the default file instabot.config.yml contains only common settings if you use multiple accounts.
Include the contents of your config here (instabot-py -c config.yml --dump) (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT

```

When I start the code, everything is ok but after one follow the code stops... I don't understand why

**Comment by nickgryg** [comment]
Please fill issue template when you create issues. We cannot help you if we know nothing about your setup: instabot-py version, configuration etc.

**Comment by dshippa** [comment]
This could be due to the wait time in between likes and follows. Personally, the first like and follow was instant, followed by a like 5 minutes later, then another like 4 minutes later. Is there a setting that determines time between likes and follows, or does it just take the "time to run/# to likes" and "time to run/# to follow"?

**Comment by nickgryg** [comment]
You can find all the information in README file:

| like_per_run | int | Number of photos to like per day (over 1000 may cause throttling) | 296 |
| follow_per_run | int | Users to follow per day | 156 |

Day means 60 * 60 * 24 = 86400 seconds.

So, 156 follows a day means to follow someone approximately every 553 seconds (86400 / 156 = 553), ie every 9 minutes 13 seconds.
