### ISSUE TITLE
Bot says he is following users, but he actually is not.

### ISSUE THREAD

**Issue by volpi3000** [instabot-py/instabot.py#2518]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
The bot is on a raspberry pi with a debian distribution.
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Rasbian Linux Raspberry PI (current)
- [x] Linux (Debian)
- [ ] Android (include terminal)

```
Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.3
```

#### Pip Version?
```
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
```

#### Instabot Version?
```
Installed version 0.5.21'
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [x] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
The bot says it is trying to follow, but never actually follows anyone.


Example Output
`2020-01-16 16:02:14,719 - X - InstaBot - DEBUG - Trying to follow user #1: id: 8702915017, username: blues.wayne
2020-01-16 16:02:21,602 - X - InstaBot - DEBUG - Trying to follow user #1: id: 303607180, username: thebeachamorlando
2020-01-16 16:02:29,815 - X - InstaBot - DEBUG - Trying to follow user #1: id: 7658334, username: minecagliyanofficial
2020-01-16 16:02:36,921 - X - InstaBot - DEBUG - Trying to follow user #1: id: 50268265, username: juliagyenge
2020-01-16 16:02:43,851 - X - InstaBot - DEBUG - Trying to follow user #1: id: 28344009756, username: universidade_da_guitarra`
2020-01-16 16:02:56,812 - X - InstaBot - DEBUG - Could not find user to follow in 30 attempts. If you want to increase this number, change 'follow_attempts' value
```

#### Config

```

debug: 1
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"

tag_list: ["hiphop", "trap", "rap", "producer", "beat", "808", "flstudio", "protools", "musicianlife", "rapper", "freebeat", "soundengineer00" ]
tag_blacklist: ["sex", "porno"]

like_per_day: 196
max_like_for_one_tag: 36
media_min_like: 20
media_max_like: 0
like_followers_per_run: 5

unlike_per_day: 0
time_till_unlike: 259200

follow_per_day: 500
follow_time: 180000
follow_attempts: 30
user_min_follow: 49
user_max_follow: 500000

unfollow_per_day: 450
unfollow_per_run: 450
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false
unfollow_whitelist: []

unwanted_username_list: ["free", "travel", "shop", "store", "sex", "online"]
comments_per_day: 0

```

**Comment by nickgryg** [comment]
Bot says that's it is trying to follow users, not following them. I think your `follow` action is blocked by Instagram. Will check if I can add more information messages here if we have such a case.

**Comment by sinanmohd** [comment]
i have the same probem

**Comment by simonefrancia** [comment]
@sinanmohd did you solve?

**Comment by nickgryg** [comment]
Please update `instabot-py` to version `0.7.11`. Above issue should be fixed there.
