### ISSUE TITLE
Non volatility

### ISSUE THREAD

**Issue by drewhga** [instabot-py/instabot.py#252]
Hello...
I often face this problem when I need to restart the script or an error pops up then those followed are not unfollowed. So I was thinking if we could print the followed users list to a file and then the file is read later by the script. This will prevent the list[]  of followed users from erasing when the not is restarted. Maybe we can use the pickle module to do this easily.

import pickle

pickle.dump(itemlist, outfile)
To read it back:

itemlist = pickle.load(infile)

**Comment by polaroi8d** [comment]
#245

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
