### ISSUE TITLE
Bot stopped working "TypeError: like() missing 1 required positional argument 'media_url'"

### ISSUE THREAD

**Issue by Jostino** [instabot-py/instabot.py#2522]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
Include more details about the environment

RASPBERRY PI 3+
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
Linux rasp2igbot 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.3
```

#### Pip Version?
```
pip 19.3.1 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
```

#### Instabot Version?
```
Installed version 0.5.21
```

#### How you use the instabot
- [x] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
2020-01-20 16:14:21,996 - xxxxxxx - InstaBot - INFO - Followed user #1: username: naomirestuccia, url: https://www.instagram.com/naomirestuccia/
2020-01-20 16:14:22,035 - xxxxxxx - InstaBot - DEBUG - Trying to unfollow user #1: panama_travel_repost
2020-01-20 16:14:22,930 - xxxxxxx - InstaBot - DEBUG - User panama_travel_repost has: 1508 followers, 1261 followings, 517 medias
2020-01-20 16:14:22,930 - xxxxxxx - InstaBot - DEBUG -     > Skipping panama_travel_repost: the user is still following you
2020-01-20 16:14:24,123 - xxxxxxx - InstaBot - DEBUG - Trying to like media of your old follower #1: _carrie_photography
2020-01-20 16:14:24,130 - xxxxxxx  - InstaBot - ERROR - like() missing 1 required positional argument: 'media_url'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/instabot_py/instabot.py", line 882, in like_followers_last_media
    if self.like(media_id):
TypeError: like() missing 1 required positional argument: 'media_url'

```

#### Config

```
debug: 0
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"

tag_list: ["nature", "follow4follow", "f4f", "landscape", "firstpost"]
tag_blacklist: ["sex", "porno"]

like_per_day: 196
max_like_for_one_tag: 36
media_min_like: 20
media_max_like: 200
like_followers_per_run: 5

unlike_per_day: 0
time_till_unlike: 259200

follow_per_day: 156
follow_time: 259200
follow_attempts: 10
user_min_follow: 200
user_max_follow: 2200

unfollow_per_day: 199
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false
unfollow_whitelist: []

unwanted_username_list: ["free", "travel", "shop", "store", "sex", "online"]
comments_per_day: 0
comment_list: [
        ["this", "the", "your"],
        ["photo", "picture", "pic", "shot", "snapshot"],
        ["is", "looks", "feels", "is really"],
        [
            "great",
            "super",
            "good",
            "very good",
            "good",
            "wow",
            "WOW",
            "cool",
            "GREAT",
            "magnificent",
            "magical",
            "very cool",
            "stylish",
            "beautiful",
            "so beautiful",
            "so stylish",
            "so professional",
            "lovely",
            "so lovely",
            "very lovely",
            "glorious",
            "so glorious",
            "very glorious",
            "adorable",
            "excellent",
            "amazing",
        ],
        [".", "..", "...", "!", "!!", "!!!"],
    ]


```

**Comment by u0xpsec** [comment]
i have the same exact issue both on raspberry pi b3+ running the same config and on Debian 10 on my laptop. Bot freezes after that error. only way to run it is with like_followers_per_run = 0

**Comment by Jostino** [comment]
> 
> 
> i have the same exact issue both on raspberry pi b3+ running the same config and on Debian 10 on my laptop. Bot freezes after that error. only way to run it is with like_followers_per_run = 0

Ya now the issue is another one about the len() function. There is any way to log down what bot is doing with the errors too?

**Comment by u0xpsec** [comment]
if you are keeping tabs on this issue, on instabot.py line 888 change `                    if self.like(media_id):` with `                    if self.like(media_id, media_to_like_url):` that will take care of the issue of not having the url to like. I forked the project and am making some changes to the code as i see fit for myself and to make things work as for me it was haging way to much and not doing what its suppose to do. Ill commit it soon so if it interests you keep an eye in my profile.
