### ISSUE TITLE
--tag-list doens't working - help

### ISSUE THREAD

**Issue by PedrinhoTc** [instabot-py/instabot.py#2523]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ x] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x ] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [ ] macOS
- [x ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [ x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
pip 19.2.2 (python 3.7)
```

#### Instabot Version?
```
Include here the response of 'instabot-py --version'
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [x ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
Hey guys
I`ve been trying to use the bot and it is going well but when the bot starts "like" the posts by default tag (cat, car, dog).
I changed the list of tags in both files.
- default_config.py and MyFile.yml
And the bot still getting the tags cat, dog....


how can I fix that?
Someone, please give one way to fix that, my brain is over.

Thanks
```

#### Config

```
---
login: ""
password: ""

debug: 1
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"

tag_list: ["tattoo", "art," "artist", "share", "shareartmagazine", "tattooshare", "tattoolife", "tattooworkers", 
          "tattooprints", "tattoocollective", "tattoodo", "tattoodesign", "neotraditionaleurope", "neotradtattoo",
          "neotraditional", "neotraditionalspain", "neotraditional"]
tag_blacklist: ["sex", "porno"]

like_per_day: 130
max_like_for_one_tag: 36
media_min_like: 20
media_max_like: 200
like_followers_per_run: 0

unlike_per_day: 0
time_till_unlike: 259200

follow_per_day: 156
follow_time: 259200
follow_attempts: 10
user_min_follow: 200
user_max_follow: 2200

unfollow_per_day: 199
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false
unfolliw_everyone: false
unfollow_whitelist: []

unwanted_username_list: ["free", "travel", "shop", "store", "sex", "online"]
comments_per_day: 30
comment_list: [
        ["this", "the", "your"],
        ["photo", "picture", "pic", "shot", "design", "tattoo"],
        ["is", "looks", "is really"],
        [
            "great",
            "good",
            "very good",
            "good",
            "cool",
            "GREAT",
            "very cool",
            "beautiful",
            "so beautiful",
            "so professional",
            "glorious",
            "very glorious",
            "excellent",
            "amazing",
        ],
        [".", "..", "...", "!", "!!", "!!!"],
    ]


```

**Comment by u0xpsec** [comment]
your config file has an error ---> , "art,"    <--- your coma is inside the quotation

**Comment by nickgryg** [comment]
@PedrinhoTc Version 0.5.21 has feature to verify configuration before bot is started. As @u0xpsec pointed you had some issue with your configuration. It is worth to upgrade instabot to version 0.5.21 before start using the bot.
