### ISSUE TITLE
add the ability to watch and interact with stories

### ISSUE THREAD

**Issue by Morph-wow** [instabot-py/instabot.py#2525]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Instabot Version?
```
Include here the response of 'instabot-py --version'
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [x] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

#### Config

```
Ensure that you specify the configuration file in the command line.
Ensure that the default file instabot.config.yml contains only common settings if you use multiple accounts.
Include the contents of your config here (instabot-py -c config.yml --dump) (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT

```

**Comment by Morph-wow** [comment]
i'd like to see the ability to watch the stories of other accounts and interact for instance with the polls

**Comment by mcarlock12** [comment]
@Morph-wow Has instabot been working for you?

I used it a while ago and stopped because it had a lot of issues since IG went to AI? im thinking of installing again?

**Comment by Morph-wow** [comment]
i’ve just started using it so for now i didn’t had any issues, what kind of issue u got?

**Comment by mcarlock1** [comment]
@Morph-wow  everything was running great, then once IG changed their algorithm I kept getting blocked messages and eventually I was blocked from Ig for 3 days.

Im really glad this is working now, its a very good program.

**Comment by nickgryg** [comment]
Duplicate to #2519
