### ISSUE TITLE
@Morph-wow  everything was running great, then once IG changed their algorithm I kept getting blocked messages when the bot try to unfollow or like medias 

### ISSUE THREAD

**Issue by Morph-wow** [instabot-py/instabot.py#2532]
@Morph-wow  everything was running great, then once IG changed their algorithm I kept getting blocked messages and eventually I was blocked from Ig for 3 days.

Im really glad this is working now, its a very good program.

_Originally posted by @mcarlock1 in https://github.com/instabot-py/instabot.py/issues/2525#issuecomment-578529603_

Morph: got the same issue, after 2 days of running the bot, it can't make any actions cause instagram is blocking it

**Comment by saifullah9002** [comment]
Same here
