### ISSUE TITLE
Finds mostly low number likes media

### ISSUE THREAD

**Issue by TomDayan9** [instabot-py/instabot.py#2558]
Hi !

I configured the media_min_like option in the configuration file to 20 likes.
When I'm running the bot it is always finds media with low number likes (0,1,2...) and so it won't like anything.
The exact message printed to log is: "will not like this media: number of likes # does not meet media_min_like requirements"
I understand that this is probably what it's supposed to do, but with this configuration it doesn't like anything at all

**Comment by nickgryg** [comment]
I cannot understand a question at all. You set `media_min_like: 20` and wondering why bot don't like medias with 1-3 likes?

**Comment by TomDayan9** [comment]
Thanks for your reply !

No, I understand why it won't these medias, but it tries to like only medias with 10 likes or less, so I can't get it to work with my configuration.
The bot doesn't even try to like medias with 20 likes or more - this is my point.
It worked fine with the previous version but now it is like I described

**Comment by nickgryg** [comment]
It's a matter of hashtags you put into a bot's configuration. It seems like almost all of the photos found by those hashtags have few likes. So, I would recommend to check those hashtags on Instagram before start a bot. 
Another thing for consideration is to set `max_like_for_one_tag: 50` and more to get more medias for at once for the hashtag.
