### ISSUE TITLE
Bot stops after follow

### ISSUE THREAD

**Issue by girlscoutfather** [instabot-py/instabot.py#2568]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ ] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
Darwin MacBook-Pro-2.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.8
```

#### Pip Version?
```
pip 20.0.2
```

#### Instabot Version?
```
0.7.1
```

#### How you use the instabot
- [x] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
Everything is going great until instabot attempts a follow, then it halts its functioning:

2020-03-09 14:58:28,228 - X - InstaBot - DEBUG - Will not like this media: number of likes 0 does not meet media_min_like requirements
2020-03-09 14:58:29,860 - X - InstaBot - DEBUG - Trying to follow user #1: id: XXXX, username: babykids013
2020-03-09 14:58:31,447 - X - InstaBot - INFO - Followed user #1: username: X, url: https://www.instagram.com/X/

And then - nothing - no matter how long I wait.
```

#### Config

login: ""
password: ""

debug: 0
user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15"

**NOTES TO SELF**
## TRY Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15
**

tag_list: ["thrasher", "thrashermag", "skate", "music", "streetwear", "fashion", "cute", "boy", "eboy", "l:212999109", "l:204517928", "l:212950988"]
tag_blacklist: ["sex", "porno", "free", "promo", "promotion", "meme", "memes"]

like_per_day: 140
max_like_for_one_tag: 20
media_min_like: 55
media_max_like: 600
like_followers_per_run: 0

unlike_per_day: 0
time_till_unlike: 259200

follow_per_day: 75
follow_time: 86400
follow_attempts: 10
user_min_follow: 600
user_max_follow: 7000

unfollow_per_day: 72
unfollow_break_min: 300
unfollow_break_max: 15000
unfollow_recent_feed: true
unfollow_selebgram: true
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: true
unfollow_whitelist: [X, X, X, X, etc.]

unwanted_username_list: ["free", "travel", "shop", "store", "sex", "online"]
comments_per_day: 0
comment_list: [
        ["this", "the", "your"],
        ["photo", "picture", "pic", "shot", "snapshot"],
        ["is", "looks", "feels", "is really"],
        [
            "great",
            "super",
            "good",
            "very good",
            "good",
            "wow",
            "WOW",
            "cool",
            "GREAT",
            "magnificent",
            "magical",
            "very cool",
            "stylish",
            "beautiful",
            "so beautiful",
            "so stylish",
            "so professional",
            "lovely",
            "so lovely",
            "very lovely",
            "glorious",
            "so glorious",
            "very glorious",
            "adorable",
            "excellent",
            "amazing",
        ],
        [".", "..", "...", "!", "!!", "!!!"],
    ]

```
Ensure that you specify the configuration file in the command line.
Ensure that the default file instabot.config.yml contains only common settings if you use multiple accounts.

Include the contents of your config here (instabot-py -c config.yml --dump) 

accept_language: en-US,en;q=0.5
ban_sleep_time: 10800
comment_list:
- - this
  - the
  - your
- - photo
  - picture
  - pic
  - shot
  - snapshot
- - is
  - looks
  - feels
  - is really
- - great
  - super
  - good
  - very good
  - good
  - wow
  - WOW
  - cool
  - GREAT
  - magnificent
  - magical
  - very cool
  - stylish
  - beautiful
  - so beautiful
  - so stylish
  - so professional
  - lovely
  - so lovely
  - very lovely
  - glorious
  - so glorious
  - very glorious
  - adorable
  - excellent
  - amazing
- - .
  - ..
  - '...'
  - '!'
  - '!!'
  - '!!!'
comments_per_day: 0
comments_per_run: '{{comments_per_day}}'
config:
  file: config.yml
database:
  connection_string: sqlite:///{{database.path}}
  path: '{{login}}.db'
  type: sql
debug: 0
end_at_h: 23
end_at_m: 59
error_400_to_ban: 3
follow_attempts: 10
follow_per_day: 92
follow_per_run: '{{follow_per_day}}'
follow_time: 259200
follow_time_enabled: true
like_followers_per_run: 0
like_per_day: 120
like_per_run: '{{like_per_day}}'
list_of_ua:
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.6.01001)
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.7.01001)
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.5.01003)
- Mozilla/5.0 (Windows NT 6.1; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0
- Mozilla/5.0 (X11; U; Linux x86_64; de; rv:1.9.2.8) Gecko/20100723 Ubuntu/10.04 (lucid)
  Firefox/3.6.8
- Mozilla/5.0 (Windows NT 5.1; rv:13.0) Gecko/20100101 Firefox/13.0.1
- Mozilla/5.0 (Windows NT 6.1; WOW64; rv:11.0) Gecko/20100101 Firefox/11.0
- Mozilla/5.0 (X11; U; Linux x86_64; de; rv:1.9.2.8) Gecko/20100723 Ubuntu/10.04 (lucid)
  Firefox/3.6.8
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; .NET CLR 1.0.3705)
- Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)
- Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727;
  .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)
- Opera/9.80 (Windows NT 5.1; U; en) Presto/2.10.289 Version/12.01
- Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727)
- Mozilla/5.0 (Windows NT 5.1; rv:5.0.1) Gecko/20100101 Firefox/5.0.1
- Mozilla/5.0 (Windows NT 6.1; rv:5.0) Gecko/20100101 Firefox/5.02
- Mozilla/5.0 (Windows NT 6.0) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/13.0.782.112
  Safari/535.1
- Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows NT 5.0) Opera 7.02 Bork-edition
  [en]
log_mod: 0
logging:
  disable_existing_loggers: false
  formatters:
    simple:
      format: '%(asctime)s - {{login}} - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      level: DEBUG
      stream: ext://sys.stdout
  loggers:
    InstaBot:
      handlers:
      - console
      level: DEBUG
      propagate: 'no'
    Persistence:
      handlers:
      - console
      level: DEBUG
      propagate: 'no'
  root:
    level: INFO
  version: 1
login: X
max_like_for_one_tag: 36
media_max_like: 800
media_min_like: 50
password: X
proxies: {}
session_file: '{{login}}.session'
start_at_h: 0
start_at_m: 0
tag_blacklist:
- sex
- porno
- free
- promo
- promotion
- meme
- memes
tag_list:
- thrasher
- thrashermag
- skate
- music
- streetwear
- fashion
- cute
- boy
- eboy
- l:212999109
- l:204517928
- l:212950988
time_till_unlike: 259200
unfollow_break_max: 17
unfollow_break_min: 3
unfollow_everyone: false
unfollow_inactive: true
unfollow_not_following: true
unfollow_per_day: 95
unfollow_per_run: '{{unfollow_per_day}}'
unfollow_probably_fake: true
unfollow_recent_feed: true
unfollow_selebgram: true
unfollow_whitelist:
- X
- X
- X
- X
etc.
unlike_per_day: 0
unlike_per_run: '{{unlike_per_day}}'
unwanted_username_list:
- free
- travel
- shop
- store
- sex
- online
- promo
- promotion
- famous
user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML,
  like Gecko) Version/13.0.5 Safari/605.1.15
user_blacklist: {}
user_max_follow: 5000
user_min_follow: 600
window_check_every: 300


```

**Comment by Komischerboy** [comment]
me too

**Comment by MarcoLeko** [comment]
This is also happening on my side with my mac os.

**Comment by nickgryg** [comment]
`follow_per_day: 75` means that bot will try to follow users every 60 * 60 * 24 / 75 = 1152 seconds  (19 minutes, 12 seconds). It seems like you didn't wait this time and created this issue, which is not an issue, but just settings.

We are getting so many similar requests, that's why I created version 0.7.7 specially for this case.
