### ISSUE TITLE
The bot halts after trying to like media 

### ISSUE THREAD

**Issue by ilMagnifico** [instabot-py/instabot.py#2570]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [x] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
MacOS last version
```

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
Darwin MacBook-Pro-2.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```

#### Python Version Requirement
- [ ] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 2.7.16
```

#### Pip Version?
```
pip 20.0.2 from /Library/Python/2.7/site-packages/pip-20.0.2-py2.7.egg/pip (python 2.7)
```

#### Instabot Version?
```
Installed version 0.7.1
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
2020-03-17 00:36:45,380 - lorenzolife_ - InstaBot - DEBUG - Selected 20 medias to process. Increase max_like_for_one_tag value for more processing medias

2020-03-17 00:36:53,712 - lorenzolife_ - InstaBot - DEBUG - Trying to like media #1: id: 2266434601079906077, url: https://www.instagram.com/p/B9z_kL4BZ8d/

2020-03-17 00:36:59,252 - USERNAME - InstaBot - INFO - Could not like media: id: 2266434601079906077, url: https://www.instagram.com/p/B9z_kL4BZ8d/, status code: 400. Reason: {"message": "feedback_required", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.", "feedback_url": "repute/report_problem/instagram_like_add/", "status": "fail"}

2020-03-17 00:36:59,252 - USERNAME - InstaBot - CRITICAL - Your like action has just been banned by Instagram. Exiting from a program... You can start your bot again if you disable like action in your configuration: set 'like_per_run: 0'

```

#### Config

```
---
login: "USERNAME"
password: "PASSWORD"

debug: 0
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"

tag_list: ["toscana", "firenze", "pistoia", "florence", "prato","tuscany", "l:235718823", "l:219237919", "l:216153789","l:213719198","l:647739","l:166847503946137","l:118188705516128"]
tag_blacklist: ["sex", "porno", "porn", "dio", "gay", "trans", "gayfrieldly", "tgirl", "lgbt", "gayitalia", "lgbtitalia", "bisex", "gayitaly", "bsex", "lesbian"]

like_per_day: 100
max_like_for_one_tag: 25
media_min_like: 0
media_max_like: 200
like_followers_per_run: 0

unlike_per_day: 70
time_till_unlike: 604800

follow_per_day: 0
follow_time: 259200
follow_attempts: 10
user_min_follow: 100
user_max_follow: 2200

unfollow_per_day: 0
unfollow_per_run: 0
unfollow_break_min: 10
unfollow_break_max: 20
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: false
unfollow_not_following: false
unfollow_recent_feed: false
unfollow_whitelist: []

unwanted_username_list: ["free", "ristorante", "prima", "dopo", "prodotto", "intimo", "prodotti", "sport", "calcio", "rugby", "football", "meme", "punto", "bar", "hotel", "apartment", "archivio", "watch", "travel", "shop", "store", "sex", "home", "house", "online", "second", "stuff", "art", "project", "love", "life", "food", "blog", "keren", "photo", "graphy", "indo", "art", "toko", "jual", "online", "murah", "jam", "kaos", "case", "baju", "fashion", "corp", "tas", "butik", "grosir", "karpet", "sosis", "salon", "skin", "care", "cloth", "tech", "rental", "kamera", "beauty", "express", "kredit", "collection", "impor", "preloved", "follow", "follower", "gain", ".id", "_id", "bags", "vino", "vini"]
comments_per_day: 0
comment_list: [
        ["this", "the", "your"],
        ["photo", "picture", "pic", "shot", "snapshot"],
        ["is", "looks", "feels", "is really"],
        [
            "great",
            "super",
            "good",
            "very good",
            "good",
            "wow",
            "WOW",
            "cool",
            "GREAT",
            "magnificent",
            "magical",
            "very cool",
            "stylish",
            "beautiful",
            "so beautiful",
            "so stylish",
            "so professional",
            "lovely",
            "so lovely",
            "very lovely",
            "glorious",
            "so glorious",
            "very glorious",
            "adorable",
            "excellent",
            "amazing",
        ],
        [".", "..", "...", "!", "!!", "!!!"],
    ]


```

**Comment by nickgryg** [comment]
This is pretty normal situation and it's clearly described in logs.

```
Could not like media: id: xxxxxxxxxxxxxxxxxxxx, url: https://www.instagram.com/p/XXXXXXXXXXX/, status code: 400. Reason: {"message": "feedback_required", "spam": true, "feedback_title": "Action Blocked", "feedback_message": "This action was blocked. Please try again later. We restrict certain content and actions to protect our community.
``` 
means that your like action was blocked.

```
CRITICAL - Your like action has just been banned by Instagram. Exiting from a program... You can start your bot again if you disable like action in your configuration: set 'like_per_run: 0'
```
describes what have just happened and stops a bot. Otherwise your account will be blocked for one week or so.

**Comment by ilMagnifico** [comment]
I used to use the bot last year and even at that time the bot was stopping after a short execution with a similar 'error'. Yesterday I tried to download all again and retry to start it but after an hour of execution all the times I try to execute it, it returns this error at console.

So I wonder why does the bots work correctly for others, but not for me? What should I do to make the bot work?

**Comment by Phexcom** [comment]
Yes I'm current Facing the same issues even with like disabled. And It also downloads the html of the users it was trying to interact with to the console

**Comment by herecomesharis** [comment]
> I used to use the bot last year and even at that time the bot was stopping after a short execution with a similar 'error'. Yesterday I tried to download all again and retry to start it but after an hour of execution all the times I try to execute it, it returns this error at console.
> 
> So I wonder why does the bots work correctly for others, but not for me? What should I do to make the bot work?

This is not an issue of the bot, it is an issue of Instagram and your account. It could mean multiple things - you sent too many requests at once, your account rating is low etc. You need to leave your account to rest for a few days and try again. Using Instagram via API is tricky and can lead to things like this.

**Comment by ilMagnifico** [comment]
> > I used to use the bot last year and even at that time the bot was stopping after a short execution with a similar 'error'. Yesterday I tried to download all again and retry to start it but after an hour of execution all the times I try to execute it, it returns this error at console.
> > So I wonder why does the bots work correctly for others, but not for me? What should I do to make the bot work?
> 
> This is not an issue of the bot, it is an issue of Instagram and your account. It could mean multiple things - you sent too many requests at once, your account rating is low etc. You need to leave your account to rest for a few days and try again. Using Instagram via API is tricky and can lead to things like this.

I tried today again after more than 7 days without using it, and nothing... It halts with the same message. I lost the hope.
