### ISSUE TITLE
installation does not work

### ISSUE THREAD

**Issue by arc9531** [instabot-py/instabot.py#2571]
Won't work! I have tried every way to install and run the damn program and it doesn't work! the instabot-py command doesn't work it says bash: "instabot-py: command not found" I followed the installation on the README and it doesn't work!!!!!!!!!!!!!!!! please help! why the hell would you change it up so much, all installation guides are completely useless now
 PLEASE HELP

**Comment by nickgryg** [comment]
Instead of writing complains here, I would suggest to describe what you tried to do to install and use `instabot-py` at least.

The information about installation process is clearly described in README of the project:
```
Installation

    From PyPi (Stable):

python3 -m pip install instabot-py
```

**Comment by arc9531** [comment]
I already ran that, it is already installed. Whenever I try running `instabot-py` to start the program I just get an error that says `bash: instabot-py: command not found` I followed all the installation instructions

**Comment by nickgryg** [comment]
https://stackoverflow.com/questions/35898734/pip-installs-packages-successfully-but-executables-not-found-from-command-line

**Comment by jfinly** [comment]
> https://stackoverflow.com/questions/35898734/pip-installs-packages-successfully-but-executables-not-found-from-command-line

Hey Nick when i try to follow the instructions in the link I get:

pip list | grep instabot-py
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

I have both python2 and python3 installed:
joshuafinly@Joshuas-iMac ~ % python --version
Python 2.7.16
joshuafinly@Joshuas-iMac ~ % python3 --version
Python 3.7.3

but trying to run the command with pip3 doesnt change the response:
pip3 list | grep instabot-py
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

**Comment by pixobit** [comment]
Same issue here. It used to work well before... Even if I run the py file, it dosn't do anything

**Comment by nickgryg** [comment]
@jfinly If your `python3` works, you can use it to install `instabot-py`:
```
python3 -m pip install instabot-py
```

**Comment by nickgryg** [comment]
@pixobit 
Everything is described in project’s documentation. Please show the step of documentation you couldn’t proceed and the error output of this step.

**Comment by pixobit** [comment]
`ERROR: Exception:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pip\_internal\cli\base_command.py", line 186, in _main
    status = self.run(options, args)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pip\_internal\commands\install.py", line 258, in run
    isolated_mode=options.isolated_mode,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pip\_internal\commands\install.py", line 604, in decide_user_install
    if site_packages_writable(root=root_path, isolated=isolated_mode):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pip\_internal\commands\install.py", line 549, in site_packages_writable
    test_writable_dir(d) for d in set(get_lib_location_guesses(**kwargs))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pip\_internal\commands\install.py", line 549, in <genexpr>
    test_writable_dir(d) for d in set(get_lib_location_guesses(**kwargs))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pip\_internal\utils\filesystem.py", line 140, in test_writable_dir
    return _test_writable_dir_win(path)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pip\_internal\utils\filesystem.py", line 153, in _test_writable_dir_win
    fd = os.open(file, os.O_RDWR | os.O_CREAT | os.O_EXCL)
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python37_64\\Lib\\site-packages\\accesstest_deleteme_fishfingers_custard_y9fomv'`

**Comment by pixobit** [comment]
when I try to install it with py -m pip install instabot-py

**Comment by nickgryg** [comment]
```
Requirements

    Python v3.6 or greater
    Pip v18 or greater
```

If you don't satisfy requirements before installing `instabot-py`, it's not a problem with its installation.

**Comment by pixobit** [comment]
I have python v3.7.5 and pip v20.0.2
