### ISSUE TITLE
Help changing hashtags...

### ISSUE THREAD

**Issue by b4ckbre4ker** [instabot-py/instabot.py#2572]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ ] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Instabot Version?
```
Include here the response of 'instabot-py --version'
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue
Using  python3 -m instabot_py                       

I have setup config with user name pass and hashtags.... hasno issues logging in however it is not using my set hashtags it is liking and following randoms.

**Comment by b4ckbre4ker** [comment]
python3 -m instabot_py

**Comment by nickgryg** [comment]
You should install `instabot-py` using the following pip command:
```
python3 -m pip install instabot-py
```
And after that to use `instabot-py` binary which will be installed from pypi package. I don't sure that `python3 -m instabot_py` works in this case.

**Comment by b4ckbre4ker** [comment]
> `python3 -m instabot_py`

I've done the install instabot-py and doing python3 -m instabot_py logs me in no problem but I cannot seem to update the hashtags even after i've manually changed the files

**Comment by b4ckbre4ker** [comment]
any other advice?

**Comment by nickgryg** [comment]
What do you mean by `manually changed the files`? Why don't start binary file and trying to use `python3 -m instabot_py`?

**Comment by b4ckbre4ker** [comment]
I have tried doing the following 
"Run `instabot-py --create-config` command and a default configuration will be created in your current directory: `instabot.config.yml`. It should be modified according the needs.
You can also run the bot with a different configuration file using `-c` flag: `instabot-py -c myconfiguration.yml`"
but it does not work, so I went into the folder and copied the sample.instabot.config.yml and made instabot.config.yml i set the hashtags to what I want but they keep doing the default... follow4follow cute and f4f

python3 -m instabot_py runs the bot no problem, logs in, likes and follows but just default hashtags

**Comment by nickgryg** [comment]
Everything is clearly described in documentation:
```
Run instabot-py --create-config command and a default configuration will be created in your current directory: instabot.config.yml. It should be modified according the needs.
You can also run the bot with a different configuration file using -c flag: instabot-py -c myconfiguration.yml
```

Please show console output of above actions.
