### ISSUE TITLE
Requirement.txt is not in the file

### ISSUE THREAD

**Issue by tanghush** [instabot-py/instabot.py#2575]
omars-mbp:phoneinfoga omar$ python3 -m pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by nickgryg** [comment]
Yes, it is not in a file `requirements.txt` in this project.

The best way to install `instabot-py` is install it from PyPi directly:
```
python3 -m pip install instabot-py
```
or from sources:
```
python3 -m pip install git+https://github.com/instabot-py/instabot.py
```

Still, you can install it from the file if it's required:
```
python3 -m pip install -r requirements/base.txt
```
