### ISSUE TITLE
Interact from list 

### ISSUE THREAD

**Issue by tobeyond** [instabot-py/instabot.py#2581]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ ] If so, have you tried running the code on your local machine?

```

```

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
``` 
Python 3.7.1
```

#### Pip Version?
```
pip 20.0.2
```

#### Instabot Version?
```
Installed version 0.7.1
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [x] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
Since it isn't possible to scrap users anymore (at least for now), it is possible to include the possibility to follow / unfollow / like / dislike etc users from a list?
It would be way more efficient to target the audience. 
We could, for example, scrap users with different methods and then use a file with the targets. 

Thanks.
```

#### Config

```


```

**Comment by nickgryg** [comment]
Sorry, it's duplicate to #2423 

Cheers!
