### ISSUE TITLE
HTTP error 429 (Could not retrieve number of followers)

### ISSUE THREAD

**Issue by josamgeek** [instabot-py/instabot.py#2582]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ X] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ X] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ X] If so, have you tried running the code on your local machine?

```
Include more details about the environment
```

#### Operating System? (include version)
- [X ] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ X] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [ X] I am using Python 3.6 or above

#### Exact Python Version?
Include here the response of 'python --version' or 'python3 --version'
Python 3.6.10

#### Pip Version?
Include here the response of 'pip --version' or 'pip3 --version'
pip 9.0.3 from /usr/lib/python3.6/dist-packages (python 3.6)

#### Instabot Version?
Include here the response of 'instabot-py --version'
Installed version 0.7.2

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [X ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

After some time of running the bot now I get the following error
"Could not retrieve number of followers of user XY url: https://www.instagram.com/XY/. Status code: 429"

This happens for all new follow attempts. 
I tried to delete the session file and I worked again for some time but than re-appeared.

Also I have the same issue locally and even in my local browser (unable to call user URL).
When I enter the URL in a new private window it works.

Looks like its the HTTP error 429, which means "Too Many Requests"

Questions:
- Is this a bug?
- Am I doing something wrong? 
- Is there a way to pass/doge this?
- Or do I just need to wait some time?

#### Config
start_at_h: 5
start_at_m: 0
end_at_h: 0
end_at_m: 0

debug: 0
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"

tag_list: ["ig_ometry", "stylishmen", "discoverearth"]
tag_blacklist: ["sex", "porno"]

like_per_day: 1101
max_like_for_one_tag: 367
media_min_like: 10
media_max_like: 300
like_followers_per_run: 0

unlike_per_day: 0
time_till_unlike: 259200

follow_per_day: 560
follow_time: 259200
follow_attempts: 10
user_min_follow: 150
user_max_follow: 2400

unfollow_per_day: 560
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false
unfollow_whitelist: []

unwanted_username_list: ["free", "travel", "shop", "store", "sex", "online"]
comments_per_day: 0
comment_list: [
        ["this", "the", "your"],
        ["photo", "picture", "pic", "shot", "snapshot"],
        ["is", "looks", "feels", "is really"],
        [
            "great",
            "super",
            "good",
            "very good",
            "good",
            "wow",
            "WOW",
            "cool",
            "GREAT",
            "magnificent",
            "magical",
            "very cool",
            "stylish",
            "beautiful",
            "so beautiful",
            "so stylish",
            "so professional",
            "lovely",
            "so lovely",
            "very lovely",
            "glorious",
            "so glorious",
            "very glorious",
            "adorable",
            "excellent",
            "amazing",
        ],
	[".", "..", "...", "!", "!!", "!!!"],
    ]

**Comment by nickgryg** [comment]
@josamgeek, thank you for the perfectly described issue! Please update `instabot-py` to version `0.7.6`. It should help you with the further investigation.
