### ISSUE TITLE
Login process crashes - after searching for username in response text 

### ISSUE THREAD

**Issue by MarcoLeko** [instabot-py/instabot.py#2585]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ ] If so, have you tried running the code on your local machine?

```
Just running the bot on my local  mac machine 
```

#### Operating System? (include version)
- [X] macOS
- [ ] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
Darwin DEA046.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
```

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
```
Python 3.7.3
```

#### Pip Version?
```
pip 19.0.3
```

#### Instabot Version?
```
Installed version 0.7.4
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [X] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

When the bot starts and is trying to log in. The Login process seems to be successfull. But it then seems to crash along the way:
```
05 09:49:22,807 - *username* - InstaBot - INFO - Instabot v0.7.4 started at 2020-Apr-05 09:49:22
2020-04-05 09:49:22,807 - *username* - InstaBot - DEBUG - User agent 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36' is used
2020-04-05 09:49:22,807 - *username* - InstaBot - INFO - Trying to login as *username*...
2020-04-05 09:49:34,293 - *username*- InstaBot - ERROR - Login error! Check your login data!
2020-04-05 09:49:34,293 - *username* - InstaBot - INFO - Exit from a program. See you later.
```
After searching in the code specifically in the __main__.py in the login function, I saw the code tries to search for the username in the response.text after a successfull login. And the finder leads everytime to -1. After setting the finder to: ```finder = r.text.find(self.csrftoken)``` instead of ```self.user_login ``` the login was successfull as the csrf_token comes also in by a successfull login.

#### Config

```

start_at_h: 0
start_at_m: 0
end_at_h: 23
end_at_m: 59
window_check_every: 60

verbosity: 2
user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"

tag_list: ["cute", "follow4follow", "f4f"]
tag_blacklist: ["sex", "porno"]

like_per_day: 196
max_like_for_one_tag: 36
media_min_like: 20
media_max_like: 200
like_followers_per_run: 0

unlike_per_day: 0
time_till_unlike: 259200

follow_per_day: 156
follow_time: 259200
follow_attempts: 10
user_min_follow: 200
user_max_follow: 2200

unfollow_per_day: 199
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false
unfollow_whitelist: []

unwanted_username_list: ["free", "travel", "shop", "store", "sex", "online"]
comments_per_day: 0
comment_list: [
        ["this", "the", "your"],
        ["photo", "picture", "pic", "shot", "snapshot"],
        ["is", "looks", "feels", "is really"],
        [
            "great",
            "super",
            "good",
            "very good",
            "good",
            "wow",
            "WOW",
            "cool",
            "GREAT",
            "magnificent",
            "magical",
            "very cool",
            "stylish",
            "beautiful",
            "so beautiful",
            "so stylish",
            "so professional",
            "lovely",
            "so lovely",
            "very lovely",
            "glorious",
            "so glorious",
            "very glorious",
            "adorable",
            "excellent",
            "amazing",
        ],
        [".", "..", "...", "!", "!!", "!!!"],
    ]


```

**Comment by karlkrach** [comment]
I think I have the same problem and i'm also on MacOS, running this locally.
@MarcoLeko – this fix you've found, what do you mean by "setting the finder to: finder = …"?
care to elaborate? :  )

**Comment by MarcoLeko** [comment]
Look for the login function in the instabot.py file there you will see the `finder` variable

**Comment by nickgryg** [comment]
When you login to IG by browser, you definitely see your username in output HTML page. If it's not happening, something wrong with the login, isn't it? The bot checks exactly this when it logs in.
Have you tried to check output HTML page when you had this error? What was written there?

**Comment by karlkrach** [comment]
um, what do you mean by "output html page"? i can manually log-in to my instagram account via browser no problem if this is what you mean.
unrelated, just a thought: as i was wondering whether this might be mac-related, i just tried the same thing on a windows machine but same result. as this is the only thing these two installations have in common: might this have to do somehting with an installation through pyenv?

**Comment by nickgryg** [comment]
We use `requests` python library to communicate with IG like you do via browser. When we send a request to IG, we, actually, get a page in plain text in HTML format which you see in your browser. When you login to IG by browser using your account is not the same when bot logs in there. Do you use different User Agent in bot's configuration comparing to your browser, for example?
So, the only way to see this page, which bot, actually, receives is to print it and check what's is there. May be it reports some error or something.

**Comment by karlkrach** [comment]
not sure if i understand: do you mean when running instabot-py, a browser window should open up? because it certainly is not. 
how do i get to see/print this html showing me what instabot is doing/receiving? ist there maybe a log somewhere?

apart: the user agents should not be the problem, i tried with different ones, also using exactly the same ones as my browser and that did not make any difference…

**Comment by nickgryg** [comment]
> do you mean when running instabot-py, a browser window should open up? because it certainly is not.

No, in simple words, bot uses python library to communicate with IG without a browser to pretend it is a browser

> how do i get to see/print this html showing me what instabot is doing/receiving? ist there maybe a log somewhere?

I've just created a patch to get this information. I cannot test this case, because for me everything works. Please update your `instabot-py` and send me that output privately:
```
python3 -m pip install --no-cache-dir --upgrade git+https://github.com/nickgryg/instabot.py@issue_2585
```
```

**Comment by karlkrach** [comment]
awesome, thank you so much for looking into this! i have a large text file for you, but do not see any email listed in your profile nor any other means of sending you a direct message… how do i get that to you?

**Comment by nickgryg** [comment]
I've just added my email to the profile. Also you can find me in Telegram by the same nickname I have here.

**Comment by nickgryg** [comment]
@karlkrach Thank you for the information you sent me by email. I think I found the reason of this issue.

You put your email address as `username` setting into bot's configuration and really (I didn't know that) you can login to IG using it. But bot is searching your Instagram username on the first page when it logs in. Of course, your Instagram username is different from your email address, that's why it thinks you logged in with issues.
Just put your IG username into configuration and that's it.

**Comment by karlkrach** [comment]
o.m.g., yes, that's it, problem solved. sometimes, it's really the simple things…
again, thank you so much for your help!!
