### ISSUE TITLE
Pythonista (iOS)? 

### ISSUE THREAD

**Issue by crashwins** [instabot-py/instabot.py#265]
This is working great for me, but I don't want to run it constantly on my main system. Anyone know if this could run using Pythonista on iOS (iPhone)? I wonder because there are some dependencies with the .pyc file...Anyone know or try this? Thanks!

**Comment by crashwins** [comment]
https://itunes.apple.com/us/app/pythonista/id528579881?mt=8

**Comment by Faykai** [comment]
yesterday i found this website called pythonanywhere 
but could understand how to run the code over there ( i'm newbie )
If you find how to run I would like to get some help

**Comment by Instaerror** [comment]
AWS Elastic Beanstalk, takes only a few seconds to configure and it costs 3 bux a month. Or free for a year if your a new customer! Ive got a few thousand accounts on it, each with own IP!

**Comment by crashwins** [comment]
Pythonanwhere is still $5...so if you're using it just for an Instragram bot like this one, you might as well pay for Robolike. I'm looking for a free option. Thought Pythonista would do it, but has anyone used this program to run this script?

**Comment by rohit366** [comment]
@Faykai I run this code on pythonanywhere only and it works great. let me know if you need help.

**Comment by crashwins** [comment]
@Faykai I would totally appreciate the help too! Just trying to figure out a way to use this free or for a little fee. Can't justify the $7 charge of RoboLike :)
