### ISSUE TITLE
how to Login, like 1 photo then logout and login with another account.

### ISSUE THREAD

**Issue by onizan** [instabot-py/instabot.py#274]
Hello, at first i want to thanks LevPasha and all everyone are joining this project.

The bot work great but i would just like to use it also in other way:

Is it possible to login, like just one photo, logout and repeat the same code but changing the account name to login in the same example.py file? 

I m sorry if it s stupid to ask but i really will be grateful if someone can help me with this.

**Comment by wrackful** [comment]
if you want login and like one post and logout :
bot = InstaBot(login="behnam.em", password="********")
bot.like(media_id)
bot.logout()

**Comment by onizan** [comment]
@wrackful really thanks for your answer. I tried this 1 month ago and it didn t worked.

tried again now and it worked great.

really thanks you and sorry that i m being stupid and opened this thread instead of try it again after some changes.

**Comment by wrackful** [comment]
your welcome,thanks of LevPasha,my self have problem with find recent media id for specific user id :(
you have good time <3
