### ISSUE TITLE
Wont to work when i start script in Terminal

### ISSUE THREAD

**Issue by vukashinp** [instabot-py/instabot.py#275]
`Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from instabot import InstaBot
  File "/Library/insta/src/instabot.py", line 4, in <module>
    from userinfo import UserInfo
  File "/Library/insta/src/userinfo.py", line 4, in <module>
    import requests
ImportError: No module named requests`

Thats what i see in my terminal. What to do?
I changed username and password in example.py

**Comment by wrackful** [comment]
you must use python 3 ,are you sure used python 3 ?

**Comment by vukashinp** [comment]
I installed requests libs, its working now! :)

**Comment by wrackful** [comment]
module request default installed for python3,ok ,good luck

**Comment by tbudd23** [comment]
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from instabot import InstaBot
ImportError: No module named 'instabot'


Any ideas?

**Comment by tbudd23** [comment]
I installed the request libs

**Comment by kundanvishen** [comment]
@tbudd23 please share the output of `ls` command (macOS) or `dir` command (windows).

**Comment by ChipWolf** [comment]
#442
