### ISSUE TITLE
[feature request] Setting start and end hour

### ISSUE THREAD

**Issue by yepes** [instabot-py/instabot.py#283]
I think it would be nice being able to set up the start and end hour so we can leave the bot running the whole day, but it will be working only when we want.

A simple start and end hour will be enough for now.

Any thoughts?

**Comment by yepes** [comment]
I've just created a simple PR that implements this:
https://github.com/LevPasha/instabot.py/pull/284

**Comment by Instaerror** [comment]
import time

while str(time.strftime("%H")) >= "07" or str(time.strftime("%H")) <= "23":
          botstuff
else:
          sleep.timer(3600)

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
