### ISSUE TITLE
get photo ID's by geotag and followings of user

### ISSUE THREAD

**Issue by niko9797** [instabot-py/instabot.py#290]
Hi, thanks everybody who made possible this code.I'm trying to understand and improve the code, i specially would love to add the way to get a list of media from geotag and list of followings of a user(like everybody). As far as i understand for both features i need to create two methods similar to get_media_id_by_tag() (If im not wrong) that ask instagram servers for the info. The problem is i dont know nothing about the form of the request to the instagram server, neither the form how the data comes back. if somebody have some info about the topic would be really apreciated. Thanks

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
