### ISSUE TITLE
Like all photos of a specific user

### ISSUE THREAD

**Issue by 01egi4** [instabot-py/instabot.py#292]
How can I like all photos of a given user?

Do I have to use bot.new_like_all_exist_media()? If yes, where do I place user IDs? In the instabot.py media_by_user = []?

**Comment by barneyvaughan** [comment]
I can see some functions to pull them in but can't manage to get them to work, I'll keep you posted if I manage to create a mod to get this running as it's something I need too! Or if the creator could hop in that'd be grand.

**Comment by 01egi4** [comment]
Thanks!

**Comment by virginsince1997** [comment]
I anticipate

**Comment by barneyvaughan** [comment]
**Add this code into the Userinfo.py file:**

       `def` get_media_by_login(self, user_name):
        url_info= self.url_user_info % (user_name)
        info = self.s.get(url_info)
        all_data = json.loads(info.text)
       
        the_media = [];
        medias = all_data['user']['media']['nodes']
        
        for rawmedia in medias:
            the_media.append(rawmedia['id'])
        return json.loads(the_media);`

**Then in example.py:**
Import it
`from userinfo import UserInfo`

**Then add a new option to the Mode list**

```
elif mode == 9 :
        ui = UserInfo();
        medias = ui.get_media_by_login("barney_vaughan")
        ex = 1;
        for media in medias:
            bot.like(media)
            print("Liked media %i of %i" %(ex, len(medias)))
            ex = ex + 1;
            time.sleep(10);
```


Word of warning this only does the 12 most recent in a timely fashion.

**Comment by barneyvaughan** [comment]
I will upload a repo of this to my git in a moment.

**Comment by barneyvaughan** [comment]
A more refined version to my Git in a moment.*

**Comment by virginsince1997** [comment]
Is there any way I can Automatically get username from my feed and use this
action, instead of manually inputting ids

**Comment by barneyvaughan** [comment]
**Here we go gang:**
[Refined Version Here](https://github.com/barneyvaughan/instabot.py)

**Comment by virginsince1997** [comment]
Awesome :) although I was thinking if there's a way to scrape users from
feed or, people who just started following u, and use this function with it

**Comment by virginsince1997** [comment]
I mean instead of inputting iDs, we should be able to scrape a particular
page, like recent feed, or people who started following you back, there's a
higher chance they would reciprocate

**Comment by barneyvaughan** [comment]
There probably is by crowbaring the new function into the get all followers function. Although, I haven't had any time to check out the other functions that are included in this project. 

If I ever get to it I'll let you know!

**Comment by virginsince1997** [comment]
Alright thanks

**Comment by VictorHartman** [comment]
@barneyvaughan solution doesn't seem to be working with private accounts, even though the account used is a follower of the desired account.

**Comment by muratcesmecioglu** [comment]
@VictorHartman You can try my fork for private accounts. I'm using now and it works.

**Comment by MarkMcPartland** [comment]
Hi @muratcesmecioglu  I tried your fork but get the following outut on first user:
now Username1 photos are liking
Except on get_media!
File "....example.py", line 101, in <module>
for media in medias:
TypeError: 'int' object is not iterable

Any ideas?
regards

**Comment by muratcesmecioglu** [comment]
@MarkMcPartland Did you set usernames in "userlist" array on 96th line in example.py?

**Comment by MarkMcPartland** [comment]
@muratcesmecioglu yes sorry (I just dummied that out in post above)
this is what I had
 userlist = ['txmum','a_boy_and_his_dad']

**Comment by muratcesmecioglu** [comment]
![image](https://cloud.githubusercontent.com/assets/12040730/22832628/cf519e26-efbf-11e6-852e-c218945bdb46.png)

İ just download my fork and run. It can't like txmum because i am not following. But as you see, it can like "a_boy_and_his_dad" user.
I'm using python 2.7. Can you try this version?

**Comment by MarkMcPartland** [comment]
Many thanks @muratcesmecioglu 
I was on 3.4, but installing and running on 2.7 works!

Also noted that the count of results updated is out by 1 (only goes up to 2 of 3 instead of 3 of 3)
You may want to change: if k == last_x_photo: to if k == last_x_photo + 1:
?

Cheers

**Comment by muratcesmecioglu** [comment]
@MarkMcPartland You are right. I changed the codes. But i like my "if"s simple, so i started k variable from 0 :)
I don't know why it's didn't work on 3.x. Maybe it's encoding problem that @LevPasha mentioned in readme but i didn't try to change encoding yet.

**Comment by rorloj** [comment]
how can I set it to like 5, 3 or any other amount of recent posts instead of 12?

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by vijuc895** [comment]
hi @barneyvaughan  tried to use above code but I am getting user: keyword error in  medias = all_data['user']['media']['nodes'].please help me out
