### ISSUE TITLE
it just stops when i launch the example.py

### ISSUE THREAD

**Issue by bouaablli** [instabot-py/instabot.py#295]
it just stops when i launch the example.py, doesnt show anything, is it normal ?

**Comment by mattkcole** [comment]
Make sure you have installed requests. 

See the readme:
Run the command `pip3 install requests` if you use Python 3, or type `pip install requests` if you use Python 2.

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
