### ISSUE TITLE
where can i find the expected log file

### ISSUE THREAD

**Issue by roger125** [instabot-py/instabot.py#30]
why i can NOT find the expected log file(1.log) when i do the beneath setting?
============start==============
# Log setting.

```
log_file_path = 'C:/Users/Administrator/Desktop/'
log_file = '1.log'
```

============end==============
thanks.

**Comment by roger125** [comment]
and one more point: after i set 
like_per_day=1000
follow_per_day=200

the log in the console only shows the like action, without the follow action(not finished the whole process yet, but i only see the like action done without the follow action happened after around 10 minutes), 
does it with the sequence that: follow action will only begin after like action finished?

thanks.

**Comment by LevPasha** [comment]
@roger125 about log file - you should write `log_file = 0`. Bot will create file in destination folder himself.
About follow - something wrong. It must be: like, follow, like,like,like,like,like, follow, like .... somethring like this. Show me your full code.

**Comment by shaharbukra** [comment]
Ive tried to change the log_file to 0, and it create me the file in the same location as the PY files but the file remains empty..
did you try to run this code on windows?

**Comment by LevPasha** [comment]
@shaharbukra hi! It should create file in `log_file_path = 'C:/Users/Administrator/Desktop/'` i don't test it on Windows, but i think it must work. Maybe it is some Windows permissions problem?

**Comment by roger125** [comment]
@LevPasha, hi! 

1. i've uploaded the zip file(just the instabot.py file), it can be run successfully with inputting my userid/password, and i have amend it into "log_file = 0" as what you replied,  but it still don't create the expected log file in my Windows7 64 laptop;

2. about the follow action, i still don't get it, pls check it what's wrong here(basically i just change the log_file_path, and the value within the class def __init__(), nothing else as i can see);

thanks.

[instabot.zip](https://github.com/LevPasha/instabot.py/files/195224/instabot.zip)

**Comment by roger125** [comment]
@LevPasha, hi!
   this issue is closed without my questions be replied, so is there any reason?

   thanks.

**Comment by LevPasha** [comment]
Sorry, my mistake.

**Comment by roger125** [comment]
so how about the solution? is it a little complicated?

thanks.

**Comment by polaroi8d** [comment]
Hey @roger125 do you still have the problem?

**Comment by roger125** [comment]
hi @polaroi8d , since then i havn't tried this python program, so yes, there's still the problem i should say, as i asked above, @LevPasha still havn't replied the expected answer.

**Comment by LevPasha** [comment]
@roger125 @polaroi8d it is hard to me test on WIN. I think this is permission problem (try to run as Admin), because in Linux all go fine.
