### ISSUE TITLE
Magic URL

### ISSUE THREAD

**Issue by ArtemBernatskyy** [instabot-py/instabot.py#301]
Adding "?__a=1" to any url on www.instagram.com returns json with page's data.

example:
https://www.instagram.com/explore/tags/designateddriver/
https://www.instagram.com/explore/tags/designateddriver/?__a=1

**Comment by gilllambrigts** [comment]
Interesting, to say the least. 👍

**Comment by ChipWolf** [comment]
We do use this already in places, but I agree there are places we could make more use of it.

**Comment by makeitviral** [comment]
Hola no entiendo que es (#301). Agradesco su ayuda

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
