### ISSUE TITLE
I keep getting this error after running the bot (MODE 0) for some minutes

### ISSUE THREAD

**Issue by virginsince1997** [instabot-py/instabot.py#304]
File "/home/oyetomiabiodun/src/insta
bot.py", line 600, in new_auto_mod_com
ments
    and self.check_exisiting_comment(s
elf.media_by_tag[0]['code']) == False:
  File "/home/oyetomiabiodun/src/insta
bot.py", line 636, in check_exisiting_
comment
    all_data = json.loads(check_commen
t.text)
  File "/usr/lib/python2.7/json/__init
__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decode
r.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=
_w(s, 0).end())
  File "/usr/lib/python2.7/json/decode
r.py", line 384, in raw_decode
    raise ValueError("No JSON object c
ould be decoded")
ValueError: No JSON object could be de
coded
>>>

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
