### ISSUE TITLE
Unfollow

### ISSUE THREAD

**Issue by DudyDudy** [instabot-py/instabot.py#306]
Hello team !

First thank you for your work.
I wanted to know if there is a way to not unfollow. Half the follow are unfollowed when I stop the bot and sometimes it follow again the ones it already unfollowed. Even when I set 0 for unfollow_per_day. The cleaning function is really necessary ? 
Have a good day guys

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
