### ISSUE TITLE
Program stuck

### ISSUE THREAD

**Issue by duedares11** [instabot-py/instabot.py#307]
Trying to login as #USERID

Login error! Check your login data!
Completed populating user blacklist with ID
//Looped here

**Comment by gaijinjoe** [comment]
Me too! Just happened right now...

**Comment by polaroi8d** [comment]
Dont you have a two steps auth?

**Comment by scazzy** [comment]
Same error. Works well locally, but doesn't on heroku.

**Comment by drewhga** [comment]
It appears Instagram is cracking down on bots especially those run on Cloud
services. I tried changing the runtime locale in Heroku, this worked for a
while then this error started appearing again. So I finally bought a paid
proxy online and used the proxy in the bot and so far so good. Else you can
get a cheap Android phone and run it using clients like Qpython.

**Comment by scazzy** [comment]
@drewhga quite possible. But the same would work fine if I run it locally using `heroku local` or using the heroku `bash` which ideally is the same as running from the server

**Comment by drewhga** [comment]
Interesting. Which processes does your Procfile declare?

**Comment by scazzy** [comment]
@drewhga tried both web and worker in vein

**Comment by drewhga** [comment]
Use bot

**Comment by strivext** [comment]
Not work in my account :(

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
