### ISSUE TITLE
Error on checking comments

### ISSUE THREAD

**Issue by rudnetto** [instabot-py/instabot.py#308]
Hello, guys.

I'm facing this error message sometimes:

`Trying to follow: 4177479494
Traceback (most recent call last):
  File "patyybo.py", line 59, in <module>
    bot.new_auto_mod()
  File "/home/rudnetto/vlmedia/bots/instabot.py/patyybo/instabot.py", line 525,$
    self.new_auto_mod_comments()
  File "/home/rudnetto/vlmedia/bots/instabot.py/patyybo/instabot.py", line 578,$
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "/home/rudnetto/vlmedia/bots/instabot.py/patyybo/instabot.py", line 603,$
    all_data = json.loads(check_comment.text)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)`

I guess that the variable `check_comment` in line 602 of instabot.py, sometimes has the value None. So when the json tries to read it and assign to `all_data` variable, the error is returned.

I added a simple IF to check if the variable is None or not, then proceed with the method.

`def check_exisiting_comment(self, media_code):
        url_check = self.url_media_detail % (media_code)
        check_comment = self.s.get(url_check)
        if check_comment is None:
            all_data = json.loads(check_comment.text)
            if all_data['media']['owner']['id'] == self.user_id:
                self.write_log("Keep calm - It's your own media ;)")
                # Del media to don't loop on it
                del self.media_by_tag[0]
                return True
            comment_list = list(all_data['media']['comments']['nodes'])
            for d in comment_list:
                if d['user']['id'] == self.user_id:
                    self.write_log("Keep calm - Media already commented ;)")`

Hope it solves the problem. If anyone has any other idea, please tell me :)

**Comment by virginsince1997** [comment]
can you send me your modified instabot , the indentaions are gone

**Comment by fireuniversal** [comment]
Solution is at #438 .
Leave a like & comment after it fixes the problem. 
Enjoy 👍

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
