### ISSUE TITLE
Follow Followers

### ISSUE THREAD

**Issue by DanielSokil** [instabot-py/instabot.py#312]
Where would i go about to add this feature in the bot?.
Like The Last 2 Pictures Or Media Of Followers That Follow A Specific Profile or Account.

So basically like the last 2 pictures of all the profiles that follow my girlfriend.

Thanks Ahead.

**Comment by DanielSokil** [comment]
@LevPasha

**Comment by LevPasha** [comment]
@DanielSokil maybe later.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
