### ISSUE TITLE
Bot is too aggressive

### ISSUE THREAD

**Issue by brumie** [instabot-py/instabot.py#313]
bot is too aggressive no matter I changed like from 1000 to 10 it will like photos every second, most stable are 598edec

**Comment by questionhere** [comment]
Similar issue here. No matter what value the like_per_day is set at (1000 or 500) and the time I change the bot to run in (0 to 23 hours, or 13 to 14 hours), the like rate does not change.

I know the formula says that it is 24 * 60 * 60 / likevalue but it does not seem to change when I change example.py's like_per_day value

**Comment by gaijinjoe** [comment]
Me too, seems like they blocked my like because of this (it was set to 1000 and liked all of them in few minutes), and now it never unfollows nor follow anyone, seems like the last update is pretty buggy :S

**Comment by LevPasha** [comment]
@nivong ?

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
