### ISSUE TITLE
error message 

### ISSUE THREAD

**Issue by thomas10154** [instabot-py/instabot.py#317]
Hi, sorry if this is a rookie question but im pretty new to this. 

When I fill in my username and password and then run the examply.py I get the error message:
File "example.py", line 6, in <module>
     from instabot import Instabot 
File "C:\...\instabot.py-master\src\instabot.py", line 138
    if self.bot_running_hour_end < self.bot_running_hour_start:
                                                                                                 ^
tabError: inconsistent use of tabs and spaves in indentation 

but I havent changed anything in instabot.py. Can anybody please explain what im doing wrong?

**Comment by j3robinson1** [comment]
This is caused by the mixing of spaces and tabs at line 138.
ive attached a zip of the file after I made the change. try and unzip it and copy and replace it inside the src folder.
[instabot.zip](https://github.com/LevPasha/instabot.py/files/659086/instabot.zip)

**Comment by thomas10154** [comment]
Thank you j3robinson1 this fixed my problem :)

**Comment by ArgonQQ** [comment]
@j3robinson1 Is there a pull request for this? Worked perfect!
