### ISSUE TITLE
[feature request] Max followers in user_blacklist

### ISSUE THREAD

**Issue by manoufeb** [instabot-py/instabot.py#318]
In order to not like picture were the author've got lot of followers. 

So it could be so cool if we can blacklist user were follower > 500 for example.

Cool bot !

**Comment by avirajkhare00** [comment]
@manoufeb Can you please explain in more details?

**Comment by vinceze** [comment]
Very interested too! Basically the same feature as the one for Likes. You don't want to like media with more than 100 likes. The same way you don't want to follow people with too many followers because they are unlikely to follow back

**Comment by guybehar** [comment]
I agree, **this is a very important feature**. I know I'm not telling you something you did not know, but Instagram users who have managed to get many followers tend not to follow users with a small number of followers. They also prefer a large gap between the number of their followers and the number of users they follow. It's a status symbol.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
