### ISSUE TITLE
Instagram sometimes returns error pages while requesting URLs

### ISSUE THREAD

**Issue by rockandwoods** [instabot-py/instabot.py#322]
I want to put few Instagram account behind a proxy and use the script. But most of time (> 90%) the pages being fetched by `get_media_id_by_tag()` gets error pages from Instagram.
See https://github.com/LevPasha/instabot.py/blob/master/src/instabot.py#L294

It's bit strange. Plain direct requests/functions gets proper pages/json from Instagram but most of time Instagram returns Error pages and hence mostly `Except` on above method.

Has anyone else encountered same issue? Any suggestions?

**Comment by HenryCooperGithub** [comment]
#815
