### ISSUE TITLE
Bot just stops working

### ISSUE THREAD

**Issue by AGZ98** [instabot-py/instabot.py#324]
So, sometimes, the bot will just stop working, regardless of mode. This is not an issue with my internet connection as I've noticed similar problems on Amazon EC2. Anyone else experience this?

**Comment by virginsince1997** [comment]
Yes, when updating user list this issue occurs or it just freezes,, I think
you should kill the bot and restart,,, using a script

**Comment by AGZ98** [comment]
What kind of script @virginsince1997 ?

**Comment by Killerherts** [comment]
ru in windowa

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
