### ISSUE TITLE
Bot mode 0 always stuck on one user

### ISSUE THREAD

**Issue by mrsamse** [instabot-py/instabot.py#325]
When I use the example.py and set the like_per_day parameter to 0 the bot is always stuck on one user and the console tells me "trying to follow: *a random user*". I want the bot only to follow people and then unfollow after a certain time.

Greetings samse

Ps. I'm new to python.

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
