### ISSUE TITLE
Predefined user list 

### ISSUE THREAD

**Issue by khabulkhan** [instabot-py/instabot.py#328]
If possible, I would like ideas for change the code by tag > by user list:

1) Follow the last (10,20) followers of a certain user (Predefined user list string)
2) Like in the Last photo of the users who gave like in the last post of a certain user (Predefined user list string)
Example: Jhon and mary like post jackchan.
I (bot cod) like  the Last post of Jhon and Last post of mary

I'll try do it myself if you point the way
I know visual BASIC, not python

thanks

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
