### ISSUE TITLE
Trying to unfollow #%i

### ISSUE THREAD

**Issue by ohld** [instabot-py/instabot.py#337]
This string appears in log:

> Trying to unfollow #%i: 

There should be an ID instead of '%i'

**Comment by LevPasha** [comment]
Show screenshot

**Comment by ohld** [comment]
https://github.com/LevPasha/instabot.py/blob/master/src/instabot.py#L566

**Comment by Killerherts** [comment]
Ive noticed this as well if you modify the unfollow time in line 145 we tried to factor in the follow time by

self.follow_delay = (self.time_in_day - self.follow_time) / self.follow_per_day

**Comment by DrCherry** [comment]
This seems like low-hanging fruit.  I'll see if I can't close this one.

**Comment by DrCherry** [comment]
This is part of new_auto_mod_unfollow() which is a little bit confusing.   I'm testing my change now.

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
