### ISSUE TITLE
Get new likes and followers of acc?

### ISSUE THREAD

**Issue by ohld** [instabot-py/instabot.py#351]
Hi there,
Is it possible to get new mentions, likes, followers and comments like we can in web version? 
I can't find this method as implemented in api.
It would be very helpful to make statistics of accounts. 

So for example when you go to instagram.com and press "heart" in the right corner you can get the list of new likes, follows etc.

**Comment by HenryCooperGithub** [comment]
This library does not offer an API , neither uses the official Instagram API . **Closed**
