### ISSUE TITLE
Divide code to "core", "main functions" and "modifications"

### ISSUE THREAD

**Issue by ohld** [instabot-py/instabot.py#352]
Hi there.
I think It would be better for future contributors if the code will be divided into these parts:
 
1. core functions (work with the requests)
2. main functions (like, unlike, follow, comment etc.)
3. mods (contributor's or user's code of using main functions)

Now the most of this 3 types of functions are implemented in one file Instabot.py.
Dear contributors, can you do this?

**Comment by DrCherry** [comment]
Right now a large number of what you're calling functions are methods of the InstaBot class.   Many of them operate by manipulating the object via the reference "self.".

I think to move these functions outside of the object might take significant refactoring.  It wouldn't make sense to manipulate the object itself necessarily as you'd be dealing with a reference.  Python experts help me out here.

**Comment by davisonio** [comment]
good idea
