### ISSUE TITLE
Unfollow is not working?

### ISSUE THREAD

**Issue by Alexlander** [instabot-py/instabot.py#368]
Tried a lot of difference settings, I can't let it work. 
RIght now my unfollow settings are unfollow_per_days=100, unfollow_break_min=15, unfollow_break_max=90

**Comment by mactrash** [comment]
Seems not working... anyone can confirm?

**Comment by Alexlander** [comment]
Forgot to mention it does unfollow after a while, but even if I have my following and likes very low it still takes a lot of time. I'd like to unfollow a lot of people and doing it all manually is faster right now 🤣

**Comment by loganyc1934** [comment]
In my case it initially unfollowed at a very slow pace, and then stuck forever and didn't do anything. In the code comment "burst mode" is mentioned and it is advised to use mode 5 only for a short period to avoid getting banned. But I don't see how there is a "burst mode". I set the unfollow break min max to be very small, number of unfollow to be 999 and number of follow to 0. From the code it seems there is no logic in mode 5 that works as burst mode.

Also my problem is that I use Daemon to make it a background process. log_mode = 1 doesn't log anything to file beyond `blacklist populated`, so I couldn't see what was wrong. Anyone has any advice?

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
