### ISSUE TITLE
Exclude some tags?

### ISSUE THREAD

**Issue by amir4949** [instabot-py/instabot.py#37]
is there anyway to exclude some tags that i dont want like or comment ?

**Comment by LevPasha** [comment]
@amir4949 you set tags `tag_list=['cat', 'car', 'dog']` that you want to like (and etc). I you don't want to like some tag - don't write this.

Or you want list of tag, that if bot find in media - ignores?

**Comment by amir4949** [comment]
> Or you want list of tag, that if bot find in media - ignores?
yes, for example i set tag 'photography' to robot like it, but may a picture has 'photography' tag and also has 'portrait' tag! i want that robot ignore this picture.
is it possible?

**Comment by LevPasha** [comment]
Ok, i will add this in future.

**Comment by mieburungdara** [comment]
Waiting for this: )

**Comment by LevPasha** [comment]
@mieburungdara as I...
