### ISSUE TITLE
Bot freezes after following a private account

### ISSUE THREAD

**Issue by mugenop** [instabot-py/instabot.py#371]
The bot gets stuck after some time.
When I checked the last followed user, it happened to be a private user with a pending request. Maybe, this is what is freezing the bot.
Is there a way to check if user is private and discard it from user list used by the bot?

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
