### ISSUE TITLE
Bot is commenting on blacklisted users' media

### ISSUE THREAD

**Issue by ig61** [instabot-py/instabot.py#375]
Hi,

As above. It's weird since it avoids them and not liking media owned by the blacklisted users and not following them, but it still comments on media owned by them.

Any ideas how to fix it?

Thanks!

**Comment by ig61** [comment]
Any idea how can we sort this out?

**Comment by ekremgurdal** [comment]
It's weird. Same bpt does not do this. When it encounters with a blacklisted user's media, it alerts. Are you sure you entered that blacklisted user's account name?

**Comment by ig61** [comment]
Yep, I'm sure. Tested with 2 accounts, they do comment on blacklisted media, but do not like it.

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
