### ISSUE TITLE
Additional Feature: Followers Like Management

### ISSUE THREAD

**Issue by brian-jeon** [instabot-py/instabot.py#377]
Hi,

I love your work because it works great and very user-friendly especially for those who are not too experienced in Python.

I wanted to add a feature that likes every photo of my followers to keep them in loop anytime they upload new photos, but I'm not sure where I could add/start on that...any help would be appreciated.

Warmest regards,

Brian

**Comment by ekremgurdal** [comment]
Bot unfollows people based on recent feed. I think bot can like these feeds with a single update. If developers have no time for this, I try to develop.

**Comment by Marcgh1** [comment]
This pull request #355 likes last x photos of the users in a user list , so if you could get a list of your followers and put that in the code ,and put that in a while loop you should basically have a code running that likes all the photos of your followers

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
