### ISSUE TITLE
mode 2 not working

### ISSUE THREAD

**Issue by bhavyaanonymous** [instabot-py/instabot.py#382]
mode 2 is not working it is showing the logs but not following

**Comment by DerWolf12** [comment]
I have the same problem, have you resolved it?

**Comment by ChipWolf** [comment]
Be careful tweaking the follow per day values if you don't know what you're doing.
The defaults are set reasonably accurately, anything higher will most likely lead to soft or hard bans

**Comment by taradell** [comment]
Hi guys! any update about Mode 2?
I am using the latest version of the bot and it is still not working.
Thank you guys!

@ChipWolf @DerWolf12 @bhavyaanonymous @LevPasha

**Comment by ugurozturk** [comment]
Closing this because there is nothing to track. mode 2 is not working is not enough
