### ISSUE TITLE
Log shows following successfully even thought it's not

### ISSUE THREAD

**Issue by assafelovic** [instabot-py/instabot.py#383]
Hey everyone,

Great job on this fantastic bot. The script has been running pretty smoothly for about 2 weeks. All of sudden since yesterday the bot stopped following users. Technically i can see from the logs that it is following by this:
Trying to follow: X
Followed: X #3.
However in reality when I check in my profile there is no change. Anyone know what might be the issue?

**Comment by DanielSokil** [comment]
You have to watch the API limits of Instagram. Instagram private API allows 60 follow/unfollow requests per hour.

**Comment by gferrer807** [comment]
I noticed that just yesterday in terms of the limit lol but has anyone figured out this unfollowing issue? It doesn't seem to be working at all. @DanielSokil

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
