### ISSUE TITLE
Follow/Unfollow same account

### ISSUE THREAD

**Issue by certainlyjacked** [instabot-py/instabot.py#385]
It seems that the bot often follows(unfollows a specific user multiple times. Is there a way to fix this?

**Comment by MrHakala** [comment]
+1

**Comment by lotusrs** [comment]
The bot resets the data every time it ends.

**Comment by ChipWolf** [comment]
The database fix might be a suitable solution.

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
