### ISSUE TITLE
Bot is giving like in blacklisted hashtag (possibly hashtags in comments)

### ISSUE THREAD

**Issue by lpdx** [instabot-py/instabot.py#390]
Scenario: I'm using the bot in mode 1 and just to give like in specific hashtags (all follow and unfollow functions are set to 0). 

Issue:
Sometimes the bot likes a post with blacklisted hashtag.
(maybe posts where people place hashtags in the comments)

Example: 

` tag_blacklist=['gopro']`

picture with #gopro is liked when it's not in the post description section.

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
