### ISSUE TITLE
'Except on media' for feed grabber from recent_media.py

### ISSUE THREAD

**Issue by BitJunky** [instabot-py/instabot.py#410]
The latest instagram update have changed the data structure and is causing except on media for get_media_id_recent_feed ( ) from recent_media.py

**Comment by shurco** [comment]
I have the same problem as he :(

**Comment by ChipWolf** [comment]
Full traceback please

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
