### ISSUE TITLE
how does the whitelist work?

### ISSUE THREAD

**Issue by LeonardSylvester** [instabot-py/instabot.py#413]
what exactly happens to the users in the whitelist?

**Comment by dadealer** [comment]
The bot will not unfollow them

**Comment by ratacat** [comment]
How can we grab the list of users an account is currently following to
populate the whitelist with?  The UserInfo class doesn't seem to be
working...?

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
