### ISSUE TITLE
Reduce Waiting Time

### ISSUE THREAD

**Issue by majordwarf** [instabot-py/instabot.py#415]
Everytime after bot follows a user it show a huge wait time >200 seconds.

```
 * Trying to follow 3579428650...  success
	Waiting 542.0 seconds

```

Any Solution?

**Comment by LevPasha** [comment]
What mode?

**Comment by majordwarf** [comment]
Mode 0, by you.

**Comment by ChipWolf** [comment]
Looks like intended behavior, it's probably spacing out follows based on the limit set in `example.py`

**Comment by majordwarf** [comment]
Any way to reduce it?

**Comment by ChipWolf** [comment]
Not recommended, but increase the follow limit in `example.py` any higher than ~450 and you're at risk of a ban.
