### ISSUE TITLE
Bug at Unfollow: except on get info

### ISSUE THREAD

**Issue by dadealer** [instabot-py/instabot.py#418]
If the bot try to unfollow a user who have following=0, the bot put out the error "except on get info"

**Comment by LevPasha** [comment]
@dadealer and what? Script die?

**Comment by dadealer** [comment]
Sry. The bot breaks the unfollow process but keep working. But the bot will not unfollow these users

**Comment by dadealer** [comment]
@LevPasha checkout the fix on my account

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
