### ISSUE TITLE
mode 5 - user info list is empty!!!

### ISSUE THREAD

**Issue by trevorgit** [instabot-py/instabot.py#420]
Hi,

I want to make use of Mode 5, if I start it in mode 5 I get "user info list is empty!!!" 

The Mode 0 seems to have a follow/unfollow leak, now having to look at mode 5 to clean things up, I am not going to use an app to do this 200 at a time. 

or has anyone come up with settings that work well to train your following?

Output:
username login success!
Completed populating user blacklist with IDs
username : Get media id on recent feed 
Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx

**Comment by trevorgit** [comment]
cant you add a mode that creates a database of the users you follow, then setting the unfollow rate on that database?

**Comment by kundanvishen** [comment]
@trevorgit PR is accepted.

**Comment by ugurozturk** [comment]
let us know if the error still shows.
