### ISSUE TITLE
Problem with Index.php - instabot not starting

### ISSUE THREAD

**Issue by Markus978** [instabot-py/instabot.py#421]
Hi there, 
I don't get the instabot to run opening 192.168.x.x/instagrambot/instabot.py/index.php in Safari.
When I run it, unfortunately nothing happens on the Pi. 
I run it on osmc/kodi/jessie on a raspberrypi. 
I installed apache with `sudo apt-get install apache2 `
Then I installed PHP with `sudo apt-get install php5 libapache2-mod-php5`

here is a screenshot of my index.php
<img width="462" alt="screenshot 2017-03-12 08 42 31" src="https://cloud.githubusercontent.com/assets/6689893/23830003/1f5655b8-0700-11e7-8377-b5b1433efbaf.png">

If I SSH into the PI and try to open the index.php, I get the following error message

> root@osmc:/var/www/html/instagrambot/instabot.py# php index.php 
PHP Parse error:  syntax error, unexpected 'as' (T_AS) in /var/www/html/instagrambot/instabot.py/index.php on line 4

However, If I run the example.py it seems to work fine. have a look..

> root@osmc:/var/www/html/instagrambot/instabot.py# python example.py 
Instabot v1.1.0 started at 12.03.2017 08:20:

>Trying to login as xxx...

>xx login success!
Completed populating user blacklist with IDs
Get media id by tag: fashion
Trying to like media: 1468704510653722175
Liked: 1468704510653722175. Like #1.
Trying to follow: 190065358
Followed: 190065358 #1.
...

Do you have any clue on what is wrong? Your help would be highly appreciated. Please let me know if you need further information.

Many thanks,

Markus

**Comment by LevPasha** [comment]
O_o

**Comment by Markus978** [comment]
I think I figured it out just now...
I removed the $ in front of `foreach...` within the index.php file. 
That seems to have caused the parse error.

Now I have to figure out how to add a second insta-account to the bot. 
Hope this helps anyone else. New to this. 
Take care, Markus

**Comment by ChipWolf** [comment]
What's the index.php for?

**Comment by Markus978** [comment]
It is used to start the example.py by browser. 
I am not using it anymore though and switched to a cronjob instead that starts my script on reboot. Way more convenient. 
Currently I just get Mode=0 working. Follow/Unfollow seems not to work for whatever reason and I get stuck on all other modes.

**Comment by kundanvishen** [comment]
@polaroi8d this issue can be closed.
