### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by JonasDrain** [instabot-py/instabot.py#426]
if i try to run the example i get follow Error:

Hint: Username & Password are correctly. 
Its the stock example.py

root@cloud1******2:~/insta# python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from instabot import InstaBot
  File "/root/insta/src/instabot.py", line 4, in <module>
    from userinfo import UserInfo
  File "/root/insta/src/userinfo.py", line 4, in <module>
    import requests
ImportError: No module named requests

**Comment by luisramirez-m** [comment]
Error:
```
import requests
ImportError: No module named requests
```

I put "request" on search, and show me:

https://github.com/LevPasha/instabot.py/issues/157#issuecomment-240065232
https://github.com/LevPasha/instabot.py/issues/294#issuecomment-263655576

**Comment by ChipWolf** [comment]
`pip install requests`

**Comment by nieves8** [comment]
i puted pip install requests and the answer is : invalid function, what i have to do? thanks

**Comment by ChipWolf** [comment]
install python
