### ISSUE TITLE
Only like picture content

### ISSUE THREAD

**Issue by lpdx** [instabot-py/instabot.py#432]
[enhancement]
Once we don't keep looking to the liked posts, it would be nice the possibility to like just pictures and no video content because it's fastest to evaluate a picture than a video.

There is a marker in JSON like `"is_video": false`

Look at this JSON: [https://www.instagram.com/explore/tags/designateddriver/?__a=1](url)

**Comment by ChipWolf** [comment]
Can you explain what you mean by `it's fastest to evaluate a picture than a video.`

**Comment by lpdx** [comment]
Hi @ChipWolf .
Fastest for user evaluation point of view.  Sometimes the bot likes content out of hashtag filters range, as pointed here #390 .

So, a quick view in a liked picture is sufficient to decide dislike it or not. With video you need to look it all.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
