### ISSUE TITLE
Auto message to new followers!

### ISSUE THREAD

**Issue by edrizo** [instabot-py/instabot.py#436]
Hello everybody!
I've been using it and very satisfied with the achievments using this tool.

But, I was wondering about onething that wold make it even better:
Is there a way to write an automatic message to those who start to follow you?

**Comment by artemdumanov** [comment]
+
I am so interested in this ability too

**Comment by filippovilla** [comment]
Use this website: holr.co

**Comment by artemdumanov** [comment]
I tring to implement my own solution

2017-04-08 20:23 GMT+03:00 filippovilla <notifications@github.com>:

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
