### ISSUE TITLE
[SOLUTION] for ValueError: No JSON object could be decoded while using bot.

### ISSUE THREAD

**Issue by fireuniversal** [instabot-py/instabot.py#438]
**Solution** for those who are facing **"ValueError: No JSON object could be decoded"** while running the python insta bot.
This happens when the bot tries to verify comment and gets failed.

Problem looks like this in console
![exception](https://cloud.githubusercontent.com/assets/26673122/24323014/00aa2d3e-1195-11e7-807e-6427b1291295.JPG)

**Steps:**
Open file "instabot.py".
Press **Control+f** keys and in search box type -> **check_exisiting_comment(self, media_code)**
Then the problem code will appear like this:

`
        

    def check_exisiting_comment(self, media_code):
        url_check = self.url_media_detail % (media_code)
        check_comment = self.s.get(url_check)

        all_data = json.loads(check_comment.text)
        if all_data['media']['owner']['id'] == self.user_id:
                self.write_log("Keep calm - It's your own media ;)")
                del self.media_by_tag[0]
                return True

        comment_list = list(all_data['media']['comments']['nodes'])
        for d in comment_list:
            if d['user']['id'] == self.user_id:
                self.write_log("Keep calm - Media already commented ;)")
                del self.media_by_tag[0]
                return True

        return False
`

> All you have to do is to copy the following code and replace with the old one.

**Corrected code:**
`
        

    def check_exisiting_comment(self, media_code):
        url_check = self.url_media_detail % (media_code)
        check_comment = self.s.get(url_check)

        if not check_comment.text:
            self.write_log("Failed to get comment info - not leaving comment")
            # There was a problem getting comment info, assume comment exists to avoid duplicates
            return True
        try:
            all_data = json.loads(check_comment.text)
            if all_data['media']['owner']['id'] == self.user_id:
                self.write_log("Keep calm - It's your own media ;)")
                del self.media_by_tag[0]
                return True

            comment_list = list(all_data['media']['comments']['nodes'])
            for d in comment_list:
                if d['user']['id'] == self.user_id:
                    self.write_log("Keep calm - Media already commented ;)")
                    del self.media_by_tag[0]
                    return True
        except:
            self.write_log("Exception parsing comments json - not leaving comment")
            return True

        return False
`

Just replace the code and then the bot will run fine.
Give a like if this helps.
Thanks 👍

**Comment by Luckygirlllll** [comment]
thanks, it seems that it works without errors now!

**Comment by fireuniversal** [comment]
Welcome dear @Luckygirlllll

**Comment by Plushkin** [comment]
i merge it) https://github.com/Plushkin/instabot

**Comment by fireuniversal** [comment]
Good :) @Plushkin

**Comment by ChipWolf** [comment]
@fireuniversal please just make a pull request instead of posting a fix in an issue.

**Comment by fireuniversal** [comment]
Ok sir @ChipWolf i am new to github.

**Comment by ChipWolf** [comment]
https://help.github.com/articles/creating-a-pull-request/ @fireuniversal

**Comment by Hostile** [comment]
> root@ns1:~/instabot.py/src# python example.py
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    from instabot import InstaBot
  File "/root/instabot.py/src/instabot.py", line 664
    url_check = self.url_media_detail % (media_code)
            ^
IndentationError: expected an indented block

**Comment by ChipWolf** [comment]
@Hostile that's unrelated to this issue, open a new one.
From what I can see though, there is an indent on that line;
![](https://i.cwlf.uk/p2bd)
Grab a fresh clone of the repo
