### ISSUE TITLE
Install requests lib

### ISSUE THREAD

**Issue by Github1010** [instabot-py/instabot.py#441]
WHEn I try to install requests lib, it says'Syntax Error: invalid syntax".
Does anybody knows why?

THanks!!

![install requests](https://cloud.githubusercontent.com/assets/26791177/24500111/7943a6fa-1544-11e7-984e-caace081ccd0.png)

**Comment by linkfy** [comment]
Hey Github1010 didn't tested it yet but I recommend you to use Python 2.7 to run the code, also if you want to try with python 3, the tested version in the documentation is Python 3.4.3. ^^

**Comment by Github1010** [comment]
Thanks, but instead of:
pip3 install requests I wrote pip install requests and the error is the same.
How could I change to python 2.6 version?

**Comment by Github1010** [comment]
The problem is here:
joan@joan-laptop:~$ pip install requests
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main

The main 'editor' says to go to python 3.2 and I CAN NOT CHANGE (no edit).
how could I change, because I have a 'main' folder with python 2.6

**Comment by Github1010** [comment]
I install pip2.6
And now it says this:

![captura de 2017-03-30 13 19 53](https://cloud.githubusercontent.com/assets/26791177/24501863/9db3f5f6-154b-11e7-8e31-31f3e0b71ecb.png)

**Comment by linkfy** [comment]
It says 's'ha denegat el permís' so you need to use de ´sudo´ before pip install requests (Jo també parlo català)

**Comment by Github1010** [comment]
WOW! ahaha
I installed now correctly, but now says: 
Instabot is not defined (I opened a new argument).
ANy idea?

**Comment by linkfy** [comment]
Check the other issue :)  #442

**Comment by JatinPardeshi** [comment]
pip install -r requirements.txt
Give this command.... It will work
