### ISSUE TITLE
Instabot is not defined

### ISSUE THREAD

**Issue by Github1010** [instabot-py/instabot.py#442]
THANK YOU

**Comment by linkfy** [comment]
Please modify and run the example.py instead
`python example.py`

**Comment by Github1010** [comment]
I copied from here:
https://github.com/instabot-py/instabot.py

Which problem could be?

**Comment by linkfy** [comment]
Check the example -> [https://github.com/instabot-py/instabot.py/blob/master/example.py](url)

**Comment by Github1010** [comment]
It doesnt exists that page.

**Comment by linkfy** [comment]
Check again, solved

**Comment by Github1010** [comment]
Now it says:
from instabot import InstaBot. (copied and pasted from your link exactly)
No module named instabot

**Comment by ChipWolf** [comment]
Give me the output of `ls`

**Comment by Github1010** [comment]
![3](https://cloud.githubusercontent.com/assets/26791177/24509007/7df1ce0e-1565-11e7-9bca-6a7da8740244.png)

**Comment by Github1010** [comment]
my question is, to work the program which code I should use:
1) https://github.com/instabot-py/instabot.py/blob/master/example.py

2)
bot = InstaBot('login', 'password',
                like_per_day=1000,
                media_max_like=0,
                media_min_like=0,
                follow_per_day=0,
                follow_time=5*60*60,
                unfollow_per_day=0,
                comments_per_day=0,
                tag_list=['cat', 'car', 'dog'],
                tag_blacklist=['rain', 'thunderstorm'],
                user_blacklist={'hellokitty':'', 'hellokitty3':''},
                max_like_for_one_tag = 5,
                unfollow_break_min = 15,
                unfollow_break_max = 30,
                log_mod = 0,
                proxy='')

ONE OR TWO?

**Comment by Github1010** [comment]
You can close that one. It's done!
