### ISSUE TITLE
Insecure Platform warning

### ISSUE THREAD

**Issue by Github1010** [instabot-py/instabot.py#445]
I started using the instabot, and the firsts minutes all goes right.
Later, for each LIKE it appears this text. WHAT DOES IT MEANS?
Liked: 1482092160828073548. Like #2.
Trying to like media: 1482092160266056337
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning

**Comment by virginsince1997** [comment]
use python3.5

**Comment by ChipWolf** [comment]
`pip install 'requests[security]'`
