### ISSUE TITLE
Detailed description

### ISSUE THREAD

**Issue by dasew** [instabot-py/instabot.py#446]
Hi, folks!

I'bad speak English, and don't know python. I want write detailed description each function, which used with code. Will you help me understand this is code? 

Lets tell telegram? Thks.

PS My native language - russia.

**Comment by kundanvishen** [comment]
Visit #245 for any help. @polaroi8d @ChipWolf issue can be closed.

**Comment by dasew** [comment]
@kundanvishen , There is a chat in the telegraph?

**Comment by kundanvishen** [comment]
@dasew yes. Use this link to [join through telegram](https://telegram.me/joinchat/DYKH-wdXpfmQCdcJLaV48Q). The link is also mentioned in project description [README.md](https://github.com/instabot-py/instabot.py)

**Comment by dasew** [comment]
@kundanvishen , i saw this link, but the link NOT work. I can say my number, add me?
