### ISSUE TITLE
Telegram group link is broken/incorrect

### ISSUE THREAD

**Issue by kundanvishen** [instabot-py/instabot.py#447]
The link mentioned in README.md is broken or incorrect.

**Comment by ChipWolf** [comment]
I think we should move to Gitter personally and keep Telegram for actual team members

**Comment by ChipWolf** [comment]
I think we should move to Gitter personally and keep Telegram for actual team members @LevPasha

**Comment by LevPasha** [comment]
https://github.com/instabot-py/instabot.py/commit/46ab62634630416f3fbea052c445fb71491491d9 update link

**Comment by canpoyrazoglu** [comment]
This issue should still be open. The link is not working for sure.

**Comment by LevPasha** [comment]
@canpoyrazoglu actual link is https://t.me/joinchat/DYKH-0G_8hsDDoN_iE8ZlA

**Comment by ugurozturk** [comment]
modified https://github.com/instabot-py/instabot.py/commit/213bc357443abf2e7d5ecfaa96d655a0bceb0892
