### ISSUE TITLE
InstaBot says I followed a user, but when I check it isn't following that user

### ISSUE THREAD

**Issue by samelliott89** [instabot-py/instabot.py#449]
For every follow that InstaBot reports back, it seems that it's not actually following that user.

Any help is much appreciated.

**Comment by ChipWolf** [comment]
Which mode are you using?
Are you sure you're logging into the correct account?

**Comment by mavala97** [comment]
i had the same thing, but some people have their account on private: because of this you don't see the numbers increase immediatly :)

**Comment by ChipWolf** [comment]
Oh yeah, this will apply to when the bot follows a private user.

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
