### ISSUE TITLE
Mode 0

### ISSUE THREAD

**Issue by Github1010** [instabot-py/instabot.py#451]
I use mode 0.
When I write, for example: 100 unfollows day, 100 follows day, everything goes right.
But when I write 0 follows/day and 50 unfollows/day, it never starts to unfollow.
It seems like only unfollow later of one follow, and now I dont want to follow anybody and I need to unfollow people!
THANKS

**Comment by ChipWolf** [comment]
Don't use mode 5

**Comment by Github1010** [comment]
But I want to unfollow only people who don't follow me, not everybody (as mode 5 does).
There is any option for this?
THANKS

**Comment by luisramirez-m** [comment]
I copy this, from example.py:
```
    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW PEOPLE WHO DON'T FOLLOW BACK BASED ON RECENT FEED ONLY")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW PEOPLE BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")
```
If you need more info or examples for all modes: https://github.com/instabot-py/instabot.py/issues/234#issuecomment-254159457

**Comment by ChipWolf** [comment]
So, mode 2 then.
