### ISSUE TITLE
No module named instabot

### ISSUE THREAD

**Issue by rookiemexico** [instabot-py/instabot.py#452]
Hi, I just follow all the steps on the example.py, tried it all but keep having the same error on running:

Traceback (most recent call last):
  File "/Users/main/Desktop/example.py", line 6, in <module>
    from instabot import InstaBot
ImportError: No module named instabot

Using Mac OS. Got pip requests installed, download Phyton 2.7, used exactly the same code with my user and password, running on IDLE ...not sure where to go next, is it the location of the file? should I install any module named instabot somewhere?
Thanks a lot, I'm going crazy on this one

**Comment by luisramirez-m** [comment]
Show your the output of `ls`

Your clone the repository?

**Comment by rookiemexico** [comment]
OMG great thanks!!!! you save my brain and solved it...now I had more problems :(
but it seems im getting close:
Not sure the format on the whitelist, tried with: 'xxxx ', and "xxxxx " and keep getting the error.
showing two errors on the instabot file...

raceback (most recent call last):
  File "/Users/main/Desktop/bot/example.py", line 37, in <module>
    unfollow_whitelist=[ ])    
  File "/Users/main/Desktop/bot/src/instabot.py", line 190, in __init__
    self.populate_user_blacklist()
  File "/Users/main/Desktop/bot/src/instabot.py", line 202, in populate_user_blacklist
    self.user_blacklist[user]=id_user
TypeError: 'set' object does not support item assignment

**Comment by luisramirez-m** [comment]
Put your code here without username and password.

**Comment by rookiemexico** [comment]
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import sys
import time

sys.path.append(os.path.join(sys.path[0], 'src'))

from check_status import check_status
from feed_scanner import feed_scanner
from follow_protocol import follow_protocol
from instabot import InstaBot
from unfollow_protocol import unfollow_protocol

Here is the example.py and at the bottom is the instabot.py

bot = InstaBot(login='abcdefg', password='abcefg',
               like_per_day=1000,
               comments_per_day=50,
               tag_list=['XXXXX', 'XXXx', 'XXXXX','XXXX','XXXX','XXXX','XXXXX'],
               tag_blacklist=['rain', 'thunderstorm','XXXX'],
               user_blacklist={'XXXX'},
               max_like_for_one_tag=50,
               follow_per_day=300,
               follow_time=1*60,
               unfollow_per_day=300,
               unfollow_break_min=15,
               unfollow_break_max=30,
               log_mod=0,
               proxy='',
               # Use unwanted username list to block users which have username contains one of this string
               ## Doesn't have to match entirely example: mozart will be blocked because it contains *art
               ### freefollowers will be blocked because it contains free
               unwanted_username_list=['second','stuff','art','project','love','life','food','blog','free','keren','photo','graphy','indo',
                                       'travel','art','shop','store','sex','toko','jual','online','murah','jam','kaos','case','baju','fashion',
                                        'corp','tas','butik','grosir','karpet','sosis','salon','skin','care','cloth','tech','rental',
                                        'kamera','beauty','express','kredit','collection','impor','preloved','follow','follower','gain',
                                        '.id','_id','bags'],
               unfollow_whitelist=[ ])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW PEOPLE WHO DON'T FOLLOW BACK BASED ON RECENT FEED ONLY")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW PEOPLE BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
           ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0 :
        bot.new_auto_mod()

    elif mode == 1 :
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10*60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) <50 :
                feed_scanner(bot)
                time.sleep(5*60)
                follow_protocol(bot)
                time.sleep(10*60)
                check_status(bot)

    elif mode == 2 :
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3 :
        unfollow_protocol(bot)
        time.sleep(10*60)

    elif mode == 4 :
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10*60)

    elif mode == 5 :
        bot.bot_mode=2
        unfollow_protocol(bot)

    else :
        print ("Wrong mode!")

******** INSTABOT.PY where the errors are being reported

       log_string = 'Instabot v1.1.0 started at %s:\n' % \
                     (now_time.strftime("%d.%m.%Y %H:%M"))
        self.write_log(log_string)
        self.login()
#         self.populate_user_blacklist()
        signal.signal(signal.SIGTERM, self.cleanup)
        atexit.register(self.cleanup)

    def populate_user_blacklist(self):
        for user in self.user_blacklist:

            user_id_url= self.url_user_detail % (user)
            info = self.s.get(user_id_url)
            all_data = json.loads(info.text)
            id_user = all_data['user']['media']['nodes'][0]['owner']['id']
            #Update the user_name with the user_id
#             self.user_blacklist[user]=id_user
            log_string = "Blacklisted user %s added with ID: %s" % (user, id_user)
            self.write_log(log_string)
            time.sleep(5 * random.random())

**Comment by luisramirez-m** [comment]
Mmm try with this:

`user_blacklist={'username_1':'', 'username_2':''},`

`unfollow_whitelist=['username_3','username_4'])`

In your code, unfollow_whitelist have space. I don't understand.

**Comment by Monoe** [comment]
Hello and Good Day,

I am having the same issue as the OP. I have downloaded the app and have met the requirements; but when I try and run the app I get:

Traceback (most recent call last):
  File "example.py", line 12, in <module>
    from instabot import InstaBot
ImportError: cannot import name InstaBot

I followed the instructions here and in the README - still nothing. Do I need to modify the path? 
Currently it looks like this --> sys.path.append(os.path.join(sys.path[0], 'src'))

I do have a 'src' directory with all the goodies including instabot ..but it seems that python is not picking it up? The instruction said nothing about modifying the path or having to modify the file or having to modify my bash_profile in my home directory (using OS X)

Please advise and thank you.

**Comment by TheGreatSega** [comment]
Hi im having the same issue, running windows. any answers for this?

**Comment by theboywiththetriangle** [comment]
Me sucede lo mismo en la linea 9 

"Traceback (most recent call last):
  File "/home/darkarto/example.py", line 9, in <module>
    from check_status import check_status
ImportError: No module named check_status

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.

**Comment by michaellie1994** [comment]
why i have this kind of message error when typing "example.py" in my python 3.6.4

C:\Users\Michael\Downloads\instabot.py-master>example.py
Traceback (most recent call last):
  File "C:\Users\Michael\Downloads\instabot.py-master\example.py", line 6, in <module>
    from src import InstaBot
  File "C:\Users\Michael\Downloads\instabot.py-master\src\__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "C:\Users\Michael\Downloads\instabot.py-master\src\instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "C:\Users\Michael\Downloads\instabot.py-master\src\userinfo.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by Hiwakea** [comment]
I have the same problem as Michaellie1994 ... Any solutions yet?
