### ISSUE TITLE
follow likers of a photo with given hashtag

### ISSUE THREAD

**Issue by hoseinit** [instabot-py/instabot.py#453]
Hi 
I am a newbie to instabot, 
I am wondering how one can follow Users who has **Liked** a photo with defined Hashtags.
I mean instead of following users who have uploaded photos, **we follow users who liked the photos**
thanks for your help in advance

**Comment by Github1010** [comment]
I want to know that too!

**Comment by lpdx** [comment]
Nice question.
I've been notice that the bot follows the user with a blacklisted hashtag.
If we don't like that kind of content, it's would be nice to not follow that user.
Great improvement.

**Comment by hoseinit** [comment]
It's not about the blacklist and not following users.
It's about following the users who Like posts with specific hashtags

**Comment by ChipWolf** [comment]
I mean, I guess this is possible; I see why you'd want to do this.
Problem being it would add an extra query for every image because it has to request extra details for each image, you'd get throttled quicker.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
