### ISSUE TITLE
Question: Why isn't this on PyPI?

### ISSUE THREAD

**Issue by ErikBoesen** [instabot-py/instabot.py#456]
I feel like the bot would be far more user-friendly if it was uploaded to PyPI (i.e. could be installed via `pip` or _shudders_ `easy_install`. Any particular reason it hasn't been?

**Comment by ChipWolf** [comment]
That's funny. The team were just talking about that, we'll have Travis builds and stick ourselves on PyPI when we clear up the repo.
Things are a bit of a mess right now, not a priority right now.
