### ISSUE TITLE
SSL Certificate verify failed

### ISSUE THREAD

**Issue by shaharbukra** [instabot-py/instabot.py#457]
Hi all,

Got this error today:
Traceback (most recent call last):
  File "D:\_Admin\Bots\Instabot\src\example.py", line 43, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "D:\_Admin\Bots\Instabot\src\instabot.py", line 190, in __init__
    self.login()
  File "D:\_Admin\Bots\Instabot\src\instabot.py", line 240, in login
    r = self.s.get(self.url)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

with my old version of the instabot and with the new version in here.
so i guess something has changed.

anyone else got it? 
anyone has an idea how to make it work?

ps
just saw needed to update my python version :(
i will give it a try later.

**Comment by daniteer** [comment]
Got same problem. 
I was running 2 different account. Tried to reset one of it and got that error code. But when I switch to the other one that was already running for few days, it's still working. So I think the problem is in the log in procces. Maybe instagram just updated.

**Comment by ChipWolf** [comment]
`pip install requests[security]`

**Comment by shaharbukra** [comment]
@ChipWolf  any idea? 

C:\Python27>python -m pip install -U requests[security]
Requirement already up-to-date: requests[security] in c:\python27\lib\site-packages
Collecting pyOpenSSL>=0.13 (from requests[security])
  Could not find a version that satisfies the requirement pyOpenSSL>=0.13 (from requests[security]) (from versions: )
No matching distribution found for pyOpenSSL>=0.13 (from requests[security])

**Comment by ChipWolf** [comment]
that's unusual, this should work; if not reinstall Python
```
git clone https://github.com/pyca/pyopenssl.git
cd pyopenssl
python setup.py build
python setup.py install
pip install requests[security]
```
