### ISSUE TITLE
How I can use emoji in comments?

### ISSUE THREAD

**Issue by Plushkin** [instabot-py/instabot.py#458]
I found code in https://github.com/oriolblanc/instabot.py/commit/027e34a7d300e2ae47b8677dbfd234e9623fc8a0? but when i try to used it i get error. 
**Your text has unicode problem!**
maybe someone can tell me how i can use it?

**Comment by Plushkin** [comment]
emojis = [':top:', ':thumbsup:', ':clap:', ':ok_hand:', ':joy:', ':smiley_cat:', ':sign_of_the_horns:', ':wink:', ':smile:', ':sunglasses:']
         return emoji.emojize(random.choice(emojis), use_aliases=True)

**Comment by jonasrafael** [comment]
Working? U can paste your .py here?

**Comment by mactrash** [comment]
http://getemoji.com/ copy and paste in the terminal do work, although cannot see afterward
