### ISSUE TITLE
conditions to follow an acc

### ISSUE THREAD

**Issue by Bellman281** [instabot-py/instabot.py#459]
I would like to add some conditions for following an account. like the ones we have to detect if an account is fake or not to unfollow it. like following code. but I want to add it somewhere as a following rule. So the bot won't start to follow such an account.
```
if follower/follows > 5:
                            self.is_selebgram = True
                            self.is_fake_account = False
                            print('   >>>This is probably Selebgram account')
```

shall I change this part? how?
` def follow(self, user_id):`

**Comment by ChipWolf** [comment]
I don't follow, could you please elaborate? What are you attempting to do?

**Comment by Bellman281** [comment]
Let me make it clear: 
I have seen that "bot" follows some arbitrary users. I am using Mode = 0. I just read the "instabot.py" script.

 So I want to make some conditions on "following" an user. we have similar ones to "unfollow" one account. Like detecting an account is "Selebgram" / FAKE /Active,.... 
I want similar conditions for "following" and account. so bot  before following an user, first checks those conditions (like if  number of followings of an account is zero then skip this account). 
`if follows =0` 

something like this.

**Comment by ChipWolf** [comment]
We already do those same checks for following and unfollowing...
https://github.com/instabot-py/instabot.py/blob/d058d9a4f2392502927610085ede4fda05c90d41/src/follow_protocol.py#L24
