### ISSUE TITLE
How to make auto comments work?

### ISSUE THREAD

**Issue by gaijinjoe** [instabot-py/instabot.py#464]
I tried to follow the guide for comments, but seems old, for the 0,5v, how to make it working in the new version?

**Comment by ChipWolf** [comment]
Increase `comments_per_day` in `example.py`

**Comment by gaijinjoe** [comment]
Don't I need to put a list of comments I want the bot to write? Is it going to be automatic? just need to increase `comments_per_day` ?

**Comment by Robcis** [comment]
@ChipWolf what is a safe comment rate per day? Any idea?
