### ISSUE TITLE
Random errors that stops the bot

### ISSUE THREAD

**Issue by bboy519** [instabot-py/instabot.py#465]
Unfollow: 549594726 #1 of 2.
Pausing for 29 seconds... 1 of 2
Logout: likes - 3, follow - 2, unfollow - 1, comments - 2.
Bot work time: 0:15:20.619427                         Logout success!
Exception KeyError: KeyError(139664627402496,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored                                            root@CubeCloud-20174225:~#

**Comment by ChipWolf** [comment]
Bunch of other issues/PRs with the same issue, search before posting.
