### ISSUE TITLE
QPython android N 7.0 how to install 

### ISSUE THREAD

**Issue by Luke050** [instabot-py/instabot.py#472]
I installed QPYTHON on my android device and i have problem when i try to run this script 

![screenshot_20170409-175435](https://cloud.githubusercontent.com/assets/27148900/24838836/3a34c174-1d50-11e7-9a6b-8edf36b78f20.png)
![screenshot_20170409-175342](https://cloud.githubusercontent.com/assets/27148900/24838841/48273320-1d50-11e7-867c-8afae728ffca.png)

I have read the instructions many times and I can not run this script
English is not my language, so I do not know how to describe the problem correctly.
I am a very beginner this is my first contact with this program so please be understanding.
Thank you in advance for your help

**Comment by zengfu94** [comment]
pip install requests

**Comment by Luke050** [comment]
Ok thanks i manually downloaded request lib and put in qpython/lib/python2.7/site-packages 
All works Perfectly fine
