### ISSUE TITLE
The bot dont run all day. it shut off halfway sometimes

### ISSUE THREAD

**Issue by phongyewtong** [instabot-py/instabot.py#473]
this time it ran only for 18mins when it start at "2017-04-10 00:00:00" and it auto logout. i have been using it for a month and my like configuration is 550 likes

2017-04-10 00:18:39,517 - myinstagramnick - Bot work time: 0:18:35.618841
2017-04-10 00:18:40,134 - myinstagramnick - Logout success!

**Comment by ChipWolf** [comment]
The logout event is triggered by a cleanup event.
The cleanup event is triggered by a SIGTERM or any other kill signals recognized by Python.
Chances are, you're running out of resources; or something else on the machine is killing the process.

**Comment by phongyewtong** [comment]
how can i disable it? it keep closing. I use aws 1 instance 2GB ram and 8GB space all by itself for this and its still closing.

**Comment by gersanchez** [comment]
@phongyewtong Hi! did you fix it?
