### ISSUE TITLE
Replace the login with a token ?

### ISSUE THREAD

**Issue by MartySGL** [instabot-py/instabot.py#475]
Hi !

I wanted to replace the login based authentication with a token.

The reason is, I would like to connect once with my login and password and then launch the program without my login and password in it (so just get the token saved somewhere)

Is there a way of achieving this easily ?

Thank you !

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/tree/save_cookies

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by danielrosero** [comment]
Hey, I'm planning to use Instagram Android SDK to get the access token, I have been looking for the way to login instabot through access token.

Is it possible? I looked in @ugurozturk branch suggestion, no results.

Thanks!
