### ISSUE TITLE
Follow/unfollow counter

### ISSUE THREAD

**Issue by Github1010** [instabot-py/instabot.py#478]
![error](https://cloud.githubusercontent.com/assets/26791177/25081596/86e3d220-234b-11e7-8bf7-3aa6fa3c39b4.jpg)

I work with mode 0.
I have the option of 150 follow, 150 unfollor / day.
But every day I follow more and more people. As u can see, the ratio between follow/unfollow it's not 1.
The program follow more people than unfollow
Does anyone knows why?
Thank you!

**Comment by Github1010** [comment]
Below "this account is following you" should appear the: unfollow.
But it seems like instabot make a "like" and "forget" to unfollow.
Any idea?

![Uploading error2.png…]()

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
