### ISSUE TITLE
Not liked: 400

### ISSUE THREAD

**Issue by Enomyx** [instabot-py/instabot.py#483]
I started in the early morning and now since like 2houres it always show me this.
Somebody know a solution? 
![screenshot_1](https://cloud.githubusercontent.com/assets/27731661/25135910/ecbcf622-2453-11e7-8aa9-847a2360d58f.png)

**Comment by Enomyx** [comment]
I already made a new account and tryd using it there. But it wont work anyways

**Comment by zoh316** [comment]
@Enomyx @canoneero same problem with me, i hav tried in 2 accounts still doesnt work.

**Comment by rferrato** [comment]
someone found some solution?

**Comment by gersanchez** [comment]
????? 👎

**Comment by ugurozturk** [comment]
use https://github.com/instabot-py/instabot.py/issues/887 for tracking in the future
