### ISSUE TITLE
commenting not working

### ISSUE THREAD

**Issue by calilinus** [instabot-py/instabot.py#484]
Trying to like media: 1495923458297732931
Liked: 1495923458297732931. Like #6.
Get media id by tag: fitness
Exception parsing comments json - not leaving comment
Exception parsing comments json - not leaving comment

the commenting is not working for hours

**Comment by IGETHE** [comment]
i have almost the same problem, the bot write 15 comments and after apears like trying to comment but never coment.
could anyone say how to fix this?

**Comment by JacobGarcia** [comment]
Bump

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
