### ISSUE TITLE
CANT MAKE COMMENTS!! Keyerror: media

### ISSUE THREAD

**Issue by drovid** [instabot-py/instabot.py#489]
Check_existing_comment spits out the ['media'] doesn't want to check if comments been written already or self media comment. Will upload code later. Here's a screenshot for now. 
![img_6199](https://cloud.githubusercontent.com/assets/25699024/25200657/fb44c7d2-2503-11e7-94d1-6c02fc89885a.JPG)

**Comment by artemdumanov** [comment]
I was already solve this issue in #488 
If it works for you, please, approve request

**Comment by drovid** [comment]
I don't see a solution :( help pls?

**Comment by artemdumanov** [comment]
@drovid  omg. Do you use github at first? 

Go follow this link, copy text, and replace text of file instabot.py  (path: /.../path/to/your/bot/.../src/instabot.py) 

https://github.com/artemdumanov/instabot.py/blob/71d753292024936acfde2bf71ea826e388d4830f/src/instabot.py

**Comment by drovid** [comment]
Yes this is my first time at github :( сорян, не сразу врубаюсь :)

**Comment by artemdumanov** [comment]
Is it works for you?

**Comment by SHUBHZZGUPTA** [comment]
I did what you said. My example.py is closing as soon as it opens now. Earlier, it was working fine. any help?

**Comment by drovid** [comment]
same, I replaced the text in instabot.py in src, and it gives me this:

>Traceback (most recent call last):
  File "/home/pi/Desktop/Instagram Bot/jumptoup/jumptoup1.py", line 6, in <module>
    from instabot import InstaBot
  File "/home/pi/Desktop/Instagram Bot/jumptoup/src/instabot.py", line 12, in <module>
    from json import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError'
>>>

**Comment by drovid** [comment]
no, I tried, same exact error. :( it gives me the same "KeyError: 'media'"

**Comment by artemdumanov** [comment]
@SHUBHZZGUPTA  any logs, errors?

**Comment by SHUBHZZGUPTA** [comment]
Hey, thankyou for your response. I tried it. I even copied and replaced the original file.
from json import JSONDecodeError is already there.
 It still shows
ImportError: cannot import name 'JSONDecodeError' and closes quickly.
Thankyou.

**Comment by artemdumanov** [comment]
Do you add this line on top of instabot.py?

from json import JSONDecodeError


2017-04-20 11:06 GMT+03:00 SHUBHZZGUPTA <notifications@github.com>:

**Comment by drovid** [comment]
I am not trying to help anyone, I am as clueless as I can possibly get :( 

How do I install JSON package?

**Comment by artemdumanov** [comment]
@Droid
Try in terminal:
pip3 install json

**Comment by artemdumanov** [comment]
@drovid  Is your issue still exist?

**Comment by artemdumanov** [comment]
Yeah, you was right. now i have same problem. I will fix it in few hours. Can you test it?

**Comment by Simeon-O** [comment]
@drovid  Hey this worked for me... its seems the json format has changed..

    def check_exisiting_comment(self, media_code):
        url_check = self.url_media_detail % (media_code)
        check_comment = self.s.get(url_check)
        all_data = json.loads(check_comment.text)
        if all_data['graphql']['shortcode_media']['owner']['id'] == self.user_id:
            self.write_log("Keep calm - It's your own media ;)")
            # Del media to don't loop on it
            del self.media_by_tag[0]
            return True
        comment_list = list(all_data['graphql']['shortcode_media']['edge_media_to_comment']['edges'])
        for d in comment_list:
            if d['node']['id'] == self.user_id:
                self.write_log("Keep calm - Media already commented ;)")
                # Del media to don't loop on it
                del self.media_by_tag[0]
                return True
        return False

**Comment by artemdumanov** [comment]
@Simeon-O Yes it was changed, I will test it in minutes. Where are you been before? :smile: 
Please, next time make forks.

**Comment by drovid** [comment]
@Simeon-O this is awesome but I have no clue what you did and what steps you took to get it to work.... :( any help please? I'm a total noob at Python, if you help I'll even pay you

**Comment by artemdumanov** [comment]
@drovid I will take a link for you with this changes tommorow. 
You use this software for free, and get value from it. If you want to pay for someone, pay for our SOCIETY, we support paypal donations.
 https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=7BMM6JGE73322&lc=US&item_name=GitHub%20donation&currency_code=USD&bn=PP-DonationsBF%3abtn_donate_SM%2egif%3aNonHosted

**Comment by drovid** [comment]
Thank you, I will donate once I get some extra cash hah.

**Comment by artemdumanov** [comment]
@drovid Check it https://github.com/artemdumanov/instabot.py

**Comment by drovid** [comment]
Just donated $20! Will check how it works once I get home

**Comment by SHUBHZZGUPTA** [comment]
It's working very well now. Thankyou for your support.
One last thing, Can we add custom comments? and how?

I guess we can officially close this issue now :p
Thankyou for your help and support,

Don't forget to answer how can we add custom comments in the system :p

**Comment by artemdumanov** [comment]
@shubhzzgupta Did you check commit? Comments works? 
I will upload example today, and send you link

**Comment by artemdumanov** [comment]
@drovid @SHUBHZZGUPTA Check this one. Read readme, how to set comments https://github.com/artemdumanov/instabot.py

**Comment by SHUBHZZGUPTA** [comment]
Hey @artemdumanov  I just updated my src from yours and installed simpleJson and now comment work.

Comments are working flawlessly. I am only 57th comment.
I will download the new instabot.py when i am online through my system <3
