### ISSUE TITLE
Not working !

### ISSUE THREAD

**Issue by edwardium** [instabot-py/instabot.py#491]
I change the username and password and save and when i run within second its jump out and finish and no errors 
Anyone can help??

**Comment by drovid** [comment]
what error do you get? post a screenshot? Sounds like it's with everyone who is trying to use comments. Temporary workaround is setting comments_per_day to 0 so it doesn't comment

**Comment by juliancnn** [comment]
`Trying to unfollow: 4243226801
Traceback (most recent call last):
  File "/home/jmorales/PycharmProjects/instaBotServer/instabot.py/example.py", line 68, in <module>
    bot.new_auto_mod()
  File "/home/jmorales/PycharmProjects/instaBotServer/instabot.py/src/instabot.py", line 564, in new_auto_mod
    self.new_auto_mod_comments()
  File "/home/jmorales/PycharmProjects/instaBotServer/instabot.py/src/instabot.py", line 619, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "/home/jmorales/PycharmProjects/instaBotServer/instabot.py/src/instabot.py", line 654, in check_exisiting_comment
    if all_data['media']['owner']['id'] == self.user_id:
KeyError: 'media'`

**Comment by artemdumanov** [comment]
I already solve this issue here #488. Try this commit, and write to me it
works or not.

**Comment by edwardium** [comment]
Tnx so much for replying.
There was not an error 
I try a lot and  keep to play with it up to i run it but now there is problem again:
1-When i run the test.py connected to iG account and start but its not compliting the bot 
Example: if its 1000 like only around 130 like and suddenly the test.py jump out and close,
And similar thing 
2- and after jump out I cannot run again 
Just comand page open and so fast close 
Up to delete it completely and unzip the file and change the .py and run but agai problem #1 its happening.
Tnx agai for helping 🙏🏻🙏🏻🙏🏻

**Comment by edwardium** [comment]
i have no idea y i receive in email i just see it
tnx every one
