### ISSUE TITLE
How can I set this up to unfollow people who dont follow me back in 2 days ?

### ISSUE THREAD

**Issue by Viral12321** [instabot-py/instabot.py#493]

**Comment by artemdumanov** [comment]
Run bot with:
follow_time = 172800

2017-04-21 18:44 GMT+03:00 Viral12321 <notifications@github.com>:

**Comment by Viral12321** [comment]
![screen shot](https://cloud.githubusercontent.com/assets/27862024/25292599/d9e4ab50-26a4-11e7-9b8e-751fad21a353.png)
 Can you help me to setup this ? I dont know the good number to be legit but gain fast real followers.

**Comment by mactrash** [comment]
@Viral12321 the unfollow function of the bot seems not work well from begin till now. You will finally follow a lot of people if you don't unfollow them manually.

**Comment by wgviana** [comment]
Duplicate #894

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
