### ISSUE TITLE
Can you help me to setup with good numbers ?

### ISSUE THREAD

**Issue by Viral12321** [instabot-py/instabot.py#494]
![screen shot](https://cloud.githubusercontent.com/assets/27862024/25292814/e563e4e0-26a5-11e7-9adf-f07ecb07e408.png)

**Comment by rikianastasoski** [comment]
i have the same just follow_time 5 * 60 * 60 and follow and unfollow at 700

**Comment by artemdumanov** [comment]
Use tags that response you auduithory, if you are merchant. If your goal is maximum followers, we can't help you.
