### ISSUE TITLE
Can I run two bots at the same time?

### ISSUE THREAD

**Issue by manguszta** [instabot-py/instabot.py#496]
First of all, thank you for this script, it eases my life for over a year now.

My question applies either the case of logining to the same account, and the case of different accounts.
I'd use one bot for following (15-16 hours of running a day) and one for liking (less than 12 hours of running a day).

**Comment by artemdumanov** [comment]
You can use as one, and as two. But, in my opinion, if you use one account it reduce ban possibility.
