### ISSUE TITLE
Automatic Unfollow

### ISSUE THREAD

**Issue by jayhill365** [instabot-py/instabot.py#499]
Is their a way to run this program using one function at a time. Example would be unfollowing 1000+ users. Then re running the bot and liking 1000+ photos or videos vs. having to do multiple actions all at once while running the bot? Thanks again for this repository!

**Comment by artemdumanov** [comment]
Do not set bot, to unfollow 1000, i recommend you to set 30 *24. Because when you use 1000, ban is so possible. It is better to do multiple actions at time. For purposes of unfollow we have mode 5, dont use it rarely, and not longer than 1 day.

**Comment by jayhill365** [comment]
How do you run mode 5?

**Comment by jayhill365** [comment]
Would you just change the text in the example.py file  in like 29 from log=0 to log=5?

**Comment by jayhill365** [comment]
hey sorry I figured this issue out actually thanks for commenting and closing !

**Comment by jayhill365** [comment]
line 60
