### ISSUE TITLE
Won't login

### ISSUE THREAD

**Issue by peerdenhoed** [instabot-py/instabot.py#501]
Hey, 
If i run the example.py it just doesn't start. Did i do something wrong? please check the steps i did:
1. i downloaded Python 2.7.11 
2. I don't know where to put that command wich is:  
To install the project's dependencies, run command `pip install -r requirements.txt` (specify `pip2` or `pip3` if you have multiple versions of Python installed)

3. i downloaded the files

 4.i modyfied the example.py 
   i did mode 2 
   login and password are xxxx and xxxx
 5. i ran the program example.py 
and by step 5 it din't do anything its frustrating. Can someone please help me with this issue?

thanks.
PS: i have windows 10

**Comment by SHUBHZZGUPTA** [comment]
you need to learn python first!
Atleast install pip then request and then simplejson

**Comment by peerdenhoed** [comment]
Hey thanks for your request. 
I addded pip to Python and i still have the bugg. 
Can you explain what is going wrong because i have no idea. am i using the wrong python version or so?
Sould i re-install the instabot?

Please help :)

**Comment by artemdumanov** [comment]
@peerdenhoed try python3

**Comment by peerdenhoed** [comment]
i have python version 3.6 32-bit 
I ran the file "example" again but it said "You don't have a progam to run it". So i did: Open with-> Python 3.6. But now i get this pop-up instantly:
![python](https://cloud.githubusercontent.com/assets/27914506/25313983/7e5cc5f0-283a-11e7-8ae3-756bc9881a04.PNG)

I tried Repair and Modify and restarted my pc but it still wont work.
(i feel like a noob now) can you please help me further.

Tanks :)

**Comment by artemdumanov** [comment]
Check this https://www.python.org/downloads/

2017-04-23 16:36 GMT+03:00 peerdenhoed <notifications@github.com>:

**Comment by peerdenhoed** [comment]
Okey i installed Python 3.6 (64.bit) but i want to run the example file and it wont run with python. Python works perfectly but i can't run that file with it. I can edit "example" with notepad++ and stuff but it wont run with Python. I hope you have an idea how to fix it. I did install the 2.7.13 version of Python too. Maybe i have to run "example" with that? i watched tutrials on youtube of Python and it worked perfectly. Can you help me?

**Comment by peerdenhoed** [comment]
Yes i finally fixed it. But now i have the problem with logging in; it says: 
Login error! Check your login data!
Completed populating user blacklist with IDs

What do i do now?

**Comment by virginsince1997** [comment]
Login into Instagram with the app and verify that the login is coming from
your account

**Comment by peerdenhoed** [comment]
I don't get an verify message :/

**Comment by virginsince1997** [comment]
Try logging in with another account, also check if you have two factor
authentication enabled

**Comment by peerdenhoed** [comment]
i have two factor authentication enabled and i logged in with another account. Do i get and message like:
"Confirm you logged in" Or so?

**Comment by virginsince1997** [comment]
Disable 2fa ,confirm login ,yes it was me

**Comment by peerdenhoed** [comment]
I disabled 2fa, how do i confirm my login? 
(Sorry for asking so much questions but i want to do it without making any mistakes) :)

**Comment by virginsince1997** [comment]
Just login after disabling 2fa ,,go to your Instagram app and click "it was
me " after login in with the bot

**Comment by peerdenhoed** [comment]
Okey thanks :)

**Comment by peerdenhoed** [comment]
Lol i still wont work. Idk what im doing wrong. i followed all steps.

**Comment by virginsince1997** [comment]
Send a screenshot of your example. Py add fake password

**Comment by peerdenhoed** [comment]
Okey

**Comment by peerdenhoed** [comment]
![jaja](https://cloud.githubusercontent.com/assets/27914506/25333093/47ec959a-28e9-11e7-9790-cc6c3d00da9e.PNG)

**Comment by hoseinit** [comment]
Problem solved by Approving IT WAS ME in instagram.
