### ISSUE TITLE
Is there any settings of the max number of followers who have the account to which i'm gonna follow ? 

### ISSUE THREAD

**Issue by IGETHE** [instabot-py/instabot.py#502]
Is there any max number of followers of the account to which the bot it's gonna like or follow? 
Thanks in advance for the reply.

**Comment by dn5** [comment]
The documentation is pretty clear and it says `follow_per_day`.

**Comment by IGETHE** [comment]
ok, maybe i expressed wrong my words, but i meant the max number of followers of the account of the person to which im going to follow, not the number of the people who im going to follow per day.
@dn5

**Comment by vinceze** [comment]
I am also very interested in knowing if there is such feature

**Comment by guybehar** [comment]
I agree, this is a very important feature. I know I'm not telling you something you did not know, but Instagram users who have managed to get many followers tend not to follow users with a small number of followers. They also prefer a large gap between the number of their followers and the number of users they follow. It's a status symbol.

**Comment by dzaytsev91** [comment]
I also thought it would be nice feature, so I send a PR

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
