### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by peerdenhoed** [instabot-py/instabot.py#503]
![jajaja](https://cloud.githubusercontent.com/assets/27914506/25339699/d8798e28-2903-11e7-87a3-0ff4df4b12f6.PNG)
I get this issue when i try to start the bot. 

Have i made a mistake with this or so?
![jajajaja](https://cloud.githubusercontent.com/assets/27914506/25339775/14a204b6-2904-11e7-8f14-ded82f176d65.PNG)

**Comment by virginsince1997** [comment]
Please try logging in with a new account that has 2FA disabled

**Comment by peerdenhoed** [comment]
I did that

**Comment by hoseinit** [comment]
I have the same problem, I dont have 2FA

**Comment by atomneo** [comment]
I have this same problem, account without 2FA
