### ISSUE TITLE
Bot says it's following users but when I refresh on my phone there are no additional follows

### ISSUE THREAD

**Issue by qnagr** [instabot-py/instabot.py#505]
It's working with LevPasha's bot though.

**Comment by oriolblanc** [comment]
Same here

**Comment by Redhead9** [comment]
Mode Settings and Log?

**Comment by aleeyou11** [comment]
Same here

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
