### ISSUE TITLE
PLEASE HELP! IT STOPS WORKING AFTER 10sec

### ISSUE THREAD

**Issue by nathanwick2001** [instabot-py/instabot.py#507]
after about ten sec it will start spamming:

======> Get media id by user: 3994794803 <======
XXXXXXX Except on get_media! XXXXXXX

btw I am using pythonanywhere not sure if that matters tho 
 please help!

**Comment by nathanwick2001** [comment]
this is a longer version of what its been saying

======> Get media id by user: 3994794803 <======
XXXXXXX Except on get_media! XXXXXXX
funnyfails.tv : Get user info 
24.04.2017 23:59
Except on get_info!
======> Get media id by user: 3994794803 <======
XXXXXXX Except on get_media! XXXXXXX
funnyfails.tv : Get media id on recent feed 
 25.04.2017 00:01
Media in recent feed = 24
funnyfails.tv : Get user info 
25.04.2017 00:01
Except on get_info!
======> Get media id by user: 798408345 <======
XXXXXXX Except on get_media! XXXXXXX
funnyfails.tv : Get user info 
25.04.2017 00:03
Except on get_info!
======> Get media id by user: 798408345 <======
XXXXXXX Except on get_media! XXXXXXX
funnyfails.tv : Get media id on recent feed 
 25.04.2017 00:05
Media in recent feed = 24
funnyfails.tv : Get user info 
25.04.2017 00:05
Except on get_info!
======> Get media id by user: 4568701164 <======
XXXXXXX Except on get_media! XXXXXXX

**Comment by Basserado** [comment]
Hey,
same here. I try to locate the problem.
Btw I used Mode 2.

**Comment by nathanwick2001** [comment]
yeah found out it only does it when i'm on mode 2

**Comment by Redhead9** [comment]
Mode 2 doesn't work it's a known issue. :(
