### ISSUE TITLE
Enhancements?

### ISSUE THREAD

**Issue by limerick11** [instabot-py/instabot.py#509]
Hi,
Wondering if you can add additional features?
1) Instead of the media_by_tag number, is it possible to get the actual URL?
2) Timestamp for each like/comment etc.
3) Restart if script hangs

**Comment by polaroi8d** [comment]
@limerick11 hey, its an open source project, if you want to use this futures, do it, open a new pull request and the community happy for your job.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
