### ISSUE TITLE
2-Step Verification

### ISSUE THREAD

**Issue by ptkdev** [instabot-py/instabot.py#510]
I try login with Two-factor authentication but is impossibile start bot. Solution?

**Comment by polaroi8d** [comment]
I don't know a solution, if you want to use with 2fact auth.

**Comment by drovid** [comment]
I just turn it off and log the bot in, then turn it on again. That's one way of doing it

**Comment by polaroi8d** [comment]
@ptkdev Please try it out @drovid solution and if works fine, close the issue.
