### ISSUE TITLE
The bot keeps trying to follow/unfollow the same user over and over

### ISSUE THREAD

**Issue by SergeSmith23** [instabot-py/instabot.py#512]
The bot keeps trying to follow the same user over and over. Or trying to unfollow the same user, saying that this user already is unfollowed.  Eventually, it doesn't follow anybody.
<img width="562" alt="screen shot 2017-04-26 at 18 33 56" src="https://cloud.githubusercontent.com/assets/28076496/25464054/34542da0-2aaf-11e7-8a32-a7cd8935ddb0.png">

**Comment by beringov** [comment]
Same issue in my case. Mode 0

![image](https://cloud.githubusercontent.com/assets/15052091/25568073/ee7e0168-2e03-11e7-91ff-820abb258f97.png)

**Comment by ParinVachhani** [comment]
I am also facing the same issue. Seems like some problem with the part of code trying to list down users based on given tags. @LevPasha

**Comment by ChipWolf** [comment]
#386 aims to fix these issues
