### ISSUE TITLE
Bot consumes all of the CPU energy

### ISSUE THREAD

**Issue by mateuszpokojowczyk** [instabot-py/instabot.py#517]
I've got a problem when trying to use bot in unfollow mode only (mode 5).
It runs for about 15 minutes and then consumes a lot of CPU.
Any fix?

**Comment by ChipWolf** [comment]
![](https://media0.giphy.com/media/xTiN0xBCbjleHzKzcI/giphy.gif)

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
