### ISSUE TITLE
Instabot tries to unfollow its own user.

### ISSUE THREAD

**Issue by conSenta** [instabot-py/instabot.py#518]
After running for ~10 secs it stops working and doesn't do anything.
Here's the code , tried entering my own username into the blacklist; doesn't change anything.

Completed populating user blacklist with IDs
Get media id by tag: menstyle
Trying to like media: 1503515345292537280
Liked: 1503515345292537280. Like #1.
Trying to follow: 247671770
Followed: 247671770 #1.
Traceback (most recent call last):
  File "/Users/aurellius/Downloads/instabot.py-master/example.py", line 67, in <module>
    bot.new_auto_mod()
  File "/Users/aurellius/Downloads/instabot.py-master/src/instabot.py", line 564, in new_auto_mod
    self.new_auto_mod_comments()
  File "/Users/aurellius/Downloads/instabot.py-master/src/instabot.py", line 619, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "/Users/aurellius/Downloads/instabot.py-master/src/instabot.py", line 654, in check_exisiting_comment
    if all_data['media']['owner']['id'] == self.user_id:
KeyError: 'media'
Trying to unfollow: 247671770
Unfollow: 247671770 #1 of 1.
Pausing for 26 seconds... 1 of 1
Logout: likes - 1, follow - 1, unfollow - 1, comments - 0.
Bot work time: 0:00:40.201241
Logout success!
Exception KeyError: KeyError(140735160573952,) in <module 'threading' from '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'> ignored

**Comment by drovid** [comment]
Looks like an issue in check_existing_comment. See my other issue opened to fix this. 

https://github.com/instabot-py/instabot.py/issues/515

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
