### ISSUE TITLE
Some users are not unfollowed

### ISSUE THREAD

**Issue by Dluzhnevsky** [instabot-py/instabot.py#521]
I'm running the bot in the auto mode (0) with the following parameters
    follow_per_day=700,
    follow_time=8 * 60 * 60,
    unfollow_per_day=700
It means I should remain at about 230 followers simultaneously. However, the followed users number keeps increasing and I have to unfollow them manually like every day.
When I look at the log, I notice some "Except on get_info!", so, I suppose, it is the problem. How can I fix that problem to unfollow every previously followed user?

**Comment by 3to1null** [comment]
If you are using mode 0, and the user is neither fake nor a celebrity, but is following you it will not unfollow that user.
(`self.is_selebgram is not False or self.is_fake_account is not False or self.is_active_user is not True or self.is_follower is not True:`)

**Comment by Dluzhnevsky** [comment]
What should be modified to unfollow everyone who was followed?
I thought that one of the previous versions was unfollowing everyone by default...

**Comment by 3to1null** [comment]
```
MODE 0 = ORIGINAL MODE BY LEVPASHA
MODE 1 = MODIFIED MODE BY KEMONG
MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK
MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED
MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY
MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT
```
These are the modes, maybe one of them is to your liking?

**Comment by Dluzhnevsky** [comment]
As far as I can see, there are no modes like "Original + unfollow even those who followed back". I think there is something to be modified inside the code.

**Comment by hopye** [comment]
Im using MODE = 2 , and getting that 'Except on get info!', then 'Except on get media!' , the bot also displays  ' Upss 3226688770 is already in ex user list...  ' , it keeps cycling thru that..

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
