### ISSUE TITLE
Bot gets stuck inside the whitelist.

### ISSUE THREAD

**Issue by Ere-Eye** [instabot-py/instabot.py#525]
![image](https://cloud.githubusercontent.com/assets/14802003/25744104/b36e8b40-31ca-11e7-9c26-c8fdcbeaff12.png)
Bot gets stuck like this for days once in it.

**Comment by TehJokeR** [comment]
is this still an issue?

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
