### ISSUE TITLE
Settings Variable Like,Comment,Follow,Unfollow

### ISSUE THREAD

**Issue by zoh316** [instabot-py/instabot.py#531]
guys give me examples of settings variables which are safe to use without getting account disabled.
I use
Likes- 1000
Comments 100
Follow 350
Unfollow 350
i use it all day

**Comment by hoseinit** [comment]
I have tested 1000 follow and unfollow a day, no problem

**Comment by napster2091** [comment]
i recomend you to use the random function, each time you calculate the delay between likes, follows, unfollows for example:

self.like_delay = self.time_in_day / random.randint(1299,1499)

random.randint(1299,1499) is for the likes between 1299 and 1499

don't use number %2, softwares recognize them, better to use 997 if you want like 1000 likes

**Comment by zoh316** [comment]
i am really new in this @napster2091 can u give me more details please.

**Comment by zoh316** [comment]
@napster2091 please give me another example suppose i want 100 comments, 1000 likes and 500 follow unfollow per day

**Comment by randomm8** [comment]
@napster2091 where do I add this line please? thanks.

**Comment by zoh316** [comment]
@randomm8 goto /src /instabot.py 
Search for the line self.like_delay
There u can replace it. 
Use a prime number.

**Comment by zoh316** [comment]
I personally use this setting for a new instagram page
likes 500 follow/unfollow 200 per day

` self.like_per_day = like_per_day
        if self.like_per_day != 0:
            self.like_delay = self.time_in_day / random.randint(409,503)

        # Follow
        self.follow_time = follow_time
        self.follow_per_day = follow_per_day
        if self.follow_per_day != 0:
            self.follow_delay = self.time_in_day / random.randint(149,223)

        # Unfollow
        self.unfollow_per_day = unfollow_per_day
        if self.unfollow_per_day != 0:
            self.unfollow_delay = self.time_in_day / random.randint(149,223)`
use any of the below numbers only e.g. for 500 us use random.randint(409,503)
                  3      5      7     11     13     17     19     23     29 
     31     37     41     43     47     53     59     61     67     71 
     73     79     83     89     97    101    103    107    109    113 
    127    131    137    139    149    151    157    163    167    173 
    179    181    191    193    197    199    211    223    227    229 
    233    239    241    251    257    263    269    271    277    281 
    283    293    307    311    313    317    331    337    347    349 
    353    359    367    373    379    383    389    397    401    409 
    419    421    431    433    439    443    449    457    461    463 
    467    479    487    491    499    503    509    521    523    541 
    547    557    563    569    571    577    587    593    599    601 
    607    613    617    619    631    641    643    647    653    659 
    661    673    677    683    691    701    709    719    727    733 
    739    743    751    757    761    769    773    787    797    809 
    811    821    823    827    829    839    853    857    859    863 
    877    881    883    887    907    911    919    929    937    941 
    947    953    967    971    977    983    991    997   1009   1013 
   1019   1021   1031   1033   1039   1049   1051   1061   1063   1069 
   1087   1091   1093   1097   1103   1109   1117   1123   1129   1151 
   1153   1163   1171   1181   1187   1193   1201   1213   1217   1223 
   1229   1231   1237   1249   1259   1277   1279   1283   1289   1291 
   1297   1301   1303   1307   1319   1321   1327   1361   1367   1373 
   1381   1399   1409   1423   1427   1429   1433   1439   1447   1451 


thank me later

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by larmanrahimil** [comment]
guy i need to nee to set follower to following ratio and folloing to follower ratio whats the best value for these?

**Comment by Kohrnii** [comment]
Hey i have Problems with tue unfollow..
