### ISSUE TITLE
https link for hide history of selected user

### ISSUE THREAD

**Issue by napster2091** [instabot-py/instabot.py#532]
is there a way to hide the history directly from the bot? for example: if i want to follow some user i use the link https://www.instagram.com/web/friendships/%s/follow/ substituting %s with the user_id, what im looking for is an https link for hide the instagram history of a user that i decide. Just because i dont want to watch histories of peoples that are not my "really" friend. i tried to analyze http request with wireshark but no success.

**Comment by TehJokeR** [comment]
no - it would require javascript

**Comment by napster2091** [comment]
Thank you man
