### ISSUE TITLE
The bot only unfollows recent followings

### ISSUE THREAD

**Issue by duycieo** [instabot-py/instabot.py#533]
To whom it may concern,

Like the title has stated, my bot only unfollows recent followings. I set follow_time to say 2hr; after 2 hours, it starts to unfollowing users. However, it only unfollow my most recent followings. Any recommendations on this?

P/s: I've tried setting it to only seconds (ex. 15680) and even like recommended (2*60*60). None seem to change the outcome.

**Comment by ekremgurdal** [comment]
1) Extract your followings' user ids by using @LevPasha 's InstagramAPI application
2) Take that list and put them this application by calling bot.unfollow(User_id)

I've merged @LevPasha 's two application and using this way.

**Comment by ChipWolf** [comment]
@ekremgurdal got a branch for me to look at?

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket. We have new unfollowing method.
