### ISSUE TITLE
Bot displays users/posts as followed/liked, but not actually performing anything.

### ISSUE THREAD

**Issue by canpoyrazoglu** [instabot-py/instabot.py#534]
I'm trying to use the bot with my main account. I've used it successfully before with another account. Now, on my main account, it says login successful, and it likes and follows a post and a user. Then I open instagram, neither my following count has changed, nor the user is in the followings list, nor there's a new liked post at "posts you've liked" section.

Here's a sample output from the bot: (replaced my username with "myaccount"). Also please note that I've checked my following list *before* the bot unfollowed the user.

```
can@raspberrypi:~/instabot $ python myaccount.py 
Instabot v1.1.0 started at 09.05.2017 17:03:

Trying to login as myaccount...

myaccount login success!
Completed populating user blacklist with IDs
Get media id by tag: astro
Trying to like media: 1511034525270260245
Liked: 1511034525270260245. Like #1.
Trying to follow: 3875022737
Followed: 3875022737 #1.
Trying to unfollow #1: 
myaccount : Get media id on recent feed
Media in recent feed = 24
myaccount : Get user info 
09.05.2017 17:05
Checking user info..
Follower : 351
Following : 348
Media : 254
   >>>This is a normal account
   >>>This user is active
   >>>This account is following you
   >>>You are following this account
Trying to like media: 1511034459822422810
Liked: 1511034459822422810. Like #2.
Trying to like media: 1511034389945369431
Liked: 1511034389945369431. Like #3.
```

What might be the problem?

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
