### ISSUE TITLE
Unfollow error

### ISSUE THREAD

**Issue by theonlymine** [instabot-py/instabot.py#535]
I downloaded the latest version of instabot.

My parametres:

    like_per_day=0,
    comments_per_day=0,
    tag_list=['vsco', 'vscocam', 'nikon', 'canon', 'vscorussia'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=0,
    follow_per_day=0,
    follow_time=1 * 60,
    unfollow_per_day=1000,
    unfollow_break_min=2,
    unfollow_break_max=3

Get this error:

![image](https://cloud.githubusercontent.com/assets/28103030/25893117/468b6a3a-357f-11e7-9b13-fc74a8a46425.png)

Why?

Best wishes, Denis.

**Comment by artemdumanov** [comment]
Try it on linux :)

2017-05-10 12:47 GMT+03:00 theonlymine <notifications@github.com>:

**Comment by ugurozturk** [comment]
Please update your code. If you have the error open a new issue with new issue_template
