### ISSUE TITLE
Exception KeyError: KeyError(8928,)

### ISSUE THREAD

**Issue by SirOrigami** [instabot-py/instabot.py#536]
This always happens if i have comments ON after a while

Traceback (most recent call last):
  File "example.py", line 67, in <module>
    bot.new_auto_mod()
  File "D:\instabot.py-master\src\instabot.py", line 578, in new_auto_mod
    self.new_auto_mod_comments()
  File "D:\instabot.py-master\src\instabot.py", line 633, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "D:\instabot.py-master\src\instabot.py", line 657, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Logout: likes - 593, follow - 0, unfollow - 0, comments - 63.
Bot work time: 7:37:39.815000
Logout success!
Exception KeyError: KeyError(8928,) in <module 'threading' from 'C:\Python27\lib\threading.pyc'> ignored

**Comment by aparcedo** [comment]
Update the files please

**Comment by ChipWolf** [comment]
I've hit this error on a fresh pull, looking into it

**Comment by BobbyLE** [comment]
I still get this error while having a fresh pull.

Logout: likes - 706, follow - 248, unfollow - 207, comments - 82.
Bot work time: 20:02:19.922990
Logout success!
Exception KeyError: KeyError(140735214113552,) in <module 'threading' from '.../threading.pyc''> ignored

**Comment by Phalap** [comment]
Any news on this issue?

**Comment by antedoro** [comment]
Hi all,
I have the same problem on raspberry: 
"Logout: likes - 0, follow - 3, unfollow - 0, comments - 0.
Bot work time: 0:02:46.804312
Logout success!
Exception KeyError: KeyError(-1225236480,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored"

It's something to do?

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
