### ISSUE TITLE
Comments are written in small Letters

### ISSUE THREAD

**Issue by wimsjohn** [instabot-py/instabot.py#537]
After i changed my comments in instabot.py i saw that only the first letter gets written in capital.

**Comment by aparcedo** [comment]
Did you put them in capital letters?

**Comment by TehJokeR** [comment]
The generate comment method in instabot.py will return a sentence with just the first letter capitalised. This makes it look more 'authentic'. If you want to use your comments exactly how they are after you've updated the instabot.py file, change 'return res.capitalize()' to just 'return res'

```
def generate_comment(self):
        c_list = list(itertools.product(*self.comment_list))

        repl = [("  ", " "), (" .", "."), (" !", "!")]
        res = " ".join(random.choice(c_list))
        for s, r in repl:
            res = res.replace(s, r)
        return res.capitalize()
```

**Comment by TehJokeR** [comment]
This is not an issue - you can close this

**Comment by prestonjohnlewis** [comment]
Thank you!
Spark by Readdle
