### ISSUE TITLE
How and Why Instagram is allowing the request of request library.

### ISSUE THREAD

**Issue by shadrachbaldon** [instabot-py/instabot.py#538]
This is a great repo, I was just curious how the requests library is able to request actions on instagram without having things like connecting/permission of the intagram's API. Why and instagram allows the requests.

**Comment by ekremgurdal** [comment]
By using these libraries, 3rd party applications can be created. Ex: Repost app

**Comment by ByronKos** [comment]
If you look at [Line 42](https://github.com/instabot-py/instabot.py/blob/master/src/instabot.py#L42) you can see that it is not making requests to the instagram API, instead it is making HTTP requests you would make if you were browsing the website version of instagram. This is why there aren't any limitations as there would be on the API.

**Comment by shadrachbaldon** [comment]
@ByronKos awesome. so does this mean that other bots just like massplanner and similar bots will be shutdown by instagram but not this?

**Comment by ChipWolf** [comment]
It just makes a web request, like you do with the web/phone apps.
It's indistinguishable from usual traffic.
