### ISSUE TITLE
Instsabot don't like

### ISSUE THREAD

**Issue by Github1010** [instabot-py/instabot.py#539]
I add on my code (it was working well) the next class:
media_min_like: 1000.
With this, the program don't start to lika any photo and I don't know why, because with the selected tags, there are thousands of photos with that amount of likes!
Could be that the program try to like only the most recent feed, so with the few seconds from the publication there are no photos with these amount of likes?
Is there a possibility to like old media?

THANKS

**Comment by aparcedo** [comment]
It only likes recent media

**Comment by Github1010** [comment]
But there is any way to change it?
Because maybe re-writting some part of code is possible

**Comment by ekremgurdal** [comment]
min like and max like are the limit of photos. If you limit min like = 1000, bot only will like photos which have more than 1000 likes. I don't think there are lots of medias which have thousands of likes. You should not limit min like. Maybe you want to limit max like.
