### ISSUE TITLE
Choose like's

### ISSUE THREAD

**Issue by Github1010** [instabot-py/instabot.py#540]
Is there any possibility to choose that users who you like media, at least have a minimum of followers?
I explain better:
I have some required tags to follow.
With these selected tags, only put like to those account who at least have 1000followers.

THANKS

**Comment by egurdal-reidin** [comment]
You can set minimum or maximum like count by media_max_like = x and media_min_like = y
This one is not exact solution for your problem but it helps a little.

**Comment by ugurozturk** [comment]
No there is not right now. You can open as like feature request
