### ISSUE TITLE
How tu run?

### ISSUE THREAD

**Issue by johnmiles899** [instabot-py/instabot.py#541]
I'm new to coding so I dont know how to use/run this code. I already downloaded Python and PeCharm. But i dont know what to do next to use this code. Could someone please help me? 
Thanks in advance!

**Comment by zoh316** [comment]
@johnmiles899 even i am new but the best and easiest way is using pythonanywhere,
thank me later.
check this video 
https://www.youtube.com/watch?v=f91SdRLHQj4

**Comment by ChipWolf** [comment]
u run using unicorn magic brah
