### ISSUE TITLE
KeyError: 'graphql'

### ISSUE THREAD

**Issue by AdrianaVecc** [instabot-py/instabot.py#542]
It was working fine, but now I get this error:

> Traceback (most recent call last):
  File "insta.py", line 57, in <module>
    bot.new_auto_mod()
  File "/Users/adriana/Documents/instabot.py", line 527, in new_auto_mod
    self.new_auto_mod_comments()
  File "/Users/adriana/Documents/instabot.py", line 580, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "/Users/adriana/Documents/instabot.py", line 612, in check_exisiting_comment
    if all_data['graphql']['shortcode_media']['owner']['id'] == self.user_id:
KeyError: 'graphql'

Did Instagram modify again the format of url_media_detail? (cf. https://github.com/instabot-py/instabot.py/issues/481) Thanks!

**Comment by johnmiles899** [comment]
I'm new to coding so I dont know how to use/run this code. I already downloaded Python and PeCharm. But i dont know what to do next to use this code. Could you please help me?
Thanks in advance!

**Comment by bovas85** [comment]
can you do a print all_data and see what the first node is?

**Comment by bovas85** [comment]
something like 
`try:
    # code of check existing comment
except KeyError, err:
    print "Key error", err`

**Comment by AdrianaVecc** [comment]
I think I found the issue. When Instagram flags the account for suspicious activity, you have to manually confirm it was you. I believe this error is concomitant with the flag

**Comment by lleviy** [comment]
So how do you solve this?

**Comment by nickgryg** [comment]
Please have a look to #2442
