### ISSUE TITLE
Unlike Pictures

### ISSUE THREAD

**Issue by svallej** [instabot-py/instabot.py#55]
It's possible to unlike pictures that i've liked before?

"Just wondering"

Thank you

**Comment by LevPasha** [comment]
@svallej bot.unlike('media_id').

**Comment by alvvvvvin** [comment]
Hey @LevPasha ! I was wondering: can you set the unlike feature the same way as unfollow?

For example: 

`unlike_per_day = 150`

would unlike the last 150 posts, and with:

'follow_time=5*60*60'

would wait 5 hours, 60 min, 60 sec. before unliking the most recent 150 liked photos.

**Comment by lurcovq** [comment]
Could anyone show me how this would be implemented? As in how it would be wrote in with the working example LevPasha supplied. Thanks :)

**Comment by alvvvvvin** [comment]
@lurcovq At the moment, the function of unlike only seems to support unliking a specific piece of content based on a unique id of the picture. (I think)

**Comment by svallej** [comment]
@alvvvvvin Yes you're right but looking deep on the function that unfollow the recent follow from my account, i think it can be the same. 

` def new_auto_mod_unfollow(self):
        if time.time()>self.next_iteration["Unfollow"] and \
            self.unfollow_per_day!=0 and len(self.bot_follow_list) > 0:
            for f in self.bot_follow_list:
                if time.time() > (f[1] + self.follow_time):

                    log_string = "Try to unfollow: %s" % (f[0])
                    self.write_log(log_string)

                    if self.unfollow(f[0]) != False:
                        self.bot_follow_list.remove(f)
                        self.next_iteration["Unfollow"] = time.time() +\
                                self.add_time(self.unfollow_delay)
`

And this is the unlike function simple not auto.

`def unlike(self, media_id):
        """ Send http request to unlike media by ID """
        if (self.login_status):
            url_unlike = self.url_unlike % (media_id)
            try:
                unlike = self.s.post(url_unlike)
            except:
                self.write_log("Exept on unlike!")
                unlike = 0
            return unlike`

How do we create the same like unfollow like unlike?

**Comment by ChipWolf** [comment]
Out of scope
