### ISSUE TITLE
Cannont Import requests when trying to run

### ISSUE THREAD

**Issue by Bornagainfatkid** [instabot-py/instabot.py#555]
I know this has been talked about in the past but i've tried all possibilities. 

I've tried to install requests every way possible. I've googled and read all possible links haha. I can not get this to run. I consistently just get.

Traceback (most recent call last):
File "example.py", line 12, in 
from instabot import InstaBot
File "/Users/HomeBase/Documents/Projects/projectfolder/instabot.py-master/src/instabot.py", line 16, in 
import requests
ImportError: No module named requests﻿

I've already installed this:
-MacBook-Pro:instabot.py-master HomeBase$ pip install -r requirements.txt
Requirement already satisfied: requests==2.12.4 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
-MacBook-Pro:instabot.py-master HomeBase$ python example.py
Traceback (most recent call last):
File "example.py", line 12, in 
from instabot import InstaBot﻿

I've installed pip,pip2,pip3 doesn't matter same result.

**Comment by luisramirez-m** [comment]
You installed requests? can you show result of `pip freeze` on your console?

You try install requests with http://docs.python-requests.org/en/master/user/install/

**Comment by Bornagainfatkid** [comment]
@luisramirez-m 
I just installed with the link you posted also 

pip freeze:
Christians-MacBook-Pro:instabot.py-master HomeBase$ pip freeze
appdirs==1.4.3
packaging==16.8
pyparsing==2.2.0
requests==2.14.2
six==1.10.0

**Comment by luisramirez-m** [comment]
@Bornagainfatkid and works? or do you still having problems?

**Comment by Bornagainfatkid** [comment]
@luisramirez-m 
Sorry, still have the problem, this is the full console output 

Christians-MacBook-Pro:instabot.py-master HomeBase$ git clone git://github.com/kennethreitz/requests.git
Cloning into 'requests'...
remote: Counting objects: 19763, done.
remote: Compressing objects: 100% (123/123), done.
remote: Total 19763 (delta 48), reused 0 (delta 0), pack-reused 19640
Receiving objects: 100% (19763/19763), 8.74 MiB | 3.73 MiB/s, done.
Resolving deltas: 100% (12876/12876), done.
Checking connectivity... done.
Christians-MacBook-Pro:instabot.py-master HomeBase$ python example.py
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    from instabot import InstaBot
  File "/Users/HomeBase/Documents/Projects/BaphIG/instabot.py-master/src/instabot.py", line 16, in <module>
    import requests
ImportError: No module named requests
Christians-MacBook-Pro:instabot.py-master HomeBase$ pip freeze
appdirs==1.4.3
packaging==16.8
pyparsing==2.2.0
requests==2.14.2
six==1.10.0

When i make sure to install reqs from requirements.txt i now get this.. I may need to just start over. 
Christians-MacBook-Pro:instabot.py-master HomeBase$ pip install -r requirements.txt
Collecting requests==2.12.4 (from -r requirements.txt (line 1))
  Using cached requests-2.12.4-py2.py3-none-any.whl
Installing collected packages: requests
  Found existing installation: requests 2.14.2
    Uninstalling requests-2.14.2:
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/requests-2.14.2.dist-info/DESCRIPTION.rst'

**Comment by Bornagainfatkid** [comment]
@LevPasha Can you close this, I figured this out. 

I installed python 3 and then used 'python3 example.py' everything worked

**Comment by FERMAT1991** [comment]
pip install requests and it worked for me always try to install things that don't exist
