### ISSUE TITLE
Please, help me.

### ISSUE THREAD

**Issue by GiuseppeCuna** [instabot-py/instabot.py#556]
Hello everyone, my name is **Giuseppe Cuna** and my artist name is **Azel** (Instagram: @azelbeatbox) and I **need** your help guys!

I'm actually **new** to coding and I found this git _perfect_ and **absolutely** **useful** for what I'm doing at the moment (Managing an important BEATBOX Instagram Page for myself to keep living with it).

In this period I'm having _**exams**_ and many other **stressful** things that I can't manage if I always think about social media like Instagram.

I need someone, like @LevPasha, that is able to help me out because I need these **only** **three** functions already set in a .py file and ready to run:

1) "**Infinity_Feedliker.py**" - Because I need to like every post published instantly on my Instagram feed and show to them that I'm active, but in real life I'm not because I'm always busy as hell.
2) "**Like_By_Hashtag.py**" - Because I need to like every post published with the hashtags: #beatbox; #beatboxing.
3) "**Like_Your_Last_Media_Likers.py**" - Because if someone appriciate my content, I need to exchange the favour to be polite.

Please, _help_ _me_ because it's very important; **thanks** in advance and sorry for my bad english.

(Down here is a screen about my Instagram Profile)
![screencapture-instagram-azelbeatbox-1495114815818](https://cloud.githubusercontent.com/assets/10977801/26204907/8b69e35e-3be0-11e7-988f-f2b51d4dc45a.png)

**Comment by ekremgurdal** [comment]
This requires additional development on this project. With this version only helps your 2nd request

**Comment by GiuseppeCuna** [comment]
Okay, _thanks_ @ekremgurdal.

Can anyone else _help_ _me_ out with this problem?
Because if actually **exist** a way to create a code relied on my second request, I think that someone like @LevPasha can help me out with the _other_ _ones_.

_Thanks_ in advance to everyone, I love this project _please_ **help** **me**!

**Comment by GiuseppeCuna** [comment]
I found _two_ **non-compatible** _.py_ files with **InstaBot** that gives me the ability to execute the **first** and the **third** (_last_) request I mentioned before in my main issue-post, can anyone please **help** **me** out to make them _compatible_ with **InstaBot** (@LevPasha) in _any_ _possible_ _way_?

**Links** for the _files_ right here:
1) https://drive.google.com/file/d/0B1HMSalOPNHXMUg1a2l0SnlYUm8/view.
2) https://drive.google.com/file/d/0B1HMSalOPNHXa1RXNmVFdjlmTTA/view.

**Thanks** in _advance_.
