### ISSUE TITLE
New functionality / Новый функционал 

### ISSUE THREAD

**Issue by djtimone** [instabot-py/instabot.py#560]
Hello Gyus, you need to extend the functionality of uor application for further development.
1) Gender users have opportunity to concentrate on women or men it is indicated in the account
2) Like`ing only followers
3) Work on the geo-position
4) Halt the followers of a  certain group of accouunt
-----------------------------------
Привет ребята, необходимо расширить функционал нашего приложения для дальнейшего развития. 
1) Пол пользователей возможность сконцентрироваться на женщинах или мужчинах он указывается в аккаунте
2) Лайкать только фолловеров 
3) Работа по геопозиции 
4) Лайкать фолловеров определенной группы аккаунтов

**Comment by ChipWolf** [comment]
We **need** to do we?
Nice, make a pull request and we'll see if your changes are suitable.
