### ISSUE TITLE
Like error 400, but not blocked on App or Web

### ISSUE THREAD

**Issue by testinghack** [instabot-py/instabot.py#562]
Hi, I am getting error like 400 while running the bot in one of my accounts for days!

I am not blocked, I can like thru the App on a mobile, as I can like logging into the Web, on the same computer the bot runs or other computers.

I have tried to run the bot in other computers and I get the same error. 

I can run the Bot for my other account on the same computer and I don´t get any problem.

The issue seems specifically to 1 of my accounts and only running the Bot, I have tried everything I am not sure why I am getting this error.

Anyone has any idea or experience similar issue?

**Comment by lsdsssc** [comment]
If the issue is on only on that 1 account , wait 24 hours , then try use bot.

**Comment by testinghack** [comment]
I waited more than 24 hrs and didn´t work. I downloaded the Demo version of the C# option and I don´t get a error there, in parallel I run the python bot and I get the error.

In the mobile app it is also not blocked. 

I am in this situation for days and not finding a light at the end of the tunnel.

Anyone, has experienced something like this? Since it is clear the account is not blocked.

**Comment by parthshiras** [comment]
Same is the case with me. Any breakthrough so far @testinghack?

**Comment by ChipWolf** [comment]
Where are you running the bot?

**Comment by testinghack** [comment]
@parthshiras no breakthrough, it started to work again after a few days. Really weird, as in no moment I was blocked in the app, could manually like or in the web.

@ChipWolf Windows box.

**Comment by ChipWolf** [comment]
Yeah, I'm hearing about this quite a bit.
I'm starting to wonder if Instagram are testing some preventative measures.

**Comment by TehJokeR** [comment]
It's definitely not an issue with 2way authentication is it? Do you need to authorise the IP address/computer where you are running the bot?

**Comment by parthshiras** [comment]
I can follow/unfollow, comment with the bot. But **cannot like** any media using the bot. So as a testing measure, I logged in the bot using a different account and could perform all functions(like/comment/follow) without any issues. 

This is my guess - Instagram is blocking my IP address from the bot to like photos because I have received soft bans a lot of times. 

Thinking of a workaround for the issue. Will keep you guys posted. Please let me know in case you guys come up with something.

**Comment by rebeloper** [comment]
Same problem here: running in pythonanywhere and cannot like error 400

**Comment by ierogliph** [comment]
Hi. 

Can u show ur code before string "while True:"? It is a block with bot options.

**Comment by rebeloper** [comment]
@ierogliph  I have only changed the username and password.

Today on first launch the first like attempt for 'follow4follow' was successful but 400 after that :(

**Comment by ChipWolf** [comment]
My bot is running fine fyi

**Comment by morenitodelnorte** [comment]
Hi I have the same issue, since one week I cannot like with my bot but follow/unfollow and comment is no problem. I am not banned since I can like with the App and on the site. Does anyone have an idea why is this happening and how long do I have to wait?
I am running the script in pythonanywhere 
@ChipWolf The script that I am using is yours
In other accounts it is working without any problem

**Comment by ChipWolf** [comment]
Accounts get throttled if you're being too aggressive, leave it cold for a few days and reduce the numbers you're trying to achieve @morenitodelnorte

**Comment by morenitodelnorte** [comment]
@ChipWolf I was liking 1000 and comment 100

But thank you, I will leave it cold a few more days

**Comment by ChipWolf** [comment]
@morenitodelnorte sounds pretty aggressive to me, especially for a new account.
Try at around 750 next time.

**Comment by morenitodelnorte** [comment]
I have the account for more than 4 years and at the beginning your script was working really good, without any problem and it is still working good in other accounts that I manage.
Did Instagram change something?

**Comment by parthshiras** [comment]
My account is cold since more than 2 weeks now. No progress. Still can't use the bot.

**Comment by ChipWolf** [comment]
Might be softbanned? I mean, who knows how IG's internals work

**Comment by TehJokeR** [comment]
Try using a proxy / different VM. I think I was IP banned earlier because when I changed the proxy the bot started working again. Everything was fully functioning on my iPhone but the bot wasnt working.

**Comment by parthshiras** [comment]
Tried that as well. I installed the bot on Python anywhere after this problem and faced the same issue. I don't want to give up on the bot though. I'll keep you guys posted if I progress somehow.

**Comment by ThomasMW** [comment]
Please not that the media is actually still liked, but still returns a 400 status code.

So the endpoint seems to be correct, these 400 codes could mean the Instagram just receives too many requests in a short period of time from the same IP.

Who here receiving these status codes are on PythonAnywhere? If a lot of people are hosting their bot here it seems there are too many requests are coming from their servers and Instagram registers it as spam.

My advice would be to take the bot off PythonAnywhere and host it somewhere else.

**Comment by parthshiras** [comment]
@ThomasMW That is a great insight. I took the bot off from PythonAnywhere. I quickly tried it on my Mac though, but still no use.

**Comment by parthshiras** [comment]
The problem is not with the IP, it is with Instagram registering an issue when we use the bot and the account which errors out. Because I used the same IP on a different account and it still worked fine for me.

**Comment by TehJokeR** [comment]
@parthshiras  "Please not that the media is actually still liked, but still returns a 400 status code." - is this the same in your case? Is your account liking the media or is it returning 400 and also not 'liking' the media?

https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1

> 10.4.1 400 Bad Request
> 
> The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modifications.
> 

Perhaps your account is blocked from sending the 'bad requests' to the server, but valid requests are still allowed ( hence the app still working ).

**Comment by ThomasMW** [comment]
The media is still liked, so in what sense is it a bad request?
Did someone take a look at endpoint or request being made and see if it's still correct?

Calling @ChipWolf

**Comment by parthshiras** [comment]
@TehJokeR Apologies for the confusion- The account is returning 400 and also not liking the media.

Is there a way to modify the code to send valid requests as opposed to 'bad requests'?

**Comment by ThomasMW** [comment]
@LevPasha 

Please take a look at this.

**Comment by drovid** [comment]
For me it was a shadowban ON THE IP ADDRESS. Switching to my LTE conection fixed the issue for me. Will be changing IP and taking a cooldown period until trying again...

**Comment by thefatpanda333** [comment]
@drovid Switching to LTE also worked for me. I also noticed that accounts that I am running with a proxy are running fine. So error 400 is definitely regarding some sort of ban on outbound likes. I will be setting up an additional proxy and taking a cool down period as well

**Comment by mswinterless** [comment]
In my case I've been running the bot in my phone with pythonanywhere, pythonanywhere in laptop and windows box and I have the problem just with first two, so.....

**Comment by ThomasMW** [comment]
As stated before, the IPs from PythonAnywhere have likely been flagged. The obvious solution is to run the bot somewhere else.

**Comment by morenitodelnorte** [comment]
Does anyone know a site like pythonanywhere? Or experience with hidemyass proxy?

**Comment by crashwins** [comment]
Same issue here...I had my likes at 950, no comments or follow/unfollow, though. Both of my accounts are returning the error and I'm not seeing any actual "likes" coming up on IG. So I'm guessing my only recourse is to run the script from another IP, eh? I just run it from a Pi.

**Comment by parthshiras** [comment]
The IP is being flagged. Use a different one.

**Comment by crashwins** [comment]
@parthshiras How does one do that; set up a proxy? I'm using a Pi. Thanks!

**Comment by parthshiras** [comment]
Set up a different proxy/Use a VM

**Comment by crashwins** [comment]
@parthshiras Any recommendations to do this with a Pi? Hamachi?

**Comment by wanlorn75** [comment]
with this problem I've tried to stop liking for one day. After that it seems to work, but after 20-30 like the error 400 started again, so I tried to start with few like in a day anche with 100 like in a day I've not the erroe. So I tried with 300 like and it was good for 10 hours and then the error coming out again.

Now I'm tryng to figure this out. Maybe instagram is just reducing the number of like that an user can make in one hour and using a specific user agent.

I'm testing in last 8 hour with 150 like x day and so far no troubles. I'll try to find the maximum number I can like to stay safe.

**Comment by TBob23** [comment]
Same problems here, the bot worked fine for weeks - multiple accounts. Since 3-4 days it's not possible to like any media and the result is "Not liked: 400". Try to figure out whats the problem is...

**Comment by crashwins** [comment]
Great..that's a bummer. I'm not doing to even bother with changing my IP then. I noticed mine worked fine yesterday morning for about 10 mins...Had the likes at 600. I decided to drop the number to 100 this morning, but no longer working. Seems like no one is having the same problem here; and how is it that this is working for anyone at this point? Interestingly, I liked a bunch of stuff using my computer and this did work...So not just a mobile thing. Ugh

**Comment by zoh316** [comment]
Same issue with me, i use pythonanywhere, settings are low, 700 likes 300 follow, unfollow. 
Was working perfectly for months but since last week this issue started. Not liked 400
Tried 2 different accounts but same issue.

**Comment by thefatpanda333** [comment]
Try setting the max media likes to less than what you have your total daily likes set at.

**Comment by vinceze** [comment]
I'm having the same issue...

**Comment by rferrato** [comment]
someone found the solution or some hint?

**Comment by stephenhyde** [comment]
I had some luck using dedicated private ip's with different subnets for each user, but I do get the occasional 400 throttling, where I need to cycle them to a new ip address. Quite annoying, wish I had a more bullet proof answer.  A cool feature would be to ip cycle users but automatically hit the "It was me" on the previous ip that was whitelisted. I been kinda doing that where once I hit it was me on one ip, I can use that IP to hit "it was me" programmatically for every ip i rotate to. Not bullet proof but a possibility. Mind you rotating your ip's too frequently will prob raise flags in their backend.

**Comment by TBob23** [comment]
How many bots do you guys run in parallel? If I only run one instance, everything's fine, as soon as I start the second, I get error 400 within a minute or so.

**Comment by stephenhyde** [comment]
ya I noticed the same thing TBob, now i run 50 or more parallel but on different private proxies subnets, seem to be helping.

**Comment by drovid** [comment]
yep, ive been running like 5-6 bots, but gonna have to run each on
dedicated IP.

What's the best way to run raspberry pi on a proxy? any help would be
appreciated

**Comment by stephenhyde** [comment]
The python script has built in proxy support so I would think its agnostic of if its running on linux or rasberry pi. Add proxy='username:password@ip:port' or just 'ip:port' if not private, to your python script arguments. @drovid

**Comment by TBob23** [comment]
thanks guys - it's working absolutely fine with dedicated proxies

**Comment by rferrato** [comment]
@TBob23 rly man? how many acc per proxy r u using?

**Comment by koeniig2** [comment]
i have the error400, and i tried to change the proxie. But it still does not like the pictures. why people say its working with dedicated proxies... for me its not. using 1 different proxy

**Comment by thefatpanda333** [comment]
you cannot use pythonanywhere - they were flagged by IG weeks ago

**Comment by TBob23** [comment]
@rferrato: I'm running 1 acc per proxy

**Comment by drovid** [comment]
whoa, what?? how do i set up a proxy? I'm using raspberry pi, if that
helps. All efforts to configure a proxy have failed, and this might be my
last chance.

Please help

**Comment by drovid** [comment]
@stephenhyde if you could help me how to set it up, I'd really really really appreciate it. cauzse setting up a proxy on rasoberry pi is the most difficult thing I've ever done so far

**Comment by TehJokeR** [comment]
@drovid just choose a public proxy from any website you can find and add it in as a variable to the script. There's a variable proxy = 'ip:port' you can enable to use the proxy

**Comment by TehJokeR** [comment]
Just make sure your proxy is located within a close proximity to your actual location OR disconnect from other devices while running the bot.

**Comment by drovid** [comment]
@TehJokeR uum... I'm a total noob at python, where exactly should I put the "ip:port" and in what file?

thank you

**Comment by napster2091** [comment]
i noticed that the bot doesn't understand when it is trying to follow someone that you have already followed. i had the same problem with error 400, i modified the bot adding a function that checks if the user im going to follow it is already between the followings, fixed this my bot works 100%.

**Comment by napster2091** [comment]
```
i try to link my code if it can help you:

**inside follow function i added:**

def new_auto_mod_follow(self):
        if time.time() > self.next_iteration["Follow"] and self.follow_per_day != 0 and len(self.media_by_tag) > 0:
            if self.like_per_day == 0:
                self.get_media_id_by_tag(random.choice(self.tag_list))
            if self.media_by_tag[0]["owner"]["id"] == self.user_id:
                self.write_log("Keep calm - It's your own profile ;)")
                return
            **if(self.check_followed_fromfile(self.media_by_tag[0]["owner"]["id"]) != True):**
                log_string = "Trying to follow: %s" % (self.media_by_tag[0]["owner"]["id"])
                self.write_log(log_string)
                if self.follow(self.media_by_tag[0]["owner"]["id"]) != False:
                    self.bot_follow_list.append([self.media_by_tag[0]["owner"]["id"],
                                             time.time()])
                    self.next_iteration["Follow"] = time.time() + self.add_time(self.time_in_day / 
                                                random.randint(self.follow_per_daymin,self.follow_per_daymax))
                    self.write_followlist_to_file(self.media_by_tag[0]["owner"]["id"])

**then i have a file where i save the userids of the followings and i invoke the function on this file to check if im already following this user:**

def check_followed_fromfile(self,followuser):
        try:
            f = open('followlist.txt', "r")
            try:
                lines = f.readlines()
                f.close()
                lineslen = len(lines)
                log_string = "Checking file if %s is already followed" % followuser
                self.write_log(log_string)
                for line in lines:
                    if line.rstrip('\n') == followuser:
                        log_string = "%s is already followed" % followuser
                        self.write_log(log_string)
                        self.get_media_id_by_tag(random.choice(self.tag_list))
                        return True
            finally:
                f.close()
        except IOError:
            log_string = "Error reading file check_followed_fromfile"
            self.write_log(log_string)
            pass

**function to write in a file is:**

def write_followlist_to_file(self,iduser):
        try:
            f = open('followlist.txt', "a")
            try:
                log_string = "Writing %s to file followlist.txt" % iduser
                self.write_log(log_string)
                f.write(iduser)
                f.write('\n')
            finally:
                f.close()
        except IOError:
            log_string = "Error writing file write_followlist_to_file"
            self.write_log(log_string)
            pass

**function to update the followlist file when you unfollow someone is:**

def check_followlist_from_file(self, unfollowuser):
        try:
            f = open('followlist.txt', "r")
            try:
                lines = f.readlines()
                f.close()
                f = open('followlist.txt', "w")
                point = 1
                lineslen = len(lines)
                log_string = "Updating file %i of %i" % (point, lineslen)
                self.write_log(log_string)
                for line in lines:
                    if line.rstrip('\n') != unfollowuser:
                        point += 1
                        f.write(line)
                        log_string = "Updating file %i of %i" % (point, lineslen)
                        self.write_log(log_string)
            finally:
                f.close()
        except IOError:
            log_string = "Error reading file check_followlist_from_file"
            self.write_log(log_string)
            pass

**function to insert the followings when you rerun the bot after a close:**

def read_followlist_from_file(self):
        try:
            f = open('followlist.txt', "r")
            try:
                iduser = f.readline().rstrip('\n')
                while iduser:
                    log_string = "Reading iduser %s" % (iduser)
                    self.write_log(log_string)
                    self.bot_follow_list.append([iduser,int(-24*60*60)])
                    self.follow_counter += 1
                    iduser = f.readline().rstrip('\n')
            finally:
                f.close()
        except IOError:
            log_string = "Error reading file read_followlist_from_file"
            self.write_log(log_string)
            pass
```

**Comment by gersanchez** [comment]
where did you put this code? at the end?

**Comment by soterorar** [comment]
hi @stephenhyde .... whats the service of private proxies you're using?

**Comment by CamiloB** [comment]
@napster2091  hi i try your code and still have the not like 400

**Comment by ugurozturk** [comment]
use https://github.com/instabot-py/instabot.py/issues/887 to track it in the future
