### ISSUE TITLE
Credentials security

### ISSUE THREAD

**Issue by wsdt** [instabot-py/instabot.py#563]
Wouldn't it better, if you run this program online, that you make it possible to authorize a user to start the bot. Additionally user credentials would not readable in a text file. 

Like that for example: 
```


# Fill in, if you want to log in automatically / Let it empty to need authorization (argv parameters)
if len(sys.argv) < 2:
	tmp_login = 'yourIG'
	tmp_password = 'yourPassw'
else: 
	tmp_login = sys.argv[1]
	tmp_password = sys.argv[2]

bot = InstaBot(
	login=tmp_login,
	password=tmp_password,
	like_per_day=1000,
```

**Comment by ChipWolf** [comment]
Secrets in command line parameters is less secure than storing them in a file, I agree it's not ideal as-is; but moving to CLI based arguments for authentication is even riskier than current.
