### ISSUE TITLE
Like media of an specific user followers

### ISSUE THREAD

**Issue by Github1010** [instabot-py/instabot.py#564]
Hello.
There is any possibility of choose a user, and to like the media of their followers?
For example, my account is related with beauty so I select an important user related with "beauty" and start to like the media of the people who follows this user.
THANKS

**Comment by ktcith** [comment]
I want the exact same feature. I wanna follow the medias under my followers.
Is there any way to do it?

Also, with current script, how do they follow medias? medias filtered with tags on instagram?
@artemdumanov

**Comment by TehJokeR** [comment]
Currently I dont think the bot supports this functionality.

The script as it stands will search for tags on instagram and then follow the users in the feed that's returned.

**Comment by ChipWolf** [comment]
Planned feature, other issues have featured this request.

**Comment by Github1010** [comment]
So tell me whete is this request, because I dont find it.
Thanks


Joan

-------- Mensaje original --------
De: Chip Wolf ‮ <notifications@github.com> 
Fecha: 29/05/2017  18:36  (GMT+01:00) 
Para: "instabot-py/instabot.py" <instabot.py@noreply.github.com> 
Cc: Github1010 <joan1593@gmail.com>,Author <author@noreply.github.com> 
Asunto: Re: [instabot-py/instabot.py] Like media of an specific user followers (#564) 
 
Planned feature, other issues have featured this request.

**Comment by ChipWolf** [comment]
#558 @Github1010
