### ISSUE TITLE
ink361 from module userinfo (+по русски)

### ISSUE THREAD

**Issue by aks4kj** [instabot-py/instabot.py#565]
Hello everyone, has anyone know how to use example from userinfo.py:

```
# example
ui = UserInfo()
# search by user_name:
ui.search_user(user_name="danbilzerian")
# or if you know user_id ui.search_user(user_id="50417061")
print(ui.user_name)
print(ui.user_id)

# get following list with no limit
ui.get_following()
print(ui.following)

# get followers list with limit 10
ui.get_followers(limit=10)
print(ui.followers)
```
Print show nothing, may be service ink361 didn't work or something else? Need method how to get all folowings from account, to not unfolowing from them. 

Павел, подскажите пожалуйста как выгрузить все подписки из аккаунта, чтобы добавить их в словарь unfollow whitelist. Либо есть более простой способ сделать так чтобы скрипт не отписывался от тех, на кого пользователь был подписан (даже если там есть аккаунты подходящие по параметрам).

**Comment by ChipWolf** [comment]
ink361 is down, read other issues
