### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by thibcop** [instabot-py/instabot.py#567]
Hi all,
I have an error when I am trying to launch the python code.
My login is ok but here is the error 👍 
![sans titre](https://cloud.githubusercontent.com/assets/28755100/26344738/f6dff678-3fa0-11e7-90e1-925a7feede30.png)
Do yo have any ideas? 
Thanks a lot and have a good day :)

**Comment by ChipWolf** [comment]
Python issue, use 2.7
