### ISSUE TITLE
How to stop the bot liking stuff of users you already follow / follow you?

### ISSUE THREAD

**Issue by ricc123** [instabot-py/instabot.py#568]
Would i need to enter all tof he friends id's in the blacklist or is there a simpler way?

**Comment by ChipWolf** [comment]
Blacklist.

**Comment by petergriffin1986** [comment]
How big can the blacklist be? I have 8000 followers, where can I get the list of all usernames? can it fit in the blacklist?

**Comment by ChipWolf** [comment]
@petergriffin1986 https://github.com/LevPasha/Instagram-API-python
getUserFollowers()
