### ISSUE TITLE
Best Settings? what settings are you using?

### ISSUE THREAD

**Issue by KoenJonguh** [instabot-py/instabot.py#570]
Hello, i was wondering what settings you people are using and what the results are.
So how many likes per day, follow/unfollow per day, follow break, follow time etc.
You would help me out a lot! thanks :)

**Comment by TehJokeR** [comment]
That depends on how active you want your account to be.
My personal preference is
follows: 900 
unfollows: 400
likes: 0
comments: 0
follow time: 60-120 minutes

**Comment by ChipWolf** [comment]
This isn't a discussion forum, join the Telegram. Link in README.
