### ISSUE TITLE
Unfollow everybody guidance

### ISSUE THREAD

**Issue by aaisataev** [instabot-py/instabot.py#574]
How to use mode 5 in burst mode? What does it mean? What I need to change in code?

**Comment by TehJokeR** [comment]
'Burst mode' means to run it for a couple of minutes every few hours as opposed to suiciding it 24/7.

You can only unfollow 100 people every every, so it's suggested to run it for a couple of minutes and then stop the script.

You shouldnt need to change the code but instead just stop the script after a 'burst' of unfollows.
