### ISSUE TITLE
Setup a Like-List

### ISSUE THREAD

**Issue by ProgrammingDude** [instabot-py/instabot.py#575]
Hey guys,
how can I setup a custom list to like or comment someones post?

The purpose of it:

It should like or comment the latest pics of selected users.

Is it possible?

Would be nice to get a response and thanks for your help!

-Jason

**Comment by TehJokeR** [comment]
Hi,

Currently there's no functionality to target specific users. This functionality is planned and is not an 'issue' but instead a 'request'

Can you close the issue?

/TJ
