### ISSUE TITLE
neither 'self_following' or 'self_follower' appear to be set at any point.

### ISSUE THREAD

**Issue by kaieden** [instabot-py/instabot.py#576]
I was investigating why the modes in the calling script didn't appear to work as intended - non of the while loops are ever entered. I grep-ed for the two properties mentioned in the title, and they don't appear to be set anywhere. 

What are they for, and does somebody with instagram knowledge know how to set them?

**Comment by TehJokeR** [comment]
Hi Kaieden,

Both variables are used in the elif block of code for mode 1 in example.py

It seems to be a numeric value which is used for calculations

This section is for issues only

//

**Comment by kaieden** [comment]
Forgive me, I appear to have jumped the gun.

I have found where the data is pulled from and set in 'user_info.py', I missed it on first inspection. 

I was concerned that they always appeared to return 0, suggesting that they fall onto the defaults set in the constructor and were otherwise unused. 

I wasn't invoking check_status, and that was where the issue lay.

**Comment by TehJokeR** [comment]
Hi Kaieden, -- (( Sorry, I just re-read your question ))

Both variables are set in the block of code for get_user_info() in user_info.py

```
follows = user_info['user']['follows']['count']
follower = user_info['user']['followed_by']['count']
if self.is_self_checking is not False:
    self.self_following = follows
    self.self_follower = follower
```

and this block of code will run when calling the check_status method in check_status.py
```

def check_status(self):
    self.is_self_checking = True
    self.is_checked = False
    while self.is_checked != True:
        get_user_info(self, self.user_login)
    self.like_counter = 0
    self.follow_counter = 0
    self.unfollow_counter = 0

```

**Comment by TehJokeR** [comment]
If there's no issue here, can you close the issue?

(( If it's possible for the author to close issues without a developer doing it ))

//TJ

**Comment by kaieden** [comment]
Already done so. Cheers
