### ISSUE TITLE
Problem when using mode 4

### ISSUE THREAD

**Issue by fernandoacf** [instabot-py/instabot.py#580]
Hello!

I'm getting problem when using mode 4. First I was getting exception on line 214 from src/instabot.py while trying to import JSONDecodeError from json. Importing the same from the simplejson worked. 

But now the bot is always getting except on get_info. Anyone can help?

**Comment by ChipWolf** [comment]
throw the exception on get_info with
```
except Exception as e:
   self.write_log(e)
```
instead of
```
except:
  self.write_log("except on get_info")
```

**Comment by fernandoacf** [comment]
Done. Received return error:

No JSON object could be decoded

**Comment by ChipWolf** [comment]
Directly under the except...
`self.write_log(all_data)`

**Comment by fernandoacf** [comment]
not defined variable..

Traceback (most recent call last):
  File "facarvalho.py", line 97, in <module>
    feed_scanner(bot)
  File "/home/fiend/instabot/instabot.py/src/feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "/home/fiend/instabot/instabot.py/src/likers_graber_protocol.py", line 21, in likers_graber_protocol
    get_media_id_user_feed(self)
  File "/home/fiend/instabot/instabot.py/src/user_feed.py", line 16, in get_media_id_user_feed
    get_user_info(self, self.current_user)
  File "/home/fiend/instabot/instabot.py/src/user_info.py", line 84, in get_user_info
    self.write_log(all_data)
NameError: global name 'all_data' is not defined
Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
Bot work time: 0:00:21.244349
Logout success!
Exception KeyError: KeyError(140653488318208,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

**Comment by ChipWolf** [comment]
which mode are you using?

**Comment by fernandoacf** [comment]
mode 4

**Comment by ChipWolf** [comment]
Ah, that explains everything.
Mode 1-5 are not supported yet
use mode 0
