### ISSUE TITLE
Not working overtime

### ISSUE THREAD

**Issue by DJJPISAWESOME** [instabot-py/instabot.py#582]
This is the error i get can anyone help? I know this is a recurring error i've used fix #373 but am still getting the error ( Bot running on https://www.pythonanywhere.com).

Traceback (most recent call last):
  File "/home/DJJP/instabot.py/example.py", line 75, in <module>
    bot.new_auto_mod()
  File "/home/DJJP/instabot.py/src/instabot.py", line 582, in new_auto_mod
    self.new_auto_mod_comments()
  File "/home/DJJP/instabot.py/src/instabot.py", line 637, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "/home/DJJP/instabot.py/src/instabot.py", line 661, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by DJJPISAWESOME** [comment]
I think i found the error but im not sure how to fix it under instabot.py/src/instabot.py in line 217 it says: except JSONDecodeError as e: but isn't assigned. idk this is my guess for now

**Comment by TehJokeR** [comment]
You can workaround this by setting comments to 0. This exception is thrown during the commenting function

**Comment by DJJPISAWESOME** [comment]
I'll try that thanks! is going to be an update that will fix that? because most followers follow because of the comments

**Comment by justusual** [comment]
Hey, this usually happens when Instagram asks for phone verification. Just verify it throught your phone or desktop, and re-start the script.

**Comment by DJJPISAWESOME** [comment]
I'll try that thanks!

**Comment by DJJPISAWESOME** [comment]
I did verify it with a number still crashing =/

**Comment by Plushkin** [comment]
I have the same errors ((

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
