### ISSUE TITLE
Bot won't unfollow the people i follow with the bot

### ISSUE THREAD

**Issue by Flamealchamist** [instabot-py/instabot.py#586]
Hello, So I want to make it so the bot will unfollow everyone that it follows. I have the bot unfollow timeout settings for 12 hours so it will begin unfollowing after 12 hours, but it only unfollows select people. It is on moDe 0 atm so, I Don't know if that is an issue.

**Comment by TehJokeR** [comment]
If you have the bot set to unfollow after 12 hours, it will unfollow each user 12 hours after it has followed them, so the unfollow script will always be 12 hours behind the following.

i.e 
Bot follows user1 at 1pm in the evening, it will unfollow user1 at 1am the next morning
Bot follows user2 at 5pm in the evening, it will unfollow user2 at 5am the next morning

You need to be following the user for atleast the minimum time set in the unfollow timeout before it will unfollow them. Even if it is already unfollowing other users.

**Comment by Flamealchamist** [comment]
@TehJokeR Yes, after 12 hours most are unfollowed but for some reason, some are not being unfollowed.

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
