### ISSUE TITLE
New Feature to create [ autopause]

### ISSUE THREAD

**Issue by focamonca** [instabot-py/instabot.py#588]
Hi guys, 
I was wondering if is it possible to implement some random pauses during the activity to make it run 24/7.
I try to explain better, I run a raspberry pi full time but sometimes the insagram algorithm detects something is going strange and asks the phone verification or similar.. It woud be great if the user can choose something like: " pause 30 m every 2h".

BTW this project is awesome!

**Comment by TehJokeR** [comment]
Update instabot.py file with the following:

What this will do:
    When we start the script, assign a time 1-2 hours away as the time we stop doing work
    Every iteration of the script, check if we've passed the timout mark
    If we have, timeout for a random amount of time between 30mins to 45mins
    Assign a new time to stop working 1-2 hours away
    Continue iterating through the script

    ```
def new_auto_mod(self):
        # timeout at some point between 1-2hrs away
        timeout_pause_timer = time.time() + random.randint(3600, 7200)
        while True:
            # ------------------- Get media_id -------------------
            if len(self.media_by_tag) == 0:
                self.get_media_id_by_tag(random.choice(self.tag_list))
                self.this_tag_like_count = 0
                self.max_tag_like_count = random.randint(
                    1, self.max_like_for_one_tag)
            # ------------------- Like -------------------
            self.new_auto_mod_like()
            # ------------------- Follow -------------------
            self.new_auto_mod_follow()
            # ------------------- Unfollow -------------------
            self.new_auto_mod_unfollow()
            # ------------------- Comment -------------------
            self.new_auto_mod_comments()
            # Bot iteration in 1 sec
            time.sleep(3)
            # print("Tic!")
            
            # Check to see if we timeout or not
            timeout_pause_timer = self.timeout(timeout_pause_timer)

    def timeout(self, pause_time):
        current_time = time.time()
        if current_time >= pause_time:
            # 30 mins -> 45 mins
            time.sleep(random.randint(1800, 2700))
            # 1 hour to 2 hours until next pause
            pause_time = time.time() + random.randint(3600, 7200)
        return pause_time
```

**Comment by dieselp** [comment]
Hmmm...

Traceback (most recent call last):
  File "/Users/Marcin/Dropbox/Instabot/noimageyet.py", line 12, in <module>
    from instabot import InstaBot
  File "/Users/Marcin/Dropbox/Instabot/src/instabot.py", line 1021
    timeout_pause_timer = time.time() + random.randint(3600, 7200)
                      ^
IndentationError: expected an indented block

:(

**Comment by focamonca** [comment]
i'd like to implement it in mode 2

**Comment by TehJokeR** [comment]
dieselp you need to indent the code 4 lines and make sure its directly in line with time.sleep(3) -- I'll update the code above

**Comment by TehJokeR** [comment]
focamonca, it will work the same for mode 2. It uses the same entry point ( new_auto_mod method )

**Comment by dieselp** [comment]
@TehJokeR Thanks for your time... Sorry but I still have an issue :/ 
  File "/Users/Marcin/Dropbox/Instabot/src/instabot.py", line 552
    while True:
              ^
TabError: inconsistent use of tabs and spaces in indentation

![zrzut ekranu 2017-06-07 16 06 41](https://user-images.githubusercontent.com/27488451/26882814-bdd54fa2-4b9b-11e7-957f-b921704fe655.png)

**Comment by focamonca** [comment]
maybe I'm doing something wrong but it crashes the CMD

**Comment by TehJokeR** [comment]
@dieselp if you added in spaces, change them to tabs - or vica versa.

> inconsistent use of tabs and spaces in indentation

this means some of the blank space is spaces and some of it is tabs.

**Comment by TehJokeR** [comment]
@focamonca can you post the error?

**Comment by dieselp** [comment]
@TehJokeR thank you so much - I didn't knew that it can be a problem... now it works fine :)

I have one more question - is it possible to print "time.sleep(random.randint(1800, 2700))" in logs/terminal?

**Comment by focamonca** [comment]
@TehJokeR  no errors, only crashes!

**Comment by TehJokeR** [comment]
@dieselp  see updated code

**Comment by TehJokeR** [comment]
@focamonca it seems dieselps is working fine ( mine too )... your issue might not be related to the update?

**Comment by prestonjohnlewis** [comment]
Mr. Preston Lewis liked your email
Spark by Readdle

**Comment by focamonca** [comment]
Can anyone post the complete working .py?

**Comment by ChipWolf** [comment]
Just throw it in a bash wrapper, something like this.
```shell
#!/bin/bash
while true; do
  python example.py &
  pid=$!
  sleep 3000
  kill $pid
  sleep 3000
done
```

That would run for 5 hours, stop, sleep for 5 hours and repeat.

**Comment by inhaletime** [comment]
Having a issue, copied the supplied code and added it to the end of the instabot.py file. 

> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "/Users/jcastrofl/Desktop/instabot.py-master/src/instabot.py", line 299, in cleanup
>     exit(0)
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_sitebuiltins.py", line 26, in __call__
>     raise SystemExit(code)
> SystemExit: 0
