### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by sabrinaxo** [instabot-py/instabot.py#591]
Hello!

I downloaded python and I'm trying to install the project's dependencies but i keep getting the message

-bash: cd: pip: No such file or directory

what am i doing wrong??

**Comment by polaroi8d** [comment]
First, what re u doing?

**Comment by sabrinaxo** [comment]
step 2 of how to instal and run -->
2. To install the project's dependencies, run command pip install -r requirements.txt (specify pip2 or pip3 if you have multiple versions of Python installed)

**Comment by tunidev** [comment]
`sudo easy_install pip`
