### ISSUE TITLE
adding emojis to comments

### ISSUE THREAD

**Issue by sabrinaxo** [instabot-py/instabot.py#592]
for the comment feature, is it possible to add emojis to the list?

i found this (https://pypi.python.org/pypi/emoji) but im not sure how to add it into the script

**Comment by polaroi8d** [comment]
Hey, there is an example how to add:

>> import emoji
>> print(emoji.emojize('Python is :thumbs_up_sign:'))
Python is 👍
>> print(emoji.emojize('Python is :thumbsup:', use_aliases=True))
Python is 👍

**Comment by sabrinaxo** [comment]
one i install the emoji's then I just place that code in the brackets ?

   comment_list=[],

**Comment by Leo7654** [comment]
I am doing copy and paste. 
❤

**Comment by polaroi8d** [comment]
yes

**Comment by sabrinaxo** [comment]
the emoji isn't pasting for me.....

i have the script written in python IDLE

**Comment by sabrinaxo** [comment]
and when i tried pasting evething excluding the emoji's I get this

SyntaxError: invalid syntax

**Comment by ChipWolf** [comment]
you don't need to install or import anything, Python supports unicode out of the box
Just copy and paste the emoji into the comments array

**Comment by MrMontague** [comment]
ChipWolf, again with your bullshit..smh
