### ISSUE TITLE
Running more than one .py file at the same time

### ISSUE THREAD

**Issue by igzrap** [instabot-py/instabot.py#600]
Hey everyone, 

How can I run more than one .py file at the same time, if I try and run one after another one is already running it just stops that one and starts the new one. 

Thanks in advance

**Comment by TBob23** [comment]
Where are you running your bot?

**Comment by ekremgurdal** [comment]
Are you using windows or linux?

**Comment by TehJokeR** [comment]
Open up 2 different cmd prompts or 2 terminal sessions and run them in seperate shells
