### ISSUE TITLE
instagram has changed its backend

### ISSUE THREAD

**Issue by compudida** [instabot-py/instabot.py#604]
nothing is working the way it should.

**Comment by crashwins** [comment]
I'd say you're right based on all the issues here...mine is no longer doing the trick

**Comment by mmixx** [comment]
The one that is broken is this URL:
```
url_media_detail = 'https://www.instagram.com/p/%s/?__a=1'
```

**Comment by artemdumanov** [comment]
Who wants to help me, to fix it?

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
