### ISSUE TITLE
KeyError: 'owner'

### ISSUE THREAD

**Issue by enrico-57** [instabot-py/instabot.py#607]
Hi, I keep getting this error and I don't know how I can fix or what is causing the issue. 
Any help would be greatly appreciated.
Thanks in advance.

Instabot v1.1.0 started at 21.06.2017 11:44:

Trying to login as 360mounts...

360mounts login success!
Get media id by tag: filmmaker
Trying to like media: 1542009288057364157
Liked: 1542009288057364157. Like #1.
Trying to follow: 4915674937
Followed: 4915674937 #1.
Trying to comment: 1542009015453552805
Write: "This photo feels so glorious!!". #1.
Trying to unfollow #1:
360mounts : Get media id on recent feed
Media in recent feed = 25
360mounts : Get user info
21.06.2017 11:45
Checking user info..
Follower : 333
Following : 266
Media : 1106
   >>>This is a normal account
   >>>This user is active
   >>>This account is NOT following you
   >>>You are following this account
strawberrygirlbananasplitlady2
Unfollow: 4915674937 #1.
Trying to like media: 1542009015453552805
Liked: 1542009015453552805. Like #2.
Trying to follow: 5465614856
Followed: 5465614856 #2.
Trying to comment: 1542008738217854419
Write: "This snapshot is great!". #2.
Trying to unfollow #2:
360mounts : Get media id on recent feed
Media in recent feed = 5
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\InstaBot Master\360mounts.py", line 80, in <module>
    bot.new_auto_mod()
  File "C:\Users\Admin\Desktop\InstaBot Master\src\instabot.py", line 580, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "C:\Users\Admin\Desktop\InstaBot Master\src\instabot.py", line 627, in new_auto_mod_unfollow
    self.auto_unfollow()
  File "C:\Users\Admin\Desktop\InstaBot Master\src\instabot.py", line 686, in auto_unfollow
    current_id = self.media_on_feed[chooser]['node']["owner"]["id"]
KeyError: 'owner'
Trying to unfollow: 5465614856
Unfollow: 5465614856 #2 of 2.
Pausing for 17 seconds... 2 of 2
Logout: likes - 2, follow - 2, unfollow - 2, comments - 2.
Bot work time: 0:06:32.840000
Logout success!
Exception KeyError: KeyError(5620,) in <module 'threading' from 'C:\Python27\lib\threading.pyc'> ignored

**Comment by TehJokeR** [comment]
Are you sure you have the latest source code? Make sure to pull the latest code from the master branch -- You might want to keep a copy of your example.py file because you may lose it and have to re-create it

**Comment by enrico57** [comment]
Hi, thanks for response. If I download this automatically give latest code ?

**Comment by TehJokeR** [comment]
It should give you the latest at the time you downloaded it. You'll need to do 'git pull' to get the latest code with updates that have been pushed since you first cloned it

**Comment by artemdumanov** [comment]
Is problem still exist?

**Comment by ChipWolf** [comment]
@TehJokeR I'd still recommend recreating it, we sometimes change example.py
