### ISSUE TITLE
MODE 5 issue, no burst

### ISSUE THREAD

**Issue by Pheela1** [instabot-py/instabot.py#611]
Hello Guys,

There is a description that mode 5 is burst mode for unfollows, so i would expect burst of unfollows to happen once you chose it, however, it seems like it is working normally, as standard mode where it follows and unfollows in interval chosen by you.

To be honest i am a beginner so there might be a mistake in myself. 

I am using this: 

elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)
                
    else:
        print("MODE = 5")

Where is the problem?

Thanks!

**Comment by TehJokeR** [comment]
If you set the value of unfollows really high ( 10k ) it should only have an 8 second cool down between each unfollow.

Do not leave this script running for more than 2-3 minutes if you set the value this high though as you WILL GET BANNED!

**Comment by Pheela1** [comment]
Thanks for reply, however i think there is a different problem, i dont think that MODE 5 is different from any of the modes, even if I set unfollows for 10K as suggested, it seems like there is no change at all. I am not sure what i am doing wrong, but there is simply no change at all between mode 5 and mode 1

**Comment by Pheela1** [comment]
right i have solve the issue for not working mode 5, it is working now, however i still dont see the burst.

Even if i set unfollow limit to 10000, there is no burst as i would expect to be, for now its doing like 3 unfollows in a minute, can someone suggest to which value should i set the timers?
Thank you

**Comment by Pheela1** [comment]
Resolved - i had to change unfollow protocol itself

if self.bot_mode == 2:
                new_auto_mod_unfollow2(self)
                time.sleep(0)

now that is the burst i wanted!
