### ISSUE TITLE
Syntax error in instabot.py (line 381)?

### ISSUE THREAD

**Issue by ssyberg** [instabot-py/instabot.py#612]
This is on Red Hat 4.4.7-16... only strange thing about my setup is I have the requests module installed with the --user flag (though "import requests" isn't throwing any errors)

Looked at that line and looks fine to me so I have no idea... Same script appears to be working on OS X.
```
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    from instabot import InstaBot
  File "./instabot.py/src/instabot.py", line 381
    for tag in caption.split()
      ^
SyntaxError: invalid syntax
```

**Comment by ekremgurdal** [comment]
Should be like this: "for tag in caption.split():"

**Comment by ssyberg** [comment]
Unfortunately that doesn't seem to affect anything:

```
  File "./instabot.py/src/instabot.py", line 381
    for tag in caption.split():
      ^
SyntaxError: invalid syntax
````

**Comment by TehJokeR** [comment]
You need to download a later version of Python, I think the recommended python version is 2.7+

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
