### ISSUE TITLE
Script not working when run with nohup

### ISSUE THREAD

**Issue by gvdh** [instabot-py/instabot.py#614]
Hi guys,

I've been searching for a few hours on this one but i can't find any solutions.
I cloned instabot.py on my VPS, installed python and now the script works fine when i launch it from my server. My problem is that I want to launch it with "nohup", so my script keeps working when i close my pc. Strangely, the script doesn't work with nohup.

Everytime i run it with
"nohup python ./example.py & tail -f nohup.out"

I get the following error : 

```
self.logout()
  File "/root/instabot.py/src/instabot.py", line 287, in logout
    self.write_log(log_string)
  File "/root/instabot.py/src/instabot.py", line 823, in write_log
    print(log_text)
KeyboardInterrupt
Logout: likes - 0, follow - 1, unfollow - 1, comments - 1.
Bot work time: 0:01:15.699452
Logout success!
Exception KeyError: KeyError(140349855794944,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
nohup: ignoring input and appending output to 'nohup.out'
```

Any ideas on this ?

**Comment by TehJokeR** [comment]
Use a screen session

[root@server] screen -S instabot
[root@server] python example.py

You can then re-attach your screen later on using screen -x instabot when you reconnect to the server

**Comment by HenryCooperGithub** [comment]
As mentioned , use screen . Closed .
