### ISSUE TITLE
No JSON object could be decoded while using bot and solution error

### ISSUE THREAD

**Issue by vinceze** [instabot-py/instabot.py#615]
Hi everyone, 

When I run comments and follows on Instant I randomly get the error bellow (screenshot) after a couple of hours:

![00aa2d3e-1195-11e7-807e-6427b1291295](https://user-images.githubusercontent.com/7132567/27512086-f582f90c-5935-11e7-8206-481682fba096.JPG)

I used the solution provided in thread #438  but I get another error when I update the code.

`root@ns1:~/instabot.py/src# python example.py
Traceback (most recent call last):
File "example.py", line 12, in 
from instabot import InstaBot
File "/root/instabot.py/src/instabot.py", line 664
url_check = self.url_media_detail % (media_code)
^
IndentationError: expected an indented block`

Thank you!

Vincent

**Comment by tunidev** [comment]
Did you check my [comment ](https://github.com/instabot-py/instabot.py/issues/598#issuecomment-309445569)

**Comment by vinceze** [comment]
Thank you but it didn't solve it for me. I found a temporary solution. I don't get any errors when I increase the number of hashtags from 3 to 10!

**Comment by TehJokeR** [comment]
You need to ensure the indentation is correct otherwise Python will throw the error you've seen:
`IndentationError: expected an indented block`

```
if IndentationError:
    print 'you need to indent 4 spaces to write code here'

    for line in code:
        print '8 spaces indentation for this one'
   else:
        print 'another 8 spaces indentation here too'
else:
   print 'No indentation error - still need 4 spaces here'
```

**Comment by vinceze** [comment]
@TehJokeR Thank you for your reply. Can you please further explain? I'm a noob here

**Comment by TehJokeR** [comment]
Notice how the 2nd and 4th line have 4 spaces before the code starts. Line number 5 has 8 spaces. You need to indent the code... paste your snippet of code here and then highlight it and click the 'code' button in the reply box and I can help fix it

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
