### ISSUE TITLE
Mode 0 to 5

### ISSUE THREAD

**Issue by limerick11** [instabot-py/instabot.py#617]
Can someone provide clarity between the modes? I don't see any documentation on how to use it. Thanks!

#print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
#print("## MODE 1 = MODIFIED MODE BY KEMONG")
#print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
#print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
#print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
#print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

**Comment by luisramirez-m** [comment]
Maybe this help: https://github.com/instabot-py/instabot.py/issues/234#issuecomment-254159457

But don't forget, most of the modes have bugs (Mode 1 to 5).⁠⁠⁠⁠

**Comment by limerick11** [comment]
Thanks!
