### ISSUE TITLE
Whitelist?

### ISSUE THREAD

**Issue by newme616** [instabot-py/instabot.py#618]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**
Is it possible to include a .txt file of users who should be whitelisted?

**Comment by TehJokeR** [comment]
There's a list you can append for whitelisting users. There's no functionality for reading it from a file

**Comment by uuaing** [comment]
Here is the solution.
https://github.com/uuaing/instabot.py/commit/91b6e8335cdbffb2ebd646021539e1a57c7faa4e

**Comment by newme616** [comment]
great thx mate!
