### ISSUE TITLE
From instabot import Instabot

### ISSUE THREAD

**Issue by Bigemm** [instabot-py/instabot.py#619]
I've installed the dependencies (pip install -r requirements) but still receive the same error: Cannot import instabot from Instabot - 

Traceback (most recent call last):
  File "example.py", line 12, in <module>
    from instabot import InstaBot
ImportError: cannot import name 'InstaBot'

is there an issue with the module?

**Comment by TehJokeR** [comment]
Your directory structure should look like this and make sure your current working directory is instabot.py before you try to run the example.py file. i.e

`[root@server instabot.py]# python example.py`

instabot.py
|__ example.py
|__ src
     |___insatbot.py
     |___userinfo.py
|__ .gitignore
|__ LICENSE
- README.md

**Comment by Bigemm** [comment]
how can I find the current working directory?

import os
cwd = os.getcwd()

into the script when i run will that work? 

or running those lines in a separate shell all together.

Additionally if the dir is not instabot.py, how do I change it?

**Comment by TehJokeR** [comment]
```
Are you on a Linux machine? 

ekava123la@IE00200553 ~/workspace/alan/instabot.py (master)
$ pwd
/c/Users/ekava123la/workspace/alan/instabot.py

ekava123la@IE00200553 ~/workspace/alan/instabot.py (master)
$ ls
ISSUE_TEMPLATE.md  LICENSE  README.md  example.py  instabot.py.iml  requirements.txt  src
```

**Comment by Bigemm** [comment]
No i am on Windows OS, but i'm sure the same applied right? use the same commands in Git bash console for desktop? Or is there the alternative commands for python/anaconda command line?

**Comment by Bigemm** [comment]
@TehJokeR 
Here we go, wonder if you could me in identifying what it means?  
![help](https://user-images.githubusercontent.com/28912732/27670556-52dea622-5cc0-11e7-91f8-9ca4b9b6c34f.jpg)

**Comment by Bigemm** [comment]
oh i see, so line will be:

import instabot from instabot.py-master ? or just change the name of the file to instabot?

**Comment by davidmantegna** [comment]
Just run `pip install -r requirements.txt`

**Comment by vhoch** [comment]
If you still have this issue, inside example delete line 7 which is `sys.path.append(os.path.join(sys.path[0], 'src'))` and put example.py inside src folder. It should work now

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
