### ISSUE TITLE
mode 0 not unfollowing

### ISSUE THREAD

**Issue by Pheela1** [instabot-py/instabot.py#620]
Hi Guys,

for some reason the default mode 0 is not unfollowing anyone at all.

Have someone experienced this as well? Unfollow works in other modes.

I have not made any changes in default mode 0 settings.

Even if i set follow_time=1 * 60, → it still doesnt unfollow after 1 minute.

Default new_unfollow shared below:

New_unfollow.py

#!/usr/bin/env python
# -*- coding: utf-8 -*-

def new_unfollow(self, user_id, user_name):
    """ Send http request to unfollow """
    url_unfollow = self.url_unfollow % (user_id)
    try:
        unfollow = self.s.post(url_unfollow)
        if unfollow.status_code == 200:
            self.unfollow_counter += 1
            log_string = "Unfollow: %s #%i." % (user_name,
                                                self.unfollow_counter)
            self.write_log(log_string)
        return unfollow
    except:
        self.write_log("Exept on unfollow!")
        return False

**Comment by TehJokeR** [comment]
Mode 0 uses the method self.new_auto_mod_unfollow()

```
def new_auto_mod_unfollow(self):
        if time.time() > self.next_iteration["Unfollow"] and \
                        self.unfollow_per_day != 0 and len(self.bot_follow_list) > 0:
            if self.bot_mode == 0:
                for f in self.bot_follow_list:
                    if time.time() > (f[1] + self.follow_time):
                        log_string = "Trying to unfollow #%i: " % (
                            self.unfollow_counter + 1)
                        self.write_log(log_string)
                        self.auto_unfollow()
                        self.bot_follow_list.remove(f)
                        self.next_iteration["Unfollow"] = time.time() + \
                                                          self.add_time(self.unfollow_delay)
            if self.bot_mode == 1:
                unfollow_protocol(self)
```

**Comment by Pheela1** [comment]
I left the bot running overnight in MODE 0 without any change, and during the morning i have found that it is unfollowing users.

So I guess it was just my time delay setting.
