### ISSUE TITLE
Help me Fast please on this

### ISSUE THREAD

**Issue by AyoubEd** [instabot-py/instabot.py#623]
File "example.py", line 12, in <module>
    from instabot import InstaBot
  File "C:\Users\Ayoub Ed\Downloads\instabot.py-master\src\instabot.py", line 16, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by Bigemm** [comment]
you need to run installation of requests.

pip install -r requests.txt 

do this from the correct directory though.

Further instructions are found in the README

**Comment by AyoubEd** [comment]
Thanks a lot @Bigemm ,
will see if it solves my problem
