### ISSUE TITLE
Question: Bot stops for a long time after few subsequent 400's on likes

### ISSUE THREAD

**Issue by stephenhyde** [instabot-py/instabot.py#624]
This may be by design but I find if the bot gets 3-4 400's when trying to like a photo it doesn't try to like a photo for a very long time if ever. Was this by design, some type of cooldown period if a few 400's happen in a row?

**Comment by stephenhyde** [comment]
If this is not by design, I presume there some kind of verbose logging I can add to see where the halt is.

**Comment by uuaing** [comment]
What's your value set for like_per_day?

**Comment by Bigemm** [comment]
3 to 4 errors means you may have received an IP ban from instagram. It was discovered a few weeks ago (on github) or at least speculated that instagram may have changed their backend to prevent bot functionality. The consensus so far has been to use private proxy for your accounts and not run bot via pythonanywhere dot com

**Comment by stephenhyde** [comment]
@Bigemm Ya I run different private proxies on all my instances, you are right about the softban but I was hoping the software would retry after a while, but it becomes stuck. I was curious if this was by design. @uuaing it ranges between 500-1000.

**Comment by stephenhyde** [comment]
I just read through code and it seems if it > 3 400's in row, you get a 2 hour sleep, so that answers that, ill close this
