### ISSUE TITLE
Batch unfollow using unfollow_whitelist

### ISSUE THREAD

**Issue by randyklein** [instabot-py/instabot.py#625]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**
I had to close the bot & now my account has about 1500 followers that I want to unfollow.  However, there are about 200 followers that I was to keep following.  Is there a way to have the bot unfollow the 1300 followers I don't want and keep the others.  It looks like mode 5 is made to batch unfollow, but it ignores the unfollow_whitelist and unfollows everyone.  Thanks!

**Comment by Bigemm** [comment]
Why not use the regular mode so the bot acknowledges your whitelist and unfollows the rest? In other words, put the people you don't wanna unfollow all in whitelist, run normal and unfollow? May take longer but at least it'll get done no?

**Comment by randyklein** [comment]
@Bigemm, thanks.  I tried that, but it didn't seem like it was unfollowing the rest of the users.  Perhaps I didn't give it long enough.  I'll give it another go

**Comment by randyklein** [comment]
@Bigemm, it looks like I was originally right.  That doesnt work.  If I set the script to follow 1 per day, like 1 per day, and unfollow 800, it just follows 1, likes 1, unfollows 1, and stops.  It's unfollowing 1 immediately because I tried setting follow_time to a low number

**Comment by kiaanpillay** [comment]
Same problem, my unfollow doesn't match what I set it to

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
