### ISSUE TITLE
Unfollow after restart

### ISSUE THREAD

**Issue by limerick11** [instabot-py/instabot.py#628]
Hi,
It seems that after a restart, it forget the list of previous followers and does not unfollow them. It act like it's starting from new and just adds more followers and waits till the follow time to start unfollowing. 
Can I confirm if this really happens? Is there a way to manually unfollow the followed users?

Thanks!

**Comment by uuaing** [comment]
That's current designed. If you want to keep you following data after restart, you may need my PR:
https://github.com/instabot-py/instabot.py/pull/621

**Comment by limerick11** [comment]
I'll try it out. Thanks!
