### ISSUE TITLE
"Not liked"

### ISSUE THREAD

**Issue by wsdt** [instabot-py/instabot.py#629]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**
![image](https://user-images.githubusercontent.com/28724551/27772846-9d2a52e2-5f6a-11e7-811f-4292d6e7bdca.png)

For several weeks from now on the bot does not like any media anymore. My account is not private, it worked before without changing anything and I can like with my account without a problem.

**Comment by Bigemm** [comment]
It's because you're on pythonanywhere dot com - don't use this site as it has resulted in multiple softbans on accounts. Use python 3 on your pc + a private proxy, see if that helps.

**Comment by Pierofgonzalez** [comment]
Is there any other site instead of pythonanywhere dot com, to run the script?
or any cloud have the same problem?
