### ISSUE TITLE
Instabot variables

### ISSUE THREAD

**Issue by Purp1ePie** [instabot-py/instabot.py#633]
My settings are: 

likes: 700
Follow/Unfollow: 250 
Follow time: 4 hours 

The issue is that my followings are growing every day. 

Are my settings ok? Do I risk to get banned?

**Comment by uuaing** [comment]
It's the designed. If you set follow=250, it'll make following every 24*60*60/250 seconds until you shutdown the application.
No worry, 250 per day is safe enough.
