### ISSUE TITLE
Traceback none type get itwm

### ISSUE THREAD

**Issue by velanpro** [instabot-py/instabot.py#635]
First off thanks for the program. It was a great idea. Now I need help making it run stable. I keep getting this error when I run in mode 1 and 4. 

Traceback (most recent call last):
  File "/home/velanzpro/INSTABOT/example3.py", line 92, in <module>
    feed_scanner(bot)
  File "/home/velanzpro/INSTABOT/src/feed_scanner.py", line 37, in feed_scanner
    self.current_id = self.media_on_feed[chooser]["node"]["owner"][
TypeError: 'NoneType' object has no attribute '__getitem__'

Any help will be greatly appreciated.

**Comment by TehJokeR** [comment]
You'll need to add more information if you want a proper response.

Basically python is complaining that your empty object doesnt contain the method 'getitem'.
**`TypeError: 'NoneType' object has no attribute 'getitem'`**

Either your configurations are not correct, you're not searching for popular tags, there's no media on your feed or else you dont have the right version of python installed

**Comment by velanpro** [comment]
Thanks for the response. I'm running from python anywhere using version 2.7. could that be the problem? Also how can I check my configuration, or is their a master I can compare it too? Thanks again.

**Comment by TehJokeR** [comment]
The example.py file has a baseline configuration you can modify. Then run the bot with
`python example.py`

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
