### ISSUE TITLE
Accidentally clicked "this wasn't me" on the bot and now can't access it 

### ISSUE THREAD

**Issue by hajjboy95** [instabot-py/instabot.py#636]
I'm using an iPhone and clicked 'this wasn't me' on the instagram app by accident when I was told by the app that my account has been accessed through a server in Miami as that's were I host the bot .

The problem is I don't see the prompt anymore and every time I run the bot it tells me that it's unable to log in  because I accidentally pressed this wasn't me when I was asked . 

Is there anyway I can trigger the prompt again on the instagram app when I try logging in from the bot from
The same Server ? 

I'm guessing the bot has a unique Id in the headers that instagram blacklisted but I'm only guessing .

Any help would be incredibly appreciated 😃

**Comment by samuelhopkins** [comment]
Having same issue even after clicking it was me

**Comment by wbaxterh** [comment]
Just change proxies... use a site like https://www.us-proxy.org/ and then enter the proxy ip:port like this proxy = '104.207.145.113:3128'

**Comment by hajjboy95** [comment]
@wbaxterh This doesn't work for me - When I run the example.py folder with the proxy added in the proxy field with the format ip:port the app crashes and doesnt run .

Can you attach your working example.py file so I can test it out on my account ?

Thanks 👍

**Comment by ChipWolf** [comment]
Change your password.

**Comment by hajjboy95** [comment]
@ChipWolf tried that but no luck unfortunately - is there a way I can change my session id or something , because it seems that instagram has blocked my bot id

**Comment by ChipWolf** [comment]
uhm, it must be the ip address the bot is using; the bot just logs in when you start it like you would via a mobile device or the website, there's no 'bot id'

**Comment by hajjboy95** [comment]
@ChipWolf Ye I changed the ip address and the bot was still blocked from accessing the account .
very strange - to test for yourself set up a bot on an account and tap this wasn't me when the instagram app prompts you to verify if you tried accessing your account . Once this wasn't me was tapped you can no longer access that account .
