### ISSUE TITLE
Instabot auto closes when start

### ISSUE THREAD

**Issue by emocol** [instabot-py/instabot.py#640]
Installed python and everything. (yes including path environmental variables) But when i open example.py it flashes a cmd window and disappears.

Help?

**Comment by nikiteezy** [comment]
Use tags only in English language

**Comment by emocol** [comment]
thats not the issue. i didnt edit tags in example.py at all. i only edited user and pw. still close immediately when i double click it

**Comment by emocol** [comment]
nvm solve it myself ty

**Comment by Ekryemadhi** [comment]
Same problem here how did you fixed it

**Comment by emocol** [comment]
Do path environmental variables for both python and pip

**Comment by Ekryemadhi** [comment]
Ok thanks
