### ISSUE TITLE
Comments work fine, but suddenly they stop with error!

### ISSUE THREAD

**Issue by krazan** [instabot-py/instabot.py#641]
![py](https://user-images.githubusercontent.com/29817429/27996429-689a396c-64ff-11e7-9dbc-9cd2a0118570.png)

^ screenshot

I thought running this script overnight would be a relief. But suddenly out of nowhere, I get this error.

Why did the script stop abruptly? What changed do I need to make and in which file?

PS: I am not a Python dev, but suggestions from coders would be much appreciated.

Thank you.

**Comment by TehJokeR** [comment]
If you want to run it overnight, disable the commenting functionality.

comments_per_day = 0

There's an issue with the commenting which needs to be fixed. Perhaps this is for comments with pure emojis or something like that, it seems to be throwing the error. It needs investigation.

Your best bet is to disable commenting

**Comment by krazan** [comment]
If I do that, there wont be any comment @TehJokeR 

I did that anyway and after 1 hour this happens:

![image](https://user-images.githubusercontent.com/29817429/28135584-659cab66-6764-11e7-8a93-0d2e0a95cd9d.png)

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
