### ISSUE TITLE
Login error! Check your login data!

### ISSUE THREAD

**Issue by davidmantegna** [instabot-py/instabot.py#643]
Getting this error when trying to launch example.py with my credentials from terminal.
Is there any issue with new security policies from Instagram blocking Bots access?

**Comment by TehJokeR** [comment]
You need to authenticate the bot using your mobile phone.
If you run the script and it fails to log in, start using your mobile phone / web browser to do some thing on instagram and it should prompt you to grant access.

This may take a couple of attempts but eventually after granting the access the bot will connect

**Comment by davidmantegna** [comment]
I didn't find any "it was me" section inside Instagram settings. Neither in the browser nor in the mobile app.

**Comment by TehJokeR** [comment]
Try log in with the bot and then use your phone/website at the same time. It usually pops up instantly after the bot attempts to connect

**Comment by PalieSE** [comment]
Same issue here.
I've tried to get the "it was me" message to pop up on Instagram's app for Android and Instagram for iOS and I tried it on my desktop using Chrome and Safari. No luck.

**Comment by PalieSE** [comment]
The error I recieve is `Login error! Check your login data!`
Tested with Python 2.7.9 and Python 3.4.2.

**Comment by dcanones** [comment]
This error means that actually you are introducing a wrong login data. Check your user and password, does not use '@' in the username.

**Comment by davidmantegna** [comment]
I made various attempts submitting my credentials, but it keeps not working.

**Comment by Voidshot** [comment]
The login information (user, pass) is correct. I keep getting this error and the "it was me" message does not appear in the app or in the browser :/

**Comment by dcanones** [comment]
` 
def login(self):
        log_string = 'Trying to login as %s...\n' % (self.user_login)
        self.write_log(log_string)
        self.s.cookies.update({
            'sessionid': '',
            'mid': '',
            'ig_pr': '1',
            'ig_vw': '1920',
            'csrftoken': '',
            's_network': '',
            'ds_user_id': ''
        })
        self.login_post = {
            'username': self.user_login,
            'password': self.user_password
        }
        self.s.headers.update({
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': self.accept_language,
            'Connection': 'keep-alive',
            'Content-Length': '0',
            'Host': 'www.instagram.com',
            'Origin': 'https://www.instagram.com',
            'Referer': 'https://www.instagram.com/',
            'User-Agent': self.user_agent,
            'X-Instagram-AJAX': '1',
            'X-Requested-With': 'XMLHttpRequest'
        })
        r = self.s.get(self.url)
        self.s.headers.update({'X-CSRFToken': r.cookies['csrftoken']})
        time.sleep(5 * random.random())
        login = self.s.post(
            self.url_login, data=self.login_post, allow_redirects=True)
        self.s.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
        self.csrftoken = login.cookies['csrftoken']
        time.sleep(5 * random.random())

        if login.status_code == 200:
            r = self.s.get('https://www.instagram.com/')
            finder = r.text.find(self.user_login)
            if finder != -1:
                ui = UserInfo()
                self.user_id = ui.get_user_id_by_login(self.user_login)
                self.login_status = True
                log_string = '%s login success!' % (self.user_login)
                self.write_log(log_string)
            else:
                self.login_status = False
                self.write_log('Login error! Check your login data!')
        else:
            self.write_log('Login error! Connection error!')
`
Going a bit deeper into the login method of Instabot class, you can see that there are two possibilities:

1. You get a 200 (OK) response from Instagram, but you are not logged == 'Login error! Check your login data!'. It means that there is a credentials error.

2. You get a 'different from 200' response from Instagram, so the message == 'Login error! Connection error!'. If I am not mistaken, in this case, if it is your first time login from a location outside your home country (for example using a proxy o a server located abroad) you get the Instagram popup in you mobile app.

Can you check which case are you stuck in? Can debug (or print) login.status_code and see what's happening?

**Comment by dehvCurtis** [comment]
for all those having 'login issues'. Be sure you can still login outside of this. I haven't looked through this code, but I had the same issue. Couldn't login by myself either. Hurry and reset my password. It seems someone had my password. Not saying it's this script, but this is the only other place aside from insta I used credentials. This script is suspect.

**Comment by davidmantegna** [comment]
@dcanones How can I verify the status code of the AJAX request?

@dehvCurtis I often login with my credentials on the mobile app and I'm not having any issue.
If you have suspects, I think you should check the code and try to find suspicious portions inside it to signal any abuse.

**Comment by dcanones** [comment]
@dehvCurtis I am using my own forked version of this code and have gone through most of it. It is clean. But I agree with you, before trying to log in, check your credentials in the Instagram app and be sure that these are the correct ones. If you can't login with instabot and also can't login outside it, almost sure you forgot your pass.

@davidmantegna The easiest way (in case you are not using a Python IDE with debug like Pycharm or any other) is printing the status code: introduce the line `print(login.status_code)`  if you are using Python 3 of `print login.status_code` in Python 2, just before the if statement which check the status code 200.

As I said before, after using this code for a long time:

- Error and 200 status code: Credentials error.
- Error and /= 200 status code (most common 403 I think): First time login error and 'It was me' popup.

**Comment by davidmantegna** [comment]
@dcanones It prints 200 status code, but the credentials are right.

**Comment by dcanones** [comment]
@davidmantegna mmm I am out of ideas... If you are 100% sure your credentials are right and the status code is also OK... do you have two step verification activated in you Instagram account (that code sent by sms to login)? (in that case be sure you set it disabled).

**Comment by davidmantegna** [comment]
@dcanones yep it is disabled, I've never enabled it. You're using this code and it's working?

**Comment by TehJokeR** [comment]
Have you tried using the bot against a different account? Can you create one just for testing purposes and see if it successfully logs in? Maybe your account is banned from that IP?

**Comment by davidmantegna** [comment]
@TehJokeR I've created a new account and now it's working! Thank you very much!!!
But I'm still interested in using it on my profile...should I use a proxy server?

**Comment by Voidshot** [comment]
I can confirm that the credentials are correct and I've never enabled 2FA.
No idea whats going on.

**Comment by Voidshot** [comment]
Changed the password to be alphanumeric only and it still doesnt work.
Just to be clear, login="" should be my email and not the user ID correct?

**Comment by dcanones** [comment]
@Voidshot I always log in user the Instagram user name (withouth the @) and not the mail, but I am not sure if mail would work.

**Comment by Voidshot** [comment]
@dcanones It works! It looks like it's not possible to login using the email.

**Comment by andreperkins12** [comment]
I have the same problem. This time I click "It Was Me" inside of Instagram and it still does not work. Should I wait a day and retry?

**Comment by ryank01** [comment]
is this code set up to handle 2FA for the user using the bot ? That is what if username and password are correct but bot is unable to connect because instagram sends a 2FA auth code to the user's phone which is needed to auth the login
