### ISSUE TITLE
Not liking

### ISSUE THREAD

**Issue by 9BadWolf9** [instabot-py/instabot.py#645]
Tried mode 0,1,4
The code
` like_per_day=600,
               comments_per_day=0,
               tag_list=['fashion', 'fashionblogger', 'beautyblogger', 'makeup', 'beauty', 'instafollow','bestoftheday'
                         ,'style','makeupjunkie','makeupartist','ootd'],
    tag_blacklist=[],
    user_blacklist={},
    media_max_like=200,
    media_min_like=50,
    max_like_for_one_tag=100,`

The log
Get media id by tag: makeupartist
Trying to follow: 1924901092
Followed: 1924901092 #1.
Get media id by tag: beautyblogger
Get media id by tag: fashionblogger
Get media id by tag: makeupartist
Get media id by tag: makeupartist
Get media id by tag: style
Get media id by tag: makeup
Get media id by tag: beautyblogger
Get media id by tag: makeup
Get media id by tag: instafollow
Get media id by tag: beautyblogger
Get media id by tag: makeup

It continues to get media id, it follows accounts every now and then but it never actually likes anything. Is something wrong with my settings?

**Comment by TehJokeR** [comment]
What mode are you using?

**Comment by 9BadWolf9** [comment]
Tried mode 0,1,4

**Comment by ChipWolf** [comment]
Use mode 0
