### ISSUE TITLE
Commenting

### ISSUE THREAD

**Issue by gj648183** [instabot-py/instabot.py#648]
If I set comments at more than 0, script will close in a few seconds. I know there were issues but has anyone got it to work to comment automatically without closing the bot? Willing to pay if someone can fix.

**Comment by ChipWolf** [comment]
You're willing to pay someone @gj648183?
Set up a bounty: https://www.bountysource.com/

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
