### ISSUE TITLE
How to run this on Digital Ocean

### ISSUE THREAD

**Issue by mubaris** [instabot-py/instabot.py#653]
I created a droplet on Digital Ocean to run this script. But it automatically closes after maximum of 3 hours. How do I make it run 24/7?

**Comment by ChipWolf** [comment]
uh, it's probably crashing for a reason
It doesn't matter who the hosting provider is, not sure why you told us that.

```
#!/bin/bash
while true; do
  python example.py
  sleep 60
done
```

if you really want to hack around it
