### ISSUE TITLE
Password keeps changing

### ISSUE THREAD

**Issue by mubaris** [instabot-py/instabot.py#654]
I ran this script for few days, and suddenly today when I tried to use my IG on phone, it says owner has changed the password. I thought someone hacked my account. I changed my password. Same thing happens in every 5 minutes. Then I stopped running the script in the remote server. I ran on my local machine, same thing happens. My password keeps changing and I am not able to use IG on my phone. Not sure what is causing it. And the script is not stopping automatically.

**Comment by TehJokeR** [comment]
Where are you running the code? 

The source is available for you to read if you think the code is dodgy. The only thing 'dodgy' about this code is the fact that your username and password are plaintext. This means when you attempt to log in, your password is probably being sent as plaintext - meaning if someone was watching your network traffic and sniffing your requests, they'd have them details in plaintext.

None of the devs would try to hack your account, they've been running this software for over 2 years and no doubt have more followers on their accounts than you have just starting out. Every change made to the code also needs to be approved by the team of developers.

The password changing is however suspicious. 

Are you running your code via PythonAnywhere or on your own virtual machine? I'd suggest if you are using PythonAnywhere, that instead you migrate to Amazon Web Services. I signed up to PythonAnywhere earlier today and received an email from a developer at PythonAnywhere, which is a bit suspicious. It means they are probably working closely with all of the users of the site. You wont get this at Amazon - which is probably better for you. They wont be watching what you're doing on your machine.

**Comment by ChipWolf** [comment]
You have all the values turned up way too high in example.py, you're being rate limited.
