### ISSUE TITLE
instant logout after successful login

### ISSUE THREAD

**Issue by sushanthvasista** [instabot-py/instabot.py#656]
im new to this and need your help? thanks!
![screenshot 111](https://user-images.githubusercontent.com/30346096/28464706-03033862-6e44-11e7-9746-cbc9aa2057ed.png)

**Comment by ChipWolf** [comment]
what's in your username blacklist?

**Comment by sushanthvasista** [comment]
I have left the username blacklist empty

**Comment by ChipWolf** [comment]
then add something.
