### ISSUE TITLE
Can't find the Syntax Error, please help.

### ISSUE THREAD

**Issue by cutegayboi** [instabot-py/instabot.py#657]
![bildschirmfoto 2017-07-22 um 16 39 42](https://user-images.githubusercontent.com/30372208/28492081-65c18fae-6efc-11e7-848d-737adc563f06.png)
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**

**Comment by ChipWolf** [comment]
You didn't give us much to work with.
Where's the rest of the file?

**Comment by TehJokeR** [comment]
Does your list contain a closing bracket? 
The line should read:
`unwanted_username_list=[]`

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
