### ISSUE TITLE
Login error while username and password are correct

### ISSUE THREAD

**Issue by bronzeboy** [instabot-py/instabot.py#659]
Title, got this error even if I can login with that account on instagram site.

**Comment by ChipWolf** [comment]
What's the error?

**Comment by TehJokeR** [comment]
Some common reasons why you fail to login:
- Your password is wrong
- You need to authenticate the bot
- Your internet connection isn't working
- Your IP address is banned ( this only happens after using the bot for some time )
- You're using a VM which has an IP address too far away from where you mobile is connected
- You're using a proxy server found from the first result of a google search and it has been banned from other users

Suggestions to fix it:
- Run the bot locally on your computer and see if it works

**Comment by dcanones** [comment]
@bronzeboy check you are login with your IG username and not with the email.

**Comment by bronzeboy** [comment]
Was a proxy problem, thanks everyone and sorry, my bad!
