### ISSUE TITLE
Question: Running from Raspberry PI or Server?

### ISSUE THREAD

**Issue by Alphavader** [instabot-py/instabot.py#662]
Hey,

iam currently looking for some info to run this awesome script from a PI or
better from a server. For the server thing i found some tutorials, but not quite what i need.

This is what i need. (server)
- access server via URL (login)
- Have something like a "terminal" opnend who i can see the script status or run the script
- having tabs for more running more than one script.
Can you give me an hint how i can do this ? Via Django ? 

Same goes for the PI - i want to cronjob and access the PI from outside, like mobilel phone.
Anyone have infos on that ? 

Thanks alot!

**Comment by ChipWolf** [comment]
SSH.
