### ISSUE TITLE
TRYİNG TO FOLLOW PROBLEMS

### ISSUE THREAD

**Issue by xxurbanx** [instabot-py/instabot.py#663]
Code problem Trying to follow problems. I use "Mod 0". Help me.
![adsiz](https://user-images.githubusercontent.com/30419934/28544894-99cf2590-70cd-11e7-8cb2-56b7b9e39cbc.jpg)

instabot.py orginal

example.py
`bot = InstaBot(`
`    login="xxxxxxx",`
`    password="xxxxxxxxx",`
`    like_per_day=100,`
`    comments_per_day=0,`
`    tag_list=['follow4follow', 'f4f', 'cute','follow'],`
`    tag_blacklist=['rain', 'thunderstorm'],`
`    user_blacklist={},`
`    max_like_for_one_tag=50,`
`    follow_per_day=2000,`
`    follow_time=1 * 1,`
`    unfollow_per_day=0,`
`    unfollow_break_min=15,`
`    unfollow_break_max=30,`
`    log_mod=0,`
`    proxy='',`
`
Where is problem?

**Comment by progl** [comment]
It's not only your's problem. Instagram changed something and now it's not working.

**Comment by xxurbanx** [comment]
Is there a bot you can recommend for a solution?
@progl
