### ISSUE TITLE
Sign in issue

### ISSUE THREAD

**Issue by davidmantegna** [instabot-py/instabot.py#665]
I created a new account to log in with your bot and everything worked. 
Now it's two weeks I'm trying to log in with my personal profile, but it gives me the same old "Login error! Check your login data!".
How do I find a solution to this issue?
On the old issue I opened two weeks ago, someone told me to use a proxy because of a possible ip - profile incompatibility. 

Has anyone any bright ideas?

**Comment by ChipWolf** [comment]
What are you running it on?

**Comment by davidmantegna** [comment]
I tried it on my terminal and on Pythonanywhere

**Comment by ChipWolf** [comment]
It won't work on Pythonanywhere, we've established that in a few dozen issues already. Instagram blocks their IP ranges.
In your terminal? Who knows? What are you using to login? Username/password?

**Comment by davidmantegna** [comment]
Ok. The new account I created works if I run the bot in my terminal, but my own profile doesn't work.
I'm using username and password.

**Comment by ChipWolf** [comment]
Can you log in via your mobile device and the desktop site?

**Comment by davidmantegna** [comment]
It goes without saying...

**Comment by ChipWolf** [comment]
So, yes then.
In which case you've probably been rate limited or something, we've seen this behaviour with a few accounts. I'd go ahead and let the account cool down for 72 hours or so.
