### ISSUE TITLE
HELP!! NOTHING WORKS!! URLLIB3

### ISSUE THREAD

**Issue by sxmuel** [instabot-py/instabot.py#666]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**
Hey when running expample.py i get the message 
Traceback (most recent call last):
  File "C:\Users\Samuel\Documents\IG bot\example.py", line 12, in <module>
    from instabot import InstaBot
  File "C:\Users\Samuel\Documents\IG bot\src\instabot.py", line 16, in <module>
    import requests
  File "C:\Python27\lib\requests\__init__.py", line 43, in <module>
    import urllib3
ImportError: No module named urllib3
>>> 

I researched lots of issues and the common answer was to use this in CMD pip install urllib3 however when i used that the CMD said (image below)
![image](https://user-images.githubusercontent.com/30480650/28644657-4b505912-7252-11e7-9b55-d0ba7ad9f241.png)

**Comment by ChipWolf** [comment]
Heh, you don't run `pip install urllib3` in the actual python shell, just run it in cmd.

**Comment by sxmuel** [comment]
I did do it in the actual CMD check the photo.

**Comment by ChipWolf** [comment]
No you didn't. You did it in the python shell which you spawned with cmd.

**Comment by sxmuel** [comment]
Then how do i do it in CMD im not very good at coding

**Comment by sxmuel** [comment]
Do you mean like this?
![image](https://user-images.githubusercontent.com/30480650/28665708-7d52de5c-72bc-11e7-9b06-4dfcc9ae464e.png)

**Comment by ChipWolf** [comment]
pip isn't in path.
cd into the python installation directory, under scripts run the same command

**Comment by ChipWolf** [comment]
Can you not open multiple tickets @sxmuel

**Comment by sxmuel** [comment]
I do not understand how do i do can you write me a step by step guide please.

**Comment by sxmuel** [comment]
i have no clue what you mean by "cd into the python installation directory, under scripts run the same command"

**Comment by ChipWolf** [comment]
You type the letters `cd` into cmd followed by the path to the python installation directory (probably C:\Python27 or C:\Program Files\Python... something) there is a folder in there called 'scripts' you then `cd scripts` to change into that directory.
Then... run the pip command.

**Comment by ChipWolf** [comment]
if that's too difficult for you.. just reinstall python and make sure you click the 'add to path' box

**Comment by sxmuel** [comment]
This is what i have put into the CMD 
![image](https://user-images.githubusercontent.com/30480650/28669916-39ec7684-72ce-11e7-8819-8e9bf460fde9.png)

however i am still getting this
![image](https://user-images.githubusercontent.com/30480650/28669935-4f8a0df8-72ce-11e7-8a50-b75af77ab964.png)

What did i do wrong?

**Comment by ChipWolf** [comment]
you didn't hit enter after the pip command.

**Comment by sxmuel** [comment]
It didn't work again.

![image](https://user-images.githubusercontent.com/30480650/28670202-858bd200-72cf-11e7-9805-06a441564014.png)

**Comment by ChipWolf** [comment]
Go ahead and reinstall Python, that's not right

**Comment by sxmuel** [comment]
Can you link me to the python i should install as that may somehow make a difference

**Comment by sxmuel** [comment]
Why do you think that happened

**Comment by ChipWolf** [comment]
http://bfy.tw/3XM8 @sxmuel

**Comment by sxmuel** [comment]
what version? if 2.7 what one?

Windows x86-64 MSI installer or 
Windows x86 MSI installer

**Comment by sxmuel** [comment]
Hey i have reinstalled python this is what is happening now :( 
![image](https://user-images.githubusercontent.com/30480650/28726088-b4c42b7e-73b7-11e7-857c-a5113fb05273.png)

Also how do you run this, pip install -r requirements.txt? This is what i get!
![image](https://user-images.githubusercontent.com/30480650/28726129-e0f99cce-73b7-11e7-9b5b-7b8236e563fd.png)
