### ISSUE TITLE
HELP! urllib3! invalid syntax!

### ISSUE THREAD

**Issue by sxmuel** [instabot-py/instabot.py#667]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**
Hey when running expample.py i get the message
Traceback (most recent call last):
File "C:\Users\Samuel\Documents\IG bot\example.py", line 12, in 
from instabot import InstaBot
File "C:\Users\Samuel\Documents\IG bot\src\instabot.py", line 16, in 
import requests
File "C:\Python27\lib\requests_init_.py", line 43, in 
import urllib3
ImportError: No module named urllib3

I researched lots of issues and the common answer was to use this in CMD pip install urllib3 however when i used that the CMD said (image below)
![image](https://user-images.githubusercontent.com/30480650/28665832-e3b946c2-72bc-11e7-9485-4e854409bbc8.png)

i also tried it like this
![image](https://user-images.githubusercontent.com/30480650/28665845-eda9e0b0-72bc-11e7-966c-7b337cbfecce.png)

**Comment by ChipWolf** [comment]
Why did you open another ticket?
