### ISSUE TITLE
Download Image + Upload from your account?

### ISSUE THREAD

**Issue by psegovias** [instabot-py/instabot.py#67]
Im thinking in something related like a instagrabber

 It is able to do this? you can guide me some how?

Regards!

**Comment by LevPasha** [comment]
Hi, there is no this functional. Maybe later...

**Comment by psegovias** [comment]
Ok, i will try to do it for my own, let u know if i sucess.

**Comment by polaroi8d** [comment]
Hey @psegovias how about this function? Can i closed the issue?

**Comment by ChipWolf** [comment]
Out of scope
