### ISSUE TITLE
Install question (new to python)

### ISSUE THREAD

**Issue by jeffreylm** [instabot-py/instabot.py#670]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**
I was reading the install instructions. At nr 2 you say:  To install the project's dependencies, run command pip install -r requirements.txt (specify pip2 or pip3 if you have multiple versions of Python installed)

Are you talking about the file that is in the ZIP file in step 3?

Otherwise I am totally confused, also could you be very specific with the install instruction, so mention is you are speaking of the python directory or the instabot directory files, as it can get confusing.

Thank you in advance.

Greetings,
Jeffrey

**Comment by TehJokeR** [comment]
The projects dependencies will be in the instabot.py directory.

Once you've installed Python2.7+ and pip, you can use the pip command line tool to install the instabot.py dependencies

**Comment by sxmuel** [comment]
Hey @TehJokeR I have the same problem i have just installed pip and i am now getting this in the CMD
![image](https://user-images.githubusercontent.com/30480650/28725847-b1b07204-73b6-11e7-9b0e-f1f4ba1665f4.png)

**Comment by TehJokeR** [comment]
Run the pip command on the command line, not in the python interpretor

(dont type python before you enter the pip command)

**Comment by TehJokeR** [comment]
The problem from the other issue is that the requirements.txt file was in the directory you ran the pip command in.

Open up your cmd prompt, then change directory to the instabot.py folder..

You can type
`dir`
to see the current directory contents and then
`cd `
to get to the next folder..

for example:
```
[user@~] dir
Desktop Documents Downloads MyComputer
[user@~] cd Downloads
[user@Downloads] dir
file1.txt file2.txt instabot.py
[user@Downloads] cd instabot.py
[user@instabot.py] dir
src requirements.txt test README.md .git
```

**Comment by TehJokeR** [comment]
Close this issue

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
