### ISSUE TITLE
Feature request - The ablity to add security code

### ISSUE THREAD

**Issue by jeffreylm** [instabot-py/instabot.py#671]
Hello,

It would be a welcomed option to be able to enter Instagram security code when it comes in as an SMS.
Also is the connection made with SSL?

Kind regards,
Jeffrey

**Comment by TehJokeR** [comment]
Deactivate your 2-way-authentication and just set a really strong temporary (or permanent) new 
password. 

You cant configure the bot to enter the authentication code

**Comment by jeffreylm** [comment]
Thank you TehJoker. That worked.

**Comment by TehJokeR** [comment]
You can close this issue

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
