### ISSUE TITLE
not using the proxie?

### ISSUE THREAD

**Issue by koeniig2** [instabot-py/instabot.py#672]
i got the error400 and he is not liking pictures. Now i tried changing the ip with a new proxy. I use proxy:port, but nothing happens. Its still the error400... how do people use proxies in the script? i use it with "ip:port"

**Comment by TehJokeR** [comment]
If your proxy doesn't work it will throw an exception saying the HTTP request failed for the proxy and this usually happens before it logs into your account. 

Your format is correct proxy = "ip:port"   ( double check the variable name )

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
