### ISSUE TITLE
HUGE PROBLEM! PLEASE HELP! URLLIB3! PIP! INSTALL !REQUIREMENTS!

### ISSUE THREAD

**Issue by sxmuel** [instabot-py/instabot.py#673]
Why is this happening?
image
![image](https://user-images.githubusercontent.com/30480650/28726535-7aa6a35c-73b9-11e7-8edf-8dfb684804c7.png)

Also how do you run this, pip install -r requirements.txt? This is what i get!
image
![image](https://user-images.githubusercontent.com/30480650/28726520-7011ed48-73b9-11e7-955e-78266ebce9ca.png)

Someone said dont do it in the Python bit of CMD, but this happens
![image](https://user-images.githubusercontent.com/30480650/28726586-b455374e-73b9-11e7-978d-89c672460490.png)

**Comment by TehJokeR** [comment]
Close this issue and lets continue the conversation in the other issue. This issue is not related to the instabot.py project.

**Comment by TehJokeR** [comment]
@ChipWolf close this please

**Comment by sxmuel** [comment]
@TehJokeR Continue it on the other one then.

**Comment by TehJokeR** [comment]
Close the issues

**Comment by omglolkillerx37** [comment]
You are supposed to the the command in cmd, what I mean by that is don't type python before you copy paste the command just copy paste the command when you open cmd.
