### ISSUE TITLE
WHY IS THE BOT NOT DOING ANYTHING? NOT LIKING OR FOLLOWING!

### ISSUE THREAD

**Issue by sxmuel** [instabot-py/instabot.py#674]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**
When i run the bot it does nothing it doesn't like, follow or anything. It just says this over an over!

============================== 
Upss 443343635 is already in ex user list... 
==============================
sxmuel.s : Get media id on recent feed 
 29.07.2017 12:38
Media in recent feed = 24
sxmuel.s : Get user info 
29.07.2017 12:38
Except on get_info!
======> Get media id by user: 1711376191 <======
XXXXXXX Except on get_media! XXXXXXX
sxmuel.s : Get user info 
29.07.2017 12:40
Except on get_info!

**Comment by sxmuel** [comment]
Mode 2

**Comment by TehJokeR** [comment]
Use mode 0
