### ISSUE TITLE
Error 400 when liking a photo, any bypass?

### ISSUE THREAD

**Issue by bronzeboy** [instabot-py/instabot.py#679]
I have read that this is a soft ban since I can like photos by myself but the app will get me 400 every time. I waited 12h to try again and I'm still softbanned. Any way to bypass it? Changing the user-agent when doing the http request? Thanks!

**Comment by justinf102** [comment]
Did you figure it out?

**Comment by remyx11** [comment]
Got the same problem.. doesnt seem to happen with other bots
