### ISSUE TITLE
Unlike Feature: more control

### ISSUE THREAD

**Issue by alvvvvvin** [instabot-py/instabot.py#68]
Hi @LevPasha,

Is it possible to have:

`like_time=5*60*60,`
`unlike_per_day=0,`

A functionality to unlike the recent photos that have been liked? Similar to how unfollow in your script works.

Thanks in advance.

**Comment by LevPasha** [comment]
Why you need unlike? ))) Ok, i will do it next release.

**Comment by alvvvvvin** [comment]
It would be the same reason why someone would need an unfollow. Thanks.

**Comment by tinevdh** [comment]
+1 for this

**Comment by ChipWolf** [comment]
Out of scope.
