### ISSUE TITLE
Updating Python 3.5 Emoji Comment Issue 

### ISSUE THREAD

**Issue by Thor-Codinson** [instabot-py/instabot.py#681]
Running 3.5 Python 
Trying to use emoji comments, worked just fine previously (not sure what my old version was)
 but now seems to cause the "Your text has unicode problem!" flag to occur. Emoji is copy and pasted such that the symbol itself shows up. (ex: ["💚"]). Any ideas? Need to go back to an older version of python?

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
