### ISSUE TITLE
Unfollow pause time

### ISSUE THREAD

**Issue by jeffreylm** [instabot-py/instabot.py#682]
Hello,

In your explanation on the main page you have:

unfollow_break_min | int | Minimum seconds for unfollow break pause

You mave unfollow_break_**min** and then discribe it as break in **seconds**
Can you clarify if it is min or sec?

greetings,
Jeffrey

**Comment by alvarongg** [comment]
Hi Jeffrey, You aswer your own question.

In this case : 

min = Minimum 

You set this value in seconds. 

In adition you have the parameter 

unfollow_break_max  = Maximum seconds for unfollow break pause

If in Min you set 30 and Max 60 , the program pause the Unfollow between 30 and 60 randomly.

Regards. :+1:

**Comment by jeffreylm** [comment]
@alvarongg I thought the min was short form minutes. Sometime when you are taking on a lot of new stuff (Python) you just miss the simple things and over think it. Thanks for clearing that up for me.

**Comment by alvarongg** [comment]
No problem, that's the purpose of the community.

Don't forget close the issue :D

Bye

**Comment by jeffreylm** [comment]
@alvarongg Thank you once again.
