### ISSUE TITLE
QPython3 on android, but same problem with Windows: Invalid character.

### ISSUE THREAD

**Issue by welamakani** [instabot-py/instabot.py#684]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**
I really don't know anything about scripting or things, but I'm quite good to understand quickly.
Got the example.py , modified it with my username, password and all the things, but when I try to open the script it says that in line 28 "welamakani" (my username) is an invalid character. Even with others usernames is the same. How to solve that? 
PS; I'm Italian, so please be very easy with the language haha

**Comment by zbagdzevicius** [comment]
should be 'welamakani' instead or "*" i guess so.
