### ISSUE TITLE
[Feature Request] Location based liking

### ISSUE THREAD

**Issue by ekremgurdal** [instabot-py/instabot.py#691]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**
It would be great if we were able to add venue_id into Instabot so that bot could like the posts which were posted in specified venue

:)

**Comment by marfert** [comment]
I also need that 👍

**Comment by ekremgurdal** [comment]
I changed tag_url with locations but it didnt work.

**Comment by JoeyLyman** [comment]
is venue the same as location?  i would be stoked if I could do it for local people, like my county / city

**Comment by andrewsegas** [comment]
Guys, Here we have follow and like by location + user interface
https://github.com/andrewsegas/instaboost

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
