### ISSUE TITLE
Feature Request - Commenting LB and Liking LB 

### ISSUE THREAD

**Issue by kiaanpillay** [instabot-py/instabot.py#693]
So there is this crazy phenomenon where teens post LB(Like Back) on Kylie and Kendall Jenners photos meaning that if you like their photo they will like yours back. This article explains it well:

https://later.com/blog/how-i-hacked-the-instagram-algorithm/

Is there a was that we could automate this and periodically comment LB on Kylie and Kendall Jenners pics as well as like the first pic of a user that has commented with a comment that contains "LB"? 

Is this possible or too complex? Sorry I don't understand python well enough

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
