### ISSUE TITLE
The unfollow in mod 5 stops after unfollowing 24 accounts

### ISSUE THREAD

**Issue by live4perfection** [instabot-py/instabot.py#694]
i've tested this various times, It stops on the 24th one and doesn't do anything and has to be restarted manually again and again. what might be the issue ? I RUN IT ON mode 5 for unfollowing and i can;t figure out what's wrong

**Comment by arshiay** [comment]
i have this issue too
any solution?

**Comment by KevinSupertramp** [comment]
Hi,
Little bump, I've the same problem as well.
