### ISSUE TITLE
Scalability questions/concerns

### ISSUE THREAD

**Issue by bgreeson** [instabot-py/instabot.py#695]
Greetings contribs,

I am curious what sorts of scalability concerns you have run into in utilizing URLS such as 'https://www.instagram.com/web/friendships/%s/follow/' for actions. I have a similar project in which I have taken the longer route of simulating all interactions through the DOM. I'd love to convert over to a simpler method. I assume this method is tested with mostly known limitations. Could you share those limitations, or lack thereof?

Thanks,
-B

**Comment by ugurozturk** [comment]
if you still asking for this. Please open a new ticket.
