### ISSUE TITLE
closing after start

### ISSUE THREAD

**Issue by lifelessinsta** [instabot-py/instabot.py#696]
Hello I have installed python 3.6.2. I have only changed the amounts of comments per day in the example file. But when I try to run the example file it opens and closes immediately.

[example.txt](https://github.com/instabot-py/instabot.py/files/1217954/example.txt)

**Comment by bgreeson** [comment]
Hello,

I am not familiar with the code base, but issue #650 describes some issues with commenting that may exist in the code. Try setting comments to 0 per that ticket.

**Comment by lifelessinsta** [comment]
Still closes immediately

**Comment by bgreeson** [comment]
Without any error message, I don't think anyone here could help. Do you have a stack trace or any output?

**Comment by lifelessinsta** [comment]
If I try to start it in the terminal the a get a syntax error or unexpected character after line continuation

C:\Users\Myusername\Desktop\instabot.py-master python3 example.py <<<this is what I type in the terminal

**Comment by bgreeson** [comment]
Would you like to post the syntax error?

**Comment by lifelessinsta** [comment]
I followed this video https://www.youtube.com/watch?v=FPrHuhEURys&t=185s. at 2.58 he types in "python example.py. For some reason he can open his terminal in the map and the location is already there so I wrote the location myself "~/C:\Users\Mypcusername\Desktop\instabot.py-master $ python3 example.py

SyntaxError: unexpected character after line continuation character
>>> ~/C:\Users\mypcusername\Desktop\instabot.py-master $ python3 example.py
  File "<stdin>", line 1
    ~/C:\Users\mypcusername\Desktop\instabot.py-master $ python3 example.py
     ^
SyntaxError: invalid syntax
>>>

**Comment by egurdal-reidin** [comment]
can you try to install pycharm and run the code in pycharm?

**Comment by ekremgurdal** [comment]
can you try to install pycharm and run the code in pycharm?

**Comment by 0xv** [comment]
@lifelessinsta that guy in video use linux.
in windows open command prompt then `cd C:\Users\mypcusername\Desktop\instabot.py-master` and `python example.py`
or
open the instabot.py-master folder -> shift+right click -> `open command window here`. then in CMD `python example.py`

you need learn how to use CMD in windows 😬

**Comment by lifelessinsta** [comment]
Oh sorry forgot to close the question. I got it working with a different version of this instabot. And yes I used shift+right click to open the terminal. :) sorry
