### ISSUE TITLE
How To Get Follow List Specific User??

### ISSUE THREAD

**Issue by wrackful** [instabot-py/instabot.py#699]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**
Is there a url like this url : 'https://www.instagram.com/web/likes/[user-id]/like/'

**Comment by wrackful** [comment]
no anybody here ?

**Comment by ugurozturk** [comment]
https://www.instagram.com/graphql/query/?query_id=17851374694183129&variables={"id":"user_id","first":500}

You can change the first:500 as you wish. The best is changing the number of total followers

**Comment by Raul1231** [comment]
Hi,

so if I want to put this code in example.py, How can I do it? 
{"id":"user_id","first":500} just like this?  thank you
