### ISSUE TITLE
how to comment on a specific post

### ISSUE THREAD

**Issue by algarih** [instabot-py/instabot.py#702]
hi all, i am totally new to this and to python world... i have managed to run this awesome Instabot and now i would like to comment on a specific post, and define a comment list/random time between every comment. is it possible ?

also i want to know how to apply this without getting banned.

regards

**Comment by wrackful** [comment]
find media id ,go to source web page

**Comment by algarih** [comment]
Finding the media id isnt the issue,, but the issue im facing is how to implement this in code lines

**Comment by davext** [comment]
The way I would do it is I would construct a text file filled with just post URLs. The bot would take the URL and extract the media ID then pass it to the comment method. This way it would check for already commented posts so you won't be commenting twice.

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
