### ISSUE TITLE
HOW TO STOP FOLLOWING PRIVATE USERS?

### ISSUE THREAD

**Issue by aruser1** [instabot-py/instabot.py#703]
Now, before anyone suggests me to follow private users, please don't. It's not working out.
Just tell me .... how . to . only . follow . public . accounts ?
also, I have 0% experience in programming or writing in cmd.
please tell any easy way, or step by step way so I can copy your steps easily.

**Comment by Funktiona** [comment]
I have not tested but I think this will work.

in bot_follow.py change the the line in follow function from
if not self.check_user(user_id:
to
if not self.check_user(user_id, filter_closed_acc=True):

**Comment by Kyozaki** [comment]
Tried @Funktiona 's fix. Doesn't work. It still adds private accounts. Does anyone else have a solution for this? Thanks.

K'+

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.

**Comment by ugurozturk** [comment]
Asked team if i am wrong but the bot does only follow public accounts anyway. Because, bot finding the people from tags. And public account's medias goes there. So bot can't find them. After you following them then they might becoming private

**Comment by Kyozaki** [comment]
It still happens. I've reported it again here https://github.com/instabot-py/instabot.py/issues/954 (as requested) and added an image to show the bug.
