### ISSUE TITLE
Comment on your own content

### ISSUE THREAD

**Issue by Funktiona** [instabot-py/instabot.py#707]
I tried to comment on my own image but was not able to. 
Reading the project it stands

Warning!

The End-User assumes sole responsibility for anything resulting from the use or modification this program. Don't worry the bot will not:

    Like - comment or follow your own account or media
    Comment a media already commented

If someone could help me I would be happy

**Comment by dv1pr** [comment]
Add your username to the line in example.py here `user_blacklist={username:''},`

I store my username in a variable and patch it in where needed but of you just put your actual username in that line you should be good.

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
