### ISSUE TITLE
Suspicious login

### ISSUE THREAD

**Issue by joecasanova** [instabot-py/instabot.py#709]
No longer works.  Says I cannot log in.  Connection failed.  After attempting to use the tool I get a warning about a suspicious log in on the desktop or Android Instagram app.

I am not using a proxy.

**Comment by yuriscosta** [comment]
I'm with this trouble when I try to run on DigitalOcean.

**Comment by aJetHorn** [comment]
This has nothing to do with the features of instabot. Instagram will try its best to detect suspicious logins and lock down your account. To fix it, just log in through your app and have a security code sent.

**Comment by joecasanova** [comment]
The issue is that the server running instabot is on the US East coast and
yet the suspicious login is from cebu City, Philippines...

Again, no proxy being used.

**Comment by aJetHorn** [comment]
What leads you to believe this is caused by instabot? The DNS entries for your server are probably outdated. Advertised/discovered location nearly always differs from Instagram's reported locatation.

**Comment by joecasanova** [comment]
So you are saying that my server is trying to log into instagram via cebu
city, phillipines?

What is the domain name that the script logs in against so that I may
verify I have the correct DNS entry?

My server is set to resolve DNS against 8.8.8.8.  I've verified that,
rebooted, verified a clear DNS cache and I still have the issue.

**Comment by joecasanova** [comment]
Also, the error reports the OS that attempted to log in being Windows NT
10.  My server runs Ubuntu 17.

**Comment by delmotte** [comment]
Same problem for me

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
