### ISSUE TITLE
Except on Like, Follow, Comments...

### ISSUE THREAD

**Issue by dwuster** [instabot-py/instabot.py#711]
![untitled](https://user-images.githubusercontent.com/11356271/29488445-a7302edc-84e1-11e7-85ce-e93fdd7ac159.png)

**Comment by justinf102** [comment]
im getting error 400 not liked :/

**Comment by adhavalboy** [comment]
change mode=2 and try again

**Comment by ugurozturk** [comment]
update your code. If it is keeps happen again please open new issue
