### ISSUE TITLE
 Bug at launch

### ISSUE THREAD

**Issue by daduzh** [instabot-py/instabot.py#712]
How can i fix this error?

![image](https://user-images.githubusercontent.com/26740000/29493971-fad762c0-85a0-11e7-8208-a10c76f3dc0c.png)

**Comment by casualtiger** [comment]
Got similar one
<img width="569" alt="screen shot 2017-08-20 at 12 55 13" src="https://user-images.githubusercontent.com/31180746/29494281-d8c25680-85a6-11e7-8250-fbf60d550842.png">

**Comment by justinf102** [comment]
Are u running that in cmd as admin?

**Comment by daduzh** [comment]
@casualtiger The error is the same

**Comment by daduzh** [comment]
@justinf102 Yes

**Comment by 321mage7** [comment]
I am having the same issue also
![screen shot 2017-08-21 at 1 43 41 pm](https://user-images.githubusercontent.com/31220013/29535115-4aebc5d4-867e-11e7-8ddc-f4b045087f3c.png)

**Comment by luisramirez-m** [comment]
You need to install requests.

Put this comand in your terminal:

pip install requests

-LR

**Comment by daduzh** [comment]
thank you @luisramirez-m 
problem solved!
