### ISSUE TITLE
Cannot install project dependencies "No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by coolfoil** [instabot-py/instabot.py#713]
Hello. Whenever I try to run `pip install -r requirements.txt` I get the error:
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
I tried searching but couldn't find a solution. Any ideas?
I'm running Ubuntu 16.04 btw

**Comment by Hax7** [comment]
unzip the instabot.py zip file then cd into it then you can run the command.

**Comment by adhavalboy** [comment]
update python with new version .

**Comment by davext** [comment]
Make sure that the requirements.txt file is in the same as your current directory.
or just install requests and you're not going to need to run pip install -r requirements.txt

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
