### ISSUE TITLE
Why I can set up protocol for proxy server?

### ISSUE THREAD

**Issue by AlexanderKozhevin** [instabot-py/instabot.py#720]
Using syntax like this will give me an error
```
http://188.166.241.120:3128
```
Some proxies could use socks protocol.

Inside *instabot.py* on line 186:
```
proxies = {
                'http': 'http://' + proxy,
                'https': 'http://' + proxy,
            }
```
Can I just add *socks* to this code?

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
