### ISSUE TITLE
Not using top_posts when getting media by tag

### ISSUE THREAD

**Issue by orensbruli** [instabot-py/instabot.py#725]
We are not using the top post showing in a tag feed:
https://github.com/instabot-py/instabot.py/blob/d62ad796820ab6d2bca5e7aa9c991658d3cc0763/src/instabot.py#L332

It would be easy to do, we would just need to change that line to something like this:
```
self.media_by_tag = list(all_data['tag']['media']['nodes']) + list(all_data['tag']['top_posts']['nodes']
```
Those are only 9 media, but probably the most relevant ones.
What do you think? If you agree I can create a PR for this.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
