### ISSUE TITLE
How to unfollow specific accounts

### ISSUE THREAD

**Issue by mehdi691** [instabot-py/instabot.py#726]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**
Hi,

I would like to unfollow specific accounts. How can I do that ? 

I'm asking that because mode 5 unfollow everybody even if I put names on the white list unfollow...

Thanks a lot

**Comment by Funktiona** [comment]
How do you mean specific. like you will time like 10 usernames in a list and unfollow them?

**Comment by Funktiona** [comment]
username = '9gag'
bot.unfollow(bot.get_userid_from_username(username))

this will unfollow 9gag

**Comment by mehdi691** [comment]
Thank you for responding @Funktiona. It seems it didn't work...

Here my code:

mode = 0

   ` if mode == 0:
        #bot.auto_mod()
        username=['ferrari', 'scuderiaferrari', 'ferrariusa'],
        bot.unfollow(bot.get_userid_from_username(username))`

Error: "AttributeError: 'InstaBot' object has no attribute 'get_userid_from_username'"

I have also tried:  `bot.unfollow(username)` 
it didn't work too..

By the way, I'm not sure to copy and past your code at the right place... 

THANK YOU

**Comment by Funktiona** [comment]
try username = '9gag'
self.unfollow(self.get_userid_from_username(username))

**Comment by ChipWolf** [comment]
This is out of scope
