### ISSUE TITLE
Does follow_time work as it should?

### ISSUE THREAD

**Issue by iounas** [instabot-py/instabot.py#728]
It is set to 12h (12 * 60 * 60) but I see it following and then unfollowing somebody after 30min.
Default mode 0

**Comment by ChipWolf** [comment]
I'm going to assume #669 might solve this. Until then, please provide evidence

**Comment by iounas** [comment]
Evidence is right in the code
new_auto_mod_unfollow goes through the list and gets first from bot_follow_list with  with correct unfollow time but then auto_unfollow() is called with no params. It gets last media on feed and unfollows 1 account randomly with no time checks.

**Comment by disprozzy** [comment]
**ionas** is right, _new_auto_mod_unfollow()_ is used for unfollowing, it checks follow time for a user and starts _auto_unfollow()_ without passing the user
