### ISSUE TITLE
error in example.py when run feed_scaner() on mode 4

### ISSUE THREAD

**Issue by AfshinZlfgh** [instabot-py/instabot.py#735]
![screenshot from 2017-09-06 23-24-05](https://user-images.githubusercontent.com/22290288/30129998-0556b7e0-935d-11e7-9d8c-7b784a67b279.jpg)

I run example.py with default function and one tag in mode 4 and get this, additional marked line in my terminal is for one print(self.media_on_feed[chooser]["node"]["owner"]["id"]) line i add by myself for debug, but i'm new in python and coudn't do that .

**Comment by kypse** [comment]
Dear,
I tried to enter with my user and password and got login "Login error! Check your login data!". Even using the username or email... is any trick on that?

**Comment by jegue** [comment]
same erro hehre

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
