### ISSUE TITLE
Hashtag analysis follow per like quote

### ISSUE THREAD

**Issue by derrainer84** [instabot-py/instabot.py#736]
Hi guys, 
I#m not shure if I'm right here. Please feel free to replace the thread. 
My pont goes about hashtag analysis. Can someone help? 
 					
Whe you use the instabot you like up to 1000 pics a day.
These pics are choosen by defined hashtags.
You get attention because of the likes.
Some of the users who own the liked pics wil follow you.
So far nothing new! 
Question: Which hashtags generate most followers? 
It would be pretty cool to have a table wich shows you the hashtags with the follow per like quote.
If you use the hashtags #cat #sport #fun it would be interesting which of them to replace and which not. 
					
For Example: 
	#cat:	0,2%
	#sport:	0,6%
	#fun:	0,01%
You can replace #fun and use the 1000 likes per day much more efficent!
Unfortunately I'm not able to program that, I experimented with the Instagram API, but ist semms to be to hard for me, cause I'm a newby in Python.

I thougt about some steps to do, don't know if its possible:
	1. Create a table within all liked pics, hastags, mediaowner and following status fo media owner.
	2. Delete all Hashtags wich are not in the parameter file. (modified example.py)
	3. Count the pics per hashtag
	4. Count the follower per hashtag
	5. Devide counted followers through counted pics
	6. Create a table with the Hastags and the quote. 
					
What do you think?

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
