### ISSUE TITLE
How to stop the bot from liking completely ?

### ISSUE THREAD

**Issue by omerbadawy11** [instabot-py/instabot.py#740]
Id like to stop the bot from liking at all i tried setting
    like_per_day=0,
    max_like_for_one_tag=0,
but it still likes
i have it on mode 3

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
