### ISSUE TITLE
Error 400 when liking or following

### ISSUE THREAD

**Issue by davidmantegna** [instabot-py/instabot.py#743]
How can I fix something like this?
![screen shot 2017-09-12 at 16 30 16](https://user-images.githubusercontent.com/18500333/30331337-d32f8eb6-97d7-11e7-87b7-87d8ca2d864a.png)

**Comment by kekbait** [comment]
Same problem here. The script works on another ip but not on my VPS. Getting 400 error constantly.
Did Instagram change it's API or it's banning process ?

**Comment by kekbait** [comment]
Try to change your IP if you are banned

**Comment by davidmantegna** [comment]
My IP is not banned. I'm also logged in with my phone


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: kekbait <notifications@github.com> Date: 13/09/2017  19:51  (GMT+01:00) To: "instabot-py/instabot.py" <instabot.py@noreply.github.com> Cc: davidmantegna <davide.montanari10@gmail.com>, Author <author@noreply.github.com> Subject: Re: [instabot-py/instabot.py] Error 400 when liking or following (#743) 
Try to change your IP if you are banned

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/instabot-py/instabot.py","title":"instabot-py/instabot.py","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/instabot-py/instabot.py"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kekbait in #743: Try to change your IP if you are banned"}],"action":{"name":"View Issue","url":"https://github.com/instabot-py/instabot.py/issues/743#issuecomment-329245846"}}}

**Comment by bearfrance** [comment]
stopped working for me too, on several ips and accounts

**Comment by davidmantegna** [comment]
In my case sometimes it works, sometimes it returns always error 400

**Comment by beben06** [comment]
I think Instagram changed something i get a lot of 400 also...

**Comment by knokkelmanns** [comment]
Same problem. I change the proxy servers, and this helps to 1-2 likes

**Comment by virginsince1997** [comment]
Same here 400 error

**Comment by justinf102** [comment]
yea, I get it sometimes making the bot stop working completely

**Comment by gersanchez** [comment]
same here!! please help!!

**Comment by ugurozturk** [comment]
Same here

**Comment by TheGrandFather** [comment]
Hi there! If we use website there's a ping to keep alive connection. I guess we need to send this periodic ping. Using firefox tools, you can see in "net connection" something like this every few minutes:
https://www.facebook.com/connect/ping?client_id=...

**Comment by ugurozturk** [comment]
use https://github.com/instabot-py/instabot.py/issues/887 for tracking in the future
