### ISSUE TITLE
Can we add private messaging function?

### ISSUE THREAD

**Issue by AlexanderKozhevin** [instabot-py/instabot.py#744]
Or it's not possible because instabot emulate web agent?

**Comment by ekremgurdal** [comment]
Did you solve that?

**Comment by AlexanderKozhevin** [comment]
Nope :)
I used a different library -  ** instagram-private-api ** based on nodeJS.
And created a server which manager multiple sessions and actions. 

@ekremgurdal Let me know if you need some help :)
https://www.codementor.io/alexander-k
