### ISSUE TITLE
Is it possible to ignore Error 400 so it doesn't stop the script?

### ISSUE THREAD

**Issue by zhen737** [instabot-py/instabot.py#748]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**

Hi all, I have realize a lot of people getting error 400 nowadays, even some people are facing the issue that few times of error 400 will stops the script (Which mean no more liking, and commenting and following as well).
Before we figure out how to deal with error 400, may I know is there any possible way to ignore the error 400 - not liked issue, and let the comment and follow continue do its job?

I am not talking about to stop the like completely, but continue liking but error 400 will not stop the script.

Cheers!

**Comment by napster2091** [comment]
set self.like_for_day = 0 when you receive the message you are been banned

**Comment by ugurozturk** [comment]
it is possible but it is dangerous i think. To track "not liked 400" error in the future use https://github.com/instabot-py/instabot.py/issues/887
