### ISSUE TITLE
[DATABASE] Works only with 1 hashtag or 1 username, not the whole list

### ISSUE THREAD

**Issue by thecube69** [instabot-py/instabot.py#749]
Hello guys,

I tried to found if somebody else has this issue but apparently not. 

In my hashtag and username database, I added several words and users. I tried to do it by opening the file and add them and also to delete everything and add them with the multi_script.

But the problem that I have, is that whenever I choose "use hastage or username database", the script will choose one randomly but will stop after the first hashtag or username, it won't continue.

Can anybody help me to fix that?

Thank you

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
