### ISSUE TITLE
Qpython not working

### ISSUE THREAD

**Issue by koeniig2** [instabot-py/instabot.py#754]
when i start the script on my android.. it says "no module named request"... people say to install request manually, but i dont know how to install it.. anyone can help me out here?

**Comment by luisramirez-m** [comment]
You need to install Requests, In QPython you have to enter the option of the QPYPI menu, then there are 2 tabs (Programs and QPypi), you have to enter in the tab with the name Qpypi, clicking an option that says "Install With Python's PYPI".

After this opens a new console, where you can run commands with pip, example to install Request, you have to enter `pip install requests`.

I hope and understand me, excuse my English.

**Comment by koeniig2** [comment]
Thank you sir.. that is a good tutorial :-) works

**Comment by TehJokeR** [comment]
@koeniig2 if the issue is solves please close the issue
