### ISSUE TITLE
My bot dont unfolows

### ISSUE THREAD

**Issue by pedronader** [instabot-py/instabot.py#756]
My bot in the modes 0 and 2 just do the likes features. Dont do the unfollows. What is the problem?

**Comment by TehJokeR** [comment]
You have an unfollow amount of time set from the point you originally start the bot. Your bot needs to be running for this amount of time before it begins to unfollow accounts. For example mine is set to 12 hours so it follows accounts for 12 hours before it starts doing both follow/unfollow

**Comment by Crusage** [comment]
@TehJokeR i set mine to 30 min, but my bot wont unfollow even after 30 min... it only unfollows like 50 people before it stops. I even have the unfollow amount on 1200, because i wanted to see if it made any difference from 400 or 800

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
