### ISSUE TITLE
Like Feature

### ISSUE THREAD

**Issue by pedronader** [instabot-py/instabot.py#758]
I'm using the like feature.
On the cmd feed it shows that the media have been liked.
Butwhen in check it on in instagram its not liked.

I shows a lot of midia liking in feed but only some of them are really liked in the Instagram.

What could be happen?

**Comment by octohedron** [comment]
Probably Instagram is detecting the weird behaviour and blocking it.

**Comment by stoicvibe** [comment]
I can confirm that the same thing is happening to me. Haven't had a chance to look into it yet but it's weird because it seems to return a successful response but it's not liking all of the media.

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
