### ISSUE TITLE
Feature Request: Follow People who follow a certain account or liked a certain post

### ISSUE THREAD

**Issue by c-zar** [instabot-py/instabot.py#759]
Allow the ability to follow users who follow a certain account or liked a certain post

**Comment by TehJokeR** [comment]
It's impossible to get this data

**Comment by c-zar** [comment]
I mean if i proved a link of the post, it should be pretty easy to get every userID that liked it.

**Comment by c-zar** [comment]
Example: https://www.instagram.com/p/BMPMNKFBPp-/liked_by/
url to get users from: https://www.instagram.com/p/%s/liked_by/

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
