### ISSUE TITLE
Not Liked: 401

### ISSUE THREAD

**Issue by christieallison12** [instabot-py/instabot.py#760]
Its not leting me like any pics i need help

Skype:BlessZinky
Kik:Cydia_Won

**Comment by kekbait** [comment]
Are you using two accounts on the same IP ?

**Comment by christieallison12** [comment]
Yes I need your help with something else too

Skype:BlessZinky

**Comment by virginsince1997** [comment]
Yes

**Comment by christieallison12** [comment]
I have to change ip address? i have Dynamic ip though

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
