### ISSUE TITLE
Syntax error when trying to run

### ISSUE THREAD

**Issue by stan58032** [instabot-py/instabot.py#764]
I have configured my pyton setting as I please and when I try to run it I get
SyntaxError: invalid syntax
it reffers to this line 21
    comments_per_day=0,
But reading the tutorial it says that this line is accepted, I don't want the bot to comment for starters.
Any advice would be welcomed, thank you very much, please mind that I am new to this. Thanks

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
