### ISSUE TITLE
Keeps following same user

### ISSUE THREAD

**Issue by numerosmg** [instabot-py/instabot.py#773]
I've read through other issues and didn't seem to find anything relevant to this issue.
Basically I'm getting:

1. Trying to follow: 123456789
2. Followed: 123456789 #2.
3. Trying to follow: 123456789
4. Followed: 123456789 #3.
5. Trying to follow: 123456789
6. Followed: 123456789 #4.
7. Trying to follow: 123456789
8. Followed: 123456789 #5.

All the time... and if I run multiple bots for multiple accounts that have same tags list they all are targeting the same one guy... After a few minutes they switch to some other guy and do the same process all over on that other guy... and after a while goes back to the first guy! I changed little to none setting from the example.py after downloading it (mainly making it to unfollow 0 accounts per day, did a little less for commenting etc,) and I'm always running it through `python example.py` command.

**Comment by neo87br** [comment]
Same issue here.

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
