### ISSUE TITLE
How do i run command "pip install -r requirements.txt"?

### ISSUE THREAD

**Issue by Crusage** [instabot-py/instabot.py#775]
Sorry if this is a very stupid question. But im new to this, and i have no idea how to run this command. I tried in cmd,
 "'pip' is not recognized as an internal or external command,
operable program or batch file".
 Then i changed directory to where the requirements.txt file was. Still 
" 'pip' is not recognized as an internal or external command,
operable program or batch file"

**Comment by kerack04** [comment]
Did you ever figure this out? I'm having the same issue in windows 7

**Comment by Crusage** [comment]
@kerack04 I did figure it out, yes. Im not sure how i fixed it, but this is what i did:
1. Found out i have the latest version of python installed
2. Reinstall python
3. Open cmd and see if "py" or "python" is a recognized command. In this case it was.
4. I closed cmd and opened it again, and tried "pip" as a command. And that also worked.
5. I then tried "pip install -r requirements.txt" But i got an error message telling me that requirements.txt cannot be found or isnt a correct file location
6. Then i figured out where i have the requirements.txt file (its in the download, btw)
7. In my case it was "D:\Documents\BHW\instabot.py-master\instabot.py-master\requirements.txt"
8. So instead of typing "pip install -r requirements.txt" as a command i typed "pip install -r D:\Documents\BHW\instabot.py-master\instabot.py-master\requirements.txt"
9. You could also try to run that command in the python command prompt, which you can access by opening cmd and typing in "python" or "py"
10. Sorry if it was all very confusing
