### ISSUE TITLE
Mode 1 - bot stops after some time with errors

### ISSUE THREAD

**Issue by numerosmg** [instabot-py/instabot.py#780]
Ye so basically it runs for some time (few second - 5 minutes max) successfully following/unfollowing a bunch of people, commenting, and liking, but then it just stops with 1 of 2 of the following errors; either:

```
Traceback (most recent call last):
  File "example.py", line 84, in <module>
    unfollow_protocol(bot)
  File ".../src/unfollow_protocol.py", line 40, in unfollow_protocol
    follow_protocol(self)
  File ".../src/follow_protocol.py", line 23, in follow_protocol
    feed_scanner(self)
  File ".../src/feed_scanner.py", line 37, in feed_scanner
    self.current_id = self.media_on_feed[chooser]["node"]["owner"][
KeyError: 'owner'
```

or the second one: 

```
Traceback (most recent call last):
  File "example.py", line 89, in <module>
    feed_scanner(bot)
  File ".../src/feed_scanner.py", line 37, in feed_scanner
    self.current_id = self.media_on_feed[chooser]["node"]["owner"][
TypeError: 'NoneType' object is not subscriptable
```

Any ideas on why is this happening and how to fix it?

**Comment by omerbilgin** [comment]
same here...

> Traceback (most recent call last):
  File "C:/Users/OMER/PycharmProjects/instabot_omer/example.py", line 91, in <module>
    feed_scanner(bot)
  File "C:\Users\OMER\PycharmProjects\instabot_omer\src\feed_scanner.py", line 37, in feed_scanner
    self.current_id = self.media_on_feed[chooser]["node"]["owner"][
TypeError: 'NoneType' object is not subscriptable

**Comment by numerosmg** [comment]
Well the only "workaround" that I am currently using (on Linux)( and probably a pretty bad one at that) but it kinda works so...:
I created a script file inside the folder where example.py is located:
```
if python example.py | grep -q 'Logout success!'; then
  echo "repete"
  ./autorun.sh
fi
```
So it just restarts the bot again if it stops... Not sure how safe this is, but I'm going with this for now.

**Comment by wizarduk** [comment]
Is this due to comments i have tested several times and lasts for 2hrs and then does this ?

**Comment by wizarduk** [comment]
@numerosmg i tried this and it didnt work ?

**Comment by indiespace** [comment]
I had the same issue, just looked at the traceback and found that in feed_scanner.py on line 37, the last part of the code was on the line underneath.

I have fixed the issue and pushed the changes.

**Comment by wizarduk** [comment]
@indiespace this is old a update of the script fixed this....

**Comment by indiespace** [comment]
@wizarduk The changed hasn't been merged with the master so the bug still exists. Also, I forgot I don't have permission to push changes :p

**Comment by wizarduk** [comment]
@indiespace sorry im talking about another script which is far better that i now use

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
