### ISSUE TITLE
Unfollowing not working (posted many times before, but still has not been fixed)

### ISSUE THREAD

**Issue by Crusage** [instabot-py/instabot.py#789]
The reason im posting this is because it still is not fixed. I see these kind of posts from a year ago. But i am having problem with it now. (i am on mode 2 btw) I set following to 400 a day, and unfollowing to 1200 a day, it unfollows 50 people, but then stops and only follows (i have also tried to set following to a lower number, but no difference) I have tried the timer on 1 hour, 2 seconds, 5 seconds, 5 hours and 30 minutes. But only unfollows about 50 people. Why does this happen? And how can i fix?

**Comment by karambita** [comment]
I have the same problem, follow works but unfollow not

**Comment by agustinx19** [comment]
The jobs like-follow-unfollow arent balanced, I think the problem is that script do not use threads for manage all jobs.

**Comment by dv1pr** [comment]
Well the script definitely is following people and adding them to a list but then just unfollowing a random user from the users followers. I've had to turn this feature off on most accounts but planning to debug soon and will post solution!

**Comment by camputty** [comment]
please do dv1pr!

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
