### ISSUE TITLE
AUTO RESTART WHEN CRASHES

### ISSUE THREAD

**Issue by focamonca** [instabot-py/instabot.py#791]
In the FB group a very kind user suggested me to use this way: http://www.devdungeon.com/content/creating-systemd-service-files

and create a file like that one:

`[Unit]
Description=Instagram Bot
#Requires=After=mysql.service # Requires the mysql service to run first

[Service]
Type=simple
ExecStart=/usr/bin/python /var/www/vhosts/instagram-bot/yourscript.py
#WorkingDirectory=/opt/nodeserver # Required on some systems
Restart=always
RestartSec=1200 # Restart service after 10 seconds if python service crashes
StandardOutput=syslog+console # Output to syslog
StandardError=syslog+console # Output to syslog
SyslogIdentifier=script-instagram-bot
#User=<alternate user>
#Group=<alternate group>
#Environment=NODE_ENV=production PORT=1337

#[Install]
#WantedBy=default.target`

but i'm gettin tons of errors... can you help me?

**Comment by agustinx19** [comment]
Or make a bat for Windows: run.bat

Code:

'''batch
title Instagram Bot
echo off
cls
echo Iniciando script...
python example.py
:A
echo Reiniciando script...
python example.py
GOTO A
'''

**Comment by Plushkin** [comment]
And how it will be on MacOS?

**Comment by focamonca** [comment]
I'm using Raspberry, this is my main problem
any solution?

**Comment by ivadenis** [comment]
I used http://supervisord.org/.
Setup is pretty simple.
`pip install supervisor`

Once the Supervisor installation has completed, run `echo_supervisord_conf`. This will print a “sample” Supervisor configuration file to your terminal’s stdout.

Once you see the file echoed to your terminal, reinvoke the command as `echo_supervisord_conf > /etc/supervisord.conf`. This won’t work if you do not have root access.

Now, let's setup the config file.

`vim /etc/supervisord.conf`

Go to the bottom of the file and add these for every routine that you are running:
`
[program:instabot_routine_1]
command=python /path/to/example.py
autorestart=true
`

Then you can launch `supervisorctl`, type `help` and you will see your routines etc.
You can add, restart, stop and control them as such.

**Comment by focamonca** [comment]
I'm getting 
```
pi@raspberrypi:~ $ sudo echo_supervisord_conf > /etc/supervisord.conf
bash: /etc/supervisord.conf: **Permission denied**
```

Evend If I'm using SUDO

**Comment by focamonca** [comment]
I I did it using 
`sudo su`

but now I'm stucked here: 

`root@raspberrypi:/home/pi# vim /etc/supervisord.conf
bash: vim: command not found
`

**Comment by ivadenis** [comment]
Ok, put it somewhere where you have access. Try

`echo_supervisord_conf > ~/supervisord.conf`
Launch supervisord:
`supervisord -c ~/supervisord.conf`

If you don't have vim, use `vi` or any other text editor.

**Comment by Banginpadr** [comment]
bro i got everything that you said. but i cant just make it to work in pycharm. is there a way to make it work using pycharm?because if im not wrong this is only if you are running the code using terminal. im using pycharm to run the examply.py

**Comment by Banginpadr** [comment]
supervisor> status
instabot_routine_1               FATAL     Exited too quickly (process log may have details)

is normal to get this error??? another thing i would like to know is that whenever i run supervisorctl i dont need to run python example.py? because by just running supervisorctl will take care of everything, right?

**Comment by ice1x** [comment]
Actually we can insert "try except" processing to ignore this situation - if somebody of project-owner is interested i can create patch

**Comment by ivadenis** [comment]
@Banginpadr you won't need to run your .py routine through pycharm anymore. Supervisor will run it for you as a process in a background on your machine and if the process goes down, then it will try to restart it. If the process can't start successfully after 3 attempts it will fail.

With the bot, if there is an exception, the routine should be able to restart.

Let's see you error message. Go to console and tell me what the log for the routine says.
The log file should be in a format below, with some random hash. Tell me if you can find it?
`cat /tmp/instabot_routine_1-stderr-`

**Comment by Banginpadr** [comment]
@ivadenis i see, thank you for your work this is fantastic. anyways i think is not running and this is the error im getting. it seen like the bot is not running from this is script or something is stoping it from doing so

2017-11-21 22:40:53,498 INFO Increased RLIMIT_NOFILE limit to 1024
2017-11-21 22:40:53,516 INFO RPC interface 'supervisor' initialized
2017-11-21 22:40:53,516 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-11-21 22:40:53,517 INFO daemonizing the supervisord process
2017-11-21 22:40:53,519 INFO supervisord started with pid 69989
2017-11-21 22:40:54,524 INFO spawned: 'instabot_routine_1' with pid 69993
2017-11-21 22:40:55,526 INFO success: instabot_routine_1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-11-21 22:40:57,450 INFO exited: instabot_routine_1 (exit status 1; not expected)
2017-11-21 22:40:58,454 INFO spawned: 'instabot_routine_1' with pid 70002
2017-11-21 22:40:59,363 INFO exited: instabot_routine_1 (exit status 1; not expected)
2017-11-21 22:41:00,367 INFO spawned: 'instabot_routine_1' with pid 70010
2017-11-21 22:41:01,256 INFO exited: instabot_routine_1 (exit status 1; not expected)
2017-11-21 22:41:03,259 INFO spawned: 'instabot_routine_1' with pid 70019
2017-11-21 22:41:04,156 INFO exited: instabot_routine_1 (exit status 1; not expected)
2017-11-21 22:41:07,161 INFO spawned: 'instabot_routine_1' with pid 70029
2017-11-21 22:41:08,058 INFO exited: instabot_routine_1 (exit status 1; not expected)
2017-11-21 22:41:09,060 INFO gave up: instabot_routine_1 entered FATAL state, too many start retries too quickly
2017-11-22 00:38:29,359 INFO Increased RLIMIT_NOFILE limit to 1024
2017-11-22 00:39:57,976 INFO Increased RLIMIT_NOFILE limit to 1024
2017-11-22 00:45:11,869 INFO Increased RLIMIT_NOFILE limit to 1024
2017-11-22 00:48:06,591 INFO Increased RLIMIT_NOFILE limit to 1024
2017-11-22 00:48:30,918 INFO Increased RLIMIT_NOFILE limit to 1024

**Comment by ivadenis** [comment]
This is for supervisord process. There should be a log file named after your process/routine.

Can you paste output of this:
`ls /tmp/`

**Comment by Banginpadr** [comment]
@ivadenis no bro nothing the only files from this file in that directory are the log and .pid

**Comment by Banginpadr** [comment]
@ivadenis the only thing i can think of is that to create the supervisord file in the etc directory, you said we need root access. i used sudo su, got into root and made the file. maybe since im not root no more isnt working or something. i will try to moving that file to another directory as you told the other guy to see if it work

**Comment by Banginpadr** [comment]
ok i got it i think the problem was because you cant have logs in the example.py. i set it up to log=2 instead of 0.

**Comment by ivadenis** [comment]
Should be log 1. however, you should have log files that I was talking
about in a /tmp folder regardless.

**Comment by HenryCooperGithub** [comment]
Crash issue will be handled in this issue #815
