### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by Godweed** [instabot-py/instabot.py#80]
Is it possible to get tag search by location?

**Comment by Gorghor** [comment]
If you know the location's code on Instagram it shouldn't be to hard to modify the script to use https://www.instagram.com/explore/locations/%s/ (%s being the code of a specific location). I don't see how you could filter those results by tag afterwards though.

**Comment by ProdigyMaster** [comment]
If i change #url_tag = 'https://www.instagram.com/explore/tags/' to 
 url_tag = 'https://www.instagram.com/explore/locations/' . I've got media exception error. Any ideas? Thanks

**Comment by Bellman281** [comment]
These links are showing media's taken in [NYC](https://www.instagram.com/explore/locations/212988663/new-york-new-york/
)
some examples:
https://www.instagram.com/p/BR6JvG9A18z/?taken-at=212988663
https://www.instagram.com/p/BR6JunChd2w/?taken-at=212988663
https://www.instagram.com/p/BR6JwBEFe1s/?taken-at=212988663
https://www.instagram.com/p/BR6Jy8VhhE9/?taken-at=212988663

I assume we can update the code url_location= = 'https://www.instagram.com/p/%s/?taken-at=212988663'

But donno how to do it!?

**Comment by andrewsegas** [comment]
Guys, Here we have follow and like by location + user interface
https://github.com/andrewsegas/instaboost

**Comment by bahadirtortop** [comment]
Hi,

It's perfect. But how can I write comment on this tool? Please let me
example.

2018-03-15 16:17 GMT+03:00 Andrews Fernandes Egas <notifications@github.com>
:

**Comment by andrewsegas** [comment]
@bahadirtortop, can you please open one issue there? I'll finish comment function in User Interface today

but anyway you can youse in example.py with console mode as well

**Comment by mcarlock12** [comment]
For some reason when I change the location id it still searches for New York in location(default). Does anyone know how to fix this?

Also when you add location does it ONLY search by that location or just includes that location?

--examples.py---
from instabot_py import InstaBot

bot = InstaBot(
    login="username",  # Enter username (lowercase). Do not enter email!
    password="password",
    like_per_day=1000,
    comments_per_day=0,
    tag_list=["follow4follow", "f4f", "cute", "l:212999109"],
    tag_blacklist=["rain", "thunderstorm"],
    location_id_list=['215824708'],

....

This goes to New york (for some reason it keeps looking here)
location_id_list=['212988663']

I need it to go to Columbus ohio
location_id_list=['215824708']
