### ISSUE TITLE
Limit number of followers got by follow_user_followers

### ISSUE THREAD

**Issue by mozlab** [instabot-py/instabot.py#800]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**
If i want to get for example only 2000 followers from some account instead of all of them(200k for example) am i able to do so?

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
