### ISSUE TITLE
Follows Only 1 Person

### ISSUE THREAD

**Issue by Pietro-Aretino** [instabot-py/instabot.py#804]
At the moment the script is able to login just fine, and it begins following based on the tags I gave it, however it only follows one person.

Once I stop the program from running, it also quits and unfollows that 1 person. Is this how it is supposed to function?

Is there a variable to tell the bot to follow a new person every X seconds?

**Comment by ugurozturk** [comment]
@Pietro-Aretino  https://github.com/ugurozturk/instabot.py/tree/sqlite3 Check this

**Comment by austinbeauch** [comment]
Was having the exact same issue. @ugurozturk thanks for the link, this appears to be working (so far followed 3 unique individuals).

**Comment by ugurozturk** [comment]
@austinbeauch i did PR and there is nobody does merge. Btw i also fixed error 400 to stopping botting problem. It does run nicely while it does also follow

**Comment by ugurozturk** [comment]
use https://github.com/instabot-py/instabot.py/issues/887 for tracking in the future
