### ISSUE TITLE
Issue when running the bot on a raspberry pi

### ISSUE THREAD

**Issue by Everyatis** [instabot-py/instabot.py#806]
Hi everybody,
I am using the bot with my PC on windows 10 with python3 and it works perfectly!
However I would like to make it run on my raspberry pi card so as I can let it turned on.
The OS is raspbian weezy and I have python3 and requests installed on the card.
But each time I try to run the bot by opening the example.py file with python I get the following error : 
Login error! Connection error!

My card is connected to internet and given that the bot works on my PC with the same account and the same "example.py" file the issue cannot be the "Two-factor authentication" or a wrong password...
Do you have any ideas?
Thank you for your help

**Comment by Everyatis** [comment]
I didn't fix the issue... if anyone has an idea..

**Comment by forevermirin94** [comment]
I have the exact same issue on my Raspberry Pi, haven't found the solution yet.

**Comment by ErikBoesen** [comment]
Could we get a full stack trace?

**Comment by spud-dog** [comment]
Hi I'm also trying to get this up and running on a Raspberry Pi, if anyone has solved this now?

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
