### ISSUE TITLE
Proxy problem

### ISSUE THREAD

**Issue by Victorrussia** [instabot-py/instabot.py#809]
Hello! Thank you very much firstly for the best bot which I have ever seen for instagram(I have been using it since summer 2016). My problem is in installing proxy for example.py. When I write something in the proxy lane nothing changes unfortunately... It seems like program doesn't react on proxy or I am doing something wrong right now.
![proxy](https://user-images.githubusercontent.com/33234413/32191849-7b06b608-bdc3-11e7-9098-1f96868adc72.jpg)
LevPasha, я знаю, что Вы понимаете по-русски, поэтому напишу на нашем на всякий случай:
Я перерыл весь форум в поисках своей проблемы, но так и не нашёл объяснения, что делать, если при вводе прокси ip:port ничего не изменяется. Причем я могу написать что угодно внутри и программа просто запустится с прокси pythonanywhere где-то в Америке и будет работать(а как всем известно, лайки прикрыли примерно полгода назад и понадобились прокси). Надеюсь, Вы подскажете мне, где моя ошибка или невнимательность.
P.S. Сейчас почему-то заработали лайки, когда изменил follow time с 1*60 на просто 60, но непонятно, работает ли мой прокси. Вполне возможно, что это лишь временно, поэтому всё ещё ожидаю ответа на свой вопрос
P.P.S. Снова перестали работать

**Comment by taradell** [comment]
Hi mate @Victorrussia I used a public proxy and it works.
From the screenshot you posted I see that you are using **" "** instead of **' '**.. try to set the proxy as follows:
proxy=**'**user:password@10.10.1.10:3128**'**,  - if you have login credentials -

or 

proxy=**'**10.10.1.10:3128**'**, - if the proxy you are using is like mine (no authentication required)

hope this helps!

**Comment by Victorrussia** [comment]
Hi, @taradell ! It doesn't depends as I know what exactly you put: ' ' or " ". Now it works 50/50(approximately after 50 likes the error 400 appears again). But I still think program does not see my proxy because I have nothing written inside the console when I start example.py with my proxy. Also I found second problem now: bot doesn't unfollow but writes that it do it. Instagram has really improved their defence from frauds like us :rofl:

**Comment by cortesr7324** [comment]
When you said, "Public Proxy", did you got them for free?

**Comment by Victorrussia** [comment]
@cortesr7324 yes he got them for free I suppose. Just write "public proxy" in google and you may get a lot of them but they are not stable. It is better to buy own proxy and don't think about changing them every hour.

**Comment by ugurozturk** [comment]
use https://github.com/instabot-py/instabot.py/issues/887 for tracking in the future
