### ISSUE TITLE
Locations insted of tags?

### ISSUE THREAD

**Issue by patitonav** [instabot-py/instabot.py#811]
I didn't find any issue about this, it's possible to follow and favorite pics, from where it was taken?

Thanks

**Comment by patitonav** [comment]
Anybody have some interest in develop this feature?

**Comment by YuliyaKar** [comment]
Yes, it would be great!
Actually, I think the best option would be the combination of tags/places.

**Comment by juancox** [comment]
yes please!

**Comment by JoeyLyman** [comment]
this would be soo killer.  Any news on it?

**Comment by andrewsegas** [comment]
Guys, Here we have follow and like by location + user interface
https://github.com/andrewsegas/instaboost

**Comment by patitonav** [comment]
I am testing the location feature and seems to work well. It would be great if you could merge it into master.

**Comment by andrewsegas** [comment]
@patitonav i tried here but they didn't accept, anyway, that another project is already with different things, and User interface as well

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
