### ISSUE TITLE
Error in atexit._exitfuncs

### ISSUE THREAD

**Issue by GamingBabe** [instabot-py/instabot.py#813]
![img_20171104_114716](https://user-images.githubusercontent.com/33370695/32404752-eee8dad8-c156-11e7-9650-0b66439675d0.png)

Error occurs after random running time (sometimes 10 minutes and sometimes 2 hours). I use a raspberry pi with raspbian jessie. Can anyone help?

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
