### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by Starfirefox** [instabot-py/instabot.py#814]
Recently I've been getting a lot of Error 400s for liking pictures (The bot runs fine for like 1-2 days and gets errors unless I let it rest for like 2 days) even though I lowered the like amount. The following and unfollowing still seem to work fine though. Does anyone know a fix to this other than waiting each time

**Comment by taradell** [comment]
take a look here: #751

**Comment by ugurozturk** [comment]
use https://github.com/instabot-py/instabot.py/issues/887 for tracking in the future
