### ISSUE TITLE
EASY FIX of NoneType error

### ISSUE THREAD

**Issue by indiespace** [instabot-py/instabot.py#818]
Go to Line 37 on feed_scanner.py  

You will see some of the code is on the line underneath. Just bring it back up and save.

That should fix that problem!

**Comment by karnac** [comment]
Also lines 24 and 26, as well as some other src files. I've tried this and it seems to still be occurring.

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
