### ISSUE TITLE
HELPPP >> instabot close automatically

### ISSUE THREAD

**Issue by edwardium** [instabot-py/instabot.py#823]
hi 
i run the example.py it load work and everything fine but after around 30-50 min close automatically.!!!
 and i have to run it again !
and same issue .

**any one can help me plz ?**

**Comment by JonasE99** [comment]
i have the same problem :/

**Comment by edwardium** [comment]
any one can help here ?

**Comment by Blacksmith1234** [comment]
Guys, read before asking.You have to create a new .bat or cmd file. Here is the code in the middle of the page---->  #815

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
