### ISSUE TITLE
InstaBot API Follow not Working

### ISSUE THREAD

**Issue by devParry** [instabot-py/instabot.py#831]
Hi,

I am using InstaBot Python API its working fine for Instagram Likes,  But if i set only follow then nothing is happened. I tried a lot to fix this but did not get Proper solution. Could any one please let me know where i am worng in the code ? Here is  my code :

`bot = InstaBot(
				login			=	"xyz",
				password			=	"xyz",
				like_per_day		=	0,
				comments_per_day	=	0,
				tag_list			=	'',
				tag_blacklist		=	["rain","thunderstorm"],
				user_blacklist		=	{},
				max_like_for_one_tag=	50,
				follow_per_day		=	10,
				follow_time			=	1 * 60,
				unfollow_per_day	=	0,
				unfollow_break_min	=	120,
				unfollow_break_max	=	180,
				log_mod				=	0,
				proxy				=	"",
				comment_list=[
								["photo", "picture", "pic", "shot", "snapshot"],
							],
				# Use unwanted_username_list to block usernames containing a string
				## Will do partial matches; i.e. "mozart" will block "'legend_mozart"
				### "free_followers" will be blocked because it contains "free"
				unwanted_username_list=[
					"second", "stuff","art", "sex", "food", "blog",
				],
				unfollow_whitelist=["example_user_1", "example_user_2"]
			)`

Please Help me to Fix my problem

Thanks in advance.

**Comment by forevermirin94** [comment]
For some reason the bot won't allow you to just follow only people, you need to use the like per day function and the follow per day function together. Also make sure that the amount set for the likes is higher than the  follow per day amount, so like_per_day(example: 500) > follow_per_day(example: 400).

**Comment by devParry** [comment]
Thanks For your reply. 
Could you please let me know is it possible to modify the bot in  such a way it **Likes** and **Follows** separately ?

**Comment by devParry** [comment]
@forevermirin94  i got the solution to make it workable for separately follow only a  time here is under given  code you have to just find the Function  Name As "new_auto_mod_follow" and replace with under given Function 

` def new_auto_mod_follow(self):
        if time.time() > self.next_iteration["Follow"] and \
                        self.follow_per_day != 0 and len(self.media_by_tag) > 0:
            if self.media_by_tag[0]["owner"]["id"] == self.user_id:
                self.write_log("Keep calm - It's your own profile ;)")
                return
            log_string = "Trying to follow: %s" % (
                self.media_by_tag[0]["owner"]["id"])
            self.write_log(log_string)

            if self.follow(self.media_by_tag[0]["owner"]["id"]) != False:
                self.bot_follow_list.append(
                    [self.media_by_tag[0]["owner"]["id"], time.time()])
                self.next_iteration["Follow"] = time.time() + \
                                                self.add_time(self.follow_delay)
            del self.media_by_tag[0]`
