### ISSUE TITLE
;0000000000

### ISSUE THREAD

**Issue by cortesr7324** [instabot-py/instabot.py#835]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**

**Comment by Dervock** [comment]
This section is for issues regarding Instabot.py. 
Please don't post stuff that doesn't regard an actual issue with the bot. Thank you.

**Comment by cortesr7324** [comment]
Sorry, I'll post this in the right fucking place ;)

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.
