### ISSUE TITLE
bot writes "followed x" but no effect on the account?

### ISSUE THREAD

**Issue by drovid** [instabot-py/instabot.py#836]
instabot acts like it followed and logs a confirmation, but instagram.com page doesn't agree. basically, the bot is bullshitting to me... wtf?

**Comment by ugurozturk** [comment]
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.

**Comment by HenryCooperGithub** [comment]
Since there was no huge outcry on this issue , I assume your IP is follow-blocked . Try the same library on a different account and your home IP .

If this issue persists , please re-open a new issue and let us know .
