### ISSUE TITLE
Not liked always

### ISSUE THREAD

**Issue by Tifiloow** [instabot-py/instabot.py#837]
Hello, i hope my English will be correct, i'm french. 
So, When i start this script on Windows or cent os, it's work, or it's bug.
So i can see all time: [
![capture](https://user-images.githubusercontent.com/27230578/33490105-486ae9d8-d6b6-11e7-9b49-6ce906898ae5.PNG)
](url)

It work few seconds, and stop ! It write not liked: 400... after this messsages, i need to restart(and it crash directely)
Thanks for your help
Have a nice day

**Comment by ugurozturk** [comment]
i updated some code and it looks like fixed. The program working for 2 days now. There is not this error. Check my repo https://github.com/ugurozturk/instabot.pyV2

**Comment by ugurozturk** [comment]
use https://github.com/instabot-py/instabot.py/issues/887 for the tracking in the future
