### ISSUE TITLE
Unfollow Not work

### ISSUE THREAD

**Issue by devParry** [instabot-py/instabot.py#838]
Hi,

I am using InstaBot Python API its working fine for Instagram Likes, follow, individually, But if i set only unfollow then nothing is happened. I tried a lot to fix this but did not get Proper solution. Could any one please let me know where i am wrong in the code ? or something need to change into main **instabot.py** file ? Here is my code :

`bot = InstaBot( login = "xyz", password = "xyz", like_per_day = 0, comments_per_day = 0, tag_list = ["car","jeep","air","earth"] tag_blacklist = ["rain","thunderstorm"], user_blacklist = {}, max_like_for_one_tag= 50, follow_per_day = 0, follow_time = 1 * 60, unfollow_per_day = 10, unfollow_break_min = 120, unfollow_break_max = 180, log_mod = 0, proxy = "", comment_list=[ ["photo", "picture", "pic", "shot", "snapshot"], ], # Use unwanted_username_list to block usernames containing a string ## Will do partial matches; i.e. "mozart" will block "'legend_mozart" ### "free_followers" will be blocked because it contains "free" unwanted_username_list=[ "second", "stuff","art", "sex", "food", "blog", ], unfollow_whitelist=["example_user_1", "example_user_2"] )
`

Please Help me to Fix my problem

Thanks in advance.

**Comment by daz99m** [comment]
use mode=5, that works for me but it only unfollows 24 users and stops

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
