### ISSUE TITLE
Unkown Problem

### ISSUE THREAD

**Issue by Tifiloow** [instabot-py/instabot.py#841]
Hello, actually, i reinitialised my cent os, etc...
But the bot can't work
It write "not like 400..." few times and it's crash and i get the following error(thanks for your help)
Have a nice day ! 
:
 File "example.py", line 79, in <module>
    bot.new_auto_mod()
  File "/bot/instabot.py/src/instabot.py", line 582, in new_auto_mod
    self.new_auto_mod_comments()
  File "/bot/instabot.py/src/instabot.py", line 637, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "/bot/instabot.py/src/instabot.py", line 661, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Trying to unfollow: 3199190791
Unfollow: 3199190791 #1 of 2.
Pausing for 24 seconds... 1 of 2
Logout: likes - 1, follow - 2, unfollow - 1, comments - 1.
Bot work time: 2:04:36.060845
Logout success!
Exception KeyError: KeyError(140250925655872,) in <module 'threading' from '/usr/lib64/python2.7/threading.pyc'> ignored

**Comment by raffg** [comment]
I'm getting almost the same error ("Exception KeyError: KeyError(140136114964224,) in <module 'threading' from"...). The bot works correctly, following, liking, and commenting as expected. I hit Ctrl-C and the bot switches to unfollowing all of the followed accounts. It always fails after unfollowing exactly 1/2 of the followed accounts.

**Comment by GithubProgress** [comment]
"No JSON object could be decoded" looks like a response issue . 

Please update to the most recent version of instabot.py

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
