### ISSUE TITLE
Can't login after password change

### ISSUE THREAD

**Issue by onkaraman** [instabot-py/instabot.py#843]
I changed the password on instagram.com. Now I can't login anymore.

- Starting script, I get a password incorrect message after login.
- I open the app on my phone: Suspicous attempt, yes it was me.
- Login still not working for script.

--------------------------

- Trying again to login with script.
- Confirming attempt with instagram.com.
- Still not success for script.

The new password works for the app and the website though.

Can anybody help?

**Comment by Instaerror** [comment]
https://github.com/instabot-py/instabot.py/issues/842

**Comment by GithubProgress** [comment]
**Most likely related to the Instagram bug that happened 1 month ago .**

Please update to the most recent version of instabot.py

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
