### ISSUE TITLE
stuck in loop: "found whitelist user, starting search again"

### ISSUE THREAD

**Issue by mlasy** [instabot-py/instabot.py#844]
after few hours, the script runs into this infinite loop of                             
"found whitelist user, starting search again"

**Comment by cody151** [comment]
does anyone have a solution??? its making the bot unusable, my bot crashes with the same issues (i have whitelisted 900 people), the bot just keeps searching through and I have to unfollow the people that the bot follwoed for me myself + the bot just keeps looping

**Comment by BlueCoww** [comment]
There must be an exception in the code somewhere generating an infinite loop.

**Comment by GithubProgress** [comment]
Please update to the recent version . If the issues persists please post a full console output and your settings .
