### ISSUE TITLE
Upss user already in ex list - I'm Stuck 

### ISSUE THREAD

**Issue by Scompe** [instabot-py/instabot.py#845]
Hey guys,
I am Stuck at this 

berrypi17 : Get media id on recent feed 
 11.12.2017 17:16
Media in recent feed = 2
======> Get media id by Tag <======
Get media by user success!
============================== 
Upss nowaythatsagirl is already in ex user list... 
==============================
berrypi17 : Get media id on recent feed 
 11.12.2017 17:16
Media in recent feed = 2
======> Get media id by Tag <======
Get media by user success!
============================== 
Upss nowaythatsagirl is already in ex user list... 
==============================

Anyone an idea how to fix it? The bot runs for 2h now and doesn't go on.

**Comment by GithubProgress** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
