### ISSUE TITLE
SH file for restart

### ISSUE THREAD

**Issue by Tifiloow** [instabot-py/instabot.py#847]
Hello,
How i can create a start.sh file for cent os 7 for running instabot and restart it each 5 minutes ? 
Thanks
Asked why ? : Because i find for .bat but not for .sh

**Comment by delminskii** [comment]
@Tifiloow I guess this's not an instabot's issue. Your problem is in bash, not in instabot. Just port your `.bat` script to `.sh` and that's it.

**Comment by Tifiloow** [comment]
@delminskii I did and it didn't work :/

**Comment by GithubProgress** [comment]
As @delminskii mentioned , this is not an instabot issue . Closed .
