### ISSUE TITLE
Cant Login

### ISSUE THREAD

**Issue by amitsahuad** [instabot-py/instabot.py#848]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**
Loginerror

**Comment by eunryeon** [comment]
I have the same error.
Login error! Check your login data!

**Comment by ugurozturk** [comment]
@amitsahuad @eunryeon it can't help. Send your OS info. And detail it, like are you guys using vps from another country that far far away ? Perhaps instagram blocks the login because of security

**Comment by GithubProgress** [comment]
Please re-open a new issue if your problem still exists .

Thanks a lot .
