### ISSUE TITLE
Random Set Comments Instead of Piecemeal Ones

### ISSUE THREAD

**Issue by Thor-Codinson** [instabot-py/instabot.py#849]
Hey all,

Was thinking a better, more natural way of commenting would be to give the bot a set list of predefined strings to chose from. The "piecemeal" style of commenting just seems really fake to me ("This snapshot feels great!" (Who talks like that?)). I was thinking a better way of commenting would be to give the bot some generic comments to choose from randomly such as ("I love this!" or "This is great!" etc etc.) These would be made to sound more natural and less "bot-like". I feel like this should be a relatively small change, maybe just having it rand from a set array instead of concatenating a bunch or randomly pieces from the list. What do you think?

**Comment by RPSPandora** [comment]
Hi, you can edit your example.py
`comment_list=[],`
like this
```
comment_list=[
["I love this","This is great","opening comment","opening comment 2","etc"],
["!","!!","!!!","!!!!",",","!,","!!,","!!! "],
["visit my profile @blabla","follow me @blabla","cek my ig @blabla","middle comment 1","middle comment 2","etc"],
["i'll follow you back","bye","see you","end comment 1","end comment 2","etc"],
],
```

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
