### ISSUE TITLE
Follow Specific Users

### ISSUE THREAD

**Issue by yugenchokshi** [instabot-py/instabot.py#850]
Whoever reading this, do respond if you can help me with this. 
How can we make a list of all the users we want to follow? Just specifc users?
And add users to the list, and the bot follows them.

**Comment by ugurozturk** [comment]
@aopiskin tell me, why you want this ? im asking because if you are going to follow spesific users by manuel created list then you can manually follow them by manually too. Without needing bot

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
