### ISSUE TITLE
can not run the bot on my android smartphone

### ISSUE THREAD

**Issue by IshakBen** [instabot-py/instabot.py#851]
everytime i try to run the bot on my smartphone using Qpythone3 it shows me this:
ImportError: No module named requsest
p.s: the Bot works perfectly on my pc

**Comment by ugurozturk** [comment]
@IshakBen  "No module named requsest" So do install the module named request. I dont know how is it works in Qpythone3. But the error is so clean. "No module named requsest"

**Comment by ugurozturk** [comment]
on pc it would work like : "pip install request" done

**Comment by GithubProgress** [comment]
This issue is not related to the library . closed .
