### ISSUE TITLE
Except on get_media

### ISSUE THREAD

**Issue by knokkelmanns** [instabot-py/instabot.py#852]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**
hi there.
last days i see the issue in console. 
![2017-12-22_10-31-03](https://user-images.githubusercontent.com/31856126/34291290-41a58d66-e704-11e7-8606-5ee460cb9dbc.png)
new photos by tag is there, but does not set the bot Like
what could be the problem?

**Comment by knokkelmanns** [comment]
bot = InstaBot(
    login="",
    password="",
    like_per_day=600,
    media_max_like=20,
    media_min_like=0,
    tag_list=['tags'],
    tag_blacklist=['free'],
    user_blacklist={},
    max_like_for_one_tag=50,
    log_mod=0,
    proxy='')
bot.auto_mod()

**Comment by knokkelmanns** [comment]
no one has encountered such a problem?

**Comment by ugurozturk** [comment]
@knokkelmanns check my repo https://github.com/ugurozturk/instabot.pyV2 it might help you. I dont remember if i fixed this or not.

**Comment by chriotte** [comment]
I'm having the same problem, the bot has been working for months without any problems

**Comment by wkox** [comment]
C:\Users\Juuuice\Desktop\instabot.pyV2-masterv2>python example.py
Traceback (most recent call last):
  File "example.py", line 9, in <module>
    from check_status import check_status
  File "C:\Users\Juuuice\Desktop\instabot.pyV2-masterv2\src\check_status.py", line 3, in <module>
    from .user_info import get_user_info
ImportError: attempted relative import with no known parent package

C:\Users\Juuuice\Desktop\instabot.pyV2-masterv2>

PLEASE HELP

**Comment by enriqueg** [comment]
@ugurozturk
Could you please help me, I got this:
python example.py
Traceback (most recent call last):
File "example.py", line 9, in
from check_status import check_status
File "/Users/MC/instabot.pyV2-masterv2/src/check_status.py", line 3, in
from .user_info import get_user_info
ImportError: attempted relative import with no known parent package

It seems that you know how to fix it, could you just change the lines in the original script (not V2)

**Comment by wkox** [comment]
@enriqueg Im having the exact same issue as you. Please let me know if you find a fix. and I'd perfer if he could change the V2 script.

**Comment by enriqueg** [comment]
@wkox I got it working! 

In each file remove the point before each module 
from .user_info import get_user_info
should be: from user_info import get_user_info

do it in all files! 

maybe there is an smarter way but I don't know anything about Python..

**Comment by wkox** [comment]
@enriqueg I'm new to this site, where do I get the ZIP file at?

**Comment by dothebernny** [comment]
example please?

**Comment by enriqueg** [comment]
@wkox https://github.com/enriqueg/SomeHelp

**Comment by enriqueg** [comment]
Just put these in /src..(if you like inspect them)

**Comment by petermirmo** [comment]
Definitely a bug in instabot. The bug is in instabot.py, on line 322. The 'tag' cannot be found

**Comment by petermirmo** [comment]
I feel like instagram just changed the name of the 'tag' index. Anyone know what the 'tag' index was?

**Comment by leandrodlorenzo** [comment]
I have the same problem, I have hours looking for the solution "Except on get_media!"

**Comment by leandrodlorenzo** [comment]
@enriqueg I have this problem en your code, can you help me?

Traceback (most recent call last):
  File "example.py", line 73, in <module>
    bot.new_auto_mod()
  File "instabot.py", line 691, in new_auto_mod
    self.new_auto_mod_comments()
  File "instabot.py", line 758, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['code']) == False:
KeyError: 'code'

**Comment by alyysaafan** [comment]
@ugurozturk your bot is working but actually i made the following time 6*60*60 but the bot keep unfollow people after 2 or 3 minutes , any solutions?

**Comment by enriqueg** [comment]
@leandrodlorenzo I included now all code in the zip jus fill login and password

**Comment by abhinavpanse** [comment]
![capture](https://user-images.githubusercontent.com/20023085/34519574-aed2fedc-f0aa-11e7-9b8a-b3f7f2e185cd.JPG)

same problem..... no solution till now...

**Comment by wkox** [comment]
@enriqueg I have this same messagge now Traceback (most recent call last):
  File "example.py", line 73, in <module>
    bot.new_auto_mod()
  File "C:\Users\Juuuice\Desktop\instabot.py-\src\instabot.py", line 689, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "C:\Users\Juuuice\Desktop\instabot.py-\src\instabot.py", line 749, in new_auto_mod_unfollow
    self.auto_unfollow()
  File "C:\Users\Juuuice\Desktop\instabot.py-\src\instabot.py", line 806, in auto_unfollow
    current_id = username_row[0]

**Comment by abhinavpanse** [comment]
maybe use python3 insted of python

**Comment by ugurozturk** [comment]
@wkox i dont tracking this repo so much. If you find any error in my repo, create a issue in my own. Somebody did report and i did fix. You can get new clone of https://github.com/ugurozturk/instabot.pyV2

**Comment by ugurozturk** [comment]
@abhinavpanse check my repo https://github.com/ugurozturk/instabot.pyV2

**Comment by wkox** [comment]
@ugurozturk just tried that exact version and here is the error message
  File "example.py", line 76, in <module>
    bot.new_auto_mod()
  File "C:\Users\Juuuice\Desktop\instabot.pyV2-masterv2\src\instabot.py", line 688, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "C:\Users\Juuuice\Desktop\instabot.pyV2-masterv2\src\instabot.py", line 749, in new_auto_mod_unfollow
    self.auto_unfollow()
  File "C:\Users\Juuuice\Desktop\instabot.pyV2-masterv2\src\instabot.py", line 806, in auto_unfollow
    current_id = username_row[0]
TypeError: 'bool' object is not subscriptable

**Comment by ugurozturk** [comment]
@wkox please open new issue on my repo for feature tracking. I got the error and going to fix it as soon as possible

**Comment by enriqueg** [comment]
@wkox  as @abhinavpanse  said use python version 3

Enriques-MBP:~ MC$ python
Python 3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 12:04:38)

**Comment by enriqueg** [comment]
@wkox please test @ugurozturk version I think he fixed it!!

**Comment by GithubProgress** [comment]
**Removed all comments which are not related to instabot.py** 

Please update to the most recent version of instabot.py

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
