### ISSUE TITLE
feature: Interact with followers of target account

### ISSUE THREAD

**Issue by remifreyo** [instabot-py/instabot.py#853]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**
Hey Guys,

Sorry i'm new to GitHub and couldn't find a place to leave comments...if there's a better place for this please let me know! 

I have a suggestion for a new feature in which instabot can scan the followings/followers of a desired user and then interact with that list (like, follow comment). Ex. Sprite could scan Pepsi's followers and then like and comment on those user's posts. Is this possible already? Thanks!

**Comment by aruser1** [comment]
If you are a coder and know how to do this then pull a request in pull request tab, thats the correct place.
this issues page is for problems mostly for newbies

**Comment by ugurozturk** [comment]
Duplicate https://github.com/instabot-py/instabot.py/issues/205
