### ISSUE TITLE
urgent! "found whitelist user: starting search again" loop within the first few minutes -bot is unusable!

### ISSUE THREAD

**Issue by cody151** [instabot-py/instabot.py#854]
**READ OTHER ISSUES BEFORE POSTING A NEW ONE**
does anyone have a solution??? its making the bot unusable, my bot crashes (i have whitelisted 900 people), the bot just keeps searching through and I have to unfollow the people that the bot follwoed for me myself, the bot just keeps looping trying to find a non whitelisted user which there should be many since the bot followed many people by itself. Any ideas?

**Comment by GithubProgress** [comment]
Please update to the most recent version of instabot.py

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
