### ISSUE TITLE
Follow and comment feature broken!

### ISSUE THREAD

**Issue by cody151** [instabot-py/instabot.py#855]
So the follow feature is broken, the whitelist doesn't work, it leads to "found whitelist user: searching again" loop and removing the whitelist users so that the bot doesn't get stuck again results in the bot unfollowing people that follow me back. I've tried the other modes aswell, mode 2 also gets stuck in a loop.

The comment feature is also broken, after a few minutes, the bot logs out and stops due to issue with commenting.

These features are broken and I've switched off follows and unfollows by setting to 0, same goes for comments. Does anyone have a fix for either whitelist issue or the unfollowing friends issue or the comments issue?

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
