### ISSUE TITLE
login error connection lost error on vpn

### ISSUE THREAD

**Issue by ekaggrat** [instabot-py/instabot.py#856]
i use a vpn to connect to instagram.. i tried the instabot and it worked wonderfully at first. but i halted the app 4 times to update the list of tags. on the fifth try it gave a failed login error. also the app on my phone gave me a suspicious activity report. At first i thought the error must be because of multiple device logins.. but i logged off everything and the error still persists..

anybody having issues with vpns. or is it caused because of crashing the app and restarting too frequently?
thanks

**Comment by GithubProgress** [comment]
This was related to some Instagram updates a month ago . Should be resolved . Open a new issue if the problem persists .
