### ISSUE TITLE
Proxy configuration

### ISSUE THREAD

**Issue by focamonca** [instabot-py/instabot.py#857]
I read all the thread about proxies but I still can't make it works.
How should I set the proxy? should I leave the ' ' ?
This is what I tried:

- went to https://free-proxy-list.net/
- Grabbed one with low ping and high uptime
- wrote: `proxy='165.227.186.129:8080` (just an example of proxy ip + port)

but the bot is stuck on `try to login into username`

what am I doing wrong?

**Comment by knokkelmanns** [comment]
proxy has a long response time or proxy is banned. I had this problem too. I fixed this problem by selecting another proxy

**Comment by focamonca** [comment]
I tried with almost 5-6

Il 26 dic 2017 16:39, "knokkelmanns" <notifications@github.com> ha scritto:

**Comment by focamonca** [comment]
If I add the proxy I have an error at line 57.. Damn.. No sense

CHECK the pic https://ibb.co/mb7RGb

**Comment by GithubProgress** [comment]
This looks like a public proxy . If the problems still persist please update to the newest version and post a full console output + your settings .
