### ISSUE TITLE
Except on get_media! and 400 error

### ISSUE THREAD

**Issue by aruser1** [instabot-py/instabot.py#864]
As the title says, I'm getting it Except on get_media! error. But it got resolved automatically but why do I get that error in the first place? what does it mean?
before getting this error , I got cannot liked : 400 ERROR! please explain this

**Comment by ugurozturk** [comment]
@aruser1 first of all im not sure about that. I was also gettin this error sometimes. Then i changed headers to make it work. And time passed, i dont getting this error anymore. Yet i am not sure if it is about changing my headers or it is because my instagram account became old. 

Here you go and check by yourself : https://github.com/ugurozturk/instabot.pyV2

**Comment by chriotte** [comment]
I'm getting the same error, the bot has been working for months just fine

**Comment by enriqueg** [comment]
stopped here as well

**Comment by S1lv10Fr4gn4n1** [comment]
stopped a few hours here

**Comment by manguszta** [comment]
Same here.

**Comment by AngelPadronR** [comment]
same too, "Except on get_media!" error

**Comment by manguszta** [comment]
Solution:

> 
> Instagram changed the syntax of their API a bit, so you need to make some small changes to the instabot.py file to accommodate for these changes. 
> 
> You can download the file here and just replace the **instabot.py** in the src folder:
> https://github.com/MaxParadiz/instabot.py/blob/patch-1/src/instabot.py
> 
> And you can see the specific changes on **instabot.py** here:
> https://github.com/MaxParadiz/instabot.py/commit/f0c3b2b9303e08050ab57e2f33fd8a7ee40f515a#diff-91adcadbdf4fad3eb76d66f30bfba3af

source: [https://www.facebook.com/groups/instabot/permalink/440877769648300/?comment_id=440992706303473&reply_comment_id=441000719636005&comment_tracking=%7B%22tn%22%3A%22R5%22%7D](url)

**Comment by mmming** [comment]
@manguszta that fixed it, thank you!

**Comment by javier2k2** [comment]
@manguszta with this instabot.py file the error Except on get_media has gone, but Not liked:400 still happening

**Comment by ugurozturk** [comment]
@javier2k2 https://github.com/ugurozturk/instabot.pyV2 can you test my repo for the not liked 400 ? and comment in https://github.com/ugurozturk/instabot.pyV2/issues/3

**Comment by aruser1** [comment]
+manguszta there is no download zip button in that MaxParadiz/instabot.py fork. Do we have to copy and replace the texts inside the instabot.py ?

**Comment by remyx11** [comment]
Your solution worked @manguszta, however my bot runs very very slow right now.. Someone else having this issue?

**Comment by javier2k2** [comment]
@ugurozturk Thanks I've tried using your repo but still getting Not Liked: 400

**Comment by ugurozturk** [comment]
@javier2k2 did you try the new one or old one ?

**Comment by bboy519** [comment]
File in instabot zip not updated. Have to download the patch manually

**Comment by AngelPadronR** [comment]
@javier2k2 when i was getting "Not Lided :400" ive found something, the "400 erro" it´s because your ip have exceded the time of follow or likes per day, i was try use it in paython online but so much ppl was using the same and getting error 400, after ive installed an virtual machine on my mac and istalled bot and problem was solved...

**Comment by jonasds10** [comment]
@manguszta hey thanks but now I'm getting this error "Couldn't find caption - not liking", how can I fix that, plz anyone help! <3

**Comment by javier2k2** [comment]
Now is working, was a shadowban, thanks!

One question, in your repo, follow and unfollow feature and mode 2 are working? Because some months ago I moved my main account to Instapy because the unfollow feature didn't work.

**Comment by javier2k2** [comment]
@ugurozturk Now is working, was a shadowban, thanks!

One question, in your repo, follow and unfollow feature and mode 2 are working? Because some months ago I moved my main account to Instapy because the unfollow feature didn't work.

**Comment by ugurozturk** [comment]
@javier2k2 everything looks working but im not sure about modes. I do only support mode 0.

**Comment by focamonca** [comment]
Even if I do this mod i still get Except on get media

**Comment by azerty800** [comment]
Hello everyone, I get this huge error: `Traceback (most recent call last):
  File "/Users/Jean-Charles/Desktop/watch/instabot.py-master/watchfan.py", line 78, in <module>
    bot.new_auto_mod()
  File "/Users/Jean-Charles/Desktop/watch/instabot.py-master/src/instabot.py", line 576, in new_auto_mod
    self.new_auto_mod_comments()
  File "/Users/Jean-Charles/Desktop/watch/instabot.py-master/src/instabot.py", line 631, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['comments_disabled']) == False:
  File "/Users/Jean-Charles/Desktop/watch/instabot.py-master/src/instabot.py", line 655, in check_exisiting_comment
    all_data = json.loads(check_comment.text)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

Can anyone help me about this? Thanks

**Comment by ugurozturk** [comment]
@azerty800 on my repo we worked for it and fixed it. the main problem is python 2 and old version requests module. And if a instagram user changes visibilty of image then this is happening. Anyway i did fix it in my repo. https://github.com/ugurozturk/instabot.pyV2

**Comment by ugurozturk** [comment]
it is fixed, if you still have the error. feedback or open a new issue

**Comment by visualpropaganda** [comment]
Hello,

I have managed to install the bot, but now i get the following error, when trying to run 'example.py':

`Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/me/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/me/Desktop/instabot.py-master/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/Users/me/Desktop/instabot.py-master/src/userinfo.py", line 5, in <module>
    import requests
ImportError: No module named requests`

Any help appreciated

**Comment by aruser1** [comment]
Replace your example file with any other working one

**Comment by visualpropaganda** [comment]
Thank you arser1,

but where would I find a working one?
I already downloaded 3 repos (the original + 2 branches).None seem to work.

**Comment by ugurozturk** [comment]
@visualpropaganda all of them is working. Better you google or search at repo's issues. I have the answer you looking for and it is so simply. Yet i want to give you tips. It is not related error of this project.

**Comment by visualpropaganda** [comment]
Well @ugurozturk that is indeed very helpful. Never thought of doing a google search. Wonder how I got here.

**Comment by ugurozturk** [comment]
@visualpropaganda Well probabby you are didn't so i said that because the question is answered more than 20 times. In closed issues. just do some search.

**Comment by visualpropaganda** [comment]
@ugurozturk solved it
