### ISSUE TITLE
Excecept on get_media issue

### ISSUE THREAD

**Issue by AngelPadronR** [instabot-py/instabot.py#867]
today 02/01/2018 i get this problem after bot loggin, when try to get "#" said "Except on get_media!" how i can fix that? 

Thanks!

**Comment by CaptainRiley** [comment]
This problems happens because Instagram changed parts of their code so the bot has to be rewritten so everything will work. Just wait a few days and someone will change it.

**Comment by arhajati** [comment]
Started facing the same "Except on get_media" issue from the past 6 hours! I guess Instagram changed something.

**Comment by ugurozturk** [comment]
i fixed it on my repo @arhajati @CaptainRiley @AngelPadronR https://github.com/ugurozturk/instabot.pyV2 and it seems working for me now. Open issue if you find an error.

**Comment by enriqueg** [comment]
@ugurozturk 
Could you please help me, I got this:
 python example.py
Traceback (most recent call last):
  File "example.py", line 9, in <module>
    from check_status import check_status
  File "/Users/MC/instabot.pyV2-masterv2/src/check_status.py", line 3, in <module>
    from .user_info import get_user_info
ImportError: attempted relative import with no known parent package

**Comment by Vizzyy** [comment]
@ugurozturk thanks, these changes worked for me.

**Comment by raffg** [comment]
@ugurozturk I'm getting an error on line 669 (line 760 in your code) 
```
and self.check_exisiting_comment(self.media_by_tag[0]['node']['code']) == False:
KeyError: 'code'
```

**Comment by heydanaye** [comment]
@ugurozturk I having some issues using your code. I opened an issue on your page! Thanks!

**Comment by ugurozturk** [comment]
@raffg @heydanaye i fixed it now. https://github.com/ugurozturk/instabot.pyV2/commit/1aefb0af369beac5d603cbc1255277b661b7f84f i am not using comment feature so i didn't realize it

**Comment by egurdal-reidin** [comment]
@ugurozturk adamsın! :)

**Comment by Jokobi** [comment]
I had the same issues "Except on get_Media!" .  Found a solution 
https://github.com/instabot-py/instabot.py/issues/864#issuecomment-354966425 
and check out @manguszta comment and his link https://github.com/MaxParadiz/instabot.py/blob/patch-1/src/instabot.py
Hope i can help you :)

**Comment by KalanaPerera** [comment]
Hi Guys, 

I have updated Instagram Latest API changes, All functionalities are working. Tested

Commit : https://github.com/KalanaPerera/instabot.py/commit/8b6d3e1a5f429376e956f72e51ba9511d39850a6

Repo : https://github.com/KalanaPerera/instabot.py

👍

**Comment by Sudge3** [comment]
@KalanaPerera when i use your script my bot tells me "came to here" and then stops working.

**Comment by volkv** [comment]
@ugurozturk your fork is awesome! thanks man!

**Comment by ugurozturk** [comment]
@volkv  Thank you. Please open issue on my repo if you find any problem

**Comment by KalanaPerera** [comment]
@Sudge3 its working for me, still my bot is running. if this not working for you take @ugurozturk  fork it will work.

Thanks.

**Comment by Leastham2** [comment]
this has has been updated in the original repo, re git

**Comment by ugurozturk** [comment]
@Leastham2 nope, original repo is not updated for 26 days.

**Comment by Sudge3** [comment]
@KalanaPerera nope the other script is also not working. I don't know why. Yesterday I had absolutely no problem with the original script

**Comment by eastcoastboys** [comment]
@ugurozturk So far it seems to be working good, I noticed that it has created a file called "follows_db.db" and "errors.log" I am assuming that these are DB logs for the follows the bot has done? How would I access these logs?

Thank you so much for your contribution!!!

**Comment by ugurozturk** [comment]
@eastcoastboys a program called "db browser for sqlite" can open and view it. I am using it.

**Comment by AngelPadronR** [comment]
@ugurozturk your new update it´s now working for me! Thanks so much, you saved me!

**Comment by AngelPadronR** [comment]
@ugurozturk you can tell me whats different your instabot version than the original? what new function have added?

**Comment by ugurozturk** [comment]
@AngelPadronR check the readme.md

**Comment by janmejay23** [comment]
@ugurozturk thanks bro u saved my day

**Comment by gwest123** [comment]
@KalanaPerera Im still getting a "Not Liked: 400" error, any ideas?

**Comment by arhajati** [comment]
@gwest123 Try waiting for 8-10 hours, may be you are shadowbanned.
Also before running the bot try using this command.

> pip install -r requirements.txt

maybe something from your requirements is missing!

Let me know what happens. Peace!

**Comment by arhajati** [comment]
@ugurozturk Thanks mate your repo works good!
Thanks for adding the date and time function!

**Comment by gwest123** [comment]
@arhajati Im having the same issue with @ugurozturk repo too, will leave it for 10 hours and see. Odd because if I restart the bot the first like occasionally works.

**Comment by arhajati** [comment]
@gwest123 I think it's a shadow ban. Wait for 8-10 hours before you use it again.

**Comment by mighty2nyce** [comment]
@ugurozturk hey does your comment feature work??

**Comment by ugurozturk** [comment]
@mighty2nyce i dont use the comment feature but it works they say. I did edit as json structure. You can test it and if you find an error just open issue

**Comment by ugurozturk** [comment]
@gwest123 there several problems causing error 400. I think it is , if the user is new and does alot like/follow or it activating as disturbing people. Same people, same tags same photos. I was also getting this error before, while using my repo and 2month passed.. Everything looks pretty fine now.

**Comment by janmejay23** [comment]
@mighty2nyce its working perfectly  . try to keep number of comment limited and change list of words so that instagram will not find pattern in your comment

**Comment by mighty2nyce** [comment]
janmejay23 hey its not working for me idk what going on. im changing the comments from 0 to 25 and i changed the list of comments and its not working. what should i do?

**Comment by janmejay23** [comment]
@ugurozturk  i think we should randomize the time interval between like and follow so that it will be hard for instagram algo to shortlist account in spam

**Comment by ugurozturk** [comment]
@mighty2nyce if my repo is not working then please open an issue in my repo.

**Comment by janmejay23** [comment]
@mighty2nyce  
![screenshot from 2018-01-04 17-41-07](https://user-images.githubusercontent.com/30259891/34562925-7b7fd786-f176-11e7-90c7-9b361e4b2db9.png)

simply change "comments_per_day= .....," in example.py

**Comment by gwest123** [comment]
@ugurozturk My account is several years old, and been running the bot for 2 months without an issue until now, do you suggest changing my tags?

**Comment by mighty2nyce** [comment]
@ugurozturk i downloaded yours and it works perfectly fine. i had someone elses and it wasnt working. thanks guys

**Comment by mighty2nyce** [comment]
@janmejay23 its working now. but do you know how to prevent it from logging out so quick. it worked well for about 5 minutes then logged me out

**Comment by janmejay23** [comment]
@mighty2nyce  from recent change what the conclusion i came to is instagram is now going to strict its policy so for safety reason try to open instagram in browers on same device and just confirm that you are not a bot . i think that may solve the problem

**Comment by gwest123** [comment]
@ugurozturk Changing my tags didnt work, ill let the account rest for a few hours.

**Comment by mighty2nyce** [comment]
@janmejay23 is okay to run the bot on my computer and be signed in on my phone. and is it just me or is it everybodys bot, they like, comment, follow and unfollow really slow?

**Comment by janmejay23** [comment]
no need to logout of phone just open in in pc browser and verify .you can also run it on phone also use qpython it and install required libraries through pip i have not done it till now their might be some changes

**Comment by mighty2nyce** [comment]
so i can run the bot on my phone?? 
And have you ever got the message 
04.01.2018_07:42 Trying to unfollow #1: 
04.01.2018_07:42 Looks like there is nobody to unfollow.

i dont know

**Comment by janmejay23** [comment]
@mighty2nyce your account might be new its my suggestion try to follow few people with this account and upload some post so that it will look like genuine account

**Comment by H4Ck3d-W0lf** [comment]
@janmejay23  How can i run the script with qpython ?

**Comment by fveitsi** [comment]
@ugurozturk Hi, I downloaded your repo and it logs out after a while. First time after couple likes and second time after 29 likes and third time after 96 likes.

**Comment by ugurozturk** [comment]
@fveitsi you do better open new issue on my repo. For future track. I need details and i can't track errors here

**Comment by fibercool** [comment]
I'm getting the same error when trying to like media using the ugurozturk version, example:

 06.01.2018_08:46 Trying to like media: 168597563757317xxx
06.01.2018_08:46 Not liked: 400
06.01.2018_08:48 Trying to like media: 1685975536062951xxx
06.01.2018_08:48 Not liked: 400

it was working fine before the api update of few days ago

Any ideas?

**Comment by focamonca** [comment]
@janmejay23 change what?

**Comment by taradell** [comment]
@ugurozturk hi man! i read about your version of the bot and i like the idea of the database. does commenting work? i read that the feature was not working. thanks

**Comment by taradell** [comment]
@ugurozturk tnx mate!

**Comment by GithubProgress** [comment]
Please update to the recent version .
