### ISSUE TITLE
need some help with this.

### ISSUE THREAD

**Issue by SivertO** [instabot-py/instabot.py#871]
C:\Users\siver\Downloads\instabot.py-master>python BOT.py
Traceback (most recent call last):
  File "BOT.py", line 12, in <module>
    from instabot import InstaBot
ImportError: cannot import name 'InstaBot' 

Yes I have tried to do this:
import os
import sys
import time

sys.path.append(os.path.join(sys.path[0], 'src'))

**Comment by ugurozturk** [comment]
You have problem via example.py file. So create new one as https://github.com/instabot-py/instabot.py/blob/master/example.py it says. Still be awere this repo is not working right now. I noticed Chipwolf closed a issue today. So Might they gonna fix it soon. Alternatifly, check my repo https://github.com/ugurozturk/instabot.pyV2

**Comment by SivertO** [comment]
do i need to do something with the lisence??

**Comment by GithubProgress** [comment]
Please update to the recent version . If the problem persists please do the following

- Use the example.py
- Attach full console output
- Give us your settings
