### ISSUE TITLE
Console is closed after about 10 min and the Bot is not working anymore

### ISSUE THREAD

**Issue by Jokobi** [instabot-py/instabot.py#873]
Everytime when i start the bot (mode 1,2,3,4,5), the bot is running for about 10-15min and the console close and the bot is stopped.

**Comment by evrpt** [comment]
I believe the bot closes if it reaches its max likes per day. Check that.

**Comment by ugurozturk** [comment]
@evrpt  it is not closing because of that

**Comment by lucasarana** [comment]
Origin master is not working anymore, you should consider fixing it yourself or forking from someone who already fixed it. I guess there are no very active owners.

**Comment by lucasarana** [comment]
you can use @ugurozturk fork

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/issues/864#issuecomment-355558262 so yeah i am not sure about modes. Yet the algorithm works pretty fine so i think you dont need the modes.

**Comment by Jokobi** [comment]
I Had to give me telephone number...

**Comment by Jokobi** [comment]
I Had to give me telephone number...

**Comment by Jokobi** [comment]
I Had to give me telephone number...

**Comment by Jokobi** [comment]
I Had to give me telephone number...

**Comment by GithubProgress** [comment]
Problem seems to be fixed according to @Jokobi 's response
