### ISSUE TITLE
Is this project actively maintained?

### ISSUE THREAD

**Issue by pablosproject** [instabot-py/instabot.py#875]
Hi, I am using this project since a long time and now I'm seeing a trend: there were some changes to the Instagram API and there are lots of pull requests to fix this issue that are not merged. This will force people to move to other forked repos, and lose the knowledge and the community sense around this one.

Is there any way the maintainers of this project can give permission to others to maintain this more actively?
I don't want to be polemic, I just want to avoid forking and staying on this repo.

**Comment by jzeferino** [comment]
@artemdumanov @ChipWolf @LevPasha @polaroi8d can you guys help here please?

**Comment by focamonca** [comment]
Please continue working on

**Comment by dimahadgi** [comment]
please do it

**Comment by iceman183** [comment]
I don't know how active it is at the moment but you use this version https://github.com/ugurozturk/instabot.pyV2 - He's actively changing it

**Comment by pablosproject** [comment]
Yes, I know. My point is more if we can make a community on our own or if the owner of this repo has no time to follow it, just give ownership to @ugurozturk or new people that are interested in this and make this project move forward.

Otherwise I agree with you, if we want to move this forward, we'll need to move to the V2 fork.

@cloudreach @LevPasha  @polaroi8d  could you help here?

**Comment by ChipWolf** [comment]
Hey @pablosproject, not sure why you tagged Cloudreach. I'll ping the dev group and figure out what the best way forward is. @ugurozturk hasn't reached out to request collab access to the main repo, I'm sure that'd be acceptable.

**Comment by ugurozturk** [comment]
Yes it is

**Comment by polaroi8d** [comment]
I have no time to managed this repo, so in my opinion, do it.
