### ISSUE TITLE
Get media owner info from post

### ISSUE THREAD

**Issue by Doblanko** [instabot-py/instabot.py#876]
With the new JSON structure, how do we get information about a media owner from a post? Under “owner” there is only “ID”, but any links to get information about the owner require the username. Anyone have any ideas?

**Comment by Doblanko** [comment]
from a post** sorry for the typo

**Comment by ugurozturk** [comment]
in my repo, I did that via instagram official api. https://github.com/ugurozturk/instabot.pyV2/blob/masterv2/src/instabot.py#L397 def get_username_by_user_id(self, user_id):

**Comment by Doblanko** [comment]
Any way without the api?

**Comment by ugurozturk** [comment]
@Doblanko yes you can. From media post you can directly get the owner id and username. in instagram.com/p/(post_code)  there is [ower][username] etc. But if you trying to find the username from tags. You can't directly. So you have to convert media_id to short_code then you can get the info.

**Comment by Doblanko** [comment]
How do you convert media_id to short_code?

**Comment by iceman183** [comment]
@Doblanko Well you will have to write function for it but you don't really need to convert media id to shortcode. I'm using a modified version of @ugurozturk script cause I was too lazy to update all the new json params myself plus he did some nice changes - thanks for that @ugurozturk . Some of my customized function has a separate log with the username and a link to it other than a full log. 

Example 
```
10-Jan-2018 10:08 PM - instausername - Get media id by tag: fadedspirits
10-Jan-2018 10:08 PM - instausername - Liked: https://www.instagram.com/takmisiewidzi #1.
10-Jan-2018 10:08 PM - instausername - Followed: https://www.instagram.com/daphne_aslan #1.
10-Jan-2018 10:08 PM - instausername - Comment: https://www.instagram.com/daphne_aslan #1.
10-Jan-2018 10:10 PM - instausername - Liked: https://www.instagram.com/daphne_aslan #2.
10-Jan-2018 10:10 PM - instausername - Get media id by tag: agameoftones
10-Jan-2018 10:12 PM - instausername - Liked: https://www.instagram.com/thedesertfern #3.
10-Jan-2018 10:14 PM - instausername - Liked: https://www.instagram.com/javierortiz__ #4.
10-Jan-2018 10:14 PM - instausername - Followed: https://www.instagram.com/_c_y_b_e_r__t_r_o_n #2.
10-Jan-2018 10:15 PM - instausername - Comment: https://www.instagram.com/_c_y_b_e_r__t_r_o_n #2.
```
So you just get the shortcode from the media_by_tag itself like this 
`self.media_by_tag[i]['node']['shortcode']`

This works for all the likes, comments and follows and get the username by running this shortcode with the link below and pulling the json params
`https://www.instagram.com/p/[shortcode]/?__a=1`

 And finally extracting the username as such 
`['graphql']['shortcode_media']['owner']['username']`


@ugurozturk  While I have you here, that is if you are reading this comment at all, can you explain the function of "Removing already liked medias". I just saw this on the log and thought I would ask before I start to reverse engineer it. Also if you need any help, please let me know :)

**Comment by ugurozturk** [comment]
@iceman183 removing already liked medias is just as it looks like. I noticed the script just trying to like a media over and over. But you can only like a media once. So i created it to stop this.

**Comment by Doblanko** [comment]
@iceman183 I don't see the ['graphql']['shortcode_media']['owner']['username'] when I run the link. Only comes up with usernames of people who commented

**Comment by Doblanko** [comment]
@iceman183 it seems to work fine in the code, but pulling it up in my browser I can't see the username of the owner

**Comment by iceman183** [comment]
@Doblanko Elaborate on what do you mean because when I open a profile on my browser, I can see the username just fine 
`"username": "space_traveling_101"`

**Comment by HenryCooperGithub** [comment]
**No library issue
No feature request**

If you want me to convert this into a feature request please let me know .
