### ISSUE TITLE
Trying to comment ends the script

### ISSUE THREAD

**Issue by Nicolas-vrcc** [instabot-py/instabot.py#883]
When I put comment_per_day = 0 the script works perfectly fine but when I try to add for example 50 comments per day, the script does this:

Instabot v1.1.0 started at 11.01.2018 11:03:
Trying to login as perledepluiejewelry...
USERNAME login success!Get media id by tag: oceanqueen
Trying to like media: 1689332529225935646
Liked: 1689332529225935646.
Like #1.Trying to follow: 392787772
Followed: 392787772 #1.
Trying to unfollow: 392787772
Unfollow: 392787772 #1 of 1.
Pausing for 26 seconds... 1 of 1
Logout: likes - 1, follow - 1, unfollow - 1, comments - 0.
Bot work time: 0:00:40.372071
Logout success!

I've updated my script with the fix from @MaxParadiz and everything works perfectly except this...

**Comment by GithubProgress** [comment]
The last bigger update is 7 hours ago . Please update .

We do not provide support for other libraries .

If this problem still persists with https://github.com/instabot-py/instabot.py please re-open a new issue .

Thanks a lot !
