### ISSUE TITLE
Attempted relative import in non-package

### ISSUE THREAD

**Issue by mactrash** [instabot-py/instabot.py#886]
Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [X] Searched and checked other issues about my problem
- [X] If have errors.log file and i did upload it

Check One :
- [X] Bug
- [ ] Feature
- [ ] Need Help

## What OS ?
Linux 
## Python Version ?
2x 
## Is it VPS ?
Yes 
### VPS: Is the vps far far away ? Another Country ?
Yes 
- [ ] VPS: Tried the same code via my local pc

## What is your python knowledge vote 0/10

python2.7 example.py 
Traceback (most recent call last):
  File "example.py", line 9, in <module>
    from check_status import check_status
  File "/root/instabot.py-master/src/check_status.py", line 3, in <module>
    from .user_info import get_user_info
ValueError: Attempted relative import in non-package

**Comment by ugurozturk** [comment]
@mactrash Remove your old folder then clone it as a new. Then feedback here again please.

**Comment by mactrash** [comment]
@ugurozturk 
still same

Traceback (most recent call last):
  File "example.py.ORG", line 9, in <module>
    from check_status import check_status
  File "/root/instabot.py-master/src/check_status.py", line 3, in <module>
    from .user_info import get_user_info
ValueError: Attempted relative import in non-package

**Comment by ivanauskas82** [comment]
I have the same issue. If I remove the . in that line, its fail in the next import

**Comment by ugurozturk** [comment]
@mactrash Sorry, i forgot to change example.py default shema. im going to commit new one

**Comment by ugurozturk** [comment]
```
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
```

For now use like this. At the example.py upperlines

**Comment by ugurozturk** [comment]
it must be fixed via https://github.com/instabot-py/instabot.py/commit/159465be6afd07b3b5e19194b96c0628f783dda4

**Comment by mactrash** [comment]
@ugurozturk 

Thanks for the fix, now it can startup and login then error...

12.01.2018_04:42 Get media id by tag: follow4follow
12.01.2018_04:42 Removing already liked medias..
Traceback (most recent call last):
  File "example.py.ORG", line 76, in <module>
    bot.new_auto_mod()
  File "/root/instabot.py-master/src/instabot.py", line 689, in new_auto_mod
    self.remove_already_liked()
  File "/root/instabot.py-master/src/instabot.py", line 710, in remove_already_liked
    if check_already_liked(self, media_id=self.media_by_tag[x]['node']['id']) == 1:
  File "/root/instabot.py-master/src/sql_updates.py", line 43, in check_already_liked
    media_id + "' LIMIT 1)").fetchone()[0] > 0:
sqlite3.OperationalError: near "񐁓񐁌????񐀠򐁘????????񐁓񐁌????????񠀠󰁒????????????????????񐁈񐁒????????????????????????????????????????????????????????????????򐁌򐁍????????": syntax error
12.01.2018_04:42 Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
12.01.2018_04:42 Bot work time: 0:00:10.711709
12.01.2018_04:42 Logout success!

**Comment by GithubProgress** [comment]
Issue has been fixed . Update your files !
