### ISSUE TITLE
159465b remove_already_liked error after login

### ISSUE THREAD

**Issue by mactrash** [instabot-py/instabot.py#888]
Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [x] Searched and checked other issues about my problem
- [x] If have errors.log file and i did upload it

Check One :
- [x] Bug
- [ ] Feature
- [ ] Need Help

## What OS ?
 Linux(detail) 
## Python Version ?
2x 
## Is it VPS ?
Yes 
### VPS: Is the vps far far away ? Another Country ?
Yes 
- [ ] VPS: Tried the same code via my local pc

## What is your python knowledge vote 0/10

```
12.01.2018_04:42 Get media id by tag: follow4follow
12.01.2018_04:42 Removing already liked medias..
Traceback (most recent call last):
File "example.py.ORG", line 76, in 
bot.new_auto_mod()
File "/root/instabot.py-master/src/instabot.py", line 689, in new_auto_mod
self.remove_already_liked()
File "/root/instabot.py-master/src/instabot.py", line 710, in remove_already_liked
if check_already_liked(self, media_id=self.media_by_tag[x]['node']['id']) == 1:
File "/root/instabot.py-master/src/sql_updates.py", line 43, in check_already_liked
media_id + "' LIMIT 1)").fetchone()[0] > 0:
sqlite3.OperationalError: near "񐁓񐁌????񐀠򐁘????????񐁓񐁌????????񠀠󰁒????????????????????񐁈񐁒????????????????????????????????????????????????????????????????򐁌򐁍????????": syntax error
12.01.2018_04:42 Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
12.01.2018_04:42 Bot work time: 0:00:10.711709
12.01.2018_04:42 Logout success!
```

**Comment by ugurozturk** [comment]
@mactrash is it a clean database ?

**Comment by mactrash** [comment]
@ugurozturk yes just unzip the master and put in username / password for test run only

**Comment by ugurozturk** [comment]
@mactrash can you post here follows_db.db file ? it stores usernames you followed and liked medias.

**Comment by ugurozturk** [comment]
@mactrash and please specify your python version, via `python --version`

**Comment by mactrash** [comment]
@ugurozturk Python 2.7.13

**Comment by ugurozturk** [comment]
Tried python 2.7.13 from fresh clone and it worked on windows. And i didn't understand the the part of  `"񐁓񐁌????񐀠򐁘????????񐁓񐁌????????񠀠󰁒????????????????????񐁈񐁒????????????????????????????????????????????????????????????????򐁌򐁍????????": syntax error`

**Comment by mactrash** [comment]
@ugurozturk is the unicode ... issue just guess

**Comment by ugurozturk** [comment]
@mactrash can you test https://github.com/ugurozturk/instabot.py/tree/check_already_liked-fix or change the line sql_updates:43 to `str(media_id) + "' LIMIT 1)").fetchone()[0] > 0:` perhaps if you can try python 3x let me know

**Comment by mactrash** [comment]
Python2.7 result
login success!
12.01.2018_19:18 Get media id by tag: follow4follow
12.01.2018_19:18 Removing already liked medias..
Traceback (most recent call last):
  File "example.py", line 76, in <module>
    bot.new_auto_mod()
  File "/root/instabot.py-master/src/instabot.py", line 689, in new_auto_mod
    self.remove_already_liked()
  File "/root/instabot.py-master/src/instabot.py", line 710, in remove_already_liked
    if check_already_liked(self, media_id=self.media_by_tag[x]['node']['id']) == 1:
  File "/root/instabot.py-master/src/sql_updates.py", line 43, in check_already_liked
    media_id + "' LIMIT 1)").fetchone()[0] > 0:
sqlite3.OperationalError: near "񐁓񐁌????񐀠򐁘????????񐁓񐁌????????񠀠󰁒????????????????????񐁈񐁒????????????????????????????????????????????????????????????????򐁌򐁍????????????": syntax error
12.01.2018_19:18 Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
12.01.2018_19:18 Bot work time: 0:00:11.235059
12.01.2018_19:18 Logout success!

Python3.6 my build have some issue
  Could not find a version that satisfies the requirement requests (from versions: )
No matching distribution found for requests
Need some time to fix

**Comment by ugurozturk** [comment]
@mactrash the result you posted is looks old. `str(media_id)` notice that

**Comment by ugurozturk** [comment]
@mactrash btw you can use go `pip install requests --upgrade` on linux python3x it might be `pip3 install requests --upgrade`

**Comment by mactrash** [comment]
@ugurozturk 

Pythong2.7 test again

login success!
12.01.2018_20:10 Get media id by tag: f4f
12.01.2018_20:10 Removing already liked medias..
12.01.2018_20:10 Trying to like media: 1690631481897265472
Traceback (most recent call last):
  File "example.py", line 76, in <module>
    bot.new_auto_mod()
  File "/root/instabot.py-check_already_liked-fix/src/instabot.py", line 691, in new_auto_mod
    self.new_auto_mod_like()
  File "/root/instabot.py-check_already_liked-fix/src/instabot.py", line 719, in new_auto_mod_like
    if self.like_all_exist_media(media_size=1, delay=False):
  File "/root/instabot.py-check_already_liked-fix/src/instabot.py", line 520, in like_all_exist_media
    status="200")
  File "/root/instabot.py-check_already_liked-fix/src/sql_updates.py", line 58, in insert_media
    media_id +"','"+ status +"','"+ str(now) +"')")
sqlite3.OperationalError: near "󠁉񐁓????򐀠????????????????????????????????????????????????????????????????????????????????𐁖????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????": syntax error
12.01.2018_20:10 Logout: likes - 1, follow - 0, unfollow - 0, comments - 0.
12.01.2018_20:10 Bot work time: 0:00:15.102651
12.01.2018_20:10 Logout success!

**Comment by ugurozturk** [comment]
@mactrash as you see it did pass from line 43, it throwed where used as the same way. Updated the branch you used for the test. You can clone and test it again or you can change the line sql_updates.py:58 `str(media_id) +"','"+ status +"','"+ str(now) +"')")`

**Comment by mactrash** [comment]
@ugurozturk thx and here is the result

login success!
12.01.2018_20:33 Get media id by tag: cute
12.01.2018_20:33 Removing already liked medias..
12.01.2018_20:33 Trying to like media: 1690643042975653064
12.01.2018_20:33 Liked: 1690643042975653064. Like #1.
12.01.2018_20:33 Trying to unfollow #1: 
12.01.2018_20:33 Looks like there is nobody to unfollow.
12.01.2018_20:33 Get media id by tag: f4f
12.01.2018_20:33 Removing already liked medias..
Traceback (most recent call last):
  File "example.py", line 76, in <module>
    bot.new_auto_mod()
  File "/root/instabot.py-check_already_liked-fix/src/instabot.py", line 693, in new_auto_mod
    self.new_auto_mod_follow()
  File "/root/instabot.py-check_already_liked-fix/src/instabot.py", line 736, in new_auto_mod_follow
    if check_already_followed(self, user_id=self.media_by_tag[0]['node']["owner"]["id"]) == 1:
  File "/root/instabot.py-check_already_liked-fix/src/sql_updates.py", line 50, in check_already_followed
    user_id + "' LIMIT 1)").fetchone()[0] > 0:
sqlite3.OperationalError: near "񐁓񐁌????񐀠򐁘????????񐁓񐁌????????񠀠󰁒????????????????????????򀁗????????????????????????????????????????????????????????󀀠󐁉????????": syntax error
12.01.2018_20:33 Logout: likes - 1, follow - 0, unfollow - 0, comments - 0.
12.01.2018_20:33 Bot work time: 0:00:22.917099
12.01.2018_20:33 Logout success!

**Comment by ugurozturk** [comment]
@mactrash i checked the python 2.7.14 realease notes and there was many sqlite updates.. Probabbly the 2.7.13 has some bugs on linux system. Anyway the i made the "probabby" last update now.

**Comment by mactrash** [comment]
@ugurozturk 

Python 2.7.14 android

login success!
12.01.2018_22:00 Get media id by tag: cute
12.01.2018_22:00 Removing already liked medias..
12.01.2018_22:00 Trying to like media: 1690686918416617811
12.01.2018_22:00 Liked: 1690686918416617811. Like #1.
Traceback (most recent call last):
  File "example.py", line 76, in <module>
    bot.new_auto_mod()
  File "/root/instabot.py-check_already_liked-fix/src/instabot.py", line 693, in new_auto_mod
    self.new_auto_mod_follow()
  File "/root/instabot.py-check_already_liked-fix/src/instabot.py", line 736, in new_auto_mod_follow
    if check_already_followed(self, user_id=self.media_by_tag[0]['node']["owner"]["id"]) == 1:
  File "/root/instabot.py-check_already_liked-fix/src/sql_updates.py", line 50, in check_already_followed
    user_id + "' LIMIT 1)").fetchone()[0] > 0:
sqlite3.OperationalError: near "񐁓񐁌????񐀠򐁘????????񐁓񐁌????????񠀠󰁒????????????????????????򀁗????????????????????????????????????????????????????????򐁌򐁍????????": syntax error
12.01.2018_22:00 Logout: likes - 1, follow - 0, unfollow - 0, comments - 0.
12.01.2018_22:00 Bot work time: 0:00:10.228539
12.01.2018_22:00 Logout success!

Almost same

**Comment by ugurozturk** [comment]
i was using it via python3x on android so i did test in python2x in android and the result is as screen shot. So what is really wrong with your repo o.o
![screenshot_20180112-175801_2](https://user-images.githubusercontent.com/7994408/34880799-a140f0ac-f7c2-11e7-9762-ce04969afae1.jpg)

**Comment by ugurozturk** [comment]
@mactrash lets find the problem and fix this together.. 

## Please answer them

1. Any unicode character in your username or password ?
2. What is your system language ?
3. May i came in your computer via teamviewer ?

**Comment by mactrash** [comment]
@ugurozturk 

Sorry I miss type it is linux Python 2.7.14 

The system is english  no unicode in username and password

**Comment by mactrash** [comment]
@ugurozturk I will test with other linux and report back,

**Comment by mactrash** [comment]
@ugurozturk I have one more question, since now there is a database file can we run multi example.py in same folder?

**Comment by mactrash** [comment]
@ugurozturk test in other VPS the latest master branch don't have that strange error.

Thanks a lot

**Comment by techchannnelandtutorials** [comment]
Lol just found soloution to the login error shit. Go to instabot.py line 65 where you will replace the self useragent with your browser's useragent. First login to chrome for an example to your instagram, next head over to https://developers.whatismybrowser.com/useragents/explore click on search which will find your useragent.
