### ISSUE TITLE
Limit all interactions (liking, commenting, following) with users with a defined maximum number of followers - Integration to  #877, #827

### ISSUE THREAD

**Issue by taradell** [instabot-py/instabot.py#892]
Check One :
- [ ] Bug
- [ x] Feature
- [ ] Need Help

_**INTEGRATION TO  #877**_
The bot targets only selected users increasing the likelihood to be followed back or to get likes

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
