### ISSUE TITLE
Interact only with users who have liked or commented recent feeds 

### ISSUE THREAD

**Issue by taradell** [instabot-py/instabot.py#893]
Check One :
- [ ] Bug
- [x] Feature
- [ ] Need Help

This feature would allow to target only users online and active in as specific moment. This would generate immediate notifications increasing the likelihood to collect more likes, comments and to be followed.

**Comment by ChipWolf** [comment]
I don't believe Instagram has presence detection

**Comment by taradell** [comment]
Hi @ChipWolf, I was thinking about this situation:

You post a new photo and all your network and people checking specific tags notice it, then they could like and/or comment it. The bot is already able to detect new media posted and if it could access to the list of users who liked or commented the photo you posted, the likelihood for the bot to target online users would increase.

what do you think?

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
