### ISSUE TITLE
Unfollow users who have not followed back after a certain amount of days

### ISSUE THREAD

**Issue by taradell** [instabot-py/instabot.py#894]
Check One :
- [ ] Bug
- [x] Feature
- [ ] Need Help

This would allow to remove old followed users (the higher the number of days they have not followed back, the lower the possibility they would follow back)

**Comment by ugurozturk** [comment]
Noting here , it is possible to do using last_followed_time in usernames table.

**Comment by Drivium** [comment]
I am also interested in this feature as well as following based on specific tag(s) (not just "like" based on tag)

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
