### ISSUE TITLE
Connction Error

### ISSUE THREAD

**Issue by y9y** [instabot-py/instabot.py#895]
The locin process fails. And there is a message that "connection Error".
Most of you think its the 2 Factor Autenthification. But I disabled the 2.F.A. So if I try to login with my PC its asks me if like to receive the confirmationcode via Mail/PhoneNr and thats why the bot doesnt function, even the 2.F.A is disabled.

Is it possible to update the bot and to give the possibility to type in the confiramtion code which I receive on my EMail ?

**Comment by ugurozturk** [comment]
Fill it please https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md
