### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by y9y** [instabot-py/instabot.py#896]
The locin process fails. And there is a message that "connection Error".
Most of you think its the 2 Factor Autenthification. But I disabled the 2.F.A. So if I try to login with my PC its asks me if like to receive the confirmationcode via Mail/PhoneNr and thats why the bot doesnt function, even the 2.F.A is disabled.

Is it possible to update the bot and to give the possibility to type in the confiramtion code which I receive on my EMail ?

Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [x ] Searched and checked other issues about my problem
- [ ] If have errors.log file and i did upload it

Check One :
- [ ] Bug
- [ x] Feature
- [ x] Need Help

## What OS ?
Windows
## Python Version ?
 3x
## Is it VPS ?
No
### VPS: Is the vps far far away ? Another Country ?
No
- [ ] VPS: Tried the same code via my local pc

**Comment by ugurozturk** [comment]
Traceback error logs please.

**Comment by y9y** [comment]
Login error! Connection error!

the only usful respond. On my instagram app I have to click " It was me", but also on a second time login fails and in background  I think instagram asks for this verfication code, which i can not typ in using the bot :S

**Comment by HenryCooperGithub** [comment]
**Please update to the most recent version of instabot.py**

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output
