### ISSUE TITLE
Location ID as source (From #508)

### ISSUE THREAD

**Issue by zhen737** [instabot-py/instabot.py#897]
> Fill in all requirements *before* submitting an issue. If you fail to do so, we will close the ticket.

- [x] This is a checked box.
- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 10

## Python Version?
3

## Description

Hi, I've been using the location as a source thanks to the awesome people from @deefault at #508.
But currently due to some changes on API, as well as major changes on InstaBot, I tried to merge the previous location feature code from #508 into the latest code, but after several trials and debug, still unable get it to work. Is there anyone able to assist me on this?

**Comment by HenryCooperGithub** [comment]
We do not support third party libraries , please talk directly to the developer that you use code from .
