### ISSUE TITLE
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: www.instagram.com

### ISSUE THREAD

**Issue by mactrash** [instabot-py/instabot.py#898]
> Fill in all requirements *before* submitting an issue. If you fail to do so, we will close the ticket.

- [x] This is a checked box.
- [c] I have searched for other issues with the same problem.

## Hosting
- [X] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Linux 

## Python Version?
2 

## Description
Error log random show
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: i.instagram.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: i.instagram.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: i.instagram.com

Is this normal or ?

```
Include the contents of the error.log here (if applicable).
```
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: i.instagram.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: i.instagram.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: i.instagram.com

**Comment by HenryCooperGithub** [comment]
Please update to the most recent version of instabot.py

If your problem still persists open a new issue and attach the following information:

- Your bot configuration (parameters)
- Full console output

**Comment by ugurozturk** [comment]
@mactrash it is happens because of the old python module requests. 

source from requests module [doc ](http://docs.python-requests.org/en/master/)

`The use of Python 3 is highly preferred over Python 2. Consider upgrading your applications and infrastructure if you find yourself still using Python 2 in production today. If you are using Python 3, congratulations — you are indeed a person of excellent taste.`

**Comment by mactrash** [comment]
@ugurozturk try python3 is same.

**Comment by ugurozturk** [comment]
@mactrash check your request module version by `pip freeze`

**Comment by mactrash** [comment]
@ugurozturk thanks a lot.
