### ISSUE TITLE
Mode=1, Instabot does not work after some time, error feed_scanner.py line 37th

### ISSUE THREAD

**Issue by Hassankashi** [instabot-py/instabot.py#899]
Hi 
When in mode=1 and condition is proper to go through *follow_protocol(bot)* 
This error will be happen.
I read this issue: https://github.com/instabot-py/instabot.py/issues/780
and I corrected line 37th from "feed_scanner.py"
But it just worked a bit more fro three attempt to #12 attempt
 Followed: xxxxxxxxxx #3  ->  Followed: xxxxxxxxxx #12

Operating System?  Windows 10

## Python Version?
Anaconda Spyde 3.2.3

The description of my issue here.
TypeError: 'NoneType' object is not subscriptable
```
Followed: 5609389919 #10.
Followed: 4568677299 #11.
Followed: 3030018156 #12.
Except on follow!
Traceback (most recent call last):

  File "<ipython-input-2-bff206fe4919>", line 1, in <module>
    runfile('D:/mm/instabot.py-master/instabot.py-master/example.py', wdir='D:/mm/instabot.py-master/instabot.py-master')

  File "C:\Users\Mahsa\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\Users\Mahsa\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/mm/instabot.py-master/instabot.py-master/example.py", line 90, in <module>
    feed_scanner(bot)

  File "src\feed_scanner.py", line 37, in feed_scanner
    self.current_id = self.media_on_feed[chooser]["node"]["owner"]["id"]

TypeError: 'NoneType' object is not subscriptable```


My configuration:
bot = InstaBot(
    login="xx",
    password="xx",
    like_per_day=100,
    comments_per_day=0,
    tag_list=['follow4follow', 'f4f', 'cute'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=3,
    follow_per_day=300,
    follow_time=1 * 60,
    unfollow_per_day=10,
    unfollow_break_min=4,
    unfollow_break_max=4,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])


My mode 1:

elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 300:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 500:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

**Comment by ugurozturk** [comment]
There is a lot of bugs on mode = 1 feed_scanner, post_page, username_checker

**Comment by ugurozturk** [comment]
@Hassankashi also i want to know why you using mode = 1 ? by personally asking it. If i missing something to

**Comment by ugurozturk** [comment]
@Hassankashi can you test https://github.com/instabot-py/instabot.py/tree/recent_feed_fix branch ?

**Comment by Hassankashi** [comment]
@ugurozturk Thank you for response , I wanna add followers ad because of that I gonna use mode one or four. Is there other way to add followers with mode=0?
Unfollow protocol is working perfectly but I have problem with follow protocol and at this moment it is problem is when it is tryin to follow after some seconds bot unfollows that id.

**Comment by Hassankashi** [comment]
In the respect on mentioned bug, I found out that it might be because my insta id is not old enough to get 23 feeds and when I changed it I could go and get from selecting feed instead of hashtag.
I changed line 20th from feed_scanner.py to `if len(self.media_on_feed) > 5: `

And also I just guess that feed_scanner.py line 37th has lack of 
`self.current_user = self.media_on_feed[chooser]["node"]["owner"]["id"]`
Besides getting self.current_id.

So I will try new branch and in meanwhile if I could debug mode one or four I will leave remark.

**Comment by ugurozturk** [comment]
@Hassankashi add followers to what ? sorry i didn't understand what you mean.. mode=0 is database based now. And it does adds all of your following and liking activities to database. So you can check it later, it also stops spamming people. That you will not follow a person again and again. 

PS : mode = 0 does follow / like / unfollow / comment any one you want

**Comment by Hassankashi** [comment]
@ugurozturk Yes you are definitely right but mode 1(if subtraction is suitable) and 4 will merely do follow protocol. 
While mode zero is doing all (like-comment-follow-unfollow) and will take loner time.

**Comment by ugurozturk** [comment]
@Hassankashi Did you try the branch i wanted you to test it ?

**Comment by Hassankashi** [comment]
@ugurozturk Yes, I felt it has been changed and now I am using mode=1 and it seems good. Thank you so much I get your last 5 hours modification.
I saw its history and I have another offer; It follow and then quickly unfollow specific id, do you think it is better to review activity user condition because it might be one user did not post and did not like and follow but still use Instagram , is there anyway to check user is sending post to their followers is active user, because it is what I do in Instagram and I am active.
So if way to detect active use is based on his or her last sharing post date , lets change to his or her last  like or follow or send post to others?

**Comment by ugurozturk** [comment]
Noting here to remember in the future if i need : 

```
user_info.py

if media > 0 and follows / media < 10 and follower / media < 10:
                    self.is_active_user = True
                    print('   >>>This user is active')
                else:
                    self.is_active_user = False
                    print('   >>>This user is passive')
```

**Comment by ugurozturk** [comment]
i dont know very much about mode = 1. I am using and editing mode=0, you needed and i just tried to edit it. About the user's active status depends on the lines i wrote here

**Comment by ugurozturk** [comment]
And this issue will be closed tmorrow. Please test the code as much as you can

**Comment by Hassankashi** [comment]
@ugurozturk My last question is, I want to specify user activity based on specific picture url .
I mean I wanna follow people who like one picture.
For example I want to insert [this url](https://www.instagram.com/p/Bd28Xe1F0rZ/?tagged=fashion) 
and follow whoever liked this picture.
I want to give a picture url "https://www.instagram.com/p/Bd28Xe1F0rZ/?tagged=fashion" and find out who liked it and put them in loop tot follow them.

If I am right it should be:
1. Go to:  instabot.py
2. in this function "get_instagram_url_from_media_id" I have url: https://www.instagram.com/p/Bd28Xe1F0rZ/?tagged=fashion
3. I want list of users who liked it
For example: "get_username_by_media_id" line 375th instabot.py
Is all_data variable includes list of user who liked as json?
4. Then I just want to run and follow "def follow(self, user_id):" inside loop and sleep for one hour after 50 users who I followed because of Instagram banning my account because it does not allow me to follow much users.

Thank you in advanced if you show me the way.

**Comment by ugurozturk** [comment]
@seppemarotta yes it will if there wont be any problem

**Comment by ugurozturk** [comment]
@Hassankashi Yeah it should be, it is 3:37 am here so im not sure. It needs test, and probabby you can make it as like modes. Yet there would be problems on that. Ins gives the comments via owners and just 9 likers. Not the 725. When i check via posts on browser it thinks we need something like `www.instagram.com/graphql/query/?query_id=xxxxxxx&variables={"shortcode":"Bd28Xe1F0rZ","first":500}` the thing is i am not sure if the query_id is unique for users nor it is dynamic
