### ISSUE TITLE
Suspicious login

### ISSUE THREAD

**Issue by Nicolas-vrcc** [instabot-py/instabot.py#901]
The bot no longer works. Says I cannot log in. Connection failed. After attempting to use the tool I get a warning about a suspicious log in on the desktop or Iphone Instagram app.

I am not using a proxy. I am running the script on a VPS and the datacenter is in France ( me too ).

**Comment by ugurozturk** [comment]
@Nicolas-vrcc https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md
