### ISSUE TITLE
Did Instagram blocked the script on VPS ?

### ISSUE THREAD

**Issue by Nicolas-vrcc** [instabot-py/instabot.py#902]
First, I tried the bot on local and it works perfectly but on my vps it's not working.
The bot no longer works. Says I cannot log in. Connection failed. After attempting to use the tool I get a warning about a suspicious log in on the desktop or Iphone Instagram app.

I am not using a proxy. I am running the script on a VPS and the datacenter is in France ( me too ).

Can I have a true answer please, and yes, I rode the question template file.

here is the error I get : 
`Instabot v1.1.0 started at 12.01.2018 10:14:
Trying to login as nicolasvrc...
Login error! Connection error!`

**Comment by ugurozturk** [comment]
@Nicolas-vrcc probabby, the vps's static ip is in their database as a blacked ones. There is a lot vps are running without any error now.  And we are requiring ISSUE_TEMPLATE for a reason. On you the most import reason is "If so; have you tried running the code on your local machine?" i am again closing this as i should without even typing this much
