### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by y9y** [instabot-py/instabot.py#908]
**Issue**
- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Windows

## Python Version?
3

## Description
I have used the bot 2 days on my local computer. It worked fine.
But today I made a lot of likes and I tried again to login after 3h and it didnt work :(
It says connection Error and on my app "suspicious activites" pops up

Need **help...**

Include the contents of the error.log here (if applicable).

C:\Users\yxz\Desktop\1>python example.py
15.01.2018_22:09 Instabot v1.2.0 started at 15.01.2018 22:09:

15.01.2018_22:09 Trying to login as *****...

15.01.2018_22:09 Login error! Connection error!
15.01.2018_22:09 Removing already liked medias..
15.01.2018_22:09 Trying to unfollow #1:
15.01.2018_22:09 Removing already liked medias..

**Comment by ugurozturk** [comment]
duplicate https://github.com/instabot-py/instabot.py/issues/905

**Comment by y9y** [comment]
Its not the same problem i think. On my browser I can login without problems...
Also in other accounts the bot works

**Comment by ugurozturk** [comment]
@y9y do you using proxy ?

**Comment by y9y** [comment]
No i didnt..

**Comment by ugurozturk** [comment]
@y9y do you have any unique character on your password or username ?

**Comment by y9y** [comment]
Hmm. My username has a point inside an passwort is usual (numbers and characters)

**Comment by ugurozturk** [comment]
@y9y Did you follow / unfollow / like / comments too much ?

PS : Also please wait tomorrow then try this new branch. https://github.com/instabot-py/instabot.py/tree/fake_user_agent . You need to install module fake-useragent via `pip install fake-useragent`

**Comment by y9y** [comment]
Yes its possible that I follow and like too much....

Okey i will try :) So whats the difference of "fake_user" ?

**Comment by ugurozturk** [comment]
@y9y Well you should check the "User Agent about browser" in the google. We are using static user agent now. Perhaps i though they have noticed the user agent so i changed it. Then wanted to test this feature with you

**Comment by Nicolas-vrcc** [comment]
@y9y @ugurozturk 
I tried with a different user agent and got the exact same issue. Someone really need to fix this and it's a real issue.

**Comment by ugurozturk** [comment]
@Nicolas-vrcc the thing is, i dont having the problem. We can't fix it if we dont get the same error. Atleast for this one. Btw PRs always welcomed.

**Comment by ugurozturk** [comment]
@y9y feedback please. What happened today ?

**Comment by Nicolas-vrcc** [comment]
@ugurozturk 
I get this error while running **pip install fake-useragent** in the master directory
`Collecting fake-useragent
  Using cached fake-useragent-0.1.8.tar.gz
Installing collected packages: fake-useragent
  Running setup.py install for fake-useragent ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/sc/k852bmqd5vs1m54zk41txqh80000gn/T/pip-build-TJApZl/fake-useragent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/sc/k852bmqd5vs1m54zk41txqh80000gn/T/pip-xNvFC6-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fake_useragent
    copying fake_useragent/__init__.py -> build/lib/fake_useragent
    copying fake_useragent/errors.py -> build/lib/fake_useragent
    copying fake_useragent/fake.py -> build/lib/fake_useragent
    copying fake_useragent/log.py -> build/lib/fake_useragent
    copying fake_useragent/settings.py -> build/lib/fake_useragent
    copying fake_useragent/utils.py -> build/lib/fake_useragent
    running egg_info
    writing fake_useragent.egg-info/PKG-INFO
    writing top-level names to fake_useragent.egg-info/top_level.txt
    writing dependency_links to fake_useragent.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'fake_useragent.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    writing manifest file 'fake_useragent.egg-info/SOURCES.txt'
    running install_lib
    creating /Library/Python/2.7/site-packages/fake_useragent
    error: could not create '/Library/Python/2.7/site-packages/fake_useragent': Permission denied
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/sc/k852bmqd5vs1m54zk41txqh80000gn/T/pip-build-TJApZl/fake-useragent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/sc/k852bmqd5vs1m54zk41txqh80000gn/T/pip-xNvFC6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/sc/k852bmqd5vs1m54zk41txqh80000gn/T/pip-build-TJApZl/fake-useragent/`

**Comment by ugurozturk** [comment]
@Nicolas-vrcc Please use google for module install errors.

**Comment by Nicolas-vrcc** [comment]
@ugurozturk tried, still not working, I am getting the same error

**Comment by ugurozturk** [comment]
@Nicolas-vrcc https://github.com/instabot-py/instabot.py/pull/911/files can you test this pr ? he just cleans user_agent string

**Comment by y9y** [comment]
@ugurozturk Thank for you demand :) Today the bot works fine with all my accounts. Maybe it was only because I liked too much Pictures...

**Comment by Nicolas-vrcc** [comment]
@ugurozturk 
Hey, how many ppl do you like per day

**Comment by Nicolas-vrcc** [comment]
@y9y How many ppl do you like a day with each account ?

**Comment by Nicolas-vrcc** [comment]
@y9y 
Ok, so I've done a lot of exepriments and here is what I found out:

I can use the script with any account as long as I run it from my local terminal ( even account that belong to friends and who've never been related to my local IP ) -> Works Fine

However : Launching it from a VPS or by using a proxy results in a 'suspicious login' endless loop.-> Fail

I don't think it's a user_agent problem because no matter what I try it doesn't change anything...

**Comment by y9y** [comment]
@ugurozturk @Nicolas-vrcc 
So i think there is problem with the limits. Today i didnt make a lot of likes and at the morning it works fine, but today evenig i made about 100likes (today totaly <500 + <100 comments) and the problem starts again..... "suspicious login" :(

**Comment by ugurozturk** [comment]
@Nicolas-vrcc Perhaps the problem is, the vps or the proxy are you using is already in instagram's database that is vps or a proxy.

**Comment by y9y** [comment]
@ugurozturk so today it is also not working. And i dont use vps or a proxy, I run it on my computer....

**Comment by y9y** [comment]
Isn't possible to program this 2.Factor A. ? I think it would solve the most problems by loggin in. But i really dont know how to program that :S

**Comment by ugurozturk** [comment]
@y9y i dont have the error so i can't fix that.

**Comment by ugurozturk** [comment]
@y9y How many account at the same time

**Comment by y9y** [comment]
@ugurozturk I do run 3 Accounts... 
(2 Accouts cant login now... and the 1 new account is going well)

**Comment by ugurozturk** [comment]
So you know the answer.. you shouldn't run 2 account in the same ip atleast without proxy
