### ISSUE TITLE
Log in error line 50

### ISSUE THREAD

**Issue by entorment** [instabot-py/instabot.py#909]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows

## Python Version?
3

## Description
Line 50 in module receives error after removing whitelist

```
C:\Users\Ouch\Downloads\instabot.py-master>python example.py
15.01.2018_17:19 Instabot v1.2.0 started at 15.01.2018 17:19:

15.01.2018_17:19 Trying to login as entorment...

Traceback (most recent call last):
  File "example.py", line 50, in <module>
    'follow', 'follower', 'gain', '.id', '_id', 'bags'
  File "C:\Users\Ouch\Downloads\instabot.py-master\src\instabot.py", line 227, in __init__
    self.login()
  File "C:\Users\Ouch\Downloads\instabot.py-master\src\instabot.py", line 296, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\Ouch\Downloads\instabot.py-master\src\userinfo.py", line 44, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "C:\Users\Ouch\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Ouch\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Ouch\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ugurozturk** [comment]
Please search or try more. Or send here full of your example.py. By meaning about "remove the parameter unfollow_whitelist" is not copy pasting what i provided. You need to check what i have changed. By the way you should also check https://www.tutorialspoint.com/python/python_basic_syntax.htm.

ref : https://github.com/instabot-py/instabot.py/issues/907

**Comment by entorment** [comment]
Alrighty, thank you sir!

**Comment by entorment** [comment]
Here is my example.py

#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="username",
    password="password",
    like_per_day=1000,
    comments_per_day=300,
    tag_list=['follow4follow', 'f4f', 'cute', 'girl'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1 * 60,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

**Comment by ugurozturk** [comment]
@entorment this one you provided me working fine. Copy all, paste a file change the username and password. Do run you will see it is working pretty fine

**Comment by entorment** [comment]
Per the video i watched on the tutorial from this github, im running it through cmd. Should this be run on python directly or should i keep using cmd?  And it was username and password in the example.py when i sent the example to you. When i run it, it has my credentials.

**Comment by entorment** [comment]
I just ran that exact script, and came up with this.

C:\Users\Ouch\Downloads\instabot.py-master>python example.py
15.01.2018_22:47 Instabot v1.2.0 started at 15.01.2018 22:47:

15.01.2018_22:47 Trying to login as entorment...

Traceback (most recent call last):
  File "example.py", line 50, in <module>
    'follow', 'follower', 'gain', '.id', '_id', 'bags'
  File "C:\Users\Ouch\Downloads\instabot.py-master\src\instabot.py", line 227, in __init__
    self.login()
  File "C:\Users\Ouch\Downloads\instabot.py-master\src\instabot.py", line 296, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\Ouch\Downloads\instabot.py-master\src\userinfo.py", line 44, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "C:\Users\Ouch\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Ouch\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Ouch\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ugurozturk** [comment]
@entorment can you change your sub title and re try it ? i mean the biography "🔮ℵλℵ🔮" . I rechecked everything yet there is not much thing

**Comment by ugurozturk** [comment]
File "C:\Users\Ouch\Downloads\instabot.py-master\src\userinfo.py", line 44, in get_user_id_by_login
all_data = json.loads(info.text)

this is your error. You might try to debug the info variable. Then you probabby see the real problem

**Comment by entorment** [comment]
How do i go about debugging the line 44 info variable?

**Comment by ugurozturk** [comment]
@entorment please use google for it. It is python project so you can google by "How to python debug" however the easiest way is to use "vscode" code editor. it has feature built in debugging. You just need to use a extension for python.

**Comment by valeirta** [comment]
I keep getting this error:

File "example.py", line 43, in <module>
    'follow', 'follower', 'gain', '.id', '_id', 'bags'
TypeError: object() takes no parameters

Can anyone help pls? @entorment ?
