### ISSUE TITLE
userinfo.py doesn't work anymore..

### ISSUE THREAD

**Issue by psam25** [instabot-py/instabot.py#91]
The userinfo.py doesn't work anymore, because of the new api from Facebook (to ink361.com).

**Comment by LevPasha** [comment]
@psam25 hmmm.. it is sad( 
https://blog.ink361.com/2016/05/ink361-changes/

**Comment by psam25** [comment]
Is it possible to integrate the Instagram API to import the userlist from there?

**Comment by gonzalon** [comment]
@psam25 for getting access to the API you need to submit the application code and so. Don't think they are going to give us acess =P

If you are logged in you can see any users followers or following. 
One way would be trying to replicate the request or try to scrap the web html to get the data you need...

**Comment by silenthunter93** [comment]
Quick question about the unfollowpub.py, i get this error when i run it (Exception KeyError: KeyError(140596547925824,) in <module 'threading' from '/usr/lib64/python2.7/threading.pyc'> ignored)

**Comment by skynyd** [comment]
https://github.com/mgp25/Instagram-API

they implemented an API in php and are able to get followers and following. maybe that helps

**Comment by LevPasha** [comment]
@skynyd ok, i look it.

**Comment by velvetflower** [comment]
@silenthunter93 unfollowpub is not working because of api trouble.

**Comment by LevPasha** [comment]
@skynyd watch it, it is interesting, buy hard to me to translate `php` to `python`. I try it later...

**Comment by feri0010** [comment]
Any news about this issue? new ideas to fix it?

**Comment by skynyd** [comment]
using the suggested API would be hard, as you would need to be logged in as two different clients. Instagram keeps locking the account

**Comment by LevPasha** [comment]
@skynyd  @feri0010 @velvetflower @silenthunter93 @gonzalon @psam25 @torlakfaruk yo-yo-yo mans!  I start to rewrite this API. The hardest part (login, cookies and etc) is done! But there are many other shit! I will rewrite it myself, when i can. Will be glad any help!

https://github.com/LevPasha/Instagram-API-python

**Comment by feri0010** [comment]
I am ready to help, but I am new to python and have no idea about PHP. If
there is anything that I can do, please let me know about it.
Waiting for a reply from you.

On Mon, Jun 6, 2016 at 2:54 PM, Pasha Lev <notifications@github.com> wrote:

> @skynyd <https://github.com/skynyd> @feri0010
> <https://github.com/feri0010> @velvetflower
> <https://github.com/velvetflower> @silenthunter93
> <https://github.com/silenthunter93> @gonzalon
> <https://github.com/gonzalon> @psam25 <https://github.com/psam25>
> @torlakfaruk <https://github.com/torlakfaruk> yo-yo-yo mans! I start to
> rewrite this API. The hardest part (login, cookies and etc) is done! But
> there are many other shit! I will rewrite it myself, when i can. Will be
> glad any help!
>
> https://github.com/LevPasha/Instagram-API-python
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/LevPasha/instabot.py/issues/91#issuecomment-223921592>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS1CU8h-uoZmUDH9bnen0SGwFuEib1aYks5qI_VFgaJpZM4IsTf6>
> .
>



-- 
Sincerely yours
Farzad Ch

**Comment by LevPasha** [comment]
@feri0010 how you can help to write program if you not programmer? Buy me a beer ))

**Comment by torlakfaruk** [comment]
@LevPasha you can get followers with this link: https://instagram.com/api/v1/friendships/$usernameId/followers/
But with that link instagram gives only 200 followers. Is there anything to do for this?

**Comment by marciogm** [comment]
If you already logged in, you can get normal as url:  https://www.instagram.com/query/
And pass query in your body, like this.

> q=ig_user(**USER_ID**)+%7B%0A++followed_by.first(**10**)+%7B%0A++++count%2C%0A++++page_info+%7B%0A++++++end_cursor%2C%0A++++++has_next_page%0A++++%7D%2C%0A++++nodes+%7B%0A++++++id%2C%0A++++++is_verified%2C%0A++++++followed_by_viewer%2C%0A++++++requested_by_viewer%2C%0A++++++full_name%2C%0A++++++profile_pic_url%2C%0A++++++username%0A++++%7D%0A++%7D%0A%7D%0A&ref=relationships%3A%3Afollow_list

Use a URL Encode/Decode like http://www.url-encode-decode.com and you will see.

To get another page you just get the **end_cursor** of your response and submit a new query.

>
q=ig_user(**USER_ID**)+%7B%0A++followed_by.after(**AQC_PGJ4zXSR36HKgymrZnt4ptlb-PxwmV9GynBkZDaPVkQf5xeno4okmKNANYpfGBG_MBgUymzZDUq3MgGLDlSl-mA-bg6hJWmOut0L3_PUWr1-P4hF8sFNHfLUZYJ8EQk**%2C+10)+%7B%0A++++count%2C%0A++++page_info+%7B%0A++++++end_cursor%2C%0A++++++has_next_page%0A++++%7D%2C%0A++++nodes+%7B%0A++++++id%2C%0A++++++is_verified%2C%0A++++++followed_by_viewer%2C%0A++++++requested_by_viewer%2C%0A++++++full_name%2C%0A++++++profile_pic_url%2C%0A++++++username%0A++++%7D%0A++%7D%0A%7D%0A&ref=relationships%3A%3Afollow_list

**Comment by LevPasha** [comment]
@torlakfaruk and @marciogm can you write work code and make pull request?

**Comment by skynyd** [comment]
@marciogm can you explian how this works in detail? thanks

**Comment by marciogm** [comment]
Maybe this week i can do the pull request, but it's simple.

You have to move userinfo.py to instabot.py, because you will use the the same request from login. and you need the response from login, to get cookies and csrftoken.
The url to post are https://www.instagram.com/query/ and the data to pass in body is

> q=ig_user(USER_ID)+%7B%0A++followed_by.first(10)+%7B%0A++++count%2C%0A++++page_info+%7B%0A++++++end_cursor%2C%0A++++++has_next_page%0A++++%7D%2C%0A++++nodes+%7B%0A++++++id%2C%0A++++++is_verified%2C%0A++++++followed_by_viewer%2C%0A++++++requested_by_viewer%2C%0A++++++full_name%2C%0A++++++profile_pic_url%2C%0A++++++username%0A++++%7D%0A++%7D%0A%7D%0A&ref=relationships%3A%3Afollow_list

This are encoded, if you use http://www.url-encode-decode.com to decode.

> q=ig_user(USER_ID) {
  followed_by.first(10) {
    count,
    page_info {
      end_cursor,
      has_next_page
    },
    nodes {
      id,
      is_verified,
      followed_by_viewer,
      requested_by_viewer,
      full_name,
      profile_pic_url,
      username
    }
  }
}
&ref=relationships::follow_list


So.. just pass the encoded string in your body request, like this.
https://gist.github.com/marciogm/5e48377c39de46d79d8eebc7880db96f

**Comment by LevPasha** [comment]
@marciogm good work, wait your integration of this to `instabot.py` to test it. THX!

**Comment by skynyd** [comment]
@marciogm had it running and testing but it seems it stopped working. Maybe due to the new API. Can you confirm that?
Or did I maybe hit a query limit or something??

**Comment by psam25** [comment]
Maybe we can use the website https://websta.me ? the only thing is we need to register for free..

**Comment by kaxil** [comment]
Hes @LevPasha I was talking about this? Did you manage to solve this issue ?

**Comment by LevPasha** [comment]
@kaxil use this https://github.com/LevPasha/Instagram-API-python
