### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by matteoFeduzi** [instabot-py/instabot.py#913]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC OSX Version 10.13.1

## Python Version?
2 

## Description

Type the description of your issue here.

Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/FeduziMatteo/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/FeduziMatteo/Desktop/instabot.py-master/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/Users/FeduziMatteo/Desktop/instabot.py-master/src/userinfo.py", line 6, in <module>
    import requests
ImportError: No module named requests
```
Include the contents of the error.log here (if applicable).
```

**Comment by ugurozturk** [comment]
"ImportError: No module named requests" means you need to install module named requests. by `pip install requests`

**Comment by clementinoux** [comment]
Hello, I've got exactly the same error but requests is well installed 

> pip3 install requests        
> Requirement already satisfied: requests in /usr/local/lib/python3.6/site-packages

Any ideas to fix this issue ? 
Thanks
