### ISSUE TITLE
Mac permission denied at module install

### ISSUE THREAD

**Issue by spaez18** [instabot-py/instabot.py#914]
- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC 10.13.2

## Python Version?
3.6.4

## Description

I was following your mac tutorial, but when I try to install the requirements i get this error:

`OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/requests'`

How can I solve this error? If the traceback is needed I can post it.
Thanks in advance!

**Comment by ugurozturk** [comment]
Please use google for not related to library things. by "pip module install mac permission denied" if you find the solution comment here. I will keep this open for whose having the same problem

**Comment by joilson-cisne** [comment]
@spaez18 Try using `sudo`. It worked for me:

`sudo pip install -r requirements.txt`

**Comment by spaez18** [comment]
Thank you! it worked!
