### ISSUE TITLE
Can we just remove already liked medias?

### ISSUE THREAD

**Issue by aopiskin** [instabot-py/instabot.py#916]
i may not have seen that function but i'm just wondering it. Can we just remove already liked medias?

**Comment by ugurozturk** [comment]
@aopiskin https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md "Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket."
