### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/errors.log'

### ISSUE THREAD

**Issue by davirami88** [instabot-py/instabot.py#917]
Jan 18 10:33:47 ip-172-31-38-175 systemd[1]: Started Servico de Instagram.
Jan 18 10:33:48 ip-172-31-38-175 python[26659]: Traceback (most recent call last):
Jan 18 10:33:48 ip-172-31-38-175 python[26659]:   File "/home/ubuntu/instabot.py/example.py", line 6, in <module>
Jan 18 10:33:48 ip-172-31-38-175 python[26659]:     from src import InstaBot
Jan 18 10:33:48 ip-172-31-38-175 python[26659]:   File "/home/ubuntu/instabot.py/src/__init__.py", line 1, in <module>
Jan 18 10:33:48 ip-172-31-38-175 python[26659]:     from .instabot import InstaBot
Jan 18 10:33:48 ip-172-31-38-175 python[26659]:   File "/home/ubuntu/instabot.py/src/instabot.py", line 22, in <module>
Jan 18 10:33:48 ip-172-31-38-175 python[26659]:     class InstaBot:
Jan 18 10:33:48 ip-172-31-38-175 python[26659]:   File "/home/ubuntu/instabot.py/src/instabot.py", line 99, in InstaBot
Jan 18 10:33:48 ip-172-31-38-175 python[26659]:     logging.basicConfig(filename='errors.log', level=logging.INFO)
Jan 18 10:33:48 ip-172-31-38-175 python[26659]:   File "/home/ubuntu/anaconda3/lib/python3.5/logging/__init__.py", line 1744, in basicConfig
Jan 18 10:33:48 ip-172-31-38-175 python[26659]:     h = FileHandler(filename, mode)
Jan 18 10:33:48 ip-172-31-38-175 python[26659]:   File "/home/ubuntu/anaconda3/lib/python3.5/logging/__init__.py", line 1008, in __init__
Jan 18 10:33:48 ip-172-31-38-175 python[26659]:     StreamHandler.__init__(self, self._open())
Jan 18 10:33:48 ip-172-31-38-175 python[26659]:   File "/home/ubuntu/anaconda3/lib/python3.5/logging/__init__.py", line 1037, in _open
Jan 18 10:33:48 ip-172-31-38-175 python[26659]:     return open(self.baseFilename, self.mode, encoding=self.encoding)
Jan 18 10:33:48 ip-172-31-38-175 python[26659]: PermissionError: [Errno 13] Permission denied: '/errors.log'
Jan 18 10:33:48 ip-172-31-38-175 systemd[1]: deploy.service: Main process exited, code=exited, status=1/FAILURE
Jan 18 10:33:48 ip-172-31-38-175 systemd[1]: deploy.service: Unit entered failed state.
Jan 18 10:33:48 ip-172-31-38-175 systemd[1]: deploy.service: Failed with result 'exit-code'.

I'm trying to deploy the script as a service in an ubuntu virtual machine but i keep getting this error, i have changed the route of the file errors.log, do you know why is this happening, i haven't had this error never until the last update

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md  `Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket`
