### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by davirami88** [instabot-py/instabot.py#918]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Linux

## Python Version?
3

## Description

Hello guys, I'm having trouble while deploying the script as a service in my Ubuntu virtual machine, it started to happen yesterday because I updated the version by doing another git clone from this repository, at first i thought it was an error from ubuntu but checking it is a python error, I tried to put the straight path to the file errors.log but it didn't do anything.

```
Jan 18 10:33:47 ip-172-31-38-175 systemd[1]: Started Servicio de Instagram.
Jan 18 10:33:48 ip-172-31-38-175 python[26659]: Traceback (most recent call last):
Jan 18 10:33:48 ip-172-31-38-175 python[26659]: File "/home/ubuntu/instabot.py/example.py", line 6, in 
Jan 18 10:33:48 ip-172-31-38-175 python[26659]: from src import InstaBot
Jan 18 10:33:48 ip-172-31-38-175 python[26659]: File "/home/ubuntu/instabot.py/src/init.py", line 1, in 
Jan 18 10:33:48 ip-172-31-38-175 python[26659]: from .instabot import InstaBot
Jan 18 10:33:48 ip-172-31-38-175 python[26659]: File "/home/ubuntu/instabot.py/src/instabot.py", line 22, in 
Jan 18 10:33:48 ip-172-31-38-175 python[26659]: class InstaBot:
Jan 18 10:33:48 ip-172-31-38-175 python[26659]: File "/home/ubuntu/instabot.py/src/instabot.py", line 99, in InstaBot
Jan 18 10:33:48 ip-172-31-38-175 python[26659]: logging.basicConfig(filename='errors.log', level=logging.INFO)
Jan 18 10:33:48 ip-172-31-38-175 python[26659]: File "/home/ubuntu/anaconda3/lib/python3.5/logging/init.py", line 1744, in basicConfig
Jan 18 10:33:48 ip-172-31-38-175 python[26659]: h = FileHandler(filename, mode)
Jan 18 10:33:48 ip-172-31-38-175 python[26659]: File "/home/ubuntu/anaconda3/lib/python3.5/logging/init.py", line 1008, in init
Jan 18 10:33:48 ip-172-31-38-175 python[26659]: StreamHandler.init(self, self._open())
Jan 18 10:33:48 ip-172-31-38-175 python[26659]: File "/home/ubuntu/anaconda3/lib/python3.5/logging/init.py", line 1037, in _open
Jan 18 10:33:48 ip-172-31-38-175 python[26659]: return open(self.baseFilename, self.mode, encoding=self.encoding)
Jan 18 10:33:48 ip-172-31-38-175 python[26659]: PermissionError: [Errno 13] Permission denied: '/errors.log'
Jan 18 10:33:48 ip-172-31-38-175 systemd[1]: deploy.service: Main process exited, code=exited, status=1/FAILURE
Jan 18 10:33:48 ip-172-31-38-175 systemd[1]: deploy.service: Unit entered failed state.
Jan 18 10:33:48 ip-172-31-38-175 systemd[1]: deploy.service: Failed with result 'exit-code'.
```

**Comment by ugurozturk** [comment]
@davirami88 as it says, permission error. Perhaps you can fix it by running as admin. `sudo python3 example.py`

**Comment by davirami88** [comment]
@ugurozturk Thanks, yeah, I know, I have tried it and I couldn't, I tried looking up for similar issues in different repositories and normally they change some file in python, that's why I'm here

**Comment by ugurozturk** [comment]
@davirami88 did you try creating empty errors.log . Perhaps it can write inside the errors.log

**Comment by davirami88** [comment]
@ugurozturk hi again, I'm sure if you can provide me an early version I can solve the problem, I've tried multiple things but anything seems to work. Thanks again.

**Comment by ugurozturk** [comment]
@davirami88 do google "github old commit clone" you will find the anser. Yet, i dont suppose you recommending old commits. You can only remove all "logging" codes to bypass directly your problem.

**Comment by davirami88** [comment]
@ugurozturk sounds good, but, do you know the file or the file where I have to delete that? or where exactly the errors.log file is created? or how to avoid to write in that file?

**Comment by ugurozturk** [comment]
@davirami88 i do but i dont have time to tell you all. You should find them. inside files do ctrl + f and find "logging." delete them

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
