### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by arslanhashmi** [instabot-py/instabot.py#921]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC 

## Python Version?
3

## Description
  File "/Users/arslan/Downloads/instabot.py-master/src/sql_updates.py", line 118, in check_and_insert_user_agent
    result_check = self.follows_db_c.execute(qry).fetchone()
AttributeError: 'UserInfo' object has no attribute 'follows_db_c'
 i am having this issue not sure how to remove it.
```
Include the contents of the error.log here (if applicable).
```

**Comment by jegue** [comment]
same

**Comment by ugurozturk** [comment]
@arslanhashmi @jegue what mode are you two using ?

**Comment by Laboratory** [comment]
+1

AttributeError: 'UserInfo' object has no attribute 'follows_db_c'

**Comment by ugurozturk** [comment]
@Laboratory what mode are you using

**Comment by ugurozturk** [comment]
Anyway did revert changes on userinfo.py . Probabby you guys aren't using `mode = 0` . Yet we are fully supporting on mode = 0 . The other modes has buggy and new features always come to mode = 0 at first. Like fake user agent, cookies.

Im closing this issue, it probabby fixed by your side now. Using mode 0 and python 3 always will be good. Update your repo via latest commit

**Comment by Laboratory** [comment]
@ugurozturk `mode=0`

**Comment by arslanhashmi** [comment]
@ugurozturk thanks for your help, just need to ask another question about user agent, what if i use the same api code and same user agent information in all the n number of processes/threads (may be 10 instagram accounts) how much api calls i may have in an hour for 1 account? how can i scale?
