### ISSUE TITLE
ImportError: No module named 'fake_useragent'

### ISSUE THREAD

**Issue by Laboratory** [instabot-py/instabot.py#922]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC 

## Python Version?
2 

## Description

Type the description of your issue here.

```
Include the contents of the error.log here (if applicable).
    from src import InstaBot
  File "/home/vanikitin/projects/instabot.py/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/vanikitin/projects/instabot.py/src/instabot.py", line 6, in <module>
    from .userinfo import UserInfo
  File "/home/vanikitin/projects/instabot.py/src/userinfo.py", line 6, in <module>
    from fake_useragent import UserAgent
ImportError: No module named 'fake_useragent'
```

**Comment by ugurozturk** [comment]
sudo pip install fake_useragent

**Comment by Laboratory** [comment]
i did it before report this issue

**Comment by Laboratory** [comment]
I copied `fake_useragent` directory to project dir and it works, but this is not a normal situation

**Comment by ugurozturk** [comment]
@Laboratory you dont need that already, it is a module. Perhaps you need like `sudo pip3 install fake_useragent`

**Comment by barelzrian** [comment]
please help me with this one guys

Traceback (most recent call last):
  File "/home/barelzrian/instabot.py/example.py", line 6, in <module>
    from src import InstaBot
  File "/home/barelzrian/instabot.py/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/barelzrian/instabot.py/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ImportError: No module named fake_useragent
>>>

??????

**Comment by ugurozturk** [comment]
@barelzrian https://github.com/instabot-py/instabot.py/issues/922#issuecomment-359203387

**Comment by follow4follow12343** [comment]
How and where to install fake_useragent @ugurozturk

**Comment by ugurozturk** [comment]
@follow4follow12343 for next time your needs https://pypi.python.org/pypi/fake-useragent . It is a module and all the modules are same. Check the link. There is Installation

**Comment by ugurozturk** [comment]
@follow4follow12343 also i did write https://github.com/instabot-py/instabot.py/issues/922#issuecomment-359207670  https://github.com/instabot-py/instabot.py/issues/922#issuecomment-359203387 there. In this issue. Before asking, do read all the issue please.
