### ISSUE TITLE
 UserInfo instance has no attribute 'follows_db_c'

### ISSUE THREAD

**Issue by condor304** [instabot-py/instabot.py#923]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Linux  - Ubuntu 17.10

## Python Version?
2 and 3

## Description

Type the description of your issue here.

 at login script errors with:  
AttributeError: UserInfo instance has no attribute 'follows_db_c'

```
Include the contents of the error.log here (if applicable).

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['user_name'])
  File "/insta/src/instabot.py", line 231, in __init__
    self.login()
  File "/insta/src/instabot.py", line 299, in login
    ui = UserInfo()
  File "/insta/src/userinfo.py", line 31, in __init__
    self.user_agent = check_and_insert_user_agent(self, str(fake_ua.random))
  File "/mnt/c/Users/andre/Downloads/insta/insta/src/sql_updates.py", line 118, in check_and_insert_user_agent
    result_check = self.follows_db_c.execute(qry).fetchone()
AttributeError: UserInfo instance has no attribute 'follows_db_c'
```

**Comment by ugurozturk** [comment]
duplicate https://github.com/instabot-py/instabot.py/issues/921#issuecomment-359233924
