### ISSUE TITLE
I have the 400 likes issue using the original instabot.py script. Then i used your V2 modified version of the script and i'm getting the following error. (See attached image) Thank you for your time, would love to see if you are able to assist?

### ISSUE THREAD

**Issue by joebay** [instabot-py/instabot.py#924]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Python Version?
2 / 3

## Description

Type the description of your issue here.

```
Include the contents of the error.log here (if applicable).
```

**Comment by joebay** [comment]
![image](https://user-images.githubusercontent.com/13026025/35196566-d5e20aa4-fea1-11e7-926d-cf0ff890d926.png)

**Comment by ugurozturk** [comment]
Fill in all requirements before submitting an issue.
Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
If you fail to follow these simple instructions, we will close the ticket.
