### ISSUE TITLE
Documentation Errors

### ISSUE THREAD

**Issue by kabauterman** [instabot-py/instabot.py#926]
I really tried to understand what is going on here but it seems like this documentation here is so bad.

There are so much more variables in the scripts then pointed out here. 
If I just use the example it does basically nothing then unfollowing accounts, no matter what mode I use...

There are options in the scripts not documented in the scripts itself and not documented anywhere here on Github.

I really wish I could use this to its full potential but in its actual state it's useless.

How can I use the script JUST to follow people based on my recent feed. I tried to use "max unfollow per day = 0" then start the script and the first it does is unfollow someone...

This, follow for a certain time and then unfollow shortly doesn't work well, you need to follow and keep them a while to have the full potential.

Best done with one day, just follow, next day just unfollow, not to fast that you get banned but this worked best for my by hand so far.

hope you can help.

**Comment by stelstef** [comment]
I agree, the documentation is really bad. You cannot do anything other than the basic function of the script. In my case, I only managed to make it not follow/unfollow anyone and only like posts based on the hashtag list I provided.

**Comment by ugurozturk** [comment]
@kabauterman @stelstef Blaming others and just talking is a easy part. Move on and do code or write some "Documentation" then do PR. We will welcomed it.  Everything is clear and working fine on my eyes so i dont changing it. If you think something must change or something must be "fixed" then do yourself. Dont expect from others. This is Open Source project. You can fork, edit, upgrade then if you want to help original repo do PR.

**Comment by ugurozturk** [comment]
closing because https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md

**Comment by kabauterman** [comment]
What kind of answer is this?! We aren't blaming anyone but documentation is the main part of working together.

Even if I would fork this, I can't do anything with it because there is no documentation how the options are used and how it works.

I would write a Documentation if I would understand it from what is written in the code.

This is a inside job, even for someone who can code it is not an easy "look at it and you know whats going on" thats where a documentation becomes handy.

The options even don't work like they should, like I said above in "unfollow per day = 0" but still unfollowing....

Why is there even an issues page here when you say I should fix it by myself when I think it is broken... -.-

**Comment by stelstef** [comment]
It was not my intention to offend or blame anyone. The documentation is bad and that is a fact. Perhaps someone more knowledgeable than me will see this thread and decide that improving the documentation might be worth their time.

**Comment by ugurozturk** [comment]
@kabauterman `The options even don't work like they should, like I said above in "unfollow per day = 0" but still unfollowing....` so it is a bug then create a issue for to help the project. It is that easy. Also from first your comment `There are options in the scripts not documented in the scripts itself and not documented anywhere here on Github.` Create issues each of them for helping the project.

**Comment by ugurozturk** [comment]
@stelstef tell me if i am wrong. If you decise a thing to ugly then you must know the beauty. It is just like that. If you think the documentation is bad then you must seeing what is bad and what must change. Im pointing that. Just dont say it is bad. Also tell us what must change.
