### ISSUE TITLE
Skip "already followed before" from beginning

### ISSUE THREAD

**Issue by NodalPoint** [instabot-py/instabot.py#927]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
macOS High Sierra 10.13.2
## Python Version?
3

## Description

Type the description of your issue here.

It happens quite often that my bot follows the same people it followed before, even though I have quite a lot of tags set for it to target. For example:
_23.01.2018_20:54 Trying to follow: 320717724
23.01.2018_20:54 Followed: 320717724 #35.
23.01.2018_20:56 Already followed before 320717724_

If the bot knows that its already followed this person before, isn't there a way for it to just skip that person? I've looked for an answer but can't seem to find one.
Thanks in advance!

Include the contents of the error.log here (if applicable).
```

**Comment by ugurozturk** [comment]
@NodalPoint it is just says it already followed before then it does skip. Doesn't try to follow again. Yet, yeah it adds the time for next follow iteration. Right now it can't be like "removing already liked medias" feature. It is complex in the code. Anyway i will make this one look like feature request.

**Comment by NodalPoint** [comment]
@ugurozturk Ooh okay fair, cuz the follow count does still add up. That's why I was wondering about it. Thanks!

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
