### ISSUE TITLE
Cant run it on QPython on Android

### ISSUE THREAD

**Issue by Sudge3** [instabot-py/instabot.py#932]
- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Android 7.1.2

## Python Version?
2 / QPython

## Description

I get this out of the errors.log

> WARNING:root:Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.8
> Traceback (most recent call last):
> File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 154, in load
> for item in get_browsers(verify_ssl=verify_ssl):
> File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 97, in get_browsers
> html = get(settings.BROWSERS_STATS_PAGE, verify_ssl=verify_ssl)
> File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 84, in get
> raise FakeUserAgentError('Maximum amount of retries reached')
> FakeUserAgentError: Maximum amount of retries reached
> WARNING:root:Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.8
> Traceback (most recent call last):
> File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 154, in load
> for item in get_browsers(verify_ssl=verify_ssl):
> File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 97, in get_browsers
> html = get(settings.BROWSERS_STATS_PAGE, verify_ssl=verify_ssl)
> File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 84, in get
> raise FakeUserAgentError('Maximum amount of retries reached')
> FakeUserAgentError: Maximum amount of retries reached

And this out of executing the script

> /data/user/0/org.qpython.qpy/files/bin/qpython-android5-root.sh
> "/storage/emulated/0/qpython/instabot.py-master/main.py" && exit
> /instabot.py-master/main.py" && exit <
> Traceback (most recent call last):
> File "/storage/emulated/0/qpython/instabot.py-master/main.py", line 77, in 
> 'yuki_nishitani8','contemporary.paintings','danteslens','ramontrotman','voidcrack',])
> File "/storage/emulated/0/qpython/instabot.py-master/src/instabot.py", line 162, in init fake_ua = UserAgent()
> File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/fake.py", line 69, in init self.load()
> File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/fake.py", line 78, in load
> verify_ssl=self.verify_ssl,
> File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 250, in load_cached
> update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
> File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 245, in update write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
> File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 189, in load
> verify_ssl=verify_ssl,
> File "/data/user/0/org.qpython.qpy/files/lib/python2.7/site-packages/fake_useragent-0.1.8-py2.7.egg/fake_useragent/utils.py", line 84, in get
> raise FakeUserAgentError('Maximum amount of retries reached')
> fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
> 1|bullhead:/ $

Can someone tell me what is wrong? Have no issus on Windows or Mac

**Comment by ugurozturk** [comment]
@Sudge3 https://play.google.com/store/apps/details?id=org.qpython.qpy3&hl=tr can you try this one ? it is python3

**Comment by Sudge3** [comment]
@ugurozturk i tryed it but the app doesnt work properly. i cant even install requests on this one.

**Comment by ugurozturk** [comment]
@Sudge3 i have tested and it does working fine. Please use google for "module install on qpython3"

**Comment by Sudge3** [comment]
@ugurozturk then I get this 

```
/data/user/0/org.qpython.qpy3/files/bin/qpython-android5-root.sh "/storage/emulated/0/qpython/scripts3/.last_tmp.py" && exit
n/scripts3/.last_tmp.py" && exit               <
Input pip commands, ie: pip install {module}
-->pip install requests
Downloading/unpacking requests
  Running setup.py egg_info for package requests
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/storage/emulated/0/qpython/cache/pip-build/requests/setup.py", line 55, in <module>
        exec(f.read(), about)
      File "<string>", line 14
        __cake__ = u'\u2728 \U0001f370 \u2728'
                                             ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/storage/emulated/0/qpython/cache/pip-build/requests/setup.py", line 55, in <module>

    exec(f.read(), about)

  File "<string>", line 14

    __cake__ = u'\u2728 \U0001f370 \u2728'

                                         ^

SyntaxError: invalid syntax

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /storage/emulated/0/qpython/cache/pip-build/requests
Storing complete log in /sdcard/qpython/.pip/pip.log
-->
```

**Comment by ugurozturk** [comment]
@Sudge3 I dont know the errors. So please do google and if you find an correct answer from qpython forums, comment here. There must be something for it.

**Comment by snthe** [comment]
Just use Termux, it works without problem on my phone

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
