### ISSUE TITLE
TypeError: Can't convert 'int' object to str implicitly in sql_updates.py

### ISSUE THREAD

**Issue by bgokden** [instabot-py/instabot.py#934]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [X ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [X ] If so; have you tried running the code on your local machine?

#### Select one:
- [X ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Linux (ubuntu 16.04) It is running inside docker

## Python Version?
2.7

## Description

I get this error after running 2 days, on two bots nearly at the same time and it happened multiple times:

```
TypeError: Can't convert 'int' object to str implicitly
media_id +"','"+ status +"','"+ str(now) +"')")
```

This is the method that fails in sql_updates.py :

def insert_media(self, media_id, status):
    """ insert media to medias """
    now = datetime.now()
    self.follows_db_c.execute("INSERT INTO medias (media_id, status, datetime) VALUES('"+
                              media_id +"','"+ status +"','"+ str(now) +"')")

Somehow media_id or status returns as int.
Can we convert this line to 
str(media_id) +"','"+ str(status) +"','"+ str(now) +"')")

What do you think?

**Comment by ugurozturk** [comment]
@bgokden I do remember somehow somewhere the same error reported by other person. Proabby at my repo. Anyway, i do remember like whenever you change to str(media_id) then there comes others errors like other parameters in sql_updates.py. All needs to be converting to str. 

So the solution must be changing the method. 
from:
media_id +"','"+ status +"','"+ str(now) +"')")
to
%s, %s + %s") % media_id, status, str(now)

Yet the all functions must be change in sql_updates.py

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
