### ISSUE TITLE
Seems like tag blacklist is not doing anything

### ISSUE THREAD

**Issue by ntKarlsson** [instabot-py/instabot.py#935]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [X ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [X ] If so; have you tried running the code on your local machine?

#### Select one:
- [X ] Bug
- [ ] Feature Request
- [ X] Technical Help
- [ ] Other

### Operating System? (include version)
High Sierra 10.13.1

## Python Version?
2.7.10

## Description

Hi! I'm not sure if this is a bug. It might be something I just haven't figured out. I have few tags on tag list and few or more on blacklist. I have new_auto_mod running and it likes posts tagged with blacklisted items.

like_per_day=5000,
comments_per_day=0,
tag_list=['skyporn', 'cloudporn', 'sunset', 'horizon', 'sunrise', 'landscape', 'sunsetporn', 'sunsetlovers', 'skylovers', 'auroraborealis', 'northernlights'],
tag_blacklist=['muscle', 'warrior', 'menshealt', 'igdaily', 'instalike', 'smile', 'hipster', 'ink', 'animal', 'modernart', 'puppy', 'dog', 'pet', 'instadog', 'doggy', 'painting', 'poetry', 'words', 'me', 'garden', 'gardening', 'selfie', 'art', 'quotes' 'flower', 'gym', 'cars', 'car', 'girl', 'boy', 'couple', 'boyfiend', 'girlfriend', 'ootd', 'outfit', 'fashion', 'canvas', 'cute', 'baby', 'hair', 'model', 'modeling', 'eyes', 'portrait', 'wedding', 'dress', 'makeup', 'fitness', 'gamer', 'game', 'games', 'videogame', 'instamodel', 'instafashion', 'shark', 'photooftheday', 'potd', 'follow', 'followme', 'photo', 'follow4follow', 'f4f', 'selfies', 'meme', 'memes', 'guy', 'decoration', 'print', 'yoga', 'house', 'history', 'food', 'foodie', 'architecture', 'chat', 'cat', 'animals', 'igers', 'marijuana', 'cannabis' ],
    user_blacklist={},
    max_like_for_one_tag=500,
    follow_per_day=1000,
    follow_time=1 * 60,
    unfollow_per_day=0,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,

```
Include the contents of the error.log here (if applicable).
```

**Comment by ugurozturk** [comment]
Give us some example. Which photo did it like including one of the blacklisted tag ?

**Comment by ntKarlsson** [comment]
Okay!

https://www.instagram.com/p/BebaIAhhlmB/?hl=fi&taken-by=madamefro420
(art, painting)

https://www.instagram.com/p/BebaGQWnHPj/?hl=fi&taken-by=mrtnmfv
(photooftheday)

https://www.instagram.com/p/BebaICMAqpD/?hl=fi&taken-by=araammie
(architecture)

https://www.instagram.com/p/Bebemy-AqUE/?hl=fi&taken-by=gavincatophotography
(wedding)

Then there is bunch of these photos without any wanted tags but with blacklisted tags.

https://www.instagram.com/p/BebeLEeBT6J/?hl=fi&taken-by=tommy_h_hyndman
(selfie, eyes)

https://www.instagram.com/p/Beaxg3sFI9P/?hl=fi&taken-by=o._n._e._direction
(cute)

And photos without any of given tags.

https://www.instagram.com/p/BeVELR7lU-H/?hl=fi&taken-by=klaffenshus

**Comment by anthonycherbuin** [comment]
Hi,

So I spend some times on the code and it seem's like the problem come from this lines (instabot.py line 476):
`if (len(self.media_by_tag[i]['node']['edge_media_to_caption']['edges']) > 1):`
once i comment it it works well:
![image](https://user-images.githubusercontent.com/16646440/35487379-29cb1924-047b-11e8-99f2-405a6d394061.png)

But as I never coded Python and don't know the code exactly (yes I am a noob) I let somebody else modify that if it's the problem.
:)

**Comment by rcuel** [comment]
Hey ntKarlsson, I have the same issue, did you figure a workaround for this one?

**Comment by limerick11** [comment]
@anthonycherbuin is correct. Comment out that line of code and it will be fixed.

**Comment by rcuel** [comment]
On my instabot.py, the line described by @anthonycherbuin is the 475. I tried commenting it out only this part (line 475):
`if (len(self.media_by_tag[i]['node']['edge_media_to_caption']['edges']) > 1):`
But that crashes the whole program. Also, I tried to remove the whole if block (lines 475 to 478):
`                                if (len(self.media_by_tag[i]['node']['edge_media_to_caption']['edges']) > 1):
                                    caption = self.media_by_tag[i]['node']['edge_media_to_caption'][
                                        'edges'][0]['node']['text'].encode(
                                            'ascii', errors='ignore')
                                    tag_blacklist = set(self.tag_blacklist)`
That runs the program, but no likes are given...

**Comment by limerick11** [comment]
@rcuel This is what I did for instabot.py. Mine is working fine with no issues.

![image](https://user-images.githubusercontent.com/18040272/37490009-d1f9a6ca-286f-11e8-8441-1734d0a71e79.png)

**Comment by rcuel** [comment]
![image](https://user-images.githubusercontent.com/26209152/37492296-d1a46a62-286e-11e8-959d-11f8ce297522.png)
Awesome! That worked great, @limerick11 !!! Thanks a lot!

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
