### ISSUE TITLE
Bot is trying to unfollow for most of the time.

### ISSUE THREAD

**Issue by VKT16** [instabot-py/instabot.py#936]
- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows

## Python Version?
3

## Description

I am running the bot 10 hours per day locally on my PC, and at the end of the session I close the bot. I have set the bot to unfollow only and below are the commands I used:
 follow_time=48 * 60 * 60,
 unfollow_per_day=1901,
unfollow_break_min=45,
unfollow_break_max=75,

As you can see I have slightly increased the number of unfollows, hoping that it will unfollow more people, however after 10 hours of the bot being active, it has unfollowed 42 people only. For most of the time it has just been trying to unfollow account, but does not actually unfollow them. 

Can someone provide some help on this issue?

Thanks

**Comment by ugurozturk** [comment]
mode does only unfollow which bot did followed. Also do lower your unfollow_break_min and unfollow_break_max to default ones.
