### ISSUE TITLE
Mode 1: unfollow_whitelist

### ISSUE THREAD

**Issue by danielmayans** [instabot-py/instabot.py#937]
¿There is a way that the bot take care of my unfollow_whitelist? Not mode 0 I mean.

I put the bot on Mode 1, and it starts to unfollow all my unfollow_whitelist, so I had to stop it.

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md Fill in all requirements before submitting an issue. Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue. If you fail to follow these simple instructions, we will close the ticket.
