### ISSUE TITLE
"Trying to comment" issue- Technical help or bug?

### ISSUE THREAD

**Issue by isbn121** [instabot-py/instabot.py#938]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Windows
## Python Version?
2 / 3
Version 3
## Description

Type the description of your issue here.
Whenever I try to comment...It says "Trying to comment" in command prompt.

```
Include the contents of the error.log here (if applicable).
```
![capture](https://user-images.githubusercontent.com/15641647/35472238-60511022-0339-11e8-9299-ccdcb6a9015f.PNG)

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by jjfriend** [comment]
@ChipWolf ive got same error
