### ISSUE TITLE
Login Error. 1 Account function, the other not...

### ISSUE THREAD

**Issue by y9y** [instabot-py/instabot.py#939]
- [ x] I have searched for other issues with the same problem.

## Hosting
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [ x] Technical Help

### Operating System? (include version)
Windows / Linux

## Python Version?
3

## Description

**I cant login using my personal insta account. There comes the typical Login Error message.
If I try to login with a other account, it works fine. I have set different database. And I also tried
to use a vpn to have another IP adress. But it still doesnt work :(**

**If I login via Webbrower form same Computer, there is no problem with both accounts**

**Comment by mbz1** [comment]
I have the same issue, it seems like some kind of shadow ban.
Error occures first time 2 days ago. Any other apps (browser, android apk, unofficial apps) worked fine.
Yesterday I was able to login and everything was ok, today this error occures again (I didn't modify any line of code in source):

`31.01.2018_10:09 Instabot v1.2.0 started at 31.01.2018 10:09:`
`31.01.2018_10:09 Trying to login as (login)...`
`31.01.2018_10:09 Login error! Check your login data!`
`31.01.2018_10:09 Removing already liked medias..`
`31.01.2018_10:09 Trying to unfollow #1:`
`31.01.2018_10:09 Removing already liked medias..`
`31.01.2018_10:09 Removing already liked medias..`
`31.01.2018_10:09 Removing already liked medias..`

Changing user-agent in code not work.

**Comment by billionbucks** [comment]
@mbz1  Did you got it working?

**Comment by digital-bloom** [comment]
#980

**Comment by ri7nz** [comment]
Check username &. Your password , if you enable 2 step verification ,
disable it.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
