### ISSUE TITLE
No module named fake_useragent

### ISSUE THREAD

**Issue by mjedmonds** [instabot-py/instabot.py#942]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

Linux 14.04

## Python Version?
2 

## Description

Type the description of your issue here.

Failed to load UserAgent from fake_useragent module. Appears to be deleted in last few commits, but still is imported in instabot.py. 

```
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/home/x/instabot.py/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/home/x/instabot.py/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ImportError: No module named fake_useragent
```

**Comment by ugurozturk** [comment]
I have searched for other issues with the same problem. Please search better

**Comment by ugurozturk** [comment]
@mjedmonds the question answered more than 20 times yet i will answer it again. `pip install modulename`
