### ISSUE TITLE
'bool' object is not subscriptable

### ISSUE THREAD

**Issue by vladerlord** [instabot-py/instabot.py#943]
- [x ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows

## Python Version?
3

## Description

�[91m Already following , Skipping �[0m
2018-01-27 20:04:39,143 - INFO - Out of unfollows for today.
11%|████████████▏ | 99/910 [05:38<46:13, 3.42s/it]2018-01-27 20:04:39,399 - ERROR - Request return 429 error!
2018-01-27 20:04:39,399 - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.

2018-01-27 20:09:39,400 - INFO - error, read exception bellow
2018-01-27 20:09:39,401 - INFO - 'bool' object is not subscriptable

```
Include the contents of the error.log here (if applicable).

There is no such file.
```

**Comment by ugurozturk** [comment]
What mode ?

**Comment by vladerlord** [comment]
multi_script_CLI
4. Unfollow
1. Unfollow non followers

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
