### ISSUE TITLE
KeyError: 'owner' -- self.current_user = self.media_on_feed[chooser]["node"]["owner"]["username"] 

### ISSUE THREAD

**Issue by sidmouthwebdesign** [instabot-py/instabot.py#944]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Windows 10
## Python Version?
3

## Description

Type the description of your issue here.

28.01.2018_15:48 Media in recent feed = 12
Traceback (most recent call last):
  File "example.py", line 96, in <module>
    bot.new_auto_mod()
  File "F:\instabot.py\src\instabot.py", line 699, in new_auto_mod
    self.new_auto_mod_unfollow()
  File "F:\instabot.py\src\instabot.py", line 764, in new_auto_mod_unfollow
    unfollow_protocol(self)
  File "F:\instabot.py\src\unfollow_protocol.py", line 22, in unfollow_protocol
    self.current_user = self.media_on_feed[chooser]["node"]["owner"]["username"]
KeyError: 'owner'```

**Comment by Chippi** [comment]
This happens because the media_on_feed contains mixed object types. GraphSuggestedUserFeedUnit type has no owner" property.

I quick fixed this for myself by adding
```
if self.media_on_feed[chooser]["node"]["__typename"] == "GraphSuggestedUserFeedUnit":
    return;
```
to line 22.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
