### ISSUE TITLE
Unfollow_Protocol Mode 5

### ISSUE THREAD

**Issue by SamMwatha** [instabot-py/instabot.py#945]
Description
Code works perfectly! But on the Unfollow Protocol, how can I set it so that after a certain amount of Unfollowing to sleep and continue once the sleep is over then end?
![code](https://user-images.githubusercontent.com/24208984/35485146-27ca640e-046c-11e8-951b-87f256ba112f.JPG)

**Comment by ugurozturk** [comment]
https://github.com/instabot-py/instabot.py/blob/master/ISSUE_TEMPLATE.md
