### ISSUE TITLE
Cookie file not found, creating cookie...

### ISSUE THREAD

**Issue by theRouter** [instabot-py/instabot.py#948]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
windows
## Python Version?
2 / 3
3
## Description

Type the description of your issue here.

i run bot and it worked . but today i cant login and it shows me this : Cookie file not found, creating cookie...
what can i do?
Include the contents of the error.log here (if applicable).
```

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
