### ISSUE TITLE
like recent photo of a specific list of usernames

### ISSUE THREAD

**Issue by bahabannour** [instabot-py/instabot.py#950]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Windows 7 familial edition
## Python Version?
2 / 3
3
## Description

How to make the bot go to every username from a list and like the recent picture posted by each one of the usernames ?
thank you.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
