### ISSUE TITLE
How do you stop the bot following private users?

### ISSUE THREAD

**Issue by Kyozaki** [instabot-py/instabot.py#954]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 10

## Python Version?
3.6

## Description

Consistently, when using instabot to follow users, it follows both public and private users. This was previously reported here (issue 703) 

https://github.com/instabot-py/instabot.py/issues/703
and was closed, but the issue still occurs. See the attached screenshot, where the bot has a followed an account, which is private. I have also included the output of when this occurs. 

The bot identifies the account as private, but then follows it anyway.
Thanks

K'+
![capture](https://user-images.githubusercontent.com/32878380/35563458-ffb99f42-05b6-11e8-96ca-63a19693645d.PNG)

```
Include the contents of the error.log here (if applicable).
```

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
