### ISSUE TITLE
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com

### ISSUE THREAD

**Issue by loooping** [instabot-py/instabot.py#955]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Linux Ubuntu (16.04 LTS)

## Python Version?
2

## Description

try running `python example.py` I getting this errors
In my local machine OK
Problem occur in VPS (Google Cloud)
VPS in other country!

```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.instagram.com
```

**Comment by loooping** [comment]
Solved in other vm with same configs :S

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
