### ISSUE TITLE
Follow users based on tags

### ISSUE THREAD

**Issue by Drivium** [instabot-py/instabot.py#956]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 7 SP1

## Python Version?
2

## Description

Is it possible to follow users based on a tag?  For example, it finds every user that's used a specific tag and follows that user.  Many follow floods/groups use tags as criteria as to whether they should follow or not.  If this is already implemented, please describe how I can achieve this.  If it is not, please include this as a feature request.  Thanks in advance!

**EDIT1: Upon further review, it looks like this may be what I'm after:
get_media_id_by_tag(tag) | Add photos with a given tag to like queue 

Researching further...

**EDIT2: No, this only "Likes" photos where that tag exists.  I need it to follow user where that tag exists.

**EDIT3: Someone here also mentions wanting the ability to follow/unfollow based on tags: https://github.com/instabot-py/instabot.py/pull/229
```
Include the contents of the error.log here (if applicable).
```

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
