### ISSUE TITLE
ImportError: No module named src

### ISSUE THREAD

**Issue by Sheacraft** [instabot-py/instabot.py#958]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC 10.12.6

## Python Version?
3

## Description

ImportError: No module named src
Ive installed requirements 
Ive tried pip3 install request
i moved the example file into the src
That Resolved the other errors 

Any other ideas?

```
IMac-iMac:src IMac$ python example.py 
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
ImportError: No module named src
```

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
