### ISSUE TITLE
Verification loop - Login error! Connection error!

### ISSUE THREAD

**Issue by sopissedoff** [instabot-py/instabot.py#959]
- [X ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ X] If so; have you tried running the code on your local machine?

#### Select one:
- [X ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
 Linux Ubuntu 
## Python Version?
3

## Description

Verification loop tried fixing for hours on end. Just so stressed rn trying to fix this. I have gone to every singlie issue with this thread and have seen this error multiple times. The devs on here keep closing the issue before it is finished or give no explenation on how to fix. Please please please help me fix this. Bot worked fine for 4 days then I started it up again and get

Login error! Connection error!
Removing already liked medias...
Trying to unfollow #1 
Looks like there is nobody to unfollow
Removing already liked medias...
Removing already liked medias...
Removing already liked medias...
Removing already liked medias...

I have no idea how to fix this. I have not tried using a vpn, I am running on ubuntu off my normal ip. Just so mad rn can anyone PLEASE help me with this!!!! VERIFICATION LOOOP keep going on my whone says was this you? Suspisous login I click yes this was me try again same error. I have tried fake user agent nothing works.

**Comment by tunidev** [comment]
I get the same

**Comment by jzos** [comment]
Are you logging in and out frequently in a certain period of time? I currently have my user-agent identical to my instabot app as my web browser, figuring it would think I was using the same web browser. Also, I use a proxy for my app and my web browser, so that way if I log in manually through Chrome, the proxy matches what I have on my app. 

I'm asking if you have been logging in and out frequently, because it was working great earlier and it just started giving me the verification loop, maybe because I was logging in and out frequently.

**Comment by tunidev** [comment]
I solved the issue by:

1. logout from the browser 
2. Tried to login from the browser 
3. I coud't login
4. I have changed the password and logged in from the browser
5. changed the script to use new password and the same user agent as the browser
6. It works ;)

**Comment by jzos** [comment]
Great! Funny, I actually did that it and it worked earlier. Thanks for validating though!!

**Comment by sopissedoff** [comment]
wow great to know that works! I just started hosting on a cloud! :)

**Comment by sopissedoff** [comment]
Now im getting the error on my FUCKING CLOUD SERVER FUCK INSTAGRAM

**Comment by sopissedoff** [comment]
PLEASE PLEASE tell me how to edit the user agent I CANT FIND IT ANYWHERE

**Comment by n0mar** [comment]
@sopissedoff I believe you can change your user-agent within the `userinfo.py` in the `src` directory.

Line 11:

     user_agent = 

Simply doing a Google search of “what is my user agent” will show you yours for your current browser. Delete, copy, paste.

**Comment by mdrzn** [comment]
Tried changing my user agent to match my browser from where I added the security code, the bot still fails to login and the verification loop continues.

**Comment by dad518** [comment]
I have tried all the above, still easily log in with on my iphone or laptop via browser.  Just cannot get the bot to run

**Comment by marioaugustorama** [comment]
Wait more than 4 hours and try again, i had the same problem!

Em dom, 18 de fev de 2018 às 09:56, dad518 <notifications@github.com>
escreveu:

**Comment by mdrzn** [comment]
I've waited 24hrs (haven't logged in from the server since yesterday), tried right now, it worked.
Weird.

**Comment by digital-bloom** [comment]
i waited 24hrs+ and still have no luck... :(

**Comment by digital-bloom** [comment]
I GOT IT! 

go to your python folder and run Install Certificates.command

this will resolve SSL Verification errors

**Comment by digital-bloom** [comment]
#980

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
