### ISSUE TITLE
Userinfo.py

### ISSUE THREAD

**Issue by carlisillo** [instabot-py/instabot.py#961]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC

## Python Version?
2

## Description

I was looking over the Userinfo.py file and I can't get to make it work if I call the functions inside of it. When I run the code below, it brings back zero followers in the list:
----------------------------------

import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol
from src.user_info import get_user_info
from src.userinfo import UserInfo

bot = InstaBot(
    login="mistelkind",
    password="carli3510",
    like_per_day=10,
    comments_per_day=0,
    tag_list=['reggaeton','trap','latintrap','badbunny','DaddyYankee'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=300,
    follow_time=1*20,
    unfollow_per_day=300,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])

while True:
	mode = 0
	#get_user_info(bot,"mistelkind")

	# example
	ui = UserInfo()

	# search by user_name:
	ui.search_user(user_name="mistelkind")
	print(ui.user_name)

	# get followers list
	ui.get_followers()
	followers = ui.followers
	
	#Create empty lists
	endlist = []
	followerslist = []

	#get followers id
	for item in followers:
	    followerslist.append(item['id'])
 	endlist=set(followerslist)
 	#use instabot

	print('Number of unnecessary subscriptions:', len(endlist), '\n')
	exit()
----------------
```
The Log is returning: Number of unnecessary subscriptions: 0
```

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
