### ISSUE TITLE
Follow users from specific country based on a predefined code

### ISSUE THREAD

**Issue by atiqkhan26** [instabot-py/instabot.py#962]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC 10.13 / Linux Ubuntu 16.04

## Python Version?
3

## Description
Most users would like to engage with users from their own country or a specific set of countries. Is there any configuration which can be used to achieve this. If not, can it be added please.
The country codes can be based on this http://www.b3rn3d.com/blog/2014/03/05/tor-country-codes/

```
Include the contents of the error.log here (if applicable).
```

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
