### ISSUE TITLE
Media Already Commented - Error

### ISSUE THREAD

**Issue by KalanaPerera** [instabot-py/instabot.py#964]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 8

## Python Version?
3

## Description

From last week Im facing issue called " Media Already Commented. Even I use new hashtags that error is coming. 

Here is the error Screenshot: https://imgur.com/a/BwxzC

```
Include the contents of the error.log here (if applicable).
```

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
