### ISSUE TITLE
Not leaving comments ?

### ISSUE THREAD

**Issue by LoneWolfsMoon** [instabot-py/instabot.py#965]
![screenshot at 2018-02-05 12-48-31](https://user-images.githubusercontent.com/30674228/35805257-09df43e4-0a73-11e8-9ccd-6934c704d2bb.png)

**Comment by KalanaPerera** [comment]
im also having same issue

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by EyezGlazed** [comment]
Same here. 500+ likes and quite a few follows, but 0 comments. Every time. It's not even trying to leave comments like in the image above.
