### ISSUE TITLE
Except on get_media!

### ISSUE THREAD

**Issue by vedsarkar** [instabot-py/instabot.py#966]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
windows 10

## Python Version?
3.6

## Description
Type the description of your issue here.
when trying to search tags the bot send Except on get_media!, tried to use different tags too did not help same result always. I have been using it since past few months and this started 3 days ago.
```
Include the contents of the error.log here (if applicable).
```

**Comment by corriejgreen** [comment]
its dead jim! get the same issue.

**Comment by Ledjob** [comment]
same here.

**Comment by marioaugustorama** [comment]
Wait 4 hours or more and try again.

Em 15/02/2018 10:24, "Ledjob" <notifications@github.com> escreveu:

**Comment by trenerok** [comment]
I have the same problem

**Comment by napster2091** [comment]
you need to change the code because JSON is changed when you try to get_new_media

all_data = json.loads(r.text)
self.media = list(all_data['graphql']['hashtag']['edge_hashtag_to_media']['edges'])

the posts now are under the:
['graphql']['hashtag']['edge_hashtag_to_media']['edges']

**Comment by trenerok** [comment]
Easy way. Update to latest version resolved this problem.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
