### ISSUE TITLE
Follow bot is failing due to HTTP resp code 400

### ISSUE THREAD

**Issue by abhilater** [instabot-py/instabot.py#967]
### Operating System? (include version)
MAC 

## Python Version?
2 

## Description

Type the description of your issue here.
The user follow api call is failing everytime with HTTP status code 400
Example API call HTTP POST https://www.instagram.com/web/friendships/3134506058/follow/
Response code 400

```
Trying to follow: 3134506058
API call HTTP POST https://www.instagram.com/web/friendships/3134506058/follow/
Response code 400
```

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
