### ISSUE TITLE
stops bot from running automaticaly

### ISSUE THREAD

**Issue by iamguido** [instabot-py/instabot.py#970]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Raspberry pi3

## Python Version?
 3

## Description

Someone has a problem that stops the bot from running automaticaly after upgrade instagram V31.0?
No error in Python Shell.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
