### ISSUE TITLE
Unsuccessful login along with secure mode

### ISSUE THREAD

**Issue by riccardorighettiphoto** [instabot-py/instabot.py#971]
Hello,
when the secure login mode (which sends a OTP by SMS) is ON, the script fails to login, so I should de-activate that feature, which I don't want.
Have you a fix to bypass? Thank you.

**Comment by ltd9938** [comment]
Pretty sure you need 2FA off for the script to work.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
