### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by Pantic14** [instabot-py/instabot.py#973]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)

Linux Ubuntu 17.10
## Python Version?

2.7.14
## Description
Script stop in mod=0.

```
Traceback (most recent call last):
  File "juguetes20.py", line 74, in <module>
    bot.new_auto_mod()
  File "/home/pantic/Escritorio/SocialMedia/Bots/Instagram/instabot.py-master/src/instabot.py", line 697, in new_auto_mod
    self.new_auto_mod_follow()
  File "/home/pantic/Escritorio/SocialMedia/Bots/Instagram/instabot.py-master/src/instabot.py", line 740, in new_auto_mod_follow
    if check_already_followed(self, user_id=self.media_by_tag[0]['node']["owner"]["id"]) == 1:
  File "/home/pantic/Escritorio/SocialMedia/Bots/Instagram/instabot.py-master/src/sql_updates.py", line 60, in check_already_followed
    user_id + "' LIMIT 1)").fetchone()[0] > 0:
sqlite3.OperationalError: database is locked

```

**Comment by iamguido** [comment]
same error.

**Comment by enriqueg** [comment]
File "/Users/MC/Documents/eneida/example.py", line 74, in <module>
    bot.new_auto_mod()
  File "/Users/MC/Documents/eneida/src/instabot.py", line 695, in new_auto_mod
    self.new_auto_mod_like()
  File "/Users/MC/Documents/eneida/src/instabot.py", line 723, in new_auto_mod_like
    if self.like_all_exist_media(media_size=1, delay=False):
  File "/Users/MC/Documents/eneida/src/instabot.py", line 524, in like_all_exist_media
    status="200")
  File "/Users/MC/Documents/eneida/src/sql_updates.py", line 68, in insert_media
    media_id +"','"+ status +"','"+ str(now) +"')")
sqlite3.OperationalError: database is locked

**Comment by 5509** [comment]
@Pantic14 @iamguido @enriqueg Are you running multiple accounts? I had the same error with multiple accounts and runnings.

In this situation, I need to create `*.db` files each account and make sure each execution with `database_name` option.

**Comment by luciatseng** [comment]
@5509 Can you elaborate? I can’t find any existing *.db files to copy

**Comment by kidd0ua** [comment]
in the root directory I have only follows_db.db database file. My bot still continues fails. Any consideration?

**Comment by josuegonzalezm** [comment]
@Pantic14 Sorry could you explain me again, because i don't find the database:name and i don't understand if thistle i need to duplicad the file and change the name

Thank !

**Comment by S0lak** [comment]
I have the same problem, can anybody help? thanks in advance

**Comment by luciatseng** [comment]
@josuegonzalezm @S0lak What I do is duplicate the code folder. For example, have an instabot.py folder, and an instabot2.py folder.

**Comment by 5509** [comment]
@josuegonzalezm @S0lak 

I hope these images solve your problems.

---

### 1. Duplicate and rename `.db` files

as many as Instagram account that you want to execute

<img width="114" alt="2018-04-06 11 00 14" src="https://user-images.githubusercontent.com/521075/38400267-519852ac-398a-11e8-8d2d-0176d4fb498e.png">

### 2. Rewrite `database_name` in each execution files.

#### example.py

<img width="287" alt="2018-04-06 11 01 06" src="https://user-images.githubusercontent.com/521075/38400268-51d64fee-398a-11e8-9711-d6bc9f24a144.png">

#### example2.py

<img width="304" alt="2018-04-06 11 01 39" src="https://user-images.githubusercontent.com/521075/38400269-52167b14-398a-11e8-8c68-34f8f6380daf.png">
