### ISSUE TITLE
Follow_time command does not seem to do its job.

### ISSUE THREAD

**Issue by VKT16** [instabot-py/instabot.py#974]
## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows

## Python Version?
3

## Description

Type the description of your issue here.

Hi, 
I have used the command "follow_time=72 * 60 * 60" to set the bot to wait 72 hours before unfollowing the account it has followed. The bot however does not wait 72 hours but unfollows the accounts very shortly after it has followed. Can anyone tell me if I am doing anything wrong or improve this feature? 

P.s. I am using logmod 0. 

Thanks

**Comment by fab976** [comment]
same for me

**Comment by dpereira411** [comment]
same

**Comment by 5ergi0** [comment]
Same for me. It starts to follow an account and 2 hours and 5 minutes later it unfollows the account. I want it waits 24 hours to start unfollowing. I have used ''24 * 60 * 60''.

I am using log_mod 0 too.

Thanks.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
