### ISSUE TITLE
Mode 0: Bot executes 1 like and comment and then hangs (multiple attempts)

### ISSUE THREAD

**Issue by econn9** [instabot-py/instabot.py#975]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting? no im hosting locally
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug

### Operating System? (include version)
MAC 10.13.2

## Python Version?
2.7.13 

## Description

Multiple attempts to start in mode 0 ... each time it only likes and comments 1 post and then hangs ... when i exit the program it throws on instabot.py 703 where it mentions sleep(3) which it should only sleep for 3 seconds ... ive waited many minutes and it still doesnt continue working. i have it set to do about 80 comments and 300 likes on a simple set of tags

```
15.02.2018_15:51 **** login success!
15.02.2018_15:51 Get media id by tag: ****
15.02.2018_15:51 Removing already liked medias..
15.02.2018_15:51 Trying to like media: ****
15.02.2018_15:51 Liked: ****. Like #1.
15.02.2018_15:51 Trying to comment: ****
15.02.2018_15:51 Write: "****". #1.
^CTraceback (most recent call last):
  File "example.py", line 61, in <module>
    bot.new_auto_mod()
  File "/Users/eugeneconnor/yoshi/bot/instabot.py/src/instabot.py", line 703, in new_auto_mod
    time.sleep(3)
KeyboardInterrupt
```

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
