### ISSUE TITLE
Like time is slow

### ISSUE THREAD

**Issue by boyinwonder** [instabot-py/instabot.py#976]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Python Version?
2 / 3

## Description

Type the description of your issue here.

```
Include the contents of the error.log here (if applicable).
```
Hey guys, I was wondering if there was a code to increase like time in the day. I set my likes for 1500 a day, but it takes around 2 days to complete. Please let me know!

**Comment by dekhogaurse** [comment]
I would like help with this too! 
It's very slow; which part of the code should I edit?

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
