### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by carlosisazadotlife** [instabot-py/instabot.py#979]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
AWS
- [x] If so; have you tried running the code on your local machine?
Yes, local machine works fine. It was working fine until saturday morning.

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
ubuntu-xenial-16.04-amd64-server

## Python Version?
2.7.12

## Description
Getting message on instagram applicacion and website about suspicious login. Even though i verify it's me the script just says connection error and stays there.

Like i said it was working fine till saturday morning, the first time i ran the script i got the same question on site, worked just fine after verification.

No double verification on instagram checked btw.

<img width="570" alt="screen shot 2018-02-18 at 7 18 00 pm" src="https://user-images.githubusercontent.com/36576995/36358718-c45bcc98-14e0-11e8-922a-cb01a96cfd95.png">

<img width="491" alt="screen shot 2018-02-18 at 7 18 25 pm" src="https://user-images.githubusercontent.com/36576995/36358719-c4700cda-14e0-11e8-9ee9-82c2e2d418a5.png">

**Comment by digital-bloom** [comment]
#980

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
