### ISSUE TITLE
"Verification Loop"/Fake UserAgent Error/SSLError (FIXED)

### ISSUE THREAD

**Issue by digital-bloom** [instabot-py/instabot.py#980]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so; have you tried running the code on your local machine?

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC 

## Python Version?
2 / 3

## Description
Bot has recently been giving out this error for what i believe to only be mac users. i found the fix. i made a new thread because users were all over the place looking for answers. 

###FIX:
Python 3.6 on MacOS uses an embedded version of OpenSSL, which does not use the system certificate store. More details [here](https://bugs.python.org/issue28150).

(To be explicit: MacOS users can probably resolve by [opening Finder and double clicking Install Certificates.command](https://i.stack.imgur.com/bWgpe.png))

Type the description of your issue here.

```
```WARNING:fake_useragent:Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.8
Traceback (most recent call last): 
.....................................................................................................................................
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
```

**Comment by ri7nz** [comment]
you can try this for fake_useragents

```python
ua = fake_useragent(verify_ssl=False)
```

**Comment by DJuiceBoi** [comment]
20.02.2018_12:34 Login error! Check your login data! 20.02.2018_12:34 Removing already liked medias.. 20.02.2018_12:34 Trying to unfollow #1: 20.02.2018_12:34 Looks like there is nobody to unfollow. 20.02.2018_12:34 Removing already liked medias..
I tried everything on here but I still get infinite removing already liked medias... Is this bad?

**Comment by ri7nz** [comment]
your account not logged in , check your username and password

**Comment by ri7nz** [comment]
can you give me  error ?

**Comment by eXistenZ** [comment]
The error.log is empty, all I see is this:

22.02.2018_04:57 Login error! Connection error!
22.02.2018_04:57 Removing already liked medias..
22.02.2018_04:57 Trying to unfollow #1:
22.02.2018_04:57 Looks like there is nobody to unfollow.
22.02.2018_04:57 Removing already liked medias..

**Comment by eXistenZ** [comment]
It worked now after I changed line 163 in instabot.py to:

self.user_agent = ("" "")

**Comment by tomckiswe** [comment]
Didn't change issue for me, The login returns a html page, not sure what it want to show me, maybe a confirmation dialog. Cannot confirm.

**Comment by tcplusplus** [comment]
Didn't change issue for me, The login returns a html page, not sure what it want to show me, maybe a confirmation dialog. Cannot confirm.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by mistrbeard** [comment]
chipwolf is a whore
