### ISSUE TITLE
Instabot login + app login at the same time: (correct) password error!

### ISSUE THREAD

**Issue by taradell** [instabot-py/instabot.py#983]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 

## Python Version?
3

## Description

I cannot login on both Instagram app AND any web browser from PC - wrong password error even if the password typed is correct; the bot cannot correctly login on my account and work.
By changing the password from web browser, the login from Instagram app is disabled (and viceversa)

```
Include the contents of the error.log here (if applicable).
```

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
