### ISSUE TITLE
URGENT!! mode 5 unfollowing same user called hajka and in mode 0 unfollowing abcd all the time

### ISSUE THREAD

**Issue by alyysaafan** [instabot-py/instabot.py#985]
Instabot v1.1.0 started at 20.02.2018 19:18:

Trying to login as creating_ella...

creating_ella login success!
creating_ella : Get media id on recent feed 
 20.02.2018 19:18
Except on get media!!
xxxxxxx user info list is empty!!! xxxxxxxxx
creating_ella : Get media id on recent feed 
 20.02.2018 19:18
Except on get media!!
======> Get media id by Tag <======
XXXXXXX Except on get_media! XXXXXXX
creating_ella : Get user info 
20.02.2018 19:19
Checking user info..
Follower : 156
Following : 377
Media : 457
   >>>This is a normal account
   >>>This user is active
   >>>This account is NOT following you
   >>>You are NOT following this account
======> Get media id by user: hajka <======
Get media by user success!
creating_ella : Get user info 
20.02.2018 19:20
Checking user info..
Follower : 156
Following : 377
Media : 457
   >>>This is a normal account
   >>>This user is active
   >>>This account is NOT following you
   >>>You are NOT following this account
======> Get media id by user: hajka <======
Get media by user success!
creating_ella : Get user info 
20.02.2018 19:20
Checking user info..
Follower : 156
Following : 377
Media : 457
   >>>This is a normal account
   >>>This user is active
   >>>This account is NOT following you
   >>>You are NOT following this account
======> Get media id by user: hajka <======
Get media by user success!
creating_ella : Get user info 
20.02.2018 19:21
Checking user info..
Follower : 156
Following : 377
Media : 457
   >>>This is a normal account
   >>>This user is active
   >>>This account is NOT following you
   >>>You are NOT following this account
======> Get media id by user: hajka <======
Get media by user success!
creating_ella : Get media id on recent feed 
 20.02.2018 19:21
Except on get media!!
======> Get media id by Tag <======
XXXXXXX Except on get_media! XXXXXXX
============================== 
Upss hajka is already in ex user list... 
==============================

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
