### ISSUE TITLE
Is removing already liked medias bad? How do I fix it?

### ISSUE THREAD

**Issue by DJuiceBoi** [instabot-py/instabot.py#986]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

## Python Version?
2 / 3

## Description

Type the description of your issue here.
Technical Help
MacOS: 10.13.3 (17D47)
Python: 2.7

20.02.2018_12:34 Login error! Check your login data! 20.02.2018_12:34 Removing already liked medias.. 20.02.2018_12:34 Trying to unfollow #1: 20.02.2018_12:34 Looks like there is nobody to unfollow. 20.02.2018_12:34 Removing already liked medias..
Include the contents of the error.log here (if applicable).
 Is this removing my likes? How do I fix it?

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by Corleanus** [comment]
Dude, why are you closing issues, and not giving an answer?
