### ISSUE TITLE
proxy / VPS question...

### ISSUE THREAD

**Issue by FrankieV26** [instabot-py/instabot.py#987]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

### Operating System? (include version)
MAC

## Python Version?
3

## Description

After following instructions, specifically on issue 71, I still can't seem to use a proxy on my password protected proxy. I changed 'proxy' on line 27 from '' to 'username:password@ipaddress:port', but it still doesn't take. Am I using a bad proxy? I am using purchased instagram proxy from highproxies.com.

Also, is there much of a difference between using VPS and proxy? Should I be using both at the same time if I do decide to use VPS? How safe is it?

Thank you for answering my noob questions. Any help at all is greatly appreciated.
```
Include the contents of the error.log here (if applicable).
```
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/admin/Desktop/instabot.py-master/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/admin/Desktop/instabot.py-master/src/instabot.py", line 281, in login
    r = self.s.get(self.url)
  File "/Users/admin/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Users/admin/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/admin/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/admin/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 502, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(54, 'Connection reset by peer')))

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!

**Comment by FrankieV26** [comment]
I figured it out. Thanks man

**Comment by Rick1998** [comment]
how
