### ISSUE TITLE
recent feed link is not working or deprecated

### ISSUE THREAD

**Issue by alyysaafan** [instabot-py/instabot.py#988]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC 

## Python Version?
2 / 3

## Description

every time i run this recent feed link found in the bot 
https://www.instagram.com/?__a=1
it returns this
 {"graphql":null}
and actually this is happening on one instagram account only the others is working properly!

**Comment by Stepyon** [comment]
The same for me, works for my private account but stopped to work on my business account.

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
