### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by mighty2nyce** [instabot-py/instabot.py#990]
> Fill in all requple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
mac
## Python Version?
2 / 3
3
## Description

i keep getting "Login error! Check your login data!" all of my information is right. i downloaded a new version and tried it again and its still not working. im not sure what to do. 
```
Include the contents of the error.log here (if applicable).

21.02.2018_13:00 Instabot v1.1.0 started at 21.02.2018 13:00:

21.02.2018_13:00 Trying to login as raw_shotography...

21.02.2018_13:00 Login error! Check your login data!
21.02.2018_13:00 Removing already liked medias..
21.02.2018_13:00 Trying to unfollow #1:

**Comment by mighty2nyce** [comment]
This is what i am getting when i use your version of instabot. can you please help

Matthews-MBP:instabot.py-master KoachMkNair$ python example.py 
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/KoachMkNair/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/KoachMkNair/Desktop/instabot.py-master/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ImportError: No module named fake_useragent
Matthews-MBP:instabot.py-master KoachMkNair$

**Comment by TehJokeR** [comment]
mighty2nyce you need to install the `fake-useragent` module

You can use the following to install it to your default python installation:

`sudo python -m pip install fake-useragent`

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
