### ISSUE TITLE
Get shadow banned

### ISSUE THREAD

**Issue by bboy519** [instabot-py/instabot.py#992]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ x] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Android 7.0
## Python Version?
2 / 3
2
## Description
Getting shadow banned in only 2 hrs. Tried it on 2 accounts and got the same result. Light bot(350 FL 500likes). Instagram has gone better at bot detection. (My local ig and vps use the same IP address.)
Need a random action delay feature. Taking action at the same frequency ( like & follow & comment) may be the reason get banned.
Type the description of your issue here.

```
Include the contents of the error.log here (if applicable).
```

**Comment by napster2091** [comment]
do you use random.randInt() function to generate the delay after like or follow or unfollow?

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
