### ISSUE TITLE
Bot logout without error after 5 days 

### ISSUE THREAD

**Issue by tunidev** [instabot-py/instabot.py#993]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
 Linux 

## Python Version?
2 / 3

## Description

 Why the bot logout without error after 5 days. Can I change that configuration to keep it running for ever ?

**Comment by napster2091** [comment]
i think the code raised an exception(some error happened) and your app entered to logout method
