### ISSUE TITLE
New Feature - Follows and Likes based on location

### ISSUE THREAD

**Issue by JMDevelopers** [instabot-py/instabot.py#994]
Hi Guys,

I was wondering if I can get any help on implementing a new mode/feature where we can get the bot to follow users and like their post that is based in a specific location; like a town or country.

Let's take full advantage of this forum in order to make this happen :D 

Peace,

**Comment by napster2091** [comment]
you need to retrieve the location code using the search link:

'https://www.instagram.com/web/search/topsearch/?context=blended&query=%s'
in %s you need to put the location name

looking the json you retrieve the location id

you need to use https://www.instagram.com/explore/locations/%s/?__a=1
putting the location code at %s place

you will have the json list of all the posts in that location and the owners of these posts.

i advise you to use the JSON viewer google chrome component that will format the JSON for a better reading

**Comment by faizalshuriken** [comment]
I'm looking for the same feature as you.There has been an effort in the past to integrate this feature.

Check it here; https://github.com/instabot-py/instabot.py/pull/508

But it seems to be outdated and no longer working.I've tried it out and there's error when I run it.

Traceback (most recent call last):
  File "example.py", line 9, in <module>
    from check_status import check_status
  File "C:\Users\xyz\Downloads\instabot.py-master\src\check_status.py", line 3, in <module>
    from .user_info import get_user_info
ImportError: attempted relative import with no known parent package

**Comment by MatheusParanhos** [comment]
@napster2091 Ok, thanks for that. I'm kinda struggling with this one because I want to retrieve users from a certain location using the tags that I mentioned. How would this be achieved? thanks

**Comment by andrewsegas** [comment]
Guys, Here we have follow and like by location + user interface
https://github.com/andrewsegas/instaboost

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
