### ISSUE TITLE
Unfollow Inactive Users

### ISSUE THREAD

**Issue by jdeplato** [instabot-py/instabot.py#995]
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Linux - Ubuntu Server 16.x

## Python Version?
3

## Description

Would like a new feature whereby the BOT can automatically unfollow users who have been inactive for a certain time period (1 Month, 2 Months, 3 Months, etc...). Inactive would be defined as a user who has not made a post in the allotted time-frame.

```
Include the contents of the error.log here (if applicable).
```

**Comment by napster2091** [comment]
Just open the desidered profile, check the Json of the last posted picture using the link:

Www.instagram.com/p/"piccode"/?__a=1

You find the piccode using the link:

Www.instagram.com/"username"/?__a=1

Executing the piccode link i posted before you we will find the value: "taken_at_timestamp:

Comparing this value with the time you want after that a user is inactive and you can unfollow the user

You will find the userid in the same Json where you found the timestamp

**Comment by ChipWolf** [comment]
If this is still an issue, please open a new issue. Thanks!
